//@@<< FB
// ***************************************************************
// *
// *                    ILunghezza_chiaviMgr.java Generated by
// *                 Computer Associates International, Inc.
// *
// *    Class: ILunghezza_chiaviMgr
// *    Package: it.cnr.contab.config00.comp
// *    Date:  Jul 23, 2001 3:24:20 PM
// *    User:  coola01
// *
// *    Copyright 2000, Computer Associates International, Inc.
// *    All rights reserved.
// *
// ***************************************************************
// *
// * Change History
// *
// * Initials    Date       Comments
// *+--------+------------+--------------------------------------------------
//@@>> FB
// *|        |            |
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------

package it.cnr.contab.config00.comp;
import it.cnr.jada.UserContext;
import it.cnr.jada.comp.ComponentException;
public interface ILunghezza_chiaviMgr
{




/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      formatta la chiave di un Capoconto
 */
        public String formatCapocontoKey (UserContext userContext,String key,Integer esercizio) throws ComponentException;

/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      formatta la chiave di un CONTO
 */
        public String formatContoKey (UserContext userContext,String key,Integer esercizio) throws ComponentException;

/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      formatta una generica chiave
 */
        public String formatKey (UserContext userContext,String key,Integer esercizio,String tabella,Integer livello,String attributo) throws ComponentException;

/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      aggiunge caratteri '0' a sinistra di un astringa fino a raggiungere la lunghezza specificata
 */
        public String leftPadding (String key,int keyLen);


/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      Estrae da una chiave completa di una organizzazione i primi n caratteri che corrispondono al codice CDS
 */
        public String extractCdsKey (UserContext userContext,String key) throws ComponentException;

/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      estrae da una chiave completa di una organizzazione gli n caratteri che corrispondono al codice UO
 */
        public String extractUoKey (UserContext userContext,String key) throws ComponentException;

/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      formatta la chiave di un Cdr
 */
        public String formatCdrKey (UserContext userContext,String key,Integer livello) throws ComponentException;

/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      formatta la chiave di un Cds
 */
        public String formatCdsKey (UserContext userContext,String key) throws ComponentException;

/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      formatta la chiave di una LINEA ATTIVITA'
 */
        public String formatLinea_attivitaKey (UserContext userContext,String key) throws ComponentException;

/**
  *  normale
  *    PreCondition:
  *      .
  *    PostCondition:
  *      formatta la chiave di una Unita Organizzativa
 */
        public String formatUoKey (UserContext userContext,String key) throws ComponentException;
}
