package it.cnr.contab.pdg00.comp;

// ***************************************************************
// *
// *                    Source Code Generated by
// *                 Computer Associates International, Inc.
// *
// *    Class: IPdGMgr
// *    Package: it.cnr.contab.pdg00.comp
// *    Date:  Wed Oct 31 10:31:55 GMT 2001
// *    User:  cnr004
// *
// *    Copyright 2000, Computer Associates International, Inc.
// *    All rights reserved.
// *
// ***************************************************************
// *
// * Change History
// *
// * Initials    Date       Comments
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------

import it.cnr.contab.pdg00.bulk.Pdg_preventivo_detBulk;
import it.cnr.contab.config00.sto.bulk.CdrBulk;
import it.cnr.contab.pdg00.bulk.Pdg_preventivoBulk;
import it.cnr.jada.UserContext;
import it.cnr.jada.comp.ComponentException;

public interface IPdGMgr
{


}
