//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.14 at 12:16:56 PM CET 
//


package it.cnr.contab.doccont00.intcass.giornaliera;

import it.cnr.contab.doccont00.intcass.xmlbnl.AnyTAG;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.cnr.contab.doccont00.intcass.xmlbnl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.cnr.contab.doccont00.intcass.xmlbnl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.CreditoreEffettivo }
     * 
     */
    public FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.CreditoreEffettivo createFlussoGiornaleDiCassaInformazioniContoEvidenzaMovimentoContoEvidenzaCreditoreEffettivo() {
        return new FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.CreditoreEffettivo();
    }

    /**
     * Create an instance of {@link FlussoGiornaleDiCassa.TotaliDisponibilitaLiquide }
     * 
     */
    public FlussoGiornaleDiCassa.TotaliDisponibilitaLiquide createFlussoGiornaleDiCassaTotaliDisponibilitaLiquide() {
        return new FlussoGiornaleDiCassa.TotaliDisponibilitaLiquide();
    }

    /**
     * Create an instance of {@link FlussoGiornaleDiCassa }
     * 
     */
    public FlussoGiornaleDiCassa createFlussoGiornaleDiCassa() {
        return new FlussoGiornaleDiCassa();
    }

    /**
     * Create an instance of {@link FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.Cliente }
     * 
     */
    public FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.Cliente createFlussoGiornaleDiCassaInformazioniContoEvidenzaMovimentoContoEvidenzaCliente() {
        return new FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.Cliente();
    }

    /**
     * Create an instance of {@link AnyTAG }
     * 
     */
    public AnyTAG createAnyTAG() {
        return new AnyTAG();
    }

    /**
     * Create an instance of {@link FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.Delegato }
     * 
     */
    public FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.Delegato createFlussoGiornaleDiCassaInformazioniContoEvidenzaMovimentoContoEvidenzaDelegato() {
        return new FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza.Delegato();
    }

    /**
     * Create an instance of {@link FlussoGiornaleDiCassa.InformazioniContoEvidenza }
     * 
     */
    public FlussoGiornaleDiCassa.InformazioniContoEvidenza createFlussoGiornaleDiCassaInformazioniContoEvidenza() {
        return new FlussoGiornaleDiCassa.InformazioniContoEvidenza();
    }

    /**
     * Create an instance of {@link FlussoGiornaleDiCassa.TotaliEsercizio }
     * 
     */
    public FlussoGiornaleDiCassa.TotaliEsercizio createFlussoGiornaleDiCassaTotaliEsercizio() {
        return new FlussoGiornaleDiCassa.TotaliEsercizio();
    }

    /**
     * Create an instance of {@link FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza }
     * 
     */
    public FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza createFlussoGiornaleDiCassaInformazioniContoEvidenzaMovimentoContoEvidenza() {
        return new FlussoGiornaleDiCassa.InformazioniContoEvidenza.MovimentoContoEvidenza();
    }

}
