//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 09:37:57 PM CET 
//


package it.siopeplus.custom;

import it.siopeplus.*;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import java.math.BigInteger;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.siopeplus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Esercizio_QNAME = new QName("", "esercizio");
    private final static QName _MessaggioRifiutoFlussoTestataMessaggio_QNAME = new QName("", "testata_messaggio");
    private final static QName _MessaggioRifiutoFlussoIdentificativoFlusso_QNAME = new QName("", "identificativo_flusso");
    private final static QName _MessaggioRifiutoFlussoIdentificativoFlussoBT_QNAME = new QName("", "identificativo_flusso_BT");
    private final static QName _MessaggioRifiutoFlussoErrore_QNAME = new QName("", "errore");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.siopeplus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessaggioRifiutoFlusso }
     * 
     */
    public MessaggioRifiutoFlusso createMessaggioRifiutoFlusso() {
        return new MessaggioRifiutoFlusso();
    }


    /**
     * Create an instance of {@link MessaggioRicezioneFlusso }
     * 
     */
    public MessaggioRicezioneFlusso createMessaggioRicezioneFlusso() {
        return new MessaggioRicezioneFlusso();
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "identificativo_flusso", scope = MessaggioRifiutoFlusso.class)
    public JAXBElement<String> createMessaggioRifiutoFlussoIdentificativoFlusso(String value) {
        return new JAXBElement<String>(_MessaggioRifiutoFlussoIdentificativoFlusso_QNAME, String.class, MessaggioRifiutoFlusso.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "identificativo_flusso_BT", scope = MessaggioRifiutoFlusso.class)
    public JAXBElement<String> createMessaggioRifiutoFlussoIdentificativoFlussoBT(String value) {
        return new JAXBElement<String>(_MessaggioRifiutoFlussoIdentificativoFlussoBT_QNAME, String.class, MessaggioRifiutoFlusso.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "esercizio", scope = MessaggioRifiutoFlusso.class)
    public JAXBElement<Integer> createMessaggioRifiutoFlussoEsercizio(Integer value) {
        return new JAXBElement<Integer>(_Esercizio_QNAME, Integer.class, MessaggioRifiutoFlusso.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtErrore }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CtErrore }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "errore", scope = MessaggioRifiutoFlusso.class)
    public JAXBElement<CtErrore> createMessaggioRifiutoFlussoErrore(CtErrore value) {
        return new JAXBElement<CtErrore>(_MessaggioRifiutoFlussoErrore_QNAME, CtErrore.class, MessaggioRifiutoFlusso.class, value);
    }


    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CtTestataMessaggio }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CtTestataMessaggio }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "testata_messaggio", scope = MessaggioRicezioneFlusso.class)
    public JAXBElement<CtTestataMessaggio> createMessaggioRicezioneFlussoTestataMessaggio(CtTestataMessaggio value) {
        return new JAXBElement<CtTestataMessaggio>(_MessaggioRifiutoFlussoTestataMessaggio_QNAME, CtTestataMessaggio.class, MessaggioRicezioneFlusso.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "identificativo_flusso", scope = MessaggioRicezioneFlusso.class)
    public JAXBElement<String> createMessaggioRicezioneFlussoIdentificativoFlusso(String value) {
        return new JAXBElement<String>(_MessaggioRifiutoFlussoIdentificativoFlusso_QNAME, String.class, MessaggioRicezioneFlusso.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "identificativo_flusso_BT", scope = MessaggioRicezioneFlusso.class)
    public JAXBElement<String> createMessaggioRicezioneFlussoIdentificativoFlussoBT(String value) {
        return new JAXBElement<String>(_MessaggioRifiutoFlussoIdentificativoFlussoBT_QNAME, String.class, MessaggioRicezioneFlusso.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "esercizio", scope = MessaggioRicezioneFlusso.class)
    public JAXBElement<Integer> createMessaggioRicezioneFlussoEsercizio(Integer value) {
        return new JAXBElement<Integer>(_Esercizio_QNAME, Integer.class, MessaggioRicezioneFlusso.class, value);
    }

    /**
     * Create an instance of {@link MessaggiEsitoApplicativo }
     *
     */
    public MessaggiEsitoApplicativo createMessaggiEsitoApplicativo() {
        return new MessaggiEsitoApplicativo();
    }
}
