//@@<< FB
// ***************************************************************
// *
// *                    INumerazione_baseMgr.java Generated by
// *                 Computer Associates International, Inc.
// *
// *    Class: INumerazione_baseMgr
// *    Package: it.cnr.contab.config00.tabnum.comp
// *    Date:  Jul 23, 2001 3:24:20 PM
// *    User:  coola01
// *
// *    Copyright 2000, Computer Associates International, Inc.
// *    All rights reserved.
// *
// ***************************************************************
// *
// * Change History
// *
// * Initials    Date       Comments
// *+--------+------------+--------------------------------------------------
//@@>> FB
// *|        |            |
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------

package it.cnr.contab.config00.tabnum.comp;
import it.cnr.jada.UserContext;
import it.cnr.jada.comp.ComponentException;
public interface INumerazione_baseMgr
{





/**
 * Crea un nuovo progressivo per la colonna e la tabella specificata.
 *
 * Pre-post-conditions:
 *
 * Nome: Primo progressivo
 * Pre: Nella tabella NUMERAZIONE_BASE non esiste nessuna riga per la chiave 
 * 			(esercizio,tabella,colonna)
 * Post: Viene inserita una nuova riga con la chiave specificata e con i 
 *			seguenti valori:
 *			CD_INIZIALE="1"
 *			CD_MASSIMO="99999999"
 *			CD_CORRENTE="1"
 *			e viene restituito il valore 1;
 * 
 * Nome: Progressivo massimo superato
 * Pre: Nella tabella NUMERAZIONE_BASE esiste una riga per la chiave 
 * 			(esercizio,tabella,colonna) e il valore di CD_CORRENTE è uguale o
 *			maggiore di CD_MASSIMO
 * Post: Viene generata una NumerazioneEsauritaException
 * 
 * Nome: Risorsa occupata
 * Pre: Nella tabella NUMERAZIONE_BASE esiste una riga per la chiave 
 * 			(esercizio,tabella,colonna) e il valore di CD_CORRENTE è minore 
 * 			di CD_MASSIMO ma il record è già stato lockato da un altro utente
 * Post: Viene generata una ComponentException con deatil la BusyResourceException
 * 			che ha provocato il tentativo di lock fallito
 *
 * Nome: Tutti i controlli superati
 * Pre: Nella tabella NUMERAZIONE_BASE esiste una riga per la chiave 
 * 			(esercizio,tabella,colonna) e il valore di CD_CORRENTE è minore 
 * 			di CD_MASSIMO
 * Post: Viene incrementato di uno il valore di CD_MASSIMO e restituito
 * 			il nuovo progressivo
 *
 * @param	uc	lo UserContext che ha generato la richiesta
 * @param	esercizio l'esercizio cui fa riferimento il progressivo
 * @param 	tabella Il nome della tabella per cui creare il progressivo
 * @param	colonna Il nome della colonna per cui creare il progressivo
 * @param 	user Lo userid dell'utente per cui è stato richiesto il progressivo
 * @return	Il nuovo progressivo.
 */

public abstract java.lang.Long creaNuovoProgressivo(it.cnr.jada.UserContext param0,java.lang.Integer param1,java.lang.String param2,java.lang.String param3,java.lang.String param4) throws it.cnr.jada.comp.ComponentException,it.cnr.jada.bulk.BusyResourceException;
}
