package it.cnr.contab.web.rest.model;

public enum EnumTypeAttachmentFile {

    ALLEGATO_FLUSSO,AGGIUDICAZIONE_FLUSSO,REVOCA_FLUSSO,
    RICHIESTA_ACQUISTO_FLUSSO ,AVVISO_POST_INFORMAZIONE_FLUSSO,STIPULA_FLUSSO,
    ELENCO_VERBALI_FLUSSO,NOMINA_COMMISSIONE_FLUSSO,AMMESSI_ESCLUSI_FLUSSO,LETTERA_INVITO_FLUSSO,
    BANDO_AVVISI_FLUSSO,MODIFICHE_VARIANTI_FLUSSO,DECISIONE_CONTRATTARE_FLUSSO;
}
