CREATE OR REPLACE FUNCTION Dwh_GetCdrAccentrfromIDClass(ID_CLASS_IN IN NUMBER)
  RETURN VARCHAR2 IS
    CD_CDR CDR.CD_CENTRO_RESPONSABILITA%TYPE;
BEGIN
    SELECT CDR_ACCENTRATORE
    INTO CD_CDR
    FROM CLASSIFICAZIONE_VOCI
    WHERE ID_CLASSIFICAZIONE = ID_CLASS_IN;
    RETURN CD_CDR;
END Dwh_GetCdrAccentrfromIDClass;
/


