CREATE OR REPLACE FUNCTION Dwh_Getuofromcdr(CD_CENTRO_RESP IN VARCHAR2)
  RETURN VARCHAR2 IS
    CD_UO CDR.CD_UNITA_ORGANIZZATIVA%TYPE;
BEGIN
    SELECT CDR.CD_UNITA_ORGANIZZATIVA
    INTO CD_UO
    FROM CDR
    WHERE CDR.CD_CENTRO_RESPONSABILITA = CD_CENTRO_RESP;
    RETURN CD_UO;
END Dwh_Getuofromcdr;
/


