CREATE OR REPLACE FUNCTION DWH_GETCDSFROMCDR(CD_CENTRO_RESP IN VARCHAR2)
  RETURN VARCHAR2 IS
    CD_CDS UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA%TYPE;
BEGIN
    SELECT UNITA_ORGANIZZATIVA.CD_UNITA_PADRE
    INTO CD_CDS
    FROM UNITA_ORGANIZZATIVA, CDR
    WHERE CDR.CD_CENTRO_RESPONSABILITA = CD_CENTRO_RESP
      AND CDR.CD_UNITA_ORGANIZZATIVA = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA;
    RETURN CD_CDS;
End DWH_GETCDSFROMCDR;
/


