//@@<< FB
// ***************************************************************
// *
// *                    IRuoloMgr.java Generated by
// *                 Computer Associates International, Inc.
// *
// *    Class: IRuoloMgr
// *    Package: it.cnr.contab.utenze00.comp
// *    Date:  Jul 23, 2001 4:44:17 PM
// *    User:  coola01
// *
// *    Copyright 2000, Computer Associates International, Inc.
// *    All rights reserved.
// *
// ***************************************************************
// *
// * Change History
// *
// * Initials    Date       Comments
// *+--------+------------+--------------------------------------------------
//@@>> FB
// *|        |            |
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------

package it.cnr.contab.utenze00.comp;
import it.cnr.jada.UserContext;
import it.cnr.jada.bulk.OggettoBulk;
import it.cnr.jada.comp.ComponentException;
public interface IRuoloMgr
{


//^^@@
/**
  *  Cancellazione RuoloBulk
  *    PreCondition:
  *      E' stata generata una richiesta di cancellazioe di un RuoloBulk
  *    PostCondition:
  *      Il RuoloBulk specificato e tutte le istanze di Utente_unita_ruoloBulk ad esso associate sono stati eliminati
 */
//^^@@
        public void eliminaConBulk (UserContext userContext,OggettoBulk bulk) throws ComponentException;

//^^@@
/**
  *  Inizializzazione bulk
  *    PreCondition:
  *      L'inizializzazione di un RuoloBulk per eventuale inserimento e' stata generata
  *    PostCondition:
  *      Il RuoloBulk viene aggiornato con l'elenco delle istanze di AccessoBulk disponibili per l'utente corrente
  *  Gestore non trovato
  *    PreCondition:
  *      L'utente che ha generato la richiesta non esiste
  *    PostCondition:
  *      Viene generata una ComponentException con detail l'ApplicationException con il messaggio da visualizzare all'utente
 */
//^^@@
        public OggettoBulk inizializzaBulkPerInserimento (UserContext userContext,OggettoBulk bulk) throws ComponentException;

//^^@@
/**
  *  Inizializzazione bulk
  *    PreCondition:
  *      L'inizializzazione di un RuoloBulk per eventuale modifica e' stata generata
  *    PostCondition:
  *      Il RuoloBulk viene aggiornato con l'elenco delle istanze di AccessoBulk ancora disponibili e con l'elenco di istanze di Utente_unita_ruoloBulk gia' assegnate al ruolo
  *  Gestore non trovato
  *    PreCondition:
  *      L'utente che ha generato la richiesta non esiste
  *    PostCondition:
  *      Viene generata una ComponentException con detail l'ApplicationException con il messaggio da visualizzare all'utente
 */
//^^@@
        public OggettoBulk inizializzaBulkPerModifica (UserContext userContext,OggettoBulk bulk) throws ComponentException;


}
