import net.sf.jasperreports.engine.*;


public class vpg_doc_genericoScriptlet extends it.businesslogic.ireport.IReportScriptlet {
    
/** Creates a new instance of JRIreportDefaultScriptlet */
public vpg_doc_genericoScriptlet() {
	
	
}


























































































/** Begin EVENT_AFTER_COLUMN_INIT This line is generated by iReport. Don't modify or move please! */
public void afterColumnInit() throws JRScriptletException
{
	super.beforeColumnInit();
}
/** End EVENT_AFTER_COLUMN_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_AFTER_DETAIL_EVAL This line is generated by iReport. Don't modify or move please! */
public void afterDetailEval() throws JRScriptletException
{
	super.afterDetailEval();
}
/** End EVENT_AFTER_DETAIL_EVAL This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_AFTER_GROUP_INIT This line is generated by iReport. Don't modify or move please! */
public void afterGroupInit(String groupName) throws JRScriptletException
{
	super.afterGroupInit(groupName);
}
/** End EVENT_AFTER_GROUP_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_AFTER_PAGE_INIT This line is generated by iReport. Don't modify or move please! */
public void afterPageInit() throws JRScriptletException
{
	super.afterPageInit();
}
/** End EVENT_AFTER_PAGE_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_AFTER_REPORT_INIT This line is generated by iReport. Don't modify or move please! */
public void afterReportInit() throws JRScriptletException
{
	
}
/** End EVENT_AFTER_REPORT_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_COLUMN_INIT This line is generated by iReport. Don't modify or move please! */
public void beforeColumnInit() throws JRScriptletException
{
		
}
/** End EVENT_BEFORE_COLUMN_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_DETAIL_EVAL This line is generated by iReport. Don't modify or move please! */
public void beforeDetailEval() throws JRScriptletException
{
	
}
/** end EVENT_BEFORE_DETAIL_EVAL Please don't touch or move this comment*/

/** End EVENT_BEFORE_DETAIL_EVAL This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_GROUP_INIT This line is generated by iReport. Don't modify or move please! */
public void beforeGroupInit(String groupName) throws JRScriptletException
{
	
}
/** End EVENT_BEFORE_GROUP_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_PAGE_INIT This line is generated by iReport. Don't modify or move please! */
public void beforePageInit() throws JRScriptletException
{
	
}
/** End EVENT_BEFORE_PAGE_INIT This line is generated by iReport. Don't modify or move please! */
/** Begin EVENT_BEFORE_REPORT_INIT This line is generated by iReport. Don't modify or move please! */
public void beforeReportInit() throws JRScriptletException
{
	java.sql.Connection conn = (java.sql.Connection)getParameterValue("REPORT_CONNECTION");
	java.sql.CallableStatement cs = null; 
	try{
        	conn.setAutoCommit(false);
		cs = conn.prepareCall("{call SPG_DOC_GENERICO(?,?,?,?,?,?,?,?,?)}");
		cs.setObject(1,(java.lang.String)getParameterValue("aCd_cds"));
		cs.setObject(2,(java.lang.String)getParameterValue("aCd_uo"));
		cs.setObject(3,(java.lang.Integer)getParameterValue("aEs"));
		cs.setObject(4,(java.lang.String)getParameterValue("aCd_tipo_doc_amm"));
		cs.setObject(5,(java.lang.Long)getParameterValue("aPg_da"));
		cs.setObject(6,(java.lang.Long)getParameterValue("aPg_a"));
		cs.setObject(7,(new java.text.SimpleDateFormat("yyyy/MM/dd")).format((java.util.Date)getParameterValue("aDt_da")));
		cs.setObject(8,(new java.text.SimpleDateFormat("yyyy/MM/dd")).format((java.util.Date)getParameterValue("aDt_a")));
		cs.setObject(9,(java.lang.String)getParameterValue("aCd_terzo"));
		cs.setObject(10,(java.lang.Long)getParameterValue("acd_tdg"));
		cs.executeQuery();
	}catch (Throwable e) {
		throw new JRScriptletException(e.getMessage());
	} finally {
		if (cs != null) 
			try {
				cs.close();
			} catch (java.sql.SQLException e1) {
				throw new JRScriptletException(e1.getMessage());
			}
	}	
}

/** End EVENT_BEFORE_REPORT_INIT This line is generated by iReport. Don't modify or move please! */

}