<%@ page pageEncoding="UTF-8"
	import="it.cnr.jada.util.jsp.*,
		it.cnr.jada.action.*,
		java.util.*,
		it.cnr.jada.util.action.*,
		it.cnr.contab.docamm00.tabrif.bulk.*,
		it.cnr.contab.docamm00.docs.bulk.*,
		it.cnr.contab.docamm00.bp.*,
		it.cnr.contab.anagraf00.tabrif.bulk.*"
%>

<% CRUDFatturaPassivaBP bp = (CRUDFatturaPassivaBP)BusinessProcess.getBusinessProcess(request);
	Fattura_passivaBulk fatturaPassiva = (Fattura_passivaBulk)bp.getModel();
	boolean roOnAutoGen = false;
	if (bp instanceof IDocumentoAmministrativoBP)
		roOnAutoGen = ((IDocumentoAmministrativoBP)bp).isAutoGenerated();
	if (fatturaPassiva instanceof Fattura_passiva_IBulk)
		bp.getDettaglio().writeHTMLTable(pageContext,"righiSet",true,false,true,"100%","40vh");
	else if (fatturaPassiva instanceof Nota_di_creditoBulk)
		bp.getDettaglio().writeHTMLTable(pageContext,"righeNdCSet",true,false,true,"100%","40vh");
	else 
		bp.getDettaglio().writeHTMLTable(pageContext,"righeNdDSet",true,false,true,"100%","40vh"); %>
   <div class="Group card" >

   <table class="w-75">
      <tr>
      	<% if (fatturaPassiva.isPromiscua()) { %>
		      	<td>
		      		<% bp.getDettaglio().writeFormLabel(out,"ti_promiscuo");%>
		      	</td>      	
		     	<td colspan="5">
		     		<% bp.getDettaglio().writeFormInput(out,null,"ti_promiscuo",roOnAutoGen,null,"");%>
		     	</td>
      	<% } else { %>
		      	<td>
		      		<% bp.getDettaglio().writeFormLabel(out,"ti_istituz_commerc");%>
		      	</td>      	
		     	<td colspan="5">
		     		<% bp.getDettaglio().writeFormInput(out,null,"ti_istituz_commerc",roOnAutoGen,null,"");%>
		     	</td>
      	<% } %>
      </tr>
      <tr>
		<td><% bp.getDettaglio().writeFormLabel(out,"bene_servizio");%>
   		<td colspan="5">
   			<% bp.getDettaglio().writeFormInput(out, null, "bene_servizio", roOnAutoGen, null, "");%>
   		</td>
      </tr>
      <tr>
		<td><% bp.getDettaglio().writeFormLabel(out,"voce_iva");%>
   		<td colspan="5">
   			<% bp.getDettaglio().writeFormInput(out, null, "voce_iva", false, null, "");%>
   		</td>
      </tr>
      <tr>
      	<td>
      		<% bp.getDettaglio().writeFormLabel(out,"ds_riga_fattura");%>
      	</td>      	
     	<td colspan="5">
     		<% bp.getDettaglio().writeFormInput(out,null,"ds_riga_fattura",false,null,"");%>
     	</td>
	  </tr>
      <tr>      	
      	<td>
      		<% bp.getDettaglio().writeFormLabel(out,"dt_da_competenza_coge");%>
      	</td>      	
     	<td colspan="2">
     		<% bp.getDettaglio().writeFormInput(out,null,"dt_da_competenza_coge",false,null,"");%>
     	</td>
      	<td>
      		<% bp.getDettaglio().writeFormLabel(out,"dt_a_competenza_coge");%>
      	</td>      	
     	<td>
     		<% bp.getDettaglio().writeFormInput(out,null,"dt_a_competenza_coge",false,null,"");%>
     	</td>
      </tr>
		<%	if (fatturaPassiva instanceof Nota_di_creditoBulk) { %>
			    <tr> 
			      	<td>
			      		<% bp.getDettaglio().writeFormLabel(out,"ds_fattura_origine");%>
			      	</td>      	
			     	<td colspan="5">
			     		<% bp.getDettaglio().writeFormInput(out,null,"ds_fattura_origine",roOnAutoGen,null,"");%>
			     	</td>
				</tr>
	    <%	} %>
		<%	it.cnr.contab.docamm00.docs.bulk.Fattura_passiva_rigaBulk riga = (it.cnr.contab.docamm00.docs.bulk.Fattura_passiva_rigaBulk)bp.getDettaglio().getModel();
			if (riga != null && riga.getCollegatoCapitoloPerTrovato()) { %>
		    <tr>
			  	  <td>
				  	<% bp.getDettaglio().writeFormLabel(out,"pg_trovato");%>
				  </td>
				  <td colspan="3">	
				  <% bp.getDettaglio().writeFormInput(out,null,"pg_trovato",false,null,"");%>
				  	<% bp.getDettaglio().writeFormField(out,"titoloTrovato");%>
				  	<% bp.getDettaglio().writeFormField(out,"inventoreTrovato");%>
  			  	  </td>
  			</tr>
		<%	}  %>
 	  </tr>
    </table>
   </div>
    <div class="Group card">
  	<table class="w-75">
	  <tr>
	  	<td>
	  		<% bp.getDettaglio().writeFormLabel(out,"quantita");%>
	  	</td>
	  	<td>
	  		<% bp.getDettaglio().writeFormInput(out,null,"quantita",false,null,"");%>
	  	</td>
	  	<td>
		  	<% bp.getDettaglio().writeFormLabel(out,"prezzo_unitario");%>
	  	</td>
	  	<td>
		  	<% bp.getDettaglio().writeFormInput(out,null,"prezzo_unitario",false,null,"");%>
		</td>	  	
      
      <% if (bp.isDetailDoubling()) { %>
	   	<td>
	  		<% bp.getDettaglio().writeFormLabel(out,"im_riga_sdoppia");%>
	  	</td>
	  	<td>
	  		<% bp.getDettaglio().writeFormInput(out,null,"im_riga_sdoppia",false,null,"");%>
	  	</td>
	 <%}%>
      </tr>
   <% if (bp.isDetailDoubling()) { %>
   	<script>setFocusOnInput('main.Dettaglio.im_riga_sdoppia')</script>
   <% bp.setDetailDoubling(false);} %>
      <tr>
      	<td>
	  		<% bp.getDettaglio().writeFormLabel(out,"im_totale_divisa");%>
	  	</td>
	  	<td>
	  		<% bp.getDettaglio().writeFormInput(out,null,"im_totale_divisa",false,null,"readonly");%>
	  	</td>
	  	<td>
		  	<% bp.getDettaglio().writeFormLabel(out,"im_imponibile");%>
	  	</td>
	  	<td>
		  	<% bp.getDettaglio().writeFormInput(out,null,"im_imponibile",false,null,"");%>
		</td>	
      </tr>
      <tr>
	  	<td>
		  	<% bp.getDettaglio().writeFormLabel(out,"im_iva");%>
	  	</td>
		<%	if (riga != null && riga.getFl_iva_forzata() != null && riga.getFl_iva_forzata().booleanValue()) { %>
			  	<td>
				  	<% bp.getDettaglio().writeFormInput(out,null,"im_iva",false,null,"style=\"color:red;text-align: right\"");%>
			  	</td>
			  	<td>
				  	<span class="FormLabel" style="color:red">L'importo IVA e' forzato.</span>
			  	</td>
		<%	} else { %>
			 	<td>
		  			<% bp.getDettaglio().writeFormInput(out,null,"im_iva",false,null,"");%>
	  			</td>
		<%	} %>
      </tr>   
    </table>
   </div>
   <div class="Group card">
  	<table>
	  <tr>
     	<td>
 	     	<% bp.getDettaglio().writeFormLabel(out,"termini_pagamento");%>
      	</td>      	
     	<td>
	      	<% bp.getDettaglio().writeFormInput(out,null,"termini_pagamento",roOnAutoGen,null,"");%>	
      	</td>   
      </tr>
      <tr>
     	<td>
 	     	<% bp.getDettaglio().writeFormLabel(out,"modalita_pagamento");%>
      	</td>      	
     	<td colspan="2">
	      	<% bp.getDettaglio().writeFormInput(out,null,"modalita_pagamento",roOnAutoGen,null,"onChange=\"submitForm('doOnModalitaPagamentoDetChange')\"");%>	
		    <% if (riga != null && riga.getBanca() != null) {
					bp.getDettaglio().writeFormInput(out, null, "listabanchedett", roOnAutoGen, null, "");
				} %>
   		</td>
      </tr>
	  <tr>
		<td colspan="2">
		 <%	if (riga != null && riga.getBanca() != null) {
				if (Rif_modalita_pagamentoBulk.BANCARIO.equalsIgnoreCase(riga.getBanca().getTi_pagamento())) {
			 	     	bp.getDettaglio().writeFormInput(out,"contoB");
				} else if (Rif_modalita_pagamentoBulk.POSTALE.equalsIgnoreCase(riga.getBanca().getTi_pagamento())) {
			 	     	bp.getDettaglio().writeFormInput(out,"contoP");
				} else if (Rif_modalita_pagamentoBulk.QUIETANZA.equalsIgnoreCase(riga.getBanca().getTi_pagamento())) {
			 	     	bp.getDettaglio().writeFormInput(out,"contoQ");
				} else if (Rif_modalita_pagamentoBulk.ALTRO.equalsIgnoreCase(riga.getBanca().getTi_pagamento())) { 
			 	     	bp.getDettaglio().writeFormInput(out,"contoA");
				} else if (Rif_modalita_pagamentoBulk.IBAN.equalsIgnoreCase(riga.getBanca().getTi_pagamento())) { 
		 	     	bp.getDettaglio().writeFormInput(out,"contoN");
				} else if (Rif_modalita_pagamentoBulk.BANCA_ITALIA.equalsIgnoreCase(riga.getBanca().getTi_pagamento()) && riga.getBanca().isTABB()) {
                    bp.getDettaglio().writeFormInput(out,"contoB");
                }
			} else if (riga != null && riga.getModalita_pagamento() != null && (riga.getFornitore() != null && riga.getFornitore().getCrudStatus() != riga.getFornitore().UNDEFINED)) { %>
				<span class="FormLabel" style="color:red">
					Nessun riferimento trovato per la modalità di pagamento selezionata!
				</span>
		 <%	} else if(riga!=null && riga.getModalita_pagamento() == null  
				 && riga.getModalita()!= null && riga.getModalita().size() == 0 && (riga.getFornitore() != null && riga.getFornitore().getCrudStatus() != riga.getFornitore().UNDEFINED)) { %>
		    <span class="FormLabel" style="color:red">
				Attenzione! Nessuna modalità di pagamento trovata!
			</span>
		 <% } %>
		<td>
	  <tr>
    </table>
   </div>
   	<% if (riga != null && riga.getModalita_pagamento() != null && riga.getCessionario() != null) { %>
		<div class="Group card">
		  	<table class="w-75">
				<tr>
					<td>
						<% bp.getDettaglio().writeFormLabel(out,"cd_cessionario");%>
					</td>   
					<td>
						<% bp.getDettaglio().writeFormInput(out,null,"cd_cessionario",roOnAutoGen,null,"");%>	
					</td>   
					<td>
						<% bp.getDettaglio().writeFormInput(out,null,"denom_sede_cessionario",roOnAutoGen,null,"");%>	
					</td>   
				</tr>
			</table>
		</div>
	<% } %>
	