<%@ page 
	import="it.cnr.jada.util.jsp.*,
		it.cnr.jada.action.*,
		java.util.*,
		it.cnr.jada.util.action.*,
		it.cnr.contab.docamm00.tabrif.bulk.*,
		it.cnr.contab.docamm00.docs.bulk.*,
		it.cnr.contab.docamm00.bp.*"
%>
<% CRUDFatturaAttivaBP bp = (CRUDFatturaAttivaBP)BusinessProcess.getBusinessProcess(request);
	Fattura_attivaBulk fatturaAttiva = (Fattura_attivaBulk)bp.getModel();
	boolean roOnAutoGen = false;
	if (bp instanceof IDocumentoAmministrativoBP)
		roOnAutoGen = ((IDocumentoAmministrativoBP)bp).isAutoGenerated();
	if (fatturaAttiva instanceof Fattura_attiva_IBulk)
		bp.getDettaglio().writeHTMLTable(pageContext,"righiSet",true,false,true,"100%","200px");
	else if (fatturaAttiva instanceof Nota_di_credito_attivaBulk)
		bp.getDettaglio().writeHTMLTable(pageContext,"righeNdCSet",true,false,true,"100%","200px");
	else 
		bp.getDettaglio().writeHTMLTable(pageContext,"righeNdDSet",true,false,true,"100%","200px"); %>

   <div class="Group card">

   <table class="w-75">
    <tr>
		<td><% bp.getDettaglio().writeFormLabel(out,"bene_servizio");%>
   		<td colspan="5">
   			<% bp.getDettaglio().writeFormInput(out, null, "bene_servizio", roOnAutoGen, null, "");%>
   		</td>
      </tr>
    <%if (fatturaAttiva.getTi_causale_emissione()!=null && fatturaAttiva.getTi_causale_emissione().equals(fatturaAttiva.TARIFFARIO)){%>
      <tr>
      	<td>
	  		<% bp.getDettaglio().writeFormLabel(out,"tariffario");%>
	  	</td>
		<td>
			<% bp.getDettaglio().writeFormInput(out, null, "tariffario", roOnAutoGen, null, "");%>
		</td>
      </tr>
      <tr>
      	<td>
	  		<% bp.getDettaglio().writeFormLabel(out,"unita_misura");%>
	  	</td>
	  	<td colspan=6>
	  		<% bp.getDettaglio().writeFormInput(out,null,"unita_misura",false,null,"");%>
	  	</td>
      </tr>
   <%}%>
      <tr>
		<td><% bp.getDettaglio().writeFormLabel(out,"voce_iva");%>
   		<td colspan="5">
			<% bp.getDettaglio().writeFormInput(out, null, "voce_iva", roOnAutoGen&&fatturaAttiva.isIvaRecuperabile(), null, "");%>
   		</td>
      </tr>
      <tr>
      	<td>
      		<% bp.getDettaglio().writeFormLabel(out,"ds_riga_fattura");%>
      	</td>      	
     	<td colspan="5">
     		<% bp.getDettaglio().writeFormInput(out,null,"ds_riga_fattura", false,null,"");%>
     	</td>
     	</tr>
      <tr>
		<%	it.cnr.contab.docamm00.docs.bulk.Fattura_attiva_rigaBulk riga = (it.cnr.contab.docamm00.docs.bulk.Fattura_attiva_rigaBulk)bp.getDettaglio().getModel();
			if (riga != null && riga.getCollegatoCapitoloPerTrovato()) { %>
			  	  <td>
				  	<% bp.getDettaglio().writeFormLabel(out,"pg_trovato");%>
				  </td>
				  <td colspan="3">	
				  <% bp.getDettaglio().writeFormInput(out,null,"pg_trovato",false,null,"");%>
				  	<% bp.getDettaglio().writeFormField(out,"titoloTrovato");%>
				  	<% bp.getDettaglio().writeFormField(out,"inventoreTrovato");%>
			  	</td>
		<%	}  %>
 	  </tr>
      </table>
   </div>
   <div class="Group card">
  	<table class="w-75">
            <tr>
	    <td>
      		<% bp.getDettaglio().writeFormLabel(out,"dt_da_competenza_coge");%>         		
      		<% bp.getDettaglio().writeFormInput(out,null,"dt_da_competenza_coge",false,null,"");%>
      	</td>
      	<td>
      		<% bp.getDettaglio().writeFormLabel(out,"dt_a_competenza_coge");%>
      		<% bp.getDettaglio().writeFormInput(out,null,"dt_a_competenza_coge",false,null,"");%>
      	</td>
      </tr>      
    </table>
   </div>

    <div class="Group card">
  	<table class="w-75">
	  <tr>
	  	<td>
	  		<% bp.getDettaglio().writeFormLabel(out,"quantita");%>
	  	</td>
	  	<td>
	  		<% bp.getDettaglio().writeFormInput(out,null,"quantita",false,null,"");%>
	  	</td>
	  	<td>
		  	<% bp.getDettaglio().writeFormLabel(out,"prezzo_unitario");%>
	  	</td>
	  	<td>
		  	<% bp.getDettaglio().writeFormInput(out,null,"prezzo_unitario",false,null,"");%>
		</td>	  	
      </tr>
      <tr>
	  	<td>
		  	<% bp.getDettaglio().writeFormLabel(out,"im_iva");%>
	  	</td>
		<%	if (riga != null && riga.getFl_iva_forzata() != null && riga.getFl_iva_forzata().booleanValue()) { %>
			  	<td>
				  	<% bp.getDettaglio().writeFormInput(out,null,"im_iva",false,null,"style=\"color:red;text-align: right\"");%>
			  	</td>
			  	<td>
				  	<span class="FormLabel" style="color:red">L'importo IVA e' forzato.</span>
			  	</td>
		<%	} else { %>
			 	<td>
		  			<% bp.getDettaglio().writeFormInput(out,null,"im_iva",false,null,"");%>
	  			</td>
		<%	} %>
      </tr>
      <tr>
	  	<td>
		  	<% bp.getDettaglio().writeFormLabel(out,"im_imponibile");%>
	  	</td>
	  	<td>
		  	<% bp.getDettaglio().writeFormInput(out,null,"im_imponibile",false,null,"");%>
		</td>	
      </tr>
      <tr>      	
	  	<td>
		  	<% bp.getDettaglio().writeFormLabel(out,"im_totale_divisa");%>
	  	</td>
	  	<td>
		  	<% bp.getDettaglio().writeFormInput(out,null,"im_totale_divisa",false,null,"");%>
		</td>	
	<% if (bp.isDetailDoubling()) { %>
	   	<td>
	  		<% bp.getDettaglio().writeFormLabel(out,"im_riga_sdoppia");%>
	  	</td>
	  	<td>
	  		<% bp.getDettaglio().writeFormInput(out,null,"im_riga_sdoppia",false,null,"");%>
	  	</td>
	 <%}%>
      </tr>
    </table>
   </div>
   <% if (bp.isDetailDoubling()) { %>
   	<script>setFocusOnInput('main.Dettaglio.im_riga_sdoppia')</script>
   <% bp.setDetailDoubling(false);} %>
