// ***************************************************************
// *
// *                    Source Code Generated by
// *                 Computer Associates International, Inc.
// *
// *    Class: IVoceIvaMgr
// *    Package: it.cnr.contab.docamm00.comp
// *    Date:  Wed Sep 12 10:21:35 GMT+02:00 2001
// *    User:  cnr016
// *
// *    Copyright 2000, Computer Associates International, Inc.
// *    All rights reserved.
// *
// ***************************************************************
// *
// * Change History
// *
// * Initials    Date       Comments
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------

package it.cnr.contab.docamm00.comp;
import it.cnr.contab.docamm00.tabrif.bulk.Voce_ivaBulk;
import it.cnr.jada.UserContext;
import it.cnr.jada.bulk.OggettoBulk;
import it.cnr.jada.comp.ComponentException;
public interface IVoceIvaMgr
{

    
//^^@@
/** 
  *  Voce iva non verificata.
  *    PreCondition:
  *      Una voce iva di default esiste gia.
  *    PostCondition:
  *      restituisce false come valore
  *  Tutti i controlli superati.
  *    PreCondition:
  *      Nessuna voce iva di default preesistente.
  *    PostCondition:
  *      restituisce true
 */
//^^@@
public abstract boolean validaVoceIva (UserContext aUC,Voce_ivaBulk voceIva);

/** 
  *  Voce iva non verificata.
  *    PreCondition:
  *      Una voce iva di default esiste gia.
  *    PostCondition:
  *      restituisce false come valore
  *  Tutti i controlli superati.
  *    PreCondition:
  *      Nessuna voce iva di default preesistente.
  *    PostCondition:
  *      restituisce true
 */

public abstract it.cnr.contab.docamm00.tabrif.bulk.Voce_ivaBulk caricaVoceIvaDefault(it.cnr.jada.UserContext param0) throws it.cnr.jada.comp.ComponentException;

/** 
  *  tutti i controlli superati
  *    PreCondition:
  *      validaVoceIva = true
  *    PostCondition:
  *      Consente la modifica della voce iva.
  *  validaVoceIva  non superata
  *    PreCondition:
  *      validaVoceIva = False.
  *    PostCondition:
  *      Viene inviato il messaggio "Attenzione, una voce iva di default è gia presente".
 */

public abstract it.cnr.jada.bulk.OggettoBulk creaConBulk(it.cnr.jada.UserContext param0,it.cnr.jada.bulk.OggettoBulk param1) throws it.cnr.jada.comp.ComponentException;

/** 
  *  tutti i controlli superati
  *    PreCondition:
  *      validaVoceIva = true
  *    PostCondition:
  *      Consente la modifica della voce iva.
  *  validaVoceIva  non superata
  *    PreCondition:
  *      validaVoceIva = False.
  *    PostCondition:
  *      Viene inviato il messaggio "Attenzione, una voce iva di default è gia presente".
 */

public abstract it.cnr.jada.bulk.OggettoBulk modificaConBulk(it.cnr.jada.UserContext param0,it.cnr.jada.bulk.OggettoBulk param1) throws it.cnr.jada.comp.ComponentException;
}