--------------------------------------------------------
--  DDL for View CNR_IFAC_FATTURA_PASSIVA_RIGA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "CNR_IFAC_FATTURA_PASSIVA_RIGA" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_FATTURA_PASSIVA", "PROGRESSIVO_RIGA", "TI_ISTITUZ_COMMERC", "ESERCIZIO_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "PG_OBBLIGAZIONE_SCADENZARIO", "NR_FATTURA_FORNITORE", "DT_FATTURA_FORNITORE", "IM_TOTALE_IMPONIBILE", "IM_TOTALE_IVA", "IM_TOTALE_FATTURA") AS 
  select
FP.CD_CDS,
FP.CD_UNITA_ORGANIZZATIVA,
fpr.ESERCIZIO,
fpr.PG_FATTURA_PASSIVA,
fpr.PROGRESSIVO_RIGA,
fpr.TI_ISTITUZ_COMMERC,
fpr.ESERCIZIO_OBBLIGAZIONE,
fpr.PG_OBBLIGAZIONE,
fpr.PG_OBBLIGAZIONE_SCADENZARIO ,
fp.NR_FATTURA_FORNITORE,
fp.DT_FATTURA_FORNITORE,
fp.IM_TOTALE_IMPONIBILE,
fp.IM_TOTALE_IVA,
fp.IM_TOTALE_FATTURA
from fattura_passiva_riga fpr, fattura_passiva fp
where fpr.PG_FATTURA_PASSIVA=fp.PG_FATTURA_PASSIVA AND
fpr.CD_CDS=fp.CD_CDS AND
fpr.ESERCIZIO = fp.ESERCIZIO ;
