--------------------------------------------------------
--  DDL for View NEW_VIEW_DHW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "NEW_VIEW_DHW" ("AREA_IST_SAC", "TIPOLOGIA", "ES_1", "ES_2", "CDS", "UO", "CD_CDR_ASSEGNATARIO", "CD_LINEA_ATTIVITA", "CD_ELEMENTO_VOCE", "CD_FUNZIONE", "CD_NATURA", "CD_MODULO", "CD_PROGETTO", "CD_COMMESSA", "CD_DIPARTIMENTO", "PG_PROGETTO", "PG_COMMESSA", "PG_MODULO", "DT_REGISTRAZIONE", "TOT_DEC") AS 
  Select 'AREE' AREA_IST_SAC, 'PREVISIONE INIZIALE USCITE' TIPOLOGIA,  PDG_MODULO_SPESE_GEST.ESERCIZIO  ES_1,  PDG_MODULO_SPESE_GEST.ESERCIZIO ES_2,
       UNITA_ORGANIZZATIVA_1.CD_UNITA_ORGANIZZATIVA CDS ,  UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA  UO,
       PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO  ,  PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA  ,
       PDG_MODULO_SPESE_GEST.CD_ELEMENTO_VOCE  ,  LINEA_ATTIVITA.CD_FUNZIONE  ,  LINEA_ATTIVITA.CD_NATURA  ,
       PROGETTO.CD_PROGETTO  CD_MODULO,  PROGETTO_1.CD_PROGETTO ,  PROGETTO_2.CD_PROGETTO CD_COMMESSA ,  DIPARTIMENTO.CD_DIPARTIMENTO  ,
       PROGETTO_2.PG_PROGETTO ,  PROGETTO_1.PG_PROGETTO PG_COMMESSA ,  PROGETTO.PG_PROGETTO  PG_MODULO,    PDG_MODULO_SPESE_GEST.DT_REGISTRAZIONE  ,
       ( PDG_MODULO_SPESE_GEST.IM_SPESE_GEST_DECENTRATA_INT  +  PDG_MODULO_SPESE_GEST.IM_SPESE_GEST_DECENTRATA_EST ) TOT_DEC
From   CDR, PDG_ESERCIZIO , DIPARTIMENTO , PROGETTO PROGETTO_2, PROGETTO PROGETTO_1, PROGETTO ,
       LINEA_ATTIVITA , UNITA_ORGANIZZATIVA ,  UNITA_ORGANIZZATIVA UNITA_ORGANIZZATIVA_1,
       PDG_MODULO_SPESE_GEST
WHERE ( PDG_MODULO_SPESE_GEST.ESERCIZIO  > 2005) AND
      ( PDG_MODULO_SPESE_GEST.CATEGORIA_DETTAGLIO  <> 'SCR') AND
      ( PDG_MODULO_SPESE_GEST.ESERCIZIO  =  PDG_ESERCIZIO.ESERCIZIO ) AND
      ( PDG_MODULO_SPESE_GEST.CD_CENTRO_RESPONSABILITA  =  PDG_ESERCIZIO.CD_CENTRO_RESPONSABILITA ) AND
      ( PDG_ESERCIZIO.STATO  = 'CG') AND
      ( PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA  =  LINEA_ATTIVITA.CD_LINEA_ATTIVITA ) AND
      ( PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO  =  LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA ) AND
      ( LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA  =  CDR.CD_CENTRO_RESPONSABILITA ) AND
      ( CDR.CD_UNITA_ORGANIZZATIVA  =  UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA ) AND
-- pezzo aggiunto PER LE AREE
      UNITA_ORGANIZZATIVA.CD_TIPO_UNITA = 'AREA' and
      PDG_MODULO_SPESE_GEST.CD_CDS_AREA = UNITA_ORGANIZZATIVA_1.CD_UNITA_ORGANIZZATIVA AND
-- pezzo aggiunto PER LE AREE
      ( UNITA_ORGANIZZATIVA.LIVELLO  = 2) AND
      ( UNITA_ORGANIZZATIVA.CD_UNITA_PADRE  =  UNITA_ORGANIZZATIVA_1.CD_UNITA_ORGANIZZATIVA ) AND
      ( UNITA_ORGANIZZATIVA_1.LIVELLO  = 1) AND
      ( UNITA_ORGANIZZATIVA_1.FL_CDS  = 'Y') AND
      ( LINEA_ATTIVITA.PG_PROGETTO  =  PROGETTO.PG_PROGETTO ) AND
      ( PROGETTO.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO.TIPO_FASE  = 'G') AND
      ( PROGETTO.LIVELLO  = 3) AND
      ( PROGETTO.PG_PROGETTO_PADRE  =  PROGETTO_1.PG_PROGETTO ) AND
      ( PROGETTO_1.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO_1.TIPO_FASE  = 'G') AND
      ( PROGETTO_1.LIVELLO  = 2) AND
      ( PROGETTO_1.PG_PROGETTO_PADRE  =  PROGETTO_2.PG_PROGETTO ) AND
      ( PROGETTO_2.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO_2.TIPO_FASE  = 'G') AND
      ( PROGETTO_2.LIVELLO  = 1) AND
      ( PROGETTO_2.CD_DIPARTIMENTO  =  DIPARTIMENTO.CD_DIPARTIMENTO )
Union All
Select 'IST + SAC NON ACC' , 'PREVISIONE INIZIALE USCITE' ,  PDG_MODULO_SPESE_GEST.ESERCIZIO  ,  PDG_MODULO_SPESE_GEST.ESERCIZIO  ,
        UNITA_ORGANIZZATIVA_1.CD_UNITA_ORGANIZZATIVA  ,  UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA  ,  PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO  ,
        PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA  ,  PDG_MODULO_SPESE_GEST.CD_ELEMENTO_VOCE  ,  LINEA_ATTIVITA.CD_FUNZIONE  ,  LINEA_ATTIVITA.CD_NATURA  ,
        PROGETTO.CD_PROGETTO  ,  PROGETTO_1.CD_PROGETTO  ,  PROGETTO_2.CD_PROGETTO  ,  DIPARTIMENTO.CD_DIPARTIMENTO  ,  PROGETTO_2.PG_PROGETTO  ,
        PROGETTO_1.PG_PROGETTO  ,  PROGETTO.PG_PROGETTO  ,    PDG_MODULO_SPESE_GEST.DT_REGISTRAZIONE  ,
        ( PDG_MODULO_SPESE_GEST.IM_SPESE_GEST_DECENTRATA_INT  +  PDG_MODULO_SPESE_GEST.IM_SPESE_GEST_DECENTRATA_EST )
From    CDR , PDG_ESERCIZIO , DIPARTIMENTO , PROGETTO PROGETTO_2, PROGETTO PROGETTO_1, PROGETTO PROGETTO,
        LINEA_ATTIVITA , UNITA_ORGANIZZATIVA , UNITA_ORGANIZZATIVA UNITA_ORGANIZZATIVA_1,
        PDG_MODULO_SPESE_GEST
WHERE ( PDG_MODULO_SPESE_GEST.ESERCIZIO  > 2005) AND
      ( PDG_MODULO_SPESE_GEST.CATEGORIA_DETTAGLIO  <> 'SCR') AND
      ( PDG_MODULO_SPESE_GEST.ESERCIZIO  =  PDG_ESERCIZIO.ESERCIZIO ) AND
      ( PDG_MODULO_SPESE_GEST.CD_CENTRO_RESPONSABILITA  =  PDG_ESERCIZIO.CD_CENTRO_RESPONSABILITA ) AND
      ( PDG_ESERCIZIO.STATO  = 'CG') AND
      ( PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA  =  LINEA_ATTIVITA.CD_LINEA_ATTIVITA ) AND
      ( PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO  =  LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA ) AND
      ( LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA  =  CDR.CD_CENTRO_RESPONSABILITA ) AND
      ( CDR.CD_UNITA_ORGANIZZATIVA  =  UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA ) AND
      ( UNITA_ORGANIZZATIVA.LIVELLO  = 2) AND
      ( UNITA_ORGANIZZATIVA.CD_UNITA_PADRE  =  UNITA_ORGANIZZATIVA_1.CD_UNITA_ORGANIZZATIVA ) AND
      ( UNITA_ORGANIZZATIVA_1.LIVELLO  = 1) AND
      ( UNITA_ORGANIZZATIVA_1.FL_CDS  = 'Y') AND
-- pezzo aggiunto NON AREE
      UNITA_ORGANIZZATIVA.CD_TIPO_UNITA != 'AREA' and
      PDG_MODULO_SPESE_GEST.CD_CDS_AREA = UNITA_ORGANIZZATIVA_1.CD_UNITA_ORGANIZZATIVA And
-- pezzo aggiunto NON AREE
      ( LINEA_ATTIVITA.PG_PROGETTO  =  PROGETTO.PG_PROGETTO ) AND
      ( PROGETTO.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO.TIPO_FASE  = 'G') AND
      ( PROGETTO.LIVELLO  = 3) AND
      ( PROGETTO.PG_PROGETTO_PADRE  =  PROGETTO_1.PG_PROGETTO ) AND
      ( PROGETTO_1.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO_1.TIPO_FASE  = 'G') AND
      ( PROGETTO_1.LIVELLO  = 2) AND
      ( PROGETTO_1.PG_PROGETTO_PADRE  =  PROGETTO_2.PG_PROGETTO ) AND
      ( PROGETTO_2.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO_2.TIPO_FASE  = 'G') AND
      ( PROGETTO_2.LIVELLO  = 1) AND
      ( PROGETTO_2.CD_DIPARTIMENTO  =  DIPARTIMENTO.CD_DIPARTIMENTO )
Union All
Select 'SAC ACC' , 'PREVISIONE INIZIALE USCITE' ,  PDG_MODULO_SPESE_GEST.ESERCIZIO  ,  PDG_MODULO_SPESE_GEST.ESERCIZIO  ,
        UNITA_ORGANIZZATIVA_1.CD_UNITA_ORGANIZZATIVA  ,  UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA  ,  PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO  ,
        PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA  ,  PDG_MODULO_SPESE_GEST.CD_ELEMENTO_VOCE  ,  LINEA_ATTIVITA.CD_FUNZIONE  ,  LINEA_ATTIVITA.CD_NATURA  ,
        PROGETTO.CD_PROGETTO  ,  PROGETTO_1.CD_PROGETTO  ,  PROGETTO_2.CD_PROGETTO  ,  DIPARTIMENTO.CD_DIPARTIMENTO  ,  PROGETTO_2.PG_PROGETTO  ,
        PROGETTO_1.PG_PROGETTO  ,  PROGETTO.PG_PROGETTO  ,    PDG_MODULO_SPESE_GEST.DT_REGISTRAZIONE  ,
        ( PDG_MODULO_SPESE_GEST.IM_SPESE_GEST_ACCENTRATA_INT  +  PDG_MODULO_SPESE_GEST.IM_SPESE_GEST_ACCENTRATA_EST )
FROM    CDR , PDG_ESERCIZIO , DIPARTIMENTO , PROGETTO PROGETTO_2, PROGETTO PROGETTO_1, PROGETTO PROGETTO,
        LINEA_ATTIVITA , UNITA_ORGANIZZATIVA , UNITA_ORGANIZZATIVA UNITA_ORGANIZZATIVA_1,
        PDG_MODULO_SPESE_GEST, classificazione_voci
WHERE ( PDG_MODULO_SPESE_GEST.ESERCIZIO  > 2005) AND
      ( PDG_MODULO_SPESE_GEST.CATEGORIA_DETTAGLIO  <> 'SCR') AND
      ( PDG_MODULO_SPESE_GEST.ESERCIZIO  =  PDG_ESERCIZIO.ESERCIZIO ) AND
      ( PDG_MODULO_SPESE_GEST.CD_CENTRO_RESPONSABILITA  =  PDG_ESERCIZIO.CD_CENTRO_RESPONSABILITA ) AND
      ( PDG_ESERCIZIO.STATO  = 'CG') AND
      ( PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA  =  LINEA_ATTIVITA.CD_LINEA_ATTIVITA ) AND
      ( PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO  =  LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA ) AND
      ( LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA  =  CDR.CD_CENTRO_RESPONSABILITA ) AND
      ( CDR.CD_UNITA_ORGANIZZATIVA  =  UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA ) AND
      ( UNITA_ORGANIZZATIVA.LIVELLO  = 2) AND
      ( UNITA_ORGANIZZATIVA.CD_UNITA_PADRE  =  UNITA_ORGANIZZATIVA_1.CD_UNITA_ORGANIZZATIVA ) AND
      ( UNITA_ORGANIZZATIVA_1.LIVELLO  = 1) AND
      ( UNITA_ORGANIZZATIVA_1.FL_CDS  = 'Y') AND
-- pezzo aggiunto CDR ACCENTRATORI della SAC
      PDG_MODULO_SPESE_GEST.id_classificazione = classificazione_voci.Id_classificazione and
      classificazione_voci.CDR_ACCENTRATORE is not null And
      PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO = CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE and
-- pezzo aggiunto CDR ACCENTRATORI della SAC
      ( LINEA_ATTIVITA.PG_PROGETTO  =  PROGETTO.PG_PROGETTO ) AND
      ( PROGETTO.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO.TIPO_FASE  = 'G') AND
      ( PROGETTO.LIVELLO  = 3) AND
      ( PROGETTO.PG_PROGETTO_PADRE  =  PROGETTO_1.PG_PROGETTO ) AND
      ( PROGETTO_1.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO_1.TIPO_FASE  = 'G') AND
      ( PROGETTO_1.LIVELLO  = 2) AND
      ( PROGETTO_1.PG_PROGETTO_PADRE  =  PROGETTO_2.PG_PROGETTO ) AND
      ( PROGETTO_2.ESERCIZIO  =  PDG_MODULO_SPESE_GEST.ESERCIZIO ) AND
      ( PROGETTO_2.TIPO_FASE  = 'G') AND
      ( PROGETTO_2.LIVELLO  = 1) AND
      ( PROGETTO_2.CD_DIPARTIMENTO  =  DIPARTIMENTO.CD_DIPARTIMENTO );
