--------------------------------------------------------
--  DDL for View PROGETTO_GEST
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PROGETTO_GEST" ("ESERCIZIO", "PG_PROGETTO", "TIPO_FASE", "ESERCIZIO_PROGETTO_PADRE", "PG_PROGETTO_PADRE", "TIPO_FASE_PROGETTO_PADRE", "CD_PROGETTO", "DS_PROGETTO", "CD_TIPO_PROGETTO", "CD_UNITA_ORGANIZZATIVA", "CD_RESPONSABILE_TERZO", "DT_INIZIO", "DT_FINE", "DT_PROROGA", "IMPORTO_PROGETTO", "IMPORTO_DIVISA", "CD_DIVISA", "NOTE", "STATO", "CONDIVISO", "DURATA_PROGETTO", "LIVELLO", "CD_DIPARTIMENTO", "FL_UTILIZZABILE", "DACR", "UTCR", "DUVA", "UTUV", "PG_VER_REC", "CD_PROGETTO_SIP") AS 
  Select
--
-- Date: 13/11/2006
-- Version: 1.0
--
-- Vista dei Progetti esistenti di tipo Gestionale
--
-- History
--
-- Date :13/11/2006
-- Version: 1.0
-- Creazione
--
-- Body
--
ESERCIZIO, PG_PROGETTO, TIPO_FASE, ESERCIZIO_PROGETTO_PADRE, PG_PROGETTO_PADRE, TIPO_FASE_PROGETTO_PADRE,
           CD_PROGETTO, DS_PROGETTO, CD_TIPO_PROGETTO,
           CD_UNITA_ORGANIZZATIVA, CD_RESPONSABILE_TERZO, DT_INIZIO, DT_FINE, DT_PROROGA,
           IMPORTO_PROGETTO, IMPORTO_DIVISA, CD_DIVISA, NOTE, STATO,
           CONDIVISO, DURATA_PROGETTO, LIVELLO, CD_DIPARTIMENTO, FL_UTILIZZABILE,
           DACR, UTCR, DUVA, UTUV, PG_VER_REC, CD_PROGETTO_SIP
From PROGETTO
Where TIPO_FASE = 'G';

   COMMENT ON COLUMN "PROGETTO_GEST"."CD_TIPO_PROGETTO" IS 'SC = Sviluppo Competenze 
MG = Modulo Gestionale 
PS = Progetto Strategico 
RTL = Ricerca a Tema Libero';
