--------------------------------------------------------
--  DDL for View PRT_REG_OBBLIG
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_REG_OBBLIG" ("ESERCIZIO", "CDS", "UO", "ESERCIZIO_ORIGINALE", "PROGRESSIVO", "DATA", "DESCRIZIONE", "IMPORTO", "VOCE_BILANCIO", "STATO_OBBL", "CREDITORE", "DS_CDS", "DS_UO", "TIPO") AS 
  SELECT
--
-- Date: 20/12/2006
-- Version: 1.4
--
-- Vista di stampa Registro Obbligazioni
--
-- History
--
-- Date :02/12/2002
-- Version: 1.0
-- Creazione
--
-- Date: 13/01/2003
-- Version: 1.1
-- Modifica: modificato campo fornitore in creditore
--
-- Date: 09/12/2003
-- Version: 1.2
-- Modifica: tolti outer join per ottimizzare la stampa (Cineca)
--
-- Date: 18/07/2006
-- Version: 1.3
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Date: 20/12/2006
-- Version: 1.4
-- Modifica mappa di lancio della stampa Registro Obbligazione
-- aggiunto il campo cd_tipo_documento_cont
--
-- Body
--
OBBLIGAZIONE.ESERCIZIO,
OBBLIGAZIONE.CD_CDS,
OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA,
OBBLIGAZIONE.ESERCIZIO_ORIGINALE,
OBBLIGAZIONE.PG_OBBLIGAZIONE,
OBBLIGAZIONE.DT_REGISTRAZIONE,
OBBLIGAZIONE.DS_OBBLIGAZIONE,
OBBLIGAZIONE.IM_OBBLIGAZIONE,
OBBLIGAZIONE.CD_ELEMENTO_VOCE,
OBBLIGAZIONE.STATO_OBBLIGAZIONE,
TERZO.DENOMINAZIONE_SEDE,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo,
OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT
FROM OBBLIGAZIONE, TERZO, UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b
WHERE OBBLIGAZIONE.CD_TERZO=TERZO.CD_TERZO And
	  (OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB' OR OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_RES' OR
	   OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_RESIM') And
	  a.CD_UNITA_ORGANIZZATIVA=OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA AND
	  b.CD_UNITA_ORGANIZZATIVA=OBBLIGAZIONE.CD_CDS
ORDER BY OBBLIGAZIONE.ESERCIZIO, OBBLIGAZIONE.ESERCIZIO_ORIGINALE, OBBLIGAZIONE.PG_OBBLIGAZIONE
;
