--------------------------------------------------------
--  DDL for View PRT_LIBRO_GIORNALE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_LIBRO_GIORNALE" ("RAGIONE_SOCIALE", "VIA_FISCALE", "NUM_CIVICO_FISCALE", "PG_COMUNE_FISCALE", "CAP_COMUNE_FISCALE", "CD_ATTIVITA_INPS", "CODICE_FISCALE", "PARTITA_IVA", "DS_COMUNE", "ESERCIZIO", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "PG_SCRITTURA", "DS_SCRITTURA", "DT_CONTABILIZZAZIONE", "CD_VOCE_EP", "IM_MOVIMENTO", "SEZIONE", "TI_ISTITUZ_COMMERC", "DS_VOCE_EP") AS 
  SELECT /*+RULE*/
--
-- Date: 18/05/2005
-- Version: 1.0
--
-- Vista di stampa Libro Giornale
--
-- History
--
-- Date :18/05/2005
-- Version: 1.0 (by Aurelio D'Amico)
-- Creazione
--
-- Body
--
 ANAGRAFICO.RAGIONE_SOCIALE,
 ANAGRAFICO.VIA_FISCALE,
 ANAGRAFICO.NUM_CIVICO_FISCALE,
 ANAGRAFICO.PG_COMUNE_FISCALE,
 ANAGRAFICO.CAP_COMUNE_FISCALE,
 ANAGRAFICO.CD_ATTIVITA_INPS,
 ANAGRAFICO.CODICE_FISCALE,
 ANAGRAFICO.PARTITA_IVA,
 COMUNE.DS_COMUNE,
 SCRITTURA_PARTITA_DOPPIA.ESERCIZIO,
 SCRITTURA_PARTITA_DOPPIA.CD_CDS,
 SCRITTURA_PARTITA_DOPPIA.CD_UNITA_ORGANIZZATIVA,
 SCRITTURA_PARTITA_DOPPIA.PG_SCRITTURA,
 SCRITTURA_PARTITA_DOPPIA.DS_SCRITTURA,
 SCRITTURA_PARTITA_DOPPIA.DT_CONTABILIZZAZIONE,
 MOVIMENTO_COGE.CD_VOCE_EP,
 MOVIMENTO_COGE.IM_MOVIMENTO,
 MOVIMENTO_COGE.SEZIONE,
 MOVIMENTO_COGE.TI_ISTITUZ_COMMERC,
 VOCE_EP.DS_VOCE_EP
FROM
 SCRITTURA_PARTITA_DOPPIA,
 MOVIMENTO_COGE,
 VOCE_EP,configurazione_cnr,ANAGRAFICO, COMUNE
WHERE
configurazione_cnr.esercizio = 0 AND
configurazione_cnr.CD_UNITA_FUNZIONALE = '*' AND
configurazione_cnr.CD_CHIAVE_PRIMARIA='COSTANTI' AND
configurazione_cnr.CD_CHIAVE_SECONDARIA ='CODICE_ANAG_ENTE' AND
configurazione_cnr.IM01 =ANAGRAFICO.CD_ANAG  AND
ANAGRAFICO.PG_COMUNE_FISCALE=COMUNE.PG_COMUNE AND
  SCRITTURA_PARTITA_DOPPIA.CD_CDS = MOVIMENTO_COGE.CD_CDS AND
  SCRITTURA_PARTITA_DOPPIA.ESERCIZIO = MOVIMENTO_COGE.ESERCIZIO AND
  SCRITTURA_PARTITA_DOPPIA.CD_UNITA_ORGANIZZATIVA = MOVIMENTO_COGE.CD_UNITA_ORGANIZZATIVA AND
  SCRITTURA_PARTITA_DOPPIA.PG_SCRITTURA = MOVIMENTO_COGE.PG_SCRITTURA AND
  SCRITTURA_PARTITA_DOPPIA.ATTIVA = 'Y' AND
  MOVIMENTO_COGE.ESERCIZIO =  VOCE_EP.ESERCIZIO AND
  MOVIMENTO_COGE.CD_VOCE_EP = VOCE_EP.CD_VOCE_EP
ORDER BY
 SCRITTURA_PARTITA_DOPPIA.DT_CONTABILIZZAZIONE,
 SCRITTURA_PARTITA_DOPPIA.PG_SCRITTURA,
 MOVIMENTO_COGE.SEZIONE Desc;

   COMMENT ON TABLE "PRT_LIBRO_GIORNALE"  IS 'Vista di stampa per Libro Giornale';
