--------------------------------------------------------
--  DDL for View PRT_VPG_REND_FIN_ENT_SPE_DEC_D
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_VPG_REND_FIN_ENT_SPE_DEC_D" ("ESERCIZIO", "CDR", "LINEA", "PG_MODULO", "DIP", "CD_LIVELLO1", "CD_LIVELLO2", "IM_OBBL_ACC_COMP", "FULL_COST_AC", "RES_FINALI", "RIS_PAG_TOT", "IM_OBBL_ACC_COMP_AP", "RES_FINALI_AP", "FULL_COST_AP", "RIS_PAG_TOT_AP", "ID", "CHIAVE", "TIPO", "SEQUENZA") AS 
  SELECT
IMPORTO_1,     -- ESERCIZIO
ATTRIBUTO_1,   -- CDR
ATTRIBUTO_2,   -- LINEA
IMPORTO_2,     -- PG_MODULO
ATTRIBUTO_3,   -- DIP
ATTRIBUTO_5,   -- CD_LIVELLO1
ATTRIBUTO_7,   -- CD_LIVELLO2
IMPORTO_3,     -- IM_OBBL_ACC_COMP
IMPORTO_4,     -- FULL_COST_AC
IMPORTO_5,     -- RES_FINALI
IMPORTO_6,     -- RIS_PAG_TOT
IMPORTO_7,     -- IM_OBBL_ACC_COMP_AP
IMPORTO_8,     -- RES_FINALI_AP
IMPORTO_9,     -- FULL_COST_AP
IMPORTO_10,     -- RIS_PAG_TOT_AP
ID,     --ID
CHIAVE,     --CHIAVE
TIPO,     --TIPO
SEQUENZA      -- SEQUENZA
FROM TMP_REPORT_GENERICO
;
