--------------------------------------------------------
--  DDL for View PRT_COMPENSI_VOCE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_COMPENSI_VOCE" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO_COMPENSO", "PG_COMPENSO", "DS_COMPENSO", "STATO_COFI_COMPENSO", "IM_TOTALE_COMPENSO", "ESERCIZIO_OBBLIGAZIONE", "ESERCIZIO_ORI_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "PG_OBBLIGAZIONE_SCADENZARIO", "TI_ISTITUZ_COMMERC", "IM_SCADENZA", "CD_ELEMENTO_VOCE") AS 
  SELECT
--
-- Date: 18/07/2006
-- Version: 1.2
--
-- View sottostante l'Elenco, per voce del piano, dei Compensi
--
-- History:
--
-- Date: 28/07/2004
-- Version: 1.0
--
-- Creazione
-- Stampa compensi per voce del piano
--
-- Date: 05/08/2004
-- Version: 1.1
--
-- Aggiunto il CDS nella vista e modificato il file rpt
--
-- Date: 18/07/2006
-- Version: 1.2
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORI_OBBLIGAZIONE
--
--Body:
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.STATO_COFI,
COMPENSO.IM_TOTALE_COMPENSO,
COMPENSO.ESERCIZIO_OBBLIGAZIONE,
COMPENSO.ESERCIZIO_ORI_OBBLIGAZIONE,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.PG_OBBLIGAZIONE_SCADENZARIO,
COMPENSO.TI_ISTITUZ_COMMERC,
OBBLIGAZIONE_SCADENZARIO.IM_SCADENZA,
OBBLIGAZIONE.CD_ELEMENTO_VOCE
FROM
    COMPENSO COMPENSO,
    OBBLIGAZIONE_SCADENZARIO OBBLIGAZIONE_SCADENZARIO,
    OBBLIGAZIONE OBBLIGAZIONE
WHERE
    COMPENSO.CD_CDS_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.CD_CDS AND
    COMPENSO.ESERCIZIO_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO AND
    COMPENSO.ESERCIZIO_ORI_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE AND
    COMPENSO.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE AND
    COMPENSO.PG_OBBLIGAZIONE_SCADENZARIO =          OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO AND
    OBBLIGAZIONE_SCADENZARIO.CD_CDS = OBBLIGAZIONE.CD_CDS AND
    OBBLIGAZIONE_SCADENZARIO.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO AND
    OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE = OBBLIGAZIONE.ESERCIZIO_ORIGINALE AND
    OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE = OBBLIGAZIONE.PG_OBBLIGAZIONE;

   COMMENT ON TABLE "PRT_COMPENSI_VOCE"  IS 'Stampa compensi per voce del piano';
