--------------------------------------------------------
--  DDL for View PRT_FC_FINALE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_FC_FINALE" ("ESERCIZIO", "CDS", "RISCOSSIONI", "PAGAMENTI", "FC_INIZIALE", "FC_FINALE") AS 
  SELECT
--
-- Date: 27/10/2003
-- Version: 1.0
--
-- Vista di ESTRAZIONE DEL FONDO FINALE DI CASSA DA INSERIRE NEL RENDICONTO FINANZIARIO
--
-- History:
--
-- Date: 27/10/2003
-- Version: 1.0
-- Creazione
--
-- Body
--
A.ESER, A.CDS, A.FC_RISC, B.FC_PAG, C.IM_CASSA_INIZIALE,
(C.IM_CASSA_INIZIALE+A.FC_RISC-B.FC_PAG) AS FC_FINALE
FROM
(SELECT
VOCE_F_SALDI_CMP.ESERCIZIO eser,
VOCE_F_SALDI_CMP.CD_CDS cds,
SUM (NVL(VOCE_F_SALDI_CMP.IM_MANDATI_REVERSALI,0)) fc_risc
FROM VOCE_F_SALDI_CMP
WHERE
VOCE_F_SALDI_CMP.TI_APPARTENENZA='D'
AND VOCE_F_SALDI_CMP.TI_GESTIONE='E'
GROUP BY
VOCE_F_SALDI_CMP.ESERCIZIO ,
VOCE_F_SALDI_CMP.CD_CDS ) A,
(SELECT
VOCE_F_SALDI_CMP.ESERCIZIO eser,
VOCE_F_SALDI_CMP.CD_CDS cds,
SUM (NVL(VOCE_F_SALDI_CMP.IM_MANDATI_REVERSALI,0)) fc_PAG
FROM VOCE_F_SALDI_CMP
WHERE
VOCE_F_SALDI_CMP.TI_APPARTENENZA='D'
AND VOCE_F_SALDI_CMP.TI_GESTIONE='S'
GROUP BY
VOCE_F_SALDI_CMP.ESERCIZIO ,
VOCE_F_SALDI_CMP.CD_CDS ) B,
ESERCIZIO C
WHERE
A.ESER=B.ESER
AND A.CDS=B.CDS
AND C.ESERCIZIO=A.ESER
AND C.CD_CDS=A.CDS
;

   COMMENT ON TABLE "PRT_FC_FINALE"  IS 'Vista di ESTRAZIONE DEL FONDO FINALE DI CASSA DA INSERIRE NEL RENDICONTO FINANZIARIO';
