--------------------------------------------------------
--  DDL for View PRT_SCAD_ACCERT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_SCAD_ACCERT" ("ESERCIZIO", "CDS", "ESERCIZIO_ORIGINALE", "PROGR_ACCERT", "PROGR_SCAD", "DATA_SCAD", "DS_SCAD", "IM_SCAD", "IM_DOC_AMM", "IMP_DOC_CONT", "VOCE_BILANCIO", "UO", "CDS_ORI", "UO_ORI", "DEBITORE", "DS_CDS", "DS_UO", "TIPO", "RIPORTATO") AS 
  SELECT
--
-- Date: 19/07/2006
-- Version: 1.2
--
-- Vista di stampa Scadenzario Accertamenti
--
-- History:
--
-- Date :13/01/2003
-- Version: 1.0
-- Creazione
--
-- Date: 11/12/2003
-- Version: 1.1
-- Modifica: tolti outer join per ottimizzazione (Cineca)
--
-- Date: 19/07/2006
-- Version: 1.2
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body
--
ACCERTAMENTO_SCADENZARIO.ESERCIZIO,
ACCERTAMENTO_SCADENZARIO.CD_CDS,
ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE,
ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO,
ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO_SCADENZARIO,
ACCERTAMENTO_SCADENZARIO.DT_SCADENZA_INCASSO,
ACCERTAMENTO_SCADENZARIO.DS_SCADENZA,
ACCERTAMENTO_SCADENZARIO.IM_SCADENZA,
ACCERTAMENTO_SCADENZARIO.IM_ASSOCIATO_DOC_AMM,
ACCERTAMENTO_SCADENZARIO.IM_ASSOCIATO_DOC_CONTABILE,
ACCERTAMENTO.CD_ELEMENTO_VOCE,
ACCERTAMENTO.CD_UNITA_ORGANIZZATIVA,
ACCERTAMENTO.CD_CDS_ORIGINE,
ACCERTAMENTO.CD_UO_ORIGINE,
TERZO.DENOMINAZIONE_SEDE,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo,
ACCERTAMENTO.CD_TIPO_DOCUMENTO_CONT,
ACCERTAMENTO.RIPORTATO
FROM ACCERTAMENTO_SCADENZARIO, ACCERTAMENTO, TERZO, UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b
WHERE ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE=ACCERTAMENTO.ESERCIZIO_ORIGINALE AND
          ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO=ACCERTAMENTO.PG_ACCERTAMENTO AND
	  ACCERTAMENTO_SCADENZARIO.CD_CDS=ACCERTAMENTO.CD_CDS AND
	  ACCERTAMENTO_SCADENZARIO.ESERCIZIO=ACCERTAMENTO.ESERCIZIO AND
	  a.CD_UNITA_ORGANIZZATIVA=ACCERTAMENTO.CD_UO_ORIGINE AND
	  b.CD_UNITA_ORGANIZZATIVA=ACCERTAMENTO.CD_CDS_ORIGINE AND
	  TERZO.CD_TERZO=ACCERTAMENTO.CD_TERZO AND
	  (ACCERTAMENTO.CD_TIPO_DOCUMENTO_CONT='ACR' OR ACCERTAMENTO.CD_TIPO_DOCUMENTO_CONT='ACR_RES')
ORDER BY ESERCIZIO,ACCERTAMENTO_SCADENZARIO.DT_SCADENZA_INCASSO, ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE, ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO,ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO_SCADENZARIO;

   COMMENT ON TABLE "PRT_SCAD_ACCERT"  IS 'Vista di stampa Scadenzario Accertamenti';
