--------------------------------------------------------
--  DDL for View PRT_SINTESI_IMPEGNATO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_SINTESI_IMPEGNATO" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "CD_ELEMENTO_VOCE", "DS_ELMENTO_VOCE", "TOT_RES_IMPROPRI_INT", "TOT_RES_IMPROPRI_EST", "TOT_IMP_COMPETENZA_INT", "TOT_IMP_COMPETENZA_EST", "TOT_VAR_RES_PRO_INT", "TOT_VAR_RES_PRO_EST") AS 
  Select
--
-- Date: 18/11/2008
-- Version: 1.0
--
-- Vista di Stampa Sintetica Impegnato per Fonte
--
-- History
--
-- Date: 18/11/2008
-- Version: 1.0
-- Creazione
--
-- Body:
V.ESERCIZIO,
V.CD_CENTRO_RESPONSABILITA,
DS_CDR,
V.CD_ELEMENTO_VOCE,
DS_ELEMENTO_VOCE,
Sum(Decode(NATURA.TIPO, 'FIN', IM_OBBL_RES_IMP, 0)) TOT_RES_IMPROPRI_INT,
Sum(Decode(NATURA.TIPO, 'FES', IM_OBBL_RES_IMP, 0)) TOT_RES_IMPROPRI_EST,
Sum(Decode(NATURA.TIPO, 'FIN', IM_OBBL_ACC_COMP, 0)) TOT_IMP_COMPETENZA_INT,
Sum(Decode(NATURA.TIPO, 'FES', IM_OBBL_ACC_COMP, 0)) TOT_IMP_COMPETENZA_EST,
Sum(Decode(NATURA.TIPO, 'FIN', Nvl(VAR_PIU_OBBL_RES_PRO, 0)-Nvl(VAR_MENO_OBBL_RES_PRO, 0), 0)) TOT_VAR_RES_PRO_INT,
Sum(Decode(NATURA.TIPO, 'FES', Nvl(VAR_PIU_OBBL_RES_PRO, 0)-Nvl(VAR_MENO_OBBL_RES_PRO, 0), 0)) TOT_VAR_RES_PRO_EST
From  VOCE_F_SALDI_CDR_LINEA V, CDR, ELEMENTO_VOCE EV, LINEA_ATTIVITA LA, NATURA
Where  V.TI_GESTIONE = 'S' And
       V.CD_CENTRO_RESPONSABILITA = CDR.CD_CENTRO_RESPONSABILITA And
       V.CD_CENTRO_RESPONSABILITA = LA.CD_CENTRO_RESPONSABILITA And
       V.CD_LINEA_ATTIVITA        = LA.CD_LINEA_ATTIVITA And
       V.ESERCIZIO                = EV.ESERCIZIO        And
       V.TI_APPARTENENZA          = EV.TI_APPARTENENZA  And
       V.TI_GESTIONE              = EV.TI_GESTIONE      And
       V.CD_ELEMENTO_VOCE         = EV.CD_ELEMENTO_VOCE And
       LA.CD_NATURA               = NATURA.CD_NATURA And
       (IM_OBBL_RES_IMP != 0 Or IM_OBBL_ACC_COMP != 0 Or VAR_PIU_OBBL_RES_PRO != 0 Or VAR_MENO_OBBL_RES_PRO != 0)
Group By V.ESERCIZIO, V.CD_CENTRO_RESPONSABILITA, DS_CDR, V.CD_ELEMENTO_VOCE, DS_ELEMENTO_VOCE;
