--------------------------------------------------------
--  DDL for View PRT_REND_FIN_ENT_GEST_DET_PIE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_REND_FIN_ENT_GEST_DET_PIE" ("ESERCIZIO", "ESERCIZIO_RES", "CD_PROPRIO_UNITA", "CD_UNITA_ORGANIZZATIVA", "UO_DS_UNITA_ORGANIZZATIVA", "CDS_DS_UNITA_ORGANIZZATIVA", "CDR", "CD_LINEA_ATTIVITA", "PG_PROGETTO", "CD_ELEMENTO_VOCE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "DS_LIVELLO1", "CD_LIVELLO2", "DS_LIVELLO2", "CD_LIVELLO3", "DS_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "PREV_INIZIALE", "VAR_PIU_COMP", "VAR_MENO_COMP", "RISCOSSIONI_COMP", "IM_OBBL_ACC_COMP", "RESIDUI_ASSESTATO", "VAR_PIU_RES", "VAR_MENO_RES", "RISCOSSIONI_RES") AS 
  SELECT  SALDI.ESERCIZIO,
        SALDI.ESERCIZIO_RES,
        UO.CD_PROPRIO_UNITA,
        CDS.CD_UNITA_ORGANIZZATIVA,
        UO.DS_UNITA_ORGANIZZATIVA,
        CDS.DS_UNITA_ORGANIZZATIVA,
        NVL(LINEA_ATTIVITA.CD_CDR_COLLEGATO, SALDI.CD_CENTRO_RESPONSABILITA) CD_CENTRO_RESPONSABILITA,
        NVL(LINEA_ATTIVITA.CD_LA_COLLEGATO, SALDI.CD_LINEA_ATTIVITA) CD_LINEA_ATTIVITA,
        LINEA_ATTIVITA.PG_PROGETTO,
        SALDI.cd_elemento_voce,
        CLASS.CD_CLASSIFICAZIONE,
        CLASS.DS_CLASSIFICAZIONE,
        CLASS.NR_LIVELLO,
        CLASS.CD_LIVELLO1,
        LIV_1.DS_CLASSIFICAZIONE,
        CLASS.CD_LIVELLO2,
        LIV_2.DS_CLASSIFICAZIONE,
        CLASS.CD_LIVELLO3,
        LIV_3.DS_CLASSIFICAZIONE,
        CLASS.CD_LIVELLO4,
        CLASS.CD_LIVELLO5,
        CLASS.CD_LIVELLO6,
        CLASS.CD_LIVELLO7,
-- STANZIAMENTO DI COMPETENZA
Cnrutl002.RF_IM_STANZ_INIZIALE_A1 (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE) prev_iniziale,
-- VARIAZIONI IN PIU' (solo positive)
Cnrutl002.RF_variazioni_piu (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- VARIAZIONI IN MENO (solo negative)
ABS(Cnrutl002.RF_variazioni_meno (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE)),
-- RISCOSSO A COMPETENZA
Cnrutl002.RF_IM_MANDATI_REVERSALI_PRO (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE) RISC_COMP,
-- ACCERTATO A COMPETENZA
Cnrutl002.RF_IM_OBBL_ACC_COMP (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE) IM_OBBL_ACC_COMP,
-- RESIDUI PROPRI ASSESTATI (FINALI DA ACCERTAMENTI)
Cnrutl002.RF_IM_OBBL_RES_PRO (saldi.ESERCIZIO, SALDI.ESERCIZIO_RES, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- VARIAZIONI IN PIU' AI RESIDUI PROPRI (SOLO 2006)
Cnrutl002.VAR_PIU_OBBL_RES_PRO (saldi.ESERCIZIO, SALDI.ESERCIZIO_RES, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE) VAR_PIU_RES,
-- VARIAZIONI IN MENO AI RESIDUI PROPRI (SOLO 2006)
Cnrutl002.VAR_MENO_OBBL_RES_PRO (saldi.ESERCIZIO, SALDI.ESERCIZIO_RES, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE) VAR_MENO_RES,
-- RISCOSSIONI A RESIDUO PROPRIO (PER FORZA)
Cnrutl002.RF_IM_MANDATI_REVERSALI_PRO (saldi.ESERCIZIO, SALDI.ESERCIZIO_RES, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE) RISCOSSIONI_RES
From    VOCE_F_SALDI_CDR_LINEA SALDI,
	ELEMENTO_VOCE,
        V_CLASSIFICAZIONE_VOCI CLASS,
        V_CLASSIFICAZIONE_VOCI LIV_1,
        V_CLASSIFICAZIONE_VOCI LIV_2,
        V_CLASSIFICAZIONE_VOCI LIV_3,
	LINEA_ATTIVITA,
	UNITA_ORGANIZZATIVA uo,
	UNITA_ORGANIZZATIVA cds
WHERE   SALDI.TI_GESTIONE              = 'E'
AND     CLASS.ID_CLASSIFICAZIONE       = ELEMENTO_VOCE.ID_CLASSIFICAZIONE
AND     CLASS.ESERCIZIO                = LIV_1.ESERCIZIO
AND     CLASS.TI_GESTIONE              = LIV_1.TI_GESTIONE
AND     CLASS.CD_LIVELLO1              = LIV_1.CD_LIVELLO1
AND     LIV_1.CD_LIVELLO2              IS NULL
AND     CLASS.ESERCIZIO                = LIV_2.ESERCIZIO
AND     CLASS.TI_GESTIONE              = LIV_2.TI_GESTIONE
AND     CLASS.CD_LIVELLO1              = LIV_2.CD_LIVELLO1
AND     CLASS.CD_LIVELLO2              = LIV_2.CD_LIVELLO2
AND     LIV_2.CD_LIVELLO3              IS NULL
AND     CLASS.ESERCIZIO                = LIV_3.ESERCIZIO
AND     CLASS.TI_GESTIONE              = LIV_3.TI_GESTIONE
AND     CLASS.CD_LIVELLO1              = LIV_3.CD_LIVELLO1
AND     CLASS.CD_LIVELLO2              = LIV_3.CD_LIVELLO2
AND     CLASS.CD_LIVELLO3              = LIV_3.CD_LIVELLO3
AND     LIV_3.CD_LIVELLO4              IS NULL
AND	ELEMENTO_VOCE.ESERCIZIO        = SALDI.ESERCIZIO
AND	ELEMENTO_VOCE.TI_APPARTENENZA  = SALDI.TI_APPARTENENZA
AND	ELEMENTO_VOCE.TI_GESTIONE      = SALDI.TI_GESTIONE
AND	ELEMENTO_VOCE.CD_ELEMENTO_VOCE = SALDI.CD_ELEMENTO_VOCE
AND	SALDI.CD_CENTRO_RESPONSABILITA = LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA
AND	SALDI.CD_LINEA_ATTIVITA	       = LINEA_ATTIVITA.CD_LINEA_ATTIVITA
AND     LINEA_ATTIVITA.pg_progetto     IS NOT NULL
AND     uo.cd_unita_organizzativa      = Cnrctb020.getCDUO(SALDI.CD_CENTRO_RESPONSABILITA) --modu.cd_unita_organizzativa
AND     uo.cd_unita_padre              = cds.cd_unita_organizzativa
GROUP BY SALDI.ESERCIZIO, -- DIPARTIMENTI INIZIALE
        SALDI.ESERCIZIO_RES,
        UO.CD_PROPRIO_UNITA,
        CDS.CD_UNITA_ORGANIZZATIVA,
        UO.DS_UNITA_ORGANIZZATIVA,
        CDS.DS_UNITA_ORGANIZZATIVA,
        NVL(LINEA_ATTIVITA.CD_CDR_COLLEGATO, SALDI.CD_CENTRO_RESPONSABILITA),
        NVL(LINEA_ATTIVITA.CD_LA_COLLEGATO, SALDI.CD_LINEA_ATTIVITA),
--        SALDI.CD_CENTRO_RESPONSABILITA,
--        SALDI.CD_LINEA_ATTIVITA,
        LINEA_ATTIVITA.PG_PROGETTO,
        SALDI.cd_elemento_voce,
        CLASS.CD_CLASSIFICAZIONE,
        CLASS.DS_CLASSIFICAZIONE,
        CLASS.NR_LIVELLO,
        CLASS.CD_LIVELLO1,
        LIV_1.DS_CLASSIFICAZIONE,
        CLASS.CD_LIVELLO2,
        LIV_2.DS_CLASSIFICAZIONE,
        CLASS.CD_LIVELLO3,
        LIV_3.DS_CLASSIFICAZIONE,
        CLASS.CD_LIVELLO4,
        CLASS.CD_LIVELLO5,
        CLASS.CD_LIVELLO6,
        CLASS.CD_LIVELLO7,
-- STANZIAMENTO DI COMPETENZA
Cnrutl002.RF_IM_STANZ_INIZIALE_A1 (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- VARIAZIONI IN PIU' (solo positive)
Cnrutl002.RF_variazioni_piu (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- VARIAZIONI IN MENO (solo negative)
Cnrutl002.RF_variazioni_meno (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- RISCOSSO A COMPETENZA
Cnrutl002.RF_IM_MANDATI_REVERSALI_PRO (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- ACCERTATO A COMPETENZA
Cnrutl002.RF_IM_OBBL_ACC_COMP (saldi.ESERCIZIO, saldi.ESERCIZIO, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- RESIDUI PROPRI ASSESTATI (FINALI DA ACCERTAMENTI)
Cnrutl002.RF_IM_OBBL_RES_PRO (saldi.ESERCIZIO, SALDI.ESERCIZIO_RES, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- VARIAZIONI IN PIU' AI RESIDUI PROPRI (SOLO 2006)
Cnrutl002.VAR_PIU_OBBL_RES_PRO (saldi.ESERCIZIO, SALDI.ESERCIZIO_RES, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- VARIAZIONI IN MENO AI RESIDUI PROPRI (SOLO 2006)
Cnrutl002.VAR_MENO_OBBL_RES_PRO (saldi.ESERCIZIO, SALDI.ESERCIZIO_RES, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE),
-- RISCOSSIONI A RESIDUO PROPRIO (PER FORZA)
Cnrutl002.RF_IM_MANDATI_REVERSALI_PRO (saldi.ESERCIZIO, SALDI.ESERCIZIO_RES, SALDI.CD_CENTRO_RESPONSABILITA, SALDI.CD_LINEA_ATTIVITA, SALDI.TI_APPARTENENZA, SALDI.TI_GESTIONE, NULL, SALDI.CD_ELEMENTO_VOCE)
;
