--------------------------------------------------------
--  DDL for View PRT_SCAD_OBBL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_SCAD_OBBL" ("ESERCIZIO", "CDS", "ESERCIZIO_ORIGINALE", "PROGR_OBBL", "PROGR_SCAD", "DATA_SCAD", "DS_SCAD", "IM_SCAD", "IM_DOC_AMM", "IMP_DOC_CONT", "VOCE_BILANCIO", "UO", "CREDITORE", "DS_CDS", "DS_UO") AS 
  SELECT DISTINCT
--
-- Date: 18/07/2006
-- Version: 1.3
--
-- Vista di stampa Scadenzario Obbligazioni
--
-- History:
--
-- Date :02/12/2002
-- Version: 1.0
-- Creazione
--
-- Date: 13/01/2003
-- Version: 1.1
-- Modifica: modificato forrnitore in creditore
--
-- Date: 09/12/2003
-- Version: 1.2
-- Modifica: tolti outer join per ottimizzazione (Cineca)
--
-- Date: 18/07/2006
-- Version: 1.3
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body
--
OBBLIGAZIONE_SCADENZARIO.ESERCIZIO,
OBBLIGAZIONE_SCADENZARIO.CD_CDS,
OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE,
OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE,
OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO,
OBBLIGAZIONE_SCADENZARIO.DT_SCADENZA,
OBBLIGAZIONE_SCADENZARIO.DS_SCADENZA,
OBBLIGAZIONE_SCADENZARIO.IM_SCADENZA,
OBBLIGAZIONE_SCADENZARIO.IM_ASSOCIATO_DOC_AMM,
OBBLIGAZIONE_SCADENZARIO.IM_ASSOCIATO_DOC_CONTABILE,
OBBLIGAZIONE.CD_ELEMENTO_VOCE,
OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA,
TERZO.DENOMINAZIONE_SEDE,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo
FROM OBBLIGAZIONE_SCADENZARIO, OBBLIGAZIONE, TERZO, UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b
WHERE OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE=OBBLIGAZIONE.ESERCIZIO_ORIGINALE AND
          OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE=OBBLIGAZIONE.PG_OBBLIGAZIONE AND
	  OBBLIGAZIONE_SCADENZARIO.CD_CDS=OBBLIGAZIONE.CD_CDS AND
	  OBBLIGAZIONE_SCADENZARIO.ESERCIZIO=OBBLIGAZIONE.ESERCIZIO AND
	  a.CD_UNITA_ORGANIZZATIVA=OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA AND
	  b.CD_UNITA_ORGANIZZATIVA=OBBLIGAZIONE.CD_CDS AND
	  TERZO.CD_TERZO=OBBLIGAZIONE.CD_TERZO AND
	  (OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB' OR
	   --OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_PGIRO' OR
	   OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_RES' OR
	   OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_RESIM')
ORDER BY ESERCIZIO,OBBLIGAZIONE_SCADENZARIO.DT_SCADENZA, OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE,OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE,OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO;

   COMMENT ON TABLE "PRT_SCAD_OBBL"  IS 'Vista di stampa Scadenzario Obbligazioni';
