--------------------------------------------------------
--  DDL for View PRT_REND_FIN_ENTR_CNR_ART
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_REND_FIN_ENTR_CNR_ART" ("ESER", "CDS", "TITOLO", "DS_TITOLO", "CATEGORIA", "DS_CATEGORIA", "CAPITOLO", "DS_CAPITOLO", "ARTICOLO", "DS_ARTICOLO", "INIZIALE", "VAR_PIU", "VAR_MENO", "ASSESTATO", "ACCERTAMENTI", "RISCOSSIONI", "DA_RISC", "IN_PIU", "IN_MENO", "INIZIALE_R", "VAR_PIU_R", "VAR_MENO_R", "ASSESTATO_R", "RISCOSSIONI_R", "IN_PIU_R", "IN_MENO_R", "TOT_RISCOSS", "RES_ATT", "IM_VAR", "CDS_OR") AS 
  (SELECT   DISTINCT "ESER","CDS","TITOLO","DS_TITOLO","CATEGORIA","DS_CATEGORIA","CAPITOLO","DS_CAPITOLO","ARTICOLO","DS_ARTICOLO","INIZIALE","VAR_PIU","VAR_MENO","ASSESTATO","ACCERTAMENTI","RISCOSSIONI","DA_RISC","IN_PIU","IN_MENO","INIZIALE_R","VAR_PIU_R","VAR_MENO_R","ASSESTATO_R","RISCOSSIONI_R","IN_PIU_R","IN_MENO_R","TOT_RISCOSS","RES_ATT","IM_VAR","CDS_OR"
--
-- Date: 02/03/2004
-- Version: 1.0
--
-- Vista di stampa Rendiconto Finanziario CNR ENTRATE (SOLO importi DIVERSI DA zero)
--
-- History:
--
-- Date: 02/03/2004
-- Version: 1.0
-- Creazione
--
-- Body
--
FROM
PRT_REND_FIN_ENTR_CNR_ART_ALL
WHERE
(INIZIALE+VAR_PIU+VAR_MENO+ACCERTAMENTI+RISCOSSIONI+INIZIALE_R+VAR_PIU_R+VAR_MENO_R+RISCOSSIONI_R)<>0
)
;

   COMMENT ON TABLE "PRT_REND_FIN_ENTR_CNR_ART"  IS 'Vista di stampa Rendiconto Finanziario CNR ENTRATE (SOLO importi DIVERSI DA zero)';
