--------------------------------------------------------
--  DDL for View PRT_AVV_MND
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_AVV_MND" ("ESERCIZIO", "CDS_OR", "UO_OR", "PROGRESSIVO", "DATA", "IMPORTO", "RITENUTE", "DESCRIZIONE", "TERZO", "TIPO_DOC", "PROG_DOC", "BENEFICIARIO", "VIA", "NUM", "CAP", "COMUNE", "PROV", "MOD_PAG", "NUMERODOC", "DATADOC", "DS_CDS", "DS_OU", "NUM_DIST", "DS_DOC_AMM", "CAB", "ABI", "NUMERO_CONTO", "CIN", "INTESTAZIONE", "IBAN") AS 
  SELECT
--
-- Date: 24/09/2003
-- Version 1.2
--
-- Vista di stampa Avviso di Pagamento Mandato
--
-- History
--
-- Date :10/03/2003
-- Version: 1.0
-- Creazione
--
-- Date :20/03/2003
-- Version: 1.1
--  aggiunta la selezione nella vista del campo ritenute
--
-- Date: 24/09/2003
-- Version: 1.2
-- modificata la query per ottimizzare la stampa(tolti alcuni outer join, modificato l'ordine delle tabelle nel from)
--
-- Body
--
MANDATO.ESERCIZIO,
MANDATO.CD_CDS_ORIGINE,
MANDATO.CD_UO_ORIGINE,
MANDATO.PG_MANDATO,
MANDATO.DT_EMISSIONE,
MANDATO.IM_MANDATO,
MANDATO.IM_RITENUTE,
MANDATO.DS_MANDATO,
MANDATO_RIGA.CD_TERZO,
MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM,
MANDATO_RIGA.PG_DOC_AMM,
TERZO.DENOMINAZIONE_SEDE,
TERZO.VIA_SEDE,
TERZO.NUMERO_CIVICO_SEDE,
TERZO.CAP_COMUNE_SEDE,
COMUNE.DS_COMUNE,
COMUNE.CD_PROVINCIA,
RIF_MODALITA_PAGAMENTO.DS_MODALITA_PAG,
FATTURA_PASSIVA.NR_FATTURA_FORNITORE AS numero,
FATTURA_PASSIVA.DT_FATTURA_FORNITORE AS data,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo,
DISTINTA_CASSIERE_DET.PG_DISTINTA,
TIPO_DOCUMENTO_AMM.DS_TIPO_DOCUMENTO_AMM,
ban.CAB,
ban.ABI,
ban.NUMERO_CONTO,
nvl(ban.CIN,' '),
ban.INTESTAZIONE,
ban.codice_iban
FROM TERZO,COMUNE,RIF_MODALITA_PAGAMENTO,FATTURA_PASSIVA,UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b,DISTINTA_CASSIERE_DET,TIPO_DOCUMENTO_AMM , MANDATO_RIGA, MANDATO
     ,terzo terzo_uo,banca ban
WHERE
MANDATO.STATO='E'
AND MANDATO.STATO_TRASMISSIONE='T'
AND MANDATO.TI_MANDATO='P'
AND MANDATO_RIGA.ESERCIZIO=MANDATO.ESERCIZIO
AND MANDATO_RIGA.PG_MANDATO=MANDATO.PG_MANDATO
AND MANDATO_RIGA.CD_CDS=MANDATO.CD_CDS
AND MANDATO_RIGA.CD_TERZO=TERZO.CD_TERZO
AND TERZO.PG_COMUNE_SEDE=COMUNE.PG_COMUNE
AND RIF_MODALITA_PAGAMENTO.CD_MODALITA_PAG=MANDATO_RIGA.CD_MODALITA_PAG
AND MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM='FATTURA_P'
AND FATTURA_PASSIVA.PG_FATTURA_PASSIVA=MANDATO_RIGA.PG_DOC_AMM
AND FATTURA_PASSIVA.CD_CDS=MANDATO_RIGA.CD_CDS_DOC_AMM
AND FATTURA_PASSIVA.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA=MANDATO_RIGA.CD_UO_DOC_AMM
AND b.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_CDS_ORIGINE
AND a.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_UO_ORIGINE
AND DISTINTA_CASSIERE_DET.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND DISTINTA_CASSIERE_DET.CD_CDS_origine=MANDATO_RIGA.CD_CDS
AND DISTINTA_CASSIERE_DET.PG_MANDATO=MANDATO_RIGA.PG_MANDATO
AND TIPO_DOCUMENTO_AMM.CD_TIPO_DOCUMENTO_AMM=MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM
and terzo_uo.cd_unita_organizzativa  = MANDATO.CD_UNITA_ORGANIZZATIVA
and ban.CD_TERZO			 = terzo_uo.CD_TERZO
and ban.FL_CC_CDS			 = 'Y'
and ban.FL_CANCELLATO  = 'N'
UNION ALL
SELECT
MANDATO.ESERCIZIO,
MANDATO.CD_CDS_ORIGINE,
MANDATO.CD_UO_ORIGINE,
MANDATO.PG_MANDATO,
MANDATO.DT_EMISSIONE,
MANDATO.IM_MANDATO,
MANDATO.IM_RITENUTE,
MANDATO.DS_MANDATO,
MANDATO_RIGA.CD_TERZO,
MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM,
MANDATO_RIGA.PG_DOC_AMM,
TERZO.DENOMINAZIONE_SEDE,
TERZO.VIA_SEDE,
TERZO.NUMERO_CIVICO_SEDE,
TERZO.CAP_COMUNE_SEDE,
COMUNE.DS_COMUNE,
COMUNE.CD_PROVINCIA,
RIF_MODALITA_PAGAMENTO.DS_MODALITA_PAG,
TO_CHAR(MISSIONE.PG_MISSIONE,'9999999999') AS numero,
MISSIONE.DT_REGISTRAZIONE AS data,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo,
DISTINTA_CASSIERE_DET.PG_DISTINTA,
TIPO_DOCUMENTO_AMM.DS_TIPO_DOCUMENTO_AMM,
ban.CAB,
ban.ABI,
ban.NUMERO_CONTO,
nvl(ban.CIN,' '),
ban.INTESTAZIONE,
ban.codice_iban
FROM TERZO,COMUNE,RIF_MODALITA_PAGAMENTO, MISSIONE ,UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b,DISTINTA_CASSIERE_DET,TIPO_DOCUMENTO_AMM , MANDATO_RIGA, MANDATO
 ,terzo terzo_uo,banca ban
WHERE
MANDATO.STATO='E'
AND MANDATO.STATO_TRASMISSIONE='T'
AND MANDATO.TI_MANDATO='P'
AND MANDATO_RIGA.ESERCIZIO=MANDATO.ESERCIZIO
AND MANDATO_RIGA.PG_MANDATO=MANDATO.PG_MANDATO
AND MANDATO_RIGA.CD_CDS=MANDATO.CD_CDS
AND MANDATO_RIGA.CD_TERZO=TERZO.CD_TERZO
AND TERZO.PG_COMUNE_SEDE=COMUNE.PG_COMUNE
AND RIF_MODALITA_PAGAMENTO.CD_MODALITA_PAG=MANDATO_RIGA.CD_MODALITA_PAG
AND MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM='MISSIONE'
AND MISSIONE.PG_MISSIONE=MANDATO_RIGA.PG_DOC_AMM
AND MISSIONE.CD_CDS=MANDATO_RIGA.CD_CDS_DOC_AMM
AND MISSIONE.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND MISSIONE.CD_UNITA_ORGANIZZATIVA=MANDATO_RIGA.CD_UO_DOC_AMM
AND b.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_CDS_ORIGINE
AND a.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_UO_ORIGINE
AND DISTINTA_CASSIERE_DET.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND DISTINTA_CASSIERE_DET.CD_CDS_origine=MANDATO_RIGA.CD_CDS
AND DISTINTA_CASSIERE_DET.PG_MANDATO=MANDATO_RIGA.PG_MANDATO
AND TIPO_DOCUMENTO_AMM.CD_TIPO_DOCUMENTO_AMM=MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM
and terzo_uo.cd_unita_organizzativa  = MANDATO.CD_UNITA_ORGANIZZATIVA
and ban.CD_TERZO			 = terzo_uo.CD_TERZO
and ban.FL_CC_CDS			 = 'Y'
and ban.FL_CANCELLATO  = 'N'
UNION ALL
SELECT
MANDATO.ESERCIZIO,
MANDATO.CD_CDS_ORIGINE,
MANDATO.CD_UO_ORIGINE,
MANDATO.PG_MANDATO,
MANDATO.DT_EMISSIONE,
MANDATO.IM_MANDATO,
MANDATO.IM_RITENUTE,
MANDATO.DS_MANDATO,
MANDATO_RIGA.CD_TERZO,
MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM,
MANDATO_RIGA.PG_DOC_AMM,
TERZO.DENOMINAZIONE_SEDE,
TERZO.VIA_SEDE,
TERZO.NUMERO_CIVICO_SEDE,
TERZO.CAP_COMUNE_SEDE,
COMUNE.DS_COMUNE,
COMUNE.CD_PROVINCIA,
RIF_MODALITA_PAGAMENTO.DS_MODALITA_PAG,
TO_CHAR(DOCUMENTO_GENERICO.PG_DOCUMENTO_GENERICO, '9999999999') AS numero,
DOCUMENTO_GENERICO.DATA_REGISTRAZIONE AS data,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo,
DISTINTA_CASSIERE_DET.PG_DISTINTA,
TIPO_DOCUMENTO_AMM.DS_TIPO_DOCUMENTO_AMM,
ban.CAB,
ban.ABI,
ban.NUMERO_CONTO,
nvl(ban.CIN,' '),
ban.INTESTAZIONE,
ban.codice_iban
FROM TERZO,COMUNE,RIF_MODALITA_PAGAMENTO,DOCUMENTO_GENERICO,UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b,DISTINTA_CASSIERE_DET,TIPO_DOCUMENTO_AMM , MANDATO_RIGA , MANDATO
 ,terzo terzo_uo,banca ban
WHERE
MANDATO.STATO='E'
AND MANDATO.STATO_TRASMISSIONE='T'
AND MANDATO.TI_MANDATO='P'
AND MANDATO_RIGA.ESERCIZIO=MANDATO.ESERCIZIO
AND MANDATO_RIGA.PG_MANDATO=MANDATO.PG_MANDATO
AND MANDATO_RIGA.CD_CDS=MANDATO.CD_CDS
AND MANDATO_RIGA.CD_TERZO=TERZO.CD_TERZO
AND TERZO.PG_COMUNE_SEDE=COMUNE.PG_COMUNE
AND RIF_MODALITA_PAGAMENTO.CD_MODALITA_PAG=MANDATO_RIGA.CD_MODALITA_PAG
AND MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM='GENERICO_S'
AND DOCUMENTO_GENERICO.PG_DOCUMENTO_GENERICO=MANDATO_RIGA.PG_DOC_AMM
AND DOCUMENTO_GENERICO.CD_CDS=MANDATO_RIGA.CD_CDS_DOC_AMM
AND DOCUMENTO_GENERICO.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND DOCUMENTO_GENERICO.CD_UNITA_ORGANIZZATIVA=MANDATO_RIGA.CD_UO_DOC_AMM
AND b.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_CDS_ORIGINE
AND a.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_UO_ORIGINE
AND DISTINTA_CASSIERE_DET.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND DISTINTA_CASSIERE_DET.CD_CDS_origine=MANDATO_RIGA.CD_CDS
AND DISTINTA_CASSIERE_DET.PG_MANDATO=MANDATO_RIGA.PG_MANDATO
AND DOCUMENTO_GENERICO.CD_TIPO_DOCUMENTO_AMM='GENERICO_S'
AND TIPO_DOCUMENTO_AMM.CD_TIPO_DOCUMENTO_AMM=MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM
and terzo_uo.cd_unita_organizzativa  = MANDATO.CD_UNITA_ORGANIZZATIVA
and ban.CD_TERZO			 = terzo_uo.CD_TERZO
and ban.FL_CC_CDS			 = 'Y'
and ban.FL_CANCELLATO  = 'N'
UNION ALL
SELECT
MANDATO.ESERCIZIO,
MANDATO.CD_CDS_ORIGINE,
MANDATO.CD_UO_ORIGINE,
MANDATO.PG_MANDATO,
MANDATO.DT_EMISSIONE,
MANDATO.IM_MANDATO,
MANDATO.IM_RITENUTE,
MANDATO.DS_MANDATO,
MANDATO_RIGA.CD_TERZO,
MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM,
MANDATO_RIGA.PG_DOC_AMM,
TERZO.DENOMINAZIONE_SEDE,
TERZO.VIA_SEDE,
TERZO.NUMERO_CIVICO_SEDE,
TERZO.CAP_COMUNE_SEDE,
COMUNE.DS_COMUNE,
COMUNE.CD_PROVINCIA,
RIF_MODALITA_PAGAMENTO.DS_MODALITA_PAG,
TO_CHAR(COMPENSO.PG_COMPENSO, '9999999999') AS numero,
COMPENSO.DT_REGISTRAZIONE AS data,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo,
DISTINTA_CASSIERE_DET.PG_DISTINTA,
TIPO_DOCUMENTO_AMM.DS_TIPO_DOCUMENTO_AMM,
ban.CAB,
ban.ABI,
ban.NUMERO_CONTO,
nvl(ban.CIN,' '),
ban.INTESTAZIONE,
ban.codice_iban
FROM  TERZO,COMUNE,RIF_MODALITA_PAGAMENTO,COMPENSO,UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b,DISTINTA_CASSIERE_DET,TIPO_DOCUMENTO_AMM , MANDATO_RIGA,  MANDATO
 ,terzo terzo_uo,banca ban
WHERE
MANDATO.STATO='E'
AND MANDATO.STATO_TRASMISSIONE='T'
AND MANDATO.TI_MANDATO='P'
AND MANDATO_RIGA.ESERCIZIO=MANDATO.ESERCIZIO
AND MANDATO_RIGA.PG_MANDATO=MANDATO.PG_MANDATO
AND MANDATO_RIGA.CD_CDS=MANDATO.CD_CDS
AND MANDATO_RIGA.CD_TERZO=TERZO.CD_TERZO
AND TERZO.PG_COMUNE_SEDE=COMUNE.PG_COMUNE
AND RIF_MODALITA_PAGAMENTO.CD_MODALITA_PAG=MANDATO_RIGA.CD_MODALITA_PAG
AND MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM='COMPENSO'
AND COMPENSO.PG_COMPENSO=MANDATO_RIGA.PG_DOC_AMM
AND COMPENSO.CD_CDS=MANDATO_RIGA.CD_CDS_DOC_AMM
AND COMPENSO.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND COMPENSO.CD_UNITA_ORGANIZZATIVA=MANDATO_RIGA.CD_UO_DOC_AMM
AND b.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_CDS_ORIGINE
AND a.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_UO_ORIGINE
AND DISTINTA_CASSIERE_DET.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND DISTINTA_CASSIERE_DET.CD_CDS_origine=MANDATO_RIGA.CD_CDS
AND DISTINTA_CASSIERE_DET.PG_MANDATO=MANDATO_RIGA.PG_MANDATO
AND TIPO_DOCUMENTO_AMM.CD_TIPO_DOCUMENTO_AMM=MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM
and terzo_uo.cd_unita_organizzativa  = MANDATO.CD_UNITA_ORGANIZZATIVA
and ban.CD_TERZO			 = terzo_uo.CD_TERZO
and ban.FL_CC_CDS			 = 'Y'
and ban.FL_CANCELLATO  = 'N'
UNION ALL
SELECT
MANDATO.ESERCIZIO,
MANDATO.CD_CDS_ORIGINE,
MANDATO.CD_UO_ORIGINE,
MANDATO.PG_MANDATO,
MANDATO.DT_EMISSIONE,
MANDATO.IM_MANDATO,
MANDATO.IM_RITENUTE,
MANDATO.DS_MANDATO,
MANDATO_RIGA.CD_TERZO,
MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM,
MANDATO_RIGA.PG_DOC_AMM,
TERZO.DENOMINAZIONE_SEDE,
TERZO.VIA_SEDE,
TERZO.NUMERO_CIVICO_SEDE,
TERZO.CAP_COMUNE_SEDE,
COMUNE.DS_COMUNE,
COMUNE.CD_PROVINCIA,
RIF_MODALITA_PAGAMENTO.DS_MODALITA_PAG,
TO_CHAR(ANTICIPO.PG_ANTICIPO, '9999999999') AS numero,
ANTICIPO.DT_REGISTRAZIONE AS data,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo,
DISTINTA_CASSIERE_DET.PG_DISTINTA,
TIPO_DOCUMENTO_AMM.DS_TIPO_DOCUMENTO_AMM,
ban.CAB,
ban.ABI,
ban.NUMERO_CONTO,
nvl(ban.CIN,' '),
ban.INTESTAZIONE,
ban.codice_iban
FROM  TERZO,COMUNE,RIF_MODALITA_PAGAMENTO,ANTICIPO,UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b,DISTINTA_CASSIERE_DET,TIPO_DOCUMENTO_AMM , MANDATO_RIGA , MANDATO
 ,terzo terzo_uo,banca ban
WHERE
MANDATO.STATO='E'
AND MANDATO.STATO_TRASMISSIONE='T'
AND MANDATO.TI_MANDATO='P'
AND MANDATO_RIGA.ESERCIZIO=MANDATO.ESERCIZIO
AND MANDATO_RIGA.PG_MANDATO=MANDATO.PG_MANDATO
AND MANDATO_RIGA.CD_CDS=MANDATO.CD_CDS
AND MANDATO_RIGA.CD_TERZO=TERZO.CD_TERZO
AND TERZO.PG_COMUNE_SEDE=COMUNE.PG_COMUNE
AND RIF_MODALITA_PAGAMENTO.CD_MODALITA_PAG=MANDATO_RIGA.CD_MODALITA_PAG
AND MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM='ANTICIPO'
AND ANTICIPO.PG_ANTICIPO=MANDATO_RIGA.PG_DOC_AMM
AND ANTICIPO.CD_CDS=MANDATO_RIGA.CD_CDS_DOC_AMM
AND ANTICIPO.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND ANTICIPO.CD_UNITA_ORGANIZZATIVA=MANDATO_RIGA.CD_UO_DOC_AMM
AND b.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_CDS_ORIGINE
AND a.CD_UNITA_ORGANIZZATIVA(+)=MANDATO.CD_UO_ORIGINE
AND DISTINTA_CASSIERE_DET.ESERCIZIO=MANDATO_RIGA.ESERCIZIO
AND DISTINTA_CASSIERE_DET.CD_CDS_origine=MANDATO_RIGA.CD_CDS
AND DISTINTA_CASSIERE_DET.PG_MANDATO=MANDATO_RIGA.PG_MANDATO
AND TIPO_DOCUMENTO_AMM.CD_TIPO_DOCUMENTO_AMM=MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM
and terzo_uo.cd_unita_organizzativa  = MANDATO.CD_UNITA_ORGANIZZATIVA
and ban.CD_TERZO			 = terzo_uo.CD_TERZO
and ban.FL_CC_CDS			 = 'Y'
and ban.FL_CANCELLATO  = 'N';

   COMMENT ON TABLE "PRT_AVV_MND"  IS 'Vista di stampa Avviso di Pagamento Mandato';
