--------------------------------------------------------
--  DDL for View PRT_SINTESI_LDA_PDG_ENT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_SINTESI_LDA_PDG_ENT" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "CD_LINEA_ATTIVITA", "CD_FUNZIONE", "CD_NATURA", "DS_LINEA_ATTIVITA", "CD_INSIEME_LA", "IM_RA_RCE", "IM_RC_ESRC_ESR", "IM_RE_A2_ENTRATE", "IM_RG_A3_ENTRATE", "RICAVO", "IM_RB_RSE", "IM_RD_A2_RICAVI", "IM_RF_A3_RICAVI") AS 
  SELECT ESERCIZIO, CDR, TI_APPARTENENZA, TI_GESTIONE, CD_ELEMENTO_VOCE,
        CD_LINEA_ATTIVITA, CD_FUNZIONE, CD_NATURA, DS_LINEA_ATTIVITA, CD_INSIEME_LA,
        SUM(IM_RA_RCE), SUM(IM_RC_ESRC_ESR), SUM(IM_RE_A2_ENTRATE), SUM(IM_RG_A3_ENTRATE), SUM(RICAVO),
        SUM(IM_RB_RSE), SUM(IM_RD_A2_RICAVI), SUM(IM_RF_A3_RICAVI)
FROM
    (
--
-- Date: 27/10/2003
-- Version: 1.0
--
-- VVista di estrazione dati dai piani di gestione per le situazioni per lda  Ricavi/Entrate
--
-- History
--
-- Date :27/10/2003
-- Version: 1.0
-- Creazione
-- (effettuate alcune modifiche per ottimizzazione-Cineca)
--
-- Body
--
-- Estrae i dettagli del PDG relativi a ricavi ed entrate anno1 anno2 anno3, aggregati
-- per cdr, lda, voce di bilancio
-- seleziona i dettagli con stato=Y confermato
-- mette in join la tabella lda per estrarre natura, funzione, descrizione e insieme
SELECT
PDG_PREVENTIVO_ETR_DET.ESERCIZIO,
PDG_PREVENTIVO_ETR_DET.CD_CENTRO_RESPONSABILITA CDR,
PDG_PREVENTIVO_ETR_DET.TI_APPARTENENZA,
PDG_PREVENTIVO_ETR_DET.TI_GESTIONE,
PDG_PREVENTIVO_ETR_DET.CD_ELEMENTO_VOCE,
PDG_PREVENTIVO_ETR_DET.CD_LINEA_ATTIVITA,
LINEA_ATTIVITA.CD_FUNZIONE,
LINEA_ATTIVITA.CD_NATURA,
LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
LINEA_ATTIVITA.CD_INSIEME_LA,
-- ENTRATE anno 1
SUM(PDG_PREVENTIVO_ETR_DET.IM_RA_RCE) IM_RA_RCE,
SUM(PDG_PREVENTIVO_ETR_DET.IM_RC_ESR) IM_RC_ESRC_ESR,
-- ENTRATE  anno 2
SUM(PDG_PREVENTIVO_ETR_DET.IM_RE_A2_ENTRATE) IM_RE_A2_ENTRATE,
-- ENTRATE  anno 3
SUM(PDG_PREVENTIVO_ETR_DET.IM_RG_A3_ENTRATE) IM_RG_A3_ENTRATE,
-- RICAVI  anno 1
 SUM(PDG_PREVENTIVO_ETR_DET.IM_RA_RCE) RICAVO,
 SUM(PDG_PREVENTIVO_ETR_DET.IM_RB_RSE) IM_RB_RSE,
 -- RICAVI  anno 2
 SUM(PDG_PREVENTIVO_ETR_DET.IM_RD_A2_RICAVI) IM_RD_A2_RICAVI,
 -- RICAVI  anno 3
 SUM(PDG_PREVENTIVO_ETR_DET.IM_RF_A3_RICAVI) IM_RF_A3_RICAVI
FROM
PDG_PREVENTIVO_ETR_DET ,
LINEA_ATTIVITA
WHERE
PDG_PREVENTIVO_ETR_DET.STATO = 'Y' AND
LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA = PDG_PREVENTIVO_ETR_DET.CD_CENTRO_RESPONSABILITA AND
LINEA_ATTIVITA.CD_LINEA_ATTIVITA = PDG_PREVENTIVO_ETR_DET.CD_LINEA_ATTIVITA AND
PDG_PREVENTIVO_ETR_DET.TI_GESTIONE = 'E' AND
PDG_PREVENTIVO_ETR_DET.TI_APPARTENENZA='C'
GROUP BY PDG_PREVENTIVO_ETR_DET.ESERCIZIO,
PDG_PREVENTIVO_ETR_DET.CD_CENTRO_RESPONSABILITA,
PDG_PREVENTIVO_ETR_DET.CD_LINEA_ATTIVITA,
PDG_PREVENTIVO_ETR_DET.TI_APPARTENENZA,
PDG_PREVENTIVO_ETR_DET.TI_GESTIONE,
PDG_PREVENTIVO_ETR_DET.CD_ELEMENTO_VOCE,
PDG_PREVENTIVO_ETR_DET.STATO,
PDG_PREVENTIVO_ETR_DET.CATEGORIA_DETTAGLIO,
LINEA_ATTIVITA.CD_FUNZIONE,
LINEA_ATTIVITA.CD_NATURA,
LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
LINEA_ATTIVITA.CD_INSIEME_LA
Union All
     -- recupero i dati di previsione relativi alla competenza dai pdg con la voce di bilancio
     -- sulla nuova tabella previsionale PDG_MODULO_ENTRATE_GEST
Select PDG_MODULO_ENTRATE_GEST.ESERCIZIO ESERCIZIO,
            PDG_MODULO_ENTRATE_GEST.CD_CDR_ASSEGNATARIO CDR,
            PDG_MODULO_ENTRATE_GEST.TI_APPARTENENZA,
            PDG_MODULO_ENTRATE_GEST.TI_gestione,
            PDG_MODULO_ENTRATE_GEST.CD_ELEMENTO_VOCE voce,
            PDG_MODULO_ENTRATE_GEST.CD_LINEA_ATTIVITA lda,
            LINEA_ATTIVITA.CD_FUNZIONE,
            LINEA_ATTIVITA.CD_NATURA,
            LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
            LINEA_ATTIVITA.CD_INSIEME_LA,
            0 IM_RA_RCE,
            NVL(PDG_MODULO_ENTRATE_GEST.IM_ENTRATA, 0) IM_RC_ESRC_ESR,
            0 IM_RE_A2_ENTRATE,
            0 IM_RG_A3_ENTRATE,
            0 RICAVO,
            0 IM_RB_RSE,
            0 IM_RD_A2_RICAVI,
            0 IM_RF_A3_RICAVI
     From
          PDG_MODULO_ENTRATE_GEST,
          ELEMENTO_VOCE,
          linea_attivita
     Where
          --Join tra "PDG_MODULO_ENTRATE_GEST" e "ELEMENTO_VOCE"
          PDG_MODULO_ENTRATE_GEST.ESERCIZIO = ELEMENTO_VOCE.ESERCIZIO And
          PDG_MODULO_ENTRATE_GEST.TI_GESTIONE = ELEMENTO_VOCE.TI_GESTIONE And
          PDG_MODULO_ENTRATE_GEST.TI_APPARTENENZA = ELEMENTO_VOCE.TI_APPARTENENZA And
          PDG_MODULO_ENTRATE_GEST.CD_ELEMENTO_VOCE = ELEMENTO_VOCE.CD_ELEMENTO_VOCE and
          PDG_MODULO_ENTRATE_GEST.CD_CDR_ASSEGNATARIO = LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA AND
          PDG_MODULO_ENTRATE_GEST.CD_LINEA_ATTIVITA = LINEA_ATTIVITA.CD_LINEA_ATTIVITA
)
GROUP BY ESERCIZIO, CDR, TI_APPARTENENZA, TI_GESTIONE, CD_ELEMENTO_VOCE,
        CD_LINEA_ATTIVITA, CD_FUNZIONE, CD_NATURA, DS_LINEA_ATTIVITA, CD_INSIEME_LA
;

   COMMENT ON TABLE "PRT_SINTESI_LDA_PDG_ENT"  IS 'Vista di estrazione dati dai piani di gestione per le situazioni per lda  Ricavi/Entrate';
