--------------------------------------------------------
--  DDL for View PRT_PDG_SPE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_PDG_SPE" ("ESERCIZIO", "PESO_DIPARTIMENTO", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO", "CD_PROGETTO", "DS_PROGETTO", "CD_COMMESSA", "DS_COMMESSA", "CD_MODULO", "DS_MODULO", "TIPO_PROGETTO", "DS_TIPO_PROGETTO", "CDS", "DS_CDS", "UO", "TIPO_UO", "DS_UO", "CDR", "CD_LINEA_ATTIVITA", "TITOLO", "DS_TITOLO", "CODICE_CLAS_SPESA", "DS_CLASSIFICAZIONE_SPESA", "ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "ORIGINE", "CATEGORIA_DETTAGLIO", "CD_FUNZIONE", "NATURA", "DS_NATURA", "PG_SPESA", "FL_RIBALTATO", "SPESE_PROPRIE", "SPESE_ALTRA_UO", "AMMORTAMENTI", "RIMANENZE", "ALTRI_COSTI", "VERSO_ALTRO_CDR", "SPESE_COSTI_ALTRUI", "SPESE_COMUNI_AREA") AS 
  Select
--
-- Date: 20/04/2005
-- Version: 1.0
--
-- Vista per la stampa del PDG per Dipartimento/Istituto parte spesa
--
-- History:
--
-- Date: 20/04/2005
-- Version: 1.0
-- Creazione
--
-- Body:
--
ESERCIZIO,
PESO_DIPARTIMENTO,
CD_DIPARTIMENTO,
DS_DIPARTIMENTO,
CD_PROGETTO,
DS_PROGETTO,
CD_COMMESSA,
DS_COMMESSA,
CD_MODULO,
DS_MODULO,
TIPO_PROGETTO,
ds_tipo_progetto,
CDS,
DS_CDS ,
UO,
TIPO_UO,
DS_UO,
CDR,
CD_LINEA_ATTIVITA,
TITOLO,
'Titolo'||' '||TITOLO||' '||'-'||' '||DS_TITOLO,
TITOLO||'.'||CODICE_CLAS_SPESA,
DS_CLASSIFICAZIONE_SPESA,
ELEMENTO_VOCE,
ds_elemento_voce,
ORIGINE,
CATEGORIA_DETTAGLIO,
cd_FUNZIONE,
NATURA,
ds_natura,
PG_SPESA,
FL_RIBALTATO,
decode(natura,5,0,V_PDG_SPE.IM_RI_CCS_SPESE_ODC+V_PDG_SPE.IM_RK_CCS_SPESE_OGC+
        V_PDG_SPE.IM_RQ_SSC_COSTI_ODC+V_PDG_SPE.IM_RS_SSC_COSTI_OGC),
V_PDG_SPE.IM_RJ_CCS_SPESE_ODC_ALTRA_UO+V_PDG_SPE.IM_RL_CCS_SPESE_OGC_ALTRA_UO+
        V_PDG_SPE.IM_RR_SSC_COSTI_ODC_ALTRA_UO+V_PDG_SPE.IM_RT_SSC_COSTI_OGC_ALTRA_UO,
V_PDG_SPE.IM_RM_CSS_AMMORTAMENTI,
V_PDG_SPE.IM_RN_CSS_RIMANENZE,
V_PDG_SPE.IM_RO_CSS_ALTRI_COSTI,
V_PDG_SPE.IM_RP_CSS_VERSO_ALTRO_CDR ,
V_PDG_SPE.IM_RU_SPESE_COSTI_ALTRUI,
Decode(FL_RIBALTATO,'N',
       decode(NATURA,5,V_PDG_SPE.IM_RI_CCS_SPESE_ODC +
                       V_PDG_SPE.IM_RK_CCS_SPESE_OGC +
                       V_PDG_SPE.IM_RQ_SSC_COSTI_ODC +
                       V_PDG_SPE.IM_RS_SSC_COSTI_OGC,0),
       Decode(NATURA,5,V_PDG_SPE.IM_RP_CSS_VERSO_ALTRO_CDR,0))
From V_PDG_SPE
Where  (
      (FL_RIBALTATO = 'Y' And
       TIPO_UO != 'AREA' And
       NATURA != '5'
      )
      Or
      (FL_RIBALTATO = 'N')
        )

;

   COMMENT ON TABLE "PRT_PDG_SPE"  IS 'Vista per la stampa del PDG per Dipartimento/Istituto parte spesa';
