--------------------------------------------------------
--  DDL for View PRT_STAMPA_ORDINE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_STAMPA_ORDINE" ("NUM_ORD", "DT_ORD", "CD_CDS", "ESERCIZIO", "VOCE_BIL", "ESERCIZIO_ORIG", "OBBLIG", "TERZO", "STATO", "NOTE", "DETT_ORD", "DESCR_DETT", "QTA", "IMP_UNI", "IMP_IVA", "CD_UO", "FORN_SEDE", "FORN_VIA", "FORN_NUM", "FORN_CAP", "FORN_CITTA", "FORN_PROV", "UO_SEDE", "UO_VIA", "UO_NUM", "UO_CAP", "UO_CITTA", "UO_PROV", "FORN_NAZ", "UO_NAZ", "ABI", "CAB", "NUM_CC", "IBAN", "DESCR_BANCA", "TERMINI_PAG", "MOD_PAG", "DESCR_TIPO_CONSEGNA", "UO_TELEFONO", "UO_FAX", "CLAUSOLA", "EMAIL") AS 
  SELECT
--
-- Date: 09/11/2010
-- Version: 1.6
--
-- Stampa Ordine
--
-- History:
--
-- Date: 13/05/2003
-- Version: 1.0
--
-- date: 18/06/2003
-- Version 1.1
-- aggiunta condizione di outerjoin sulla ricerca di abi e cab della banca
--
-- date: 07/07/2003
-- Version 1.2
-- aggiunta tabella PROVINCIA e colonne UO_PROV - FORN_PROV
--
-- date: 01/12/2003
-- Version 1.3
-- eliminata tabella PROVINCIA e inserita seconda NAZIONE per fornitore estero
--
-- Date: 18/07/2006
-- Version: 1.4
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Date: 18/11/2008
-- Version: 1.5
-- Aggiunti i campi UO_TELEFONO e UO_FAX come da richiesta Help-Desk
--
-- Date: 09/11/2010
-- Version: 1.6
-- Aggiunto il campo CLAUSOLA
--
-- Date: 01/12/2010
-- Version: 1.7
-- Aggiunto il campo EMAIL come da richiesta Help-Desk(GREGORI)
--
-- Body
ORDINE.PG_ORDINE,
ORDINE.DT_REGISTRAZIONE,
ORDINE.CD_CDS,
ORDINE.ESERCIZIO,
ORDINE.CD_ELEMENTO_VOCE,
ORDINE.ESERCIZIO_ORI_OBBLIGAZIONE,
ORDINE.PG_OBBLIGAZIONE,
ORDINE.CD_TERZO,
ORDINE.STATO,
ORDINE.NOTE,
ORDINE_DETT.PG_DETTAGLIO,
ORDINE_DETT.DS_DETTAGLIO,
ORDINE_DETT.QUANTITA,
ORDINE_DETT.IM_UNITARIO,
ORDINE_DETT.IM_IVA,
OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA,
A.DENOMINAZIONE_SEDE,
A.VIA_SEDE,
A.NUMERO_CIVICO_SEDE,
A.CAP_COMUNE_SEDE,
C.DS_COMUNE,
C.CD_PROVINCIA,
B.DENOMINAZIONE_SEDE,
B.VIA_SEDE,
B.NUMERO_CIVICO_SEDE,
B.CAP_COMUNE_SEDE,
D.DS_COMUNE,
D.CD_PROVINCIA,
E.DS_NAZIONE,
F.DS_NAZIONE,
BANCA.ABI,
BANCA.CAB,
BANCA.NUMERO_CONTO,
nvl(banca.CODICE_IBAN,'') iban,
ABICAB.DS_ABICAB,
RIF_TERMINI_PAGAMENTO.DS_TERMINI_PAG,
RIF_MODALITA_PAGAMENTO.DS_MODALITA_PAG,
TIPO_CONSEGNA.DS_TIPO_CONSEGNA,
CONTATTO.TELEFONO,
CONTATTO.FAX,
ORDINE.CLAUSOLA,
CONTATTO.EMAIL
FROM ORDINE,ORDINE_DETT,OBBLIGAZIONE,
TERZO  A,TERZO B,
COMUNE C,COMUNE D,
NAZIONE E,NAZIONE F,BANCA,ABICAB,RIF_TERMINI_PAGAMENTO,
RIF_MODALITA_PAGAMENTO,TIPO_CONSEGNA,CONTATTO
WHERE
ORDINE.PG_ORDINE = ORDINE_DETT.PG_ORDINE AND
ORDINE.CD_CDS = ORDINE_DETT.CD_CDS AND
ORDINE.ESERCIZIO = ORDINE_DETT.ESERCIZIO AND
ORDINE.ESERCIZIO_ORI_OBBLIGAZIONE = OBBLIGAZIONE.ESERCIZIO_ORIGINALE AND
ORDINE.PG_OBBLIGAZIONE = OBBLIGAZIONE.PG_OBBLIGAZIONE AND
ORDINE.CD_CDS = OBBLIGAZIONE.CD_CDS AND
ORDINE.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO AND
ORDINE.PG_BANCA = BANCA.PG_BANCA AND
ORDINE.CD_TERMINI_PAG = RIF_TERMINI_PAGAMENTO.CD_TERMINI_PAG AND
ORDINE.CD_MODALITA_PAG = RIF_MODALITA_PAGAMENTO.CD_MODALITA_PAG AND
ORDINE.CD_TIPO_CONSEGNA = TIPO_CONSEGNA.CD_TIPO_CONSEGNA AND
A.CD_TERZO = ORDINE.CD_TERZO AND
A.PG_COMUNE_SEDE = C.PG_COMUNE AND
B.PG_COMUNE_SEDE = D.PG_COMUNE AND
C.PG_NAZIONE = E.PG_NAZIONE AND
D.PG_NAZIONE = F.PG_NAZIONE AND
A.CD_TERZO = BANCA.CD_TERZO AND
ABICAB.ABI(+)=BANCA.ABI AND
ABICAB.CAB(+)=BANCA.CAB AND
OBBLIGAZIONE.CD_UO_ORIGINE = B.CD_UNITA_ORGANIZZATIVA and
b.dt_fine_rapporto is null
and b.cd_terzo in( select min(terzo.cd_terzo) from terzo where
terzo.cd_unita_organizzativa = OBBLIGAZIONE.CD_UO_ORIGINE
and terzo.dt_fine_rapporto is null)
And B.CD_TERZO = CONTATTO.CD_TERZO(+)
ORDER BY ORDINE_DETT.PG_ORDINE,ORDINE_DETT.PG_DETTAGLIO;
