--------------------------------------------------------
--  DDL for View PRT_STAMPA_PERSONALE_DANIELA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_STAMPA_PERSONALE_DANIELA" ("TIPO", "ESERCIZIO", "MESE", "UO", "CDR", "ALTRA_UO", "CD_PROGETTO", "DS_PROGETTO", "CD_DIPARTIMENTO", "CD_COMMESSA", "DS_COMMESSA", "PG_PROGETTO", "CD_MODULO", "DS_MODULO", "CD_LINEA_ATTIVITA", "DS_LINEA_ATTIVITA", "ID_MATRICOLA", "NOMINATIVO", "DS_PROFILO", "PERCENT_A1", "PERCENT_A2", "PERCENT_A3", "STIPENDIO", "CDS", "TIPO_RAPPORTO", "IMPORTO_TFR") AS 
  SELECT
  'Somme non ripartite' Tipo,
  COSTO_DEL_DIPENDENTE.ESERCIZIO,
  COSTO_DEL_DIPENDENTE.MESE,
  COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  COSTO_DEL_DIPENDENTE.ID_MATRICOLA,
  COSTO_DEL_DIPENDENTE.NOMINATIVO,
  COSTO_DEL_DIPENDENTE.DS_PROFILO,
  0,
  0,
  0,
  SUM(COSTO_DEL_DIPENDENTE.IM_A1 + COSTO_DEL_DIPENDENTE.IM_ONERI_CNR_A1 +
      COSTO_DEL_DIPENDENTE.IM_TFR_A1) STIPENDIO,
  DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
FROM
   COSTO_DEL_DIPENDENTE,  UNITA_ORGANIZZATIVA U
WHERE NOT EXISTS (SELECT 1 FROM  ASS_CDP_LA
                  WHERE ASS_CDP_LA.MESE  =  COSTO_DEL_DIPENDENTE.MESE
                    AND ASS_CDP_LA.ESERCIZIO  =  COSTO_DEL_DIPENDENTE.ESERCIZIO
                    AND ASS_CDP_LA.ID_MATRICOLA  =  COSTO_DEL_DIPENDENTE.ID_MATRICOLA/*
                    And COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA =
                                            (Select CD_UNITA_ORGANIZZATIVA From  CDR
                                                  Where CD_CENTRO_RESPONSABILITA = ASS_CDP_LA.CD_CENTRO_RESPONSABILITA)*/)
  AND NOT EXISTS (SELECT 1 FROM  ASS_CDP_UO
                  WHERE ASS_CDP_UO.MESE  =  COSTO_DEL_DIPENDENTE.MESE
                    AND ASS_CDP_UO.ESERCIZIO  =  COSTO_DEL_DIPENDENTE.ESERCIZIO
                    AND ASS_CDP_UO.ID_MATRICOLA  =  COSTO_DEL_DIPENDENTE.ID_MATRICOLA
                    AND ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA = COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA)
  AND U.CD_UNITA_ORGANIZZATIVA  = COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA
GROUP BY   'Somme non ripartite',
  COSTO_DEL_DIPENDENTE.ESERCIZIO,
  COSTO_DEL_DIPENDENTE.MESE,
  COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  COSTO_DEL_DIPENDENTE.ID_MATRICOLA,
  COSTO_DEL_DIPENDENTE.NOMINATIVO,
  COSTO_DEL_DIPENDENTE.DS_PROFILO,
  0,
  0,
  0,
  DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
UNION ALL
SELECT
  'Somme non ripartite',
   COSTO_DEL_DIPENDENTE.ESERCIZIO,
   COSTO_DEL_DIPENDENTE.MESE,
   ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA,
   NULL,
   COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA ALTRA_UO,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   ASS_CDP_UO.ID_MATRICOLA,
   COSTO_DEL_DIPENDENTE.NOMINATIVO,
   COSTO_DEL_DIPENDENTE.DS_PROFILO,
   0,
   0,
   0,
   SUM( COSTO_DEL_DIPENDENTE.IM_A1 +  COSTO_DEL_DIPENDENTE.IM_ONERI_CNR_A1 +
       COSTO_DEL_DIPENDENTE.IM_TFR_A1) STIPENDIO,
   DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
FROM
   ASS_CDP_UO,
   COSTO_DEL_DIPENDENTE,
   UNITA_ORGANIZZATIVA U
WHERE ASS_CDP_UO.MESE  =  COSTO_DEL_DIPENDENTE.MESE
  AND ASS_CDP_UO.ESERCIZIO  =  COSTO_DEL_DIPENDENTE.ESERCIZIO
  AND ASS_CDP_UO.ID_MATRICOLA  =  COSTO_DEL_DIPENDENTE.ID_MATRICOLA
  AND NOT EXISTS (SELECT 1 FROM  ASS_CDP_LA
                   WHERE ASS_CDP_LA.MESE  =  COSTO_DEL_DIPENDENTE.MESE
                     AND ASS_CDP_LA.ESERCIZIO  =  COSTO_DEL_DIPENDENTE.ESERCIZIO
                     AND ASS_CDP_LA.ID_MATRICOLA  =  COSTO_DEL_DIPENDENTE.ID_MATRICOLA
                     /*And COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA =
                        (Select CD_UNITA_ORGANIZZATIVA From  CDR
                          Where CD_CENTRO_RESPONSABILITA = ASS_CDP_LA.CD_CENTRO_RESPONSABILITA)*/)
  AND U.CD_UNITA_ORGANIZZATIVA  = COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA
GROUP BY
  'Somme non ripartite',
   COSTO_DEL_DIPENDENTE.ESERCIZIO,
   COSTO_DEL_DIPENDENTE.MESE,
   ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA,
   NULL,
   COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   NULL,
   ASS_CDP_UO.ID_MATRICOLA,
   COSTO_DEL_DIPENDENTE.NOMINATIVO,
   COSTO_DEL_DIPENDENTE.DS_PROFILO,
   0,
   0,
   0,
   DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
UNION ALL
SELECT
  'Somme ripartite',
   COSTO_DEL_DIPENDENTE.ESERCIZIO,
   COSTO_DEL_DIPENDENTE.MESE,
   COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA,
   LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA,
   NULL ALTRA_UO,
   PROGETTO.CD_PROGETTO,
   PROGETTO.DS_PROGETTO,
   PROGETTO.CD_DIPARTIMENTO,
   COMMESSA.CD_PROGETTO,
   COMMESSA.DS_PROGETTO,
   MODULO.PG_PROGETTO,
   MODULO.CD_PROGETTO,
   MODULO.DS_PROGETTO,
   LINEA_ATTIVITA.CD_LINEA_ATTIVITA,
   LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
   COSTO_DEL_DIPENDENTE.ID_MATRICOLA,
   COSTO_DEL_DIPENDENTE.NOMINATIVO,
   COSTO_DEL_DIPENDENTE.DS_PROFILO,
   ASS_CDP_LA.PRC_LA_A1 PERCENT_A1,
   ASS_CDP_LA.PRC_LA_A2 PERCENT_A2,
   ASS_CDP_LA.PRC_LA_A3 PERCENT_A3,
   SUM( COSTO_DEL_DIPENDENTE.IM_A1 +  COSTO_DEL_DIPENDENTE.IM_ONERI_CNR_A1 +
       COSTO_DEL_DIPENDENTE.IM_TFR_A1) STIPENDIO,
   DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
FROM
   LINEA_ATTIVITA,
   ASS_CDP_LA,
   COSTO_DEL_DIPENDENTE,
   UNITA_ORGANIZZATIVA U,
   PROGETTO_PREV COMMESSA,
   PROGETTO_PREV MODULO,
   PROGETTO_PREV PROGETTO
WHERE ASS_CDP_LA.FL_DIP_ALTRA_UO = 'N'
  AND ASS_CDP_LA.CD_LINEA_ATTIVITA= LINEA_ATTIVITA.CD_LINEA_ATTIVITA
  AND LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA= ASS_CDP_LA.CD_CENTRO_RESPONSABILITA
  AND ASS_CDP_LA.MESE  =   COSTO_DEL_DIPENDENTE.MESE
  AND ASS_CDP_LA.ESERCIZIO  =   COSTO_DEL_DIPENDENTE.ESERCIZIO
  AND ASS_CDP_LA.ID_MATRICOLA  =   COSTO_DEL_DIPENDENTE.ID_MATRICOLA
  AND U.CD_UNITA_ORGANIZZATIVA  = COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA
  AND LINEA_ATTIVITA.PG_PROGETTO = MODULO.PG_PROGETTO(+)
  AND (MODULO.ESERCIZIO  IS NULL OR MODULO.ESERCIZIO = COSTO_DEL_DIPENDENTE.ESERCIZIO)
  AND MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO(+)
  AND MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO(+)
  AND COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO(+)
  AND COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO(+)
GROUP BY 'Somme ripartite',
   COSTO_DEL_DIPENDENTE.ESERCIZIO,
   COSTO_DEL_DIPENDENTE.MESE,
   COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA,
   LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA,
   NULL,
   PROGETTO.CD_PROGETTO,
   PROGETTO.DS_PROGETTO,
   PROGETTO.CD_DIPARTIMENTO,
   COMMESSA.CD_PROGETTO,
   COMMESSA.DS_PROGETTO,
   MODULO.PG_PROGETTO,
   MODULO.CD_PROGETTO,
   MODULO.DS_PROGETTO,
   LINEA_ATTIVITA.CD_LINEA_ATTIVITA,
   LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
   COSTO_DEL_DIPENDENTE.ID_MATRICOLA,
   COSTO_DEL_DIPENDENTE.NOMINATIVO,
   COSTO_DEL_DIPENDENTE.DS_PROFILO,
   ASS_CDP_LA.PRC_LA_A1,
   ASS_CDP_LA.PRC_LA_A2,
   ASS_CDP_LA.PRC_LA_A3,
   DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
UNION ALL
SELECT
  'Somme assegnate ad altra UO',
   COSTO_DEL_DIPENDENTE.ESERCIZIO,
   COSTO_DEL_DIPENDENTE.MESE,
   COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA,
   LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA,
   ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA ALTRA_UO,
   PROGETTO.CD_PROGETTO,
   PROGETTO.DS_PROGETTO,
   PROGETTO.CD_DIPARTIMENTO,
   COMMESSA.CD_PROGETTO,
   COMMESSA.DS_PROGETTO,
   MODULO.PG_PROGETTO,
   MODULO.CD_PROGETTO,
   MODULO.DS_PROGETTO,
   LINEA_ATTIVITA.CD_LINEA_ATTIVITA,
   LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
   COSTO_DEL_DIPENDENTE.ID_MATRICOLA,
   COSTO_DEL_DIPENDENTE.NOMINATIVO,
   COSTO_DEL_DIPENDENTE.DS_PROFILO,
   NVL("ASS_CDP_UO"."PRC_UO_A1", 100) * "ASS_CDP_LA"."PRC_LA_A1" / 100 PERCENT_A1,
   NVL("ASS_CDP_UO"."PRC_UO_A2", 100) * "ASS_CDP_LA"."PRC_LA_A2" / 100 PERCENT_A2,
   NVL("ASS_CDP_UO"."PRC_UO_A3", 100) * "ASS_CDP_LA"."PRC_LA_A3" / 100 PERCENT_A3,
   SUM( COSTO_DEL_DIPENDENTE.IM_A1 +  COSTO_DEL_DIPENDENTE.IM_ONERI_CNR_A1 +
        COSTO_DEL_DIPENDENTE.IM_TFR_A1) STIPENDIO,
   DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
FROM
   LINEA_ATTIVITA,
   ASS_CDP_LA,
   ASS_CDP_UO,
   COSTO_DEL_DIPENDENTE,
   UNITA_ORGANIZZATIVA U,
   PROGETTO_PREV COMMESSA,
   PROGETTO_PREV MODULO,
   PROGETTO_PREV PROGETTO
WHERE ASS_CDP_LA.FL_DIP_ALTRA_UO = 'Y'
  AND ASS_CDP_LA.CD_LINEA_ATTIVITA= LINEA_ATTIVITA.CD_LINEA_ATTIVITA
  AND ASS_CDP_UO.ID_MATRICOLA= ASS_CDP_LA.ID_MATRICOLA
  AND LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA= ASS_CDP_LA.CD_CENTRO_RESPONSABILITA
  AND ASS_CDP_UO.MESE= ASS_CDP_LA.MESE
  AND ASS_CDP_UO.ESERCIZIO= ASS_CDP_LA.ESERCIZIO
  AND ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA = (SELECT CD_UNITA_ORGANIZZATIVA FROM  CDR
                  WHERE CD_CENTRO_RESPONSABILITA = ASS_CDP_LA.CD_CENTRO_RESPONSABILITA)
  AND ASS_CDP_LA.MESE  =   COSTO_DEL_DIPENDENTE.MESE
  AND ASS_CDP_LA.ESERCIZIO  =   COSTO_DEL_DIPENDENTE.ESERCIZIO
  AND ASS_CDP_LA.ID_MATRICOLA  =   COSTO_DEL_DIPENDENTE.ID_MATRICOLA
  AND U.CD_UNITA_ORGANIZZATIVA  = COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA
  AND LINEA_ATTIVITA.PG_PROGETTO = MODULO.PG_PROGETTO(+)
  AND (MODULO.ESERCIZIO  IS NULL OR MODULO.ESERCIZIO = COSTO_DEL_DIPENDENTE.ESERCIZIO)
  AND MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO(+)
  AND MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO(+)
  AND COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO(+)
  AND COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO(+)
GROUP BY 'Somme assegnate ad altra UO',
   COSTO_DEL_DIPENDENTE.ESERCIZIO,
   COSTO_DEL_DIPENDENTE.MESE,
   COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA,
   LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA,
   ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA,
   PROGETTO.CD_PROGETTO,
   PROGETTO.DS_PROGETTO,
   PROGETTO.CD_DIPARTIMENTO,
   COMMESSA.CD_PROGETTO,
   COMMESSA.DS_PROGETTO,
   MODULO.PG_PROGETTO,
   MODULO.CD_PROGETTO,
   MODULO.DS_PROGETTO,
   LINEA_ATTIVITA.CD_LINEA_ATTIVITA,
   LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
   COSTO_DEL_DIPENDENTE.ID_MATRICOLA,
   COSTO_DEL_DIPENDENTE.NOMINATIVO,
   COSTO_DEL_DIPENDENTE.DS_PROFILO,
   NVL("ASS_CDP_UO"."PRC_UO_A1", 100) * "ASS_CDP_LA"."PRC_LA_A1" / 100,
   NVL("ASS_CDP_UO"."PRC_UO_A2", 100) * "ASS_CDP_LA"."PRC_LA_A2" / 100,
   NVL("ASS_CDP_UO"."PRC_UO_A3", 100) * "ASS_CDP_LA"."PRC_LA_A3" / 100,
   DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
UNION ALL
SELECT
  'Somme assegnate da altra UO',
   COSTO_DEL_DIPENDENTE.ESERCIZIO,
   COSTO_DEL_DIPENDENTE.MESE,
   ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA,
   LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA,
   COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA ALTRA_UO,
   PROGETTO.CD_PROGETTO,
   PROGETTO.DS_PROGETTO,
   PROGETTO.CD_DIPARTIMENTO,
   COMMESSA.CD_PROGETTO,
   COMMESSA.DS_PROGETTO,
   MODULO.PG_PROGETTO,
   MODULO.CD_PROGETTO,
   MODULO.DS_PROGETTO,
   LINEA_ATTIVITA.CD_LINEA_ATTIVITA,
   LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
   ASS_CDP_UO.ID_MATRICOLA,
   COSTO_DEL_DIPENDENTE.NOMINATIVO,
   COSTO_DEL_DIPENDENTE.DS_PROFILO,
   NVL("ASS_CDP_UO"."PRC_UO_A1", 100) * "ASS_CDP_LA"."PRC_LA_A1" / 100 PERCENT_A1,
   NVL("ASS_CDP_UO"."PRC_UO_A2", 100) * "ASS_CDP_LA"."PRC_LA_A2" / 100 PERCENT_A2,
   NVL("ASS_CDP_UO"."PRC_UO_A3", 100) * "ASS_CDP_LA"."PRC_LA_A3" / 100 PERCENT_A3,
   SUM( COSTO_DEL_DIPENDENTE.IM_A1 +  COSTO_DEL_DIPENDENTE.IM_ONERI_CNR_A1 +
       COSTO_DEL_DIPENDENTE.IM_TFR_A1) STIPENDIO,
   DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
FROM
   LINEA_ATTIVITA,
   ASS_CDP_LA,
   ASS_CDP_UO,
   COSTO_DEL_DIPENDENTE,
   UNITA_ORGANIZZATIVA U,
   PROGETTO_PREV COMMESSA,
   PROGETTO_PREV MODULO,
   PROGETTO_PREV PROGETTO
WHERE ASS_CDP_LA.FL_DIP_ALTRA_UO = 'Y'
  AND ASS_CDP_LA.CD_LINEA_ATTIVITA=LINEA_ATTIVITA.CD_LINEA_ATTIVITA
  AND LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA=ASS_CDP_LA.CD_CENTRO_RESPONSABILITA
  AND ASS_CDP_UO.MESE=ASS_CDP_LA.MESE
  AND ASS_CDP_UO.ESERCIZIO=ASS_CDP_LA.ESERCIZIO
  AND ASS_CDP_UO.ID_MATRICOLA=ASS_CDP_LA.ID_MATRICOLA
  AND ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA = (SELECT CD_UNITA_ORGANIZZATIVA FROM  CDR
                  WHERE CD_CENTRO_RESPONSABILITA = ASS_CDP_LA.CD_CENTRO_RESPONSABILITA)
  AND ASS_CDP_LA.MESE  =  COSTO_DEL_DIPENDENTE.MESE
  AND ASS_CDP_LA.ESERCIZIO  =  COSTO_DEL_DIPENDENTE.ESERCIZIO
  AND COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA !=
                 (SELECT CD_UNITA_ORGANIZZATIVA FROM  CDR
                   WHERE CD_CENTRO_RESPONSABILITA = LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA)
  AND ASS_CDP_LA.ID_MATRICOLA  =  COSTO_DEL_DIPENDENTE.ID_MATRICOLA
  AND U.CD_UNITA_ORGANIZZATIVA  = COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA
  AND LINEA_ATTIVITA.PG_PROGETTO = MODULO.PG_PROGETTO(+)
  AND (MODULO.ESERCIZIO  IS NULL OR MODULO.ESERCIZIO = COSTO_DEL_DIPENDENTE.ESERCIZIO)
  AND MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO(+)
  AND MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO(+)
  AND COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO(+)
  AND COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO(+)
GROUP BY
  'Somme assegnate da altra UO',
   COSTO_DEL_DIPENDENTE.ESERCIZIO,
   COSTO_DEL_DIPENDENTE.MESE,
   ASS_CDP_UO.CD_UNITA_ORGANIZZATIVA,
   LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA,
   COSTO_DEL_DIPENDENTE.CD_UNITA_ORGANIZZATIVA,
   PROGETTO.CD_PROGETTO,
   PROGETTO.DS_PROGETTO,
   PROGETTO.CD_DIPARTIMENTO,
   COMMESSA.CD_PROGETTO,
   COMMESSA.DS_PROGETTO,
   MODULO.PG_PROGETTO,
   MODULO.CD_PROGETTO,
   MODULO.DS_PROGETTO,
   LINEA_ATTIVITA.CD_LINEA_ATTIVITA,
   LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
   ASS_CDP_UO.ID_MATRICOLA,
   COSTO_DEL_DIPENDENTE.NOMINATIVO,
   COSTO_DEL_DIPENDENTE.DS_PROFILO,
   NVL("ASS_CDP_UO"."PRC_UO_A1", 100) * "ASS_CDP_LA"."PRC_LA_A1" / 100,
   NVL("ASS_CDP_UO"."PRC_UO_A2", 100) * "ASS_CDP_LA"."PRC_LA_A2" / 100,
   NVL("ASS_CDP_UO"."PRC_UO_A3", 100) * "ASS_CDP_LA"."PRC_LA_A3" / 100,
   DECODE(U.FL_CDS,'N',U.CD_UNITA_PADRE,U.CD_UNITA_ORGANIZZATIVA),
  COSTO_DEL_DIPENDENTE.TI_RAPPORTO,
  COSTO_DEL_DIPENDENTE.IM_TFR_A1
;
