--------------------------------------------------------
--  DDL for View PRT_GENERICI_PASSIVI_VOCE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_GENERICI_PASSIVI_VOCE" ("CD_CS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_DOCUMENTO_GENERICO", "PROGRESSIVO_RIGA", "DS_RIGA", "IM_RIGA", "STATO_COFI", "ESERCIZIO_OBBLIGAZIONE", "ESERCIZIO_ORI_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "PG_OBBLIGAZIONE_SCADENZARIO", "IM_SCADENZA", "CD_ELEMENTO_VOCE") AS 
  SELECT
--
-- Date: 18/07/2006
-- Version: 1.2
--
-- Stampa documenti generici passivi per voce del piano
--
--
-- History:
--
-- Date: 28/07/2004
-- Version: 1.0
--
-- Creazione
--
--
-- Date: 05/08/2004
-- Version: 1.1
--
-- Aggiunto il CDS nella vista e modificato il file rpt
--
-- Date: 18/07/2006
-- Version: 1.2
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body:
    DOCUMENTO_GENERICO_RIGA.CD_CDS,
    DOCUMENTO_GENERICO_RIGA.CD_UNITA_ORGANIZZATIVA,
    DOCUMENTO_GENERICO_RIGA.ESERCIZIO,
    DOCUMENTO_GENERICO_RIGA.PG_DOCUMENTO_GENERICO,
    DOCUMENTO_GENERICO_RIGA.PROGRESSIVO_RIGA,
    DOCUMENTO_GENERICO_RIGA.DS_RIGA,
    DOCUMENTO_GENERICO_RIGA.IM_RIGA,
    DOCUMENTO_GENERICO_RIGA.STATO_COFI,
    DOCUMENTO_GENERICO_RIGA.ESERCIZIO_OBBLIGAZIONE,
    DOCUMENTO_GENERICO_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE,
    DOCUMENTO_GENERICO_RIGA.PG_OBBLIGAZIONE,
    DOCUMENTO_GENERICO_RIGA.PG_OBBLIGAZIONE_SCADENZARIO,
    OBBLIGAZIONE_SCADENZARIO.IM_SCADENZA,
    OBBLIGAZIONE.CD_ELEMENTO_VOCE
FROM
    DOCUMENTO_GENERICO_RIGA DOCUMENTO_GENERICO_RIGA,
    OBBLIGAZIONE_SCADENZARIO OBBLIGAZIONE_SCADENZARIO,
    OBBLIGAZIONE OBBLIGAZIONE
WHERE
DOCUMENTO_GENERICO_RIGA.CD_CDS_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.CD_CDS AND
DOCUMENTO_GENERICO_RIGA.ESERCIZIO_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO AND
DOCUMENTO_GENERICO_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE AND
DOCUMENTO_GENERICO_RIGA.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE AND
DOCUMENTO_GENERICO_RIGA.PG_OBBLIGAZIONE_SCADENZARIO = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO AND
    	OBBLIGAZIONE_SCADENZARIO.CD_CDS = OBBLIGAZIONE.CD_CDS AND
    	OBBLIGAZIONE_SCADENZARIO.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO AND
    	OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE = OBBLIGAZIONE.ESERCIZIO_ORIGINALE AND
    	OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE = OBBLIGAZIONE.PG_OBBLIGAZIONE;

   COMMENT ON TABLE "PRT_GENERICI_PASSIVI_VOCE"  IS 'Stampa documenti generici passivi per voce del piano';
