--------------------------------------------------------
--  DDL for View PRT_AVANZO_DISAVANZO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_AVANZO_DISAVANZO" ("ESER", "CDS", "TIPO", "VOCE_AVANZO_DISAVANZO", "DS_VOCE_AVANZO_DISAVANZO", "INIZIALE", "VAR_PIU", "VAR_MENO", "ASSESTATO", "IMPEGN_ACCERT", "ACCRED_RISCOSS") AS 
  (SELECT
--
-- Date: 02/03/2004
-- Version: 1.0
--
-- Vista di estrazione per avanzo e disavanzo
--
-- History:
--
-- Date: 02/03/2004
-- Version: 1.0
-- Creazione
--
-- Body
--
ESER,CDS, TIPO,
VOCE_AVANZO_DISAVANZO, Prt_Getdes_Vocecap('F', eser, 'C', 'E', VOCE_AVANZO_DISAVANZO, 'C')  AS DS_VOCE_AVANZO,
INIZIALE, VAR_PIU, VAR_MENO, ASSESTATO, IMPEGN_ACCERT, ACCRED_RISCOSS
FROM
-- AVANZO CNR
(SELECT
a.ESERCIZIO eser,
a.CD_CDS cds,
'A_C' AS TIPO,
SUBSTR(a.CD_VOCE,1,9) VOCE_AVANZO_DISAVANZO,
SUM(NVL(a.IM_STANZ_INIZIALE_A1,0)) iniziale,
SUM(NVL(a.VARIAZIONI_PIU,0)) var_piu,
SUM(NVL(a.VARIAZIONI_MENO,0)) var_meno,
SUM((NVL(a.IM_STANZ_INIZIALE_A1,0)+NVL(a.VARIAZIONI_PIU,0)-NVL(a.VARIAZIONI_MENO,0))) assestato,
SUM(NVL(A.IM_OBBLIG_IMP_ACR,0)) IMPEGN_ACCERT,
SUM(NVL(A.IM_MANDATI_REVERSALI,0)) ACCRED_RISCOSS
FROM VOCE_F_SALDI_CMP A
WHERE
a.ti_competenza_residuo='C'
AND a.ti_appartenenza='C'
AND a.ti_gestione='E'
AND a.cd_voce LIKE  SUBSTR(Prt_Getdati_Confcnr(A.ESERCIZIO, 'VOCEF_SPECIALE', 'AVANZO_E_CNR'),1,9)||'%'  -- '00.00.000%'
GROUP BY
a.ESERCIZIO,
a.CD_CDS,
SUBSTR(a.CD_VOCE,1,9)
)
--DISAVANZO CNR
UNION ALL
(SELECT ESER,CDS,TIPO,
VOCE_AVANZO_DISAVANZO,Prt_Getdes_Vocecap('E', eser, 'C', 'S', VOCE_AVANZO_DISAVANZO, 'C') AS DS_VOCE_DISAVANZO,
INIZIALE, VAR_PIU, VAR_MENO, ASSESTATO, IMPEGN_ACCERT, ACCRED_RISCOSS
FROM
-- parte II del bilancio CNR
(SELECT
a.ESERCIZIO eser,
a.CD_CDS cds,
'D_C' AS TIPO,
SUBSTR(a.CD_VOCE,1,13) VOCE_AVANZO_DISAVANZO,
SUM(NVL(a.IM_STANZ_INIZIALE_A1,0)) iniziale,
SUM(NVL(a.VARIAZIONI_PIU,0)) var_piu,
SUM(NVL(a.VARIAZIONI_MENO,0)) var_meno,
SUM((NVL(a.IM_STANZ_INIZIALE_A1,0)+NVL(a.VARIAZIONI_PIU,0)-NVL(a.VARIAZIONI_MENO,0))) assestato,
SUM(NVL(A.IM_OBBLIG_IMP_ACR,0)) IMPEGN_ACCERT,
SUM(NVL(A.IM_MANDATI_REVERSALI,0)) ACCRED_RISCOSS
FROM VOCE_F_SALDI_CMP A
WHERE
(a.ti_competenza_residuo='C'
AND a.ti_appartenenza='C'
AND a.ti_gestione='S'
AND SUBSTR(a.CD_VOCE,1,1)='2'
AND a.cd_voce=Prt_Getdati_Confcnr(A.ESERCIZIO, 'VOCEF_SPECIALE', 'AVANZO_S_CNR')) -- '2.000')
GROUP BY
a.ESERCIZIO,
a.CD_CDS,
SUBSTR(a.CD_VOCE,1,13)
)
)
--AVANZO CDS
UNION ALL
(SELECT ESER,CDS,TIPO,
VOCE_AVANZO_DISAVANZO,Prt_Getdes_Vocecap('F', eser, 'D', 'E', VOCE_AVANZO_DISAVANZO, 'C') AS DS_VOCE_DISAVANZO,
INIZIALE, VAR_PIU, VAR_MENO, ASSESTATO, IMPEGN_ACCERT, ACCRED_RISCOSS
FROM
(SELECT
a.ESERCIZIO eser,
a.CD_CDS cds,
'A_D' AS TIPO,
SUBSTR(a.CD_VOCE,1,6) VOCE_AVANZO_DISAVANZO,
(NVL(a.IM_STANZ_INIZIALE_A1,0)) iniziale,
(NVL(a.VARIAZIONI_PIU,0)) var_piu,
(NVL(a.VARIAZIONI_MENO,0)) var_meno,
((NVL(a.IM_STANZ_INIZIALE_A1,0)+NVL(a.VARIAZIONI_PIU,0)-NVL(a.VARIAZIONI_MENO,0))) assestato,
(NVL(A.IM_OBBLIG_IMP_ACR,0)) IMPEGN_ACCERT,
(NVL(A.IM_MANDATI_REVERSALI,0)) ACCRED_RISCOSS
FROM VOCE_F_SALDI_CMP A
WHERE
a.ti_competenza_residuo='C'
AND a.ti_appartenenza='D'
AND a.ti_gestione='E'
AND a.cd_voce = Prt_Getdati_Confcnr(A.ESERCIZIO, 'VOCEF_SPECIALE', 'AVANZO_E_CDS') --'05.006'
)
UNION ALL
--DISAVANZO CDS
(SELECT ESER,CDS,TIPO,
VOCE_AVANZO_DISAVANZO,Prt_Getdes_Vocecap('F', eser, 'D', 'S', VOCE_AVANZO_DISAVANZO, 'C') AS DS_VOCE_DISAVANZO,
INIZIALE, VAR_PIU, VAR_MENO, ASSESTATO, IMPEGN_ACCERT, ACCRED_RISCOSS
FROM
(SELECT
a.ESERCIZIO eser,
a.CD_CDS cds,
'D_D' AS TIPO,
SUBSTR(a.CD_VOCE,1,6) VOCE_AVANZO_DISAVANZO,
(NVL(a.IM_STANZ_INIZIALE_A1,0)) iniziale,
(NVL(a.VARIAZIONI_PIU,0)) var_piu,
(NVL(a.VARIAZIONI_MENO,0)) var_meno,
((NVL(a.IM_STANZ_INIZIALE_A1,0)+NVL(a.VARIAZIONI_PIU,0)-NVL(a.VARIAZIONI_MENO,0))) assestato,
(NVL(A.IM_OBBLIG_IMP_ACR,0)) IMPEGN_ACCERT,
(NVL(A.IM_MANDATI_REVERSALI,0)) ACCRED_RISCOSS
FROM VOCE_F_SALDI_CMP A
WHERE
a.ti_competenza_residuo='C'
AND a.ti_appartenenza='D'
AND a.ti_gestione='S'
AND a.cd_voce = Prt_Getdati_Confcnr(A.ESERCIZIO, 'VOCEF_SPECIALE', 'AVANZO_S_CDS') --'2.006'
))
)
)
;

   COMMENT ON TABLE "PRT_AVANZO_DISAVANZO"  IS 'Vista di estrazione per avanzo e disavanzo';
