--------------------------------------------------------
--  DDL for View PRT_STAMPA_FATTURE_VOCE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_STAMPA_FATTURE_VOCE" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO_FATTURA", "PG_FATTURA_PASSIVA", "PROGRESSIVO_RIGA", "TI_ISTITUZ_COMMERC", "CD_BENE_SERVIZIO", "DS_RIGA_FATTURA", "TI_FATTURA", "IM_IMPONIBILE", "CD_VOCE_IVA", "IM_IVA", "STATO_COFI", "ESERCIZIO_OBBLIGAZIONE", "ESERCIZIO_ORI_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "PG_OBBLIGAZIONE_SCADENZARIO", "IM_SCADENZA", "CD_ELEMENTO_VOCE", "CD_TERZO") AS 
  select
--
-- Date: 18/07/2006
-- Version: 1.2
--
-- View sottostante l'elenco, per voce del piano, delle fatture passive.
--
--
-- History:
--
-- Date: 28/07/2004
-- Version: 1.0
--
-- Creazione
--
-- Date: 05/08/2004
-- Version: 1.1
--
-- Aggiunto il CDS nella vista e modificato il file rpt
--
-- Date: 18/07/2006
-- Version: 1.2
-- Gestione Impegni/Accertamenti Residui:
-- aggiornata la funzione per tener conto anche del campo Esercizio Originale Impegno/Accertamento
--
-- Body:
--
    FATTURA_PASSIVA_RIGA.CD_CDS,
      FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA,
    FATTURA_PASSIVA_RIGA.ESERCIZIO,
    FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA,
    FATTURA_PASSIVA_RIGA.PROGRESSIVO_RIGA,
    FATTURA_PASSIVA_RIGA.TI_ISTITUZ_COMMERC,
    FATTURA_PASSIVA_RIGA.CD_BENE_SERVIZIO,
    FATTURA_PASSIVA_RIGA.DS_RIGA_FATTURA,
    FATTURA_PASSIVA.TI_FATTURA,
    FATTURA_PASSIVA_RIGA.IM_IMPONIBILE,
    FATTURA_PASSIVA_RIGA.CD_VOCE_IVA,
    FATTURA_PASSIVA_RIGA.IM_IVA,
    FATTURA_PASSIVA_RIGA.STATO_COFI,
    FATTURA_PASSIVA_RIGA.ESERCIZIO_OBBLIGAZIONE,
    FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE,
    FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE,
    FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO,
    OBBLIGAZIONE_SCADENZARIO.IM_SCADENZA,
    OBBLIGAZIONE.CD_ELEMENTO_VOCE,
	FATTURA_PASSIVA.CD_TERZO
FROM
    FATTURA_PASSIVA FATTURA_PASSIVA,
    FATTURA_PASSIVA_RIGA FATTURA_PASSIVA_RIGA,
    OBBLIGAZIONE_SCADENZARIO OBBLIGAZIONE_SCADENZARIO,
    OBBLIGAZIONE OBBLIGAZIONE
WHERE
    FATTURA_PASSIVA.CD_CDS = FATTURA_PASSIVA_RIGA.CD_CDS AND
    FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
    FATTURA_PASSIVA.ESERCIZIO = FATTURA_PASSIVA_RIGA.ESERCIZIO AND
    FATTURA_PASSIVA.PG_FATTURA_PASSIVA = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA AND
    FATTURA_PASSIVA_RIGA.CD_CDS_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.CD_CDS AND
    FATTURA_PASSIVA_RIGA.ESERCIZIO_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO AND
    FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE AND
    FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE AND
    FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO AND
    OBBLIGAZIONE_SCADENZARIO.CD_CDS = OBBLIGAZIONE.CD_CDS AND
    OBBLIGAZIONE_SCADENZARIO.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO AND
    OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE = OBBLIGAZIONE.ESERCIZIO_ORIGINALE AND
    OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE = OBBLIGAZIONE.PG_OBBLIGAZIONE;

   COMMENT ON TABLE "PRT_STAMPA_FATTURE_VOCE"  IS 'Stampa fatture per voce del piano';
