--------------------------------------------------------
--  DDL for View PRT_REG_ACCERT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_REG_ACCERT" ("ESERCIZIO", "CDS", "CDS_OR", "UO_OR", "ESERCIZIO_ORIGINALE", "PROGRESSIVO", "DATA", "DESCRIZIONE", "IMPORTO", "VOCE_BILANCIO", "DEBITORE", "DS_CDS", "DS_UO", "DATA_CANC", "RIPORTATO", "TIPO") AS 
  SELECT
--
-- Date: 19/07/2006
-- Version: 1.3
--
-- Vista di stampa Registro Accertamenti
--
-- History:
--
-- Date: 13/01/2003
-- Version: 1.0
-- Creazione
--
-- Date : 20/03/2003
-- Version: 1.1
-- inserito il campo cds
--
-- Date: 09/12/2003
-- Version: 1.2
-- tolti outer join per ottimizzare la stampa (Cineca)
--
-- Date: 19/07/2006
-- Version: 1.3
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body
--
ACCERTAMENTO.ESERCIZIO,
ACCERTAMENTO.CD_CDS,
ACCERTAMENTO.CD_CDS_ORIGINE,
ACCERTAMENTO.CD_UO_ORIGINE,
ACCERTAMENTO.ESERCIZIO_ORIGINALE,
ACCERTAMENTO.PG_ACCERTAMENTO,
ACCERTAMENTO.DT_REGISTRAZIONE,
ACCERTAMENTO.DS_ACCERTAMENTO,
ACCERTAMENTO.IM_ACCERTAMENTO,
ACCERTAMENTO.CD_ELEMENTO_VOCE,
TERZO.DENOMINAZIONE_SEDE,
b.DS_UNITA_ORGANIZZATIVA AS ds_cds,
a.DS_UNITA_ORGANIZZATIVA AS ds_uo,
ACCERTAMENTO.DT_CANCELLAZIONE,
ACCERTAMENTO.RIPORTATO,
ACCERTAMENTO.CD_TIPO_DOCUMENTO_CONT
FROM ACCERTAMENTO, TERZO, UNITA_ORGANIZZATIVA a, UNITA_ORGANIZZATIVA b
WHERE ACCERTAMENTO.CD_TERZO=TERZO.CD_TERZO AND
	  (ACCERTAMENTO.CD_TIPO_DOCUMENTO_CONT='ACR' OR
	  ACCERTAMENTO.CD_TIPO_DOCUMENTO_CONT='ACR_RES') AND
	  ACCERTAMENTO.FL_PGIRO='N' AND
	  a.CD_UNITA_ORGANIZZATIVA=ACCERTAMENTO.CD_UO_ORIGINE AND
	  b.CD_UNITA_ORGANIZZATIVA=ACCERTAMENTO.CD_CDS_ORIGINE
ORDER BY ACCERTAMENTO.ESERCIZIO, ACCERTAMENTO.ESERCIZIO_ORIGINALE, ACCERTAMENTO.PG_ACCERTAMENTO;

   COMMENT ON TABLE "PRT_REG_ACCERT"  IS 'Vista di stampa Registro Accertamenti';
