--------------------------------------------------------
--  DDL for View PRT_REND_FIN_ENTRATE_CDS_ALL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_REND_FIN_ENTRATE_CDS_ALL" ("ESERCIZIO", "CDS", "TITOLO", "DS_TITOLO", "CAPITOLO", "DS_CAPITOLO", "INIZIALE", "VAR_PIU", "VAR_MENO", "ASSESTATO", "RISCOSSIONI", "IN_PIU", "IN_MENO", "INIZ_CASSA", "VAR_PIU_CASSA", "VAR_MENO_CASSA", "ASSEST_CASSA") AS 
  SELECT DISTINCT
--
-- Date:27/10/2003
-- Version: 1.0
--
-- Vista di stampa Rendiconto Finanziario CDS Entrate (compresi importi a zero)
--
-- History:
--
-- Date: 27/10/2003
-- Version: 1.0
-- Creazione
-- (effettuate alcune modifiche per ottimizzazione-Cineca)
--
-- Body
--
eser, cds, titolo, prt_getdes_vocecap('E', eser, 'D', 'E', titolo, 'T') AS ds_titolo,
capitolo, prt_getdes_vocecap('E', eser, 'D', 'E', capitolo, 'C') AS ds_capitolo,
iniziale, var_piu, var_meno, assestato, riscossioni, in_piu, in_meno, iniz_cassa, var_piu_cassa, var_meno_cassa,
assest_cassa
FROM
(Select  VOCE_F_SALDI_CMP.ESERCIZIO eser,
	VOCE_F_SALDI_CMP.CD_CDS cds,
	SUBSTR(VOCE_F_SALDI_CMP.CD_VOCE,1,2) titolo,
	SUBSTR(VOCE_F_SALDI_CMP.CD_VOCE,1,6) capitolo,
	SUM(NVL(VOCE_F_SALDI_CMP.IM_STANZ_INIZIALE_A1,0)) iniziale,
	SUM(NVL(VOCE_F_SALDI_CMP.VARIAZIONI_PIU,0)) var_piu,
	SUM(NVL(VOCE_F_SALDI_CMP.VARIAZIONI_MENO,0)) var_meno,
	SUM((NVL(VOCE_F_SALDI_CMP.IM_STANZ_INIZIALE_A1,0)+NVL(VOCE_F_SALDI_CMP.VARIAZIONI_PIU,0)-NVL(VOCE_F_SALDI_CMP.VARIAZIONI_MENO,0))) assestato,
	SUM(NVL(VOCE_F_SALDI_CMP.IM_MANDATI_REVERSALI,0)) riscossioni,
	SUM(NVL(VOCE_F_SALDI_CMP.IM_MANDATI_REVERSALI,0)  - (NVL(VOCE_F_SALDI_CMP.IM_STANZ_INIZIALE_A1,0)+NVL(VOCE_F_SALDI_CMP.VARIAZIONI_PIU,0)-NVL(VOCE_F_SALDI_CMP.VARIAZIONI_MENO,0))) in_piu,
	SUM((NVL(VOCE_F_SALDI_CMP.IM_STANZ_INIZIALE_A1,0)+NVL(VOCE_F_SALDI_CMP.VARIAZIONI_PIU,0)-NVL(VOCE_F_SALDI_CMP.VARIAZIONI_MENO,0))-NVL(VOCE_F_SALDI_CMP.IM_MANDATI_REVERSALI,0)) in_meno
 From  	VOCE_F_SALDI_CMP
 Where 	VOCE_F_SALDI_CMP.TI_APPARTENENZA = 'D' And
	VOCE_F_SALDI_CMP.TI_GESTIONE = 'E' And
	VOCE_F_SALDI_CMP.ESERCIZIO In (Select ESERCIZIO From PARAMETRI_CNR Where FL_REGOLAMENTO_2006 = 'N')
 Group By VOCE_F_SALDI_CMP.ESERCIZIO,
 	  VOCE_F_SALDI_CMP.CD_CDS,
	  SUBSTR(VOCE_F_SALDI_CMP.CD_VOCE,1,2),
	  SUBSTR(VOCE_F_SALDI_CMP.CD_VOCE,1,6)),
/* QUERY PER FONDO INIZIALE DI CASSA */
(Select VOCE_F_SALDI_CMP.ESERCIZIO ESER_CASSA,
	VOCE_F_SALDI_CMP.CD_CDS CDS_CASSA,
	VOCE_F_SALDI_CMP.IM_STANZ_INIZIALE_A1 iniz_cassa,
	VOCE_F_SALDI_CMP.VARIAZIONI_PIU var_piu_cassa,
	VOCE_F_SALDI_CMP.VARIAZIONI_MENO var_meno_cassa,
	(VOCE_F_SALDI_CMP.IM_STANZ_INIZIALE_A1+VOCE_F_SALDI_CMP.VARIAZIONI_PIU-VOCE_F_SALDI_CMP.VARIAZIONI_MENO) assest_cassa
 From 	VOCE_F_SALDI_CMP
 where	VOCE_F_SALDI_CMP.TI_APPARTENENZA = 'D' And
	VOCE_F_SALDI_CMP.TI_GESTIONE = 'E' And
	VOCE_F_SALDI_CMP.CD_VOCE = '00.001' And
        VOCE_F_SALDI_CMP.ESERCIZIO In (Select ESERCIZIO From PARAMETRI_CNR Where FL_REGOLAMENTO_2006 = 'N'))
Where 	ESER_CASSA = ESER And
	CDS_CASSA = CDS
Union All
SELECT DISTINCT
eser, cds, titolo, prt_getdes_vocecap('E', eser, 'D', 'E', titolo, 'T') AS ds_titolo,
capitolo, prt_getdes_vocecap('E', eser, 'D', 'E', capitolo, 'C') AS ds_capitolo,
iniziale, var_piu, var_meno, assestato, riscossioni, in_piu, in_meno, iniz_cassa, var_piu_cassa, var_meno_cassa,
assest_cassa
FROM
(Select VOCE_F_SALDI_CDR_LINEA.ESERCIZIO eser,
	CNRUTL001.getCdsFromCdr(VOCE_F_SALDI_CDR_LINEA.CD_CENTRO_RESPONSABILITA) CDS,
	SUBSTR(VOCE_F_SALDI_CDR_LINEA.CD_VOCE,1,2) titolo,
	SUBSTR(VOCE_F_SALDI_CDR_LINEA.CD_VOCE,1,6) capitolo,
	SUM(NVL(VOCE_F_SALDI_CDR_LINEA.IM_STANZ_INIZIALE_A1,0)) iniziale,
	SUM(NVL(VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_PIU,0)) var_piu,
	SUM(NVL(VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_MENO,0)) var_meno,
	SUM((NVL(VOCE_F_SALDI_CDR_LINEA.IM_STANZ_INIZIALE_A1,0)+NVL(VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_PIU,0)-NVL(VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_MENO,0))) assestato,
	SUM(NVL(VOCE_F_SALDI_CDR_LINEA.IM_MANDATI_REVERSALI_PRO,0)) riscossioni,
	SUM(NVL(VOCE_F_SALDI_CDR_LINEA.IM_MANDATI_REVERSALI_PRO,0)-(NVL(VOCE_F_SALDI_CDR_LINEA.IM_STANZ_INIZIALE_A1,0)+NVL(VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_PIU,0)-NVL(VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_MENO,0))) in_piu,
	SUM((NVL(VOCE_F_SALDI_CDR_LINEA.IM_STANZ_INIZIALE_A1,0)+NVL(VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_PIU,0)-NVL(VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_MENO,0))-NVL(VOCE_F_SALDI_CDR_LINEA.IM_MANDATI_REVERSALI_PRO,0)) in_meno
 From  	VOCE_F_SALDI_CDR_LINEA
 Where 	VOCE_F_SALDI_CDR_LINEA.ESERCIZIO = VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES And
 	VOCE_F_SALDI_CDR_LINEA.TI_APPARTENENZA = 'C' And
	VOCE_F_SALDI_CDR_LINEA.TI_GESTIONE = 'E' And
	VOCE_F_SALDI_CDR_LINEA.ESERCIZIO In (Select ESERCIZIO From PARAMETRI_CNR Where FL_REGOLAMENTO_2006 = 'Y')
 Group By VOCE_F_SALDI_CDR_LINEA.ESERCIZIO,
 	  CNRUTL001.getCdsFromCdr(VOCE_F_SALDI_CDR_LINEA.CD_CENTRO_RESPONSABILITA),
	  SUBSTR(VOCE_F_SALDI_CDR_LINEA.CD_VOCE,1,2),
	  SUBSTR(VOCE_F_SALDI_CDR_LINEA.CD_VOCE,1,6)),
-- QUERY PER FONDO INIZIALE DI CASSA
(Select VOCE_F_SALDI_CDR_LINEA.ESERCIZIO ESER_CASSA,
	CNRUTL001.getCdsFromCdr(VOCE_F_SALDI_CDR_LINEA.CD_CENTRO_RESPONSABILITA) CDS_CASSA,
	VOCE_F_SALDI_CDR_LINEA.IM_STANZ_INIZIALE_A1 iniz_cassa,
	VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_PIU var_piu_cassa,
	VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_MENO var_meno_cassa,
	(VOCE_F_SALDI_CDR_LINEA.IM_STANZ_INIZIALE_A1+VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_PIU-VOCE_F_SALDI_CDR_LINEA.VARIAZIONI_MENO) assest_cassa
 From 	VOCE_F_SALDI_CDR_LINEA
 Where	VOCE_F_SALDI_CDR_LINEA.ESERCIZIO = VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES And
 	VOCE_F_SALDI_CDR_LINEA.TI_APPARTENENZA = 'D' And
	VOCE_F_SALDI_CDR_LINEA.TI_GESTIONE = 'E' And
	VOCE_F_SALDI_CDR_LINEA.CD_VOCE = '00.001' And
        VOCE_F_SALDI_CDR_LINEA.ESERCIZIO In (Select ESERCIZIO From PARAMETRI_CNR Where FL_REGOLAMENTO_2006 = 'Y'))
Where 	ESER_CASSA = ESER And
	CDS_CASSA = CDS
;
