--------------------------------------------------------
--  DDL for View PRT_SINTESI_LDA_PDG_SPE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_SINTESI_LDA_PDG_SPE" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "CD_LINEA_ATTIVITA", "CD_FUNZIONE", "CD_NATURA", "DS_LINEA_ATTIVITA", "CD_INSIEME_LA", "IM_RI_CCS_SPESE_ODC", "IM_RK_CCS_SPESE_OGC", "IM_RQ_SSC_COSTI_ODC", "IM_RS_SSC_COSTI_OGC", "IM_RU_SPESE_COSTI_ALTRUI", "IM_RAC_A2_SPESE_ODC", "IM_RAE_A2_SPESE_OGC", "IM_RAG_A2_SPESE_COSTI_ALTRUI", "IM_RAL_A3_SPESE_ODC", "IM_RAN_A3_SPESE_OGC", "IM_RAP_A3_SPESE_COSTI_ALTRUI", "IM_RH_CCS_COSTI", "IM_RM_CSS_AMMORTAMENTI", "IM_RN_CSS_RIMANENZE", "IM_RO_CSS_ALTRI_COSTI", "IM_RP_CSS_VERSO_ALTRO_CDR", "IM_RAA_A2_COSTI_FINALI", "IM_RAB_A2_COSTI_ALTRO_CDR", "IM_RAH_A3_COSTI_FINALI", "IM_RAI_A3_COSTI_ALTRO_CDR") AS 
  select
--
-- Date: 28/04/2003
-- Version 1.0
--
-- Vista di estrazione dati dai piani di gestione per le situazioni per lda  Costi/spese
--
-- History
--
-- Date :28/04/2003
-- Version: 1.0
-- Creazione
--
--
-- Body
--
-- Estrae i dettagli del PDG relativi a costi e spese anno1 anno2 anno3, aggregati
-- per cdr, lda, voce di bilancio
-- seleziona i dettagli con stato=Y confermato
-- mette in join la tabella lda per estrarre natura, funzione, descrizione e insieme
PDG_PREVENTIVO_SPE_DET.ESERCIZIO,
PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA,
PDG_PREVENTIVO_SPE_DET.TI_APPARTENENZA,
PDG_PREVENTIVO_SPE_DET.TI_GESTIONE,
PDG_PREVENTIVO_SPE_DET.CD_ELEMENTO_VOCE,
PDG_PREVENTIVO_SPE_DET.CD_LINEA_ATTIVITA,
LINEA_ATTIVITA.CD_FUNZIONE,
LINEA_ATTIVITA.CD_NATURA,
LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
LINEA_ATTIVITA.CD_INSIEME_LA,
-- spese anno 1
SUM(PDG_PREVENTIVO_SPE_DET.IM_RI_CCS_SPESE_ODC),
SUM(PDG_PREVENTIVO_SPE_DET.IM_RK_CCS_SPESE_OGC),
SUM(PDG_PREVENTIVO_SPE_DET.IM_RQ_SSC_COSTI_ODC),
SUM(PDG_PREVENTIVO_SPE_DET.IM_RS_SSC_COSTI_OGC),
SUM(PDG_PREVENTIVO_SPE_DET.IM_RU_SPESE_COSTI_ALTRUI),
-- spese anno 2
SUM(PDG_PREVENTIVO_SPE_DET.IM_RAC_A2_SPESE_ODC),
SUM(PDG_PREVENTIVO_SPE_DET.IM_RAE_A2_SPESE_OGC),
SUM(PDG_PREVENTIVO_SPE_DET.IM_RAG_A2_SPESE_COSTI_ALTRUI),
-- spese anno 3
SUM(PDG_PREVENTIVO_SPE_DET.IM_RAL_A3_SPESE_ODC),
SUM(PDG_PREVENTIVO_SPE_DET.IM_RAN_A3_SPESE_OGC),
SUM(PDG_PREVENTIVO_SPE_DET.IM_RAP_A3_SPESE_COSTI_ALTRUI),
-- costi anno 1
 sum(PDG_PREVENTIVO_SPE_DET.IM_RH_CCS_COSTI),
 sum(PDG_PREVENTIVO_SPE_DET.IM_RM_CSS_AMMORTAMENTI),
 sum(PDG_PREVENTIVO_SPE_DET.IM_RN_CSS_RIMANENZE),
 sum(PDG_PREVENTIVO_SPE_DET.IM_RO_CSS_ALTRI_COSTI),
 sum(PDG_PREVENTIVO_SPE_DET.IM_RP_CSS_VERSO_ALTRO_CDR),
-- costi anno 2
 sum(PDG_PREVENTIVO_SPE_DET.IM_RAA_A2_COSTI_FINALI),
 sum(PDG_PREVENTIVO_SPE_DET.IM_RAB_A2_COSTI_ALTRO_CDR),
-- costi anno 3
 sum(PDG_PREVENTIVO_SPE_DET.IM_RAH_A3_COSTI_FINALI),
 sum(PDG_PREVENTIVO_SPE_DET.IM_RAI_A3_COSTI_ALTRO_CDR)
FROM
PDG_PREVENTIVO_SPE_DET ,
LINEA_ATTIVITA
WHERE
PDG_PREVENTIVO_SPE_DET.STATO = 'Y' AND
LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA = PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA AND
LINEA_ATTIVITA.CD_LINEA_ATTIVITA = PDG_PREVENTIVO_SPE_DET.CD_LINEA_ATTIVITA AND
PDG_PREVENTIVO_SPE_DET.TI_GESTIONE = 'S' AND
PDG_PREVENTIVO_SPE_DET.TI_APPARTENENZA='D'
GROUP BY PDG_PREVENTIVO_SPE_DET.ESERCIZIO,
PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA,
PDG_PREVENTIVO_SPE_DET.CD_LINEA_ATTIVITA,
PDG_PREVENTIVO_SPE_DET.TI_APPARTENENZA,
PDG_PREVENTIVO_SPE_DET.TI_GESTIONE,
PDG_PREVENTIVO_SPE_DET.CD_ELEMENTO_VOCE,
PDG_PREVENTIVO_SPE_DET.STATO,
PDG_PREVENTIVO_SPE_DET.CATEGORIA_DETTAGLIO,
LINEA_ATTIVITA.CD_FUNZIONE,
LINEA_ATTIVITA.CD_NATURA,
LINEA_ATTIVITA.DS_LINEA_ATTIVITA,
LINEA_ATTIVITA.CD_INSIEME_LA
;

   COMMENT ON TABLE "PRT_SINTESI_LDA_PDG_SPE"  IS 'Vista di estrazione dati dai piani di gestione per le situazioni per lda  Costi/spese';
