--------------------------------------------------------
--  DDL for View PRT_ELENCO_FATT_PER_FORNITORE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_ELENCO_FATT_PER_FORNITORE" ("CD_TERZO", "RAGIONE_SOCIALE", "NOME", "COGNOME", "CODICE_FISCALE", "PARTITA_IVA", "CD_CDS_FATT", "DES_CDS", "CD_UNITA_ORGANIZZATIVA_FATT", "DES_UO", "ESERCIZIO_FATT", "PG_FATTURA_PASSIVA_FATT", "TI_FATTURA_FATT", "IST_COMM_FATT", "PROTOCOLLO_IVA_FATT", "DT_REGISTRAZIONE_FATT", "NR_FATTURA", "DT_EMISSIONE_FATT", "CD_MODALITA_PAG_UO_CDS", "IM_TOTALE_IMPONIBILE_FATT", "IM_TOTALE_IVA_FATT", "IM_TOTALE_FATTURA_FATT", "ESERCIZIO_LETTERA", "PG_LETTERA", "CD_DIVISA_FATT", "PROGRESSIVO_RIGA", "DS_RIGA_FATTURA", "IM_IMPONIBILE_RIGA", "CD_VOCE_IVA_RIGA", "IM_IVA_RIGA", "DT_DA_COMPETENZA_COGE_RIGA", "DT_A_COMPETENZA_COGE_RIGA", "ENT_SPE", "CD_CDS_ACC_OBB", "ESERCIZIO_ACC_OBB", "ESERCIZIO_ORI_ACC_OBB", "PG_ACC_OBB", "PG_ACC_OBB_SCAD", "CD_CDS_REV_MAN", "ESERCIZIO_REV_MAN", "PG_REV_MAN", "PROV_DEF_REV_MAN", "TIPO_REV_MAN", "COMP_RES_REV_MAN", "DS_REV_MAN", "DT_EM_REV_MAN", "DT_TRASMISSIONE_REV_MAN", "DT_INCASSO_REV_MAN", "PG_DIS", "DT_EM_DIS", "DT_INVIO_DIS") AS 
  SELECT
--
-- Date: 18/07/2006
-- Version: 1.3
--
-- Vista di stampa elenco fatture passive per fornitore
--
-- History:
--
-- Date: 28/07/2004
-- Version: 1.0
-- Creazione
--
-- Date: 06/08/2004
-- Version: 1.1
-- Rinominata view, cambiato in string il tipo delle date
--
-- Date: 17/01/2005
-- Version: 1.2
-- Aggiunte le fatture passive e le note non ancora pagate
-- o anche se pagate, non inserite in distinta)
--
-- Date: 18/07/2006
-- Version: 1.3
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body:
--FATTURE E NOTE GIA' PAGATE E IN DISTINTA
FATTURA_PASSIVA.CD_TERZO,
          FATTURA_PASSIVA.RAGIONE_SOCIALE,
          FATTURA_PASSIVA.NOME,
          FATTURA_PASSIVA.COGNOME,
          FATTURA_PASSIVA.CODICE_FISCALE,
          FATTURA_PASSIVA.PARTITA_IVA,
          FATTURA_PASSIVA.CD_CDS,
          UO_CDS.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA,
          UO_UO.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.ESERCIZIO,
          FATTURA_PASSIVA.PG_FATTURA_PASSIVA,
          FATTURA_PASSIVA.TI_FATTURA,
          FATTURA_PASSIVA.TI_ISTITUZ_COMMERC,
          FATTURA_PASSIVA.PROTOCOLLO_IVA,
          FATTURA_PASSIVA.DT_REGISTRAZIONE,
          FATTURA_PASSIVA.NR_FATTURA_FORNITORE,
          FATTURA_PASSIVA.DT_FATTURA_FORNITORE,
          FATTURA_PASSIVA.CD_MODALITA_PAG_UO_CDS,
          FATTURA_PASSIVA.IM_TOTALE_IMPONIBILE,
          FATTURA_PASSIVA.IM_TOTALE_IVA,
          FATTURA_PASSIVA.IM_TOTALE_FATTURA,
          FATTURA_PASSIVA.ESERCIZIO_LETTERA,
          FATTURA_PASSIVA.PG_LETTERA,
          FATTURA_PASSIVA.CD_DIVISA,
          FATTURA_PASSIVA_RIGA.PROGRESSIVO_RIGA,
          FATTURA_PASSIVA_RIGA.DS_RIGA_FATTURA,
          FATTURA_PASSIVA_RIGA.IM_IMPONIBILE,
          FATTURA_PASSIVA_RIGA.CD_VOCE_IVA,
          FATTURA_PASSIVA_RIGA.IM_IVA,
          FATTURA_PASSIVA_RIGA.DT_DA_COMPETENZA_COGE,
          FATTURA_PASSIVA_RIGA.DT_A_COMPETENZA_COGE,
          'S',
          FATTURA_PASSIVA_RIGA.CD_CDS_OBBLIGAZIONE,
          FATTURA_PASSIVA_RIGA.ESERCIZIO_OBBLIGAZIONE,
          FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE,
          FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE,
          FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO,
          MANDATO.CD_CDS,
          MANDATO.ESERCIZIO,
          MANDATO.PG_MANDATO,
          MANDATO.CD_TIPO_DOCUMENTO_CONT,
          MANDATO.TI_MANDATO,
          MANDATO.TI_COMPETENZA_RESIDUO,
          MANDATO.DS_MANDATO,
          MANDATO.DT_EMISSIONE,
          MANDATO.DT_TRASMISSIONE,
          MANDATO.DT_PAGAMENTO,
          DISTINTA_CASSIERE.PG_DISTINTA,
          DISTINTA_CASSIERE.DT_EMISSIONE,
          DISTINTA_CASSIERE.DT_INVIO
FROM  FATTURA_PASSIVA, FATTURA_PASSIVA_RIGA,
      MANDATO, MANDATO_RIGA,
      DISTINTA_CASSIERE_DET, DISTINTA_CASSIERE,
      UNITA_ORGANIZZATIVA UO_CDS,
      UNITA_ORGANIZZATIVA UO_UO
WHERE UO_CDS.CD_UNITA_ORGANIZZATIVA            = FATTURA_PASSIVA.CD_CDS                      AND
      UO_UO.CD_UNITA_ORGANIZZATIVA             = FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA      AND
      FATTURA_PASSIVA.CD_CDS                   = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA   = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      FATTURA_PASSIVA.ESERCIZIO                = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      FATTURA_PASSIVA.PG_FATTURA_PASSIVA       = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     AND
      MANDATO_RIGA.CD_CDS                      = MANDATO.CD_CDS                              AND
      MANDATO_RIGA.ESERCIZIO                   = MANDATO.ESERCIZIO                           AND
      MANDATO_RIGA.PG_MANDATO                  = MANDATO.PG_MANDATO                          AND
      MANDATO_RIGA.CD_CDS                      = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      --MANDATO_RIGA.ESERCIZIO_OBBLIGAZIONE      = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      MANDATO_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE  = FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE AND
      MANDATO_RIGA.PG_OBBLIGAZIONE             = FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE        AND
      MANDATO_RIGA.PG_OBBLIGAZIONE_SCADENZARIO = FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO AND
      MANDATO_RIGA.CD_CDS_DOC_AMM              = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      MANDATO_RIGA.CD_UO_DOC_AMM               = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      MANDATO_RIGA.ESERCIZIO_DOC_AMM           = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM       = 'FATTURA_P'                                 AND
      MANDATO_RIGA.PG_DOC_AMM                  = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     AND
      MANDATO_RIGA.STATO                       != 'A'   AND
      MANDATO.CD_CDS                           = DISTINTA_CASSIERE_DET.CD_CDS_origine     AND
      MANDATO.ESERCIZIO                        = DISTINTA_CASSIERE_DET.ESERCIZIO  AND
      MANDATO.PG_MANDATO                       = DISTINTA_CASSIERE_DET.PG_MANDATO AND
      DISTINTA_CASSIERE_DET.CD_CDS                 = DISTINTA_CASSIERE.CD_CDS                 AND
      DISTINTA_CASSIERE_DET.ESERCIZIO              = DISTINTA_CASSIERE.ESERCIZIO              AND
      DISTINTA_CASSIERE_DET.CD_UNITA_ORGANIZZATIVA = DISTINTA_CASSIERE.CD_UNITA_ORGANIZZATIVA AND
      DISTINTA_CASSIERE_DET.PG_DISTINTA            = DISTINTA_CASSIERE.PG_DISTINTA
Union
Select
--FATTURE E NOTE GIA' PAGATE MA NON INSERITE IN DISTINTA
FATTURA_PASSIVA.CD_TERZO,
          FATTURA_PASSIVA.RAGIONE_SOCIALE,
          FATTURA_PASSIVA.NOME,
          FATTURA_PASSIVA.COGNOME,
          FATTURA_PASSIVA.CODICE_FISCALE,
          FATTURA_PASSIVA.PARTITA_IVA,
          FATTURA_PASSIVA.CD_CDS,
          UO_CDS.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA,
          UO_UO.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.ESERCIZIO,
          FATTURA_PASSIVA.PG_FATTURA_PASSIVA,
          FATTURA_PASSIVA.TI_FATTURA,
          FATTURA_PASSIVA.TI_ISTITUZ_COMMERC,
          FATTURA_PASSIVA.PROTOCOLLO_IVA,
          FATTURA_PASSIVA.DT_REGISTRAZIONE,
          FATTURA_PASSIVA.NR_FATTURA_FORNITORE,
          FATTURA_PASSIVA.DT_FATTURA_FORNITORE,
          FATTURA_PASSIVA.CD_MODALITA_PAG_UO_CDS,
          FATTURA_PASSIVA.IM_TOTALE_IMPONIBILE,
          FATTURA_PASSIVA.IM_TOTALE_IVA,
          FATTURA_PASSIVA.IM_TOTALE_FATTURA,
          FATTURA_PASSIVA.ESERCIZIO_LETTERA,
          FATTURA_PASSIVA.PG_LETTERA,
          FATTURA_PASSIVA.CD_DIVISA,
          FATTURA_PASSIVA_RIGA.PROGRESSIVO_RIGA,
          FATTURA_PASSIVA_RIGA.DS_RIGA_FATTURA,
          FATTURA_PASSIVA_RIGA.IM_IMPONIBILE,
          FATTURA_PASSIVA_RIGA.CD_VOCE_IVA,
          FATTURA_PASSIVA_RIGA.IM_IVA,
          FATTURA_PASSIVA_RIGA.DT_DA_COMPETENZA_COGE,
          FATTURA_PASSIVA_RIGA.DT_A_COMPETENZA_COGE,
          'S',
          FATTURA_PASSIVA_RIGA.CD_CDS_OBBLIGAZIONE,
          FATTURA_PASSIVA_RIGA.ESERCIZIO_OBBLIGAZIONE,
          FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE,
          FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE,
          FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO,
          MANDATO.CD_CDS,
          MANDATO.ESERCIZIO,
          MANDATO.PG_MANDATO,
          MANDATO.CD_TIPO_DOCUMENTO_CONT,
          MANDATO.TI_MANDATO,
          MANDATO.TI_COMPETENZA_RESIDUO,
          MANDATO.DS_MANDATO,
          MANDATO.DT_EMISSIONE,
          MANDATO.DT_TRASMISSIONE,
          MANDATO.DT_PAGAMENTO,
          Null, --DISTINTA_CASSIERE.PG_DISTINTA,
          Null, --DISTINTA_CASSIERE.DT_EMISSIONE,
          Null  --DISTINTA_CASSIERE.DT_INVIO
FROM  FATTURA_PASSIVA, FATTURA_PASSIVA_RIGA,
      MANDATO, MANDATO_RIGA,
      UNITA_ORGANIZZATIVA UO_CDS,
      UNITA_ORGANIZZATIVA UO_UO
WHERE UO_CDS.CD_UNITA_ORGANIZZATIVA            = FATTURA_PASSIVA.CD_CDS                      AND
      UO_UO.CD_UNITA_ORGANIZZATIVA             = FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA      AND
      FATTURA_PASSIVA.CD_CDS                   = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA   = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      FATTURA_PASSIVA.ESERCIZIO                = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      FATTURA_PASSIVA.PG_FATTURA_PASSIVA       = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     AND
      MANDATO_RIGA.CD_CDS                      = MANDATO.CD_CDS                              AND
      MANDATO_RIGA.ESERCIZIO                   = MANDATO.ESERCIZIO                           AND
      MANDATO_RIGA.PG_MANDATO                  = MANDATO.PG_MANDATO                          AND
      MANDATO_RIGA.CD_CDS                      = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      --MANDATO_RIGA.ESERCIZIO_OBBLIGAZIONE      = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      MANDATO_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE  = FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE AND
      MANDATO_RIGA.PG_OBBLIGAZIONE             = FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE        AND
      MANDATO_RIGA.PG_OBBLIGAZIONE_SCADENZARIO = FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO AND
      MANDATO_RIGA.CD_CDS_DOC_AMM              = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      MANDATO_RIGA.CD_UO_DOC_AMM               = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      MANDATO_RIGA.ESERCIZIO_DOC_AMM           = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM       = 'FATTURA_P'                                 AND
      MANDATO_RIGA.PG_DOC_AMM                  = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     AND
      MANDATO_RIGA.STATO                       != 'A'   And
      Not Exists
      (Select '1' From Distinta_cassiere_det
       Where DISTINTA_CASSIERE_DET.CD_CDS_origine = MANDATO.CD_CDS And
             DISTINTA_CASSIERE_DET.ESERCIZIO = MANDATO.ESERCIZIO And
	     DISTINTA_CASSIERE_DET.PG_MANDATO = MANDATO.PG_MANDATO)
Union
--FATTURE E NOTE NON PAGATE E NON RISCOSSE (se ci sono solo note viene emessa una reversale)
Select
FATTURA_PASSIVA.CD_TERZO,
          FATTURA_PASSIVA.RAGIONE_SOCIALE,
          FATTURA_PASSIVA.NOME,
          FATTURA_PASSIVA.COGNOME,
          FATTURA_PASSIVA.CODICE_FISCALE,
          FATTURA_PASSIVA.PARTITA_IVA,
          FATTURA_PASSIVA.CD_CDS,
          UO_CDS.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA,
          UO_UO.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.ESERCIZIO,
          FATTURA_PASSIVA.PG_FATTURA_PASSIVA,
          FATTURA_PASSIVA.TI_FATTURA,
          FATTURA_PASSIVA.TI_ISTITUZ_COMMERC,
          FATTURA_PASSIVA.PROTOCOLLO_IVA,
          FATTURA_PASSIVA.DT_REGISTRAZIONE,
          FATTURA_PASSIVA.NR_FATTURA_FORNITORE,
          FATTURA_PASSIVA.DT_FATTURA_FORNITORE,
          FATTURA_PASSIVA.CD_MODALITA_PAG_UO_CDS,
          FATTURA_PASSIVA.IM_TOTALE_IMPONIBILE,
          FATTURA_PASSIVA.IM_TOTALE_IVA,
          FATTURA_PASSIVA.IM_TOTALE_FATTURA,
          FATTURA_PASSIVA.ESERCIZIO_LETTERA,
          FATTURA_PASSIVA.PG_LETTERA,
          FATTURA_PASSIVA.CD_DIVISA,
          FATTURA_PASSIVA_RIGA.PROGRESSIVO_RIGA,
          FATTURA_PASSIVA_RIGA.DS_RIGA_FATTURA,
          FATTURA_PASSIVA_RIGA.IM_IMPONIBILE,
          FATTURA_PASSIVA_RIGA.CD_VOCE_IVA,
          FATTURA_PASSIVA_RIGA.IM_IVA,
          FATTURA_PASSIVA_RIGA.DT_DA_COMPETENZA_COGE,
          FATTURA_PASSIVA_RIGA.DT_A_COMPETENZA_COGE,
          'S',
          Decode(FATTURA_PASSIVA_RIGA.CD_CDS_OBBLIGAZIONE,Null,
              FATTURA_PASSIVA_RIGA.CD_CDS_ACCERTAMENTO,FATTURA_PASSIVA_RIGA.CD_CDS_OBBLIGAZIONE),
          Decode(FATTURA_PASSIVA_RIGA.ESERCIZIO_OBBLIGAZIONE,Null,
              FATTURA_PASSIVA_RIGA.ESERCIZIO_ACCERTAMENTO,FATTURA_PASSIVA_RIGA.ESERCIZIO_OBBLIGAZIONE),
          Decode(FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE,Null,
              FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_ACCERTAMENTO,FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE),
          Decode(FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE,Null,
              FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO,FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE),
          Decode(FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO,Null,
              FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO_SCADENZARIO,FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO),
	  Null,	--MANDATO.CD_CDS,
          Null,	--MANDATO.ESERCIZIO,
          Null,	--MANDATO.PG_MANDATO,
          Null,	--MANDATO.CD_TIPO_DOCUMENTO_CONT,
          Null,	--MANDATO.TI_MANDATO,
          Null,	--MANDATO.TI_COMPETENZA_RESIDUO,
          Null,	--MANDATO.DS_MANDATO,
          Null,	--MANDATO.DT_EMISSIONE,
          Null,	--MANDATO.DT_TRASMISSIONE,
          Null,	--MANDATO.DT_PAGAMENTO,
          Null,	--DISTINTA_CASSIERE.PG_DISTINTA,
          Null,	--DISTINTA_CASSIERE.DT_EMISSIONE,
          Null  --DISTINTA_CASSIERE.DT_INVIO
FROM  FATTURA_PASSIVA, FATTURA_PASSIVA_RIGA,
      UNITA_ORGANIZZATIVA UO_CDS,
      UNITA_ORGANIZZATIVA UO_UO
WHERE UO_CDS.CD_UNITA_ORGANIZZATIVA            = FATTURA_PASSIVA.CD_CDS                      AND
      UO_UO.CD_UNITA_ORGANIZZATIVA             = FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA      AND
      FATTURA_PASSIVA.CD_CDS                   = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA   = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      FATTURA_PASSIVA.ESERCIZIO                = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      FATTURA_PASSIVA.PG_FATTURA_PASSIVA       = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     And
      Not Exists
       	(Select '1' From Mandato_Riga
	 Where MANDATO_RIGA.CD_CDS = FATTURA_PASSIVA_RIGA.CD_CDS And
               --MANDATO_RIGA.ESERCIZIO_OBBLIGAZIONE = FATTURA_PASSIVA_RIGA.ESERCIZIO And
               MANDATO_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE = FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_OBBLIGAZIONE And
               MANDATO_RIGA.PG_OBBLIGAZIONE = FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE And
      	       MANDATO_RIGA.PG_OBBLIGAZIONE_SCADENZARIO = FATTURA_PASSIVA_RIGA.PG_OBBLIGAZIONE_SCADENZARIO And
      	       MANDATO_RIGA.CD_CDS_DOC_AMM = FATTURA_PASSIVA_RIGA.CD_CDS And
               MANDATO_RIGA.CD_UO_DOC_AMM = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA And
               MANDATO_RIGA.ESERCIZIO_DOC_AMM = FATTURA_PASSIVA_RIGA.ESERCIZIO And
               MANDATO_RIGA.CD_TIPO_DOCUMENTO_AMM = 'FATTURA_P' And
               MANDATO_RIGA.PG_DOC_AMM = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA And
               MANDATO_RIGA.STATO != 'A') And
      Not Exists
       	(Select '1' From Reversale_Riga
	 Where REVERSALE_RIGA.CD_CDS = FATTURA_PASSIVA_RIGA.CD_CDS And
               --REVERSALE_RIGA.ESERCIZIO_ACCERTAMENTO = FATTURA_PASSIVA_RIGA.ESERCIZIO And
               REVERSALE_RIGA.ESERCIZIO_ORI_ACCERTAMENTO = FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_ACCERTAMENTO And
               REVERSALE_RIGA.PG_ACCERTAMENTO = FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO And
               REVERSALE_RIGA.PG_ACCERTAMENTO_SCADENZARIO = FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO_SCADENZARIO And
               REVERSALE_RIGA.CD_CDS_DOC_AMM = FATTURA_PASSIVA_RIGA.CD_CDS And
               REVERSALE_RIGA.CD_UO_DOC_AMM = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA And
               REVERSALE_RIGA.ESERCIZIO_DOC_AMM = FATTURA_PASSIVA_RIGA.ESERCIZIO And
               REVERSALE_RIGA.CD_TIPO_DOCUMENTO_AMM = 'FATTURA_P' And
               REVERSALE_RIGA.PG_DOC_AMM = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA And
               REVERSALE_RIGA.STATO != 'A')
Union
--NOTE PER LE QUALI VIENE EMESSA UNA REVERSALE E C'E' ANCHE LA DISTINTA
Select    FATTURA_PASSIVA.CD_TERZO,
          FATTURA_PASSIVA.RAGIONE_SOCIALE,
          FATTURA_PASSIVA.NOME,
          FATTURA_PASSIVA.COGNOME,
          FATTURA_PASSIVA.CODICE_FISCALE,
          FATTURA_PASSIVA.PARTITA_IVA,
          FATTURA_PASSIVA.CD_CDS,
          UO_CDS.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA,
          UO_UO.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.ESERCIZIO,
          FATTURA_PASSIVA.PG_FATTURA_PASSIVA,
          FATTURA_PASSIVA.TI_FATTURA,
          FATTURA_PASSIVA.TI_ISTITUZ_COMMERC,
          FATTURA_PASSIVA.PROTOCOLLO_IVA,
          FATTURA_PASSIVA.DT_REGISTRAZIONE,
          FATTURA_PASSIVA.NR_FATTURA_FORNITORE,
          FATTURA_PASSIVA.DT_FATTURA_FORNITORE,
          FATTURA_PASSIVA.CD_MODALITA_PAG_UO_CDS,
          FATTURA_PASSIVA.IM_TOTALE_IMPONIBILE,
          FATTURA_PASSIVA.IM_TOTALE_IVA,
          FATTURA_PASSIVA.IM_TOTALE_FATTURA,
          FATTURA_PASSIVA.ESERCIZIO_LETTERA,
          FATTURA_PASSIVA.PG_LETTERA,
          FATTURA_PASSIVA.CD_DIVISA,
          FATTURA_PASSIVA_RIGA.PROGRESSIVO_RIGA,
          FATTURA_PASSIVA_RIGA.DS_RIGA_FATTURA,
          FATTURA_PASSIVA_RIGA.IM_IMPONIBILE,
          FATTURA_PASSIVA_RIGA.CD_VOCE_IVA,
          FATTURA_PASSIVA_RIGA.IM_IVA,
          FATTURA_PASSIVA_RIGA.DT_DA_COMPETENZA_COGE,
          FATTURA_PASSIVA_RIGA.DT_A_COMPETENZA_COGE,
          'E',
          FATTURA_PASSIVA_RIGA.CD_CDS_ACCERTAMENTO,
          FATTURA_PASSIVA_RIGA.ESERCIZIO_ACCERTAMENTO,
          FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_ACCERTAMENTO,
          FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO,
          FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO_SCADENZARIO,
          REVERSALE.CD_CDS,
          REVERSALE.ESERCIZIO,
          REVERSALE.PG_REVERSALE,
          REVERSALE.CD_TIPO_DOCUMENTO_CONT,
          REVERSALE.TI_REVERSALE,
          REVERSALE.TI_COMPETENZA_RESIDUO,
          REVERSALE.DS_REVERSALE,
          REVERSALE.DT_EMISSIONE,
          REVERSALE.DT_TRASMISSIONE,
          REVERSALE.DT_INCASSO,
          DISTINTA_CASSIERE.PG_DISTINTA,
          DISTINTA_CASSIERE.DT_EMISSIONE,
          DISTINTA_CASSIERE.DT_INVIO
FROM  FATTURA_PASSIVA, FATTURA_PASSIVA_RIGA,
      REVERSALE, REVERSALE_RIGA,
      DISTINTA_CASSIERE_DET, DISTINTA_CASSIERE,
      UNITA_ORGANIZZATIVA UO_CDS,
      UNITA_ORGANIZZATIVA UO_UO
WHERE UO_CDS.CD_UNITA_ORGANIZZATIVA            = FATTURA_PASSIVA.CD_CDS                      AND
      UO_UO.CD_UNITA_ORGANIZZATIVA             = FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA      AND
      FATTURA_PASSIVA.CD_CDS                     = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA     = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      FATTURA_PASSIVA.ESERCIZIO                  = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      FATTURA_PASSIVA.PG_FATTURA_PASSIVA         = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     AND
      REVERSALE_RIGA.CD_CDS                      = REVERSALE.CD_CDS                            AND
      REVERSALE_RIGA.ESERCIZIO                   = REVERSALE.ESERCIZIO                         AND
      REVERSALE_RIGA.PG_REVERSALE                  = REVERSALE.PG_REVERSALE                      AND
      REVERSALE_RIGA.CD_CDS                      = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      --REVERSALE_RIGA.ESERCIZIO_ACCERTAMENTO      = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      REVERSALE_RIGA.ESERCIZIO_ORI_ACCERTAMENTO  = FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_ACCERTAMENTO AND
      REVERSALE_RIGA.PG_ACCERTAMENTO             = FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO        AND
      REVERSALE_RIGA.PG_ACCERTAMENTO_SCADENZARIO = FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO_SCADENZARIO AND
      REVERSALE_RIGA.CD_CDS_DOC_AMM              = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      REVERSALE_RIGA.CD_UO_DOC_AMM               = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      REVERSALE_RIGA.ESERCIZIO_DOC_AMM           = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      REVERSALE_RIGA.CD_TIPO_DOCUMENTO_AMM       = 'FATTURA_P'                                 AND
      REVERSALE_RIGA.PG_DOC_AMM                  = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     AND
      REVERSALE_RIGA.STATO                       != 'A'  AND
      REVERSALE.CD_CDS                           = DISTINTA_CASSIERE_DET.CD_CDS_origine     AND
      REVERSALE.ESERCIZIO                        = DISTINTA_CASSIERE_DET.ESERCIZIO  AND
      REVERSALE.PG_REVERSALE                     = DISTINTA_CASSIERE_DET.PG_REVERSALE AND
      DISTINTA_CASSIERE_DET.CD_CDS                 = DISTINTA_CASSIERE.CD_CDS                 AND
      DISTINTA_CASSIERE_DET.ESERCIZIO              = DISTINTA_CASSIERE.ESERCIZIO              AND
      DISTINTA_CASSIERE_DET.CD_UNITA_ORGANIZZATIVA = DISTINTA_CASSIERE.CD_UNITA_ORGANIZZATIVA AND
      DISTINTA_CASSIERE_DET.PG_DISTINTA            = DISTINTA_CASSIERE.PG_DISTINTA
Union
--NOTE PER LE QUALI VIENE EMESSA UNA REVERSALE MA NON C'E' LA DISTINTA
Select    FATTURA_PASSIVA.CD_TERZO,
          FATTURA_PASSIVA.RAGIONE_SOCIALE,
          FATTURA_PASSIVA.NOME,
          FATTURA_PASSIVA.COGNOME,
          FATTURA_PASSIVA.CODICE_FISCALE,
          FATTURA_PASSIVA.PARTITA_IVA,
          FATTURA_PASSIVA.CD_CDS,
          UO_CDS.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA,
          UO_UO.DS_UNITA_ORGANIZZATIVA,
          FATTURA_PASSIVA.ESERCIZIO,
          FATTURA_PASSIVA.PG_FATTURA_PASSIVA,
          FATTURA_PASSIVA.TI_FATTURA,
          FATTURA_PASSIVA.TI_ISTITUZ_COMMERC,
          FATTURA_PASSIVA.PROTOCOLLO_IVA,
          FATTURA_PASSIVA.DT_REGISTRAZIONE,
          FATTURA_PASSIVA.NR_FATTURA_FORNITORE,
          FATTURA_PASSIVA.DT_FATTURA_FORNITORE,
          FATTURA_PASSIVA.CD_MODALITA_PAG_UO_CDS,
          FATTURA_PASSIVA.IM_TOTALE_IMPONIBILE,
          FATTURA_PASSIVA.IM_TOTALE_IVA,
          FATTURA_PASSIVA.IM_TOTALE_FATTURA,
          FATTURA_PASSIVA.ESERCIZIO_LETTERA,
          FATTURA_PASSIVA.PG_LETTERA,
          FATTURA_PASSIVA.CD_DIVISA,
          FATTURA_PASSIVA_RIGA.PROGRESSIVO_RIGA,
          FATTURA_PASSIVA_RIGA.DS_RIGA_FATTURA,
          FATTURA_PASSIVA_RIGA.IM_IMPONIBILE,
          FATTURA_PASSIVA_RIGA.CD_VOCE_IVA,
          FATTURA_PASSIVA_RIGA.IM_IVA,
          FATTURA_PASSIVA_RIGA.DT_DA_COMPETENZA_COGE,
          FATTURA_PASSIVA_RIGA.DT_A_COMPETENZA_COGE,
          'E',
          FATTURA_PASSIVA_RIGA.CD_CDS_ACCERTAMENTO,
          FATTURA_PASSIVA_RIGA.ESERCIZIO_ACCERTAMENTO,
          FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_ACCERTAMENTO,
          FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO,
          FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO_SCADENZARIO,
          REVERSALE.CD_CDS,
          REVERSALE.ESERCIZIO,
          REVERSALE.PG_REVERSALE,
          REVERSALE.CD_TIPO_DOCUMENTO_CONT,
          REVERSALE.TI_REVERSALE,
          REVERSALE.TI_COMPETENZA_RESIDUO,
          REVERSALE.DS_REVERSALE,
          REVERSALE.DT_EMISSIONE,
          REVERSALE.DT_TRASMISSIONE,
          REVERSALE.DT_INCASSO,
          Null,  --DISTINTA_CASSIERE.PG_DISTINTA,
          Null,  --DISTINTA_CASSIERE.DT_EMISSIONE,
          Null   --DISTINTA_CASSIERE.DT_INVIO
FROM  FATTURA_PASSIVA, FATTURA_PASSIVA_RIGA,
      REVERSALE, REVERSALE_RIGA,
      UNITA_ORGANIZZATIVA UO_CDS,
      UNITA_ORGANIZZATIVA UO_UO
WHERE UO_CDS.CD_UNITA_ORGANIZZATIVA            = FATTURA_PASSIVA.CD_CDS                      AND
      UO_UO.CD_UNITA_ORGANIZZATIVA             = FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA      AND
      FATTURA_PASSIVA.CD_CDS                     = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA     = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      FATTURA_PASSIVA.ESERCIZIO                  = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      FATTURA_PASSIVA.PG_FATTURA_PASSIVA         = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     AND
      REVERSALE_RIGA.CD_CDS                      = REVERSALE.CD_CDS                            AND
      REVERSALE_RIGA.ESERCIZIO                   = REVERSALE.ESERCIZIO                         AND
      REVERSALE_RIGA.PG_REVERSALE                  = REVERSALE.PG_REVERSALE                      AND
      REVERSALE_RIGA.CD_CDS                      = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      --REVERSALE_RIGA.ESERCIZIO_ACCERTAMENTO      = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      REVERSALE_RIGA.ESERCIZIO_ORI_ACCERTAMENTO  = FATTURA_PASSIVA_RIGA.ESERCIZIO_ORI_ACCERTAMENTO AND
      REVERSALE_RIGA.PG_ACCERTAMENTO             = FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO        AND
      REVERSALE_RIGA.PG_ACCERTAMENTO_SCADENZARIO = FATTURA_PASSIVA_RIGA.PG_ACCERTAMENTO_SCADENZARIO AND
      REVERSALE_RIGA.CD_CDS_DOC_AMM              = FATTURA_PASSIVA_RIGA.CD_CDS                 AND
      REVERSALE_RIGA.CD_UO_DOC_AMM               = FATTURA_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA AND
      REVERSALE_RIGA.ESERCIZIO_DOC_AMM           = FATTURA_PASSIVA_RIGA.ESERCIZIO              AND
      REVERSALE_RIGA.CD_TIPO_DOCUMENTO_AMM       = 'FATTURA_P'                                 AND
      REVERSALE_RIGA.PG_DOC_AMM                  = FATTURA_PASSIVA_RIGA.PG_FATTURA_PASSIVA     AND
      REVERSALE_RIGA.STATO                       != 'A'  And
      Not Exists
      (Select '1' From Distinta_cassiere_det
       Where DISTINTA_CASSIERE_DET.CD_CDS_origine = REVERSALE.CD_CDS And
             DISTINTA_CASSIERE_DET.ESERCIZIO = REVERSALE.ESERCIZIO And
             DISTINTA_CASSIERE_DET.PG_REVERSALE = REVERSALE.PG_REVERSALE);

   COMMENT ON TABLE "PRT_ELENCO_FATT_PER_FORNITORE"  IS 'Vista di stampa elenco fatture passive per fornitore';
