--------------------------------------------------------
--  DDL for View PRT_REND_FIN_SPE_GEST_CAPITOLO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_REND_FIN_SPE_GEST_CAPITOLO" ("ESERCIZIO", "ST_DIP_YN", "SCIENT_YN", "PESO_DIP", "NUM_DIP", "DIP", "DS_DIPARTIMENTO", "CDS", "DS_CDS", "CD_ELEMENTO_VOCE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "CD_LIVELLO1_ROM", "DS_LIVELLO1", "CD_LIVELLO2", "DS_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "DS_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "PREV_INIZIALE", "VAR_PIU_COMP", "VAR_MENO_COMP", "PAGATO_COMP", "IM_OBBL_ACC_COMP", "RESIDUI_INIZIALI", "PAGATO_RES", "RES_DA_PAGARE", "VAR_PIU_RES", "VAR_MENO_RES", "ASSEST_CASSA") AS 
  SELECT ESERCIZIO, ST_DIP_YN, SCIENT_YN, PESO_DIP, NUM_DIP,
 DIP, DS_DIPARTIMENTO, CDS, DS_CDS, CD_ELEMENTO_VOCE, CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO,
 CD_LIVELLO1, CD_LIVELLO1_ROM, DS_LIVELLO1, CD_LIVELLO2, DS_LIVELLO2,
 CD_LIVELLO3, CD_LIVELLO4, DS_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6,
 CD_LIVELLO7,
 SUM(PREV_INIZIALE),
 SUM(VAR_PIU_COMP),
 SUM(VAR_MENO_COMP),
 SUM(PAGATO_COMP),
 SUM(IM_OBBL_ACC_COMP),
 SUM(RESIDUI_INIZIALI),
 SUM(PAGATO_RES),
 SUM(RES_DA_PAGARE),
 SUM(VAR_PIU_RES),
 SUM(VAR_MENO_RES),
 SUM(ASSEST_CASSA)
FROM PRT_REND_FIN_SPE_GEST
GROUP BY ESERCIZIO, ST_DIP_YN, SCIENT_YN, PESO_DIP, NUM_DIP,
 DIP, DS_DIPARTIMENTO, CDS, DS_CDS, CD_ELEMENTO_VOCE, CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO,
 CD_LIVELLO1, CD_LIVELLO1_ROM, DS_LIVELLO1, CD_LIVELLO2, DS_LIVELLO2,
 CD_LIVELLO3, CD_LIVELLO4, DS_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6,
 CD_LIVELLO7
;
