--------------------------------------------------------
--  DDL for View PRT_VPG_REND_FIN_ENT_SPE_DEC
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "PRT_VPG_REND_FIN_ENT_SPE_DEC" ("ID", "CHIAVE", "TIPO", "SEQUENZA", "ESERCIZIO", "ST_DIP_YN", "SCIENT_YN", "PESO_DIP", "NUM_DIP", "DIP", "DS_DIPARTIMENTO", "CD_LIVELLO1", "CD_LIVELLO1_ROM", "DS_LIVELLO1", "CD_LIVELLO2", "DS_LIVELLO2", "IM_OBBL_ACC_COMP", "FULL_COST_AC", "RES_FINALI", "RIS_PAG_TOT", "IM_OBBL_ACC_COMP_AP", "RES_FINALI_AP", "FULL_COST_AP", "RIS_PAG_TOT_AP") AS 
  SELECT ID, CHIAVE, TIPO, SEQUENZA,
IMPORTO_1, -- ESERCIZIO,
ATTRIBUTO_1, -- ST_DIP_YN,
ATTRIBUTO_2, -- SCIENT_YN,
ATTRIBUTO_3, -- PESO_DIP,
ATTRIBUTO_4, -- NUM_DIP,
ATTRIBUTO_5, -- DIP,
ATTRIBUTO_6, -- DS_DIPARTIMENTO,
ATTRIBUTO_14, -- CD_LIVELLO1,
ATTRIBUTO_15, -- CD_LIVELLO1_ROM,
ATTRIBUTO_16, -- DS_LIVELLO1,
ATTRIBUTO_17, -- CD_LIVELLO2,
ATTRIBUTO_18, -- DS_LIVELLO2,
IMPORTO_3, -- IM_OBBL_ACC_COMP,
IMPORTO_9, -- FULL_COST_AC
IMPORTO_4, -- RES_FINALI,
IMPORTO_5, -- RISCOSSIONI_TOT,
IMPORTO_6, -- IM_OBBL_ACC_COMP_AP,
IMPORTO_7, -- RES_FINALI_AP,
IMPORTO_10, -- FULL_COST_AP
IMPORTO_8 -- RISCOSSIONI_TOT_AP
FROM TMP_REPORT_GENERICO
;
