--------------------------------------------------------
--  DDL for View RICONCILIAZIONE_CNR_CDS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "RICONCILIAZIONE_CNR_CDS" ("ESERCIZIO", "CD_CDS", "RES_FIN_CNR", "RES_FIN_CDS_DA_COMP", "RES_FIN_CDS_DA_RES", "FONDO_CASSA_FIN_ES_CORSO", "FONDO_CASSA_INI_ES_SUCC") AS 
  Select ES.ESERCIZIO, ES.CD_CDS,
      (Select Sum(IM_OBBL_ACC_COMP + IM_OBBL_RES_PRO + VAR_PIU_OBBL_RES_PRO - VAR_MENO_OBBL_RES_PRO - IM_MANDATI_REVERSALI_PRO)
       From   VOCE_F_SALDI_CDR_LINEA
       Where  VOCE_F_SALDI_CDR_LINEA.ESERCIZIO = ES.ESERCIZIO AND
              TI_GESTIONE = 'S' AND
              TI_APPARTENENZA = 'C' AND
              SUBSTR(CD_VOCE, 17, 3) = ES.CD_CDS) RES_FIN_CNR,
      (Select Sum(IM_STANZ_INIZIALE_A1 + VARIAZIONI_PIU - VARIAZIONI_MENO - IM_MANDATI_REVERSALI_PRO)
       From   VOCE_F_SALDI_CDR_LINEA
       Where  VOCE_F_SALDI_CDR_LINEA.ESERCIZIO = ES.ESERCIZIO And
              VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES = ES.ESERCIZIO And
              TI_GESTIONE = 'S' AND
              TI_APPARTENENZA = 'D' AND
              CNRUTL001.GETCDSFROMCDR(VOCE_F_SALDI_CDR_LINEA.cd_centro_responsabilita) = ES.CD_CDS) RES_FIN_CDS_DA_COMP,
      (Select Sum((IM_STANZ_RES_IMPROPRIO + VAR_PIU_STANZ_RES_IMP - VAR_MENO_STANZ_RES_IMP - VAR_PIU_OBBL_RES_PRO + VAR_MENO_OBBL_RES_PRO - IM_OBBL_RES_IMP) +
                  (IM_OBBL_RES_PRO + VAR_PIU_OBBL_RES_PRO - VAR_MENO_OBBL_RES_PRO - IM_MANDATI_REVERSALI_PRO) +
                  (IM_OBBL_RES_IMP - IM_MANDATI_REVERSALI_IMP))
       From   VOCE_F_SALDI_CDR_LINEA
       Where  VOCE_F_SALDI_CDR_LINEA.ESERCIZIO = ES.ESERCIZIO AND
              VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES < ES.ESERCIZIO And
              TI_GESTIONE = 'S' AND
              TI_APPARTENENZA = 'D' AND
              CNRUTL001.GETCDSFROMCDR(VOCE_F_SALDI_CDR_LINEA.cd_centro_responsabilita) = ES.CD_CDS) RES_FIN_CDS_DA_RES,
        0,
       (Select IM_CASSA_INIZIALE From ESERCIZIO Where CD_CDS = ES.CD_CDS And ESERCIZIO = ES.ESERCIZIO+1)
From   ESERCIZIO ES;
