--------------------------------------------------------
--  DDL for View V_ABIL_PROGETTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_ABIL_PROGETTI" ("ESERCIZIO_PROGETTO", "PG_PROGETTO", "TIPO_FASE_PROGETTO", "ESERCIZIO_COMMESSA", "PG_COMMESSA", "TIPO_FASE_COMMESSA", "ESERCIZIO_MODULO", "PG_MODULO", "TIPO_FASE_MODULO", "CD_UNITA_ORGANIZZATIVA") AS 
  SELECT 
COMMESSA.ESERCIZIO_PROGETTO_PADRE ESERCIZIO_PROGETTO, COMMESSA.PG_PROGETTO_PADRE PG_PROGETTO, COMMESSA.TIPO_FASE_PROGETTO_PADRE TIPO_FASE_PROGETTO,
COMMESSA.ESERCIZIO ESERCIZIO_COMMESSA, COMMESSA.PG_PROGETTO PG_COMMESSA, COMMESSA.TIPO_FASE TIPO_FASE_COMMESSA,
MODULO.ESERCIZIO   ESERCIZIO_MODULO,   MODULO.PG_PROGETTO   PG_MODULO,   MODULO.TIPO_FASE   TIPO_FASSE_MODULO,
MODULO.CD_UNITA_ORGANIZZATIVA
From PROGETTO MODULO, PROGETTO COMMESSA
Where MODULO.LIVELLO = 3
  And MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO
  And MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO
  And MODULO.TIPO_FASE_PROGETTO_PADRE = COMMESSA.TIPO_FASE
  And COMMESSA.LIVELLO = 2
;
