--------------------------------------------------------
--  DDL for View V_ABIL_PROGETTI_PROVA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_ABIL_PROGETTI_PROVA" ("CD_UNITA_ORGANIZZATIVA", "ESERCIZIO_MODULO", "PG_MODULO", "TIPO_FASE_MODULO", "ESERCIZIO_COMMESSA", "PG_COMMESSA", "TIPO_FASE_COMMESSA") AS 
  SELECT 
-- 
-- Date: 09/11/2006 
-- Version: 1.1 
-- 
-- Vista per controllare le abilitazioni dei progetti 
-- 
-- History: 
-- 
-- Date: 24/10/2005 
-- Version: 1.0 
-- Creazione 
-- 
-- Date: 09/11/2006 
-- Version: 1.1 
-- Aggiunta l'anno del progetto/commessa/modulo e la tipologia PREV/GEST del progetto 
-- 
-- Body: 
-- 
MODULO.CD_UNITA_ORGANIZZATIVA, 
MODULO.ESERCIZIO   ESERCIZIO_MODULO,   MODULO.PG_PROGETTO   PG_MODULO,   MODULO.TIPO_FASE   TIPO_FASE_MODULO, 
COMMESSA.ESERCIZIO ESERCIZIO_COMMESSA, COMMESSA.PG_PROGETTO PG_COMMESSA, COMMESSA.TIPO_FASE TIPO_FASE_COMMESSA 
--, 
--PROGETTO.ESERCIZIO ESERCIZIO_PROGETTO, PROGETTO.PG_PROGETTO PG_PROGETTO, PROGETTO.TIPO_FASE TIPO_FASE_PROGETTO 
From PROGETTO MODULO, PROGETTO COMMESSA--, PROGETTO PROGETTO 
Where MODULO.LIVELLO=3 
And   COMMESSA.ESERCIZIO = 2006 
And   COMMESSA.PG_PROGETTO = 5050 
And   COMMESSA.TIPO_FASE = 'C' 
--/ 
--  And COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO 
--  And COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO 
--  And COMMESSA.TIPO_FASE_PROGETTO_PADRE = PROGETTO.TIPO_FASE 
--;
