--------------------------------------------------------
--  DDL for View V_ABIL_PROGETTI_MARCO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_ABIL_PROGETTI_MARCO" ("ESERCIZIO_PROGETTO", "PG_PROGETTO", "TIPO_FASE_PROGETTO", "ESERCIZIO_COMMESSA", "PG_COMMESSA", "TIPO_FASE_COMMESSA", "ESERCIZIO_MODULO", "PG_MODULO", "TIPO_FASE_MODULO", "CD_UNITA_ORGANIZZATIVA") AS 
  Select
MODULO.ESERCIZIO   ESERCIZIO_PROGETTO,
(Select PROGETTO.PG_PROGETTO PG_PROGETTO
FROM PROGETTO
Where COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO
  And COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO
  And COMMESSA.TIPO_FASE_PROGETTO_PADRE = PROGETTO.TIPO_FASE
),
MODULO.TIPO_FASE TIPO_FASE_PROGETTO,
COMMESSA.ESERCIZIO ESERCIZIO_COMMESSA, COMMESSA.PG_PROGETTO PG_COMMESSA, COMMESSA.TIPO_FASE TIPO_FASE_COMMESSA,
MODULO.ESERCIZIO   ESERCIZIO_MODULO,   MODULO.PG_PROGETTO   PG_MODULO,   MODULO.TIPO_FASE   TIPO_FASE_MODULO, MODULO.CD_UNITA_ORGANIZZATIVA
From PROGETTO MODULO, PROGETTO COMMESSA--, PROGETTO PROGETTO
Where MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO
  And MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO
  And MODULO.TIPO_FASE_PROGETTO_PADRE = COMMESSA.TIPO_FASE
  --And COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO
  --And COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO
  --And COMMESSA.TIPO_FASE_PROGETTO_PADRE = PROGETTO.TIPO_FASE
;
