--------------------------------------------------------
--  DDL for View V_ASSESTATO_RESIDUO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_ASSESTATO_RESIDUO" ("ESERCIZIO", "ESERCIZIO_RES", "CD_CENTRO_RESPONSABILITA", "CD_LINEA_ATTIVITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_VOCE", "CD_ELEMENTO_VOCE", "ASSESTATO_RES", "TOT_IMP_RES_IMP", "DISP_RES_IMP", "VARIAZIONI_PROVVISORIE", "VARIAZIONI_DEFINITIVE", "TOTALE") AS 
  Select
  ESERCIZIO,
  ESERCIZIO_RES,
  CD_CENTRO_RESPONSABILITA,
  CD_LINEA_ATTIVITA,
  TI_APPARTENENZA,
  TI_GESTIONE,
  CD_VOCE,
  CD_ELEMENTO_VOCE,
  ASSESTATO_RES,
  TOT_IMP_RES_IMP,
  (ASSESTATO_RES - TOT_IMP_RES_IMP) DISP_RES_IMP,
  VARIAZIONI_PROVVISORIE,
  VARIAZIONI_DEFINITIVE,
  ((ASSESTATO_RES - TOT_IMP_RES_IMP) + VARIAZIONI_PROVVISORIE + VARIAZIONI_DEFINITIVE) TOTALE
From (
Select
--
-- Date: 27/02/2006
-- Version: 1.0
--
-- Vista di estrazione dei Saldi per l'assestato resuduo
--
-- History:
--
-- Date: 27/02/2006
-- Version: 1.0
-- Creazione
--
-- Body:
--
VOCE_F_SALDI_CDR_LINEA.ESERCIZIO,
VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES,
VOCE_F_SALDI_CDR_LINEA.CD_CENTRO_RESPONSABILITA,
VOCE_F_SALDI_CDR_LINEA.CD_LINEA_ATTIVITA,
VOCE_F_SALDI_CDR_LINEA.TI_APPARTENENZA,
VOCE_F_SALDI_CDR_LINEA.TI_GESTIONE,
VOCE_F_SALDI_CDR_LINEA.CD_VOCE,
VOCE_F_SALDI_CDR_LINEA.CD_ELEMENTO_VOCE,
Sum((IM_STANZ_RES_IMPROPRIO + VAR_PIU_STANZ_RES_IMP - VAR_MENO_STANZ_RES_IMP) +
  (VAR_MENO_OBBL_RES_PRO - VAR_PIU_OBBL_RES_PRO)) ASSESTATO_RES, 
Sum((IM_OBBL_RES_IMP + VAR_PIU_OBBL_RES_IMP - VAR_MENO_OBBL_RES_IMP)) TOT_IMP_RES_IMP,
(Select Nvl(Sum(VAR_STANZ_RES_RIGA.IM_VARIAZIONE),0)
 From VAR_STANZ_RES_RIGA, VAR_STANZ_RES
 Where VOCE_F_SALDI_CDR_LINEA.ESERCIZIO = VAR_STANZ_RES_RIGA.ESERCIZIO
   And VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES = VAR_STANZ_RES_RIGA.ESERCIZIO_RES
   And VOCE_F_SALDI_CDR_LINEA.CD_CENTRO_RESPONSABILITA = VAR_STANZ_RES_RIGA.CD_CDR
   And VOCE_F_SALDI_CDR_LINEA.CD_LINEA_ATTIVITA = VAR_STANZ_RES_RIGA.CD_LINEA_ATTIVITA
   And VOCE_F_SALDI_CDR_LINEA.TI_APPARTENENZA = VAR_STANZ_RES_RIGA.TI_APPARTENENZA
   And VOCE_F_SALDI_CDR_LINEA.TI_GESTIONE = VAR_STANZ_RES_RIGA.TI_GESTIONE
   And VOCE_F_SALDI_CDR_LINEA.CD_VOCE = VAR_STANZ_RES_RIGA.CD_VOCE
   And VAR_STANZ_RES_RIGA.ESERCIZIO = VAR_STANZ_RES.ESERCIZIO
   And VAR_STANZ_RES_RIGA.PG_VARIAZIONE = VAR_STANZ_RES.PG_VARIAZIONE
   And VAR_STANZ_RES.STATO = 'PRP'
 ) VARIAZIONI_PROVVISORIE,
(Select Nvl(Sum(VAR_STANZ_RES_RIGA.IM_VARIAZIONE),0)
 From VAR_STANZ_RES_RIGA, VAR_STANZ_RES
 Where VOCE_F_SALDI_CDR_LINEA.ESERCIZIO = VAR_STANZ_RES_RIGA.ESERCIZIO
   And VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES = VAR_STANZ_RES_RIGA.ESERCIZIO_RES
   And VOCE_F_SALDI_CDR_LINEA.CD_CENTRO_RESPONSABILITA = VAR_STANZ_RES_RIGA.CD_CDR
   And VOCE_F_SALDI_CDR_LINEA.CD_LINEA_ATTIVITA = VAR_STANZ_RES_RIGA.CD_LINEA_ATTIVITA
   And VOCE_F_SALDI_CDR_LINEA.TI_APPARTENENZA = VAR_STANZ_RES_RIGA.TI_APPARTENENZA
   And VOCE_F_SALDI_CDR_LINEA.TI_GESTIONE = VAR_STANZ_RES_RIGA.TI_GESTIONE
   And VOCE_F_SALDI_CDR_LINEA.CD_VOCE = VAR_STANZ_RES_RIGA.CD_VOCE
   And VAR_STANZ_RES_RIGA.ESERCIZIO = VAR_STANZ_RES.ESERCIZIO
   And VAR_STANZ_RES_RIGA.PG_VARIAZIONE = VAR_STANZ_RES.PG_VARIAZIONE
   And VAR_STANZ_RES.STATO = 'PRD'
 ) VARIAZIONI_DEFINITIVE
FROM VOCE_F_SALDI_CDR_LINEA
Group By VOCE_F_SALDI_CDR_LINEA.ESERCIZIO,
VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES,
VOCE_F_SALDI_CDR_LINEA.CD_CENTRO_RESPONSABILITA,
VOCE_F_SALDI_CDR_LINEA.CD_LINEA_ATTIVITA,
VOCE_F_SALDI_CDR_LINEA.TI_APPARTENENZA,
VOCE_F_SALDI_CDR_LINEA.TI_GESTIONE,
VOCE_F_SALDI_CDR_LINEA.CD_VOCE,
VOCE_F_SALDI_CDR_LINEA.CD_ELEMENTO_VOCE)
;
