--------------------------------------------------------
--  DDL for View V_ASS_INV_BENE_FATTURA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_ASS_INV_BENE_FATTURA" ("CD_CDS_FATT_PASS", "CD_UO_FATT_PASS", "ESERCIZIO_FATT_PASS", "PG_FATTURA_PASSIVA", "PROGRESSIVO_RIGA_FATT_PASS", "PG_INVENTARIO", "NR_INVENTARIO", "PROGRESSIVO", "DS_BENE", "DS_FATTURA", "CD_TERZO", "DS_TERZO", "TIPO", "PG_BUONO_C_S", "TI_DOCUMENTO", "ESERCIZIO", "CD_TIPO_DOCUMENTO_AMM") AS 
  SELECT
  ASS.CD_CDS_FATT_PASS           ,
  ASS.CD_UO_FATT_PASS            ,
  ASS.ESERCIZIO_FATT_PASS        ,
  ASS.PG_FATTURA_PASSIVA     ,
  ASS.PROGRESSIVO_RIGA_FATT_PASS ,
  ASS.PG_INVENTARIO              ,
  ASS.NR_INVENTARIO              ,
  ASS.PROGRESSIVO                ,
  BENE.DS_BENE                    ,
  F_PASSIVA.DS_FATTURA_PASSIVA DS_FATTURA,
  F_PASSIVA.CD_TERZO CD_TERZO,
  Nvl(F_PASSIVA.RAGIONE_SOCIALE,Nvl(f_passiva.cognome,' ')||' '||Nvl(f_passiva.nome,' ')) DS_TERZO,Decode(f_passiva.ti_fattura,'F','Fattura Passiva','C','Nota Credito da Fatt.Pass.','Nota Debito da Fatt.Pass.') Tipo,
  BUONO.PG_BUONO_C_S,
  BUONO.TI_DOCUMENTO,
  BUONO.ESERCIZIO,
  Null tipo_generico
  FROM ASS_INV_BENE_FATTURA ASS,
       INVENTARIO_BENI     BENE,
       FATTURA_PASSIVA F_PASSIVA,
       FATTURA_PASSIVA_RIGA F_PASSIVA_RIGA,
       BUONO_CARICO_SCARICO_DETT BUONO
  Where
   -- JOIN INVENTARIO_BENE
     --BUONO.TI_DOCUMENTO ='C' And
    (ASS.PG_INVENTARIO = BENE.PG_INVENTARIO  And
     ASS.NR_INVENTARIO = BENE.NR_INVENTARIO  And
     ASS.PROGRESSIVO   = BENE.PROGRESSIVO )  And
      -- JOIN CON DETTAGLIO BUONO
    (ASS.PG_INVENTARIO = BUONO.PG_INVENTARIO And
     ASS.NR_INVENTARIO = BUONO.NR_INVENTARIO And
     ASS.PROGRESSIVO   = BUONO.PROGRESSIVO   And
     (Nvl(ASS.TI_DOCUMENTO,BUONO.TI_DOCUMENTO)  = BUONO.TI_DOCUMENTO  	And
     Nvl(ASS.ESERCIZIO,BUONO.ESERCIZIO)    	= BUONO.ESERCIZIO    	And
     Nvl(ASS.PG_BUONO_C_S,BUONO.PG_BUONO_C_S)  	= BUONO.PG_BUONO_C_S   And
     Nvl(ASS.ESERCIZIO,BUONO.ESERCIZIO)   =  ASS.ESERCIZIO_FATT_PASS )) And
     --
     ( ASS.PG_FATTURA_PASSIVA Is Not Null    						And
       ASS.CD_CDS_FATT_PASS   		= F_PASSIVA_RIGA.CD_CDS   			And
       ASS.CD_UO_FATT_PASS   		= F_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA   	And
       ASS.ESERCIZIO_FATT_PASS         	= F_PASSIVA_RIGA.ESERCIZIO			And
       ASS.PG_FATTURA_PASSIVA           = F_PASSIVA_RIGA.PG_FATTURA_PASSIVA		And
       ASS.PROGRESSIVO_RIGA_FATT_PASS   = F_PASSIVA_RIGA.PROGRESSIVO_RIGA 		And
       F_PASSIVA_RIGA.CD_CDS                 = F_PASSIVA.CD_CDS   			And
       F_PASSIVA_RIGA.CD_UNITA_ORGANIZZATIVA = F_PASSIVA.CD_UNITA_ORGANIZZATIVA   	And
       F_PASSIVA_RIGA.ESERCIZIO		     = F_PASSIVA.ESERCIZIO			And
       F_PASSIVA_RIGA.PG_FATTURA_PASSIVA     = F_PASSIVA.PG_FATTURA_PASSIVA	)
 Union
SELECT
  ASS.CD_CDS_FATT_ATT    	CD_CDS_FATT_PASS,
  ASS.CD_UO_FATT_ATT      	CD_UO_FATT_PASS,
  ASS.ESERCIZIO_FATT_ATT   	ESERCIZIO_FATT_PASS,
  ASS.PG_FATTURA_ATTIVA     	PG_FATTURA_PASSIVA,
  ASS.PROGRESSIVO_RIGA_FATT_ATT PROGRESSIVO_RIGA_FATT_PASS,
  ASS.PG_INVENTARIO              ,
  ASS.NR_INVENTARIO              ,
  ASS.PROGRESSIVO                ,
  BENE.DS_BENE                    ,
  F_attiva.DS_FATTURA_ATTIVA DS_FATTURA,
  F_attiva.CD_TERZO CD_TERZO,
  Nvl(F_attiva.RAGIONE_SOCIALE,Nvl(f_attiva.cognome,' ')||' '||Nvl(f_attiva.nome,' ')) DS_TERZO,Decode(f_attiva.ti_fattura,'F','Fattura Attiva','C','Nota Credito da Fatt.Att.','Nota Debito da Fatt.Att.') Tipo,
  BUONO.PG_BUONO_C_S,
  BUONO.TI_DOCUMENTO,
  BUONO.ESERCIZIO,
  Null tipo_generico
  FROM ASS_INV_BENE_FATTURA ASS,
       INVENTARIO_BENI     BENE,
       FATTURA_ATTIVA F_ATTIVA,
       FATTURA_ATTIVA_RIGA F_ATTIVA_RIGA,
       BUONO_CARICO_SCARICO_DETT BUONO
  Where
   -- JOIN INVENTARIO_BENE
     --BUONO.TI_DOCUMENTO ='S' And
    (ASS.PG_INVENTARIO = BENE.PG_INVENTARIO And
     ASS.NR_INVENTARIO = BENE.NR_INVENTARIO And
     ASS.PROGRESSIVO   = BENE.PROGRESSIVO ) And
     -- JOIN CON DETTAGLIO BUONO
    (ASS.PG_INVENTARIO = BUONO.PG_INVENTARIO And
     ASS.NR_INVENTARIO = BUONO.NR_INVENTARIO And
     ASS.PROGRESSIVO   = BUONO.PROGRESSIVO   And
     Nvl(ASS.TI_DOCUMENTO,BUONO.TI_DOCUMENTO)  	= BUONO.TI_DOCUMENTO  	And
     Nvl(ASS.ESERCIZIO,BUONO.ESERCIZIO)    	= BUONO.ESERCIZIO    	And
     Nvl(ASS.PG_BUONO_C_S,BUONO.PG_BUONO_C_S)  	= BUONO.PG_BUONO_C_S) 	And
     --
     ( ASS.PG_FATTURA_ATTIVA Is Not Null    						And
       ASS.CD_CDS_FATT_ATT   		= F_ATTIVA_RIGA.CD_CDS   			And
       ASS.CD_UO_FATT_ATT   		= F_ATTIVA_RIGA.CD_UNITA_ORGANIZZATIVA   	And
       ASS.ESERCIZIO_FATT_ATT         	= F_ATTIVA_RIGA.ESERCIZIO			And
       ASS.PG_FATTURA_ATTIVA           = F_ATTIVA_RIGA.PG_FATTURA_ATTIVA		And
       ASS.PROGRESSIVO_RIGA_FATT_ATT   = F_ATTIVA_RIGA.PROGRESSIVO_RIGA 		And
       F_ATTIVA_RIGA.CD_CDS                 = F_ATTIVA.CD_CDS   			And
       F_ATTIVA_RIGA.CD_UNITA_ORGANIZZATIVA = F_ATTIVA.CD_UNITA_ORGANIZZATIVA   	And
       F_ATTIVA_RIGA.ESERCIZIO		     = F_ATTIVA.ESERCIZIO			And
       F_ATTIVA_RIGA.PG_FATTURA_ATTIVA     = F_ATTIVA.PG_FATTURA_ATTIVA	)
 Union
SELECT
  ASS.CD_CDS_DOC_GEN    	CD_CDS_FATT_PASS,
  ASS.CD_UO_DOC_GEN      	CD_UO_FATT_PASS,
  ASS.ESERCIZIO_DOC_GEN    	ESERCIZIO_FATT_PASS,
  ASS.PG_DOCUMENTO_GENERICO    	PG_FATTURA_PASSIVA,
  ASS.PROGRESSIVO_RIGA_DOC_GEN  PROGRESSIVO_RIGA_FATT_PASS,
  ASS.PG_INVENTARIO              ,
  ASS.NR_INVENTARIO              ,
  ASS.PROGRESSIVO                ,
  BENE.DS_BENE                    ,
  GEN_RIGA.DS_RIGA DS_FATTURA,
  GEN_RIGA.CD_TERZO CD_TERZO,
  Nvl(GEN_RIGA.RAGIONE_SOCIALE,Nvl(GEN_RIGA.cognome,' ')||' '||Nvl(GEN_RIGA.nome,' ')) DS_TERZO,Decode(GEN_RIGA.CD_TIPO_DOCUMENTO_AMM,'GENERICO_E','Generico Entrata','GENERICO_S','Generico Spesa','Generico') tipo,
  BUONO.PG_BUONO_C_S,
  BUONO.TI_DOCUMENTO,
  BUONO.ESERCIZIO,
  GEN_RIGA.CD_TIPO_DOCUMENTO_AMM tipo_generico
  FROM ASS_INV_BENE_FATTURA ASS,
       INVENTARIO_BENI     BENE,
       DOCUMENTO_GENERICO_RIGA GEN_RIGA,
       BUONO_CARICO_SCARICO_DETT BUONO
  Where
   -- JOIN INVENTARIO_BENE
     --BUONO.TI_DOCUMENTO ='S' And
    (ASS.PG_INVENTARIO = BENE.PG_INVENTARIO And
     ASS.NR_INVENTARIO = BENE.NR_INVENTARIO And
     ASS.PROGRESSIVO   = BENE.PROGRESSIVO ) And
     -- JOIN CON DETTAGLIO BUONO
    (ASS.PG_INVENTARIO = BUONO.PG_INVENTARIO And
     ASS.NR_INVENTARIO = BUONO.NR_INVENTARIO And
     ASS.PROGRESSIVO   = BUONO.PROGRESSIVO   And
     Nvl(ASS.TI_DOCUMENTO,BUONO.TI_DOCUMENTO)  	= BUONO.TI_DOCUMENTO  	And
     Nvl(ASS.ESERCIZIO,BUONO.ESERCIZIO)    	= BUONO.ESERCIZIO    	And
     Nvl(ASS.PG_BUONO_C_S,BUONO.PG_BUONO_C_S)  	= BUONO.PG_BUONO_C_S) 	And
     --
     ( ASS.PG_DOCUMENTO_GENERICO Is Not Null    				And
       ASS.CD_CDS_DOC_GEN   			= GEN_RIGA.CD_CDS   			And
       ASS.CD_UO_DOC_GEN   			= GEN_RIGA.CD_UNITA_ORGANIZZATIVA   	And
       ASS.ESERCIZIO_DOC_GEN         		= GEN_RIGA.ESERCIZIO			And
       ASS.CD_TIPO_DOCUMENTO_AMM 		= GEN_RIGA.CD_TIPO_DOCUMENTO_AMM	AND
       ASS.PG_DOCUMENTO_GENERICO        	= GEN_RIGA.PG_DOCUMENTO_GENERICO	And
       ASS.PROGRESSIVO_RIGA_DOC_GEN     	= GEN_RIGA.PROGRESSIVO_RIGA 		)
 Order By   CD_CDS_FATT_PASS,CD_UO_FATT_PASS,ESERCIZIO_FATT_PASS,PG_FATTURA_PASSIVA,PROGRESSIVO_RIGA_FATT_PASS,
  			PG_INVENTARIO,NR_INVENTARIO, PROGRESSIVO,TI_DOCUMENTO,ESERCIZIO,PG_BUONO_C_S;
