--------------------------------------------------------
--  DDL for View V_BUONO_CARICO_SCARICO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_BUONO_CARICO_SCARICO" ("PG_INVENTARIO", "TI_DOCUMENTO", "ESERCIZIO", "PG_BUONO_C_S", "DS_BUONO_CARICO_SCARICO", "DATA_REGISTRAZIONE", "CD_TIPO_CARICO_SCARICO", "PROVENIENZA", "DACR", "UTCR", "DUVA", "UTUV", "PG_VER_REC", "NR_INVENTARIO", "CD_BARRE") AS 
  SELECT DETT.PG_INVENTARIO, DETT.TI_DOCUMENTO ,DETT.ESERCIZIO ,DETT.PG_BUONO_C_S,
  	DS_BUONO_CARICO_SCARICO ,DATA_REGISTRAZIONE ,CD_TIPO_CARICO_SCARICO  ,PROVENIENZA,
  	DETT.DACR ,DETT.UTCR,DETT.DUVA ,DETT.UTUV,DETT.PG_VER_REC ,DETT.NR_INVENTARIO ,CD_BARRE
  	FROM   BUONO_CARICO_SCARICO,BUONO_CARICO_SCARICO_DETT DETT,INVENTARIO_BENI BENI
  	WHERE
  	DETT.PG_INVENTARIO = BENI.PG_INVENTARIO 		AND
  	DETT.NR_INVENTARIO = BENI.NR_INVENTARIO 		AND
  	DETT.PROGRESSIVO = BENI.PROGRESSIVO 		AND
  	DETT.PG_INVENTARIO = BUONO_CARICO_SCARICO.PG_INVENTARIO	and
  	DETT.ESERCIZIO	   = BUONO_CARICO_SCARICO.ESERCIZIO 	and
  	DETT.TI_DOCUMENTO  = BUONO_CARICO_SCARICO.TI_DOCUMENTO 	and
  	DETT.PG_BUONO_C_S  = BUONO_CARICO_SCARICO.PG_BUONO_C_S;
