--------------------------------------------------------
--  DDL for View V_CDP_STATO_MENSILITA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CDP_STATO_MENSILITA" ("ESERCIZIO", "CD_UNITA_ORGANIZZATIVA", "MESE", "STATO_CARICO", "FL_STATO_SCARICO") AS 
  SELECT
--
-- Date: 20/09/2002
-- Version: 1.1
--
-- Vista di estrazione delle mensilità per la ripartizione dei costi stipendiali
-- mensili
--
-- History:
--
-- Date: 20/09/2002
-- Version: 1.0
-- Creazione
--
-- Date: 18/10/2002
-- Version: 1.1
-- Modifica per gestire il fatto che in STIPENDI_COAN non sempre c'è un record
--
-- Body:
--
  STIPENDI_COFI.ESERCIZIO,
	UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
	STIPENDI_COFI.MESE,
	STIPENDI_COFI.STATO,
	'Y'
FROM
  STIPENDI_COFI,
	UNITA_ORGANIZZATIVA
WHERE
  EXISTS ( SELECT 1 FROM STIPENDI_COAN WHERE
   	STIPENDI_COAN.CD_UO = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA AND
  	STIPENDI_COAN.CD_CDS = UNITA_ORGANIZZATIVA.CD_UNITA_PADRE AND
  	STIPENDI_COAN.ESERCIZIO = STIPENDI_COFI.ESERCIZIO AND
    STIPENDI_COAN.MESE = STIPENDI_COFI.MESE AND
		STIPENDI_COAN.PG_SCRITTURA_AN IS NOT NULL )
UNION
SELECT
  STIPENDI_COFI.ESERCIZIO,
	UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
	STIPENDI_COFI.MESE,
	STIPENDI_COFI.STATO,
	'N'
FROM
  STIPENDI_COFI,
	UNITA_ORGANIZZATIVA
WHERE
  NOT EXISTS ( SELECT 1 FROM STIPENDI_COAN WHERE
   	STIPENDI_COAN.CD_UO = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA AND
  	STIPENDI_COAN.CD_CDS = UNITA_ORGANIZZATIVA.CD_UNITA_PADRE AND
  	STIPENDI_COAN.ESERCIZIO = STIPENDI_COFI.ESERCIZIO AND
    STIPENDI_COAN.MESE = STIPENDI_COFI.MESE AND
		STIPENDI_COAN.PG_SCRITTURA_AN IS NOT NULL )
;

   COMMENT ON TABLE "V_CDP_STATO_MENSILITA"  IS 'Vista di estrazione delle mensilità per la ripartizione dei costi stipendiali mensili';
