--------------------------------------------------------
--  DDL for View V_CONS_DISP_COMP_RES_SINTESI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_DISP_COMP_RES_SINTESI" ("ESERCIZIO", "CDS", "CDR", "DS_CDR", "LDA", "DS_LDA", "CD_RESPONSABILE_TERZO", "DENOMINAZIONE_SEDE", "CD_ELEMENTO_VOCE", "DS_VOCE", "DISP_COMP", "DISP_RES") AS 
  SELECT   ESERCIZIO, CDS, CDR, DS_CDR, LDA, DS_LDA, LINEA_ATTIVITA.CD_RESPONSABILE_TERZO, (SELECT DENOMINAZIONE_SEDE FROM TERZO WHERE LINEA_ATTIVITA.CD_RESPONSABILE_TERZO = CD_TERZO) DENOMINAZIONE_SEDE, CD_ELEMENTO_VOCE, DS_VOCE, SUM(DISP_COMP), SUM(DISP_RES)
FROM     V_CONS_DISP_COMP_RES, LINEA_ATTIVITA 
WHERE    V_CONS_DISP_COMP_RES.CDR = LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA AND 
         V_CONS_DISP_COMP_RES.LDA = LINEA_ATTIVITA.CD_LINEA_ATTIVITA 
GROUP BY ESERCIZIO, CDS, CDR, DS_CDR, LDA, DS_LDA, LINEA_ATTIVITA.CD_RESPONSABILE_TERZO, CD_ELEMENTO_VOCE, DS_VOCE
HAVING SUM(DISP_COMP)+SUM(DISP_RES) != 0;
