--------------------------------------------------------
--  DDL for View V_CONS_PARTITE_GIRO_DET
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PARTITE_GIRO_DET" ("ESERCIZIO", "TI_ORIGINE", "CD_CDS_OBB", "ESERCIZIO_OBB", "CD_UNITA_ORGANIZZATIVA_OBB", "CD_CDS_ORIGINE_OBB", "CD_UO_ORIGINE_OBB", "CD_ELEMENTO_VOCE_OBB", "ESERCIZIO_ORI_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "IM_SCADENZA_COMP_OBB", "IM_SCADENZA_RES_OBB", "IM_ASSOCIATO_DOC_AMM_COMP_OBB", "IM_ASSOCIATO_DOC_AMM_RES_OBB", "IM_PAGATO_COMP", "IM_PAGATO_RES", "CD_CDS_ACR", "ESERCIZIO_ACR", "CD_UNITA_ORGANIZZATIVA_ACR", "CD_CDS_ORIGINE_ACR", "CD_UO_ORIGINE_ACR", "CD_ELEMENTO_VOCE_ACR", "ESERCIZIO_ORI_ACCERTAMENTO", "PG_ACCERTAMENTO", "IM_SCADENZA_COMP_ACR", "IM_SCADENZA_RES_ACR", "IM_ASSOCIATO_DOC_COMP_ACR", "IM_ASSOCIATO_DOC_RES_ACR", "IM_INCASSATO_COMP", "IM_INCASSATO_RES") AS 
  SELECT      ASS_OBB_ACR_PGIRO.ESERCIZIO,
	    ASS_OBB_ACR_PGIRO.TI_ORIGINE,
	    V_CONS_OBBLIGAZIONI.CD_CDS CD_CDS_OBB,
	    V_CONS_OBBLIGAZIONI.ESERCIZIO ESERCIZIO_OBB,
	    V_CONS_OBBLIGAZIONI.CD_UNITA_ORGANIZZATIVA CD_UNITA_ORGANIZZATIVA_OBB,
	    V_CONS_OBBLIGAZIONI.CD_CDS_ORIGINE CD_CDS_ORIGINE_OBB,
	    V_CONS_OBBLIGAZIONI.CD_UO_ORIGINE CD_UO_ORIGINE_OBB,
	    V_CONS_OBBLIGAZIONI.CD_ELEMENTO_VOCE CD_ELEMENTO_VOCE_OBB,
	    V_CONS_OBBLIGAZIONI.ESERCIZIO_ORIGINALE ESERCIZIO_ORI_OBBLIGAZIONE,
	    V_CONS_OBBLIGAZIONI.PG_OBBLIGAZIONE,
	    V_CONS_OBBLIGAZIONI.IM_SCADENZA_COMP IM_SCADENZA_COMP_OBB,
	    V_CONS_OBBLIGAZIONI.IM_SCADENZA_RES IM_SCADENZA_RES_OBB,
	    V_CONS_OBBLIGAZIONI.IM_ASSOCIATO_DOC_AMM_COMP IM_ASSOCIATO_DOC_AMM_COMP_OBB,
	    V_CONS_OBBLIGAZIONI.IM_ASSOCIATO_DOC_AMM_RES IM_ASSOCIATO_DOC_AMM_RES_OBB,
	    V_CONS_OBBLIGAZIONI.IM_PAGATO_COMP,
	    V_CONS_OBBLIGAZIONI.IM_PAGATO_RES,
            V_CONS_ACCERTAMENTI.CD_CDS CD_CDS_ACR,
            V_CONS_ACCERTAMENTI.ESERCIZIO ESERCIZIO_ACR,
	    V_CONS_ACCERTAMENTI.CD_UNITA_ORGANIZZATIVA CD_UNITA_ORGANIZZATIVA_ACR,
	    V_CONS_ACCERTAMENTI.CD_CDS_ORIGINE CD_CDS_ORIGINE_ACR,
	    V_CONS_ACCERTAMENTI.CD_UO_ORIGINE CD_UO_ORIGINE_ACR,
            V_CONS_ACCERTAMENTI.CD_ELEMENTO_VOCE  CD_ELEMENTO_VOCE_ACR,
	    V_CONS_ACCERTAMENTI.ESERCIZIO_ORIGINALE ESERCIZIO_ORI_ACCERTAMENTO,
	    V_CONS_ACCERTAMENTI.PG_ACCERTAMENTO,
	    V_CONS_ACCERTAMENTI.IM_SCADENZA_COMP IM_SCADENZA_COMP_ACR,
	    V_CONS_ACCERTAMENTI.IM_SCADENZA_RES IM_SCADENZA_RES_ACR,
	    V_CONS_ACCERTAMENTI.IM_ASSOCIATO_DOC_AMM_COMP IM_ASSOCIATO_DOC_COMP_ACR,
	    V_CONS_ACCERTAMENTI.IM_ASSOCIATO_DOC_AMM_RES IM_ASSOCIATO_DOC_RES_ACR,
	    V_CONS_ACCERTAMENTI.IM_INCASSATO_COMP,
	    V_CONS_ACCERTAMENTI.IM_INCASSATO_RES
FROM        ASS_OBB_ACR_PGIRO,
	    V_CONS_OBBLIGAZIONI,
	    V_CONS_ACCERTAMENTI
WHERE
-- JOIN         ASS_OBB_ACR_PGIRO
--              OBBLIGAZIONE
   	    ASS_OBB_ACR_PGIRO.CD_CDS	  	                        = V_CONS_OBBLIGAZIONI.CD_CDS
AND	    ASS_OBB_ACR_PGIRO.ESERCIZIO 		                = V_CONS_OBBLIGAZIONI.ESERCIZIO
AND	    ASS_OBB_ACR_PGIRO.ESERCIZIO_ORI_OBBLIGAZIONE                = V_CONS_OBBLIGAZIONI.ESERCIZIO_ORIGINALE
AND	    ASS_OBB_ACR_PGIRO.PG_OBBLIGAZIONE	                        = V_CONS_OBBLIGAZIONI.PG_OBBLIGAZIONE
-- JOIN         ASS_OBB_ACR_PGIRO
--              ACCERTAMENTO
AND	    ASS_OBB_ACR_PGIRO.CD_CDS	  	                        = V_CONS_ACCERTAMENTI.CD_CDS
AND	    ASS_OBB_ACR_PGIRO.ESERCIZIO 		                = V_CONS_ACCERTAMENTI.ESERCIZIO
AND	    ASS_OBB_ACR_PGIRO.ESERCIZIO_ORI_ACCERTAMENTO                = V_CONS_ACCERTAMENTI.ESERCIZIO_ORIGINALE
AND	    ASS_OBB_ACR_PGIRO.PG_ACCERTAMENTO	                        = V_CONS_ACCERTAMENTI.PG_ACCERTAMENTO
Union
SELECT      V_CONS_OBBLIGAZIONI.ESERCIZIO,
	    Null,
	    V_CONS_OBBLIGAZIONI.CD_CDS CD_CDS_OBB,
	    V_CONS_OBBLIGAZIONI.ESERCIZIO ESERCIZIO_OBB,
	    V_CONS_OBBLIGAZIONI.CD_UNITA_ORGANIZZATIVA CD_UNITA_ORGANIZZATIVA_OBB,
	    V_CONS_OBBLIGAZIONI.CD_CDS_ORIGINE CD_CDS_ORIGINE_OBB,
	    V_CONS_OBBLIGAZIONI.CD_UO_ORIGINE CD_UO_ORIGINE_OBB,
	    V_CONS_OBBLIGAZIONI.CD_ELEMENTO_VOCE CD_ELEMENTO_VOCE_OBB,
	    V_CONS_OBBLIGAZIONI.ESERCIZIO_ORIGINALE ESERCIZIO_ORI_OBBLIGAZIONE,
	    V_CONS_OBBLIGAZIONI.PG_OBBLIGAZIONE,
	    V_CONS_OBBLIGAZIONI.IM_SCADENZA_COMP IM_SCADENZA_COMP_OBB,
	    V_CONS_OBBLIGAZIONI.IM_SCADENZA_RES IM_SCADENZA_RES_OBB,
	    V_CONS_OBBLIGAZIONI.IM_ASSOCIATO_DOC_AMM_COMP IM_ASSOCIATO_DOC_AMM_COMP_OBB,
	    V_CONS_OBBLIGAZIONI.IM_ASSOCIATO_DOC_AMM_RES IM_ASSOCIATO_DOC_AMM_RES_OBB,
	    V_CONS_OBBLIGAZIONI.IM_PAGATO_COMP,
	    V_CONS_OBBLIGAZIONI.IM_PAGATO_RES,
            Null,
            Null,
	    Null,
	    Null,
	    Null,
            Null,
	    Null,
	    Null,
	    0,
	    0,
	    0,
	    0,
	    0,
	    0
From        V_CONS_OBBLIGAZIONI
Where       V_CONS_OBBLIGAZIONI.FL_PGIRO = 'Y'
And         Not exists
                  (Select 1
                   From    ASS_OBB_ACR_PGIRO
                   where   ASS_OBB_ACR_PGIRO.CD_CDS  	           = V_CONS_OBBLIGAZIONI.CD_CDS
	           And     ASS_OBB_ACR_PGIRO.ESERCIZIO             = V_CONS_OBBLIGAZIONI.ESERCIZIO
                   And	   ASS_OBB_ACR_PGIRO.ESERCIZIO_ORI_OBBLIGAZIONE = V_CONS_OBBLIGAZIONI.ESERCIZIO_ORIGINALE
	           And     ASS_OBB_ACR_PGIRO.PG_OBBLIGAZIONE       = V_CONS_OBBLIGAZIONI.PG_OBBLIGAZIONE )
Union
SELECT      V_CONS_ACCERTAMENTI.ESERCIZIO,
			null,
	    V_CONS_ACCERTAMENTI.CD_CDS,
	    Null,
	    V_CONS_ACCERTAMENTI.CD_UNITA_ORGANIZZATIVA,
	    V_CONS_ACCERTAMENTI.CD_CDS_ORIGINE,
	    V_CONS_ACCERTAMENTI.CD_UO_ORIGINE,
	    Null,
	    Null,
	    Null,
	    0,
	    0,
	    0,
	    0,
	    0,
	    0,
            V_CONS_ACCERTAMENTI.CD_CDS CD_CDS_ACR,
            V_CONS_ACCERTAMENTI.ESERCIZIO ESERCIZIO_ACR,
	    V_CONS_ACCERTAMENTI.CD_UNITA_ORGANIZZATIVA CD_UNITA_ORGANIZZATIVA_ACR,
	    V_CONS_ACCERTAMENTI.CD_CDS_ORIGINE CD_CDS_ORIGINE_ACR,
	    V_CONS_ACCERTAMENTI.CD_UO_ORIGINE CD_UO_ORIGINE_ACR,
            V_CONS_ACCERTAMENTI.CD_ELEMENTO_VOCE  CD_ELEMENTO_VOCE_ACR,
	    V_CONS_ACCERTAMENTI.ESERCIZIO_ORIGINALE ESERCIZIO_ORI_ACCERTAMENTO,
	    V_CONS_ACCERTAMENTI.PG_ACCERTAMENTO,
	    V_CONS_ACCERTAMENTI.IM_SCADENZA_COMP IM_SCADENZA_COMP_ACR,
	    V_CONS_ACCERTAMENTI.IM_SCADENZA_RES IM_SCADENZA_RES_ACR,
	    V_CONS_ACCERTAMENTI.IM_ASSOCIATO_DOC_AMM_COMP IM_ASSOCIATO_DOC_COMP_ACR,
	    V_CONS_ACCERTAMENTI.IM_ASSOCIATO_DOC_AMM_RES IM_ASSOCIATO_DOC_RES_ACR,
	    V_CONS_ACCERTAMENTI.IM_INCASSATO_COMP,
	    V_CONS_ACCERTAMENTI.IM_INCASSATO_RES
FROM        V_CONS_ACCERTAMENTI
Where       V_CONS_ACCERTAMENTI.FL_PGIRO = 'Y'
And         Not exists
                (Select 1
                From 	 ASS_OBB_ACR_PGIRO
                where 	 ASS_OBB_ACR_PGIRO.CD_CDS  	        = V_CONS_ACCERTAMENTI.CD_CDS
	        AND      ASS_OBB_ACR_PGIRO.ESERCIZIO             = V_CONS_ACCERTAMENTI.ESERCIZIO
                AND	 ASS_OBB_ACR_PGIRO.ESERCIZIO_ORI_ACCERTAMENTO  = V_CONS_ACCERTAMENTI.ESERCIZIO_ORIGINALE
	        AND      ASS_OBB_ACR_PGIRO.PG_ACCERTAMENTO      = V_CONS_ACCERTAMENTI.PG_ACCERTAMENTO );
