--------------------------------------------------------
--  DDL for View V_CONS_PDGG_SPE_ASSESTATO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PDGG_SPE_ASSESTATO" ("ESERCIZIO", "PESO_DIP", "DIP", "DS_DIPARTIMENTO", "CDS", "DES_CDS", "UO", "DES_UO", "CDR", "DS_CDR", "CD_LINEA_ATTIVITA", "CD_ELEMENTO_VOCE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "ESERCIZIO_PDG_VARIAZIONE", "PG_VARIAZIONE_PDG", "INI", "VAR_PIU", "VAR_MENO") AS 
  Select
--
-- Date: 09/11/2006
-- Version: 1.1
--
-- Vista CONSULTAZIONE Assestato Piano di Gestione Spese
--
-- History:
--
-- Date: 01/01/2006
-- Version: 1.0
-- Creazione
--
-- Date: 09/11/2006
-- Version: 1.1
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
PDG_MODULO_SPESE_GEST.esercizio, -- DIPARTIMENTI INIZIALE
        nvl(peso,1000) PESO_DIP,
        Nvl(progetto.cd_dipartimento, Null) DIP,
        nvl(p.DS_DIPARTIMENTO,DIPARTIMENTO.DS_DIPARTIMENTO) DS_DIPARTIMENTO,
        CDS.CD_UNITA_ORGANIZZATIVA CDS,
        CDS.DS_UNITA_ORGANIZZATIVA DES_CDS,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA UO,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA DES_UO,
        PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO CDR,
        CDR.DS_CDR,
        PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA,
        PDG_MODULO_SPESE_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_MODULO_SPESE_GEST.ESERCIZIO_PDG_VARIAZIONE,
        PDG_MODULO_SPESE_GEST.PG_VARIAZIONE_PDG,
        Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(V_CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE, PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO), PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(V_CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE, PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO), PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)
            ) INI,
        0 VAR_PIU,
        0 VAR_MENO
From    PDG_MODULO_SPESE_GEST,
        V_CLASSIFICAZIONE_VOCI,
	linea_attivita,
	progetto_gest progetto,
	progetto_gest com,
	progetto_gest modu,
	DIPARTIMENTO,
	UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA CDS,
        CDR,
        dipartimento_peso p
Where
 PROGETTO.esercizio= p.esercizio(+) AND
 PROGETTO.cd_dipartimento= p.cd_dipartimento (+) and
 PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO	= linea_attivita.CD_CENTRO_RESPONSABILITA
and	PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA	        = linea_attivita.CD_LINEA_ATTIVITA
And     PDG_MODULO_SPESE_GEST.categoria_dettaglio       = 'DIR'
And     PDG_MODULO_SPESE_GEST.id_classificazione        = V_CLASSIFICAZIONE_VOCI.id_classificazione
And     linea_attivita.pg_progetto                      Is Not Null
and	linea_attivita.PG_PROGETTO			= modu.PG_PROGETTO
And     modu.ESERCIZIO                                  = PDG_MODULO_SPESE_GEST.esercizio
And     modu.ESERCIZIO_PROGETTO_PADRE                   = com.ESERCIZIO
And	modu.PG_PROGETTO_PADRE                          = com.PG_PROGETTO
And     com.ESERCIZIO_PROGETTO_PADRE                    = progetto.ESERCIZIO
And	com.PG_PROGETTO_PADRE                           = progetto.PG_PROGETTO
And     PROGETTO.CD_DIPARTIMENTO                        = DIPARTIMENTO.CD_DIPARTIMENTO
And 	PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO	= CDR.CD_CENTRO_RESPONSABILITA
And 	CDR.CD_UNITA_ORGANIZZATIVA			= UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And 	UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
Group BY PDG_MODULO_SPESE_GEST.esercizio,
        nvl(peso,1000),
        Nvl(progetto.cd_dipartimento, Null),
        nvl(p.DS_DIPARTIMENTO,DIPARTIMENTO.DS_DIPARTIMENTO),
        CDS.CD_UNITA_ORGANIZZATIVA,
        CDS.DS_UNITA_ORGANIZZATIVA ,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
        PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO,
        CDR.DS_CDR,
        PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA,
        PDG_MODULO_SPESE_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_MODULO_SPESE_GEST.ESERCIZIO_PDG_VARIAZIONE,
        PDG_MODULO_SPESE_GEST.PG_VARIAZIONE_PDG
Having  Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(V_CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE, PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO), PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(V_CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE, PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO), PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)) != 0
Union All -- DIPARTIMENTI VARIAZIONI PIU
Select  PDG_VARIAZIONE_RIGA_GEST.esercizio,
        nvl(peso,1000) PESO_DIP,
        Nvl(progetto.cd_dipartimento, Null) DIP,
        nvl(p.DS_DIPARTIMENTO,DIPARTIMENTO.DS_DIPARTIMENTO) DS_DIPARTIMENTO,
        CDS.CD_UNITA_ORGANIZZATIVA CDS,
        CDS.DS_UNITA_ORGANIZZATIVA DES_CDS,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA UO,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA DES_UO,
        PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO CDR,
        CDR.DS_CDR,
        PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
        PDG_VARIAZIONE_RIGA_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO,
        PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG,
        0 INI,
        Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)
            ) VAR_PIU,
        0 VAR_MENO
From    PDG_VARIAZIONE_RIGA_GEST,
	elemento_voce,
        V_CLASSIFICAZIONE_VOCI,
        V_CLASSIFICAZIONE_VOCI CLA_PADRE,
	linea_attivita,
	progetto_gest progetto,
	progetto_gest com,
	progetto_gest modu,
	DIPARTIMENTO,
	UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA CDS,
        CDR,
	PDG_VARIAZIONE,
        dipartimento_peso p
Where
 PROGETTO.esercizio= p.esercizio(+) AND
 PROGETTO.cd_dipartimento= p.cd_dipartimento (+) and
 V_CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE       = elemento_voce.ID_CLASSIFICAZIONE
and	elemento_voce.ESERCIZIO 			= PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO
and	elemento_voce.TI_APPARTENENZA 		  	= PDG_VARIAZIONE_RIGA_GEST.TI_APPARTENENZA
AND	elemento_voce.TI_GESTIONE			= PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE
and	elemento_voce.CD_ELEMENTO_VOCE		  	= PDG_VARIAZIONE_RIGA_GEST.CD_ELEMENTO_VOCE
and	PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO    = linea_attivita.CD_CENTRO_RESPONSABILITA
and	PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA	= linea_attivita.CD_LINEA_ATTIVITA
And     PDG_VARIAZIONE_RIGA_GEST.categoria_dettaglio    != 'SCR'
And     linea_attivita.pg_progetto                      Is Not Null
And     V_CLASSIFICAZIONE_VOCI.ID_CLASS_PADRE           = CLA_PADRE.ID_CLASSIFICAZIONE
--And     NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO) = PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO
And	linea_attivita.PG_PROGETTO			= modu.PG_PROGETTO
And     modu.ESERCIZIO                                  = PDG_VARIAZIONE_RIGA_GEST.esercizio
And     modu.ESERCIZIO_PROGETTO_PADRE                   = com.ESERCIZIO
And	modu.PG_PROGETTO_PADRE                          = com.PG_PROGETTO
And     com.ESERCIZIO_PROGETTO_PADRE                    = progetto.ESERCIZIO
And	com.PG_PROGETTO_PADRE                           = progetto.PG_PROGETTO
And     PROGETTO.CD_DIPARTIMENTO                        = DIPARTIMENTO.CD_DIPARTIMENTO
And 	PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO	= CDR.CD_CENTRO_RESPONSABILITA
And 	CDR.CD_UNITA_ORGANIZZATIVA			= UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And 	UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
And     PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO              = PDG_VARIAZIONE.ESERCIZIO
And     PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG      = PDG_VARIAZIONE.PG_VARIAZIONE_PDG
And     PDG_VARIAZIONE.STATO = 'APP'
And     Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
        Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
        Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0) > 0
Group BY PDG_VARIAZIONE_RIGA_GEST.esercizio,
         nvl(peso,1000),
        Nvl(progetto.cd_dipartimento, Null) ,
        nvl(p.DS_DIPARTIMENTO,DIPARTIMENTO.DS_DIPARTIMENTO) ,
        CDS.CD_UNITA_ORGANIZZATIVA,
        CDS.DS_UNITA_ORGANIZZATIVA ,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
        PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO,
        CDR.DS_CDR,
        PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
        PDG_VARIAZIONE_RIGA_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO,
        PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG
Having  Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)) != 0
Union All  -- DIPARTIMENTI VARIAZIONI MENO
Select  PDG_VARIAZIONE_RIGA_GEST.esercizio,
         nvl(peso,1000) PESO_DIP,
        Nvl(progetto.cd_dipartimento, Null) DIP,
        nvl(p.DS_DIPARTIMENTO,DIPARTIMENTO.DS_DIPARTIMENTO) DS_DIPARTIMENTO,
        CDS.CD_UNITA_ORGANIZZATIVA CDS,
        CDS.DS_UNITA_ORGANIZZATIVA DES_CDS,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA UO,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA DES_UO,
        PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO,
        CDR.DS_CDR,
        PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
        PDG_VARIAZIONE_RIGA_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO,
        PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG,
        0 INI,
        0 VAR_PIU,
        Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)
            ) VAR_MENO
From    PDG_VARIAZIONE_RIGA_GEST,
	elemento_voce,
        V_CLASSIFICAZIONE_VOCI,
        V_CLASSIFICAZIONE_VOCI CLA_PADRE,
	linea_attivita,
	progetto_gest progetto,
	progetto_gest com,
	progetto_gest modu,
	DIPARTIMENTO,
	PDG_VARIAZIONE,
        UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA CDS,
        CDR,
        dipartimento_peso p
Where
 PROGETTO.esercizio= p.esercizio(+) AND
 PROGETTO.cd_dipartimento= p.cd_dipartimento (+) and
  V_CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE	= elemento_voce.ID_CLASSIFICAZIONE
and	elemento_voce.ESERCIZIO 			= PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO
and	elemento_voce.TI_APPARTENENZA 		  	= PDG_VARIAZIONE_RIGA_GEST.TI_APPARTENENZA
AND	elemento_voce.TI_GESTIONE			= PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE
and	elemento_voce.CD_ELEMENTO_VOCE		  	= PDG_VARIAZIONE_RIGA_GEST.CD_ELEMENTO_VOCE
and	PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO	= linea_attivita.CD_CENTRO_RESPONSABILITA
and	PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA	= linea_attivita.CD_LINEA_ATTIVITA
And     PDG_VARIAZIONE_RIGA_GEST.categoria_dettaglio    != 'SCR'
And     linea_attivita.pg_progetto                      Is Not Null
And     V_CLASSIFICAZIONE_VOCI.ID_CLASS_PADRE           = CLA_PADRE.ID_CLASSIFICAZIONE
--And     NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO) = PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO
and	linea_attivita.PG_PROGETTO			= modu.PG_PROGETTO
And     modu.ESERCIZIO                                  = PDG_VARIAZIONE_RIGA_GEST.esercizio
And     modu.ESERCIZIO_PROGETTO_PADRE                   = com.ESERCIZIO
And	modu.PG_PROGETTO_PADRE                          = com.PG_PROGETTO
And     com.ESERCIZIO_PROGETTO_PADRE                    = progetto.ESERCIZIO
And	com.PG_PROGETTO_PADRE                           = progetto.PG_PROGETTO
And     PROGETTO.CD_DIPARTIMENTO                        = DIPARTIMENTO.CD_DIPARTIMENTO
And 	PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO	= CDR.CD_CENTRO_RESPONSABILITA
And 	CDR.CD_UNITA_ORGANIZZATIVA			= UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And 	UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
And     PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO              = PDG_VARIAZIONE.ESERCIZIO
And     PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG      = PDG_VARIAZIONE.PG_VARIAZIONE_PDG
And     PDG_VARIAZIONE.STATO = 'APP'
And     Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
        Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
        Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0) < 0
Group BY PDG_VARIAZIONE_RIGA_GEST.esercizio,
         nvl(peso,1000),
        Nvl(progetto.cd_dipartimento, Null) ,
        nvl(p.DS_DIPARTIMENTO,DIPARTIMENTO.DS_DIPARTIMENTO) ,
        CDS.CD_UNITA_ORGANIZZATIVA,
        CDS.DS_UNITA_ORGANIZZATIVA ,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
        PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO,
        CDR.DS_CDR,
        PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
        PDG_VARIAZIONE_RIGA_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO,
        PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG
Having  Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)) !=0
Union All -- SAC INIZIALE
Select  PDG_MODULO_SPESE_GEST.esercizio,
        nvl( peso,1000),
        'SAC',
        'dipartimento SAC',
        CDS.CD_UNITA_ORGANIZZATIVA CDS,
        CDS.DS_UNITA_ORGANIZZATIVA DES_CDS,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA UO,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA DES_UO,
        PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO CDR,
        CDR.DS_CDR,
        PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA,
        PDG_MODULO_SPESE_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_MODULO_SPESE_GEST.ESERCIZIO_PDG_VARIAZIONE,
        PDG_MODULO_SPESE_GEST.PG_VARIAZIONE_PDG,
        Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(V_CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE, PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO), PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(V_CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE, PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO), PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)
            ) INI,
        0 VAR_PIU,
        0 VAR_MENO
From    PDG_MODULO_SPESE_GEST,
        V_CLASSIFICAZIONE_VOCI,
        cdr,
	unita_organizzativa,
        UNITA_ORGANIZZATIVA CDS,
dipartimento_peso p
Where
PDG_MODULO_SPESE_GEST.esercizio= p.esercizio(+) AND
'SAC'= p.cd_dipartimento (+) and
 PDG_MODULO_SPESE_GEST.categoria_dettaglio       != 'SCR'
And     PDG_MODULO_SPESE_GEST.id_classificazione        = V_CLASSIFICAZIONE_VOCI.id_classificazione
And     PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO       = CDR.CD_CENTRO_RESPONSABILITA
And     CDR.CD_UNITA_ORGANIZZATIVA                      = unita_organizzativa.CD_UNITA_ORGANIZZATIVA
And 	PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO	= CDR.CD_CENTRO_RESPONSABILITA
And 	CDR.CD_UNITA_ORGANIZZATIVA			= UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And 	UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
And     unita_organizzativa.CD_TIPO_UNITA = 'SAC'
Group BY PDG_MODULO_SPESE_GEST.esercizio,
        nvl( peso,1000),
        'SAC',
        'dipartimento SAC',
        CDS.CD_UNITA_ORGANIZZATIVA,
        CDS.DS_UNITA_ORGANIZZATIVA ,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
        PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO,
        CDR.DS_CDR,
        PDG_MODULO_SPESE_GEST.CD_LINEA_ATTIVITA,
        PDG_MODULO_SPESE_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_MODULO_SPESE_GEST.ESERCIZIO_PDG_VARIAZIONE,
        PDG_MODULO_SPESE_GEST.PG_VARIAZIONE_PDG
Having  Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(V_CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE, PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO), PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(V_CLASSIFICAZIONE_VOCI.CDR_ACCENTRATORE, PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO), PDG_MODULO_SPESE_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)) != 0
Union All -- SAC VARIAZIONI PIU'
Select  PDG_VARIAZIONE_RIGA_GEST.esercizio,
        nvl( peso,1000),
        'SAC',
        'dipartimento SAC',
        CDS.CD_UNITA_ORGANIZZATIVA CDS,
        CDS.DS_UNITA_ORGANIZZATIVA DES_CDS,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA UO,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA DES_UO,
        PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO CDR,
        CDR.DS_CDR,
        PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
        PDG_VARIAZIONE_RIGA_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO,
        PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG,
        0 INI,
        Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)
            ) VAR_PIU,
        0 VAR_MENO
From    PDG_VARIAZIONE_RIGA_GEST,
	elemento_voce,
        V_CLASSIFICAZIONE_VOCI,
        V_CLASSIFICAZIONE_VOCI CLA_PADRE,
        cdr,
	unita_organizzativa,
        PDG_VARIAZIONE,
        UNITA_ORGANIZZATIVA CDS,
dipartimento_peso p
Where
PDG_VARIAZIONE_RIGA_GEST.esercizio= p.esercizio(+) AND
'SAC'= p.cd_dipartimento (+) and
 V_CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE		= elemento_voce.ID_CLASSIFICAZIONE
and	elemento_voce.ESERCIZIO 			= PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO
and	elemento_voce.TI_APPARTENENZA 		  	= PDG_VARIAZIONE_RIGA_GEST.TI_APPARTENENZA
AND	elemento_voce.TI_GESTIONE			= PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE
and	elemento_voce.CD_ELEMENTO_VOCE		  	= PDG_VARIAZIONE_RIGA_GEST.CD_ELEMENTO_VOCE
And     PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO = CDR.CD_CENTRO_RESPONSABILITA
And     CDR.CD_UNITA_ORGANIZZATIVA = unita_organizzativa.CD_UNITA_ORGANIZZATIVA
And     V_CLASSIFICAZIONE_VOCI.ID_CLASS_PADRE           = CLA_PADRE.ID_CLASSIFICAZIONE
--And     NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO) = PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO
And     PDG_VARIAZIONE_RIGA_GEST.categoria_dettaglio    != 'SCR'
And     unita_organizzativa.CD_TIPO_UNITA               = 'SAC'
And     PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO              = PDG_VARIAZIONE.ESERCIZIO
And     PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG      = PDG_VARIAZIONE.PG_VARIAZIONE_PDG
And     PDG_VARIAZIONE.STATO                            = 'APP'
And 	PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO	= CDR.CD_CENTRO_RESPONSABILITA
And 	CDR.CD_UNITA_ORGANIZZATIVA			= UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And 	UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
And     Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
        Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
        Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0) > 0
Group BY PDG_VARIAZIONE_RIGA_GEST.esercizio,
        nvl( peso,1000),
        'SAC',
        'dipartimento SAC',
        CDS.CD_UNITA_ORGANIZZATIVA,
        CDS.DS_UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
        PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO,
        CDR.DS_CDR,
        PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
        PDG_VARIAZIONE_RIGA_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO,
        PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG
Having  Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)) != 0
Union All -- SAC VARIAZIONI MENO
Select  PDG_VARIAZIONE_RIGA_GEST.esercizio,
        nvl( peso,1000),
        'SAC',
        'dipartimento SAC',
        CDS.CD_UNITA_ORGANIZZATIVA CDS,
        CDS.DS_UNITA_ORGANIZZATIVA DES_CDS,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA UO,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA DES_UO,
        PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO CDR,
        CDR.DS_CDR,
        PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
        PDG_VARIAZIONE_RIGA_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO,
        PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG,
        0 INI,
        0 VAR_PIU,
        Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)) VAR_MENO
From    PDG_VARIAZIONE_RIGA_GEST,
	elemento_voce,
        V_CLASSIFICAZIONE_VOCI,
        V_CLASSIFICAZIONE_VOCI CLA_PADRE,
        cdr,
	unita_organizzativa,
        PDG_VARIAZIONE,
        UNITA_ORGANIZZATIVA CDS,
dipartimento_peso p
Where
PDG_VARIAZIONE_RIGA_GEST.esercizio= p.esercizio(+) AND
'SAC'= p.cd_dipartimento (+) and
  V_CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE	= elemento_voce.ID_CLASSIFICAZIONE
and	elemento_voce.ESERCIZIO 			= PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO
and	elemento_voce.TI_APPARTENENZA 		  	= PDG_VARIAZIONE_RIGA_GEST.TI_APPARTENENZA
AND	elemento_voce.TI_GESTIONE			= PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE
and	elemento_voce.CD_ELEMENTO_VOCE		  	= PDG_VARIAZIONE_RIGA_GEST.CD_ELEMENTO_VOCE
And     PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO = CDR.CD_CENTRO_RESPONSABILITA
And     CDR.CD_UNITA_ORGANIZZATIVA = unita_organizzativa.CD_UNITA_ORGANIZZATIVA
And     V_CLASSIFICAZIONE_VOCI.ID_CLASS_PADRE           = CLA_PADRE.ID_CLASSIFICAZIONE
--And     NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO) = PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO
And     unita_organizzativa.CD_TIPO_UNITA               = 'SAC'
And     PDG_VARIAZIONE_RIGA_GEST.categoria_dettaglio    != 'SCR'
And     PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO              = PDG_VARIAZIONE.ESERCIZIO
And     PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG      = PDG_VARIAZIONE.PG_VARIAZIONE_PDG
And     PDG_VARIAZIONE.STATO                            = 'APP'
And 	PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO	= CDR.CD_CENTRO_RESPONSABILITA
And 	CDR.CD_UNITA_ORGANIZZATIVA			= UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And 	UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
And     Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
        Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
        Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0) < 0
Group BY PDG_VARIAZIONE_RIGA_GEST.esercizio,
        nvl( peso,1000),
        'SAC',
        'dipartimento SAC',
        CDS.CD_UNITA_ORGANIZZATIVA,
        CDS.DS_UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
        UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
        PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO,
        CDR.DS_CDR,
        PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
        PDG_VARIAZIONE_RIGA_GEST.cd_elemento_voce,
        V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
        V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
        V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
        PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO,
        PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG
Having  Sum(Nvl(IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(IM_SPESE_GEST_DECENTRATA_EST, 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0), 0) +
            Decode(NVL(CLA_PADRE.CDR_ACCENTRATORE, PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO), PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO, Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0), 0)) != 0;
