--------------------------------------------------------
--  DDL for View V_CONS_SCAD_OBBL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_SCAD_OBBL" ("CDS", "UO", "ESERCIZIO", "ESERCIZIO_ORIGINALE", "PG_OBBL", "PG_OBBL_SCAD", "VOCE_BILANCIO", "DATA_SCAD", "DS_OBBL", "DS_SCAD", "IM_SCAD", "IM_ASS_DOC_AMM", "IMP_ASS_DOC_CONT", "CREDITORE") AS 
  SELECT DISTINCT
--
-- Date: 07/03/2007
-- Version: 1.0
--
-- Vista per la consultazione Scadenzario Impegni
--
--
-- Body
--
OBBLIGAZIONE_SCADENZARIO.CD_CDS,
OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA,
OBBLIGAZIONE_SCADENZARIO.ESERCIZIO,
OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE,
OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE,
OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO,
OBBLIGAZIONE.CD_ELEMENTO_VOCE,
OBBLIGAZIONE_SCADENZARIO.DT_SCADENZA,
obbligazione.DS_OBBLIGAZIONE,
OBBLIGAZIONE_SCADENZARIO.DS_SCADENZA,
OBBLIGAZIONE_SCADENZARIO.IM_SCADENZA,
OBBLIGAZIONE_SCADENZARIO.IM_ASSOCIATO_DOC_AMM,
OBBLIGAZIONE_SCADENZARIO.IM_ASSOCIATO_DOC_CONTABILE,
TERZO.DENOMINAZIONE_SEDE
FROM OBBLIGAZIONE_SCADENZARIO, OBBLIGAZIONE, TERZO
WHERE OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE=OBBLIGAZIONE.ESERCIZIO_ORIGINALE AND
          OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE=OBBLIGAZIONE.PG_OBBLIGAZIONE AND
	  OBBLIGAZIONE_SCADENZARIO.CD_CDS=OBBLIGAZIONE.CD_CDS AND
	  OBBLIGAZIONE_SCADENZARIO.ESERCIZIO=OBBLIGAZIONE.ESERCIZIO AND
	  TERZO.CD_TERZO=OBBLIGAZIONE.CD_TERZO AND
	  (OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB' OR
	   OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_RES' OR OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_RESIM')
ORDER BY ESERCIZIO,OBBLIGAZIONE_SCADENZARIO.DT_SCADENZA, OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE,OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE,OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO;
