--------------------------------------------------------
--  DDL for View V_CONS_VAR_PDGG
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_VAR_PDGG" ("ESERCIZIO", "PG_VARIAZIONE_PDG", "DS_VARIAZIONE", "DT_APERTURA", "DT_CHIUSURA", "DT_APPROVAZIONE", "DT_ANNULLAMENTO", "DS_DELIBERA", "STATO", "DS_STATO", "RIFERIMENTI", "CD_CAUSALE_RESPINTA", "DS_CAUSALE_RESPINTA", "DT_APP_FORMALE", "TIPOLOGIA", "DS_TIPO_VARIAZIONE", "TIPOLOGIA_FIN", "DS_TIPOLOGIA_FIN", "PG_RIGA", "CD_CDR_ASSEGNATARIO", "DS_CDR_ASSEGNATARIO", "CD_LINEA_ATTIVITA", "DENOMINAZIONE", "ID_CLASSIFICAZIONE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "PG_MODULO", "CD_MODULO", "DS_MODULO", "CD_TIPO_MODULO", "DS_TIPO_MODULO", "PG_COMMESSA", "CD_COMMESSA", "DS_COMMESSA", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO", "CD_CDS_AREA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "DT_REGISTRAZIONE", "DESCRIZIONE", "IM_SPESE_GEST_DECENTRATA_INT", "IM_SPESE_GEST_DECENTRATA_EST", "IM_SPESE_GEST_ACCENTRATA_INT", "IM_SPESE_GEST_ACCENTRATA_EST", "IM_ENTRATA", "ABS_TOT_VARIAZIONE") AS 
  Select
--
-- Date: 09/11/2006
-- Version: 1.1
--
-- Vista CONSULTAZIONE Variazione Piano di Gestione Gestionale
--
-- History:
--
-- Date: 01/01/2006
-- Version: 1.0
-- Creazione
--
-- Date: 09/11/2006
-- Version: 1.1
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
/*+ FIRST_ROWS(10) INDEX(PDG_VARIAZIONE_RIGA_GEST PDG_VARIAZIONE_RIGA_GEST_APPO) INDEX(ELEMENTO_VOCE PX_ELEMENTO_VOCE) INDEX(CLASSIFICAZIONE_VOCI PX_CLASSIFICAZIONE_VOCI)*/
PDG_VARIAZIONE.ESERCIZIO,
PDG_VARIAZIONE.PG_VARIAZIONE_PDG,
PDG_VARIAZIONE.DS_VARIAZIONE,
PDG_VARIAZIONE.DT_APERTURA,
PDG_VARIAZIONE.DT_CHIUSURA,
PDG_VARIAZIONE.DT_APPROVAZIONE,
PDG_VARIAZIONE.DT_ANNULLAMENTO,
PDG_VARIAZIONE.DS_DELIBERA,
PDG_VARIAZIONE.STATO,
Decode (PDG_VARIAZIONE.STATO, 'PRP', 'Proposta Provvisoria', 'PRD', 'Proposta Definitiva', 'APP', 'Approvata', 'APF', 'Approvazione formale', 'ANN', 'Annullata', Null),
PDG_VARIAZIONE.RIFERIMENTI,
PDG_VARIAZIONE.CD_CAUSALE_RESPINTA,
PDG_VARIAZIONE.DS_CAUSALE_RESPINTA,
PDG_VARIAZIONE.DT_APP_FORMALE,
PDG_VARIAZIONE.TIPOLOGIA,
(Select DS_TIPO_VARIAZIONE From TIPO_VARIAZIONE
 Where TIPO_VARIAZIONE.ESERCIZIO = PDG_VARIAZIONE.ESERCIZIO
   And TIPO_VARIAZIONE.CD_TIPO_VARIAZIONE = PDG_VARIAZIONE.TIPOLOGIA) DS_TIPO_VARIAZIONE,
PDG_VARIAZIONE.TIPOLOGIA_FIN,
Decode (PDG_VARIAZIONE.TIPOLOGIA_FIN, 'FES', 'Fonti Esterne', 'FIN', 'Fonti Interne'),
PDG_VARIAZIONE_RIGA_GEST.PG_RIGA,
PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO,
(Select DS_CDR From CDR Where PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO = CDR.CD_CENTRO_RESPONSABILITA) DS_CDR_ASSEGNATARIO,
PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA,
LINEA_ATTIVITA.DENOMINAZIONE,
V_CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE,
V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
MODU.PG_PROGETTO,
MODU.CD_PROGETTO,
modu.DS_PROGETTO,
MODU.CD_TIPO_PROGETTO,
(Select DS_TIPO_PROGETTO From TIPO_PROGETTO Where MODU.CD_TIPO_PROGETTO = TIPO_PROGETTO.CD_TIPO_PROGETTO) DS_TIPO_MODULO,
COM.PG_PROGETTO,
COM.CD_PROGETTO,
COM.DS_PROGETTO,
PROGETTO.PG_PROGETTO,
PROGETTO.CD_PROGETTO,
PROGETTO.DS_PROGETTO,
NVL(PROGETTO.CD_DIPARTIMENTO, NULL) CD_DIPARTIMENTO,
--(Select DS_DIPARTIMENTO From DIPARTIMENTO Where CD_DIPARTIMENTO = PROGETTO.CD_DIPARTIMENTO) DS_DIPARTIMENTO,
cnrctb020.GETDESDIPARTIMENTO (PROGETTO.CD_DIPARTIMENTO) DS_DIPARTIMENTO,
PDG_VARIAZIONE_RIGA_GEST.CD_CDS_AREA,
PDG_VARIAZIONE_RIGA_GEST.TI_APPARTENENZA,
PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE,
PDG_VARIAZIONE_RIGA_GEST.CD_ELEMENTO_VOCE,
DS_ELEMENTO_VOCE,
PDG_VARIAZIONE_RIGA_GEST.DT_REGISTRAZIONE,
PDG_VARIAZIONE_RIGA_GEST.DESCRIZIONE,
PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_DECENTRATA_INT,
PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_DECENTRATA_EST,
PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_ACCENTRATA_INT,
PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_ACCENTRATA_EST,
PDG_VARIAZIONE_RIGA_GEST.IM_ENTRATA,
-- FORNISCE IL VALORE ASSOLUTO DELLA VARIAZIONE, SERVE COME FILTRO PER VEDERE GLI SPOSTAMENTI (ANCHE STORNI) OLTRE UN CERTO IMPORTO
                                     (Select SUM(ABS(NVL(V2.IM_SPESE_GEST_DECENTRATA_INT, 0) +
                                                     NVL(V2.IM_SPESE_GEST_DECENTRATA_EST, 0) +
                                                     NVL(V2.IM_SPESE_GEST_ACCENTRATA_INT, 0) +
                                                     NVL(V2.IM_SPESE_GEST_ACCENTRATA_EST, 0) +
                                                     NVL(V2.IM_ENTRATA, 0)))
                                      FROM  PDG_VARIAZIONE_RIGA_GEST V2
                                      WHERE V2.ESERCIZIO = PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO AND
                                            V2.PG_VARIAZIONE_PDG = PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG AND
                                            V2.TI_GESTIONE = PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE AND
                                            V2.categoria_dettaglio    != 'SCR' AND
(((NVL(PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_DECENTRATA_INT, 0) + NVL(PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_DECENTRATA_EST, 0) +
   NVL(PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_ACCENTRATA_INT, 0) + NVL(PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_ACCENTRATA_EST, 0) +
   NVL(PDG_VARIAZIONE_RIGA_GEST.IM_ENTRATA, 0)) > 0 AND
  (NVL(V2.IM_SPESE_GEST_DECENTRATA_INT, 0) + NVL(V2.IM_SPESE_GEST_DECENTRATA_EST, 0) + NVL(V2.IM_SPESE_GEST_ACCENTRATA_INT, 0) +
   NVL(V2.IM_SPESE_GEST_ACCENTRATA_EST, 0) + NVL(V2.IM_ENTRATA, 0)) > 0) OR
 ((NVL(PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_DECENTRATA_INT, 0) + NVL(PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_DECENTRATA_EST, 0) +
   NVL(PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_ACCENTRATA_INT, 0) + NVL(PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_ACCENTRATA_EST, 0) +
   NVL(PDG_VARIAZIONE_RIGA_GEST.IM_ENTRATA, 0)) < 0 AND
  (NVL(V2.IM_SPESE_GEST_DECENTRATA_INT, 0) + NVL(V2.IM_SPESE_GEST_DECENTRATA_EST, 0) + NVL(V2.IM_SPESE_GEST_ACCENTRATA_INT, 0) +
   NVL(V2.IM_SPESE_GEST_ACCENTRATA_EST, 0) + NVL(V2.IM_ENTRATA, 0)) < 0)))
FROM    PDG_VARIAZIONE,
        PDG_VARIAZIONE_RIGA_GEST,
	ELEMENTO_VOCE,
        V_CLASSIFICAZIONE_VOCI,
	LINEA_ATTIVITA,
	PROGETTO_GEST PROGETTO,
	PROGETTO_GEST COM,
	PROGETTO_GEST MODU
WHERE   PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO              = PDG_VARIAZIONE.ESERCIZIO
AND     PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG      = PDG_VARIAZIONE.PG_VARIAZIONE_PDG
And     PDG_VARIAZIONE_RIGA_GEST.CATEGORIA_DETTAGLIO    != 'SCR'
AND	PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO              = ELEMENTO_VOCE.ESERCIZIO
AND	PDG_VARIAZIONE_RIGA_GEST.TI_APPARTENENZA        = ELEMENTO_VOCE.TI_APPARTENENZA
AND	PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE            = ELEMENTO_VOCE.TI_GESTIONE
AND	PDG_VARIAZIONE_RIGA_GEST.CD_ELEMENTO_VOCE       = ELEMENTO_VOCE.CD_ELEMENTO_VOCE
And     ELEMENTO_VOCE.ID_CLASSIFICAZIONE                = V_CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE
AND	LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA         = PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO
AND	LINEA_ATTIVITA.CD_LINEA_ATTIVITA                = PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA
And     LINEA_ATTIVITA.PG_PROGETTO                      IS NOT Null
AND	LINEA_ATTIVITA.PG_PROGETTO			= MODU.PG_PROGETTO
And     MODU.ESERCIZIO                                  = PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO
AND	MODU.ESERCIZIO_PROGETTO_PADRE		        = COM.ESERCIZIO
AND	MODU.PG_PROGETTO_PADRE				= COM.PG_PROGETTO
AND	COM.ESERCIZIO_PROGETTO_PADRE		        = PROGETTO.ESERCIZIO
AND	COM.PG_PROGETTO_PADRE                           = PROGETTO.PG_PROGETTO
;
