--------------------------------------------------------
--  DDL for View V_COAN_SCADENZE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_COAN_SCADENZE" ("CD_TIPO_DOCUMENTO_AMM", "CD_TERZO", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_NUMERO_DOCUMENTO", "TI_FATTURA", "CD_CDS_OBB_ACC", "ESERCIZIO_OBB_ACC", "ESERCIZIO_ORI_OBB_ACC", "PG_OBB_ACC", "PG_OBB_ACC_SCADENZARIO", "IM_DIPONIBILE_NC", "IM_IMPONIBILE", "IM_IVA", "IM_IVA_DETRAIBILE", "IM_TOTALE", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "IM_SCADENZA", "FL_OBBIGAZIONE") AS 
  SELECT
--
-- Date: 18/07/2006
-- Version: 1.5
--
-- Vista di estrazione del dettaglio delle scadenze di OBB_ACC relative ai documenti gestiti nella movimentazione coan
--
-- History:
--
-- Date: 03/04/2002
-- Version: 1.0
-- Creazione
--
-- Date: 10/06/2002
-- Version: 1.1
-- Introduzione degli accertamenti
--
-- Date: 12/06/2002
-- Version: 1.2
-- Fix per la corretta gestione dell'associazione tra documento e tipo di conto associato
--
-- Date: 13/06/2003
-- Version: 1.3
-- Ottimizzazione
--
-- Date: 17/02/2004
-- Version: 1.4
-- Fix errore di calcolo del costo in fattura commerciale come imponibile + iva - iva detraibile
--
-- Date: 18/07/2006
-- Version: 1.5
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body:
--
        V.CD_TIPO_DOCUMENTO_AMM
	   ,V.CD_TERZO
       ,V.CD_CDS
	   ,V.CD_UNITA_ORGANIZZATIVA
	   ,V.ESERCIZIO
	   ,V.PG_NUMERO_DOCUMENTO
	   ,V.TI_FATTURA
	   ,V.CD_CDS_OBB_ACC
	   ,V.ESERCIZIO_OBB_ACC
	   ,V.ESERCIZIO_ORI_OBB_ACC
	   ,V.PG_OBB_ACC
	   ,V.PG_OBB_ACC_SCADENZARIO
	   ,SUM(NVL(V.IM_DIPONIBILE_NC,0)) IM_DIPONIBILE_NC
	   ,SUM(NVL(V.IM_IMPONIBILE,0))    IM_IMPONIBILE
	   ,SUM(NVL(V.IM_IVA,0))    IM_IVA
	   ,SUM(NVL(V.IM_IVA_DETRAIBILE,0))  IM_IVA_DETRAIBILE
	   ,SUM(DECODE(V.TI_ISTITUZ_COMMERC,'C',V.IM_IMPONIBILE + V.IM_IVA - V.IM_IVA_DETRAIBILE,V.IM_IMPONIBILE + V.IM_IVA )) IM_TOTALE
	   ,OBBL.TI_APPARTENENZA
	   ,OBBL.TI_GESTIONE
	   ,OBBL.CD_ELEMENTO_VOCE
	   ,O_SCAD.IM_SCADENZA
	   ,V.FL_OBBIGAZIONE
FROM V_COAN_DOCUMENTI_DETT V
     ,OBBLIGAZIONE OBBL
	 ,OBBLIGAZIONE_SCADENZARIO O_SCAD
WHERE V.CD_CDS_OBB_ACC    = OBBL.CD_CDS (+)
  AND V.ESERCIZIO_OBB_ACC = OBBL.ESERCIZIO (+)
  AND V.ESERCIZIO_ORI_OBB_ACC = OBBL.ESERCIZIO_ORIGINALE (+)
  AND V.PG_OBB_ACC        = OBBL.PG_OBBLIGAZIONE (+)
  AND V.CD_CDS_OBB_ACC    = O_SCAD.CD_CDS (+)
  AND V.ESERCIZIO_OBB_ACC = O_SCAD.ESERCIZIO (+)
  AND V.ESERCIZIO_ORI_OBB_ACC = O_SCAD.ESERCIZIO_ORIGINALE (+)
  AND V.PG_OBB_ACC        = O_SCAD.PG_OBBLIGAZIONE (+)
  AND V.PG_OBB_ACC_SCADENZARIO = O_SCAD.PG_OBBLIGAZIONE_SCADENZARIO (+)
  and V.FL_OBBIGAZIONE = 'Y'
GROUP BY V.CD_TIPO_DOCUMENTO_AMM
	    ,V.CD_TERZO
        ,V.CD_CDS
	    ,V.CD_UNITA_ORGANIZZATIVA
	    ,V.ESERCIZIO
	    ,V.PG_NUMERO_DOCUMENTO
        ,V.TI_FATTURA
	    ,V.CD_CDS_OBB_ACC
	    ,V.ESERCIZIO_OBB_ACC
	    ,V.ESERCIZIO_ORI_OBB_ACC
	    ,V.PG_OBB_ACC
	    ,V.PG_OBB_ACC_SCADENZARIO
	    ,OBBL.TI_APPARTENENZA
	    ,OBBL.TI_GESTIONE
	    ,OBBL.CD_ELEMENTO_VOCE
	    ,O_SCAD.IM_SCADENZA
	    ,V.FL_OBBIGAZIONE
union all
SELECT
        V.CD_TIPO_DOCUMENTO_AMM
	   ,V.CD_TERZO
       ,V.CD_CDS
	   ,V.CD_UNITA_ORGANIZZATIVA
	   ,V.ESERCIZIO
	   ,V.PG_NUMERO_DOCUMENTO
	   ,V.TI_FATTURA
	   ,V.CD_CDS_OBB_ACC
	   ,V.ESERCIZIO_OBB_ACC
	   ,V.ESERCIZIO_ORI_OBB_ACC
	   ,V.PG_OBB_ACC
	   ,V.PG_OBB_ACC_SCADENZARIO
	   ,SUM(NVL(V.IM_DIPONIBILE_NC,0)) IM_DIPONIBILE_NC
	   ,SUM(NVL(V.IM_IMPONIBILE,0))    IM_IMPONIBILE
	   ,SUM(NVL(V.IM_IVA,0))    IM_IVA
	   ,SUM(NVL(V.IM_IVA_DETRAIBILE,0))  IM_IVA_DETRAIBILE
	   ,SUM(DECODE(V.TI_ISTITUZ_COMMERC,'C',V.IM_IMPONIBILE + V.IM_IVA - V.IM_IVA_DETRAIBILE,V.IM_IMPONIBILE + V.IM_IVA )) IM_TOTALE
	   ,ACC.TI_APPARTENENZA
	   ,ACC.TI_GESTIONE
	   ,ACC.CD_ELEMENTO_VOCE
	   ,A_SCAD.IM_SCADENZA
       ,V.FL_OBBIGAZIONE
FROM V_COAN_DOCUMENTI_DETT V
	 , ACCERTAMENTO ACC
	 , ACCERTAMENTO_SCADENZARIO A_SCAD
WHERE V.CD_CDS_OBB_ACC    = ACC.CD_CDS (+)
  AND V.ESERCIZIO_OBB_ACC = ACC.ESERCIZIO (+)
  AND V.ESERCIZIO_ORI_OBB_ACC = ACC.ESERCIZIO_ORIGINALE (+)
  AND V.PG_OBB_ACC        = ACC.PG_ACCERTAMENTO (+)
  AND V.CD_CDS_OBB_ACC    = A_SCAD.CD_CDS (+)
  AND V.ESERCIZIO_OBB_ACC = A_SCAD.ESERCIZIO (+)
  AND V.ESERCIZIO_ORI_OBB_ACC = A_SCAD.ESERCIZIO_ORIGINALE (+)
  AND V.PG_OBB_ACC        = A_SCAD.PG_ACCERTAMENTO (+)
  AND V.PG_OBB_ACC_SCADENZARIO = A_SCAD.PG_ACCERTAMENTO_SCADENZARIO (+)
  and V.FL_OBBIGAZIONE = 'N'
GROUP BY V.CD_TIPO_DOCUMENTO_AMM
	    ,V.CD_TERZO
            ,V.CD_CDS
	    ,V.CD_UNITA_ORGANIZZATIVA
	    ,V.ESERCIZIO
	    ,V.PG_NUMERO_DOCUMENTO
            ,V.TI_FATTURA
	    ,V.CD_CDS_OBB_ACC
	    ,V.ESERCIZIO_OBB_ACC
	    ,V.ESERCIZIO_ORI_OBB_ACC
	    ,V.PG_OBB_ACC
	    ,V.PG_OBB_ACC_SCADENZARIO
	    ,ACC.TI_APPARTENENZA
	    ,ACC.TI_GESTIONE
	    ,ACC.CD_ELEMENTO_VOCE
	    ,A_SCAD.IM_SCADENZA
	    ,V.FL_OBBIGAZIONE;

   COMMENT ON TABLE "V_COAN_SCADENZE"  IS 'Vista di estrazione del dettaglio delle scadenze di OBB_ACC relative ai documenti gestiti nella movimentazione coan';
