--------------------------------------------------------
--  DDL for View V_CONTROLLI_PCC
--------------------------------------------------------
CREATE OR REPLACE FORCE VIEW "V_CONTROLLI_PCC" ("IDENTIFICATIVO_SDI", "NUMERO_DOCUMENTO", "DATA_DOCUMENTO", "CODICE_FISCALE", "CODICE_DESTINATARIO", "DATA_RICEZIONE", "DATA_SCADENZA", "STATO_DOCUMENTO", "IMPORTO_DOCUMENTO", "IMPONIBILE", "IMPOSTA", "TIPO_DOCUMENTO", "ESERCIZIO", "CD_UNITA_ORGANIZZATIVA", "PG_FATTURA_PASSIVA", "DT_REGISTRAZIONE", "STATO_LIQUIDAZIONE", "CAUSALE", "DT_INIZIO_SOSPENSIONE", "DT_EMISSIONE_MAN", "IM_MANDATO", "IM_TOTALE_NC", "CD_TIPO_CONTRATTO", "FL_IRREGISTRABILE", "CD_UO_CUU", "FL_DA_COMPENSO", "ESITO_PCC", "FL_SPLIT_PAYMENT", "DA_PAGARE") AS
  SELECT
    "IDENTIFICATIVO_SDI",
    "NUMERO_DOCUMENTO",
    "DATA_DOCUMENTO",
    "CODICE_FISCALE",
    "CODICE_DESTINATARIO",
    "DATA_RICEZIONE",
    "DATA_SCADENZA",
    "STATO_DOCUMENTO",
    DECODE(TIPO_DOCUMENTO, 'TD04', -ABS(IMPORTO_DOCUMENTO), IMPORTO_DOCUMENTO) "IMPORTO_DOCUMENTO",
    DECODE(TIPO_DOCUMENTO, 'TD04', -ABS(IMPONIBILE), IMPONIBILE) "IMPONIBILE",
    DECODE(TIPO_DOCUMENTO, 'TD04', -ABS(IMPOSTA), IMPOSTA) "IMPOSTA",
    "TIPO_DOCUMENTO",
    "ESERCIZIO",
    "CD_UNITA_ORGANIZZATIVA",
    "PG_FATTURA_PASSIVA",
    "DT_REGISTRAZIONE",
    "STATO_LIQUIDAZIONE",
    "CAUSALE",
    "DT_INIZIO_SOSPENSIONE",
    "DT_EMISSIONE_MAN",
    "IM_MANDATO",
    "IM_TOTALE_NC",
    "CD_TIPO_CONTRATTO",
    "FL_IRREGISTRABILE",
    "CD_UO_CUU",
    "FL_DA_COMPENSO",
    "ESITO_PCC",
    "FL_SPLIT_PAYMENT",
     "DA_PAGARE" FROM (
SELECT y.IDENTIFICATIVO_SDI, det.NUMERO_DOCUMENTO, det.DATA_DOCUMENTO, nvl(det2.PRESTATORE_CODICEFISCALE,PRESTATORE_CODICE) CODICE_FISCALE,
	   det2.CODICE_DESTINATARIO, det2.DATA_RICEZIONE, nvl(fp.DT_SCADENZA, det2.DATA_RICEZIONE+30) DATA_SCADENZA,
	   det.STATO_DOCUMENTO, det.IMPORTO_DOCUMENTO,
       y.IMPONIBILE, y.IMPOSTA,
       det.tipo_documento, fp.ESERCIZIO, fp.CD_UNITA_ORGANIZZATIVA, fp.PG_FATTURA_PASSIVA, fp.DT_REGISTRAZIONE, fp.stato_liquidazione,
       fp.CAUSALE, fp.DT_INIZIO_SOSPENSIONE,
       y.DT_EMISSIONE_MAN , y.IM_MANDATO, y.IM_TOTALE_NC, y.CD_TIPO_CONTRATTO,
       det.FL_IRREGISTRABILE,
       (SELECT t.CD_UNITA_ORGANIZZATIVA
        FROM TERZO t
        WHERE t.CODICE_UNIVOCO_UFFICIO_IPA = det2.CODICE_DESTINATARIO
        AND DUVA = (SELECT MAX(DUVA) FROM TERZO t2 WHERE t2.CODICE_UNIVOCO_UFFICIO_IPA = det2.CODICE_DESTINATARIO)) CD_UO_CUU,
        DECODE(fp.ESERCIZIO_COMPENSO, null, 'N', 'Y') FL_DA_COMPENSO, det.ESITO_PCC, NVL(NVL(fp.FL_SPLIT_PAYMENT, y.FL_SPLIT_PAYMENT), 'N') FL_SPLIT_PAYMENT,
        DECODE(NVL(NVL(fp.FL_SPLIT_PAYMENT, y.FL_SPLIT_PAYMENT), 'N'), 'Y', nvl(y.IMPONIBILE,0) - nvl(y.IM_MANDATO,0), nvl(y.IMPONIBILE,0) + nvl(y.IMPOSTA,0) - nvl(y.IM_MANDATO,0)) DA_PAGARE
FROM (SELECT x.ID_PAESE, x.ID_CODICE, x.IDENTIFICATIVO_SDI, x.PROGRESSIVO,
             sum(x.IMPONIBILE_IMPORTO) IMPONIBILE,
	         sum(x.IMPOSTA) IMPOSTA,
	         min(x.DT_EMISSIONE_MAN) DT_EMISSIONE_MAN,
	         SUM(x.IM_MANDATO) IM_MANDATO,
	         SUM(x.IM_TOTALE_NC) IM_TOTALE_NC,
	         min(x.CD_TIPO_CONTRATTO) CD_TIPO_CONTRATTO,
	         min(x.ESIGIBILITA_IVA) FL_SPLIT_PAYMENT
	  FROM (SELECT dei.ID_PAESE, dei.ID_CODICE, dei.IDENTIFICATIVO_SDI, dei.PROGRESSIVO, dei.IMPONIBILE_IMPORTO, dei.IMPOSTA,
				   NULL DT_EMISSIONE_MAN, NULL IM_MANDATO, NULL IM_TOTALE_NC, NULL CD_TIPO_CONTRATTO, DECODE(ESIGIBILITA_IVA, 'S', 'Y', 'D', 'Y','N') ESIGIBILITA_IVA
			FROM DOCUMENTO_ELE_IVA dei
			UNION ALL
			SELECT fp.ID_PAESE, fp.ID_CODICE, fp.IDENTIFICATIVO_SDI, fp.PROGRESSIVO, NULL, NULL,
				   null, null, null, c.CD_TIPO_CONTRATTO, NULL
			FROM FATTURA_PASSIVA_RIGA fpr
			LEFT JOIN FATTURA_PASSIVA fp ON fp.CD_CDS = fpr.CD_CDS AND fp.CD_UNITA_ORGANIZZATIVA = fpr.CD_UNITA_ORGANIZZATIVA AND fp.ESERCIZIO = fpr.ESERCIZIO AND fp.PG_FATTURA_PASSIVA = fpr.PG_FATTURA_PASSIVA
			LEFT JOIN OBBLIGAZIONE o ON o.CD_CDS = fpr.CD_CDS_OBBLIGAZIONE AND o.ESERCIZIO = fpr.ESERCIZIO_OBBLIGAZIONE AND o.ESERCIZIO_ORIGINALE = fpr.ESERCIZIO_ORI_OBBLIGAZIONE AND o.PG_OBBLIGAZIONE = fpr.PG_OBBLIGAZIONE
			LEFT JOIN CONTRATTO c ON c.ESERCIZIO = o.ESERCIZIO_CONTRATTO AND c.STATO = o.STATO_CONTRATTO AND c.PG_CONTRATTO = o.PG_CONTRATTO
			WHERE fp.IDENTIFICATIVO_SDI IS NOT NULL AND fp.FL_FATTURA_COMPENSO = 'N'
			UNION ALL
			SELECT fp.ID_PAESE, fp.ID_CODICE, fp.IDENTIFICATIVO_SDI, fp.PROGRESSIVO, NULL, NULL,
				   m.DT_EMISSIONE,
				   mr.IM_MANDATO_RIGA - mr.IM_RITENUTE_RIGA,
				   NULL, NULL, NULL
			FROM mandato_riga mr
			LEFT JOIN FATTURA_PASSIVA fp ON fp.ESERCIZIO = mr.ESERCIZIO_DOC_AMM AND fp.CD_CDS = mr.CD_CDS_DOC_AMM AND fp.CD_UNITA_ORGANIZZATIVA = mr.CD_UO_DOC_AMM
			AND fp.PG_FATTURA_PASSIVA = mr.PG_DOC_AMM
			LEFT JOIN mandato m ON mr.cd_cds = m.cd_cds AND mr.esercizio = m.esercizio AND mr.pg_mandato = m.pg_mandato
			WHERE fp.IDENTIFICATIVO_SDI IS NOT NULL AND fp.FL_FATTURA_COMPENSO = 'N' AND m.stato != 'A'
			AND mr.CD_TIPO_DOCUMENTO_AMM = 'FATTURA_P'
			UNION ALL
			SELECT fp.ID_PAESE, fp.ID_CODICE, fp.IDENTIFICATIVO_SDI, fp.PROGRESSIVO, NULL, NULL,
				   m.DT_EMISSIONE,
				   CASE WHEN m.PG_MANDATO IS NOT NULL THEN fpr.IM_TOTALE_DIVISA ELSE 0 END IM_TOTALE_DIVISA,
				   NULL, NULL, NULL
			FROM FATTURA_PASSIVA_RIGA fpr
			LEFT JOIN FATTURA_PASSIVA fp ON fp.CD_CDS = fpr.CD_CDS AND fp.CD_UNITA_ORGANIZZATIVA = fpr.CD_UNITA_ORGANIZZATIVA AND fp.ESERCIZIO = fpr.ESERCIZIO AND fp.PG_FATTURA_PASSIVA = fpr.PG_FATTURA_PASSIVA
			LEFT JOIN COMPENSO c ON c.CD_CDS = fp.CDS_COMPENSO AND c.CD_UNITA_ORGANIZZATIVA = fp.UO_COMPENSO AND c.ESERCIZIO = fp.ESERCIZIO_COMPENSO AND c.PG_COMPENSO = fp.PG_COMPENSO
			LEFT JOIN mandato_riga mr ON mr.CD_CDS = c.CD_CDS_OBBLIGAZIONE AND mr.ESERCIZIO_OBBLIGAZIONE = c.ESERCIZIO_OBBLIGAZIONE AND mr.ESERCIZIO_ORI_OBBLIGAZIONE = c.ESERCIZIO_ORI_OBBLIGAZIONE AND mr.PG_OBBLIGAZIONE = c.PG_OBBLIGAZIONE AND mr.PG_OBBLIGAZIONE_SCADENZARIO = c.PG_OBBLIGAZIONE_SCADENZARIO
			LEFT JOIN mandato m ON mr.cd_cds = m.cd_cds AND mr.esercizio = m.esercizio AND mr.pg_mandato = m.pg_mandato
			WHERE fp.IDENTIFICATIVO_SDI IS NOT NULL AND fp.FL_FATTURA_COMPENSO = 'Y' AND m.stato != 'A'
			UNION ALL
			SELECT fp.ID_PAESE, fp.ID_CODICE, fp.IDENTIFICATIVO_SDI, fp.PROGRESSIVO, NULL, NULL, null,
				   null,
				   ncr.IM_IMPONIBILE + CASE WHEN fp.FL_SPLIT_PAYMENT = 'Y' THEN 0 ELSE ncr.IM_IVA END, NULL, NULL
			FROM FATTURA_PASSIVA_RIGA fpr
			LEFT JOIN FATTURA_PASSIVA fp ON fp.CD_CDS = fpr.CD_CDS AND fp.CD_UNITA_ORGANIZZATIVA = fpr.CD_UNITA_ORGANIZZATIVA AND fp.ESERCIZIO = fpr.ESERCIZIO AND fp.PG_FATTURA_PASSIVA = fpr.PG_FATTURA_PASSIVA
			LEFT JOIN FATTURA_PASSIVA_RIGA ncr ON ncr.CD_CDS_ASSNCNA_FIN = fpr.CD_CDS AND ncr.CD_UO_ASSNCNA_FIN = fpr.CD_UNITA_ORGANIZZATIVA AND
			ncr.ESERCIZIO_ASSNCNA_FIN = fpr.ESERCIZIO AND ncr.PG_FATTURA_ASSNCNA_FIN = fpr.PG_FATTURA_PASSIVA AND ncr.PG_RIGA_ASSNCNA_FIN = fpr.PROGRESSIVO_RIGA
			LEFT JOIN mandato_riga mr ON mr.CD_CDS = ncr.CD_CDS_OBBLIGAZIONE AND mr.ESERCIZIO_OBBLIGAZIONE = ncr.ESERCIZIO_OBBLIGAZIONE AND
			mr.ESERCIZIO_ORI_OBBLIGAZIONE = ncr.ESERCIZIO_ORI_OBBLIGAZIONE AND mr.PG_OBBLIGAZIONE = ncr.PG_OBBLIGAZIONE AND
			mr.PG_OBBLIGAZIONE_SCADENZARIO = ncr.PG_OBBLIGAZIONE_SCADENZARIO AND mr.ESERCIZIO_DOC_AMM = ncr.ESERCIZIO AND
			mr.CD_CDS_DOC_AMM = ncr.CD_CDS AND mr.CD_UO_DOC_AMM = ncr.CD_UNITA_ORGANIZZATIVA AND mr.PG_DOC_AMM = ncr.PG_FATTURA_PASSIVA AND
			mr.CD_TIPO_DOCUMENTO_AMM = 'FATTURA_P'
			WHERE fp.IDENTIFICATIVO_SDI IS NOT NULL AND ncr.PG_FATTURA_PASSIVA IS NOT NULL) x
	  GROUP BY x.ID_PAESE, x.ID_CODICE, x.IDENTIFICATIVO_SDI, x.PROGRESSIVO) y
LEFT JOIN DOCUMENTO_ELE_TESTATA det ON det.ID_PAESE = y.ID_PAESE AND det.ID_CODICE = y.ID_CODICE AND det.IDENTIFICATIVO_SDI = y.IDENTIFICATIVO_SDI AND det.PROGRESSIVO = y.PROGRESSIVO
LEFT JOIN DOCUMENTO_ELE_TRASMISSIONE det2 ON det2.ID_PAESE = det.ID_PAESE AND det2.ID_CODICE = det.ID_CODICE AND det2.IDENTIFICATIVO_SDI = det.IDENTIFICATIVO_SDI
LEFT JOIN FATTURA_PASSIVA fp ON fp.ID_PAESE = det.ID_PAESE AND fp.ID_CODICE = det.ID_CODICE AND fp.IDENTIFICATIVO_SDI = det.IDENTIFICATIVO_SDI AND fp.PROGRESSIVO = det.PROGRESSIVO
)
/

 COMMENT ON COLUMN "V_CONTROLLI_PCC"."IDENTIFICATIVO_SDI" IS 'Identificativo SDI';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."NUMERO_DOCUMENTO" IS 'Numero Documento';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."DATA_DOCUMENTO" IS 'Data Documento';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."CODICE_FISCALE" IS 'Codice Fiscale';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."CODICE_DESTINATARIO" IS 'Codice Destinatario';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."DATA_RICEZIONE" IS 'Data Ricezione';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."DATA_SCADENZA" IS 'Data Scadenza';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."STATO_DOCUMENTO" IS 'Stato Documento';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."IMPORTO_DOCUMENTO" IS 'Importo Documento';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."IMPONIBILE" IS 'Imponibile';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."IMPOSTA" IS 'Imposta';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."TIPO_DOCUMENTO" IS 'Tipo Documento';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."ESERCIZIO" IS 'Esercizio';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."CD_UNITA_ORGANIZZATIVA" IS 'Unità Organizzativa';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."PG_FATTURA_PASSIVA" IS 'Progressivo Fattura Passiva';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."DT_REGISTRAZIONE" IS 'Data Registrazione';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."STATO_LIQUIDAZIONE" IS 'Stato Liquidazione';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."CAUSALE" IS 'Causale';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."DT_INIZIO_SOSPENSIONE" IS 'Data Inizio Sospensione';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."DT_EMISSIONE_MAN" IS 'Data Emissione Mandato';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."IM_MANDATO" IS 'Importo Mandato';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."IM_TOTALE_NC" IS 'totale note di credito collegate';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."CD_TIPO_CONTRATTO" IS 'Codice Contratto';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."FL_IRREGISTRABILE" IS 'Fattura elettronica non registrabile';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."CD_UO_CUU" IS 'Unità Organizzativa del CUU';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."FL_DA_COMPENSO" IS 'Fattura da Compenso';
 COMMENT ON COLUMN "V_CONTROLLI_PCC"."FL_SPLIT_PAYMENT" IS 'Fattura Split Payment';

