--------------------------------------------------------
--  DDL for View V_CONS_PDG_MODULO_CLASS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PDG_MODULO_CLASS" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "CD_PROGETTO", "DS_PROGETTO", "ID_CLASSIFICAZIONE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "IMPORTO_RIPARTITO") AS 
  Select
--
-- Date: 09/11/2006
-- Version: 1.1
--
-- Vista CONSULTAZIONE Piano di Gestione per Modulo/Classificazione
--
-- History:
--
-- Date: 01/01/2006
-- Version: 1.0
-- Creazione
--
-- Date: 09/11/2006
-- Version: 1.1
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
A.ESERCIZIO, A.CD_CENTRO_RESPONSABILITA, B.DS_CDR, D.CD_PROGETTO, D.DS_PROGETTO,
       A.ID_CLASSIFICAZIONE, C.CD_CLASSIFICAZIONE, C.DS_CLASSIFICAZIONE,
       NVL(SUM(A.IMPORTO_RIPARTITO), 0) IMPORTO_RIPARTITO
From (Select ESERCIZIO,
             CD_CENTRO_RESPONSABILITA,
             ID_CLASSIFICAZIONE,
             PG_PROGETTO,
             Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0) +
             Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_SPESE
      union all
      Select a.ESERCIZIO,
             a.CD_CENTRO_RESPONSABILITA,
             To_Number(b.VAL01) ID_CLASSIFICAZIONE,
             a.PG_PROGETTO,
             Nvl(a.IM_CF_AMM_IMMOBILI, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_COSTI a, CONFIGURAZIONE_CNR b
      Where a.ESERCIZIO = b.ESERCIZIO
      And   b.CD_CHIAVE_PRIMARIA = 'PIANO_RIPARTO'
      And   b.CD_CHIAVE_SECONDARIA = 'IM_CF_AMM_IMMOBILI'
      union all
      Select a.ESERCIZIO,
             a.CD_CENTRO_RESPONSABILITA,
             To_Number(b.VAL01) ID_CLASSIFICAZIONE,
             a.PG_PROGETTO,
             Nvl(a.IM_CF_AMM_ATTREZZ, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_COSTI a, CONFIGURAZIONE_CNR b
      Where a.ESERCIZIO = b.ESERCIZIO
      And   b.CD_CHIAVE_PRIMARIA = 'PIANO_RIPARTO'
      And   b.CD_CHIAVE_SECONDARIA = 'IM_CF_AMM_ATTREZZ'
      union all
      Select a.ESERCIZIO,
             a.CD_CENTRO_RESPONSABILITA,
             To_Number(b.VAL01) ID_CLASSIFICAZIONE,
             a.PG_PROGETTO,
             Nvl(a.IM_CF_AMM_ALTRO, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_COSTI a, CONFIGURAZIONE_CNR b
      Where a.ESERCIZIO = b.ESERCIZIO
      And   b.CD_CHIAVE_PRIMARIA = 'PIANO_RIPARTO'
      And   b.CD_CHIAVE_SECONDARIA = 'IM_CF_AMM_ALTRO') A, CDR B, V_CLASSIFICAZIONE_VOCI C, PROGETTO_PREV D
Where A.CD_CENTRO_RESPONSABILITA = B.CD_CENTRO_RESPONSABILITA
and   A.ID_CLASSIFICAZIONE = C.ID_CLASSIFICAZIONE
and   A.PG_PROGETTO = D.PG_PROGETTO
And   D.ESERCIZIO = A.ESERCIZIO
Group by A.ESERCIZIO, A.CD_CENTRO_RESPONSABILITA, B.DS_CDR, D.CD_PROGETTO, D.DS_PROGETTO,
         A.ID_CLASSIFICAZIONE, C.CD_CLASSIFICAZIONE, C.DS_CLASSIFICAZIONE;
