--------------------------------------------------------
--  DDL for View V_CONFRONTO_RES_FIN_INI_ENTE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONFRONTO_RES_FIN_INI_ENTE" ("CD_CDS", "ESERCIZIO", "ESERCIZIO_RES", "CD_VOCE", "ASS_COMP", "IMP_COMP", "PAG_COMP", "ASS_RES", "PAG_RES", "RES_INI_ES_SUCC") AS 
  SELECT 	SUBSTR(VOCE_F_SALDI_CDR_LINEA.CD_VOCE, 17, 3) cd_cds,
	VOCE_F_SALDI_CDR_LINEA.ESERCIZIO,
	ESERCIZIO_RES,
	VOCE_F_SALDI_CDR_LINEA.CD_VOCE,
	SUM(IM_STANZ_INIZIALE_A1)+Sum(VARIAZIONI_PIU)-Sum(VARIAZIONI_MENO) ASS_COMP,
	SUM(IM_OBBL_ACC_COMP) IMP_COMP,
	SUM(Decode(VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES, VOCE_F_SALDI_CDR_LINEA.ESERCIZIO, IM_MANDATI_REVERSALI_PRO, 0)) PAG_COMP,
	SUM(IM_OBBL_RES_PRO)+Sum(VAR_PIU_OBBL_RES_PRO)-Sum(VAR_MENO_OBBL_RES_PRO) ASS_RES,
	SUM(Decode(VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES, VOCE_F_SALDI_CDR_LINEA.ESERCIZIO, 0, IM_MANDATI_REVERSALI_PRO)) PAG_RES,
	(SELECT Nvl(SUM(IM_OBBL_RES_PRO), 0)
	 FROM 	VOCE_F_SALDI_CDR_LINEA V_ES_SUCC
	 WHERE 	V_ES_SUCC.ESERCIZIO             = VOCE_F_SALDI_CDR_LINEA.ESERCIZIO+1 AND
	 	V_ES_SUCC.ESERCIZIO_RES         = VOCE_F_SALDI_CDR_LINEA.ESERCIZIO_RES AND
	 	V_ES_SUCC.CD_CENTRO_RESPONSABILITA = '999.000.000' AND
	 	V_ES_SUCC.CD_VOCE                = VOCE_F_SALDI_CDR_LINEA.CD_VOCE AND
		V_ES_SUCC.TI_APPARTENENZA       = 'C' AND
		V_ES_SUCC.TI_GESTIONE           = 'S') RES_INI_ES_SUCC
FROM    VOCE_F_SALDI_CDR_LINEA, VOCE_F
WHERE	VOCE_F_SALDI_CDR_LINEA.ESERCIZIO = VOCE_F.ESERCIZIO And
        VOCE_F_SALDI_CDR_LINEA.TI_APPARTENENZA = VOCE_F.TI_APPARTENENZA And
        VOCE_F_SALDI_CDR_LINEA.TI_GESTIONE = VOCE_F.TI_GESTIONE And
        VOCE_F_SALDI_CDR_LINEA.CD_VOCE = VOCE_F.CD_VOCE And
        VOCE_F.CD_PARTE != '2' And
        VOCE_F_SALDI_CDR_LINEA.TI_APPARTENENZA          = 'C' AND
	VOCE_F_SALDI_CDR_LINEA.TI_GESTIONE              = 'S' AND
	VOCE_F_SALDI_CDR_LINEA.CD_CENTRO_RESPONSABILITA = '999.000.000'
GROUP BY SUBSTR(VOCE_F_SALDI_CDR_LINEA.CD_VOCE, 17, 3),
	VOCE_F_SALDI_CDR_LINEA.ESERCIZIO,
	ESERCIZIO_RES,
	VOCE_F_SALDI_CDR_LINEA.CD_VOCE;
