--------------------------------------------------------
--  DDL for View V_COMPENSO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_COMPENSO" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_COMPENSO", "DS_COMPENSO", "DT_REGISTRAZIONE", "DT_DA_COMPETENZA_COGE", "DT_A_COMPETENZA_COGE", "FL_COMPENSO_CONGUAGLIO", "FL_SENZA_CALCOLI", "IM_LORDO_PERCIPIENTE", "IM_NETTO_PERCIPIENTE", "DETRAZIONE_ALTRI_NETTO", "DETRAZIONE_CONIUGE_NETTO", "DETRAZIONE_FIGLI_NETTO", "DETRAZIONI_LA_NETTO", "DETRAZIONI_PERSONALI_NETTO", "DETRAZIONE_RID_CUNEO_NETTO", "IM_DEDUZIONE_IRPEF", "CD_TERZO", "NOME", "COGNOME", "RAGIONE_SOCIALE", "CODICE_FISCALE", "PARTITA_IVA", "PG_OBBLIGAZIONE", "CD_TRATTAMENTO", "DS_TI_TRATTAMENTO", "CD_ANAG", "TI_ITALIANO_ESTERO", "TI_ENTITA", "TI_ENTITA_FISICA", "TI_ENTITA_GIURIDICA", "DENOMINAZIONE_SEDE", "VIA_SEDE", "NUMERO_CIVICO_SEDE", "PG_COMUNE_SEDE", "DS_COMUNE_SEDE", "CD_PROVINCIA_SEDE", "DS_PROVINCIA_SEDE", "CAP_COMUNE_SEDE", "FRAZIONE_SEDE", "VIA_FISCALE", "NUM_CIVICO_FISCALE", "PG_COMUNE_FISCALE", "DS_COMUNE_FISCALE", "CD_PROVINCIA_FISCALE", "DS_PROVINCIA_FISCALE", "CAP_COMUNE_FISCALE", "FRAZIONE_FISCALE", "PG_NAZIONE_FISCALE", "DT_NASCITA", "PG_COMUNE_NASCITA", "DS_COMUNE_NASCITA", "CD_PROVINCIA_NASCITA", "DS_PROVINCIA_NASCITA", "CD_CONTRIBUTO_RITENUTA", "TI_ENTE_PERCIPIENTE", "PG_RIGA", "IMPONIBILE", "ALIQUOTA", "AMMONTARE_LORDO", "IMPONIBILE_LORDO", "CLASSIFICAZIONE", "IM_CORI_SOSPESO", "ORDINAMENTO", "IM_DEDUZIONE_FAMILY", "PG_MINICARRIERA", "ALIQUOTA_FISCALE", "FL_CARICHI_FAMILIARI", "FL_NOTAXAREA", "FL_NOFAMILYAREA", "IM_TOTALE_COMPENSO", "DS_CONTRIBUTO_RITENUTA", "PG_MISSIONE", "FL_CERVELLONE", "FL_NO_DETRAZIONI_ALTRE", "FL_NO_DETRAZIONI_FAMILY", "FL_DETRAZIONI_ALTRI_TIPI", "IM_NETTO_DA_TRATTENERE", "TI_DIPENDENTE_ALTRO", "FL_ENTE_PRENDERE", "DACR", "UTCR", "DS_UNITA_ORGANIZZATIVA", "FL_NO_CREDITO_IRPEF", "FL_NO_CREDITO_CUNEO_IRPEF", "FL_NO_DETR_CUNEO_IRPEF", "DS_NAZIONE_SEDE") AS
  SELECT
--==============================================================================
-- History:
-- Date: 07/08/2008
-- Version: 1.3
-- Creazione
--
-- Vista per la stampa massiva dei compensi
--
-- Date: 31/01/2007
-- Version: 1.1
-- Modifica
--
-- Aggiunti FL_NO_DETRAZIONI_ALTRE, FL_NO_DETRAZIONI_FAMILY
-- Date: 17/05/2007
-- Version: 1.2
-- Modifica
--
-- Aggiunta classificazione_cori C1
--
-- Date: 07/08/2008
-- Version: 1.3
-- Modifica
--
-- Aggiunte classificazione_cori R0,P0,C0 e IV
--
-- Date: 06/04/2011
-- Version: 1.4
-- Modifica
--
-- Aggiunto FL_DETRAZIONI_ALTRI_TIPI
--
-- Date: 25/05/2014
-- Version: 2.21
-- Adeguamenti relativi al Bonus DL 66/2014
-- Aggiunto FL_NO_CREDITO_IRPEF
--==============================================================================
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
1,
CONTRIBUTO_RITENUTA.IMPONIBILE,
CONTRIBUTO_RITENUTA.ALIQUOTA,
CONTRIBUTO_RITENUTA.AMMONTARE_LORDO,
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
10, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
(Select Distinct PG_MINICARRIERA From Minicarriera_rata M
 Where M.CD_CDS_COMPENSO = COMPENSO.CD_CDS
   And M.CD_UO_COMPENSO = COMPENSO.CD_UNITA_ORGANIZZATIVA
   And M.ESERCIZIO_COMPENSO = COMPENSO.ESERCIZIO
   And M.PG_COMPENSO = COMPENSO.PG_COMPENSO),
V_ANAGRAFICO_TERZO.ALIQUOTA_FISCALE,
(Select Decode(Count(1),0,'N','Y')
 From CARICO_FAMILIARE_ANAG
 Where CARICO_FAMILIARE_ANAG.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG),
Nvl((Select FL_NOTAXAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NOFAMILYAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
V_ANAGRAFICO_TERZO.FL_CERVELLONE,
Nvl((Select FL_NO_DETRAZIONI_ALTRE
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETRAZIONI_FAMILY
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_DETRAZIONI_ALTRI_TIPI
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'N',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Nvl((Select FL_NO_CREDITO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_CREDITO_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETR_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
   nazione.ds_nazione
FROM
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
Where
COMPENSO.FL_COMPENSO_CONGUAGLIO   = 'N' AND
ti_trat.CD_TRATTAMENTO 			  = COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			  <= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			  >= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				  = V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		  = TIPO_RAPPORTO.CD_TIPO_RAPPORTO AND
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'A'  And
CONTRIBUTO_RITENUTA.CD_CDS 		  		   = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 			   = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 		   = COMPENSO.PG_COMPENSO AND
--CONTRIBUTO_RITENUTA.ALIQUOTA != 0 AND CONTRIBUTO_RITENUTA.ALIQUOTA IS NOT NULL AND
--CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE    = 'P' AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 	   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI 	 = 'FI'--IN ('IL', 'PR', 'FI')
 and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
 and nazione.pg_nazione = comune.pg_nazione
 and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune
Union ALL
SELECT
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
1,
CONTRIBUTO_RITENUTA.IMPONIBILE,
CONTRIBUTO_RITENUTA.ALIQUOTA,
CONTRIBUTO_RITENUTA.AMMONTARE_LORDO,
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
5, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
(Select Distinct PG_MINICARRIERA From Minicarriera_rata M
 Where M.CD_CDS_COMPENSO = COMPENSO.CD_CDS
   And M.CD_UO_COMPENSO = COMPENSO.CD_UNITA_ORGANIZZATIVA
   And M.ESERCIZIO_COMPENSO = COMPENSO.ESERCIZIO
   And M.PG_COMPENSO = COMPENSO.PG_COMPENSO),
V_ANAGRAFICO_TERZO.ALIQUOTA_FISCALE,
(Select Decode(Count(1),0,'N','Y')
 From CARICO_FAMILIARE_ANAG
 Where CARICO_FAMILIARE_ANAG.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG),
Nvl((Select FL_NOTAXAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NOFAMILYAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
V_ANAGRAFICO_TERZO.FL_CERVELLONE,
Nvl((Select FL_NO_DETRAZIONI_ALTRE
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETRAZIONI_FAMILY
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_DETRAZIONI_ALTRI_TIPI
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'N',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Nvl((Select FL_NO_CREDITO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_CREDITO_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETR_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
   nazione.ds_nazione
FROM
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
WHERE
COMPENSO.FL_COMPENSO_CONGUAGLIO   = 'N' AND
ti_trat.CD_TRATTAMENTO 			  = COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			  <= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			  >= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				  = V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		  = TIPO_RAPPORTO.CD_TIPO_RAPPORTO And
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'A'  And
CONTRIBUTO_RITENUTA.CD_CDS 		  		   = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 			   = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 		   = COMPENSO.PG_COMPENSO AND
--CONTRIBUTO_RITENUTA.ALIQUOTA != 0 AND CONTRIBUTO_RITENUTA.ALIQUOTA IS NOT NULL AND
--CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE    = 'P' AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 	   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI 	 IN ('IL', 'PR','IP') --IN ('IL', 'PR', 'FI')
AND NOT EXISTS (SELECT 1 FROM CONTRIBUTO_RITENUTA_DET CORID
			    WHERE CORID.CD_CDS = CONTRIBUTO_RITENUTA.CD_CDS
				  AND CORID.CD_UNITA_ORGANIZZATIVA = CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA
				  AND CORID.ESERCIZIO 			   = CONTRIBUTO_RITENUTA.ESERCIZIO
				  AND CORID.PG_COMPENSO			   = CONTRIBUTO_RITENUTA.PG_COMPENSO
				  AND CORID.CD_CONTRIBUTO_RITENUTA = CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA
				  AND CORID.TI_ENTE_PERCIPIENTE	   = CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE)
				   and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
				  and nazione.pg_nazione = comune.pg_nazione
 					and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune
UNION ALL
SELECT
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
1,
CONTRIBUTO_RITENUTA.IMPONIBILE,
CONTRIBUTO_RITENUTA.ALIQUOTA,
CONTRIBUTO_RITENUTA.AMMONTARE_LORDO,
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
20, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
(Select Distinct PG_MINICARRIERA From Minicarriera_rata M
 Where M.CD_CDS_COMPENSO = COMPENSO.CD_CDS
   And M.CD_UO_COMPENSO = COMPENSO.CD_UNITA_ORGANIZZATIVA
   And M.ESERCIZIO_COMPENSO = COMPENSO.ESERCIZIO
   And M.PG_COMPENSO = COMPENSO.PG_COMPENSO),
V_ANAGRAFICO_TERZO.ALIQUOTA_FISCALE,
(Select Decode(Count(1),0,'N','Y')
 From CARICO_FAMILIARE_ANAG
 Where CARICO_FAMILIARE_ANAG.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG),
Nvl((Select FL_NOTAXAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NOFAMILYAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
V_ANAGRAFICO_TERZO.FL_CERVELLONE,
Nvl((Select FL_NO_DETRAZIONI_ALTRE
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETRAZIONI_FAMILY
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_DETRAZIONI_ALTRI_TIPI
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'N',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Nvl((Select FL_NO_CREDITO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_CREDITO_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETR_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
   nazione.ds_nazione
FROM
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
WHERE
COMPENSO.FL_COMPENSO_CONGUAGLIO   = 'N' AND
ti_trat.CD_TRATTAMENTO 			  = COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			  <= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			  >= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				  = V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		  = TIPO_RAPPORTO.CD_TIPO_RAPPORTO And
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'A'  And
CONTRIBUTO_RITENUTA.CD_CDS 		  		   = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 			   = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 		   = COMPENSO.PG_COMPENSO AND
--CONTRIBUTO_RITENUTA.ALIQUOTA != 0 AND CONTRIBUTO_RITENUTA.ALIQUOTA IS NOT NULL AND
--CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE    = 'P' AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 	   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI 	 IN ('P9','C9','R9','C1','R0','P0','C0') --IN ('IL', 'PR', 'FI')
AND NOT EXISTS (SELECT 1 FROM CONTRIBUTO_RITENUTA_DET CORID
			    WHERE CORID.CD_CDS = CONTRIBUTO_RITENUTA.CD_CDS
				  AND CORID.CD_UNITA_ORGANIZZATIVA = CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA
				  AND CORID.ESERCIZIO 			   = CONTRIBUTO_RITENUTA.ESERCIZIO
				  AND CORID.PG_COMPENSO			   = CONTRIBUTO_RITENUTA.PG_COMPENSO
				  AND CORID.CD_CONTRIBUTO_RITENUTA = CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA
				  AND CORID.TI_ENTE_PERCIPIENTE	   = CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE)
				   and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
				    and nazione.pg_nazione = comune.pg_nazione
 and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune
UNION ALL
SELECT
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
1,
CONTRIBUTO_RITENUTA.IMPONIBILE,
CONTRIBUTO_RITENUTA.ALIQUOTA,
CONTRIBUTO_RITENUTA.AMMONTARE_LORDO,
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
1, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
(Select Distinct PG_MINICARRIERA From Minicarriera_rata M
 Where M.CD_CDS_COMPENSO = COMPENSO.CD_CDS
   And M.CD_UO_COMPENSO = COMPENSO.CD_UNITA_ORGANIZZATIVA
   And M.ESERCIZIO_COMPENSO = COMPENSO.ESERCIZIO
   And M.PG_COMPENSO = COMPENSO.PG_COMPENSO),
V_ANAGRAFICO_TERZO.ALIQUOTA_FISCALE,
(Select Decode(Count(1),0,'N','Y')
 From CARICO_FAMILIARE_ANAG
 Where CARICO_FAMILIARE_ANAG.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG),
Nvl((Select FL_NOTAXAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NOFAMILYAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
V_ANAGRAFICO_TERZO.FL_CERVELLONE,
Nvl((Select FL_NO_DETRAZIONI_ALTRE
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETRAZIONI_FAMILY
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_DETRAZIONI_ALTRI_TIPI
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'S',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Nvl((Select FL_NO_CREDITO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_CREDITO_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETR_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
   nazione.ds_nazione
FROM
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
WHERE
COMPENSO.FL_COMPENSO_CONGUAGLIO   = 'N' AND
ti_trat.CD_TRATTAMENTO 			  = COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			  <= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			  >= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				  = V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		  = TIPO_RAPPORTO.CD_TIPO_RAPPORTO AND
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'A'  And
CONTRIBUTO_RITENUTA.CD_CDS 		  		   = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 			   = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 		   = COMPENSO.PG_COMPENSO AND
--CONTRIBUTO_RITENUTA.ALIQUOTA != 0 AND CONTRIBUTO_RITENUTA.ALIQUOTA IS NOT NULL AND
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE    = 'E' AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 	   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI 	 IN ('RV','IV') --IN ('IL', 'PR', 'FI')
AND NOT EXISTS (SELECT 1 FROM CONTRIBUTO_RITENUTA_DET CORID
			    WHERE CORID.CD_CDS = CONTRIBUTO_RITENUTA.CD_CDS
				  AND CORID.CD_UNITA_ORGANIZZATIVA = CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA
				  AND CORID.ESERCIZIO 			   = CONTRIBUTO_RITENUTA.ESERCIZIO
				  AND CORID.PG_COMPENSO			   = CONTRIBUTO_RITENUTA.PG_COMPENSO
				  AND CORID.CD_CONTRIBUTO_RITENUTA = CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA
				  AND CORID.TI_ENTE_PERCIPIENTE	   = CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE)
				   and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
				   and nazione.pg_nazione = comune.pg_nazione
 and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune
UNION ALL
SELECT
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
NVL(CONTRIBUTO_RITENUTA_DET.PG_RIGA,1),
NVL(CONTRIBUTO_RITENUTA_DET.IMPONIBILE,CONTRIBUTO_RITENUTA.IMPONIBILE),
NVL(CONTRIBUTO_RITENUTA_DET.ALIQUOTA,CONTRIBUTO_RITENUTA.ALIQUOTA),
NVL(CONTRIBUTO_RITENUTA_DET.AMMONTARE,CONTRIBUTO_RITENUTA.AMMONTARE_LORDO),
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
5, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
(Select Distinct PG_MINICARRIERA From Minicarriera_rata M
 Where M.CD_CDS_COMPENSO = COMPENSO.CD_CDS
   And M.CD_UO_COMPENSO = COMPENSO.CD_UNITA_ORGANIZZATIVA
   And M.ESERCIZIO_COMPENSO = COMPENSO.ESERCIZIO
   And M.PG_COMPENSO = COMPENSO.PG_COMPENSO),
V_ANAGRAFICO_TERZO.ALIQUOTA_FISCALE,
(Select Decode(Count(1),0,'N','Y')
 From CARICO_FAMILIARE_ANAG
 Where CARICO_FAMILIARE_ANAG.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG),
Nvl((Select FL_NOTAXAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NOFAMILYAREA
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
V_ANAGRAFICO_TERZO.FL_CERVELLONE,
Nvl((Select FL_NO_DETRAZIONI_ALTRE
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETRAZIONI_FAMILY
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_DETRAZIONI_ALTRI_TIPI
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'N',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Nvl((Select FL_NO_CREDITO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_CREDITO_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
Nvl((Select FL_NO_DETR_CUNEO_IRPEF
 From ANAGRAFICO_ESERCIZIO
 Where ANAGRAFICO_ESERCIZIO.CD_ANAG = V_ANAGRAFICO_TERZO.CD_ANAG
   And ANAGRAFICO_ESERCIZIO.ESERCIZIO = COMPENSO.ESERCIZIO),'N'),
   nazione.ds_nazione
FROM
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA_DET,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
WHERE
COMPENSO.FL_COMPENSO_CONGUAGLIO = 'N' AND
ti_trat.CD_TRATTAMENTO 			= COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			<= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			>= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				= V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		= TIPO_RAPPORTO.CD_TIPO_RAPPORTO AND
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'A'  And
CONTRIBUTO_RITENUTA.CD_CDS 		  			  = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA 	  = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 				  = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 			  = COMPENSO.PG_COMPENSO AND
(CONTRIBUTO_RITENUTA.ALIQUOTA = 0 OR CONTRIBUTO_RITENUTA.ALIQUOTA IS NULL) AND
--CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE = 'P' AND
CONTRIBUTO_RITENUTA_DET.CD_CDS 			  	  	   = CONTRIBUTO_RITENUTA.CD_CDS AND
CONTRIBUTO_RITENUTA_DET.CD_UNITA_ORGANIZZATIVA 	   = CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA_DET.ESERCIZIO 				   = CONTRIBUTO_RITENUTA.ESERCIZIO AND
CONTRIBUTO_RITENUTA_DET.PG_COMPENSO 			   = CONTRIBUTO_RITENUTA.PG_COMPENSO AND
CONTRIBUTO_RITENUTA_DET.CD_CONTRIBUTO_RITENUTA 	   = CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA_DET.TI_ENTE_PERCIPIENTE 	   = CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA 		   = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 			   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI   = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI IN ('IL', 'PR')
 and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
  and nazione.pg_nazione = comune.pg_nazione
 and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune
Union All
SELECT
-- Vista per la stampa massiva dei compensi per dipendenti
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
1,
CONTRIBUTO_RITENUTA.IMPONIBILE,
CONTRIBUTO_RITENUTA.ALIQUOTA,
CONTRIBUTO_RITENUTA.AMMONTARE_LORDO,
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
10, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
Null ,-- PG_MINICARRIERA,
Null ,--ALIQUOTA_FISCALE,
Null ,--FL_CARICHI_FAMILIARI,
Null ,--FL_NOTAXAREA,
Null ,--FL_NOFAMILYAREA,
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
Null ,--FL_CERVELLONE,
Null ,--FL_NO_DETRAZIONI_ALTRE,
Null ,--FL_NO_DETRAZIONI_FAMILY,
Null ,--FL_DETRAZIONI_ALTRI_TIPI,
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'N',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Null , --FL_NO_CREDITO_IRPEF
Null ,
Null ,
nazione.ds_nazione
FROM
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
Where
COMPENSO.FL_COMPENSO_CONGUAGLIO   = 'N' AND
ti_trat.CD_TRATTAMENTO 			  = COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			  <= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			  >= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				  = V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		  = TIPO_RAPPORTO.CD_TIPO_RAPPORTO AND
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'D' AND
CONTRIBUTO_RITENUTA.CD_CDS 		  		   = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 			   = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 		   = COMPENSO.PG_COMPENSO AND
--CONTRIBUTO_RITENUTA.ALIQUOTA != 0 AND CONTRIBUTO_RITENUTA.ALIQUOTA IS NOT NULL AND
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE    = 'P' AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 	   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI 	 = 'FI'--IN ('IL', 'PR', 'FI')
and COMPENSO.FL_SENZA_CALCOLI = 'N' and
pg_missione is null
 and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
  and nazione.pg_nazione = comune.pg_nazione
 and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune
Union ALL
SELECT
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
1,
CONTRIBUTO_RITENUTA.IMPONIBILE,
CONTRIBUTO_RITENUTA.ALIQUOTA,
CONTRIBUTO_RITENUTA.AMMONTARE_LORDO,
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
5, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
Null ,-- PG_MINICARRIERA,
Null ,--ALIQUOTA_FISCALE,
Null ,--FL_CARICHI_FAMILIARI,
Null ,--FL_NOTAXAREA,
Null ,--FL_NOFAMILYAREA,
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
Null ,--FL_CERVELLONE,
Null ,--FL_NO_DETRAZIONI_ALTRE,
Null ,--FL_NO_DETRAZIONI_FAMILY,
Null ,--FL_DETRAZIONI_ALTRI_TIPI,
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'N',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Null ,  --FL_NO_CREDITO_IRPEF
Null ,
Null ,
nazione.ds_nazione
From
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
WHERE
COMPENSO.FL_COMPENSO_CONGUAGLIO   = 'N' AND
ti_trat.CD_TRATTAMENTO 			  = COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			  <= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			  >= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				  = V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		  = TIPO_RAPPORTO.CD_TIPO_RAPPORTO AND
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'D' AND
CONTRIBUTO_RITENUTA.CD_CDS 		  		   = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 			   = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 		   = COMPENSO.PG_COMPENSO AND
--CONTRIBUTO_RITENUTA.ALIQUOTA != 0 AND CONTRIBUTO_RITENUTA.ALIQUOTA IS NOT NULL AND
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE    = 'P' AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 	   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI 	 IN ('IL', 'PR') --IN ('IL', 'PR', 'FI')
AND NOT EXISTS (SELECT 1 FROM CONTRIBUTO_RITENUTA_DET CORID
			    WHERE CORID.CD_CDS = CONTRIBUTO_RITENUTA.CD_CDS
				  AND CORID.CD_UNITA_ORGANIZZATIVA = CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA
				  AND CORID.ESERCIZIO 			   = CONTRIBUTO_RITENUTA.ESERCIZIO
				  AND CORID.PG_COMPENSO			   = CONTRIBUTO_RITENUTA.PG_COMPENSO
				  AND CORID.CD_CONTRIBUTO_RITENUTA = CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA
				  AND CORID.TI_ENTE_PERCIPIENTE	   = CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE)
And COMPENSO.FL_SENZA_CALCOLI = 'N' and
pg_missione is null
 and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
  and nazione.pg_nazione = comune.pg_nazione
 and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune
Union ALL
SELECT
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
1,
CONTRIBUTO_RITENUTA.IMPONIBILE,
CONTRIBUTO_RITENUTA.ALIQUOTA,
CONTRIBUTO_RITENUTA.AMMONTARE_LORDO,
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
20, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
Null ,-- PG_MINICARRIERA,
Null ,--ALIQUOTA_FISCALE,
Null ,--FL_CARICHI_FAMILIARI,
Null ,--FL_NOTAXAREA,
Null ,--FL_NOFAMILYAREA,
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
Null ,--FL_CERVELLONE,
Null ,--FL_NO_DETRAZIONI_ALTRE,
Null ,--FL_NO_DETRAZIONI_FAMILY,
Null ,--FL_DETRAZIONI_ALTRI_TIPI,
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'N',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Null ,  --FL_NO_CREDITO_IRPEF
Null ,
Null ,
nazione.ds_nazione
From
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
WHERE
COMPENSO.FL_COMPENSO_CONGUAGLIO   = 'N' AND
ti_trat.CD_TRATTAMENTO 			  = COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			  <= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			  >= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				  = V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		  = TIPO_RAPPORTO.CD_TIPO_RAPPORTO AND
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'D' AND
CONTRIBUTO_RITENUTA.CD_CDS 		  		   = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 			   = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 		   = COMPENSO.PG_COMPENSO AND
--CONTRIBUTO_RITENUTA.ALIQUOTA != 0 AND CONTRIBUTO_RITENUTA.ALIQUOTA IS NOT NULL AND
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE    = 'P' AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 	   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI 	 IN ('P9','C9','R9','C1','R0','P0','C0') --IN ('IL', 'PR', 'FI')
AND NOT EXISTS (SELECT 1 FROM CONTRIBUTO_RITENUTA_DET CORID
			    WHERE CORID.CD_CDS = CONTRIBUTO_RITENUTA.CD_CDS
				  AND CORID.CD_UNITA_ORGANIZZATIVA = CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA
				  AND CORID.ESERCIZIO 			   = CONTRIBUTO_RITENUTA.ESERCIZIO
				  AND CORID.PG_COMPENSO			   = CONTRIBUTO_RITENUTA.PG_COMPENSO
				  AND CORID.CD_CONTRIBUTO_RITENUTA = CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA
				  AND CORID.TI_ENTE_PERCIPIENTE	   = CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE)
And COMPENSO.FL_SENZA_CALCOLI = 'N' and
pg_missione is null
 and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
  and nazione.pg_nazione = comune.pg_nazione
 and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune
Union ALL
SELECT
COMPENSO.CD_CDS,
COMPENSO.CD_UNITA_ORGANIZZATIVA,
COMPENSO.ESERCIZIO,
COMPENSO.PG_COMPENSO,
COMPENSO.DS_COMPENSO,
COMPENSO.DT_REGISTRAZIONE,
COMPENSO.DT_DA_COMPETENZA_COGE,
COMPENSO.DT_A_COMPETENZA_COGE,
COMPENSO.FL_COMPENSO_CONGUAGLIO,
COMPENSO.FL_SENZA_CALCOLI,
COMPENSO.IM_LORDO_PERCIPIENTE,
COMPENSO.IM_NETTO_PERCIPIENTE,
COMPENSO.DETRAZIONE_ALTRI_NETTO,
COMPENSO.DETRAZIONE_CONIUGE_NETTO,
COMPENSO.DETRAZIONE_FIGLI_NETTO,
COMPENSO.DETRAZIONI_LA_NETTO,
COMPENSO.DETRAZIONI_PERSONALI_NETTO,
COMPENSO.DETRAZIONE_RID_CUNEO_NETTO,
COMPENSO.IM_DEDUZIONE_IRPEF,
COMPENSO.CD_TERZO,
COMPENSO.NOME,
COMPENSO.COGNOME,
COMPENSO.RAGIONE_SOCIALE,
COMPENSO.CODICE_FISCALE,
COMPENSO.PARTITA_IVA,
COMPENSO.PG_OBBLIGAZIONE,
COMPENSO.CD_TRATTAMENTO,
ti_trat.DS_TI_TRATTAMENTO,
V_ANAGRAFICO_TERZO.CD_ANAG,
V_ANAGRAFICO_TERZO.TI_ITALIANO_ESTERO,
V_ANAGRAFICO_TERZO.TI_ENTITA,
V_ANAGRAFICO_TERZO.TI_ENTITA_FISICA,
V_ANAGRAFICO_TERZO.TI_ENTITA_GIURIDICA,
V_ANAGRAFICO_TERZO.DENOMINAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_SEDE,
V_ANAGRAFICO_TERZO.NUMERO_CIVICO_SEDE,
V_ANAGRAFICO_TERZO.PG_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.DS_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_SEDE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_SEDE,
V_ANAGRAFICO_TERZO.FRAZIONE_SEDE,
V_ANAGRAFICO_TERZO.VIA_FISCALE,
V_ANAGRAFICO_TERZO.NUM_CIVICO_FISCALE,
V_ANAGRAFICO_TERZO.PG_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.DS_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_FISCALE,
V_ANAGRAFICO_TERZO.CAP_COMUNE_FISCALE,
V_ANAGRAFICO_TERZO.FRAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.PG_NAZIONE_FISCALE,
V_ANAGRAFICO_TERZO.DT_NASCITA,
V_ANAGRAFICO_TERZO.PG_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.DS_COMUNE_NASCITA,
V_ANAGRAFICO_TERZO.CD_PROVINCIA_NASCITA,
V_ANAGRAFICO_TERZO.DS_PROVINCIA_NASCITA,
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE,
NVL(CONTRIBUTO_RITENUTA_DET.PG_RIGA,1),
NVL(CONTRIBUTO_RITENUTA_DET.IMPONIBILE,CONTRIBUTO_RITENUTA.IMPONIBILE),
NVL(CONTRIBUTO_RITENUTA_DET.ALIQUOTA,CONTRIBUTO_RITENUTA.ALIQUOTA),
NVL(CONTRIBUTO_RITENUTA_DET.AMMONTARE,CONTRIBUTO_RITENUTA.AMMONTARE_LORDO),
CONTRIBUTO_RITENUTA.IMPONIBILE_LORDO,
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI,
CONTRIBUTO_RITENUTA.IM_CORI_SOSPESO,
5, --Campo per ordinamento Stampa
CONTRIBUTO_RITENUTA.IM_DEDUZIONE_FAMILY,
Null ,-- PG_MINICARRIERA,
Null ,--ALIQUOTA_FISCALE,
Null ,--FL_CARICHI_FAMILIARI,
Null ,--FL_NOTAXAREA,
Null ,--FL_NOFAMILYAREA,
COMPENSO.IM_TOTALE_COMPENSO,
Nvl(TIPO_CONTRIBUTO_RITENUTA.DS_STAMPE,TIPO_CONTRIBUTO_RITENUTA.DS_CONTRIBUTO_RITENUTA) DS_CONTRIBUTO_RITENUTA,
COMPENSO.PG_MISSIONE,
Null ,--FL_CERVELLONE,
Null ,--FL_NO_DETRAZIONI_ALTRE,
Null ,--FL_NO_DETRAZIONI_FAMILY,
Null ,--FL_DETRAZIONI_ALTRI_TIPI,
COMPENSO.IM_NETTO_DA_TRATTENERE,
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO,
'N',
compenso.DACR,
compenso.UTCR,
unita_organizzativa.ds_unita_organizzativa,
Null ,  --FL_NO_CREDITO_IRPEF
Null ,
Null ,
nazione.ds_nazione
From
COMPENSO,
TIPO_TRATTAMENTO ti_trat,
TIPO_RAPPORTO,
V_ANAGRAFICO_TERZO,
CONTRIBUTO_RITENUTA,
CONTRIBUTO_RITENUTA_DET,
TIPO_CONTRIBUTO_RITENUTA,
CLASSIFICAZIONE_CORI,
unita_organizzativa,nazione,comune
WHERE
COMPENSO.FL_COMPENSO_CONGUAGLIO = 'N' AND
ti_trat.CD_TRATTAMENTO 			= COMPENSO.CD_TRATTAMENTO AND
ti_trat.DT_INI_VALIDITA			<= COMPENSO.DT_registrazione AND
ti_trat.DT_FIN_VALIDITA			>= COMPENSO.DT_registrazione AND
COMPENSO.CD_TERZO 				= V_ANAGRAFICO_TERZO.CD_TERZO AND
COMPENSO.CD_TIPO_RAPPORTO 		= TIPO_RAPPORTO.CD_TIPO_RAPPORTO AND
TIPO_RAPPORTO.TI_DIPENDENTE_ALTRO = 'D' AND
CONTRIBUTO_RITENUTA.CD_CDS 		  			  = COMPENSO.CD_CDS AND
CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA 	  = COMPENSO.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA.ESERCIZIO 				  = COMPENSO.ESERCIZIO AND
CONTRIBUTO_RITENUTA.PG_COMPENSO 			  = COMPENSO.PG_COMPENSO AND
(CONTRIBUTO_RITENUTA.ALIQUOTA = 0 OR CONTRIBUTO_RITENUTA.ALIQUOTA IS NULL) AND
CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE = 'P' AND
CONTRIBUTO_RITENUTA_DET.CD_CDS 			  	  	   = CONTRIBUTO_RITENUTA.CD_CDS AND
CONTRIBUTO_RITENUTA_DET.CD_UNITA_ORGANIZZATIVA 	   = CONTRIBUTO_RITENUTA.CD_UNITA_ORGANIZZATIVA AND
CONTRIBUTO_RITENUTA_DET.ESERCIZIO 				   = CONTRIBUTO_RITENUTA.ESERCIZIO AND
CONTRIBUTO_RITENUTA_DET.PG_COMPENSO 			   = CONTRIBUTO_RITENUTA.PG_COMPENSO AND
CONTRIBUTO_RITENUTA_DET.CD_CONTRIBUTO_RITENUTA 	   = CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA_DET.TI_ENTE_PERCIPIENTE 	   = CONTRIBUTO_RITENUTA.TI_ENTE_PERCIPIENTE AND
CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA 		   = TIPO_CONTRIBUTO_RITENUTA.CD_CONTRIBUTO_RITENUTA AND
CONTRIBUTO_RITENUTA.DT_INI_VALIDITA 			   = TIPO_CONTRIBUTO_RITENUTA.DT_INI_VALIDITA AND
TIPO_CONTRIBUTO_RITENUTA.CD_CLASSIFICAZIONE_CORI   = CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI AND
CLASSIFICAZIONE_CORI.CD_CLASSIFICAZIONE_CORI IN ('IL', 'PR') and
COMPENSO.FL_SENZA_CALCOLI = 'N' and
pg_missione is Null
 and compenso.cd_unita_organizzativa  = unita_organizzativa.cd_unita_organizzativa
  and nazione.pg_nazione = comune.pg_nazione
 and V_ANAGRAFICO_TERZO.pg_comune_sede = comune.pg_comune;
