--------------------------------------------------------
--  DDL for View V_CONS_COMMESSE_CONTRATTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_COMMESSE_CONTRATTI" ("CD_COMMESSA", "DS_COMMESSA", "CD_PROGETTO", "DS_PROGETTO", "ESERCIZIO_CONTRATTO_PADRE", "STATO_CONTRATTO_PADRE", "PG_CONTRATTO_PADRE", "ESERCIZIO_CONTRATTO", "STATO_CONTRATTO", "PG_CONTRATTO", "OGGETTO_CONTRATTO", "TOTALE_ENTRATE", "TOTALE_SPESE") AS 
  SELECT CD_COMMESSA, DS_COMMESSA, CD_PROGETTO, DS_PROGETTO, ESERCIZIO_CONTRATTO_PADRE,
 STATO_CONTRATTO_PADRE, PG_CONTRATTO_PADRE, ESERCIZIO_CONTRATTO, STATO_CONTRATTO, PG_CONTRATTO,
 OGGETTO_CONTRATTO, sum(TOTALE_ENTRATE), sum(TOTALE_SPESE)
FROM (select
--
-- Date: 09/11/2006
-- Version: 1.2
--
-- Vista per la consultazione del totale dei documenti contabili
-- per Commessa e Contratto
--
-- History:
--
-- Date: 18/04/2005
-- Version: 1.0
-- Creazione
--
-- Date: 18/07/2006
-- Version: 1.1
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Date: 09/11/2006
-- Version: 1.2
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
decode(PROGETTO.CD_PROGETTO,null,modulo.cd_progetto,COMMESSA.CD_PROGETTO) cd_commessa,
decode(PROGETTO.DS_PROGETTO,null,modulo.ds_progetto,COMMESSA.DS_PROGETTO) ds_commessa,
decode(PROGETTO.CD_PROGETTO,null,COMMESSA.cd_progetto,PROGETTO.CD_PROGETTO) CD_PROGETTO,
decode(PROGETTO.DS_PROGETTO,null,COMMESSA.ds_progetto,PROGETTO.DS_PROGETTO) DS_PROGETTO,
CONTRATTO_PADRE.ESERCIZIO ESERCIZIO_CONTRATTO_PADRE,
CONTRATTO_PADRE.STATO STATO_CONTRATTO_PADRE,
CONTRATTO_PADRE.PG_CONTRATTO pg_contratto_padre,
CONTRATTO.ESERCIZIO ESERCIZIO_CONTRATTO,
CONTRATTO.STATO STATO_CONTRATTO,
CONTRATTO.PG_CONTRATTO pg_contratto,
CONTRATTO.OGGETTO oggetto_contratto,
Sum(ACCERTAMENTO_SCAD_VOCE.IM_VOCE) TOTALE_ENTRATE,
0 TOTALE_SPESE
From PROGETTO_GEST PROGETTO, PROGETTO_GEST COMMESSA, PROGETTO_GEST MODULO, CONTRATTO,
     CONTRATTO CONTRATTO_PADRE, ACCERTAMENTO, ACCERTAMENTO_SCADENZARIO, ACCERTAMENTO_SCAD_VOCE,
     v_LINEA_ATTIVITA_valida
Where CONTRATTO.ESERCIZIO = ACCERTAMENTO.ESERCIZIO_CONTRATTO
  And CONTRATTO.PG_CONTRATTO = ACCERTAMENTO.PG_CONTRATTO
  And CONTRATTO.STATO = ACCERTAMENTO.STATO_CONTRATTO
  And ACCERTAMENTO.CD_CDS = ACCERTAMENTO_SCADENZARIO.CD_CDS
  And ACCERTAMENTO.ESERCIZIO = ACCERTAMENTO_SCADENZARIO.ESERCIZIO
  And ACCERTAMENTO.ESERCIZIO_ORIGINALE = ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE
  And ACCERTAMENTO.PG_ACCERTAMENTO = ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO
  	AND (accertamento.esercizio_originale =accertamento.esercizio
                       or (accertamento.cd_tipo_documento_cont ='ACC_RES' and
                       not exists (select 1 from accertamento acc where
                		accertamento.CD_CDS = acc.CD_CDS
             			And accertamento.ESERCIZIO > acc.ESERCIZIO
             			And accertamento.ESERCIZIO_ORIGINALE = acc.ESERCIZIO_ORIGINALE
             			And accertamento.PG_accertamento = acc.PG_accertamento
             			and accertamento.ESERCIZIO_contratto = acc.ESERCIZIO_CONTRATTO
             			And accertamento.STATO_CONTRATTO = acc.STATO_CONTRATTO
             			And accertamento.PG_CONTRATTO = acc.PG_CONTRATTO)))
  And ACCERTAMENTO_SCADENZARIO.CD_CDS = ACCERTAMENTO_SCAD_VOCE.CD_CDS
  And ACCERTAMENTO_SCADENZARIO.ESERCIZIO = ACCERTAMENTO_SCAD_VOCE.ESERCIZIO
  And ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE = ACCERTAMENTO_SCAD_VOCE.ESERCIZIO_ORIGINALE
  And ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO = ACCERTAMENTO_SCAD_VOCE.PG_ACCERTAMENTO
  And ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO_SCADENZARIO = ACCERTAMENTO_SCAD_VOCE.PG_ACCERTAMENTO_SCADENZARIO
  And ACCERTAMENTO_SCAD_VOCE.CD_CENTRO_RESPONSABILITA = v_LINEA_ATTIVITA_valida.CD_CENTRO_RESPONSABILITA
  And ACCERTAMENTO_SCAD_VOCE.CD_LINEA_ATTIVITA = v_LINEA_ATTIVITA_valida.CD_LINEA_ATTIVITA
  And v_LINEA_ATTIVITA_valida.PG_PROGETTO = MODULO.PG_PROGETTO
  and v_LINEA_ATTIVITA_valida.ESERCIZIO= accertamento.esercizio
  And MODULO.ESERCIZIO = ACCERTAMENTO.ESERCIZIO
  And MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO
  And MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO
  And COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO(+)
  And COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO(+)
  And CONTRATTO.ESERCIZIO_PADRE = CONTRATTO_PADRE.ESERCIZIO(+)
  And CONTRATTO.PG_CONTRATTO_PADRE = CONTRATTO_PADRE.PG_CONTRATTO(+)
Group By
decode(PROGETTO.CD_PROGETTO,null,modulo.cd_progetto,COMMESSA.CD_PROGETTO),
decode(PROGETTO.DS_PROGETTO,null,modulo.ds_progetto,COMMESSA.DS_PROGETTO),
decode(PROGETTO.CD_PROGETTO,null,COMMESSA.cd_progetto,PROGETTO.CD_PROGETTO),
decode(PROGETTO.DS_PROGETTO,null,COMMESSA.ds_progetto,PROGETTO.DS_PROGETTO),
CONTRATTO_PADRE.ESERCIZIO,
CONTRATTO_PADRE.STATO,
CONTRATTO_PADRE.PG_CONTRATTO,
CONTRATTO.ESERCIZIO,
CONTRATTO.STATO,
CONTRATTO.PG_CONTRATTO,
CONTRATTO.OGGETTO
Union All
select
decode(PROGETTO.CD_PROGETTO,null,modulo.cd_progetto,COMMESSA.CD_PROGETTO) cd_commessa,
decode(PROGETTO.DS_PROGETTO,null,modulo.ds_progetto,COMMESSA.DS_PROGETTO) ds_commessa,
decode(PROGETTO.CD_PROGETTO,null,COMMESSA.cd_progetto,PROGETTO.CD_PROGETTO) CD_PROGETTO,
decode(PROGETTO.DS_PROGETTO,null,COMMESSA.ds_progetto,PROGETTO.DS_PROGETTO) DS_PROGETTO,
CONTRATTO_PADRE.ESERCIZIO ESERCIZIO_CONTRATTO_PADRE,
CONTRATTO_PADRE.STATO STATO_CONTRATTO_PADRE,
CONTRATTO_PADRE.PG_CONTRATTO pg_contratto_padre,
CONTRATTO.ESERCIZIO ESERCIZIO_CONTRATTO,
CONTRATTO.STATO STATO_CONTRATTO,
CONTRATTO.PG_CONTRATTO pg_contratto,
CONTRATTO.OGGETTO oggetto_contratto,
Sum(ACCERTAMENTO_mod_VOCE.IM_modifica) TOTALE_ENTRATE,
0 TOTALE_SPESE
From PROGETTO_GEST PROGETTO, PROGETTO_GEST COMMESSA, PROGETTO_GEST MODULO, CONTRATTO,
     CONTRATTO CONTRATTO_PADRE, ACCERTAMENTO, ACCERTAMENTO_modifica, ACCERTAMENTO_mod_VOCE,
     v_LINEA_ATTIVITA_valida
Where CONTRATTO.ESERCIZIO = ACCERTAMENTO.ESERCIZIO_CONTRATTO
  And CONTRATTO.PG_CONTRATTO = ACCERTAMENTO.PG_CONTRATTO
  And CONTRATTO.STATO = ACCERTAMENTO.STATO_CONTRATTO
  and accertamento.cd_cds = accertamento_modifica.cd_cds
  AND accertamento.esercizio = accertamento_modifica.esercizio
  AND accertamento.esercizio_originale = accertamento_modifica.esercizio_originale
	AND accertamento.pg_accertamento =  accertamento_modifica.pg_accertamento
  AND accertamento_modifica.cd_cds = accertamento_mod_voce.cd_cds
  AND accertamento_modifica.esercizio = accertamento_mod_voce.esercizio
  AND accertamento_modifica.pg_modifica = accertamento_mod_voce.pg_modifica
  And accertamento_mod_voce.CD_CENTRO_RESPONSABILITA = v_LINEA_ATTIVITA_valida.CD_CENTRO_RESPONSABILITA
  And accertamento_mod_voce.CD_LINEA_ATTIVITA = v_LINEA_ATTIVITA_valida.CD_LINEA_ATTIVITA
  And v_LINEA_ATTIVITA_valida.PG_PROGETTO = MODULO.PG_PROGETTO
  and v_LINEA_ATTIVITA_valida.esercizio = accertamento.esercizio
  And MODULO.ESERCIZIO = ACCERTAMENTO.ESERCIZIO
  And MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO
  And MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO
  And COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO(+)
  And COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO(+)
  And CONTRATTO.ESERCIZIO_PADRE = CONTRATTO_PADRE.ESERCIZIO(+)
  And CONTRATTO.PG_CONTRATTO_PADRE = CONTRATTO_PADRE.PG_CONTRATTO(+)
 	AND exists(select 1 from ACCERTAMENTO acc where
                ACCERTAMENTO.CD_CDS = acc.CD_CDS
             --And ACCERTAMENTO.ESERCIZIO = acc.ESERCIZIO
             And ACCERTAMENTO.ESERCIZIO_ORIGINALE = acc.ESERCIZIO_ORIGINALE
             And ACCERTAMENTO.pg_accertamento = acc.pg_accertamento
             and ACCERTAMENTO.ESERCIZIO_contratto = acc.ESERCIZIO_CONTRATTO
             And ACCERTAMENTO.STATO_contratto = acc.STATO_CONTRATTO
             And ACCERTAMENTO.PG_CONTRATTO = acc.PG_CONTRATTO
             and acc.ESERCIZIO = acc.ESERCIZIO_ORIGINALE )
Group By
decode(PROGETTO.CD_PROGETTO,null,modulo.cd_progetto,COMMESSA.CD_PROGETTO),
decode(PROGETTO.DS_PROGETTO,null,modulo.ds_progetto,COMMESSA.DS_PROGETTO),
decode(PROGETTO.CD_PROGETTO,null,COMMESSA.cd_progetto,PROGETTO.CD_PROGETTO),
decode(PROGETTO.DS_PROGETTO,null,COMMESSA.ds_progetto,PROGETTO.DS_PROGETTO),
CONTRATTO_PADRE.ESERCIZIO,
CONTRATTO_PADRE.STATO,
CONTRATTO_PADRE.PG_CONTRATTO,
CONTRATTO.ESERCIZIO,
CONTRATTO.STATO,
CONTRATTO.PG_CONTRATTO,
CONTRATTO.OGGETTO
Union all
Select
decode(PROGETTO.CD_PROGETTO,null,modulo.cd_progetto,COMMESSA.CD_PROGETTO) cd_commessa,
decode(PROGETTO.DS_PROGETTO,null,modulo.ds_progetto,COMMESSA.DS_PROGETTO) ds_commessa,
decode(PROGETTO.CD_PROGETTO,null,COMMESSA.cd_progetto,PROGETTO.CD_PROGETTO) CD_PROGETTO,
decode(PROGETTO.DS_PROGETTO,null,COMMESSA.ds_progetto,PROGETTO.DS_PROGETTO) DS_PROGETTO,
CONTRATTO_PADRE.ESERCIZIO,
CONTRATTO_PADRE.STATO,
CONTRATTO_PADRE.PG_CONTRATTO,
CONTRATTO.ESERCIZIO,
CONTRATTO.STATO,
CONTRATTO.PG_CONTRATTO,
CONTRATTO.OGGETTO,
0 TOTALE_ENTRATE,
Sum(OBBLIGAZIONE_SCAD_VOCE.IM_VOCE) TOTALE_SPESE
From PROGETTO_GEST PROGETTO, PROGETTO_GEST COMMESSA, PROGETTO_GEST MODULO, CONTRATTO,
     CONTRATTO CONTRATTO_PADRE, OBBLIGAZIONE, OBBLIGAZIONE_SCADENZARIO, OBBLIGAZIONE_SCAD_VOCE,
     v_LINEA_ATTIVITA_valida
Where CONTRATTO.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO_CONTRATTO
  And CONTRATTO.PG_CONTRATTO = OBBLIGAZIONE.PG_CONTRATTO
  And CONTRATTO.STATO = OBBLIGAZIONE.STATO_CONTRATTO
  And OBBLIGAZIONE.CD_CDS = OBBLIGAZIONE_SCADENZARIO.CD_CDS
  And OBBLIGAZIONE.ESERCIZIO = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
  And OBBLIGAZIONE.ESERCIZIO_ORIGINALE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE
  And OBBLIGAZIONE.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE
  AND (obbligazione.esercizio_originale =obbligazione.esercizio
                       or obbligazione.cd_tipo_documento_cont ='OBB_RESIM'
                       or (obbligazione.cd_tipo_documento_cont ='OBB_RES' and
                       not exists (select 1 from obbligazione obb where
                		OBBLIGAZIONE.CD_CDS = obb.CD_CDS
             			And OBBLIGAZIONE.ESERCIZIO > obb.ESERCIZIO
             			And OBBLIGAZIONE.ESERCIZIO_ORIGINALE = obb.ESERCIZIO_ORIGINALE
             			And OBBLIGAZIONE.PG_OBBLIGAZIONE = obb.PG_OBBLIGAZIONE
             			and OBBLIGAZIONE.ESERCIZIO_contratto = obb.ESERCIZIO_CONTRATTO
             			And OBBLIGAZIONE.STATO_CONTRATTO = obb.STATO_CONTRATTO
             			And OBBLIGAZIONE.PG_CONTRATTO = obb.PG_CONTRATTO)))
  And OBBLIGAZIONE_SCADENZARIO.CD_CDS = OBBLIGAZIONE_SCAD_VOCE.CD_CDS
  And OBBLIGAZIONE_SCADENZARIO.ESERCIZIO = OBBLIGAZIONE_SCAD_VOCE.ESERCIZIO
  And OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE = OBBLIGAZIONE_SCAD_VOCE.ESERCIZIO_ORIGINALE
  And OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCAD_VOCE.PG_OBBLIGAZIONE
  And OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO = OBBLIGAZIONE_SCAD_VOCE.PG_OBBLIGAZIONE_SCADENZARIO
  And OBBLIGAZIONE_SCAD_VOCE.CD_CENTRO_RESPONSABILITA = v_LINEA_ATTIVITA_valida.CD_CENTRO_RESPONSABILITA
  And OBBLIGAZIONE_SCAD_VOCE.CD_LINEA_ATTIVITA = v_LINEA_ATTIVITA_valida.CD_LINEA_ATTIVITA
  And v_LINEA_ATTIVITA_valida.PG_PROGETTO = MODULO.PG_PROGETTO
  and v_LINEA_ATTIVITA_valida.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO
  And MODULO.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO
  And MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO
  And MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO
  And COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO(+)
  And COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO(+)
  And CONTRATTO.ESERCIZIO_PADRE = CONTRATTO_PADRE.ESERCIZIO(+)
  And CONTRATTO.PG_CONTRATTO_PADRE = CONTRATTO_PADRE.PG_CONTRATTO(+)
Group By
decode(PROGETTO.CD_PROGETTO,null,modulo.cd_progetto,COMMESSA.CD_PROGETTO),
decode(PROGETTO.DS_PROGETTO,null,modulo.ds_progetto,COMMESSA.DS_PROGETTO),
decode(PROGETTO.CD_PROGETTO,null,COMMESSA.cd_progetto,PROGETTO.CD_PROGETTO),
decode(PROGETTO.DS_PROGETTO,null,COMMESSA.ds_progetto,PROGETTO.DS_PROGETTO),
CONTRATTO_PADRE.ESERCIZIO,
CONTRATTO_PADRE.STATO,
CONTRATTO_PADRE.PG_CONTRATTO,
CONTRATTO.ESERCIZIO,
CONTRATTO.STATO,
CONTRATTO.PG_CONTRATTO,
CONTRATTO.OGGETTO
Union all
Select
decode(PROGETTO.CD_PROGETTO,null,modulo.cd_progetto,COMMESSA.CD_PROGETTO) cd_commessa,
decode(PROGETTO.DS_PROGETTO,null,modulo.ds_progetto,COMMESSA.DS_PROGETTO) ds_commessa,
decode(PROGETTO.CD_PROGETTO,null,COMMESSA.cd_progetto,PROGETTO.CD_PROGETTO) CD_PROGETTO,
decode(PROGETTO.DS_PROGETTO,null,COMMESSA.ds_progetto,PROGETTO.DS_PROGETTO) DS_PROGETTO,
CONTRATTO_PADRE.ESERCIZIO,
CONTRATTO_PADRE.STATO,
CONTRATTO_PADRE.PG_CONTRATTO,
CONTRATTO.ESERCIZIO,
CONTRATTO.STATO,
CONTRATTO.PG_CONTRATTO,
CONTRATTO.OGGETTO,
0 TOTALE_ENTRATE,
Sum(OBBLIGAZIONE_mod_VOCE.IM_modifica) TOTALE_SPESE
From PROGETTO_GEST PROGETTO, PROGETTO_GEST COMMESSA, PROGETTO_GEST MODULO, CONTRATTO,
     CONTRATTO CONTRATTO_PADRE, OBBLIGAZIONE, OBBLIGAZIONE_modifica, OBBLIGAZIONE_mod_VOCE,
     v_LINEA_ATTIVITA_valida
Where CONTRATTO.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO_CONTRATTO
  And CONTRATTO.PG_CONTRATTO = OBBLIGAZIONE.PG_CONTRATTO
  And CONTRATTO.STATO = OBBLIGAZIONE.STATO_CONTRATTO
  AND obbligazione.cd_cds = obbligazione_modifica.cd_cds
  AND obbligazione.esercizio = obbligazione_modifica.esercizio
  AND obbligazione.esercizio_originale =obbligazione_modifica.esercizio_originale
  AND obbligazione.pg_obbligazione = obbligazione_modifica.pg_obbligazione
  AND obbligazione_modifica.cd_cds = obbligazione_mod_voce.cd_cds
  AND obbligazione_modifica.esercizio = obbligazione_mod_voce.esercizio
  AND obbligazione_modifica.pg_modifica = obbligazione_mod_voce.pg_modifica
  And OBBLIGAZIONE_mod_VOCE.CD_CENTRO_RESPONSABILITA = v_LINEA_ATTIVITA_valida.CD_CENTRO_RESPONSABILITA
  And OBBLIGAZIONE_mod_VOCE.CD_LINEA_ATTIVITA = v_LINEA_ATTIVITA_valida.CD_LINEA_ATTIVITA
  And v_LINEA_ATTIVITA_valida.PG_PROGETTO = MODULO.PG_PROGETTO
  AND v_LINEA_ATTIVITA_valida.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO
  And MODULO.ESERCIZIO = OBBLIGAZIONE.ESERCIZIO
  And MODULO.ESERCIZIO_PROGETTO_PADRE = COMMESSA.ESERCIZIO
  And MODULO.PG_PROGETTO_PADRE = COMMESSA.PG_PROGETTO
  And COMMESSA.ESERCIZIO_PROGETTO_PADRE = PROGETTO.ESERCIZIO(+)
  And COMMESSA.PG_PROGETTO_PADRE = PROGETTO.PG_PROGETTO(+)
  And CONTRATTO.ESERCIZIO_PADRE = CONTRATTO_PADRE.ESERCIZIO(+)
  And CONTRATTO.PG_CONTRATTO_PADRE = CONTRATTO_PADRE.PG_CONTRATTO(+)
  -- per evitare che prende le variazioni su impegni già diminuiti nell'importo sull'obbligazione collegato al contratto
  AND exists(select 1 from obbligazione obb where
                OBBLIGAZIONE.CD_CDS = obb.CD_CDS
             --And OBBLIGAZIONE.ESERCIZIO = obb.ESERCIZIO
             And OBBLIGAZIONE.ESERCIZIO_ORIGINALE = obb.ESERCIZIO_ORIGINALE
             And OBBLIGAZIONE.PG_OBBLIGAZIONE = obb.PG_OBBLIGAZIONE
             and OBBLIGAZIONE.ESERCIZIO_contratto = obb.ESERCIZIO_CONTRATTO
             And OBBLIGAZIONE.STATO_CONTRATTO = obb.STATO_CONTRATTO
             And OBBLIGAZIONE.PG_CONTRATTO = obb.PG_CONTRATTO
             and (obb.ESERCIZIO = obb.ESERCIZIO_ORIGINALE or
								 obb.cd_tipo_documento_cont ='OBB_RESIM'))
Group By
decode(PROGETTO.CD_PROGETTO,null,modulo.cd_progetto,COMMESSA.CD_PROGETTO),
decode(PROGETTO.DS_PROGETTO,null,modulo.ds_progetto,COMMESSA.DS_PROGETTO),
decode(PROGETTO.CD_PROGETTO,null,COMMESSA.cd_progetto,PROGETTO.CD_PROGETTO),
decode(PROGETTO.DS_PROGETTO,null,COMMESSA.ds_progetto,PROGETTO.DS_PROGETTO),
CONTRATTO_PADRE.ESERCIZIO,
CONTRATTO_PADRE.STATO,
CONTRATTO_PADRE.PG_CONTRATTO,
CONTRATTO.ESERCIZIO,
CONTRATTO.STATO,
CONTRATTO.PG_CONTRATTO,
CONTRATTO.OGGETTO)
group by CD_COMMESSA, DS_COMMESSA, CD_PROGETTO, DS_PROGETTO, ESERCIZIO_CONTRATTO_PADRE,
 STATO_CONTRATTO_PADRE, PG_CONTRATTO_PADRE, ESERCIZIO_CONTRATTO, STATO_CONTRATTO, PG_CONTRATTO,
 OGGETTO_CONTRATTO;
