--------------------------------------------------------
--  DDL for View V_CONS_PDGG_SPE_BIL_IST_DIP_FN
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PDGG_SPE_BIL_IST_DIP_FN" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "PG_MODULO", "CD_MODULO", "DS_MODULO", "CD_TIPO_MODULO", "DS_TIPO_MODULO", "PG_COMMESSA", "CD_COMMESSA", "DS_COMMESSA", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO", "CD_CDR_ASSEGNATARIO", "DS_CDR_ASSEGNATARIO", "CD_LINEA_ATTIVITA", "DS_LINEA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "IM_DEC_IST_INT", "IM_DEC_IST_EST", "IM_DEC_AREA_INT", "IM_DEC_AREA_EST", "TRATT_ECON_INT", "TRATT_ECON_EST", "IM_ACC_ALTRE_SP_INT", "IM_PAGAMENTI") AS 
  Select PREV_GEST.ESERCIZIO,
       PREV_GEST.CD_CENTRO_RESPONSABILITA,
       CDR.DS_CDR,
       PREV_GEST.CD_CLASSIFICAZIONE,
       PREV_GEST.DS_CLASSIFICAZIONE,
       PREV_GEST.NR_LIVELLO,
       PREV_GEST.CD_LIVELLO1,
       PREV_GEST.CD_LIVELLO2,
       PREV_GEST.CD_LIVELLO3,
       PREV_GEST.CD_LIVELLO4,
       PREV_GEST.CD_LIVELLO5,
       PREV_GEST.CD_LIVELLO6,
       PREV_GEST.CD_LIVELLO7,
       MODU.PG_PROGETTO PG_MODULO,
       MODU.CD_PROGETTO CD_MODULO,
       MODU.DS_PROGETTO DS_MODULO,
       MODU.CD_TIPO_PROGETTO CD_TIPO_MODULO,
       TIPO_PROGETTO.DS_TIPO_PROGETTO DS_TIPO_MODULO,
       COMM.PG_PROGETTO PG_COMMESSA,
       COMM.CD_PROGETTO CD_COMMESSA,
       COMM.DS_PROGETTO DS_COMMESSA,
       PROG.PG_PROGETTO,
       PROG.CD_PROGETTO,
       PROG.DS_PROGETTO,
       PROG.CD_DIPARTIMENTO,
       DIP.DS_DIPARTIMENTO,
       PREV_GEST.CD_CDR_ASSEGNATARIO,
       CDR_ASS.DS_CDR,
       PREV_GEST.CD_LINEA_ATTIVITA,
       LA.DENOMINAZIONE,
       PREV_GEST.TI_APPARTENENZA,
       PREV_GEST.TI_GESTIONE,
       PREV_GEST.CD_ELEMENTO_VOCE,
       EV.DS_ELEMENTO_VOCE,
       PREV_GEST.IM_DEC_IST_INT,
       PREV_GEST.IM_DEC_IST_EST,
       PREV_GEST.IM_DEC_AREA_INT,
       PREV_GEST.IM_DEC_AREA_EST,
       PREV_GEST.TRATT_ECON_INT,
       PREV_GEST.TRATT_ECON_EST,
       PREV_GEST.IM_ACC_ALTRE_SP_INT,
       PREV_GEST.IM_PAGAMENTI
From   CDR, CDR CDR_ASS, PROGETTO_GEST MODU, PROGETTO_GEST COMM, PROGETTO_GEST PROG,
       TIPO_PROGETTO, DIPARTIMENTO DIP, LINEA_ATTIVITA LA, ELEMENTO_VOCE EV,
      (Select PDG_SPE.ESERCIZIO, PDG_SPE.CD_CENTRO_RESPONSABILITA, PDG_SPE.PG_PROGETTO,
              CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO, CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6, CD_LIVELLO7,
              PDG_SPE.CD_CDR_ASSEGNATARIO, PDG_SPE.CD_LINEA_ATTIVITA,
              PDG_SPE.TI_APPARTENENZA, PDG_SPE.TI_GESTIONE, PDG_SPE.CD_ELEMENTO_VOCE,
              SUM(PDG_SPE.IM_SPESE_GEST_DECENTRATA_INT)  IM_DEC_IST_INT,
              SUM(PDG_SPE.IM_SPESE_GEST_DECENTRATA_EST)  IM_DEC_IST_EST,
              0  IM_DEC_AREA_INT,
              0  IM_DEC_AREA_EST,
              0  TRATT_ECON_INT,
              0  TRATT_ECON_EST,
              SUM(PDG_SPE.IM_SPESE_GEST_ACCENTRATA_INT) + SUM(PDG_SPE.IM_SPESE_GEST_ACCENTRATA_EST) IM_ACC_ALTRE_SP_INT,
              SUM(IM_PAGAMENTI) IM_PAGAMENTI
       From   PDG_MODULO_SPESE_GEST PDG_SPE, V_CLASSIFICAZIONE_VOCI CLA, UNITA_ORGANIZZATIVA AREA
       Where  PDG_SPE.ID_CLASSIFICAZIONE = CLA.ID_CLASSIFICAZIONE AND
              PDG_SPE.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA AND
              NVL(CLA.CDR_ACCENTRATORE, 'xxx') != CNRCTB020.getCdCDRPersonale(PDG_SPE.ESERCIZIO) And
              AREA.CD_TIPO_UNITA != 'AREA' And
              PDG_SPE.FL_SOLA_LETTURA = 'N'
       Group By PDG_SPE.ESERCIZIO, PDG_SPE.CD_CENTRO_RESPONSABILITA, PDG_SPE.PG_PROGETTO,
                CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO, CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6, CD_LIVELLO7,
                PDG_SPE.CD_CDR_ASSEGNATARIO,
                PDG_SPE.CD_LINEA_ATTIVITA,
                PDG_SPE.TI_APPARTENENZA, PDG_SPE.TI_GESTIONE, PDG_SPE.CD_ELEMENTO_VOCE
       Union All
       -- ISTITUTI (PERSONALE)
       Select PDG_SPE.ESERCIZIO, PDG_SPE.CD_CENTRO_RESPONSABILITA, PDG_SPE.PG_PROGETTO,
              CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO, CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6, CD_LIVELLO7,
              PDG_SPE.CD_CDR_ASSEGNATARIO, PDG_SPE.CD_LINEA_ATTIVITA,
              PDG_SPE.TI_APPARTENENZA, PDG_SPE.TI_GESTIONE, PDG_SPE.CD_ELEMENTO_VOCE,
              0 IM_DEC_IST_INT,
              0 IM_DEC_IST_EST,
              0 IM_DEC_AREA_INT,
              0 IM_DEC_AREA_EST,
              SUM(PDG_SPE.IM_SPESE_GEST_DECENTRATA_INT) + SUM(PDG_SPE.IM_SPESE_GEST_ACCENTRATA_INT) TRATT_ECON_INT,
              SUM(PDG_SPE.IM_SPESE_GEST_DECENTRATA_EST) + SUM(PDG_SPE.IM_SPESE_GEST_ACCENTRATA_EST) TRATT_ECON_EST,
              0 IM_ACC_ALTRE_SP_INT,
              0 IM_PAGAMENTI
       From   PDG_MODULO_SPESE_GEST PDG_SPE, V_CLASSIFICAZIONE_VOCI CLA, UNITA_ORGANIZZATIVA AREA
       Where  PDG_SPE.ID_CLASSIFICAZIONE = CLA.ID_CLASSIFICAZIONE AND
              PDG_SPE.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA AND
              NVL(CLA.CDR_ACCENTRATORE, 'xxx') = CNRCTB020.getCdCDRPersonale(PDG_SPE.ESERCIZIO) AND
              PDG_SPE.CD_CDR_ASSEGNATARIO != CNRCTB020.getCdCDRPersonale(PDG_SPE.ESERCIZIO) AND
              AREA.CD_TIPO_UNITA != 'AREA' AND
              PDG_SPE.FL_SOLA_LETTURA = 'Y'
       Group BY PDG_SPE.ESERCIZIO, PDG_SPE.CD_CENTRO_RESPONSABILITA, PDG_SPE.PG_PROGETTO,
              CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO, CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6, CD_LIVELLO7,
              PDG_SPE.CD_CDR_ASSEGNATARIO, PDG_SPE.CD_LINEA_ATTIVITA, PDG_SPE.TI_APPARTENENZA, PDG_SPE.TI_GESTIONE, PDG_SPE.CD_ELEMENTO_VOCE
       Union All
       -- AREE
       Select PDG_SPE.ESERCIZIO, PDG_SPE.CD_CENTRO_RESPONSABILITA, PDG_SPE.PG_PROGETTO,
              CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO, CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6, CD_LIVELLO7,
              PDG_SPE.CD_CDR_ASSEGNATARIO, PDG_SPE.CD_LINEA_ATTIVITA,
              PDG_SPE.TI_APPARTENENZA, PDG_SPE.TI_GESTIONE, PDG_SPE.CD_ELEMENTO_VOCE,
              0 IM_DEC_IST_INT,
              0 IM_DEC_IST_EST,
              SUM(PDG_SPE.IM_SPESE_GEST_DECENTRATA_INT)  IM_DEC_AREA_INT,
              SUM(PDG_SPE.IM_SPESE_GEST_DECENTRATA_EST)  IM_DEC_AREA_EST,
              0  TRATT_ECON_INT,
              0  TRATT_ECON_EST,
              0  IM_ACC_ALTRE_SP_INT,
              SUM(IM_PAGAMENTI) IM_PAGAMENTI
       From   PDG_MODULO_SPESE_GEST PDG_SPE, V_CLASSIFICAZIONE_VOCI CLA, UNITA_ORGANIZZATIVA AREA
       Where  PDG_SPE.ID_CLASSIFICAZIONE = CLA.ID_CLASSIFICAZIONE AND
              PDG_SPE.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA AND
              AREA.CD_TIPO_UNITA = 'AREA' AND
              PDG_SPE.FL_SOLA_LETTURA = 'N'
       Group By PDG_SPE.ESERCIZIO, PDG_SPE.CD_CENTRO_RESPONSABILITA, PDG_SPE.PG_PROGETTO,
                CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO, CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6, CD_LIVELLO7,
                PDG_SPE.CD_CDR_ASSEGNATARIO, PDG_SPE.CD_LINEA_ATTIVITA,
                PDG_SPE.TI_APPARTENENZA, PDG_SPE.TI_GESTIONE, PDG_SPE.CD_ELEMENTO_VOCE
       Union All
       -- TRATTAMENTO ECONOMICO DEL PERSONALE
       Select PDG_SPE.ESERCIZIO, PDG_SPE.CD_CENTRO_RESPONSABILITA, PDG_SPE.PG_PROGETTO,
              CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO, CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6, CD_LIVELLO7,
              PDG_SPE.CD_CDR_ASSEGNATARIO, PDG_SPE.CD_LINEA_ATTIVITA,
              PDG_SPE.TI_APPARTENENZA, PDG_SPE.TI_GESTIONE, PDG_SPE.CD_ELEMENTO_VOCE,
              0  IM_DEC_IST_INT,
              0  IM_DEC_IST_EST,
              0  IM_DEC_AREA_INT,
              0  IM_DEC_AREA_EST,
              SUM(PDG_SPE.IM_SPESE_GEST_ACCENTRATA_INT)   TRATT_ECON_INT,
              SUM(PDG_SPE.IM_SPESE_GEST_ACCENTRATA_EST)   TRATT_ECON_EST,
              0  IM_ACC_ALTRE_SP_INT,
              SUM(IM_PAGAMENTI) IM_PAGAMENTI
       From   PDG_MODULO_SPESE_GEST PDG_SPE, V_CLASSIFICAZIONE_VOCI CLA, UNITA_ORGANIZZATIVA AREA
       Where  PDG_SPE.ID_CLASSIFICAZIONE = CLA.ID_CLASSIFICAZIONE AND
              PDG_SPE.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA AND
              NVL(PDG_SPE.CD_CDR_ASSEGNATARIO, 'xxx') = CNRCTB020.getCdCDRPersonale(PDG_SPE.ESERCIZIO)
       Group BY PDG_SPE.ESERCIZIO, PDG_SPE.CD_CENTRO_RESPONSABILITA, PDG_SPE.PG_PROGETTO,
              CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO, CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5, CD_LIVELLO6, CD_LIVELLO7,
              PDG_SPE.CD_CDR_ASSEGNATARIO, PDG_SPE.CD_LINEA_ATTIVITA,
              PDG_SPE.TI_APPARTENENZA, PDG_SPE.TI_GESTIONE, PDG_SPE.CD_ELEMENTO_VOCE) PREV_GEST
Where  PREV_GEST.CD_CDR_ASSEGNATARIO = CDR_ASS.CD_CENTRO_RESPONSABILITA And
       PREV_GEST.CD_CENTRO_RESPONSABILITA = CDR.CD_CENTRO_RESPONSABILITA AND
       PREV_GEST.PG_PROGETTO = MODU.PG_PROGETTO AND
       MODU.ESERCIZIO = PREV_GEST.ESERCIZIO And
       MODU.ESERCIZIO_PROGETTO_PADRE = COMM.ESERCIZIO AND
       MODU.PG_PROGETTO_PADRE = COMM.PG_PROGETTO AND
       COMM.ESERCIZIO_PROGETTO_PADRE = PROG.ESERCIZIO AND
       COMM.PG_PROGETTO_PADRE = PROG.PG_PROGETTO AND
       LA.CD_CENTRO_RESPONSABILITA = PREV_GEST.CD_CDR_ASSEGNATARIO AND
       LA.CD_LINEA_ATTIVITA = PREV_GEST.CD_LINEA_ATTIVITA AND
       EV.ESERCIZIO         = PREV_GEST.ESERCIZIO        AND
       EV.TI_APPARTENENZA   = PREV_GEST.TI_APPARTENENZA  AND
       EV.TI_GESTIONE       = PREV_GEST.TI_GESTIONE      AND
       EV.CD_ELEMENTO_VOCE  = PREV_GEST.CD_ELEMENTO_VOCE AND
       MODU.CD_TIPO_PROGETTO = TIPO_PROGETTO.CD_TIPO_PROGETTO AND
       DIP.CD_DIPARTIMENTO = PROG.CD_DIPARTIMENTO;
