--------------------------------------------------------
--  DDL for View V_CONS_PDGP_PDGG_SPE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PDGP_PDGG_SPE" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "ID_CLASSIFICAZIONE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "CD_CDS_AREA", "PG_DETTAGLIO", "CD_COFOG", "CD_MISSIONE", "IM_SPESE_GEST_DEC_INT_PDGP", "IM_SPESE_GEST_DEC_EST_PDGP", "IM_SPESE_GEST_ACC_INT_PDGP", "IM_SPESE_GEST_ACC_EST_PDGP", "IM_SPESE_GEST_DEC_INT_PDGG", "IM_SPESE_GEST_DEC_EST_PDGG", "IM_SPESE_GEST_ACC_INT_PDGG", "IM_SPESE_GEST_ACC_EST_PDGG", "IM_PAGAMENTI_PDGG", "IM_SPESE_GEST_DEC_INT_DA_RIP", "IM_SPESE_GEST_DEC_EST_DA_RIP", "IM_SPESE_GEST_ACC_INT_DA_RIP", "IM_SPESE_GEST_ACC_EST_DA_RIP") AS 
  Select
--
-- Date: 13/11/2006
-- Version: 1.1
--
-- Vista CONSULTAZIONE Entrata Piano di Gestione per Area
--
-- History:
--
-- Date: 01/01/2006
-- Version: 1.0
-- Creazione
--
-- Date: 13/11/2006
-- Version: 1.1
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
ESERCIZIO, CD_CENTRO_RESPONSABILITA, DS_CDR, PG_PROGETTO, CD_PROGETTO,
       DS_PROGETTO, ID_CLASSIFICAZIONE, CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, CD_CDS_AREA,pg_dettaglio,cd_cofog,cd_missione,
       IM_SPESE_GEST_DEC_INT_PDGP, IM_SPESE_GEST_DEC_EST_PDGP, IM_SPESE_GEST_ACC_INT_PDGP, IM_SPESE_GEST_ACC_EST_PDGP, IM_SPESE_GEST_DEC_INT_PDGG,
       IM_SPESE_GEST_DEC_EST_PDGG, IM_SPESE_GEST_ACC_INT_PDGG, IM_SPESE_GEST_ACC_EST_PDGG, IM_PAGAMENTI_PDGG,
       (IM_SPESE_GEST_DEC_INT_PDGP - IM_SPESE_GEST_DEC_INT_PDGG) IM_SPESE_GEST_DEC_INT_DA_RIP,
       (IM_SPESE_GEST_DEC_EST_PDGP - IM_SPESE_GEST_DEC_EST_PDGG) IM_SPESE_GEST_DEC_EST_DA_RIP,
       (IM_SPESE_GEST_ACC_INT_PDGP - IM_SPESE_GEST_ACC_INT_PDGG) IM_SPESE_GEST_ACC_INT_DA_RIP,
       (IM_SPESE_GEST_ACC_EST_PDGP - IM_SPESE_GEST_ACC_EST_PDGG) IM_SPESE_GEST_ACC_EST_DA_RIP
From (Select PDGP.ESERCIZIO, PDGP.CD_CENTRO_RESPONSABILITA, B.DS_CDR, PDGP.PG_PROGETTO, D.CD_PROGETTO, D.DS_PROGETTO,
             PDGP.ID_CLASSIFICAZIONE, C.CD_CLASSIFICAZIONE, C.DS_CLASSIFICAZIONE, PDGP.CD_CDS_AREA,PDGP.pg_dettaglio,PDGP.cd_cofog,PDGP.cd_missione,
             NVL(PDGP.IM_SPESE_GEST_DECENTRATA_INT, 0) IM_SPESE_GEST_DEC_INT_PDGP,
             NVL(PDGP.IM_SPESE_GEST_DECENTRATA_EST, 0) IM_SPESE_GEST_DEC_EST_PDGP,
             NVL(PDGP.IM_SPESE_GEST_ACCENTRATA_INT, 0) IM_SPESE_GEST_ACC_INT_PDGP,
             NVL(PDGP.IM_SPESE_GEST_ACCENTRATA_EST, 0) IM_SPESE_GEST_ACC_EST_PDGP,
             (SELECT NVL(SUM(IM_SPESE_GEST_DECENTRATA_INT), 0)
              FROM PDG_MODULO_SPESE_GEST PDGG, V_STRUTTURA_ORGANIZZATIVA A, V_STRUTTURA_ORGANIZZATIVA B
              WHERE PDGG.ESERCIZIO = PDGP.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = PDGP.CD_CENTRO_RESPONSABILITA
              AND   PDGG.PG_PROGETTO = PDGP.PG_PROGETTO
              AND   PDGG.ID_CLASSIFICAZIONE = PDGP.ID_CLASSIFICAZIONE
              AND   PDGG.CD_CDS_AREA = PDGP.CD_CDS_AREA
              AND   PDGG.PG_DETTAGLIO = PDGP.PG_DETTAGLIO
              AND   PDGG.ESERCIZIO = A.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = A.CD_ROOT
              AND   PDGG.ESERCIZIO = B.ESERCIZIO
              AND   PDGG.CD_CDR_ASSEGNATARIO = B.CD_ROOT
              AND   A.CD_CDS = B.CD_CDS) IM_SPESE_GEST_DEC_INT_PDGG,
             (SELECT NVL(SUM(IM_SPESE_GEST_DECENTRATA_EST), 0)
              FROM PDG_MODULO_SPESE_GEST PDGG, V_STRUTTURA_ORGANIZZATIVA A, V_STRUTTURA_ORGANIZZATIVA B
              WHERE PDGG.ESERCIZIO = PDGP.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = PDGP.CD_CENTRO_RESPONSABILITA
              AND   PDGG.PG_PROGETTO = PDGP.PG_PROGETTO
              AND   PDGG.ID_CLASSIFICAZIONE = PDGP.ID_CLASSIFICAZIONE
              AND   PDGG.CD_CDS_AREA = PDGP.CD_CDS_AREA
              AND   PDGG.PG_DETTAGLIO = PDGP.PG_DETTAGLIO
              AND   PDGG.ESERCIZIO = A.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = A.CD_ROOT
              AND   PDGG.ESERCIZIO = B.ESERCIZIO
              AND   PDGG.CD_CDR_ASSEGNATARIO = B.CD_ROOT
              AND   A.CD_CDS = B.CD_CDS) IM_SPESE_GEST_DEC_EST_PDGG,
             (SELECT NVL(SUM(IM_SPESE_GEST_ACCENTRATA_INT), 0)
              FROM PDG_MODULO_SPESE_GEST PDGG, V_STRUTTURA_ORGANIZZATIVA A, V_STRUTTURA_ORGANIZZATIVA B
              WHERE PDGG.ESERCIZIO = PDGP.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = PDGP.CD_CENTRO_RESPONSABILITA
              AND   PDGG.PG_PROGETTO = PDGP.PG_PROGETTO
              AND   PDGG.ID_CLASSIFICAZIONE = PDGP.ID_CLASSIFICAZIONE
              AND   PDGG.CD_CDS_AREA = PDGP.CD_CDS_AREA
              AND   PDGG.PG_DETTAGLIO = PDGP.PG_DETTAGLIO
              AND   PDGG.ESERCIZIO = A.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = A.CD_ROOT
              AND   PDGG.ESERCIZIO = B.ESERCIZIO
              AND   PDGG.CD_CDR_ASSEGNATARIO = B.CD_ROOT
              AND   A.CD_CDS = B.CD_CDS) IM_SPESE_GEST_ACC_INT_PDGG,
             (SELECT NVL(SUM(IM_SPESE_GEST_ACCENTRATA_EST), 0)
              FROM PDG_MODULO_SPESE_GEST PDGG, V_STRUTTURA_ORGANIZZATIVA A, V_STRUTTURA_ORGANIZZATIVA B
              WHERE PDGG.ESERCIZIO = PDGP.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = PDGP.CD_CENTRO_RESPONSABILITA
              AND   PDGG.PG_PROGETTO = PDGP.PG_PROGETTO
              AND   PDGG.ID_CLASSIFICAZIONE = PDGP.ID_CLASSIFICAZIONE
              AND   PDGG.CD_CDS_AREA = PDGP.CD_CDS_AREA
              AND   PDGG.PG_DETTAGLIO = PDGP.PG_DETTAGLIO
              AND   PDGG.ESERCIZIO = A.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = A.CD_ROOT
              AND   PDGG.ESERCIZIO = B.ESERCIZIO
              AND   PDGG.CD_CDR_ASSEGNATARIO = B.CD_ROOT
              AND   A.CD_CDS = B.CD_CDS) IM_SPESE_GEST_ACC_EST_PDGG,
             (SELECT NVL(SUM(IM_PAGAMENTI), 0)
              FROM PDG_MODULO_SPESE_GEST PDGG, V_STRUTTURA_ORGANIZZATIVA A, V_STRUTTURA_ORGANIZZATIVA B
              WHERE PDGG.ESERCIZIO = PDGP.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = PDGP.CD_CENTRO_RESPONSABILITA
              AND   PDGG.PG_PROGETTO = PDGP.PG_PROGETTO
              AND   PDGG.ID_CLASSIFICAZIONE = PDGP.ID_CLASSIFICAZIONE
              AND   PDGG.CD_CDS_AREA = PDGP.CD_CDS_AREA
              AND   PDGG.PG_DETTAGLIO = PDGP.PG_DETTAGLIO
              AND   PDGG.ESERCIZIO = A.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = A.CD_ROOT
              AND   PDGG.ESERCIZIO = B.ESERCIZIO
              AND   PDGG.CD_CDR_ASSEGNATARIO = B.CD_ROOT
              AND   A.CD_CDS = B.CD_CDS) IM_PAGAMENTI_PDGG
      From PDG_MODULO_SPESE PDGP, CDR B, V_CLASSIFICAZIONE_VOCI C, PROGETTO_PREV D
      Where PDGP.CD_CENTRO_RESPONSABILITA = B.CD_CENTRO_RESPONSABILITA
      And   PDGP.ID_CLASSIFICAZIONE = C.ID_CLASSIFICAZIONE
      And   PDGP.PG_PROGETTO = D.PG_PROGETTO
      And   D.ESERCIZIO = PDGP.ESERCIZIO
order by     PDGP.ESERCIZIO, PDGP.CD_CENTRO_RESPONSABILITA,PDGP.PG_PROGETTO,
      PDGP.ID_CLASSIFICAZIONE,PDGP.CD_CDS_AREA,PDGP.pg_dettaglio);
