--------------------------------------------------------
--  DDL for View V_CONS_PDG_ETR_BIL_IST_DIP_FN
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PDG_ETR_BIL_IST_DIP_FN" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "PG_MODULO", "CD_MODULO", "DS_MODULO", "CD_TIPO_MODULO", "DS_TIPO_MODULO", "PG_COMMESSA", "CD_COMMESSA", "DS_COMMESSA", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO", "CD_TERZO_FINANZIATORE", "DS_DETTAGLIO", "TOT_FINANZIAMENTO", "TOT_ENT_IST_A1", "TOT_ENT_AREE_A1", "TOT_ENT_IST_A2", "TOT_ENT_AREE_A2", "TOT_ENT_IST_A3", "TOT_ENT_AREE_A3") AS 
  Select PREV_ENT.ESERCIZIO,
       PREV_ENT.CD_CENTRO_RESPONSABILITA,
       CDR.DS_CDR,
       CD_CLASSIFICAZIONE,
       DS_CLASSIFICAZIONE,
       NR_LIVELLO,
       CD_LIVELLO1,
       CD_LIVELLO2,
       CD_LIVELLO3,
       CD_LIVELLO4,
       CD_LIVELLO5,
       CD_LIVELLO6,
       CD_LIVELLO7,
       MODU.PG_PROGETTO PG_MODULO,
       MODU.CD_PROGETTO CD_MODULO,
       MODU.DS_PROGETTO DS_MODULO,
       MODU.CD_TIPO_PROGETTO CD_TIPO_MODULO,
       TIPO_PROGETTO.DS_TIPO_PROGETTO DS_TIPO_MODULO,
       COMM.PG_PROGETTO PG_COMMESSA,
       COMM.CD_PROGETTO CD_COMMESSA,
       COMM.DS_PROGETTO DS_COMMESSA,
       PROG.PG_PROGETTO,
       PROG.CD_PROGETTO,
       PROG.DS_PROGETTO,
       PROG.CD_DIPARTIMENTO,
       DIP.DS_DIPARTIMENTO,
       PREV_ENT.CD_TERZO_FINANZIATORE,
       PREV_ENT.DS_DETTAGLIO,
       PREV_ENT.TOT_FINANZIAMENTO,
       PREV_ENT.TOT_ENT_IST_A1,
       PREV_ENT.TOT_ENT_AREE_A1,
       PREV_ENT.TOT_ENT_IST_A2,
       PREV_ENT.TOT_ENT_AREE_A2,
       PREV_ENT.TOT_ENT_IST_A3,
       PREV_ENT.TOT_ENT_AREE_A3
From V_CLASSIFICAZIONE_VOCI CLA, CDR, PROGETTO_PREV MODU, PROGETTO_PREV COMM, PROGETTO_PREV PROG, TIPO_PROGETTO, DIPARTIMENTO DIP,
    (Select PDG.ESERCIZIO, PDG.CD_CENTRO_RESPONSABILITA, PDG.PG_PROGETTO, PDG.ID_CLASSIFICAZIONE,
            PDG.CD_TERZO CD_TERZO_FINANZIATORE,
            DS_DETTAGLIO,
            IM_ENTRATA_TOT     TOT_FINANZIAMENTO,
            Sum(IM_ENTRATA)    TOT_ENT_IST_A1,
            0                  TOT_ENT_AREE_A1,
            Sum(IM_ENTRATA_A2) TOT_ENT_IST_A2,
            0                  TOT_ENT_AREE_A2,
            Sum(IM_ENTRATA_A3) TOT_ENT_IST_A3,
            0                  TOT_ENT_AREE_A3
     From   PDG_MODULO_ENTRATE PDG, UNITA_ORGANIZZATIVA AREA
     Where  PDG.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA AND
            AREA.CD_TIPO_UNITA != 'AREA'
     Group By PDG.ESERCIZIO, PDG.CD_CENTRO_RESPONSABILITA, PDG.PG_PROGETTO, PDG.ID_CLASSIFICAZIONE, PDG.CD_TERZO, DS_DETTAGLIO, IM_ENTRATA_TOT
     Union All
     Select PDG.ESERCIZIO, PDG.CD_CENTRO_RESPONSABILITA, PDG.PG_PROGETTO, PDG.ID_CLASSIFICAZIONE, PDG.CD_TERZO CD_TERZO_FINANZIATORE,
            DS_DETTAGLIO,
            IM_ENTRATA_TOT TOT_FINANZIAMENTO,
            0 TOT_ENT_IST_A1,
            Sum(IM_ENTRATA)    TOT_ENT_AREE_A1,
            0 TOT_ENT_IST_A2,
            Sum(IM_ENTRATA_A2) TOT_ENT_AREE_A2,
            0 TOT_ENT_IST_A3,
            Sum(IM_ENTRATA_A3) TOT_ENT_AREE_A3
     From   PDG_MODULO_ENTRATE PDG, UNITA_ORGANIZZATIVA AREA
     Where  PDG.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA AND
            AREA.CD_TIPO_UNITA = 'AREA'
     Group By PDG.ESERCIZIO, PDG.CD_CENTRO_RESPONSABILITA, PDG.PG_PROGETTO, PDG.ID_CLASSIFICAZIONE, PDG.CD_TERZO, DS_DETTAGLIO, IM_ENTRATA_TOT) PREV_ENT
Where       PREV_ENT.ID_CLASSIFICAZIONE = CLA.ID_CLASSIFICAZIONE And
            PREV_ENT.CD_CENTRO_RESPONSABILITA = CDR.CD_CENTRO_RESPONSABILITA AND
            PREV_ENT.PG_PROGETTO = MODU.PG_PROGETTO And
            MODU.ESERCIZIO = PREV_ENT.ESERCIZIO And
            MODU.ESERCIZIO_PROGETTO_PADRE = COMM.ESERCIZIO And
            MODU.PG_PROGETTO_PADRE = COMM.PG_PROGETTO And
            COMM.ESERCIZIO_PROGETTO_PADRE = PROG.ESERCIZIO And
            COMM.PG_PROGETTO_PADRE = PROG.PG_PROGETTO And
            MODU.CD_TIPO_PROGETTO = TIPO_PROGETTO.CD_TIPO_PROGETTO And
            DIP.CD_DIPARTIMENTO = PROG.CD_DIPARTIMENTO;
