--------------------------------------------------------
--  DDL for View V_CONS_PDGP_PDGG_ETR
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PDGP_PDGG_ETR" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "CD_NATURA", "ID_CLASSIFICAZIONE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "CD_CDS_AREA", "PG_DETTAGLIO", "CD_TERZO", "DS_DETTAGLIO", "IM_ENTRATA_TOT_PDGP", "IM_ENTRATA_PDGP", "IM_ENTRATA_PDGG", "IM_INCASSI_PDGG", "IM_ENTRATA_DA_RIP") AS 
  Select
--
-- Date: 13/11/2006
-- Version: 1.1
--
-- Vista CONSULTAZIONE Entrata Piano di Gestione per Area
--
-- History:
--
-- Date: 01/01/2006
-- Version: 1.0
-- Creazione
--
-- Date: 13/11/2006
-- Version: 1.1
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
ESERCIZIO, CD_CENTRO_RESPONSABILITA, DS_CDR, PG_PROGETTO, CD_PROGETTO,
       DS_PROGETTO, CD_NATURA, ID_CLASSIFICAZIONE, CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE,
       CD_CDS_AREA, PG_DETTAGLIO, CD_TERZO, DS_DETTAGLIO, IM_ENTRATA_TOT,
       IM_ENTRATA_PDGP, IM_ENTRATA_PDGG, IM_INCASSI_PDGG, (IM_ENTRATA_PDGP - IM_ENTRATA_PDGG) IM_ENTRATA_DA_RIP
From (Select PDGP.ESERCIZIO, PDGP.CD_CENTRO_RESPONSABILITA, B.DS_CDR, PDGP.PG_PROGETTO, D.CD_PROGETTO,
             D.DS_PROGETTO, PDGP.CD_NATURA, PDGP.ID_CLASSIFICAZIONE, C.CD_CLASSIFICAZIONE, C.DS_CLASSIFICAZIONE,
             PDGP.CD_CDS_AREA, PDGP.PG_DETTAGLIO, PDGP.CD_TERZO, PDGP.DS_DETTAGLIO, PDGP.IM_ENTRATA_TOT,
             Nvl(PDGP.IM_ENTRATA, 0) IM_ENTRATA_PDGP,
             (SELECT NVL(SUM(IM_ENTRATA), 0) FROM PDG_MODULO_ENTRATE_GEST PDGG
              WHERE PDGG.ESERCIZIO = PDGP.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = PDGP.CD_CENTRO_RESPONSABILITA
              AND   PDGG.PG_PROGETTO = PDGP.PG_PROGETTO
              AND   PDGG.CD_NATURA = PDGP.CD_NATURA
              AND   PDGG.ID_CLASSIFICAZIONE = PDGP.ID_CLASSIFICAZIONE
              AND   PDGG.CD_CDS_AREA = PDGP.CD_CDS_AREA
              AND   PDGG.PG_DETTAGLIO = PDGP.PG_DETTAGLIO) IM_ENTRATA_PDGG,
             (SELECT NVL(SUM(IM_INCASSI), 0) FROM PDG_MODULO_ENTRATE_GEST PDGG
              WHERE PDGG.ESERCIZIO = PDGP.ESERCIZIO
              AND   PDGG.CD_CENTRO_RESPONSABILITA = PDGP.CD_CENTRO_RESPONSABILITA
              AND   PDGG.PG_PROGETTO = PDGP.PG_PROGETTO
              AND   PDGG.CD_NATURA = PDGP.CD_NATURA
              AND   PDGG.ID_CLASSIFICAZIONE = PDGP.ID_CLASSIFICAZIONE
              AND   PDGG.CD_CDS_AREA = PDGP.CD_CDS_AREA
              AND   PDGG.PG_DETTAGLIO = PDGP.PG_DETTAGLIO) IM_INCASSI_PDGG
      From PDG_MODULO_ENTRATE PDGP, CDR B, V_CLASSIFICAZIONE_VOCI C, PROGETTO_PREV D
      Where PDGP.CD_CENTRO_RESPONSABILITA = B.CD_CENTRO_RESPONSABILITA
      And   PDGP.ID_CLASSIFICAZIONE = C.ID_CLASSIFICAZIONE
      And   PDGP.PG_PROGETTO = D.PG_PROGETTO
      And   D.ESERCIZIO = PDGP.ESERCIZIO);
