--------------------------------------------------------
--  DDL for View V_CONS_PDG_ETR_PRELIMINARE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PDG_ETR_PRELIMINARE" ("ESERCIZIO", "PESO_DIP", "CD_DIPARTIMENTO", "CD_CENTRO_SPESA", "CD_UNITA_ORGANIZZATIVA", "CD_CENTRO_RESPONSABILITA", "CD_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "PG_MODULO", "CD_MODULO", "CD_TIPO_MODULO", "PG_COMMESSA", "CD_COMMESSA", "PG_PROGETTO", "CD_PROGETTO", "CD_TERZO_FINANZIATORE", "TOT_FINANZIAMENTO", "TOT_ENT_IST_A1", "TOT_ENT_AREE_A1", "TOT_ENT_IST_A2", "TOT_ENT_AREE_A2", "TOT_ENT_IST_A3", "TOT_ENT_AREE_A3") AS 
  Select
--
-- Date: 09/11/2006
-- Version: 1.1
--
-- Vista CONSULTAZIONE Piano di Gestione Preliminare Entrate
--
-- History:
--
-- Date: 01/01/2006
-- Version: 1.0
-- Creazione
--
-- Date: 09/11/2006
-- Version: 1.1
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
PDG_ETR.ESERCIZIO,
       nvl(p.peso,1000) PESO_DIP,
       Nvl(prog.cd_dipartimento, Null) CD_DIPARTIMENTO,
       UNITA_ORGANIZZATIVA.CD_UNITA_PADRE CD_CENTRO_SPESA,
       UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
       PDG_ETR.CD_CENTRO_RESPONSABILITA,
       CD_CLASSIFICAZIONE,
       NR_LIVELLO,
       CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5,  CD_LIVELLO6, CD_LIVELLO7,
       MODU.PG_PROGETTO PG_MODULO, MODU.CD_PROGETTO CD_MODULO, MODU.CD_TIPO_PROGETTO CD_TIPO_MODULO,
       COMM.PG_PROGETTO PG_COMMESSA, COMM.CD_PROGETTO CD_COMMESSA,
       PROG.PG_PROGETTO, PROG.CD_PROGETTO,
       PDG_ETR.CD_TERZO CD_TERZO_FINANZIATORE,
       Nvl(Sum(IM_ENTRATA_TOT), 0) TOT_FINANZIAMENTO,
       Nvl(Sum(IM_ENTRATA), 0)     TOT_ENT_IST_A1,
       0 TOT_ENT_AREE_A1,
       Nvl(Sum(IM_ENTRATA_A2), 0)  TOT_ENT_IST_A2,
       0 TOT_ENT_AREE_A2,
       Nvl(Sum(IM_ENTRATA_A3), 0)  TOT_ENT_IST_A3,
       0 TOT_ENT_AREE_A3
From   PDG_MODULO_ENTRATE PDG_ETR,
       V_CLASSIFICAZIONE_VOCI CLA,
       UNITA_ORGANIZZATIVA,
       UNITA_ORGANIZZATIVA AREA,
       CDR,
       PROGETTO_PREV MODU,
       PROGETTO_PREV COMM,
       PROGETTO_PREV PROG,
	dipartimento_peso p
Where
 PROG.esercizio= p.esercizio(+) AND
 PROG.cd_dipartimento= p.cd_dipartimento (+) and
  --Join tra PDG_MODULO_SPESE e V_CLASSIFICAZIONE_VOCI
       PDG_ETR.ID_CLASSIFICAZIONE = CLA.ID_CLASSIFICAZIONE And
--Join tra PDG_MODULO_SPESE e AREA (UNITA_ORGANIZZATIVA)
       PDG_ETR.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA And
--Join tra PDG_MODULO_SPESE e CDR
       PDG_ETR.CD_CENTRO_RESPONSABILITA = CDR.CD_CENTRO_RESPONSABILITA And
--Join tra CDR e UNITA_ORGANIZZATIVA
       CDR.CD_UNITA_ORGANIZZATIVA = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA And
--Join tra PDG_MODULO_SPESE e MODULO (PROGETTO)
       PDG_ETR.PG_PROGETTO = MODU.PG_PROGETTO And
       MODU.ESERCIZIO = PDG_ETR.ESERCIZIO And
--Join tra MODULO e COMMESSA (PROGETTO)
       MODU.ESERCIZIO_PROGETTO_PADRE = COMM.ESERCIZIO And
       MODU.PG_PROGETTO_PADRE = COMM.PG_PROGETTO And
--Join tra COMMESSA e PROGETTO
       COMM.ESERCIZIO_PROGETTO_PADRE = PROG.ESERCIZIO And
       COMM.PG_PROGETTO_PADRE = PROG.PG_PROGETTO And
       AREA.CD_TIPO_UNITA != 'AREA'
Group By PDG_ETR.ESERCIZIO,
         nvl(p.peso,1000),
         Nvl(prog.cd_dipartimento, Null),
         UNITA_ORGANIZZATIVA.CD_UNITA_PADRE,
         UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
         PDG_ETR.CD_CENTRO_RESPONSABILITA,
         CD_CLASSIFICAZIONE,
         NR_LIVELLO,
         CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5,  CD_LIVELLO6, CD_LIVELLO7,
         MODU.PG_PROGETTO, MODU.CD_PROGETTO, MODU.CD_TIPO_PROGETTO,
         COMM.PG_PROGETTO, COMM.CD_PROGETTO,
         PROG.PG_PROGETTO, PROG.CD_PROGETTO,
         PDG_ETR.CD_TERZO
Union All --Aree
Select PDG_ETR.ESERCIZIO,
       nvl(p.peso,1000) PESO_DIP,
       Nvl(prog.cd_dipartimento, Null) CD_DIPARTIMENTO,
       PDG_ETR.CD_CDS_AREA CD_CENTRO_SPESA,
       UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
       CDR.CD_CENTRO_RESPONSABILITA,
       CD_CLASSIFICAZIONE,
       NR_LIVELLO,
       CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5,  CD_LIVELLO6, CD_LIVELLO7,
       MODU.PG_PROGETTO PG_MODULO, MODU.CD_PROGETTO CD_MODULO, MODU.CD_TIPO_PROGETTO CD_TIPO_MODULO,
       COMM.PG_PROGETTO PG_COMMESSA, COMM.CD_PROGETTO CD_COMMESSA,
       PROG.PG_PROGETTO, PROG.CD_PROGETTO,
       PDG_ETR.CD_TERZO CD_TERZO_FINANZIATORE,
       Nvl(Sum(IM_ENTRATA_TOT), 0) TOT_FINANZIAMENTO,
       0 TOT_ENT_IST_A1,
       Nvl(Sum(IM_ENTRATA), 0)    TOT_ENT_AREE_A1,
       0 TOT_ENT_IST_A2,
       Nvl(Sum(IM_ENTRATA_A2), 0) TOT_ENT_AREE_A2,
       0 TOT_ENT_IST_A3,
       Nvl(Sum(IM_ENTRATA_A3), 0) TOT_ENT_AREE_A3
From   PDG_MODULO_ENTRATE PDG_ETR,
       V_CLASSIFICAZIONE_VOCI CLA,
       UNITA_ORGANIZZATIVA AREA,
       UNITA_ORGANIZZATIVA,
       CDR,
       PROGETTO_PREV MODU,
       PROGETTO_PREV COMM,
       PROGETTO_PREV PROG,
	dipartimento_peso p
Where
 PROG.esercizio= p.esercizio(+) AND
 PROG.cd_dipartimento= p.cd_dipartimento (+) and
  --Join tra PDG_MODULO_SPESE e V_CLASSIFICAZIONE_VOCI
       PDG_ETR.ID_CLASSIFICAZIONE = CLA.ID_CLASSIFICAZIONE And
--Join tra PDG_MODULO_SPESE e AREA (UNITA_ORGANIZZATIVA)
       PDG_ETR.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA And
--Join tra AREA e UNITA_ORGANIZZATIVA
       AREA.CD_UNITA_ORGANIZZATIVA = UNITA_ORGANIZZATIVA.CD_UNITA_PADRE And
       UNITA_ORGANIZZATIVA.FL_UO_CDS = 'Y' And
--Join tra UNITA_ORGANIZZATIVA e CDR
       UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA = CDR.CD_UNITA_ORGANIZZATIVA And
       CDR.CD_CDR_AFFERENZA Is Null And
--Join tra PDG_MODULO_SPESE e MODULO (PROGETTO)
       PDG_ETR.PG_PROGETTO = MODU.PG_PROGETTO And
       MODU.ESERCIZIO = PDG_ETR.ESERCIZIO And
--Join tra MODULO e COMMESSA (PROGETTO)
       MODU.ESERCIZIO_PROGETTO_PADRE = COMM.ESERCIZIO And
       MODU.PG_PROGETTO_PADRE = COMM.PG_PROGETTO And
--Join tra COMMESSA e PROGETTO
       COMM.ESERCIZIO_PROGETTO_PADRE = PROG.ESERCIZIO And
       COMM.PG_PROGETTO_PADRE = PROG.PG_PROGETTO And
       AREA.CD_TIPO_UNITA = 'AREA'
Group By PDG_ETR.ESERCIZIO,
         nvl(p.peso,1000),
         Nvl(prog.cd_dipartimento, Null),
         PDG_ETR.CD_CDS_AREA,
         UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
         CDR.CD_CENTRO_RESPONSABILITA,
         CD_CLASSIFICAZIONE,
         NR_LIVELLO,
         CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5,  CD_LIVELLO6, CD_LIVELLO7,
         MODU.PG_PROGETTO, MODU.CD_PROGETTO, MODU.CD_TIPO_PROGETTO,
         COMM.PG_PROGETTO, COMM.CD_PROGETTO,
         PROG.PG_PROGETTO, PROG.CD_PROGETTO,
         PDG_ETR.CD_TERZO;
