--------------------------------------------------------
--  DDL for View V_CONS_PARTITE_GIRO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PARTITE_GIRO" ("ESERCIZIO", "CD_CDS_OBB", "CD_UNITA_ORGANIZZATIVA_OBB", "CD_CDS_ORIGINE_OBB", "CD_UO_ORIGINE_OBB", "CD_ELEMENTO_VOCE_OBB", "IM_SCADENZA_COMP_OBB", "IM_SCADENZA_RES_OBB", "IM_ASSOCIATO_DOC_AMM_COMP_OBB", "IM_ASSOCIATO_DOC_AMM_RES_OBB", "IM_PAGATO_COMP", "IM_PAGATO_RES", "CD_ELEMENTO_VOCE_ACR", "IM_SCADENZA_COMP_ACR", "IM_SCADENZA_RES_ACR", "IM_ASSOCIATO_DOC_COMP_ACR", "IM_ASSOCIATO_DOC_RES_ACR", "IM_INCASSATO_COMP", "IM_INCASSATO_RES") AS 
  SELECT      ASS_OBB_ACR_PGIRO.ESERCIZIO,
	    V_CONS_OBBLIGAZIONI.CD_CDS CD_CDS_OBB,
	    V_CONS_OBBLIGAZIONI.CD_UNITA_ORGANIZZATIVA CD_UNITA_ORGANIZZATIVA_OBB,
	    V_CONS_OBBLIGAZIONI.CD_CDS_ORIGINE CD_CDS_ORIGINE_OBB,
	    V_CONS_OBBLIGAZIONI.CD_UO_ORIGINE CD_UO_ORIGINE_OBB,
	    V_CONS_OBBLIGAZIONI.CD_ELEMENTO_VOCE CD_ELEMENTO_VOCE_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_SCADENZA_COMP), 0) IM_SCADENZA_COMP_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_SCADENZA_RES), 0) IM_SCADENZA_RES_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_ASSOCIATO_DOC_AMM_COMP), 0) IM_ASSOCIATO_DOC_AMM_COMP_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_ASSOCIATO_DOC_AMM_RES), 0) IM_ASSOCIATO_DOC_AMM_RES_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_PAGATO_COMP), 0) IM_PAGATO_COMP,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_PAGATO_RES), 0) IM_PAGATO_RES,
            V_CONS_ACCERTAMENTI.CD_ELEMENTO_VOCE  CD_ELEMENTO_VOCE_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_SCADENZA_COMP), 0) IM_SCADENZA_COMP_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_SCADENZA_RES), 0) IM_SCADENZA_RES_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_ASSOCIATO_DOC_AMM_COMP), 0) IM_ASSOCIATO_DOC_COMP_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_ASSOCIATO_DOC_AMM_RES), 0) IM_ASSOCIATO_DOC_RES_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_INCASSATO_COMP), 0) IM_INCASSATO_COMP,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_INCASSATO_RES), 0) IM_INCASSATO_RES
FROM        ASS_OBB_ACR_PGIRO,
	    V_CONS_OBBLIGAZIONI,
	    V_CONS_ACCERTAMENTI
WHERE
-- JOIN         ASS_OBB_ACR_PGIRO
--              OBBLIGAZIONE
   	    ASS_OBB_ACR_PGIRO.CD_CDS	  	                        = V_CONS_OBBLIGAZIONI.CD_CDS
AND	    ASS_OBB_ACR_PGIRO.ESERCIZIO 		                = V_CONS_OBBLIGAZIONI.ESERCIZIO
AND	    ASS_OBB_ACR_PGIRO.ESERCIZIO_ORI_OBBLIGAZIONE                = V_CONS_OBBLIGAZIONI.ESERCIZIO_ORIGINALE
AND	    ASS_OBB_ACR_PGIRO.PG_OBBLIGAZIONE	                        = V_CONS_OBBLIGAZIONI.PG_OBBLIGAZIONE
-- JOIN         ASS_OBB_ACR_PGIRO
--              ACCERTAMENTO
AND	    ASS_OBB_ACR_PGIRO.CD_CDS	  	                        = V_CONS_ACCERTAMENTI.CD_CDS
AND	    ASS_OBB_ACR_PGIRO.ESERCIZIO 		                = V_CONS_ACCERTAMENTI.ESERCIZIO
AND	    ASS_OBB_ACR_PGIRO.ESERCIZIO_ORI_ACCERTAMENTO                = V_CONS_ACCERTAMENTI.ESERCIZIO_ORIGINALE
AND	    ASS_OBB_ACR_PGIRO.PG_ACCERTAMENTO	                        = V_CONS_ACCERTAMENTI.PG_ACCERTAMENTO
GROUP BY ASS_OBB_ACR_PGIRO.ESERCIZIO,
	    V_CONS_OBBLIGAZIONI.CD_CDS,
	    V_CONS_OBBLIGAZIONI.CD_UNITA_ORGANIZZATIVA,
	    V_CONS_OBBLIGAZIONI.CD_CDS_ORIGINE,
	    V_CONS_OBBLIGAZIONI.CD_UO_ORIGINE,
	    V_CONS_OBBLIGAZIONI.CD_ELEMENTO_VOCE,
	    V_CONS_ACCERTAMENTI.CD_ELEMENTO_VOCE
Union
Select      V_CONS_OBBLIGAZIONI.ESERCIZIO,
	    V_CONS_OBBLIGAZIONI.CD_CDS CD_CDS_OBB,
	    V_CONS_OBBLIGAZIONI.CD_UNITA_ORGANIZZATIVA CD_UNITA_ORGANIZZATIVA_OBB,
	    V_CONS_OBBLIGAZIONI.CD_CDS_ORIGINE CD_CDS_ORIGINE_OBB,
	    V_CONS_OBBLIGAZIONI.CD_UO_ORIGINE CD_UO_ORIGINE_OBB,
	    V_CONS_OBBLIGAZIONI.CD_ELEMENTO_VOCE CD_ELEMENTO_VOCE_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_SCADENZA_COMP), 0) IM_SCADENZA_COMP_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_SCADENZA_RES), 0) IM_SCADENZA_RES_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_ASSOCIATO_DOC_AMM_COMP), 0) IM_ASSOCIATO_DOC_AMM_COMP_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_ASSOCIATO_DOC_AMM_RES), 0) IM_ASSOCIATO_DOC_AMM_RES_OBB,
	    NVL(SUM(V_CONS_OBBLIGAZIONI.IM_PAGATO_COMP), 0) IM_PAGATO_COMP,
            NVL(SUM(V_CONS_OBBLIGAZIONI.IM_PAGATO_RES), 0) IM_PAGATO_RES,
            Null,
            0,
            0,
            0,
            0,
            0,
            0
From        V_CONS_OBBLIGAZIONI
Where       V_CONS_OBBLIGAZIONI.FL_PGIRO = 'Y'
And         Not exists
                (Select 1
                 From    ASS_OBB_ACR_PGIRO
                 where 	 ASS_OBB_ACR_PGIRO.CD_CDS  	        = V_CONS_OBBLIGAZIONI.CD_CDS
	         AND     ASS_OBB_ACR_PGIRO.ESERCIZIO             = V_CONS_OBBLIGAZIONI.ESERCIZIO
                 AND	 ASS_OBB_ACR_PGIRO.ESERCIZIO_ORI_OBBLIGAZIONE = V_CONS_OBBLIGAZIONI.ESERCIZIO_ORIGINALE
	         AND     ASS_OBB_ACR_PGIRO.PG_OBBLIGAZIONE       = V_CONS_OBBLIGAZIONI.PG_OBBLIGAZIONE )
group by 	V_CONS_OBBLIGAZIONI.ESERCIZIO,
	        V_CONS_OBBLIGAZIONI.CD_CDS ,
	        V_CONS_OBBLIGAZIONI.CD_UNITA_ORGANIZZATIVA ,
	        V_CONS_OBBLIGAZIONI.CD_CDS_ORIGINE ,
	        V_CONS_OBBLIGAZIONI.CD_UO_ORIGINE ,
	        V_CONS_OBBLIGAZIONI.CD_ELEMENTO_VOCE
Union
Select      V_CONS_ACCERTAMENTI.ESERCIZIO,
            V_CONS_ACCERTAMENTI.CD_CDS CD_CDS_ACR,
	    V_CONS_ACCERTAMENTI.CD_UNITA_ORGANIZZATIVA CD_UNITA_ORGANIZZATIVA_ACR,
	    V_CONS_ACCERTAMENTI.CD_CDS_ORIGINE CD_CDS_ORIGINE_ACR,
	    V_CONS_ACCERTAMENTI.CD_UO_ORIGINE CD_UO_ORIGINE_ACR,
	    Null,
            0,
            0,
            0,
            0,
            0,
            0,
            V_CONS_ACCERTAMENTI.CD_ELEMENTO_VOCE  CD_ELEMENTO_VOCE_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_SCADENZA_COMP), 0) IM_SCADENZA_COMP_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_SCADENZA_RES), 0) IM_SCADENZA_RES_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_ASSOCIATO_DOC_AMM_COMP), 0) IM_ASSOCIATO_DOC_COMP_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_ASSOCIATO_DOC_AMM_RES), 0) IM_ASSOCIATO_DOC_RES_ACR,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_INCASSATO_COMP), 0) IM_INCASSATO_COMP,
	    NVL(SUM(V_CONS_ACCERTAMENTI.IM_INCASSATO_RES), 0) IM_INCASSATO_RES
From        V_CONS_ACCERTAMENTI
Where       V_CONS_ACCERTAMENTI.FL_PGIRO  = 'Y'
And         Not exists
                (Select 1
                 From 	 ASS_OBB_ACR_PGIRO
                 where 	 ASS_OBB_ACR_PGIRO.CD_CDS  	        = V_CONS_ACCERTAMENTI.CD_CDS
	         AND     ASS_OBB_ACR_PGIRO.ESERCIZIO             = V_CONS_ACCERTAMENTI.ESERCIZIO
                 AND	 ASS_OBB_ACR_PGIRO.ESERCIZIO_ORI_ACCERTAMENTO = V_CONS_ACCERTAMENTI.ESERCIZIO_ORIGINALE
	         AND     ASS_OBB_ACR_PGIRO.PG_ACCERTAMENTO       = V_CONS_ACCERTAMENTI.PG_ACCERTAMENTO )
group By        V_CONS_ACCERTAMENTI.ESERCIZIO,
                V_CONS_ACCERTAMENTI.CD_CDS ,
	        V_CONS_ACCERTAMENTI.CD_UNITA_ORGANIZZATIVA ,
	        V_CONS_ACCERTAMENTI.CD_CDS_ORIGINE ,
	        V_CONS_ACCERTAMENTI.CD_UO_ORIGINE ,
	        V_CONS_ACCERTAMENTI.CD_ELEMENTO_VOCE;
