--------------------------------------------------------
--  DDL for View V_CONS_VAR_PDGG_AREA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_VAR_PDGG_AREA" ("ESERCIZIO", "PG_VARIAZIONE_PDG", "DS_VARIAZIONE", "DT_APPROVAZIONE", "DT_APP_FORMALE", "DS_DELIBERA", "TIPOLOGIA", "DS_TIPO_VARIAZIONE", "TIPOLOGIA_FIN", "DS_TIPOLOGIA_FIN", "PG_RIGA", "CD_CDR_ASSEGNATARIO", "DS_CDR", "CD_LINEA_ATTIVITA", "DS_LINEA_CDR_ORIGINE", "CD_CDR_AREA", "DS_CDR_AREA", "CD_LINEA_CDR_AREA", "DS_LINEA_CDR_AREA", "ID_CLASSIFICAZIONE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "PG_MODULO", "CD_MODULO", "DS_MODULO", "CD_TIPO_MODULO", "DS_TIPO_MODULO", "PG_COMMESSA", "CD_COMMESSA", "DS_COMMESSA", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO", "CD_CDS_AREA", "DS_UNITA_ORGANIZZATIVA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "DT_REGISTRAZIONE", "DESCRIZIONE", "IM_DEC_FONTE_INT", "IM_DEC_FONTE_EST", "IM_SPESE_GEST_ACCENTRATA_INT", "IM_SPESE_GEST_ACCENTRATA_EST", "IM_ENTRATA") AS 
  SELECT
/*+ FIRST_ROWS(10) INDEX(PDG_VARIAZIONE_RIGA_GEST PDG_VARIAZIONE_RIGA_GEST_APPO) INDEX(ELEMENTO_VOCE PX_ELEMENTO_VOCE) INDEX(CLASSIFICAZIONE_VOCI PX_CLASSIFICAZIONE_VOCI)*/
PDG_VARIAZIONE.ESERCIZIO,
PDG_VARIAZIONE.PG_VARIAZIONE_PDG,
PDG_VARIAZIONE.DS_VARIAZIONE,
PDG_VARIAZIONE.DT_APPROVAZIONE,
PDG_VARIAZIONE.DT_APP_FORMALE,
PDG_VARIAZIONE.DS_DELIBERA,
PDG_VARIAZIONE.TIPOLOGIA,
(SELECT DS_TIPO_VARIAZIONE FROM TIPO_VARIAZIONE Where TIPO_VARIAZIONE.ESERCIZIO = PDG_VARIAZIONE.ESERCIZIO AND TIPO_VARIAZIONE.CD_TIPO_VARIAZIONE = PDG_VARIAZIONE.TIPOLOGIA) DS_TIPO_VARIAZIONE,
PDG_VARIAZIONE.TIPOLOGIA_FIN,
DECODE (PDG_VARIAZIONE.TIPOLOGIA_FIN, 'FES', 'Fonti Esterne', 'FIN', 'Fonti Interne'),
PDG_VARIAZIONE_RIGA_GEST.PG_RIGA,
PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO_CLGS CD_CDR_ORIGINE, -- cdr originale
(SELECT DS_CDR FROM CDR WHERE PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO_CLGS = CDR.CD_CENTRO_RESPONSABILITA) DS_CDR_ORIGINE,
PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA_CLGS CD_LINEA_CDR_ORIGINE, -- linea del cdr originale
(Select DENOMINAZIONE FROM LINEA_ATTIVITA
 WHERE CD_CENTRO_RESPONSABILITA = PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO_CLGS And
       CD_LINEA_ATTIVITA = PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA_CLGS) DS_LINEA_CDR_ORIGINE,
PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO CD_CDR_AREA, -- cdr finale, quiandi area
(SELECT DS_CDR FROM CDR WHERE PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO = CDR.CD_CENTRO_RESPONSABILITA) DS_CDR_AREA,
PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA CD_LINEA_CDR_AREA, -- linea dell'area
(SELECT DENOMINAZIONE FROM LINEA_ATTIVITA
 WHERE CD_CENTRO_RESPONSABILITA = PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO And
       CD_LINEA_ATTIVITA = PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA) DS_LINEA_CDR_AREA,
V_CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE,
V_CLASSIFICAZIONE_VOCI.CD_CLASSIFICAZIONE,
V_CLASSIFICAZIONE_VOCI.DS_CLASSIFICAZIONE,
V_CLASSIFICAZIONE_VOCI.NR_LIVELLO,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO1,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO2,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO3,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO4,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO5,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO6,
V_CLASSIFICAZIONE_VOCI.CD_LIVELLO7,
MODU.PG_PROGETTO,
MODU.CD_PROGETTO,
modu.DS_PROGETTO,
MODU.CD_TIPO_PROGETTO,
(SELECT DS_TIPO_PROGETTO FROM TIPO_PROGETTO WHERE MODU.CD_TIPO_PROGETTO = TIPO_PROGETTO.CD_TIPO_PROGETTO) DS_TIPO_MODULO,
COM.PG_PROGETTO,
COM.CD_PROGETTO,
COM.DS_PROGETTO,
PROGETTO.PG_PROGETTO,
PROGETTO.CD_PROGETTO,
PROGETTO.DS_PROGETTO,
NVL(PROGETTO.CD_DIPARTIMENTO, NULL) CD_DIPARTIMENTO,
--(Select DS_DIPARTIMENTO From DIPARTIMENTO Where CD_DIPARTIMENTO = PROGETTO.CD_DIPARTIMENTO) DS_DIPARTIMENTO,
Cnrctb020.GETDESDIPARTIMENTO (PROGETTO.CD_DIPARTIMENTO) DS_DIPARTIMENTO,
PDG_VARIAZIONE_RIGA_GEST.CD_CDS_AREA,
AREA.DS_UNITA_ORGANIZZATIVA,
PDG_VARIAZIONE_RIGA_GEST.TI_APPARTENENZA,
PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE,
PDG_VARIAZIONE_RIGA_GEST.CD_ELEMENTO_VOCE,
DS_ELEMENTO_VOCE,
PDG_VARIAZIONE_RIGA_GEST.DT_REGISTRAZIONE,
PDG_VARIAZIONE_RIGA_GEST.DESCRIZIONE,
PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_DECENTRATA_INT,
PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_DECENTRATA_EST,
PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_ACCENTRATA_INT,
PDG_VARIAZIONE_RIGA_GEST.IM_SPESE_GEST_ACCENTRATA_EST,
PDG_VARIAZIONE_RIGA_GEST.IM_ENTRATA
FROM    PDG_VARIAZIONE,
        PDG_VARIAZIONE_RIGA_GEST,
	ELEMENTO_VOCE,
        V_CLASSIFICAZIONE_VOCI,
	LINEA_ATTIVITA LA_AREA,
	PROGETTO_GEST PROGETTO,
	PROGETTO_GEST COM,
	PROGETTO_GEST MODU,
	UNITA_ORGANIZZATIVA AREA
WHERE   PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO              = PDG_VARIAZIONE.ESERCIZIO
AND     PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG      = PDG_VARIAZIONE.PG_VARIAZIONE_PDG
AND     PDG_VARIAZIONE_RIGA_GEST.CATEGORIA_DETTAGLIO    = 'DIR'
AND	PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO              = ELEMENTO_VOCE.ESERCIZIO
AND	PDG_VARIAZIONE_RIGA_GEST.TI_APPARTENENZA        = ELEMENTO_VOCE.TI_APPARTENENZA
AND	PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE            = ELEMENTO_VOCE.TI_GESTIONE
AND	PDG_VARIAZIONE_RIGA_GEST.CD_ELEMENTO_VOCE       = ELEMENTO_VOCE.CD_ELEMENTO_VOCE
AND     ELEMENTO_VOCE.ID_CLASSIFICAZIONE                = V_CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE
--And     PDG_VARIAZIONE_RIGA_GEST.CD_CDS_AREA            = AREA.CD_UNITA_ORGANIZZATIVA
And     cnrutl001.getCdsFromCdr(CD_CDR_ASSEGNATARIO)    = AREA.CD_UNITA_ORGANIZZATIVA
And     AREA.CD_TIPO_UNITA                              = 'AREA'
AND	LA_AREA.CD_CENTRO_RESPONSABILITA                = PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO
AND	LA_AREA.CD_LINEA_ATTIVITA                       = PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA
AND     LA_AREA.PG_PROGETTO                             IS NOT NULL
AND	LA_AREA.PG_PROGETTO			        = MODU.PG_PROGETTO
AND     MODU.ESERCIZIO                                  = PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO
AND	MODU.ESERCIZIO_PROGETTO_PADRE		        = COM.ESERCIZIO
AND	MODU.PG_PROGETTO_PADRE				= COM.PG_PROGETTO
AND	COM.ESERCIZIO_PROGETTO_PADRE		        = PROGETTO.ESERCIZIO
AND	COM.PG_PROGETTO_PADRE                           = PROGETTO.PG_PROGETTO
And     PDG_VARIAZIONE.STATO                            In ('APP', 'APF')
--And     PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO_CLGS Is Not Null;
