--------------------------------------------------------
--  DDL for View V_CONS_PDGG_SPE_X_AREA_DET
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_PDGG_SPE_X_AREA_DET" ("ESERCIZIO", "CD_CDS_AREA", "DS_UNITA_ORGANIZZATIVA", "CD_CDR_ASSEGNATARIO", "DS_CDR", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "NR_LIVELLO", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "PG_MODULO", "CD_MODULO", "DS_MODULO", "PG_COMMESSA", "CD_COMMESSA", "DS_COMMESSA", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "CD_LINEA_ATTIVITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "IM_DEC_FONTE_INT", "IM_DEC_FONTE_EST", "TOT_DECENTRATO", "IM_PAGAMENTI") AS 
  SELECT
--
-- Date: 09/11/2006
-- Version: 1.1
--
-- Vista CONSULTAZIONE Spesa Piano di Gestione per Area
--
-- History:
--
-- Date: 01/01/2006
-- Version: 1.0
-- Creazione
--
-- Date: 09/11/2006
-- Version: 1.1
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
PDGG.ESERCIZIO, PDGG.CD_CDS_AREA, AREA.DS_UNITA_ORGANIZZATIVA,
       PDGG.CD_CDR_ASSEGNATARIO_CLGS, CDR.DS_CDR,
       CD_CLASSIFICAZIONE, DS_CLASSIFICAZIONE, NR_LIVELLO,
       CD_LIVELLO1, CD_LIVELLO2, CD_LIVELLO3, CD_LIVELLO4, CD_LIVELLO5,
       CD_LIVELLO6, CD_LIVELLO7,
       MODU.PG_PROGETTO PG_MODULO, MODU.CD_PROGETTO CD_MODULO, MODU.DS_PROGETTO DS_MODULO,
       COMM.PG_PROGETTO PG_COMMESSA, COMM.CD_PROGETTO CD_COMMESSA, COMM.DS_PROGETTO DS_COMMESSA,
       PROG.PG_PROGETTO, PROG.CD_PROGETTO, PROG.DS_PROGETTO,
       PDGG.CD_LINEA_ATTIVITA,
       PDGG.TI_APPARTENENZA,
       PDGG.TI_GESTIONE,
       PDGG.CD_ELEMENTO_VOCE,
       EV.DS_ELEMENTO_VOCE,
       PDGG.IM_SPESE_GEST_DECENTRATA_INT IM_DEC_FONTE_INT,
       PDGG.IM_SPESE_GEST_DECENTRATA_EST IM_DEC_FONTE_EST,
       Nvl(PDGG.IM_SPESE_GEST_DECENTRATA_INT, 0) + Nvl(PDGG.IM_SPESE_GEST_DECENTRATA_EST, 0) TOT_DECENTRATO,
       PDGG.IM_PAGAMENTI
From   PDG_MODULO_SPESE_GEST PDGG, V_CLASSIFICAZIONE_VOCI CLA, UNITA_ORGANIZZATIVA AREA,
       CDR, PROGETTO_PREV MODU, PROGETTO_PREV COMM, PROGETTO_PREV PROG, ELEMENTO_VOCE EV
Where  PDGG.ID_CLASSIFICAZIONE = CLA.ID_CLASSIFICAZIONE AND
       PDGG.CD_CDS_AREA = AREA.CD_UNITA_ORGANIZZATIVA AND
       PDGG.CD_CDR_ASSEGNATARIO_CLGS = CDR.CD_CENTRO_RESPONSABILITA AND
       PDGG.PG_PROGETTO = MODU.PG_PROGETTO And
       PDGG.ESERCIZIO = MODU.ESERCIZIO And
       MODU.ESERCIZIO_PROGETTO_PADRE = COMM.ESERCIZIO And
       MODU.PG_PROGETTO_PADRE = COMM.PG_PROGETTO And
       COMM.ESERCIZIO_PROGETTO_PADRE = PROG.ESERCIZIO And
       COMM.PG_PROGETTO_PADRE = PROG.PG_PROGETTO And
       AREA.CD_TIPO_UNITA = 'AREA' AND
       EV.ESERCIZIO         = PDGG.ESERCIZIO        AND
       EV.TI_APPARTENENZA   = PDGG.TI_APPARTENENZA  AND
       EV.TI_GESTIONE       = PDGG.TI_GESTIONE      AND
       EV.CD_ELEMENTO_VOCE  = PDGG.CD_ELEMENTO_VOCE And
       PDGG.CATEGORIA_DETTAGLIO = 'DIR';
