--------------------------------------------------------
--  DDL for View V_CONS_REVERSALI_RISCONTRATE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_REVERSALI_RISCONTRATE" ("ESERCIZIO", "DT_REGISTRAZIONE", "CD_SOSPESO", "CD_UNITA_ORGANIZZATIVA", "PG_REVERSALE", "CD_CDS", "IM_SOSPESO", "IM_ASSOCIATO") AS 
  Select S.ESERCIZIO,
	S.DT_REGISTRAZIONE,
	S.CD_SOSPESO,
	R.CD_UNITA_ORGANIZZATIVA,
	SD.PG_reversale,
	R.CD_CDS,
	S.IM_SOSPESO,
	SD.IM_ASSOCIATO
FROM	SOSPESO S,
	SOSPESO_DET_ETR SD,
	REVERSALE R
WHERE  S.CD_CDS 		= SD.CD_CDS
AND 	S.ESERCIZIO 		= SD.ESERCIZIO
AND 	S.TI_ENTRATA_SPESA 	= SD.TI_ENTRATA_SPESA
AND 	S.TI_SOSPESO_RISCONTRO  = SD.TI_SOSPESO_RISCONTRO
AND 	S.CD_SOSPESO 		= SD.CD_SOSPESO
AND 	SD.CD_CDS 		= R.CD_CDS
AND 	SD.ESERCIZIO 		= R.ESERCIZIO
AND 	SD.PG_reversale 	= R.PG_reversale
And 	S.TI_ENTRATA_SPESA 	='E'
AND 	S.TI_SOSPESO_RISCONTRO ='R'
AND 	S.FL_STORNATO 	='N'
Order By S.ESERCIZIO,S.CD_CDS,R.CD_UNITA_ORGANIZZATIVA,SD.PG_REVERSALE,S.CD_SOSPESO;
