--------------------------------------------------------
--  DDL for View V_CONS_ACCERTAMENTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_ACCERTAMENTI" ("CD_CDS", "ESERCIZIO", "CD_UNITA_ORGANIZZATIVA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "CD_ELEMENTO_VOCE", "TI_APPARTENENZA", "TI_GESTIONE", "ESERCIZIO_ORIGINALE", "PG_ACCERTAMENTO", "FL_PGIRO", "IM_SCADENZA_COMP", "IM_SCADENZA_RES", "IM_ASSOCIATO_DOC_AMM_COMP", "IM_ASSOCIATO_DOC_AMM_RES", "IM_INCASSATO_COMP", "IM_INCASSATO_RES") AS 
  Select
--
-- Date: 14/05/2007
-- Version: 1.1
--
-- History
--
-- Date: 19/07/2006
-- Version: 1.0
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
--
-- Date: 14/05/2007
-- Version: 1.1
-- Modificata logica per distinguere
-- compenza e residui
--
-- Body
--
ACCERTAMENTO.CD_CDS,
	    ACCERTAMENTO.ESERCIZIO,
	    ACCERTAMENTO.CD_UNITA_ORGANIZZATIVA,
	    ACCERTAMENTO.CD_CDS_ORIGINE,
	    ACCERTAMENTO.CD_UO_ORIGINE,
            ACCERTAMENTO.CD_ELEMENTO_VOCE,
            ACCERTAMENTO.TI_APPARTENENZA,
            ACCERTAMENTO.TI_GESTIONE,
	    ACCERTAMENTO.ESERCIZIO_ORIGINALE,
	    ACCERTAMENTO.PG_ACCERTAMENTO,
	    ACCERTAMENTO.FL_PGIRO,
	    Nvl(Decode(ACCERTAMENTO.ESERCIZIO, ACCERTAMENTO.ESERCIZIO_ORIGINALE,
	                  (Select Nvl(Sum(ACCERTAMENTO_SCADENZARIO.IM_SCADENZA), 0)
                           From  ACCERTAMENTO_SCADENZARIO
                           Where ACCERTAMENTO_SCADENZARIO.CD_CDS          = ACCERTAMENTO.CD_CDS
                           And   ACCERTAMENTO_SCADENZARIO.ESERCIZIO       = ACCERTAMENTO.ESERCIZIO
                           And   ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE = ACCERTAMENTO.ESERCIZIO_ORIGINALE
                           And   ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO = ACCERTAMENTO.PG_ACCERTAMENTO), 0), 0) IM_SCADENZA_COMP,
	    Nvl(Decode(ACCERTAMENTO.ESERCIZIO, ACCERTAMENTO.ESERCIZIO_ORIGINALE, 0,
	                  (Select Nvl(Sum(ACCERTAMENTO_SCADENZARIO.IM_SCADENZA), 0)
                           From  ACCERTAMENTO_SCADENZARIO
                           Where ACCERTAMENTO_SCADENZARIO.CD_CDS          = ACCERTAMENTO.CD_CDS
                           And   ACCERTAMENTO_SCADENZARIO.ESERCIZIO       = ACCERTAMENTO.ESERCIZIO
                           And   ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE = ACCERTAMENTO.ESERCIZIO_ORIGINALE
                           And   ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO = ACCERTAMENTO.PG_ACCERTAMENTO)), 0) IM_SCADENZA_RES,
	    Nvl(Decode(ACCERTAMENTO.ESERCIZIO, ACCERTAMENTO.ESERCIZIO_ORIGINALE,
	                  (Select Nvl(Sum(ACCERTAMENTO_SCADENZARIO.IM_ASSOCIATO_DOC_AMM), 0)
                           From  ACCERTAMENTO_SCADENZARIO
                           Where ACCERTAMENTO_SCADENZARIO.CD_CDS          = ACCERTAMENTO.CD_CDS
                           And   ACCERTAMENTO_SCADENZARIO.ESERCIZIO       = ACCERTAMENTO.ESERCIZIO
                           And   ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE = ACCERTAMENTO.ESERCIZIO_ORIGINALE
                           And   ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO = ACCERTAMENTO.PG_ACCERTAMENTO), 0), 0) IM_ASSOCIATO_DOC_AMM_COMP,
	    Nvl(Decode(ACCERTAMENTO.ESERCIZIO, ACCERTAMENTO.ESERCIZIO_ORIGINALE, 0,
	                  (Select Nvl(Sum(ACCERTAMENTO_SCADENZARIO.IM_ASSOCIATO_DOC_AMM), 0)
                           From  ACCERTAMENTO_SCADENZARIO
                           Where ACCERTAMENTO_SCADENZARIO.CD_CDS          = ACCERTAMENTO.CD_CDS
                           And   ACCERTAMENTO_SCADENZARIO.ESERCIZIO       = ACCERTAMENTO.ESERCIZIO
                           And   ACCERTAMENTO_SCADENZARIO.ESERCIZIO_ORIGINALE = ACCERTAMENTO.ESERCIZIO_ORIGINALE
                           And   ACCERTAMENTO_SCADENZARIO.PG_ACCERTAMENTO = ACCERTAMENTO.PG_ACCERTAMENTO)), 0) IM_ASSOCIATO_DOC_AMM_RES,
	    Nvl(Decode(ACCERTAMENTO.ESERCIZIO, ACCERTAMENTO.ESERCIZIO_ORIGINALE,
	                  (Select Nvl(Sum(Decode(REVERSALE_RIGA.STATO,'A',0,REVERSALE_RIGA.IM_REVERSALE_RIGA)), 0)
                           From  REVERSALE_RIGA
                           Where REVERSALE_RIGA.CD_CDS                 = ACCERTAMENTO.CD_CDS
	                   And   REVERSALE_RIGA.ESERCIZIO_ACCERTAMENTO = ACCERTAMENTO.ESERCIZIO
                           And   REVERSALE_RIGA.ESERCIZIO_ORI_ACCERTAMENTO = ACCERTAMENTO.ESERCIZIO_ORIGINALE
                           And   REVERSALE_RIGA.PG_ACCERTAMENTO        = ACCERTAMENTO.PG_ACCERTAMENTO), 0), 0) IM_INCASSATO_COMP,
	    Nvl(Decode(ACCERTAMENTO.ESERCIZIO, ACCERTAMENTO.ESERCIZIO_ORIGINALE, 0,
	                  (Select Nvl(Sum(Decode(REVERSALE_RIGA.STATO,'A',0,REVERSALE_RIGA.IM_REVERSALE_RIGA)), 0)
                           From  REVERSALE_RIGA
                           Where REVERSALE_RIGA.CD_CDS                 = ACCERTAMENTO.CD_CDS
	                   And   REVERSALE_RIGA.ESERCIZIO_ACCERTAMENTO = ACCERTAMENTO.ESERCIZIO
                           And   REVERSALE_RIGA.ESERCIZIO_ORI_ACCERTAMENTO = ACCERTAMENTO.ESERCIZIO_ORIGINALE
                           And   REVERSALE_RIGA.PG_ACCERTAMENTO        = ACCERTAMENTO.PG_ACCERTAMENTO)), 0) IM_INCASSATO_RES
From   ACCERTAMENTO
;
