--------------------------------------------------------
--  DDL for View V_CONS_MANDATI_RISCONTRATI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_MANDATI_RISCONTRATI" ("ESERCIZIO", "DT_REGISTRAZIONE", "CD_SOSPESO", "CD_UNITA_ORGANIZZATIVA", "PG_MANDATO", "CD_CDS", "IM_SOSPESO", "IM_ASSOCIATO") AS 
  SELECT S.ESERCIZIO,
	S.DT_REGISTRAZIONE,
	S.CD_SOSPESO,
	M.CD_UNITA_ORGANIZZATIVA,
	SD.PG_MANDATO,
	S.CD_CDS,
	S.IM_SOSPESO,
	SD.IM_ASSOCIATO
FROM	SOSPESO S,
	SOSPESO_DET_USC SD,
	MANDATO M
WHERE   S.CD_CDS 		= SD.CD_CDS
AND 	S.ESERCIZIO 		= SD.ESERCIZIO
AND 	S.TI_ENTRATA_SPESA 	= SD.TI_ENTRATA_SPESA
AND 	S.TI_SOSPESO_RISCONTRO = SD.TI_SOSPESO_RISCONTRO
AND 	S.CD_SOSPESO 		= SD.CD_SOSPESO
AND 	SD.CD_CDS 		= M.CD_CDS
AND 	SD.ESERCIZIO 		= M.ESERCIZIO
AND 	SD.PG_MANDATO 	        = M.PG_MANDATO
And 	S.TI_ENTRATA_SPESA 	= 'S'
AND 	S.TI_SOSPESO_RISCONTRO  = 'R'
AND 	S.FL_STORNATO 	        = 'N'
Order By S.ESERCIZIO,S.CD_CDS,M.CD_UNITA_ORGANIZZATIVA,SD.PG_MANDATO,S.CD_SOSPESO;
