--------------------------------------------------------
--  DDL for View V_DISP_RES_IMPROPRIE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_DISP_RES_IMPROPRIE" ("ESERCIZIO", "ESERCIZIO_RES", "CD_CENTRO_RESPONSABILITA", "CD_LINEA_ATTIVITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_VOCE", "TOT_IM_RESIDUI_RICOSTRUITI", "TOT_IM_STANZ_INIZIALE_A1", "TOT_VARIAZIONI_PIU", "TOT_VARIAZIONI_MENO", "TOT_IM_OBBL_ACC_COMP", "TOT_IM_STANZ_RES_IMPROPRIO", "TOT_VAR_PIU_STANZ_RES_IMP", "TOT_VAR_MENO_STANZ_RES_IMP", "TOT_IM_OBBL_RES_IMP", "TOT_VAR_PIU_OBBL_RES_IMP", "TOT_VAR_MENO_OBBL_RES_IMP", "TOT_VAR_PIU_OBBL_RES_PRO", "TOT_VAR_MENO_OBBL_RES_PRO") AS 
  Select ESERCIZIO,
       ESERCIZIO_RES,
       CD_CENTRO_RESPONSABILITA,
       CD_LINEA_ATTIVITA,
       TI_APPARTENENZA,
       TI_GESTIONE,
       CD_VOCE,
       0 TOT_IM_RESIDUI_RICOSTRUITI,
       sum(IM_STANZ_INIZIALE_A1) tot_IM_STANZ_INIZIALE_A1,
       Sum(VARIAZIONI_PIU) tot_VARIAZIONI_PIU,
       Sum(VARIAZIONI_MENO) tot_VARIAZIONI_MENO,
       Sum(IM_OBBL_ACC_COMP) tot_IM_OBBL_ACC_COMP,
       Sum(IM_STANZ_RES_IMPROPRIO) tot_IM_STANZ_RES_IMPROPRIO,
       Sum(VAR_PIU_STANZ_RES_IMP) tot_VAR_PIU_STANZ_RES_IMP,
       Sum(VAR_MENO_STANZ_RES_IMP) tot_VAR_MENO_STANZ_RES_IMP,
       Sum(IM_OBBL_RES_IMP) tot_IM_OBBL_RES_IMP,
       Sum(VAR_PIU_OBBL_RES_IMP) tot_VAR_PIU_OBBL_RES_IMP,
       Sum(VAR_MENO_OBBL_RES_IMP) tot_VAR_MENO_OBBL_RES_IMP,
       Sum(VAR_PIU_OBBL_RES_PRO) tot_VAR_PIU_OBBL_RES_PRO,
       Sum(VAR_MENO_OBBL_RES_PRO) tot_VAR_MENO_OBBL_RES_PRO
From  voce_f_saldi_cdr_linea
Group By ESERCIZIO, ESERCIZIO_RES, CD_CENTRO_RESPONSABILITA,
       CD_LINEA_ATTIVITA, TI_APPARTENENZA, TI_GESTIONE, CD_VOCE
UNION ALL
Select ESERCIZIO,
       ESERCIZIO,
       CD_CDR_LINEA,
       CD_LINEA_ATTIVITA,
       TI_APPARTENENZA,
       TI_GESTIONE,
       CNRCTB053.GETVOCE_FDAEV (PDG_RESIDUO_DET.ESERCIZIO,
                                PDG_RESIDUO_DET.TI_APPARTENENZA,
                                PDG_RESIDUO_DET.TI_GESTIONE,
                                PDG_RESIDUO_DET.CD_ELEMENTO_VOCE,
                                PDG_RESIDUO_DET.CD_CDR_LINEA,
                                PDG_RESIDUO_DET.CD_LINEA_ATTIVITA),
       sum(IM_RESIDUO) TOT_IM_RESIDUI_RICOSTRUITI,
       0 tot_IM_STANZ_INIZIALE_A1,
       0 tot_VARIAZIONI_PIU,
       0 tot_VARIAZIONI_MENO,
       0 tot_IM_OBBL_ACC_COMP,
       0 tot_IM_STANZ_RES_IMPROPRIO,
       0 tot_VAR_PIU_STANZ_RES_IMP,
       0 tot_VAR_MENO_STANZ_RES_IMP,
       0 tot_IM_OBBL_RES_IMP,
       0 tot_VAR_PIU_OBBL_RES_IMP,
       0 tot_VAR_MENO_OBBL_RES_IMP,
       0 tot_VAR_PIU_OBBL_RES_PRO,
       0 tot_VAR_MENO_OBBL_RES_PRO
From   PDG_RESIDUO_DET
Where STATO != 'A'
Group By ESERCIZIO, ESERCIZIO, CD_CDR_LINEA,
       CD_LINEA_ATTIVITA, TI_APPARTENENZA, TI_GESTIONE, CD_ELEMENTO_VOCE;
