--------------------------------------------------------
--  DDL for View V_DOC_AMM_BREVETTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_DOC_AMM_BREVETTI" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_FATTURA_PASSIVA", "DS_FATTURA_PASSIVA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "TIPO_FATTURA_COMPENSO", "NR_FATTURA_FORNITORE", "DT_FATTURA_FORNITORE", "PARTITA_IVA", "CODICE_FISCALE", "DT_REGISTRAZIONE", "CD_TERZO", "COGNOME", "NOME", "RAGIONE_SOCIALE", "CAMBIO", "CD_DIVISA") AS 
  select
FP.CD_CDS,
FP.CD_UNITA_ORGANIZZATIVA,
FP.ESERCIZIO, 
FP.PG_FATTURA_PASSIVA, 
FP.DS_FATTURA_PASSIVA, 
FP.CD_CDS_ORIGINE, 
FP.CD_UO_ORIGINE, 
DECODE(fP.TI_FATTURA,'F','FATTURA', 'N', 'NOTA'), 
FP.NR_FATTURA_FORNITORE, 
FP.DT_FATTURA_FORNITORE, 
FP.PARTITA_IVA, 
FP.CODICE_FISCALE,
FP.DT_REGISTRAZIONE,
FP.CD_TERZO, 
FP.COGNOME, 
FP.NOME, 
FP.RAGIONE_SOCIALE, 
FP.CAMBIO, 
FP.CD_DIVISA
from fattura_PASSiva fP
where (fP.CD_CDS, fP.CD_UNITA_ORGANIZZATIVA, fP.ESERCIZIO, fP.PG_FATTURA_PASSIVA) IN 
	(select fPr.CD_CDS, fPr.CD_UNITA_ORGANIZZATIVA, fPr.ESERCIZIO, fPr.PG_FATTURA_PASSIVA 
	 from fattura_passiva_riga fpr
	 where	FPR.PG_TROVATO IS NOT NULL )
UNION ALL
select DISTINCT
COMP.CD_CDS,
COMP.CD_UNITA_ORGANIZZATIVA,
COMP.ESERCIZIO, 
COMP.PG_COMPENSO, 
COMP.DS_COMPENSO, 
COMP.CD_CDS_ORIGINE, 
COMP.CD_UO_ORIGINE, 
'C', 
COMP.NR_FATTURA_FORNITORE, 
COMP.DT_FATTURA_FORNITORE, 
COMP.PARTITA_IVA, 
COMP.CODICE_FISCALE,
COMP.DT_REGISTRAZIONE,
COMP.CD_TERZO, 
COMP.COGNOME, 
COMP.NOME, 
COMP.RAGIONE_SOCIALE, 
null, 
null
from COMPENSO COMP, COMPENSO_RIGA COMPRIGA
where COMP.CD_CDS = COMPRIGA.CD_CDS
and   COMP.CD_UNITA_ORGANIZZATIVA = COMPRIGA.CD_UNITA_ORGANIZZATIVA
and   COMP.ESERCIZIO = COMPRIGA.ESERCIZIO
and   COMP.PG_COMPENSO = COMPRIGA.PG_COMPENSO
and   COMPRIGA.PG_TROVATO IS NOT NULL ;
