--------------------------------------------------------
--  DDL for View V_DOCUMENTO_ELE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_DOCUMENTO_ELE" ("ID_PAESE", "ID_CODICE", "IDENTIFICATIVO_SDI", "PROGRESSIVO",
    "TIPO_DOCUMENTO", "DIVISA", "DATA_DOCUMENTO", "NUMERO_DOCUMENTO", "BOLLO_VIRTUALE",
    "IMPORTO_BOLLO", "TIPO_BOLLO", "IMPORTO_DOCUMENTO", "ARROTONDAMENTO", "CAUSALE", "ART73",
    "VETTORE_PAESE", "VETTORE_CODICE", "VETTORE_CODICEFISCALE", "VETTORE_DENOMINAZIONE",
    "VETTORE_NOME", "VETTORE_COGNOME", "VETTORE_TITOLO", "VETTORE_CODEORI", "VETTORE_NUMEROLICENZA",
    "MEZZO_TRASPORTO", "CAUSALE_TRASPORTO", "NUMERO_COLLI", "DESCRIZIONE_TRASPORTO", "UNITA_MISURAPESO",
    "PESO_LORDO", "PESO_NETTO", "DATAORA_RITIRO", "DATAINIZIO_TRASPORTO", "TIPO_RESA", "RESA_INDIRIZZO",
    "RESA_NUMEROCIVICO", "RESA_CAP", "RESA_COMUNE", "RESA_PROVINCIA", "RESA_NAZIONE", "DATAORA_CONSEGNA",
    "NUMERO_FATTURAPRINCIPALE", "DATA_FATTURAPRINCIPALE", "DATA_IMMATRICOLAZIONEVEICOLO", "TOTALE_PERCORSOVEICOLO",
    "BENEFICIARIO_PAGAMENTO", "BENEFICIARIO_MOD_PAG", "DATATERMINI_PAGAMENTO", "GIORNITERMINI_PAGAMENTO", "DATASCADENZA_PAGAMENTO",
    "IMPORTO_PAGAMENTO", "CODUFFICIOPOSTALE", "COGNOME_QUIETANZANTE", "NOME_QUIETANZANTE", "ISTITUTO_FINANZIARIO",
    "IBAN", "ABI", "CAB", "BIC", "PAGAMENTO_CD_TERZO", "PAGAMENTO_CD_MODALITA_PAG", "SCONTO_PAGAMENTO_ANT",
    "DATALIMITE_PAGAMENTO_ANT", "PENALITA_PAG_RITARDATI", "DATA_RICORRENZAPENALE", "CODICE_PAGAMENTO", "STATO_DOCUMENTO",
    "MOTIVO_RIFIUTO", "ANOMALIE", "DATA_RICEVIMENTO_MAIL_RIFIUTO", "DACR", "UTCR", "DUVA", "UTUV", "PG_VER_REC",
    "FL_DECORRENZA_TERMINI", "STATO_NOTIFICA_ESITO", "PROGRESSIVO_INVIO", "FORMATO_TRASMISSIONE",
    "CODICE_DESTINATARIO", "CD_UNITA_ORGANIZZATIVA", "CD_UNITA_COMPETENZA", "FL_COMPLETATO", "TRASMITTENTE_TELEFONO",
    "TRASMITTENTE_EMAIL", "PRESTATORE_PAESE", "PRESTATORE_CODICE", "PRESTATORE_CODICEFISCALE", "PRESTATORE_DENOMINAZIONE",
    "PRESTATORE_NOME", "PRESTATORE_COGNOME", "PRESTATORE_TITOLO", "PRESTATORE_CODEORI", "ALBOPROFESSIONALE", "PROVINCIAALBO",
    "NUMEROALBO", "DATAISCRIZIONEALBO", "REGIMEFISCALE", "PRESTATORE_INDIRIZZO", "PRESTATORE_NUMEROCIVICO", "PRESTATORE_CAP",
    "PRESTATORE_COMUNE", "PRESTATORE_PROVINCIA", "PRESTATORE_NAZIONE", "PRESTATORE_CD_TERZO", "PRESTATORE_CD_ANAG",
    "STABILEORG_INDIRIZZO", "STABILEORG_NUMEROCIVICO", "STABILEORG_CAP", "STABILEORG_COMUNE", "STABILEORG_PROVINCIA",
    "STABILEORG_NAZIONE", "REA_UFFICIO", "REA_NUMEROREA", "REA_CAPITALESOCIALE", "REA_SOCIOUNICO", "REA_STATOLIQUIDAZIONE",
    "PRESTATORE_TELEFONO", "PRESTATORE_FAX", "PRESTATORE_EMAIL", "RIFERIMENTO_AMMINISTRAZIONE", "RAPPRESENTANTE_PAESE",
    "RAPPRESENTANTE_CODICE", "RAPPRESENTANTE_CODICEFISCALE", "RAPPRESENTANTE_DENOMINAZIONE", "RAPPRESENTANTE_NOME",
    "RAPPRESENTANTE_COGNOME", "RAPPRESENTANTE_TITOLO", "RAPPRESENTANTE_CODEORI", "RAPPRESENTANTE_CD_TERZO", "RAPPRESENTANTE_CD_ANAG",
    "COMMITTENTE_PAESE", "COMMITTENTE_CODICE", "COMMITTENTE_CODICEFISCALE", "COMMITTENTE_DENOMINAZIONE", "COMMITTENTE_NOME",
    "COMMITTENTE_COGNOME", "COMMITTENTE_TITOLO", "COMMITTENTE_CODEORI", "COMMITTENTE_INDIRIZZO", "COMMITTENTE_NUMEROCIVICO",
    "COMMITTENTE_CAP", "COMMITTENTE_COMUNE", "COMMITTENTE_PROVINCIA", "COMMITTENTE_NAZIONE", "COMMITTENTE_CD_TERZO",
    "INTERMEDIARIO_PAESE", "INTERMEDIARIO_CODICE", "INTERMEDIARIO_CODICEFISCALE", "INTERMEDIARIO_DENOMINAZIONE", "INTERMEDIARIO_NOME",
    "INTERMEDIARIO_COGNOME", "INTERMEDIARIO_TITOLO", "INTERMEDIARIO_CODEORI", "INTERMEDIARIO_CD_TERZO", "INTERMEDIARIO_CD_ANAG",
    "SOGGETTO_EMITTENTE", "CODICE_UNIVOCO_SDI", "DATA_RICEZIONE", "ANOMALIE_RICEZIONE", "CMIS_NODE_REF", "NOME_FILE", "REPLY_TO",
    "FL_IRREGISTRABILE","ID_PAESE_FAT_COL", "ID_CODICE_FAT_COL", "IDENTIFICATIVO_SDI_FAT_COL", "PROGRESSIVO_FAT_COL") AS
  (SELECT tes."ID_PAESE", tes."ID_CODICE", tes."IDENTIFICATIVO_SDI",
           tes."PROGRESSIVO", tes."TIPO_DOCUMENTO", tes."DIVISA",
           tes."DATA_DOCUMENTO", tes."NUMERO_DOCUMENTO", tes."BOLLO_VIRTUALE",
           tes."IMPORTO_BOLLO", tes."TIPO_BOLLO", tes."IMPORTO_DOCUMENTO",
           tes."ARROTONDAMENTO", tes."CAUSALE", tes."ART73",
           tes."VETTORE_PAESE", tes."VETTORE_CODICE",
           tes."VETTORE_CODICEFISCALE", tes."VETTORE_DENOMINAZIONE",
           tes."VETTORE_NOME", tes."VETTORE_COGNOME", tes."VETTORE_TITOLO",
           tes."VETTORE_CODEORI", tes."VETTORE_NUMEROLICENZA",
           tes."MEZZO_TRASPORTO", tes."CAUSALE_TRASPORTO", tes."NUMERO_COLLI",
           tes."DESCRIZIONE_TRASPORTO", tes."UNITA_MISURAPESO",
           tes."PESO_LORDO", tes."PESO_NETTO", tes."DATAORA_RITIRO",
           tes."DATAINIZIO_TRASPORTO", tes."TIPO_RESA", tes."RESA_INDIRIZZO",
           tes."RESA_NUMEROCIVICO", tes."RESA_CAP", tes."RESA_COMUNE",
           tes."RESA_PROVINCIA", tes."RESA_NAZIONE", tes."DATAORA_CONSEGNA",
           tes."NUMERO_FATTURAPRINCIPALE", tes."DATA_FATTURAPRINCIPALE",
           tes."DATA_IMMATRICOLAZIONEVEICOLO", tes."TOTALE_PERCORSOVEICOLO",
           tes."BENEFICIARIO_PAGAMENTO", tes."BENEFICIARIO_MOD_PAG",
           tes."DATATERMINI_PAGAMENTO", tes."GIORNITERMINI_PAGAMENTO",
           tes."DATASCADENZA_PAGAMENTO", tes."IMPORTO_PAGAMENTO",
           tes."CODUFFICIOPOSTALE", tes."COGNOME_QUIETANZANTE",
           tes."NOME_QUIETANZANTE", tes."ISTITUTO_FINANZIARIO", tes."IBAN",
           tes."ABI", tes."CAB", tes."BIC", tes."PAGAMENTO_CD_TERZO",
           tes."PAGAMENTO_CD_MODALITA_PAG", tes."SCONTO_PAGAMENTO_ANT",
           tes."DATALIMITE_PAGAMENTO_ANT", tes."PENALITA_PAG_RITARDATI",
           tes."DATA_RICORRENZAPENALE", tes."CODICE_PAGAMENTO",
           tes."STATO_DOCUMENTO", tes."MOTIVO_RIFIUTO", tes."ANOMALIE", tes."DATA_RICEVIMENTO_MAIL_RIFIUTO",
           tes."DACR", tes."UTCR", tes."DUVA", tes."UTUV", tes."PG_VER_REC",
           tes."FL_DECORRENZA_TERMINI", tes."STATO_NOTIFICA_ESITO", tra.progressivo_invio,
           tra.formato_trasmissione, tra.codice_destinatario,
           tra.cd_unita_organizzativa, tes.cd_unita_competenza,
           tra.fl_completato, tra.trasmittente_telefono,
           tra.trasmittente_email, tra.prestatore_paese,
           tra.prestatore_codice, tra.prestatore_codicefiscale,
           nvl(tra.prestatore_denominazione,tra.prestatore_cognome||' '||tra.prestatore_nome), tra.prestatore_nome,
           tra.prestatore_cognome, tra.prestatore_titolo,
           tra.prestatore_codeori, tra.alboprofessionale, tra.provinciaalbo,
           tra.numeroalbo, tra.dataiscrizionealbo, tra.regimefiscale,
           tra.prestatore_indirizzo, tra.prestatore_numerocivico,
           tra.prestatore_cap, tra.prestatore_comune,
           tra.prestatore_provincia, tra.prestatore_nazione,
           tra.prestatore_cd_terzo, tra.prestatore_cd_anag,
           tra.stabileorg_indirizzo, tra.stabileorg_numerocivico,
           tra.stabileorg_cap, tra.stabileorg_comune,
           tra.stabileorg_provincia, tra.stabileorg_nazione, tra.rea_ufficio,
           tra.rea_numerorea, tra.rea_capitalesociale, tra.rea_sociounico,
           tra.rea_statoliquidazione, tra.prestatore_telefono,
           tra.prestatore_fax, tra.prestatore_email,
           tra.riferimento_amministrazione, tra.rappresentante_paese,
           tra.rappresentante_codice, tra.rappresentante_codicefiscale,
           tra.rappresentante_denominazione, tra.rappresentante_nome,
           tra.rappresentante_cognome, tra.rappresentante_titolo,
           tra.rappresentante_codeori, tra.rappresentante_cd_terzo,
           tra.rappresentante_cd_anag, tra.committente_paese,
           tra.committente_codice, tra.committente_codicefiscale,
           tra.committente_denominazione, tra.committente_nome,
           tra.committente_cognome, tra.committente_titolo,
           tra.committente_codeori, tra.committente_indirizzo,
           tra.committente_numerocivico, tra.committente_cap,
           tra.committente_comune, tra.committente_provincia,
           tra.committente_nazione, tra.committente_cd_terzo,
           tra.intermediario_paese, tra.intermediario_codice,
           tra.intermediario_codicefiscale, tra.intermediario_denominazione,
           tra.intermediario_nome, tra.intermediario_cognome,
           tra.intermediario_titolo, tra.intermediario_codeori,
           tra.intermediario_cd_terzo, tra.intermediario_cd_anag,
           tra.soggetto_emittente, tra.codice_univoco_sdi, tra.data_ricezione,
           tra.anomalie_ricezione, tra.cmis_node_ref, tra.nome_file, tra.reply_to,tes.fl_irregistrabile,
           tes."ID_PAESE_FAT_COL", tes."ID_CODICE_FAT_COL", tes."IDENTIFICATIVO_SDI_FAT_COL", tes."PROGRESSIVO_FAT_COL"
      FROM documento_ele_testata tes, documento_ele_trasmissione tra
     WHERE tes.id_paese = tra.id_paese
       AND tes.id_codice = tra.id_codice
       AND tes.identificativo_sdi = tra.identificativo_sdi);
