--------------------------------------------------------
--  DDL for View V_DOC_AMM_ATTIVI_BREVETTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_DOC_AMM_ATTIVI_BREVETTI" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_FATTURA_ATTIVA", "DS_FATTURA_ATTIVA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "TIPO_FATTURA", "DT_REGISTRAZIONE", "DT_EMISSIONE", "CD_TERZO", "COGNOME", "NOME", "RAGIONE_SOCIALE", "CAMBIO", "CD_DIVISA") AS 
  select
FA.CD_CDS,
FA.CD_UNITA_ORGANIZZATIVA,
FA.ESERCIZIO, 
FA.PG_FATTURA_ATTIVA, 
FA.DS_FATTURA_ATTIVA, 
FA.CD_CDS_ORIGINE, 
FA.CD_UO_ORIGINE, 
DECODE(fA.TI_FATTURA,'F','F', 'N'), 
FA.DT_REGISTRAZIONE,
DT_EMISSIONE,
FA.CD_TERZO, 
FA.COGNOME, 
FA.NOME, 
FA.RAGIONE_SOCIALE, 
FA.CAMBIO, 
FA.CD_DIVISA
from fattura_ATTiva fA
where (fA.CD_CDS, fA.CD_UNITA_ORGANIZZATIVA, fA.ESERCIZIO, fA.PG_FATTURA_ATTIVA) IN 
	(select fAr.CD_CDS, fAr.CD_UNITA_ORGANIZZATIVA, fAr.ESERCIZIO, fAr.PG_FATTURA_ATTIVA 
	 from fattura_ATTiva_riga fAr
	 where	FAR.PG_TROVATO IS NOT NULL ) ;
