--------------------------------------------------------
--  DDL for View V_DOC_AMM_COGE_RIGA_EPR
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_DOC_AMM_COGE_RIGA_EPR" ("CD_TIPO_DOCUMENTO", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_NUMERO_DOCUMENTO", "CD_TERZO", "PG_RIGA", "CD_BENE_SERVIZIO", "DT_DA_COMPETENZA_COGE", "DT_A_COMPETENZA_COGE", "TI_ISTITUZ_COMMERC", "IM_TOTALE_DIVISA", "IM_IMPONIBILE", "IM_IVA", "IM_DIPONIBILE_NC", "FL_PGIRO", "ESERCIZIO_EV", "TI_APPARTENENZA_EV", "TI_GESTIONE_EV", "CD_ELEMENTO_VOCE_EV") AS 
  (
select -- Estrazione fattura passiva
--
-- Date: 18/07/2006
-- Version: 1.2
--
-- Vista di estrazione dei dettagli di documento amministrativo con valorizzazioni a fini COGE.
-- Tale vista estrae solo DOCUMENTI parzialmente o totalmente riportati a nuovo esercizio da esercizio precedente, quello
-- di creazione del documento.
--
-- History:
--
-- Date: 30/01/2004
-- Version: 1.0
-- Creazione
--
-- Date: 19/02/2004
-- Version: 1.1
-- Fix errore su fine canale di comunicazione (è stato necessario introdurre una stored procedure ad HOC)
--
-- Date: 18/07/2006
-- Version: 1.2
-- Fix: non estraeva le righe di doc amm gia pagate e rimaste nell'esercizio di origine
--
-- Body:
--
V.CD_TIPO_DOCUMENTO,
V.CD_CDS,
V.CD_UNITA_ORGANIZZATIVA,
V.ESERCIZIO,
V.PG_NUMERO_DOCUMENTO,
V.CD_TERZO,
V.PG_RIGA,
V.CD_BENE_SERVIZIO,
V.DT_DA_COMPETENZA_COGE,
V.DT_A_COMPETENZA_COGE,
V.TI_ISTITUZ_COMMERC,
V.IM_TOTALE_DIVISA,
V.IM_IMPONIBILE,
V.IM_IVA,
V.IM_DIPONIBILE_NC,
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.FL_PGIRO,O.FL_PGIRO),
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.ESERCIZIO_EV,O.ESERCIZIO),
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.TI_APPARTENENZA_EV,O.TI_APPARTENENZA),
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.TI_GESTIONE_EV,O.TI_GESTIONE),
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.CD_ELEMENTO_VOCE_EV,O.CD_ELEMENTO_VOCE)
from V_DOC_AMM_COGE_RIGA V, OBBLIGAZIONE O where
     O.CD_CDS(+)=V.CD_CDS_DOC_ORI_RIPORTO
 AND O.ESERCIZIO(+)=V.ESERCIZIO_DOC_ORI_RIPORTO
 AND O.ESERCIZIO_ORIGINALE(+)=V.ESERCIZIO_DOC_ORI_ORI_RIPORTO
 AND O.PG_OBBLIGAZIONE(+)=V.PG_DOC_ORI_RIPORTO
 AND V.IS_DOC_OBB='Y'
 AND IS_DOCAMM_RIP_UNA_VOLTA(V.CD_TIPO_DOCUMENTO, V.CD_CDS,V.CD_UNITA_ORGANIZZATIVA,V.ESERCIZIO,V.PG_NUMERO_DOCUMENTO) = 'Y'
union all
select
V.CD_TIPO_DOCUMENTO,
V.CD_CDS,
V.CD_UNITA_ORGANIZZATIVA,
V.ESERCIZIO,
V.PG_NUMERO_DOCUMENTO,
V.CD_TERZO,
V.PG_RIGA,
V.CD_BENE_SERVIZIO,
V.DT_DA_COMPETENZA_COGE,
V.DT_A_COMPETENZA_COGE,
V.TI_ISTITUZ_COMMERC,
V.IM_TOTALE_DIVISA,
V.IM_IMPONIBILE,
V.IM_IVA,
V.IM_DIPONIBILE_NC,
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.FL_PGIRO,O.FL_PGIRO),
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.ESERCIZIO_EV,O.ESERCIZIO),
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.TI_APPARTENENZA_EV,O.TI_APPARTENENZA),
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.TI_GESTIONE_EV,O.TI_GESTIONE),
decode(V.ESERCIZIO,V.ESERCIZIO_DOC,V.CD_ELEMENTO_VOCE_EV,O.CD_ELEMENTO_VOCE)
from V_DOC_AMM_COGE_RIGA V, ACCERTAMENTO O where
     O.CD_CDS(+)=V.CD_CDS_DOC_ORI_RIPORTO
 AND O.ESERCIZIO(+)=V.ESERCIZIO_DOC_ORI_RIPORTO
 AND O.ESERCIZIO_ORIGINALE(+)=V.ESERCIZIO_DOC_ORI_ORI_RIPORTO
 AND O.PG_ACCERTAMENTO(+)=V.PG_DOC_ORI_RIPORTO
 AND V.IS_DOC_OBB='N'
 AND IS_DOCAMM_RIP_UNA_VOLTA(V.CD_TIPO_DOCUMENTO, V.CD_CDS,V.CD_UNITA_ORGANIZZATIVA,V.ESERCIZIO,V.PG_NUMERO_DOCUMENTO) = 'Y'
);

   COMMENT ON TABLE "V_DOC_AMM_COGE_RIGA_EPR"  IS 'Vista di estrazione dei dettagli di documento amministrativo con valorizzazioni a fini COGE.
Tale vista estrae solo DOCUMENTI parzialmente o totalmente riportati a nuovo esercizio da esercizio precedente, quello
di creazione del documento.';
