--------------------------------------------------------
--  DDL for View V_DPDG_AGGREGATO_SPE_VAR
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_DPDG_AGGREGATO_SPE_VAR" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "CD_CDS_ROOT", "DS_CDS_ROOT", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "CD_FUNZIONE", "DS_FUNZIONE", "CD_NATURA", "DS_NATURA", "CD_CDS", "DS_CDS", "IM_RH_CCS_COSTI", "IM_RI_CCS_SPESE_ODC", "IM_RJ_CCS_SPESE_ODC_ALTRA_UO", "IM_RK_CCS_SPESE_OGC", "IM_RL_CCS_SPESE_OGC_ALTRA_UO", "IM_RM_CSS_AMMORTAMENTI", "IM_RN_CSS_RIMANENZE", "IM_RO_CSS_ALTRI_COSTI", "IM_RP_CSS_VERSO_ALTRO_CDR", "IM_RQ_SSC_COSTI_ODC", "IM_RR_SSC_COSTI_ODC_ALTRA_UO", "IM_RS_SSC_COSTI_OGC", "IM_RT_SSC_COSTI_OGC_ALTRA_UO", "IM_RU_SPESE_COSTI_ALTRUI", "IM_RV_PAGAMENTI", "IM_RAA_A2_COSTI_FINALI", "IM_RAB_A2_COSTI_ALTRO_CDR", "IM_RAC_A2_SPESE_ODC", "IM_RAD_A2_SPESE_ODC_ALTRA_UO", "IM_RAE_A2_SPESE_OGC", "IM_RAF_A2_SPESE_OGC_ALTRA_UO", "IM_RAG_A2_SPESE_COSTI_ALTRUI", "IM_RAH_A3_COSTI_FINALI", "IM_RAI_A3_COSTI_ALTRO_CDR", "IM_RAL_A3_SPESE_ODC", "IM_RAM_A3_SPESE_ODC_ALTRA_UO", "IM_RAN_A3_SPESE_OGC", "IM_RAO_A3_SPESE_OGC_ALTRA_UO", "IM_RAP_A3_SPESE_COSTI_ALTRUI", "MIM_RH_CCS_COSTI", "MIM_RI_CCS_SPESE_ODC", "MIM_RJ_CCS_SPESE_ODC_ALTRA_UO", "MIM_RK_CCS_SPESE_OGC", "MIM_RL_CCS_SPESE_OGC_ALTRA_UO", "MIM_RM_CSS_AMMORTAMENTI", "MIM_RN_CSS_RIMANENZE", "MIM_RO_CSS_ALTRI_COSTI", "MIM_RP_CSS_VERSO_ALTRO_CDR", "MIM_RQ_SSC_COSTI_ODC", "MIM_RR_SSC_COSTI_ODC_ALTRA_UO", "MIM_RS_SSC_COSTI_OGC", "MIM_RT_SSC_COSTI_OGC_ALTRA_UO", "MIM_RU_SPESE_COSTI_ALTRUI", "MIM_RV_PAGAMENTI", "MIM_RAA_A2_COSTI_FINALI", "MIM_RAB_A2_COSTI_ALTRO_CDR", "MIM_RAC_A2_SPESE_ODC", "MIM_RAD_A2_SPESE_ODC_ALTRA_UO", "MIM_RAE_A2_SPESE_OGC", "MIM_RAF_A2_SPESE_OGC_ALTRA_UO", "MIM_RAG_A2_SPESE_COSTI_ALTRUI", "MIM_RAH_A3_COSTI_FINALI", "MIM_RAI_A3_COSTI_ALTRO_CDR", "MIM_RAL_A3_SPESE_ODC", "MIM_RAM_A3_SPESE_ODC_ALTRA_UO", "MIM_RAN_A3_SPESE_OGC", "MIM_RAO_A3_SPESE_OGC_ALTRA_UO", "MIM_RAP_A3_SPESE_COSTI_ALTRUI", "DIM_RH_CCS_COSTI", "DIM_RI_CCS_SPESE_ODC", "DIM_RJ_CCS_SPESE_ODC_ALTRA_UO", "DIM_RK_CCS_SPESE_OGC", "DIM_RL_CCS_SPESE_OGC_ALTRA_UO", "DIM_RM_CSS_AMMORTAMENTI", "DIM_RN_CSS_RIMANENZE", "DIM_RO_CSS_ALTRI_COSTI", "DIM_RP_CSS_VERSO_ALTRO_CDR", "DIM_RQ_SSC_COSTI_ODC", "DIM_RR_SSC_COSTI_ODC_ALTRA_UO", "DIM_RS_SSC_COSTI_OGC", "DIM_RT_SSC_COSTI_OGC_ALTRA_UO", "DIM_RU_SPESE_COSTI_ALTRUI", "DIM_RV_PAGAMENTI", "DIM_RAA_A2_COSTI_FINALI", "DIM_RAB_A2_COSTI_ALTRO_CDR", "DIM_RAC_A2_SPESE_ODC", "DIM_RAD_A2_SPESE_ODC_ALTRA_UO", "DIM_RAE_A2_SPESE_OGC", "DIM_RAF_A2_SPESE_OGC_ALTRA_UO", "DIM_RAG_A2_SPESE_COSTI_ALTRUI", "DIM_RAH_A3_COSTI_FINALI", "DIM_RAI_A3_COSTI_ALTRO_CDR", "DIM_RAL_A3_SPESE_ODC", "DIM_RAM_A3_SPESE_ODC_ALTRA_UO", "DIM_RAN_A3_SPESE_OGC", "DIM_RAO_A3_SPESE_OGC_ALTRA_UO", "DIM_RAP_A3_SPESE_COSTI_ALTRUI") AS 
  select
--
-- Date: 28/01/2003
-- Version: 1.1
--
-- Vista di estrazione dettagli aggregato correnti (con variazioni) e aggregato pre-variazioni
--
-- History:
--
-- Date: 23/01/2003
-- Version: 1.0
-- Creazione
--
-- Date: 28/01/2003
-- Version: 1.1
-- Modificata estrazione del pg_variazione con cui effettuare il paragone
--
-- Body:
--
a1.ESERCIZIO,
a1.CD_CENTRO_RESPONSABILITA,
d.DS_CDR,
h.CD_UNITA_ORGANIZZATIVA CD_CDS_ROOT,
h.DS_UNITA_ORGANIZZATIVA DS_CDS_ROOT,
a1.CD_ELEMENTO_VOCE,
DS_ELEMENTO_VOCE,
a1.CD_FUNZIONE,
b.DS_FUNZIONE,
a1.CD_NATURA,
c.DS_NATURA,
a1.CD_CDS,
e.DS_UNITA_ORGANIZZATIVA DS_CDS,
sum(IM_RH_CCS_COSTI),
sum(IM_RI_CCS_SPESE_ODC),
sum(IM_RJ_CCS_SPESE_ODC_ALTRA_UO),
sum(IM_RK_CCS_SPESE_OGC),
sum(IM_RL_CCS_SPESE_OGC_ALTRA_UO),
sum(IM_RM_CSS_AMMORTAMENTI),
sum(IM_RN_CSS_RIMANENZE),
sum(IM_RO_CSS_ALTRI_COSTI),
sum(IM_RP_CSS_VERSO_ALTRO_CDR),
sum(IM_RQ_SSC_COSTI_ODC),
sum(IM_RR_SSC_COSTI_ODC_ALTRA_UO),
sum(IM_RS_SSC_COSTI_OGC),
sum(IM_RT_SSC_COSTI_OGC_ALTRA_UO),
sum(IM_RU_SPESE_COSTI_ALTRUI),
sum(IM_RV_PAGAMENTI),
sum(IM_RAA_A2_COSTI_FINALI),
sum(IM_RAB_A2_COSTI_ALTRO_CDR),
sum(IM_RAC_A2_SPESE_ODC),
sum(IM_RAD_A2_SPESE_ODC_ALTRA_UO),
sum(IM_RAE_A2_SPESE_OGC),
sum(IM_RAF_A2_SPESE_OGC_ALTRA_UO),
sum(IM_RAG_A2_SPESE_COSTI_ALTRUI),
sum(IM_RAH_A3_COSTI_FINALI),
sum(IM_RAI_A3_COSTI_ALTRO_CDR),
sum(IM_RAL_A3_SPESE_ODC),
sum(IM_RAM_A3_SPESE_ODC_ALTRA_UO),
sum(IM_RAN_A3_SPESE_OGC),
sum(IM_RAO_A3_SPESE_OGC_ALTRA_UO),
sum(IM_RAP_A3_SPESE_COSTI_ALTRUI),
sum(MIM_RH_CCS_COSTI), sum(MIM_RI_CCS_SPESE_ODC), sum(MIM_RJ_CCS_SPESE_ODC_ALTRA_UO), sum(MIM_RK_CCS_SPESE_OGC),
sum(MIM_RL_CCS_SPESE_OGC_ALTRA_UO), sum(MIM_RM_CSS_AMMORTAMENTI), sum(MIM_RN_CSS_RIMANENZE), sum(MIM_RO_CSS_ALTRI_COSTI),
sum(MIM_RP_CSS_VERSO_ALTRO_CDR), sum(MIM_RQ_SSC_COSTI_ODC), sum(MIM_RR_SSC_COSTI_ODC_ALTRA_UO), sum(MIM_RS_SSC_COSTI_OGC),
sum(MIM_RT_SSC_COSTI_OGC_ALTRA_UO), sum(MIM_RU_SPESE_COSTI_ALTRUI), sum(MIM_RV_PAGAMENTI), sum(MIM_RAA_A2_COSTI_FINALI),
sum(MIM_RAB_A2_COSTI_ALTRO_CDR), sum(MIM_RAC_A2_SPESE_ODC), sum(MIM_RAD_A2_SPESE_ODC_ALTRA_UO), sum(MIM_RAE_A2_SPESE_OGC),
sum(MIM_RAF_A2_SPESE_OGC_ALTRA_UO), sum(MIM_RAG_A2_SPESE_COSTI_ALTRUI), sum(MIM_RAH_A3_COSTI_FINALI), sum(MIM_RAI_A3_COSTI_ALTRO_CDR),
sum(MIM_RAL_A3_SPESE_ODC), sum(MIM_RAM_A3_SPESE_ODC_ALTRA_UO), sum(MIM_RAN_A3_SPESE_OGC), sum(MIM_RAO_A3_SPESE_OGC_ALTRA_UO),
sum(MIM_RAP_A3_SPESE_COSTI_ALTRUI),
sum(MIM_RH_CCS_COSTI-IM_RH_CCS_COSTI), sum(MIM_RI_CCS_SPESE_ODC-IM_RI_CCS_SPESE_ODC), sum(MIM_RJ_CCS_SPESE_ODC_ALTRA_UO-IM_RJ_CCS_SPESE_ODC_ALTRA_UO), sum(MIM_RK_CCS_SPESE_OGC-IM_RK_CCS_SPESE_OGC),
sum(MIM_RL_CCS_SPESE_OGC_ALTRA_UO-IM_RL_CCS_SPESE_OGC_ALTRA_UO), sum(MIM_RM_CSS_AMMORTAMENTI-IM_RM_CSS_AMMORTAMENTI), sum(MIM_RN_CSS_RIMANENZE-IM_RN_CSS_RIMANENZE), sum(MIM_RO_CSS_ALTRI_COSTI-IM_RO_CSS_ALTRI_COSTI),
sum(MIM_RP_CSS_VERSO_ALTRO_CDR-IM_RP_CSS_VERSO_ALTRO_CDR), sum(MIM_RQ_SSC_COSTI_ODC-IM_RQ_SSC_COSTI_ODC), sum(MIM_RR_SSC_COSTI_ODC_ALTRA_UO-IM_RR_SSC_COSTI_ODC_ALTRA_UO), sum(MIM_RS_SSC_COSTI_OGC-IM_RS_SSC_COSTI_OGC),
sum(MIM_RT_SSC_COSTI_OGC_ALTRA_UO-IM_RT_SSC_COSTI_OGC_ALTRA_UO), sum(MIM_RU_SPESE_COSTI_ALTRUI-IM_RU_SPESE_COSTI_ALTRUI), sum(MIM_RV_PAGAMENTI-IM_RV_PAGAMENTI), sum(MIM_RAA_A2_COSTI_FINALI-IM_RAA_A2_COSTI_FINALI),
sum(MIM_RAB_A2_COSTI_ALTRO_CDR-IM_RAB_A2_COSTI_ALTRO_CDR), sum(MIM_RAC_A2_SPESE_ODC-IM_RAC_A2_SPESE_ODC), sum(MIM_RAD_A2_SPESE_ODC_ALTRA_UO-IM_RAD_A2_SPESE_ODC_ALTRA_UO), sum(MIM_RAE_A2_SPESE_OGC-IM_RAE_A2_SPESE_OGC),
sum(MIM_RAF_A2_SPESE_OGC_ALTRA_UO-IM_RAF_A2_SPESE_OGC_ALTRA_UO), sum(MIM_RAG_A2_SPESE_COSTI_ALTRUI-IM_RAG_A2_SPESE_COSTI_ALTRUI), sum(MIM_RAH_A3_COSTI_FINALI-IM_RAH_A3_COSTI_FINALI), sum(MIM_RAI_A3_COSTI_ALTRO_CDR-IM_RAI_A3_COSTI_ALTRO_CDR),
sum(MIM_RAL_A3_SPESE_ODC-IM_RAL_A3_SPESE_ODC), sum(MIM_RAM_A3_SPESE_ODC_ALTRA_UO-IM_RAM_A3_SPESE_ODC_ALTRA_UO), sum(MIM_RAN_A3_SPESE_OGC-IM_RAN_A3_SPESE_OGC), sum(MIM_RAO_A3_SPESE_OGC_ALTRA_UO-IM_RAO_A3_SPESE_OGC_ALTRA_UO),
sum(MIM_RAP_A3_SPESE_COSTI_ALTRUI-IM_RAP_A3_SPESE_COSTI_ALTRUI)
from (
select
a.ESERCIZIO ESERCIZIO,
a.CD_CENTRO_RESPONSABILITA CD_CENTRO_RESPONSABILITA,
a.CD_CDS CD_CDS,
a.TI_APPARTENENZA TI_APPARTENENZA,
a.TI_GESTIONE TI_GESTIONE,
a.CD_ELEMENTO_VOCE CD_ELEMENTO_VOCE,
a.CD_FUNZIONE CD_FUNZIONE,
a.CD_NATURA CD_NATURA,
0 IM_RH_CCS_COSTI,
0 IM_RI_CCS_SPESE_ODC,
0 IM_RJ_CCS_SPESE_ODC_ALTRA_UO,
0 IM_RK_CCS_SPESE_OGC,
0 IM_RL_CCS_SPESE_OGC_ALTRA_UO,
0 IM_RM_CSS_AMMORTAMENTI,
0 IM_RN_CSS_RIMANENZE,
0 IM_RO_CSS_ALTRI_COSTI,
0 IM_RP_CSS_VERSO_ALTRO_CDR,
0 IM_RQ_SSC_COSTI_ODC,
0 IM_RR_SSC_COSTI_ODC_ALTRA_UO,
0 IM_RS_SSC_COSTI_OGC,
0 IM_RT_SSC_COSTI_OGC_ALTRA_UO,
0 IM_RU_SPESE_COSTI_ALTRUI,
0 IM_RV_PAGAMENTI,
0 IM_RAA_A2_COSTI_FINALI,
0 IM_RAB_A2_COSTI_ALTRO_CDR,
0 IM_RAC_A2_SPESE_ODC,
0 IM_RAD_A2_SPESE_ODC_ALTRA_UO,
0 IM_RAE_A2_SPESE_OGC,
0 IM_RAF_A2_SPESE_OGC_ALTRA_UO,
0 IM_RAG_A2_SPESE_COSTI_ALTRUI,
0 IM_RAH_A3_COSTI_FINALI,
0 IM_RAI_A3_COSTI_ALTRO_CDR,
0 IM_RAL_A3_SPESE_ODC,
0 IM_RAM_A3_SPESE_ODC_ALTRA_UO,
0 IM_RAN_A3_SPESE_OGC,
0 IM_RAO_A3_SPESE_OGC_ALTRA_UO,
0 IM_RAP_A3_SPESE_COSTI_ALTRUI,
a.IM_RH_CCS_COSTI MIM_RH_CCS_COSTI,
a.IM_RI_CCS_SPESE_ODC MIM_RI_CCS_SPESE_ODC,
a.IM_RJ_CCS_SPESE_ODC_ALTRA_UO MIM_RJ_CCS_SPESE_ODC_ALTRA_UO,
a.IM_RK_CCS_SPESE_OGC MIM_RK_CCS_SPESE_OGC,
a.IM_RL_CCS_SPESE_OGC_ALTRA_UO MIM_RL_CCS_SPESE_OGC_ALTRA_UO,
a.IM_RM_CSS_AMMORTAMENTI MIM_RM_CSS_AMMORTAMENTI,
a.IM_RN_CSS_RIMANENZE MIM_RN_CSS_RIMANENZE,
a.IM_RO_CSS_ALTRI_COSTI MIM_RO_CSS_ALTRI_COSTI,
a.IM_RP_CSS_VERSO_ALTRO_CDR MIM_RP_CSS_VERSO_ALTRO_CDR,
a.IM_RQ_SSC_COSTI_ODC MIM_RQ_SSC_COSTI_ODC,
a.IM_RR_SSC_COSTI_ODC_ALTRA_UO MIM_RR_SSC_COSTI_ODC_ALTRA_UO,
a.IM_RS_SSC_COSTI_OGC MIM_RS_SSC_COSTI_OGC,
a.IM_RT_SSC_COSTI_OGC_ALTRA_UO MIM_RT_SSC_COSTI_OGC_ALTRA_UO,
a.IM_RU_SPESE_COSTI_ALTRUI MIM_RU_SPESE_COSTI_ALTRUI,
a.IM_RV_PAGAMENTI MIM_RV_PAGAMENTI,
a.IM_RAA_A2_COSTI_FINALI MIM_RAA_A2_COSTI_FINALI,
a.IM_RAB_A2_COSTI_ALTRO_CDR MIM_RAB_A2_COSTI_ALTRO_CDR,
a.IM_RAC_A2_SPESE_ODC MIM_RAC_A2_SPESE_ODC,
a.IM_RAD_A2_SPESE_ODC_ALTRA_UO MIM_RAD_A2_SPESE_ODC_ALTRA_UO,
a.IM_RAE_A2_SPESE_OGC MIM_RAE_A2_SPESE_OGC,
a.IM_RAF_A2_SPESE_OGC_ALTRA_UO MIM_RAF_A2_SPESE_OGC_ALTRA_UO,
a.IM_RAG_A2_SPESE_COSTI_ALTRUI MIM_RAG_A2_SPESE_COSTI_ALTRUI,
a.IM_RAH_A3_COSTI_FINALI MIM_RAH_A3_COSTI_FINALI,
a.IM_RAI_A3_COSTI_ALTRO_CDR MIM_RAI_A3_COSTI_ALTRO_CDR,
a.IM_RAL_A3_SPESE_ODC MIM_RAL_A3_SPESE_ODC,
a.IM_RAM_A3_SPESE_ODC_ALTRA_UO MIM_RAM_A3_SPESE_ODC_ALTRA_UO,
a.IM_RAN_A3_SPESE_OGC MIM_RAN_A3_SPESE_OGC,
a.IM_RAO_A3_SPESE_OGC_ALTRA_UO MIM_RAO_A3_SPESE_OGC_ALTRA_UO,
a.IM_RAP_A3_SPESE_COSTI_ALTRUI MIM_RAP_A3_SPESE_COSTI_ALTRUI
from PDG_AGGREGATO_SPE_DET a
where
     a.ti_aggregato = 'M'
 and (
           a.IM_RH_CCS_COSTI!=0
        or a.IM_RI_CCS_SPESE_ODC!=0
        or a.IM_RJ_CCS_SPESE_ODC_ALTRA_UO!=0
        or a.IM_RK_CCS_SPESE_OGC!=0
        or a.IM_RL_CCS_SPESE_OGC_ALTRA_UO!=0
        or a.IM_RM_CSS_AMMORTAMENTI!=0
        or a.IM_RN_CSS_RIMANENZE!=0
        or a.IM_RO_CSS_ALTRI_COSTI!=0
        or a.IM_RP_CSS_VERSO_ALTRO_CDR!=0
        or a.IM_RQ_SSC_COSTI_ODC!=0
        or a.IM_RR_SSC_COSTI_ODC_ALTRA_UO!=0
        or a.IM_RS_SSC_COSTI_OGC!=0
        or a.IM_RT_SSC_COSTI_OGC_ALTRA_UO!=0
        or a.IM_RU_SPESE_COSTI_ALTRUI!=0
        or a.IM_RV_PAGAMENTI!=0
        or a.IM_RAA_A2_COSTI_FINALI!=0
        or a.IM_RAB_A2_COSTI_ALTRO_CDR!=0
        or a.IM_RAC_A2_SPESE_ODC!=0
        or a.IM_RAD_A2_SPESE_ODC_ALTRA_UO!=0
        or a.IM_RAE_A2_SPESE_OGC!=0
        or a.IM_RAF_A2_SPESE_OGC_ALTRA_UO!=0
        or a.IM_RAG_A2_SPESE_COSTI_ALTRUI!=0
        or a.IM_RAH_A3_COSTI_FINALI!=0
        or a.IM_RAI_A3_COSTI_ALTRO_CDR!=0
        or a.IM_RAL_A3_SPESE_ODC!=0
        or a.IM_RAM_A3_SPESE_ODC_ALTRA_UO!=0
        or a.IM_RAN_A3_SPESE_OGC!=0
        or a.IM_RAO_A3_SPESE_OGC_ALTRA_UO!=0
        or a.IM_RAP_A3_SPESE_COSTI_ALTRUI!=0
)
union
select
a.ESERCIZIO ESERCIZIO,
a.CD_CENTRO_RESPONSABILITA CD_CENTRO_RESPONSABILITA,
a.CD_CDS CD_CDS,
a.TI_APPARTENENZA TI_APPARTENENZA,
a.TI_GESTIONE TI_GESTIONE,
a.CD_ELEMENTO_VOCE CD_ELEMENTO_VOCE,
a.CD_FUNZIONE CD_FUNZIONE,
a.CD_NATURA CD_NATURA,
a.IM_RH_CCS_COSTI IM_RH_CCS_COSTI,
a.IM_RI_CCS_SPESE_ODC IM_RI_CCS_SPESE_ODC,
a.IM_RJ_CCS_SPESE_ODC_ALTRA_UO IM_RJ_CCS_SPESE_ODC_ALTRA_UO,
a.IM_RK_CCS_SPESE_OGC IM_RK_CCS_SPESE_OGC,
a.IM_RL_CCS_SPESE_OGC_ALTRA_UO IM_RL_CCS_SPESE_OGC_ALTRA_UO,
a.IM_RM_CSS_AMMORTAMENTI IM_RM_CSS_AMMORTAMENTI,
a.IM_RN_CSS_RIMANENZE IM_RN_CSS_RIMANENZE,
a.IM_RO_CSS_ALTRI_COSTI IM_RO_CSS_ALTRI_COSTI,
a.IM_RP_CSS_VERSO_ALTRO_CDR IM_RP_CSS_VERSO_ALTRO_CDR,
a.IM_RQ_SSC_COSTI_ODC IM_RQ_SSC_COSTI_ODC,
a.IM_RR_SSC_COSTI_ODC_ALTRA_UO IM_RR_SSC_COSTI_ODC_ALTRA_UO,
a.IM_RS_SSC_COSTI_OGC IM_RS_SSC_COSTI_OGC,
a.IM_RT_SSC_COSTI_OGC_ALTRA_UO IM_RT_SSC_COSTI_OGC_ALTRA_UO,
a.IM_RU_SPESE_COSTI_ALTRUI IM_RU_SPESE_COSTI_ALTRUI,
a.IM_RV_PAGAMENTI IM_RV_PAGAMENTI,
a.IM_RAA_A2_COSTI_FINALI IM_RAA_A2_COSTI_FINALI,
a.IM_RAB_A2_COSTI_ALTRO_CDR IM_RAB_A2_COSTI_ALTRO_CDR,
a.IM_RAC_A2_SPESE_ODC IM_RAC_A2_SPESE_ODC,
a.IM_RAD_A2_SPESE_ODC_ALTRA_UO IM_RAD_A2_SPESE_ODC_ALTRA_UO,
a.IM_RAE_A2_SPESE_OGC IM_RAE_A2_SPESE_OGC,
a.IM_RAF_A2_SPESE_OGC_ALTRA_UO IM_RAF_A2_SPESE_OGC_ALTRA_UO,
a.IM_RAG_A2_SPESE_COSTI_ALTRUI IM_RAG_A2_SPESE_COSTI_ALTRUI,
a.IM_RAH_A3_COSTI_FINALI IM_RAH_A3_COSTI_FINALI,
a.IM_RAI_A3_COSTI_ALTRO_CDR IM_RAI_A3_COSTI_ALTRO_CDR,
a.IM_RAL_A3_SPESE_ODC IM_RAL_A3_SPESE_ODC,
a.IM_RAM_A3_SPESE_ODC_ALTRA_UO IM_RAM_A3_SPESE_ODC_ALTRA_UO,
a.IM_RAN_A3_SPESE_OGC IM_RAN_A3_SPESE_OGC,
a.IM_RAO_A3_SPESE_OGC_ALTRA_UO IM_RAO_A3_SPESE_OGC_ALTRA_UO,
a.IM_RAP_A3_SPESE_COSTI_ALTRUI IM_RAP_A3_SPESE_COSTI_ALTRUI,
0 MIM_RH_CCS_COSTI,
0 MIM_RI_CCS_SPESE_ODC,
0 MIM_RJ_CCS_SPESE_ODC_ALTRA_UO,
0 MIM_RK_CCS_SPESE_OGC,
0 MIM_RL_CCS_SPESE_OGC_ALTRA_UO,
0 MIM_RM_CSS_AMMORTAMENTI,
0 MIM_RN_CSS_RIMANENZE,
0 MIM_RO_CSS_ALTRI_COSTI,
0 MIM_RP_CSS_VERSO_ALTRO_CDR,
0 MIM_RQ_SSC_COSTI_ODC,
0 MIM_RR_SSC_COSTI_ODC_ALTRA_UO,
0 MIM_RS_SSC_COSTI_OGC,
0 MIM_RT_SSC_COSTI_OGC_ALTRA_UO,
0 MIM_RU_SPESE_COSTI_ALTRUI,
0 MIM_RV_PAGAMENTI,
0 MIM_RAA_A2_COSTI_FINALI,
0 MIM_RAB_A2_COSTI_ALTRO_CDR,
0 MIM_RAC_A2_SPESE_ODC,
0 MIM_RAD_A2_SPESE_ODC_ALTRA_UO,
0 MIM_RAE_A2_SPESE_OGC,
0 MIM_RAF_A2_SPESE_OGC_ALTRA_UO,
0 MIM_RAG_A2_SPESE_COSTI_ALTRUI,
0 MIM_RAH_A3_COSTI_FINALI,
0 MIM_RAI_A3_COSTI_ALTRO_CDR,
0 MIM_RAL_A3_SPESE_ODC,
0 MIM_RAM_A3_SPESE_ODC_ALTRA_UO,
0 MIM_RAN_A3_SPESE_OGC,
0 MIM_RAO_A3_SPESE_OGC_ALTRA_UO,
0 MIM_RAP_A3_SPESE_COSTI_ALTRUI
from PDG_AGGREGATO_SPE_VAR a, PDG_PREVENTIVO_VAR b
where
     a.esercizio = b.esercizio
 and a.cd_centro_responsabilita =b.cd_centro_responsabilita
 and a.pg_variazione_pdg = b.pg_variazione_pdg
 and b.pg_variazione_pdg =
			  (select max(pg_variazione_pdg)-1 from PDG_PREVENTIVO_VAR
                   where
                         esercizio = a.esercizio
                     and cd_centro_responsabilita = a.cd_centro_responsabilita )
 and (
           a.IM_RH_CCS_COSTI!=0
        or a.IM_RI_CCS_SPESE_ODC!=0
        or a.IM_RJ_CCS_SPESE_ODC_ALTRA_UO!=0
        or a.IM_RK_CCS_SPESE_OGC!=0
        or a.IM_RL_CCS_SPESE_OGC_ALTRA_UO!=0
        or a.IM_RM_CSS_AMMORTAMENTI!=0
        or a.IM_RN_CSS_RIMANENZE!=0
        or a.IM_RO_CSS_ALTRI_COSTI!=0
        or a.IM_RP_CSS_VERSO_ALTRO_CDR!=0
        or a.IM_RQ_SSC_COSTI_ODC!=0
        or a.IM_RR_SSC_COSTI_ODC_ALTRA_UO!=0
        or a.IM_RS_SSC_COSTI_OGC!=0
        or a.IM_RT_SSC_COSTI_OGC_ALTRA_UO!=0
        or a.IM_RU_SPESE_COSTI_ALTRUI!=0
        or a.IM_RV_PAGAMENTI!=0
        or a.IM_RAA_A2_COSTI_FINALI!=0
        or a.IM_RAB_A2_COSTI_ALTRO_CDR!=0
        or a.IM_RAC_A2_SPESE_ODC!=0
        or a.IM_RAD_A2_SPESE_ODC_ALTRA_UO!=0
        or a.IM_RAE_A2_SPESE_OGC!=0
        or a.IM_RAF_A2_SPESE_OGC_ALTRA_UO!=0
        or a.IM_RAG_A2_SPESE_COSTI_ALTRUI!=0
        or a.IM_RAH_A3_COSTI_FINALI!=0
        or a.IM_RAI_A3_COSTI_ALTRO_CDR!=0
        or a.IM_RAL_A3_SPESE_ODC!=0
        or a.IM_RAM_A3_SPESE_ODC_ALTRA_UO!=0
        or a.IM_RAN_A3_SPESE_OGC!=0
        or a.IM_RAO_A3_SPESE_OGC_ALTRA_UO!=0
        or a.IM_RAP_A3_SPESE_COSTI_ALTRUI!=0
 )
) a1,
FUNZIONE b,
NATURA c,
CDR d,
UNITA_ORGANIZZATIVA e, -- CDS articolo
ELEMENTO_VOCE f,
UNITA_ORGANIZZATIVA g, -- UO del pdg
UNITA_ORGANIZZATIVA h -- CDS del pdg
where
b.cd_funzione = a1.cd_funzione
and c.cd_natura = a1.cd_natura
and d.cd_centro_responsabilita = a1.cd_centro_responsabilita
and e.cd_unita_organizzativa = a1.cd_cds
and f.esercizio = a1.esercizio
and f.ti_appartenenza = a1.ti_appartenenza
and f.ti_gestione = a1.ti_gestione
and f.cd_elemento_voce = a1.cd_elemento_voce
and g.cd_unita_organizzativa = d.cd_unita_organizzativa
and h.cd_unita_organizzativa = g.cd_unita_padre
and exists (select 1 from pdg_preventivo_var where
                esercizio = a1.esercizio
			and cd_centro_responsabilita = a1.cd_centro_responsabilita
			and pg_variazione_pdg > 0
		   )
group by
a1.ESERCIZIO,
a1.CD_CENTRO_RESPONSABILITA,
d.DS_CDR,
h.CD_UNITA_ORGANIZZATIVA,
h.DS_UNITA_ORGANIZZATIVA,
a1.CD_ELEMENTO_VOCE,
DS_ELEMENTO_VOCE,
a1.CD_FUNZIONE,
b.DS_FUNZIONE,
a1.CD_NATURA,
c.DS_NATURA,
a1.CD_CDS,
e.DS_UNITA_ORGANIZZATIVA
;

   COMMENT ON TABLE "V_DPDG_AGGREGATO_SPE_VAR"  IS 'Vista di estrazione dettagli aggregato correnti (con variazioni) e aggregato pre-variazioni';
