--------------------------------------------------------
--  DDL for View V_ELEMENTO_VOCE_ASSESTATO
--------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "V_ELEMENTO_VOCE_ASSESTATO" ("ESERCIZIO", "CD_ELEMENTO_VOCE", "TI_APPARTENENZA", "TI_GESTIONE", "TI_ELEMENTO_VOCE", "CD_PARTE", "CD_PROPRIO_ELEMENTO", "DS_ELEMENTO_VOCE", "DUVA", "CD_ELEMENTO_PADRE", "UTUV", "DACR", "UTCR", "PG_VER_REC", "FL_LIMITE_ASS_OBBLIG", "FL_VOCE_PERSONALE", "FL_PARTITA_GIRO", "CD_CAPOCONTO_FIN", "FL_VOCE_SAC", "FL_VOCE_NON_SOGG_IMP_AUT", "ESERCIZIO_CLA_S", "COD_CLA_S", "ESERCIZIO_CLA_E", "COD_CLA_E", "FL_RECON", "FL_INV_BENI_PATR", "FL_VOCE_FONDO", "FL_CHECK_TERZO_SIOPE", "ID_CLASSIFICAZIONE",  "FL_INV_BENI_COMP", "FL_LIMITE_SPESA", "FL_PRELIEVO", "FL_SOGGETTO_PRELIEVO", "PERC_PRELIEVO_PDGP_ENTRATE", "FL_SOLO_RESIDUO", "FL_SOLO_COMPETENZA", "FL_TROVATO", "FL_MISSIONI", "FL_AZZERA_RESIDUI", "ESERCIZIO_ELEMENTO_PADRE", "TI_APPARTENENZA_ELEMENTO_PADRE", "TI_GESTIONE_ELEMENTO_PADRE", "CD_UNITA_PIANO", "CD_VOCE_PIANO", "GG_DEROGA_OBBL_COMP_PRG_SCAD", "GG_DEROGA_OBBL_RES_PRG_SCAD", "FL_COMUNICA_PAGAMENTI", "FL_LIMITE_COMPETENZA", "BLOCCO_IMPEGNI_NATFIN", "CD_CDR_BILANCIO", "ESERCIZIO_BILANCIO", "IMPORTO_ASSESTATO_BILANCIO", "IMPORTO_UTILIZZATO_BILANCIO", "IMPORTO_DISPONIBILE_BILANCIO") AS
  SELECT  A.ESERCIZIO
      --
      -- Date: 16/05/2007
      -- Version: 1.7
      --
      -- Estrae tutti gli elementi voce con gli importi del bilancio
      --
      -- History:
      --
      -- Date: 25/09/2001
      -- Version: 1.0
      -- Creazione
      --
      -- Body:
      --
     , A.CD_ELEMENTO_VOCE
     , A.TI_APPARTENENZA
     , A.TI_GESTIONE
     , A.TI_ELEMENTO_VOCE
     , A.CD_PARTE
     , A.CD_PROPRIO_ELEMENTO
     , A.DS_ELEMENTO_VOCE
     , A.DUVA
     , A.CD_ELEMENTO_PADRE
     , A.UTUV
     , A.DACR
     , A.UTCR
     , A.PG_VER_REC
     , A.FL_LIMITE_ASS_OBBLIG
     , A.FL_VOCE_PERSONALE
     , A.FL_PARTITA_GIRO
     , A.CD_CAPOCONTO_FIN
     , A.FL_VOCE_SAC
     , A.FL_VOCE_NON_SOGG_IMP_AUT
     , A.ESERCIZIO_CLA_S
     , A.COD_CLA_S
     , A.ESERCIZIO_CLA_E
     , A.COD_CLA_E
     , A.FL_RECON
     , A.FL_INV_BENI_PATR
     , A.FL_VOCE_FONDO
     , A.FL_CHECK_TERZO_SIOPE
     , A.ID_CLASSIFICAZIONE
     , A.FL_INV_BENI_COMP
     , A.fl_limite_spesa
     , A.FL_PRELIEVO
     , A.FL_SOGGETTO_PRELIEVO
     , A.PERC_PRELIEVO_PDGP_ENTRATE
     , A.FL_SOLO_RESIDUO
     , A.FL_SOLO_COMPETENZA
     , A.FL_TROVATO
     , A.FL_MISSIONI
     , A.FL_AZZERA_RESIDUI
     , A.ESERCIZIO_ELEMENTO_PADRE
     , A.TI_APPARTENENZA_ELEMENTO_PADRE
     , A.TI_GESTIONE_ELEMENTO_PADRE
     , A.CD_UNITA_PIANO
     , A.CD_VOCE_PIANO
     , A.GG_DEROGA_OBBL_COMP_PRG_SCAD
     , A.GG_DEROGA_OBBL_RES_PRG_SCAD
     , A.FL_COMUNICA_PAGAMENTI
     , A.FL_LIMITE_COMPETENZA
     , A.BLOCCO_IMPEGNI_NATFIN
     , A.CD_CDR_BILANCIO
     , A.ESERCIZIO_BILANCIO
     , nvl(SUM(A.IMPORTO_ASSESTATO_BILANCIO), 0) IMPORTO_ASSESTATO_BILANCIO
     , nvl(SUM(A.IMPORTO_UTILIZZATO_BILANCIO), 0) IMPORTO_UTILIZZATO_BILANCIO
     , nvl(SUM(A.IMPORTO_DISPONIBILE_BILANCIO), 0) IMPORTO_DISPONIBILE_BILANCIO
FROM (
  SELECT  ELEMENTO_VOCE.ESERCIZIO
      --
      -- Date: 16/05/2007
      -- Version: 1.7
      --
      -- Estrae tutti gli elementi voce con gli importi del bilancio
      --
      -- History:
      --
      -- Date: 25/09/2001
      -- Version: 1.0
      -- Creazione
      --
			-- Body:
			--
     , ELEMENTO_VOCE.CD_ELEMENTO_VOCE
     , ELEMENTO_VOCE.TI_APPARTENENZA
     , ELEMENTO_VOCE.TI_GESTIONE
     , ELEMENTO_VOCE.TI_ELEMENTO_VOCE
     , ELEMENTO_VOCE.CD_PARTE
     , ELEMENTO_VOCE.CD_PROPRIO_ELEMENTO
     , ELEMENTO_VOCE.DS_ELEMENTO_VOCE
     , ELEMENTO_VOCE.DUVA
     , ELEMENTO_VOCE.CD_ELEMENTO_PADRE
     , ELEMENTO_VOCE.UTUV
     , ELEMENTO_VOCE.DACR
     , ELEMENTO_VOCE.UTCR
     , ELEMENTO_VOCE.PG_VER_REC
     , ELEMENTO_VOCE.FL_LIMITE_ASS_OBBLIG
     , ELEMENTO_VOCE.FL_VOCE_PERSONALE
     , ELEMENTO_VOCE.FL_PARTITA_GIRO
     , ELEMENTO_VOCE.CD_CAPOCONTO_FIN
     , ELEMENTO_VOCE.FL_VOCE_SAC
     , ELEMENTO_VOCE.FL_VOCE_NON_SOGG_IMP_AUT
     , ELEMENTO_VOCE.ESERCIZIO_CLA_S
     , ELEMENTO_VOCE.COD_CLA_S
     , ELEMENTO_VOCE.ESERCIZIO_CLA_E
     , ELEMENTO_VOCE.COD_CLA_E
     , ELEMENTO_VOCE.FL_RECON
     , ELEMENTO_VOCE.FL_INV_BENI_PATR
     , ELEMENTO_VOCE.FL_VOCE_FONDO
     , ELEMENTO_VOCE.FL_CHECK_TERZO_SIOPE
     , ELEMENTO_VOCE.ID_CLASSIFICAZIONE
     , ELEMENTO_VOCE.FL_INV_BENI_COMP
     , Elemento_voce.fl_limite_spesa
     , ELEMENTO_VOCE.FL_PRELIEVO
     , ELEMENTO_VOCE.FL_SOGGETTO_PRELIEVO
     , ELEMENTO_VOCE.PERC_PRELIEVO_PDGP_ENTRATE
     , ELEMENTO_VOCE.FL_SOLO_RESIDUO
     , ELEMENTO_VOCE.FL_SOLO_COMPETENZA
     , ELEMENTO_VOCE.FL_TROVATO
     , ELEMENTO_VOCE.FL_MISSIONI
     , ELEMENTO_VOCE.FL_AZZERA_RESIDUI
     , ELEMENTO_VOCE.ESERCIZIO_ELEMENTO_PADRE
     , ELEMENTO_VOCE.TI_APPARTENENZA_ELEMENTO_PADRE
     , ELEMENTO_VOCE.TI_GESTIONE_ELEMENTO_PADRE
     , ELEMENTO_VOCE.CD_UNITA_PIANO
     , ELEMENTO_VOCE.CD_VOCE_PIANO
     , ELEMENTO_VOCE.GG_DEROGA_OBBL_COMP_PRG_SCAD
     , ELEMENTO_VOCE.GG_DEROGA_OBBL_RES_PRG_SCAD
     , ELEMENTO_VOCE.FL_COMUNICA_PAGAMENTI
     , ELEMENTO_VOCE.FL_LIMITE_COMPETENZA
     , ELEMENTO_VOCE.BLOCCO_IMPEGNI_NATFIN
     , CDR.CD_CENTRO_RESPONSABILITA CD_CDR_BILANCIO
     , ELEMENTO_VOCE.ESERCIZIO ESERCIZIO_BILANCIO
     , 0 IMPORTO_ASSESTATO_BILANCIO
     , 0 IMPORTO_UTILIZZATO_BILANCIO
     , 0 IMPORTO_DISPONIBILE_BILANCIO
  From ELEMENTO_VOCE,
       CDR
  UNION ALL
  SELECT ELEMENTO_VOCE.ESERCIZIO                              --
     , ELEMENTO_VOCE.CD_ELEMENTO_VOCE
     , ELEMENTO_VOCE.TI_APPARTENENZA
     , ELEMENTO_VOCE.TI_GESTIONE
     , ELEMENTO_VOCE.TI_ELEMENTO_VOCE
     , ELEMENTO_VOCE.CD_PARTE
     , ELEMENTO_VOCE.CD_PROPRIO_ELEMENTO
     , ELEMENTO_VOCE.DS_ELEMENTO_VOCE
     , ELEMENTO_VOCE.DUVA
     , ELEMENTO_VOCE.CD_ELEMENTO_PADRE
     , ELEMENTO_VOCE.UTUV
     , ELEMENTO_VOCE.DACR
     , ELEMENTO_VOCE.UTCR
     , ELEMENTO_VOCE.PG_VER_REC
     , ELEMENTO_VOCE.FL_LIMITE_ASS_OBBLIG
     , ELEMENTO_VOCE.FL_VOCE_PERSONALE
     , ELEMENTO_VOCE.FL_PARTITA_GIRO
     , ELEMENTO_VOCE.CD_CAPOCONTO_FIN
     , ELEMENTO_VOCE.FL_VOCE_SAC
     , ELEMENTO_VOCE.FL_VOCE_NON_SOGG_IMP_AUT
     , ELEMENTO_VOCE.ESERCIZIO_CLA_S
     , ELEMENTO_VOCE.COD_CLA_S
     , ELEMENTO_VOCE.ESERCIZIO_CLA_E
     , ELEMENTO_VOCE.COD_CLA_E
     , ELEMENTO_VOCE.FL_RECON
     , ELEMENTO_VOCE.FL_INV_BENI_PATR
     , ELEMENTO_VOCE.FL_VOCE_FONDO
     , ELEMENTO_VOCE.FL_CHECK_TERZO_SIOPE
     , ELEMENTO_VOCE.ID_CLASSIFICAZIONE
     , ELEMENTO_VOCE.FL_INV_BENI_COMP
     , Elemento_voce.fl_limite_spesa
     , ELEMENTO_VOCE.FL_PRELIEVO
     , ELEMENTO_VOCE.FL_SOGGETTO_PRELIEVO
     , ELEMENTO_VOCE.PERC_PRELIEVO_PDGP_ENTRATE
     , ELEMENTO_VOCE.FL_SOLO_RESIDUO
     , ELEMENTO_VOCE.FL_SOLO_COMPETENZA
     , ELEMENTO_VOCE.FL_TROVATO
     , ELEMENTO_VOCE.FL_MISSIONI
     , ELEMENTO_VOCE.FL_AZZERA_RESIDUI
     , ELEMENTO_VOCE.ESERCIZIO_ELEMENTO_PADRE
     , ELEMENTO_VOCE.TI_APPARTENENZA_ELEMENTO_PADRE
     , ELEMENTO_VOCE.TI_GESTIONE_ELEMENTO_PADRE
     , ELEMENTO_VOCE.CD_UNITA_PIANO
     , ELEMENTO_VOCE.CD_VOCE_PIANO
     , ELEMENTO_VOCE.GG_DEROGA_OBBL_COMP_PRG_SCAD
     , ELEMENTO_VOCE.GG_DEROGA_OBBL_RES_PRG_SCAD
     , ELEMENTO_VOCE.FL_COMUNICA_PAGAMENTI
     , ELEMENTO_VOCE.FL_LIMITE_COMPETENZA
     , ELEMENTO_VOCE.BLOCCO_IMPEGNI_NATFIN
     , V_ASSESTATO.CD_CENTRO_RESPONSABILITA
     , V_ASSESTATO.ESERCIZIO_RES
     , V_ASSESTATO.ASSESTATO_INIZIALE
     , V_ASSESTATO.IMPORTO_UTILIZZATO
     , V_ASSESTATO.IMPORTO_DISPONIBILE
  From ELEMENTO_VOCE
     , V_ASSESTATO
 WHERE ELEMENTO_VOCE.ESERCIZIO = V_ASSESTATO.ESERCIZIO
   AND ELEMENTO_VOCE.TI_APPARTENENZA = V_ASSESTATO.TI_APPARTENENZA
   AND ELEMENTO_VOCE.TI_GESTIONE = V_ASSESTATO.TI_GESTIONE
   AND ELEMENTO_VOCE.CD_ELEMENTO_VOCE = V_ASSESTATO.CD_ELEMENTO_VOCE) A
GROUP BY A.ESERCIZIO
     , A.CD_ELEMENTO_VOCE
     , A.TI_APPARTENENZA
     , A.TI_GESTIONE
     , A.TI_ELEMENTO_VOCE
     , A.CD_PARTE
     , A.CD_PROPRIO_ELEMENTO
     , A.DS_ELEMENTO_VOCE
     , A.DUVA
     , A.CD_ELEMENTO_PADRE
     , A.UTUV
     , A.DACR
     , A.UTCR
     , A.PG_VER_REC
     , A.FL_LIMITE_ASS_OBBLIG
     , A.FL_VOCE_PERSONALE
     , A.FL_PARTITA_GIRO
     , A.CD_CAPOCONTO_FIN
     , A.FL_VOCE_SAC
     , A.FL_VOCE_NON_SOGG_IMP_AUT
     , A.ESERCIZIO_CLA_S
     , A.COD_CLA_S
     , A.ESERCIZIO_CLA_E
     , A.COD_CLA_E
     , A.FL_RECON
     , A.FL_INV_BENI_PATR
     , A.FL_VOCE_FONDO
     , A.FL_CHECK_TERZO_SIOPE
     , A.ID_CLASSIFICAZIONE
     , A.FL_INV_BENI_COMP
     , A.fl_limite_spesa
     , A.FL_PRELIEVO
     , A.FL_SOGGETTO_PRELIEVO
     , A.PERC_PRELIEVO_PDGP_ENTRATE
     , A.FL_SOLO_RESIDUO
     , A.FL_SOLO_COMPETENZA
     , A.FL_TROVATO
     , A.FL_MISSIONI
     , A.FL_AZZERA_RESIDUI
     , A.ESERCIZIO_ELEMENTO_PADRE
     , A.TI_APPARTENENZA_ELEMENTO_PADRE
     , A.TI_GESTIONE_ELEMENTO_PADRE
     , A.CD_UNITA_PIANO
     , A.CD_VOCE_PIANO
     , A.GG_DEROGA_OBBL_COMP_PRG_SCAD
     , A.GG_DEROGA_OBBL_RES_PRG_SCAD
     , A.FL_COMUNICA_PAGAMENTI
     , A.FL_LIMITE_COMPETENZA
     , A.BLOCCO_IMPEGNI_NATFIN
     , A.CD_CDR_BILANCIO
     , A.ESERCIZIO_BILANCIO;

COMMENT ON TABLE V_ELEMENTO_VOCE_ASSESTATO IS 'Estrae tutti gli elementi voce con le informazioni dei saldi di bilancio.';