--------------------------------------------------------
--  DDL for View V_ESTRAI_GLA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_ESTRAI_GLA" ("CD_UO_COMPENSO", "DT_CMP_DA_COMPENSO", "DT_CMP_A_COMPENSO", "DT_MANDATO", "ESERCIZIO_PAGAMENTO", "CD_TERZO", "CD_ANAG", "IMPONIBILE", "ALIQUOTA", "AMMONTARE", "CODICE_FISCALE", "NOME", "COGNOME", "TI_SESSO", "DT_NASCITA", "COMUNE_NASCITA", "PROVINCIA_NASCITA", "COMUNE_RESIDENZA", "PROVINCIA_RESIDENZA", "CAP_RESIDENZA", "VIA", "NUM_CIVICO", "DENOMINAZIONE_SEDE", "VIA_SEDE", "CIVICO_SEDE", "CAP_SEDE", "COD_FIS_CNR", "DS_CNR", "COMUNE_CNR", "IND_CNR", "CIV_CNR", "CAP_CNR", "DATA_F24", "NOTA") AS 
  Select  CD_UO_COMPENSO,To_Char(DT_CMP_DA_COMPENSO,'MM/YYYY'), To_Char(DT_CMP_A_COMPENSO,'MM/YYYY'),
 To_Char(data,'MM/YYYY'),ESERCIZIO_PAGAMENTO,CD_TERZO, CD_ANAG,SUM(IMPONIBILE), ALIQUOTA, SUM(AMMONTARE),
 codice_fiscale,nome,cognome,ti_sesso,dt_nascita, comune_nas, prov_nas, comune_res, prov_res,cd_cap,
 via_fiscale,num_civico_fiscale,DENOMINAZIONE_SEDE,VIA_SEDE,NUMERO_CIVICO_SEDE,CAP_COMUNE_SEDE,
 COD_FIS_CNR,DS_CNR,COMUNE_CNR,IND_CNR,CIV_CNR,CAP_CNR,
 Decode('A','B',trunc(sysdate),null)DATA_F24 ,Null From
(Select V.CD_CDS_COMPENSO, V.CD_UO_COMPENSO, V.ESERCIZIO_COMPENSO, V.PG_COMPENSO, V.CHIAVE_COMPENSO,
 V.FL_SENZA_CALCOLI, V.STATO_COFI, V.DT_REGISTRAZIONE_COMPENSO,V.DT_CMP_DA_COMPENSO, V.DT_CMP_A_COMPENSO,
 V.dt_trasmissione_mandato, V.ESERCIZIO_PAGAMENTO, V.TI_ANAGRAFICO,
 V.CD_TERZO, V.CD_ANAG, V.CD_TRATTAMENTO, V.CD_TIPO_RAPPORTO, V.CD_CONTRIBUTO_RITENUTA,
 V.DS_CONTRIBUTO_RITENUTA, decode(v.imponibile_det,0,V.IMPONIBILE,v.imponibile_det) imponibile, SUM(decode(v.aliquota_det,0,V.ALIQUOTA,v.aliquota_det)) ALIQUOTA,
 decode(V.BASE_CALCOLO_det,0,V.BASE_CALCOLO,V.BASE_CALCOLO_det) base_calcolo,
SUM(decode(v.AMMONTARE_det,0,V.AMMONTARE,v.AMMONTARE_det)) AMMONTARE,
 Decode(CNRCTB015.GETVAL01PERCHIAVE(V.ESERCIZIO_PAGAMENTO, 'GESTIONE_CORI_SPECIALE','STATO_LIQUIDA_CORI'),'INV', V.DT_TRASMISSIONE_MANDATO,  V.DT_EMISSIONE_MANDATO) data,
 a.codice_fiscale,a.nome,a.cognome,a.ti_sesso,a.dt_nascita,c.ds_comune comune_nas,c.cd_provincia prov_nas,c1.ds_comune comune_res,c1.cd_provincia prov_res,Nvl(A.CAP_COMUNE_FISCALE,c1.cd_cap) CD_CAP,
 a.via_fiscale,a.num_civico_fiscale,T.DENOMINAZIONE_SEDE,T.VIA_SEDE,T.NUMERO_CIVICO_SEDE,T.CAP_COMUNE_SEDE||' '||C3.DS_COMUNE CAP_COMUNE_SEDE,
 A1.CODICE_FISCALE COD_FIS_CNR,A1.RAGIONE_SOCIALE DS_CNR ,C2.DS_COMUNE COMUNE_CNR,A1.VIA_FISCALE IND_CNR,A1.NUM_CIVICO_FISCALE CIV_CNR,A1.CAP_COMUNE_FISCALE CAP_CNR
 from V_ESTRAI_DATI_INPS V, ANAGRAFICO A,COMUNE C,COMUNE C1,TERZO T,ANAGRAFICO A1,COMUNE C2,COMUNE C3
 WHERE
 T.CD_UNITA_ORGANIZZATIVA = V.CD_UO_COMPENSO    AND
 A.CD_ANAG   =  V.CD_ANAG                       AND
 C.PG_COMUNE = A.PG_COMUNE_NASCITA              AND
 A1.TI_ENTITA = 'U'                             AND
 C1.PG_COMUNE = A.PG_COMUNE_FISCALE             And
 C2.PG_COMUNE = A1.PG_COMUNE_FISCALE            And
 C3.PG_COMUNE = T.PG_COMUNE_SEDE                And
 V.dt_trasmissione_mandato Is Not Null
GROUP BY V.CD_CDS_COMPENSO, V.CD_UO_COMPENSO, V.ESERCIZIO_COMPENSO, V.PG_COMPENSO, V.CHIAVE_COMPENSO,
 V.FL_SENZA_CALCOLI, V.STATO_COFI, V.DT_REGISTRAZIONE_COMPENSO,V.DT_CMP_DA_COMPENSO, V.DT_CMP_A_COMPENSO,
 Decode(CNRCTB015.GETVAL01PERCHIAVE(V.ESERCIZIO_PAGAMENTO, 'GESTIONE_CORI_SPECIALE','STATO_LIQUIDA_CORI'),'INV', V.DT_TRASMISSIONE_MANDATO,  V.DT_EMISSIONE_MANDATO), V.dt_trasmissione_mandato, V.ESERCIZIO_PAGAMENTO, V.TI_ANAGRAFICO,
 V.CD_TERZO, V.CD_ANAG, V.CD_TRATTAMENTO, V.CD_TIPO_RAPPORTO, V.CD_CONTRIBUTO_RITENUTA,
 V.DS_CONTRIBUTO_RITENUTA,  decode(v.imponibile_det,0,V.IMPONIBILE,v.imponibile_det),decode(V.BASE_CALCOLO_det,0,V.BASE_CALCOLO,V.BASE_CALCOLO_det),
 a.codice_fiscale,a.nome,a.cognome,a.ti_sesso,a.dt_nascita,c.ds_comune ,c.cd_provincia ,c1.ds_comune ,c1.cd_provincia ,Nvl(A.CAP_COMUNE_FISCALE,c1.cd_cap),
 a.via_fiscale,a.num_civico_fiscale,T.DENOMINAZIONE_SEDE,T.VIA_SEDE,T.NUMERO_CIVICO_SEDE,T.CAP_COMUNE_SEDE||' '||C3.DS_COMUNE,
 A1.CODICE_FISCALE ,A1.RAGIONE_SOCIALE,C2.DS_COMUNE,A1.VIA_FISCALE,A1.NUM_CIVICO_FISCALE,A1.CAP_COMUNE_FISCALE)
 Where imponibile!=0
 Group By  CD_UO_COMPENSO,To_Char(DT_CMP_DA_COMPENSO,'MM/YYYY'), To_Char(DT_CMP_A_COMPENSO,'MM/YYYY'),
 To_Char(data,'MM/YYYY'),ESERCIZIO_PAGAMENTO,CD_TERZO,CD_ANAG, ALIQUOTA,
 codice_fiscale,nome,cognome,Ti_sesso,dt_nascita,comune_nas, prov_nas, comune_res, prov_res,cd_cap,
 via_fiscale,num_civico_fiscale,DENOMINAZIONE_SEDE,VIA_SEDE,NUMERO_CIVICO_SEDE,CAP_COMUNE_SEDE,
 COD_FIS_CNR,DS_CNR,COMUNE_CNR,IND_CNR,CIV_CNR,CAP_CNR
 Order By CD_UO_COMPENSO,To_Date(To_Char(data,'MM/YYYY'),'MM/YYYY'),To_Date(To_Char(DT_CMP_DA_COMPENSO,'MM/YYYY'),'MM/YYYY'), To_Date(To_Char(DT_CMP_A_COMPENSO,'MM/YYYY'),'MM/YYYY'),
 ESERCIZIO_PAGAMENTO,CD_TERZO,CD_ANAG, ALIQUOTA,
 codice_fiscale,nome,cognome,Ti_sesso,dt_nascita,comune_nas, prov_nas, comune_res, prov_res,cd_cap,
 via_fiscale,num_civico_fiscale,DENOMINAZIONE_SEDE,VIA_SEDE,NUMERO_CIVICO_SEDE,CAP_COMUNE_SEDE,
 COD_FIS_CNR,DS_CNR,COMUNE_CNR,IND_CNR,CIV_CNR,CAP_CNR;
