--------------------------------------------------------
--  DDL for View V_FATTURA_ATTIVA_RIGA_BREVETTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_FATTURA_ATTIVA_RIGA_BREVETTI" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_FATTURA_ATTIVA", "DS_FATTURA_ATTIVA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "TIPO_FATTURA", "DT_REGISTRAZIONE", "CD_TERZO", "COGNOME", "NOME", "RAGIONE_SOCIALE", "CODICE_FISCALE", "PARTITA_IVA", "CAMBIO", "CD_DIVISA", "PROGRESSIVO_RIGA", "CD_VOCE_IVA", "DS_VOCE_IVA", "DS_RIGA_FATTURA", "PG_TROVATO", "IM_IMPONIBILE", "FC_IVA", "IM_IVA", "ESERCIZIO_ACCERTAMENTO", "PG_ACCERTAMENTO", "DT_EMISSIONE_ACCERTAMENTO", "ESERCIZIO_REVERSALE", "PG_REVERSALE", "DT_EMISSIONE_REVERSALE") AS 
  select
FA.CD_CDS,
FA.CD_UNITA_ORGANIZZATIVA,
FA.ESERCIZIO, 
FA.PG_FATTURA_ATTIVA, 
FA.DS_FATTURA_ATTIVA, 
FA.CD_CDS_ORIGINE, 
FA.CD_UO_ORIGINE, 
FA.TI_FATTURA, 
FA.DT_REGISTRAZIONE,
FA.CD_TERZO, 
FA.COGNOME, 
FA.NOME, 
FA.RAGIONE_SOCIALE, 
FA.CODICE_FISCALE, 
FA.PARTITA_IVA, 
FA.CAMBIO, 
FA.CD_DIVISA, 
fAr.PROGRESSIVO_RIGA,
fAr.CD_VOCE_IVA,
V.DS_VOCE_IVA,
fAr.DS_RIGA_FATTURA,
fAr.PG_TROVATO,
DECODE(V.FL_NON_SOGGETTO, 'Y', 0, IM_IMPONIBILE),
DECODE(V.FL_NON_SOGGETTO, 'Y', IM_IMPONIBILE, 0),
fAR.IM_IVA,
ACC.ESERCIZIO_ORIGINALE, 
ACC.PG_ACCERTAMENTO, 
ACC.DT_REGISTRAZIONE, 
DECODE(far.Ti_associato_manrev, 'T', CNRCTB062.getEsercizioReversale(far.CD_CDS, FAR.cd_UNITA_ORGANIZZATIVA, FAR.esercizio, 'FATTURA_A', FAR.PG_FATTURA_ATTIVA)  , NULL),
DECODE(far.Ti_associato_manrev, 'T', CNRCTB062.getPgReversale(far.cd_cds, FAR.cd_UNITA_ORGANIZZATIVA, FAR.esercizio, 'FATTURA_A', FAR.PG_FATTURA_ATTIVA)  , NULL),
DECODE(far.Ti_associato_manrev, 'T', CNRCTB062.getDataReversale(far.cd_cds, FAR.cd_UNITA_ORGANIZZATIVA, FAR.esercizio, 'FATTURA_A', FAR.PG_FATTURA_ATTIVA)  , NULL)
from fattura_ATTIVA_riga fAr, fattura_ATTiva fA, ACCERTAMENTO ACC, VOCE_IVA V
where fAr.PG_FATTURA_ATTIVA=fA.PG_FATTURA_ATTIVA AND
fAr.CD_CDS=fA.CD_CDS AND
fAr.CD_UNITA_ORGANIZZATIVA=fA.CD_UNITA_ORGANIZZATIVA AND
FAR.PG_TROVATO IS NOT NULL AND
fAr.ESERCIZIO = fA.ESERCIZIO AND
FAR.ESERCIZIO_ACCERTAMENTO = ACC.ESERCIZIO(+) AND
FAR.ESERCIZIO_ORI_ACCERTAMENTO = ACC.ESERCIZIO_ORIGINALE(+) AND
FAR.PG_ACCERTAMENTO = ACC.PG_ACCERTAMENTO(+) AND
FAR.CD_CDS_ACCERTAMENTO = ACC.CD_CDS(+) AND
FAR.CD_VOCE_IVA = V.CD_VOCE_IVA ;
