--------------------------------------------------------
--  DDL for View V_FATTURA_PASSIV_RIGA_BREVETTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_FATTURA_PASSIV_RIGA_BREVETTI" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_FATTURA_PASSIVA", "DS_FATTURA_PASSIVA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "TIPO_FATTURA_COMPENSO", "NR_FATTURA_FORNITORE", "DT_FATTURA_FORNITORE", "PARTITA_IVA", "CODICE_FISCALE", "DT_REGISTRAZIONE", "CD_TERZO", "COGNOME", "NOME", "RAGIONE_SOCIALE", "CAMBIO", "CD_DIVISA", "PROGRESSIVO_RIGA", "CD_VOCE_IVA", "DS_VOCE_IVA", "DS_RIGA_FATTURA", "PG_TROVATO", "IM_IMPONIBILE", "FC_IVA", "IM_IVA", "DT_PAGAMENTO_FONDO_ECO", "STATO_PAGAMENTO_FONDO_ECO", "ESERCIZIO_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "DT_EMISSIONE_OBBLIGAZIONE", "ESERCIZIO_MANDATO", "PG_MANDATO", "DT_EMISSIONE_MANDATO", "IM_LORDO_PERCIPIENTE", "IM_NETTO_PERCIPIENTE", "IM_TOTALE_COMPENSO") AS 
  select
FP.CD_CDS,
FP.CD_UNITA_ORGANIZZATIVA,
FP.ESERCIZIO, 
FP.PG_FATTURA_PASSIVA, 
FP.DS_FATTURA_PASSIVA, 
FP.CD_CDS_ORIGINE, 
FP.CD_UO_ORIGINE, 
DECODE(fP.TI_FATTURA,'F','FATTURA', 'N', 'NOTA'), 
FP.NR_FATTURA_FORNITORE, 
FP.DT_FATTURA_FORNITORE, 
FP.PARTITA_IVA, 
FP.CODICE_FISCALE,
FP.DT_REGISTRAZIONE,
FP.CD_TERZO, 
FP.COGNOME, 
FP.NOME, 
FP.RAGIONE_SOCIALE, 
FP.CAMBIO, 
FP.CD_DIVISA, 
fPr.PROGRESSIVO_RIGA,
fPr.CD_VOCE_IVA,
V.DS_VOCE_IVA,
fPr.DS_RIGA_FATTURA,
fPr.PG_TROVATO,
DECODE(V.FL_NON_SOGGETTO, 'Y', 0, IM_IMPONIBILE),
DECODE(V.FL_NON_SOGGETTO, 'Y', IM_IMPONIBILE, 0),
fPR.IM_IVA,
FP.DT_PAGAMENTO_FONDO_ECO, 
FP.STATO_PAGAMENTO_FONDO_ECO, 
OBB.ESERCIZIO_ORIGINALE, 
OBB.PG_OBBLIGAZIONE, 
OBB.DT_REGISTRAZIONE, 
DECODE(fPr.Ti_associato_manrev, 'T', CNRCTB062.getEsercizioMandato(fpr.CD_CDS, FpR.cd_UNITA_ORGANIZZATIVA, FpR.esercizio, 'FATTURA_P', FPR.PG_FATTURA_PASSIVA)  , NULL),
DECODE(fPr.Ti_associato_manrev, 'T', CNRCTB062.getPgMandato(fpr.cd_cds, FPR.cd_UNITA_ORGANIZZATIVA, FPR.esercizio, 'FATTURA_P', FPR.PG_FATTURA_PASSIVA)  , NULL),
DECODE(fPr.Ti_associato_manrev, 'T', CNRCTB062.getDataMandato(fPr.cd_cds, FPR.cd_UNITA_ORGANIZZATIVA, FPR.esercizio, 'FATTURA_P', FPR.PG_FATTURA_PASSIVA)  , NULL),
0,0,0
from fattura_PASSIVA_riga fPr, fattura_PASSiva fP, OBBLIGAZIONE OBB, VOCE_IVA V
where fPr.PG_FATTURA_PASSIVA=fP.PG_FATTURA_PASSIVA AND
fPr.CD_CDS=fP.CD_CDS AND
fPr.CD_UNITA_ORGANIZZATIVA=fP.CD_UNITA_ORGANIZZATIVA AND
FPR.PG_TROVATO IS NOT NULL AND
fPr.ESERCIZIO = fP.ESERCIZIO AND
FPR.ESERCIZIO_OBBLIGAZIONE = OBB.ESERCIZIO(+) AND
FPR.ESERCIZIO_ORI_OBBLIGAZIONE = OBB.ESERCIZIO_ORIGINALE(+) AND
FPR.PG_OBBLIGAZIONE = OBB.PG_OBBLIGAZIONE(+) AND
FPR.CD_CDS_OBBLIGAZIONE = OBB.CD_CDS(+) AND
FPR.CD_VOCE_IVA = V.CD_VOCE_IVA
UNION ALL
select
COMP.CD_CDS,
COMP.CD_UNITA_ORGANIZZATIVA,
COMP.ESERCIZIO, 
COMP.PG_COMPENSO, 
COMP.DS_COMPENSO, 
COMP.CD_CDS_ORIGINE, 
COMP.CD_UO_ORIGINE, 
'C', 
COMP.NR_FATTURA_FORNITORE, 
COMP.DT_FATTURA_FORNITORE, 
COMP.PARTITA_IVA, 
COMP.CODICE_FISCALE,
COMP.DT_REGISTRAZIONE,
COMP.CD_TERZO, 
COMP.COGNOME, 
COMP.NOME, 
COMP.RAGIONE_SOCIALE, 
1, 
NULL, 
1,
COMP.CD_VOCE_IVA,
V.DS_VOCE_IVA,
COMP.DS_COMPENSO, 
COMP.PG_TROVATO,
0,
0,
0,
COMP.DT_PAGAMENTO_FONDO_ECO, 
COMP.STATO_PAGAMENTO_FONDO_ECO, 
OBB.ESERCIZIO_ORIGINALE, 
OBB.PG_OBBLIGAZIONE, 
OBB.DT_REGISTRAZIONE, 
DECODE(COMP.Ti_associato_manrev, 'T', CNRCTB062.getEsercizioMandato(COMP.CD_CDS, COMP.cd_UNITA_ORGANIZZATIVA, COMP.esercizio, 'COMPENSO', comp.PG_COMPENSO)  , NULL),
DECODE(COMP.Ti_associato_manrev, 'T', CNRCTB062.getPgMandato(COMP.cd_cds, COMP.cd_UNITA_ORGANIZZATIVA, COMP.esercizio, 'COMPENSO', comp.PG_COMPENSO)  , NULL),
DECODE(COMP.Ti_associato_manrev, 'T', CNRCTB062.getDataMandato(COMP.cd_cds, COMP.cd_UNITA_ORGANIZZATIVA, COMP.esercizio, 'COMPENSO', comp.PG_COMPENSO)  , NULL),
COMP.IM_LORDO_PERCIPIENTE,
COMP.IM_NETTO_PERCIPIENTE,
COMP.IM_TOTALE_COMPENSO
from COMPENSO COMP, OBBLIGAZIONE OBB, VOCE_IVA V
where 
COMP.PG_TROVATO IS NOT NULL AND
COMP.ESERCIZIO_OBBLIGAZIONE = OBB.ESERCIZIO(+) AND
COMP.ESERCIZIO_ORI_OBBLIGAZIONE = OBB.ESERCIZIO_ORIGINALE(+) AND
COMP.PG_OBBLIGAZIONE = OBB.PG_OBBLIGAZIONE(+) AND
COMP.CD_CDS_OBBLIGAZIONE = OBB.CD_CDS(+) AND
COMP.CD_VOCE_IVA = V.CD_VOCE_IVA ;
