--------------------------------------------------------
--  DDL for View V_IMPEGNO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_IMPEGNO" ("ESERCIZIO", "CD_CDS", "ESERCIZIO_ORIGINALE", "PG_OBBLIGAZIONE", "PG_OBBLIGAZIONE_SCADENZARIO", "CD_TIPO_DOCUMENTO_CONT", "FL_PGIRO", "CD_UNITA_ORGANIZZATIVA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "DT_SCADENZA", "IM_SCADENZA", "IM_ASSOCIATO_DOC_AMM", "IM_ASSOCIATO_DOC_CONTABILE", "TI_APPARTENENZA", "TI_GESTIONE", "CD_VOCE", "PG_VER_REC", "PG_VER_REC_SCADENZA") AS 
  (SELECT
--
-- Date: 18/07/2006
-- Version: 1.5
--
-- Vista di estrazione degli impegni CNR, che racchiude in un unico record i dati
-- riportati in OBBLIGAZIONE, OBBLIGAZIONE_SCADENZARIO, OBBLIGAZIONE_SCAD_VOCE
--
-- History:
--
-- Date: 14/01/2002
-- Version: 1.0
-- Creazione
--
-- Date: 01/08/2002
-- Version: 1.1
-- Aggiunto filtro su FL_PGIRO
--
-- Date: 22/10/2002
-- Version: 1.2
-- Aggiunto IM_ASSOCIATO_DOC_AMM
--
-- Date: 16/06/2003
-- Version: 1.3
-- Aggiunto filtro su RIPORTATO
--
-- Date: 1/07/2003
-- Version: 1.4
-- Aggiunto pg_ver_rec, pg_ver_rec_scadenza
--
-- Date: 18/07/2006
-- Version: 1.5
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body:
--
A.ESERCIZIO,
A.CD_CDS,
A.ESERCIZIO_ORIGINALE,
A.PG_OBBLIGAZIONE,
B.PG_OBBLIGAZIONE_SCADENZARIO,
A.CD_TIPO_DOCUMENTO_CONT,
A.FL_PGIRO,
A.CD_UNITA_ORGANIZZATIVA,
A.CD_CDS_ORIGINE,
A.CD_UO_ORIGINE,
B.DT_SCADENZA,
B.IM_SCADENZA,
B.IM_ASSOCIATO_DOC_AMM,
B.IM_ASSOCIATO_DOC_CONTABILE,
C.TI_APPARTENENZA,
C.TI_GESTIONE,
C.CD_VOCE,
A.PG_VER_REC,
B.PG_VER_REC
FROM
OBBLIGAZIONE A,
OBBLIGAZIONE_SCADENZARIO B,
OBBLIGAZIONE_SCAD_VOCE C
WHERE
(A.CD_TIPO_DOCUMENTO_CONT = 'IMP' OR
A.CD_TIPO_DOCUMENTO_CONT = 'IMP_RES') AND
A.STATO_OBBLIGAZIONE='D' AND
A.FL_PGIRO='N' AND
A.RIPORTATO='N' AND
A.CD_CDS = B.CD_CDS AND
A.ESERCIZIO = B.ESERCIZIO AND
A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE AND
A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE AND
B.CD_CDS = C.CD_CDS AND
B.ESERCIZIO = C.ESERCIZIO AND
B.ESERCIZIO_ORIGINALE = C.ESERCIZIO_ORIGINALE AND
B.PG_OBBLIGAZIONE = C.PG_OBBLIGAZIONE AND
B.PG_OBBLIGAZIONE_SCADENZARIO = C.PG_OBBLIGAZIONE_SCADENZARIO);

   COMMENT ON TABLE "V_IMPEGNO"  IS 'Vista di estrazione degli impegni CNR, che racchiude in un unico record i dati
riportati in OBBLIGAZIONE, OBBLIGAZIONE_SCADENZARIO, OBBLIGAZIONE_SCAD_VOCE';
