--------------------------------------------------------
--  DDL for View V_IMPEGNATO_PER_TIPO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_IMPEGNATO_PER_TIPO" ("ESERCIZIO", "VOCE", "DESCRIZIONE", "TIPO", "TOT_IMPEGNATO") AS 
  Select ESERCIZIO, VOCE, DESCRIZIONE, TIPO, Nvl(Sum(IMPEGNATO),0) TOT_IMPEGNATO
From
(SELECT O.ESERCIZIO, O.CD_ELEMENTO_VOCE VOCE, E.DS_ELEMENTO_VOCE DESCRIZIONE,
        T.DS_TIPO_SPESA TIPO, Nvl(Sum(O.IM_OBBLIGAZIONE),0) IMPEGNATO
FROM    OBBLIGAZIONE O, ELEMENTO_VOCE E, TIPO_SPESA T, UNITA_ORGANIZZATIVA U
WHERE   O.DT_CANCELLAZIONE Is Null				AND
        O.CD_UNITA_ORGANIZZATIVA = U.CD_UNITA_ORGANIZZATIVA	AND
        U.CD_TIPO_UNITA		= 'SAC'				AND
        E.CD_TIPO_SPESA_SAC     = T.CD_TIPO_SPESA (+)		AND
        O.ESERCIZIO		= E.ESERCIZIO			AND
        O.TI_APPARTENENZA	= E.TI_APPARTENENZA		AND
        O.TI_GESTIONE		= E.TI_GESTIONE			AND
        O.CD_ELEMENTO_VOCE 	= E.CD_ELEMENTO_VOCE		AND
        E.TI_GESTIONE 		= 'S'				AND
        E.TI_APPARTENENZA	= 'D'				AND
        E.TI_ELEMENTO_VOCE	= 'C'				AND
        E.CD_PARTE		= '1'
Group By O.ESERCIZIO, O.CD_ELEMENTO_VOCE, E.DS_ELEMENTO_VOCE, T.DS_TIPO_SPESA
Union
SELECT  O.ESERCIZIO, O.CD_ELEMENTO_VOCE VOCE, E.DS_ELEMENTO_VOCE DESCRIZIONE,
        T.DS_TIPO_SPESA TIPO, Nvl(Sum(O.IM_OBBLIGAZIONE),0) IMPEGNATO
FROM    OBBLIGAZIONE O, ELEMENTO_VOCE E, TIPO_SPESA T, UNITA_ORGANIZZATIVA U
WHERE   O.DT_CANCELLAZIONE Is Null				AND
        O.CD_UNITA_ORGANIZZATIVA = U.CD_UNITA_ORGANIZZATIVA	AND
        U.CD_TIPO_UNITA		!= 'SAC'			AND
        E.CD_TIPO_SPESA_IST     = T.CD_TIPO_SPESA (+)		AND
        O.ESERCIZIO		= E.ESERCIZIO			AND
        O.TI_APPARTENENZA	= E.TI_APPARTENENZA		AND
        O.TI_GESTIONE		= E.TI_GESTIONE			AND
        O.CD_ELEMENTO_VOCE 	= E.CD_ELEMENTO_VOCE		AND
        E.TI_GESTIONE 		= 'S'				AND
        E.TI_APPARTENENZA	= 'D'				AND
        E.TI_ELEMENTO_VOCE	= 'C'				AND
        E.CD_PARTE		= '1'
Group By O.ESERCIZIO, O.CD_ELEMENTO_VOCE, E.DS_ELEMENTO_VOCE, T.DS_TIPO_SPESA)
Group By ESERCIZIO, VOCE, DESCRIZIONE, TIPO
;
