--------------------------------------------------------
--  DDL for View V_INCARICHI_DA_ASSEGNARE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_INCARICHI_DA_ASSEGNARE" ("ESERCIZIO_LIMITE", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_PROCEDURA", "ESERCIZIO_REPERTORIO", "PG_REPERTORIO", "CD_TERZO", "DT_PUBBLICAZIONE", "DT_FINE_PUBBLICAZIONE", "DT_SCADENZA", "STATO", "CD_TIPO_LIMITE", "IM_INCARICHI") AS 
  (SELECT
--
-- Date: 11/11/2008
-- Version: 1.2
--
-- Vista Incarichi da assegnare utilizzata per conoscere, dato il codice limite e la UO,
-- la lista degli incarichi ancora da assegnare della UO del CDS
--
-- History:
--
-- Date: 26/03/2008
-- Version: 1.0
-- Creazione
--
-- Date: 15/09/2008
-- Version: 1.1
-- Aggiornata tenedo conto della nuova struttura degli incarichi che prevedono la nuova tabella
-- INCARICHI_PROCEDURA
--
-- Date: 11/11/2008
-- Version: 1.2
-- Corretta anomalia. Non visualizzava le procedure senza incarico
--
-- Body:
--
  INCARICHI_REPERTORIO_ANNO.ESERCIZIO_LIMITE,
  INCARICHI_REPERTORIO.CD_CDS,
  INCARICHI_REPERTORIO.CD_UNITA_ORGANIZZATIVA,
  INCARICHI_REPERTORIO.ESERCIZIO_PROCEDURA,
  INCARICHI_REPERTORIO.PG_PROCEDURA,
  INCARICHI_REPERTORIO.ESERCIZIO,
  INCARICHI_REPERTORIO.PG_REPERTORIO,
  INCARICHI_REPERTORIO.CD_TERZO,
  INCARICHI_PROCEDURA.DT_PUBBLICAZIONE,
  INCARICHI_PROCEDURA.DT_FINE_PUBBLICAZIONE,
  INCARICHI_PROCEDURA.DT_SCADENZA,
  INCARICHI_REPERTORIO.STATO,
  V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_LIMITE,
  INCARICHI_REPERTORIO_ANNO.IMPORTO_COMPLESSIVO IM_INCARICHI
FROM INCARICHI_REPERTORIO, INCARICHI_REPERTORIO_ANNO, INCARICHI_PROCEDURA, V_ASS_INCARICO_ATTIVITA_REPLIM, UNITA_ORGANIZZATIVA
WHERE INCARICHI_REPERTORIO.stato IN ('PP','PU')
AND   INCARICHI_REPERTORIO.ESERCIZIO = INCARICHI_REPERTORIO_ANNO.ESERCIZIO
AND   INCARICHI_REPERTORIO.PG_REPERTORIO = INCARICHI_REPERTORIO_ANNO.PG_REPERTORIO
AND   INCARICHI_REPERTORIO.ESERCIZIO_PROCEDURA = INCARICHI_PROCEDURA.ESERCIZIO
AND   INCARICHI_REPERTORIO.PG_PROCEDURA = INCARICHI_PROCEDURA.PG_PROCEDURA
AND   INCARICHI_REPERTORIO.CD_UNITA_ORGANIZZATIVA = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.ESERCIZIO = INCARICHI_REPERTORIO.ESERCIZIO
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.ESERCIZIO_LIMITE = INCARICHI_REPERTORIO_ANNO.ESERCIZIO_LIMITE
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_INCARICO = INCARICHI_PROCEDURA.CD_TIPO_INCARICO
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_ATTIVITA = INCARICHI_PROCEDURA.CD_TIPO_ATTIVITA
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.TIPO_NATURA = INCARICHI_PROCEDURA.TIPO_NATURA
UNION ALL
SELECT ESERCIZIO_LIMITE, CD_CDS, CD_UNITA_ORGANIZZATIVA, ESERCIZIO, PG_PROCEDURA, NULL, NULL, NULL,
       DT_PUBBLICAZIONE, DT_FINE_PUBBLICAZIONE, DT_SCADENZA, STATO, CD_TIPO_LIMITE, IM_INCARICHI
FROM(SELECT INCARICHI_PROCEDURA_ANNO.ESERCIZIO_LIMITE,
            INCARICHI_PROCEDURA.CD_CDS,
            INCARICHI_PROCEDURA.CD_UNITA_ORGANIZZATIVA,
            INCARICHI_PROCEDURA.ESERCIZIO,
            INCARICHI_PROCEDURA.PG_PROCEDURA,
            NULL, NULL, NULL,
            INCARICHI_PROCEDURA.DT_PUBBLICAZIONE,
            INCARICHI_PROCEDURA.DT_FINE_PUBBLICAZIONE,
            INCARICHI_PROCEDURA.DT_SCADENZA,
            INCARICHI_PROCEDURA.STATO,
            V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_LIMITE,
           (SELECT INCARICHI_PROCEDURA_ANNO.IMPORTO_COMPLESSIVO - NVL(SUM(INCARICHI_REPERTORIO_ANNO.IMPORTO_COMPLESSIVO),0)
            FROM INCARICHI_REPERTORIO, INCARICHI_REPERTORIO_ANNO
            WHERE INCARICHI_REPERTORIO.ESERCIZIO_PROCEDURA = INCARICHI_PROCEDURA.ESERCIZIO
            AND   INCARICHI_REPERTORIO.PG_PROCEDURA = INCARICHI_PROCEDURA.PG_PROCEDURA
            AND   INCARICHI_REPERTORIO.ESERCIZIO = INCARICHI_REPERTORIO_ANNO.ESERCIZIO
            AND   INCARICHI_REPERTORIO.PG_REPERTORIO = INCARICHI_REPERTORIO_ANNO.PG_REPERTORIO
			AND   INCARICHI_REPERTORIO_ANNO.ESERCIZIO_LIMITE = INCARICHI_PROCEDURA_ANNO.ESERCIZIO_LIMITE) IM_INCARICHI
     FROM INCARICHI_PROCEDURA, INCARICHI_PROCEDURA_ANNO, V_ASS_INCARICO_ATTIVITA_REPLIM, UNITA_ORGANIZZATIVA
     WHERE INCARICHI_PROCEDURA.stato IN ('PP','PU')
     AND   INCARICHI_PROCEDURA.ESERCIZIO = INCARICHI_PROCEDURA_ANNO.ESERCIZIO
     AND   INCARICHI_PROCEDURA.PG_PROCEDURA = INCARICHI_PROCEDURA_ANNO.PG_PROCEDURA
     AND   INCARICHI_PROCEDURA.CD_UNITA_ORGANIZZATIVA = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
     AND   V_ASS_INCARICO_ATTIVITA_REPLIM.ESERCIZIO = INCARICHI_PROCEDURA.ESERCIZIO
     AND   V_ASS_INCARICO_ATTIVITA_REPLIM.ESERCIZIO_LIMITE = INCARICHI_PROCEDURA_ANNO.ESERCIZIO_LIMITE
     AND   V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_INCARICO = INCARICHI_PROCEDURA.CD_TIPO_INCARICO
     AND   V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_ATTIVITA = INCARICHI_PROCEDURA.CD_TIPO_ATTIVITA
     AND   V_ASS_INCARICO_ATTIVITA_REPLIM.TIPO_NATURA = INCARICHI_PROCEDURA.TIPO_NATURA)
WHERE IM_INCARICHI != 0
)
;
