--------------------------------------------------------
--  DDL for View V_INCARICHI_UO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_INCARICHI_UO" ("ESERCIZIO_LIMITE", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "DS_UNITA_ORGANIZZATIVA", "CD_TIPO_LIMITE", "IM_INCARICHI") AS 
  (SELECT
--
-- Date: 15/09/2008
-- Version: 1.1
--
-- Vista Incarichi per UO utilizzata per conoscere, dato il codice limite ed il CDS,
-- la ripartizione tra le varie UO del CDS degli incarichi conferiti
--
-- History:
--
-- Date: 10/01/2008
-- Version: 1.0
-- Creazione
--
-- Date: 15/09/2008
-- Version: 1.1
-- Aggiornata tenedo conto della nuova struttura degli incarichi che prevedono la nuova tabella
-- INCARICHI_PROCEDURA
--
-- Body:
--
  INCARICHI_PROCEDURA_ANNO.ESERCIZIO_LIMITE,
  INCARICHI_PROCEDURA.CD_CDS,
  INCARICHI_PROCEDURA.CD_UNITA_ORGANIZZATIVA,
  UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
  V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_LIMITE,
  SUM(INCARICHI_PROCEDURA_ANNO.IMPORTO_COMPLESSIVO) IM_INCARICHI
FROM INCARICHI_PROCEDURA, INCARICHI_PROCEDURA_ANNO, V_ASS_INCARICO_ATTIVITA_REPLIM, UNITA_ORGANIZZATIVA UNITA_ORGANIZZATIVA
WHERE INCARICHI_PROCEDURA.stato in ('PP','PU','PD', 'CC')
And   INCARICHI_PROCEDURA.ESERCIZIO = INCARICHI_PROCEDURA_ANNO.ESERCIZIO
AND   INCARICHI_PROCEDURA.PG_PROCEDURA = INCARICHI_PROCEDURA_ANNO.PG_PROCEDURA
And   INCARICHI_PROCEDURA.CD_UNITA_ORGANIZZATIVA = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.ESERCIZIO = INCARICHI_PROCEDURA.ESERCIZIO
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.ESERCIZIO_LIMITE = INCARICHI_PROCEDURA_ANNO.ESERCIZIO_LIMITE
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_INCARICO = INCARICHI_PROCEDURA.CD_TIPO_INCARICO
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_ATTIVITA = INCARICHI_PROCEDURA.CD_TIPO_ATTIVITA
AND   V_ASS_INCARICO_ATTIVITA_REPLIM.TIPO_NATURA = INCARICHI_PROCEDURA.TIPO_NATURA
GROUP BY INCARICHI_PROCEDURA_ANNO.ESERCIZIO_LIMITE,
         INCARICHI_PROCEDURA.CD_CDS,
         INCARICHI_PROCEDURA.CD_UNITA_ORGANIZZATIVA,
         UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
         V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_LIMITE);
