--------------------------------------------------------
--  DDL for View V_INVENTARIO_UTILIZZATORI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_INVENTARIO_UTILIZZATORI" ("PG_INVENTARIO", "NR_INVENTARIO", "PROGRESSIVO", "DS_BENE", "CD_CATEGORIA_GRUPPO", "FL_AMMORTAMENTO", "DS_CONDIZIONE_BENE", "TIPOLOGIA", "VALORE", "FONDO", "IMPONIBILE", "STATO", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "CD_UBICAZIONE", "DS_UBICAZIONE", "ASSEGNATARIO", "ETICHETTA", "ID_BENE_ORIGINE", "CD_BARRE", "TARGA", "CD_UTILIZZATORE_CDR", "DS_CDR", "CD_LINEA_ATTIVITA", "DS_LINEA_ATTIVITA") AS 
  SELECT  BENI.PG_INVENTARIO     ,
        BENI.NR_INVENTARIO      ,
        BENI.PROGRESSIVO        ,
        BENI.DS_BENE            ,
        BENI.CD_CATEGORIA_GRUPPO,
        BENI.FL_AMMORTAMENTO    ,
        CONDIZIONE.DS_CONDIZIONE_BENE  ,
        DECODE(TI_COMMERCIALE_ISTITUZIONALE,'I','ISTITUZIONE','COMMERCIALE') TIPOLOGIA,
        VALORE_INIZIALE+VARIAZIONE_PIU-VARIAZIONE_MENO VALORE,
        VALORE_AMMORTIZZATO             FONDO,
        IMPONIBILE_AMMORTAMENTO         IMPONIBILE,
        DECODE(FL_TOTALMENTE_SCARICATO,'Y','TOTALMENTE SCARICATO','N','ATTIVO') STATO,
        BENI.CD_CDS                  ,
        BENI.CD_UNITA_ORGANIZZATIVA  ,
        BENI.CD_UBICAZIONE      ,
        DS_UBICAZIONE_BENE           ,
        (SELECT NVL(ANAGRAFICO.COGNOME||' '||ANAGRAFICO.NOME,ANAGRAFICO.RAGIONE_SOCIALE)
        FROM TERZO,ANAGRAFICO
        WHERE
        TERZO.CD_TERZO          = BENI.CD_ASSEGNATARIO AND
        ANAGRAFICO.CD_ANAG      = TERZO.CD_ANAG
        ) ASSEGNATATIO           ,
        ETICHETTA                ,
        ID_BENE_ORIGINE          ,
        CD_BARRE                 ,
        TARGA                    ,
        CD_UTILIZZATORE_CDR,
        DS_CDR,
        UTILIZZATORI.CD_LINEA_ATTIVITA ,
        DS_LINEA_ATTIVITA
        FROM
        INVENTARIO_BENI BENI,
        INVENTARIO_UTILIZZATORI_LA UTILIZZATORI,
        CONDIZIONE_BENE CONDIZIONE,
        UBICAZIONE_BENE,
        CDR,
        LINEA_ATTIVITA LINEA
        WHERE
        BENI.CD_CDS            		 = UBICAZIONE_BENE.CD_CDS		        AND
        BENI.CD_UNITA_ORGANIZZATIVA      = UBICAZIONE_BENE.CD_UNITA_ORGANIZZATIVA        AND
        BENI.CD_UBICAZIONE               = UBICAZIONE_BENE.CD_UBICAZIONE        AND
        BENI.CD_CONDIZIONE_BENE          = CONDIZIONE.CD_CONDIZIONE_BENE        AND
        BENI.PG_INVENTARIO               = UTILIZZATORI.PG_INVENTARIO           AND
        BENI.NR_INVENTARIO               = UTILIZZATORI.NR_INVENTARIO           AND
        BENI.PROGRESSIVO                 = UTILIZZATORI.PROGRESSIVO             AND
        UTILIZZATORI.CD_UTILIZZATORE_CDR = CDR.CD_CENTRO_RESPONSABILITA         AND
        UTILIZZATORI.CD_UTILIZZATORE_CDR = LINEA.CD_CENTRO_RESPONSABILITA       AND
        UTILIZZATORI.CD_LINEA_ATTIVITA   = LINEA.CD_LINEA_ATTIVITA;
