--------------------------------------------------------
--  DDL for View V_INCARICHI_TERZO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_INCARICHI_TERZO" ("ESERCIZIO_LIMITE", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "CD_TERZO", "DS_TERZO", "CD_TIPO_LIMITE", "IM_INCARICHI") AS 
  (SELECT
--
-- Date: 15/09/2008
-- Version: 1.1
--
-- Vista Incarichi per Terzo utilizzata per conoscere, dato il codice limite e la UO,
-- la ripartizione tra i terzi della UO del CDS degli incarichi conferiti
--
-- History:
--
-- Date: 10/01/2008
-- Version: 1.0
-- Creazione
--
-- Date: 15/09/2008
-- Version: 1.1
-- Aggiornata tenedo conto della nuova struttura degli incarichi che prevedono la nuova tabella
-- INCARICHI_PROCEDURA
--
-- Body:
--
  INCARICHI_REPERTORIO_ANNO.ESERCIZIO_LIMITE,
  INCARICHI_REPERTORIO.CD_CDS,
  INCARICHI_REPERTORIO.CD_UNITA_ORGANIZZATIVA,
  INCARICHI_REPERTORIO.CD_TERZO,
  TERZO.DENOMINAZIONE_SEDE,
  V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_LIMITE,
  SUM(INCARICHI_REPERTORIO_ANNO.IMPORTO_COMPLESSIVO) IM_INCARICHI
From INCARICHI_REPERTORIO, INCARICHI_REPERTORIO_ANNO, INCARICHI_PROCEDURA, V_ASS_INCARICO_ATTIVITA_REPLIM, UNITA_ORGANIZZATIVA, TERZO
Where INCARICHI_REPERTORIO.stato in ('PD','CC')
And   INCARICHI_REPERTORIO.ESERCIZIO = INCARICHI_REPERTORIO_ANNO.ESERCIZIO
And   INCARICHI_REPERTORIO.PG_REPERTORIO = INCARICHI_REPERTORIO_ANNO.PG_REPERTORIO
And   INCARICHI_REPERTORIO.ESERCIZIO_PROCEDURA = INCARICHI_PROCEDURA.ESERCIZIO
And   INCARICHI_REPERTORIO.PG_PROCEDURA = INCARICHI_PROCEDURA.PG_PROCEDURA
And   INCARICHI_REPERTORIO.CD_UNITA_ORGANIZZATIVA = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And   INCARICHI_REPERTORIO.CD_TERZO = TERZO.CD_TERZO
And   V_ASS_INCARICO_ATTIVITA_REPLIM.ESERCIZIO = INCARICHI_REPERTORIO.ESERCIZIO
And   V_ASS_INCARICO_ATTIVITA_REPLIM.ESERCIZIO_LIMITE = INCARICHI_REPERTORIO_ANNO.ESERCIZIO_LIMITE
And   V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_INCARICO = INCARICHI_PROCEDURA.CD_TIPO_INCARICO
And   V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_ATTIVITA = INCARICHI_PROCEDURA.CD_TIPO_ATTIVITA
And   V_ASS_INCARICO_ATTIVITA_REPLIM.TIPO_NATURA = INCARICHI_PROCEDURA.TIPO_NATURA
Group By INCARICHI_REPERTORIO_ANNO.ESERCIZIO_LIMITE,
         INCARICHI_REPERTORIO.CD_CDS,
         INCARICHI_REPERTORIO.CD_UNITA_ORGANIZZATIVA,
         INCARICHI_REPERTORIO.CD_TERZO,
         TERZO.DENOMINAZIONE_SEDE,
         V_ASS_INCARICO_ATTIVITA_REPLIM.CD_TIPO_LIMITE);
