--------------------------------------------------------
--  DDL for View V_INCARICHI_ELENCO_CORR
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_INCARICHI_ELENCO_CORR" ("ESERCIZIO", "PG_REPERTORIO", "CD_CDS", "DS_CDS", "CD_UNITA_ORGANIZZATIVA", "DS_UNITA_ORGANIZZATIVA", "NOMINATIVO", "OGGETTO", "IMPORTO_LORDO", "DT_INIZIO_VALIDITA", "DT_FINE_VALIDITA") AS 
  (SELECT
  INCARICHI_REPERTORIO.ESERCIZIO,
  INCARICHI_REPERTORIO.PG_REPERTORIO,
  INCARICHI_REPERTORIO.CD_CDS,
  CDS.DS_UNITA_ORGANIZZATIVA,
  UO.CD_UNITA_ORGANIZZATIVA,
  UO.DS_UNITA_ORGANIZZATIVA,
  Decode(V_ANAGRAFICO_TERZO.TI_ENTITA,'F',V_ANAGRAFICO_TERZO.COGNOME||' '||V_ANAGRAFICO_TERZO.NOME,V_ANAGRAFICO_TERZO.RAGIONE_SOCIALE),
  INCARICHI_PROCEDURA.OGGETTO,
  INCARICHI_REPERTORIO.IMPORTO_LORDO,
  INCARICHI_REPERTORIO.DT_INIZIO_VALIDITA,
  INCARICHI_REPERTORIO.DT_FINE_VALIDITA
--
-- Date: 15/09/2008
-- Version: 1.1
--
-- Vista elenco degli incarichi di collaborazione utilizzata per ricerca delle competenze
-- necessarie all''interno del CNR, utile alla estrazione in file XML
--
-- History:
--
-- Date: 5/11/2007
-- Version: 1.0
-- Creazione
--
-- Date: 15/09/2008
-- Version: 1.1
-- Aggiornata tenedo conto della nuova struttura degli incarichi che prevedono la nuova tabella
-- INCARICHI_PROCEDURA
--
-- Body:
--
from INCARICHI_REPERTORIO, INCARICHI_PROCEDURA, UNITA_ORGANIZZATIVA CDS, UNITA_ORGANIZZATIVA UO, V_ANAGRAFICO_TERZO
Where INCARICHI_REPERTORIO.CD_CDS = CDS.CD_UNITA_ORGANIZZATIVA
And INCARICHI_REPERTORIO.CD_UNITA_ORGANIZZATIVA = UO.CD_UNITA_ORGANIZZATIVA
And INCARICHI_REPERTORIO.CD_TERZO=V_ANAGRAFICO_TERZO.CD_TERZO
And INCARICHI_REPERTORIO.ESERCIZIO_PROCEDURA = INCARICHI_PROCEDURA.ESERCIZIO
And INCARICHI_REPERTORIO.PG_PROCEDURA = INCARICHI_PROCEDURA.PG_PROCEDURA
And INCARICHI_REPERTORIO.FL_PUBBLICA_CONTRATTO='Y'
)
Order By 1,2;
