--------------------------------------------------------
--  DDL for View V_INCARICHI_RICHIESTA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_INCARICHI_RICHIESTA" ("ESERCIZIO", "PG_RICHIESTA", "CD_CDS", "DS_CDS", "CD_UNITA_ORGANIZZATIVA", "DS_UNITA_ORGANIZZATIVA", "ATTIVITA", "ATTIVITA_BREVE", "COMPETENZE", "DURATA", "SEDE_LAVORO", "NOTE", "STATO", "DATA_PUBBLICAZIONE", "DATA_FINE_PUBBLICAZIONE", "DATA_SCADENZA", "PERSONALE_INTERNO", "EMAIL_RISPOSTE", "NR_RISORSE_DA_TROVARE") AS 
  (SELECT
  ESERCIZIO,
  PG_RICHIESTA,
  CD_CDS,
  CDS.DS_UNITA_ORGANIZZATIVA,
  UO.CD_UNITA_ORGANIZZATIVA,
  UO.DS_UNITA_ORGANIZZATIVA,
  ATTIVITA,
  ATTIVITA_BREVE,
  COMPETENZE,
  DURATA,
  SEDE_LAVORO,
  NOTE,
  STATO,
  DATA_PUBBLICAZIONE,
  DATA_FINE_PUBBLICAZIONE,
  DATA_SCADENZA,
  PERSONALE_INTERNO,
  EMAIL_RISPOSTE,
  nr_risorse_da_trovare
--
-- Date: 13/09/2007
-- Version: 1.0
--
-- Vista richieste incarichi utilizzata per ricerca delle competenze
-- necessarie all''interno del CNR, utile alla estrazione in file XML
--
-- History:
--
-- Date: 13/09/2007
-- Version: 1.0
-- Creazione
--
-- Body:
--
from INCARICHI_RICHIESTA, UNITA_ORGANIZZATIVA CDS, UNITA_ORGANIZZATIVA UO
Where INCARICHI_RICHIESTA.CD_CDS = CDS.CD_UNITA_ORGANIZZATIVA
And INCARICHI_RICHIESTA.CD_UNITA_ORGANIZZATIVA = UO.CD_UNITA_ORGANIZZATIVA
And stato In ('C','D')
)
Order By 1,2
;
