--------------------------------------------------------
--  DDL for View V_INCARICHI_CONTROLLO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_INCARICHI_CONTROLLO" ("ESERCIZIO", "PG_REPERTORIO", "CD_UNITA_ORGANIZZATIVA", "DS_UNITA_ORGANIZZATIVA", "NOMINATIVO", "OGGETTO", "IMPORTO_COMPLESSIVO", "DT_INIZIO_VALIDITA", "DT_FINE_VALIDITA", "CD_TIPO_ATTIVITA", "FL_PUBBLICA_CONTRATTO") AS 
  Select
INCARICHI_REPERTORIO.ESERCIZIO,
INCARICHI_REPERTORIO.PG_REPERTORIO,
INCARICHI_REPERTORIO.CD_UNITA_ORGANIZZATIVA,
UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA,
TERZO.DENOMINAZIONE_SEDE NOMINATIVO,
INCARICHI_PROCEDURA.OGGETTO,
INCARICHI_REPERTORIO.IMPORTO_COMPLESSIVO,
INCARICHI_REPERTORIO.DT_INIZIO_VALIDITA,
INCARICHI_REPERTORIO.DT_FINE_VALIDITA,
INCARICHI_PROCEDURA.CD_TIPO_ATTIVITA,
INCARICHI_PROCEDURA.FL_PUBBLICA_CONTRATTO
From INCARICHI_REPERTORIO, INCARICHI_PROCEDURA, UNITA_ORGANIZZATIVA, TERZO
Where INCARICHI_REPERTORIO.ESERCIZIO_PROCEDURA = INCARICHI_PROCEDURA.ESERCIZIO
And   INCARICHI_REPERTORIO.PG_PROCEDURA = INCARICHI_PROCEDURA.PG_PROCEDURA
And   INCARICHI_REPERTORIO.CD_TERZO = TERZO.CD_TERZO
AND   INCARICHI_REPERTORIO.CD_UNITA_ORGANIZZATIVA = UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA;
