--------------------------------------------------------
--  DDL for View V_MANDATO_REVERSALE_VER_CORI_N
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_MANDATO_REVERSALE_VER_CORI_N" (
  "CD_TIPO_DOCUMENTO_CONT",
  "CD_CDS",
  "ESERCIZIO",
  "PG_DOCUMENTO_CONT",
  "CD_UNITA_ORGANIZZATIVA",
  "CD_CDS_ORIGINE",
  "CD_UO_ORIGINE",
  "TI_DOCUMENTO_CONT",
  "DS_DOCUMENTO_CONT",
  "STATO",
  "STATO_TRASMISSIONE",
  "DT_EMISSIONE",
  "DT_TRASMISSIONE",
  "DT_RITRASMISSIONE",
  "DT_PAGAMENTO_INCASSO",
  "DT_ANNULLAMENTO",
  "IM_DOCUMENTO_CONT",
  "IM_RITENUTE",
  "IM_PAGATO_INCASSATO",
  "TI_CC_BI",
  "CD_TERZO",
  "CD_TIPO_DOCUMENTO_CONT_PADRE",
  "PG_DOCUMENTO_CONT_PADRE",
  "TI_DOCUMENTO_CONT_PADRE",
  "PG_VER_REC",
  "VERSAMENTO_CORI",
  "DT_FIRMA",
   "TIPO_DEBITO_SIOPE") AS
  Select
CD_TIPO_DOCUMENTO_CONT, CD_CDS, ESERCIZIO, PG_DOCUMENTO_CONT, CD_UNITA_ORGANIZZATIVA,
CD_CDS_ORIGINE, CD_UO_ORIGINE, TI_DOCUMENTO_CONT, DS_DOCUMENTO_CONT, STATO,
STATO_TRASMISSIONE, DT_EMISSIONE, DT_TRASMISSIONE, DT_RITRASMISSIONE, DT_PAGAMENTO_INCASSO,
DT_ANNULLAMENTO, IM_DOCUMENTO_CONT, IM_RITENUTE, IM_PAGATO_INCASSATO, TI_CC_BI,
CD_TERZO, CD_TIPO_DOCUMENTO_CONT_PADRE, PG_DOCUMENTO_CONT_PADRE, TI_DOCUMENTO_CONT_PADRE, PG_VER_REC, 'N',DT_FIRMA, TIPO_DEBITO_SIOPE
FROM V_MANDATO_REVERSALE
Minus
SELECT
CD_TIPO_DOCUMENTO_CONT, CD_CDS, ESERCIZIO, PG_DOCUMENTO_CONT, CD_UNITA_ORGANIZZATIVA,
CD_CDS_ORIGINE, CD_UO_ORIGINE, TI_DOCUMENTO_CONT, DS_DOCUMENTO_CONT, STATO,
STATO_TRASMISSIONE, DT_EMISSIONE, DT_TRASMISSIONE, DT_RITRASMISSIONE, DT_PAGAMENTO_INCASSO,
DT_ANNULLAMENTO, IM_DOCUMENTO_CONT, IM_RITENUTE, IM_PAGATO_INCASSATO, TI_CC_BI,
CD_TERZO, CD_TIPO_DOCUMENTO_CONT_PADRE, PG_DOCUMENTO_CONT_PADRE, TI_DOCUMENTO_CONT_PADRE, PG_VER_REC, 'N',DT_FIRMA, TIPO_DEBITO_SIOPE
From
V_MANDATO_REVERSALE_VER_CORI
;
