--------------------------------------------------------
--  DDL for View V_OBBLIGAZIONE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_OBBLIGAZIONE" ("ESERCIZIO", "CD_CDS", "ESERCIZIO_ORIGINALE", "PG_OBBLIGAZIONE", "PG_OBBLIGAZIONE_SCADENZARIO", "CD_TIPO_DOCUMENTO_CONT", "FL_PGIRO", "CD_UNITA_ORGANIZZATIVA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "CD_TERZO", "DT_SCADENZA", "IM_SCADENZA", "IM_ASSOCIATO_DOC_AMM", "IM_ASSOCIATO_DOC_CONTABILE", "PG_VER_REC", "PG_VER_REC_SCADENZA") AS 
  (SELECT
--
-- Date: 18/07/2006
-- Version: 1.1
--
-- Vista di estrazione delle obbligazioni, che racchiude in un unico record i dati
-- riportati in OBBLIGAZIONE, OBBLIGAZIONE_SCADENZARIO, OBBLIGAZIONE_SCAD_VOCE
--
-- History:
--
-- Date: 31/03/2006
-- Version: 1.0
-- Creazione
--
-- Date: 18/07/2006
-- Version: 1.1
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body:
--
A.ESERCIZIO,
A.CD_CDS,
A.ESERCIZIO_ORIGINALE,
A.PG_OBBLIGAZIONE,
B.PG_OBBLIGAZIONE_SCADENZARIO,
A.CD_TIPO_DOCUMENTO_CONT,
A.FL_PGIRO,
A.CD_UNITA_ORGANIZZATIVA,
A.CD_CDS_ORIGINE,
A.CD_UO_ORIGINE,
A.CD_TERZO,
B.DT_SCADENZA,
B.IM_SCADENZA,
B.IM_ASSOCIATO_DOC_AMM,
B.IM_ASSOCIATO_DOC_CONTABILE,
A.PG_VER_REC,
B.PG_VER_REC
FROM
OBBLIGAZIONE A,
OBBLIGAZIONE_SCADENZARIO B
WHERE
A.STATO_OBBLIGAZIONE='D' AND
A.FL_PGIRO='N' AND
A.RIPORTATO='N' AND
A.CD_CDS = B.CD_CDS AND
A.ESERCIZIO = B.ESERCIZIO AND
A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE AND
A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE);
