--------------------------------------------------------
--  DDL for View V_PDG_SPE_MOD
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PDG_SPE_MOD" ("ESERCIZIO", "PESO_DIPARTIMENTO", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO", "CD_PROGETTO", "DS_PROGETTO", "CD_COMMESSA", "DS_COMMESSA", "CD_MODULO", "DS_MODULO", "TIPO_PROGETTO", "DS_TIPO_PROGETTO", "CDS", "DS_CDS", "UO", "TIPO_UO", "DS_UO", "CDR", "CD_LINEA_ATTIVITA", "TITOLO", "DS_TITOLO", "CODICE_CLAS_SPESA", "DS_CLASSIFICAZIONE_SPESA", "ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "ORIGINE", "CATEGORIA_DETTAGLIO", "CD_FUNZIONE", "NATURA", "DS_NATURA", "PG_SPESA", "FL_RIBALTATO", "IM_RI_CCS_SPESE_ODC", "IM_RK_CCS_SPESE_OGC", "IM_RQ_SSC_COSTI_ODC", "IM_RS_SSC_COSTI_OGC", "IM_RJ_CCS_SPESE_ODC_ALTRA_UO", "IM_RL_CCS_SPESE_OGC_ALTRA_UO", "IM_RR_SSC_COSTI_ODC_ALTRA_UO", "IM_RT_SSC_COSTI_OGC_ALTRA_UO", "IM_RM_CSS_AMMORTAMENTI", "IM_RN_CSS_RIMANENZE", "IM_RO_CSS_ALTRI_COSTI", "IM_RP_CSS_VERSO_ALTRO_CDR", "IM_RU_SPESE_COSTI_ALTRUI", "IM_RI_CCS_SPESE_ODC_V", "IM_RK_CCS_SPESE_OGC_V", "IM_RQ_SSC_COSTI_ODC_V", "IM_RS_SSC_COSTI_OGC_V", "IM_RJ_CCS_SPESE_ODC_ALTRA_UO_V", "IM_RL_CCS_SPESE_OGC_ALTRA_UO_V", "IM_RR_SSC_COSTI_ODC_ALTRA_UO_V", "IM_RT_SSC_COSTI_OGC_ALTRA_UO_V", "IM_RM_CSS_AMMORTAMENTI_V", "IM_RN_CSS_RIMANENZE_V", "IM_RO_CSS_ALTRI_COSTI_V", "IM_RP_CSS_VERSO_ALTRO_CDR_V", "IM_RU_SPESE_COSTI_ALTRUI_V") AS 
  Select
--
-- Date: 09/11/2006
-- Version: 1.1
--
-- Vista per la consultazione del PDG per commessa parte spesa
-- con importi suddivisi tra iniziali e variati
--
-- History:
--
-- Date: 25/08/2005
-- Version: 1.0
-- Creazione
--
-- Date: 09/11/2006
-- Version: 1.1
-- Aggiunta la selezione del progetto/commessa/modulo per anno
--
-- Body:
--
PDG_PREVENTIVO_SPE_DET.ESERCIZIO,
nvl(p.peso,1000),
Nvl(progetto.cd_dipartimento, Null),
p.DS_DIPARTIMENTO,
PROGETTO.CD_PROGETTO,
PROGETTO.DS_PROGETTO,
COM.CD_PROGETTO,
COM.DS_PROGETTO,
MODU.CD_PROGETTO,
MODU.DS_PROGETTO,
MODU.CD_TIPO_PROGETTO,
TIPO_PROGETTO.DS_TIPO_PROGETTO,
CDS.CD_UNITA_ORGANIZZATIVA,
CDS.DS_UNITA_ORGANIZZATIVA ,
UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
UNITA_ORGANIZZATIVA.CD_TIPO_UNITA,
UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA ,
DECODE(PDG_PREVENTIVO_SPE_DET.CD_NATURA,'5',UNITA_ORGANIZZATIVA.CD_AREA_RICERCA,PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA),
PDG_PREVENTIVO_SPE_DET.CD_LINEA_ATTIVITA,
TITOLO.CD_ELEMENTO_VOCE,
TITOLO.DS_ELEMENTO_VOCE,
CLASSIFICAZIONE_SPESE.CODICE_CLA_S,
CLASSIFICAZIONE_SPESE.DESCRIZIONE,
ELEMENTO_VOCE.CD_ELEMENTO_VOCE,
elemento_voce.ds_elemento_voce,
PDG_PREVENTIVO_SPE_DET.ORIGINE,
PDG_PREVENTIVO_SPE_DET.CATEGORIA_DETTAGLIO,
PDG_PREVENTIVO_SPE_DET.CD_FUNZIONE,
PDG_PREVENTIVO_SPE_DET.CD_NATURA,
natura.ds_natura,
PDG_PREVENTIVO_SPE_DET.PG_SPESA,
PDG_PREVENTIVO.FL_RIBALTATO_SU_AREA,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RI_CCS_SPESE_ODC, 0) IM_RI_CCS_SPESE_ODC,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RK_CCS_SPESE_OGC, 0) IM_RK_CCS_SPESE_OGC,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RQ_SSC_COSTI_ODC, 0) IM_RQ_SSC_COSTI_ODC,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RS_SSC_COSTI_OGC, 0) IM_RS_SSC_COSTI_OGC,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RJ_CCS_SPESE_ODC_ALTRA_UO, 0) IM_RJ_CCS_SPESE_ODC_ALTRA_UO,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RL_CCS_SPESE_OGC_ALTRA_UO, 0) IM_RL_CCS_SPESE_OGC_ALTRA_UO,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RR_SSC_COSTI_ODC_ALTRA_UO, 0) IM_RR_SSC_COSTI_ODC_ALTRA_UO,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RT_SSC_COSTI_OGC_ALTRA_UO, 0) IM_RT_SSC_COSTI_OGC_ALTRA_UO,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RM_CSS_AMMORTAMENTI, 0) IM_RM_CSS_AMMORTAMENTI,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RN_CSS_RIMANENZE, 0) IM_RN_CSS_RIMANENZE,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RO_CSS_ALTRI_COSTI, 0) IM_RO_CSS_ALTRI_COSTI,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RP_CSS_VERSO_ALTRO_CDR, 0) IM_RP_CSS_VERSO_ALTRO_CDR,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RU_SPESE_COSTI_ALTRUI, 0) IM_RU_SPESE_COSTI_ALTRUI,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RI_CCS_SPESE_ODC) IM_RI_CCS_SPESE_ODC_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RK_CCS_SPESE_OGC) IM_RK_CCS_SPESE_OGC_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RQ_SSC_COSTI_ODC) IM_RQ_SSC_COSTI_ODC_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RS_SSC_COSTI_OGC) IM_RS_SSC_COSTI_OGC_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RJ_CCS_SPESE_ODC_ALTRA_UO) IM_RJ_CCS_SPESE_ODC_ALTRA_UO_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RL_CCS_SPESE_OGC_ALTRA_UO) IM_RL_CCS_SPESE_OGC_ALTRA_UO_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RR_SSC_COSTI_ODC_ALTRA_UO) IM_RR_SSC_COSTI_ODC_ALTRA_UO_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RT_SSC_COSTI_OGC_ALTRA_UO) IM_RT_SSC_COSTI_OGC_ALTRA_UO_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RM_CSS_AMMORTAMENTI) IM_RM_CSS_AMMORTAMENTI_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RN_CSS_RIMANENZE)	 IM_RN_CSS_RIMANENZE_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RO_CSS_ALTRI_COSTI) IM_RO_CSS_ALTRI_COSTI_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RP_CSS_VERSO_ALTRO_CDR) IM_RP_CSS_VERSO_ALTRO_CDR_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RU_SPESE_COSTI_ALTRUI) IM_RU_SPESE_COSTI_ALTRUI_V
From
PDG_PREVENTIVO,
PDG_PREVENTIVO_SPE_DET ,
CLASSIFICAZIONE_SPESE ,
ELEMENTO_VOCE TITOLO,
ELEMENTO_VOCE ,
LINEA_ATTIVITA ,
natura,
CDR,
UNITA_ORGANIZZATIVA,
UNITA_ORGANIZZATIVA CDS,
PROGETTO_PREV PROGETTO,
PROGETTO_PREV COM,
PROGETTO_PREV MODU,
TIPO_PROGETTO,
DIPARTIMENTO,
	dipartimento_peso p
Where
 PROGETTO.esercizio= p.esercizio(+) AND
 PROGETTO.cd_dipartimento= p.cd_dipartimento (+) and
   PDG_PREVENTIVO.ESERCIZIO                        = PDG_PREVENTIVO_SPE_DET.ESERCIZIO
And     PDG_PREVENTIVO.CD_CENTRO_RESPONSABILITA         = PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA
And     CLASSIFICAZIONE_SPESE.ESERCIZIO		        = ELEMENTO_VOCE.ESERCIZIO_CLA_S
And 	CLASSIFICAZIONE_SPESE.CODICE_CLA_S		= ELEMENTO_VOCE.COD_CLA_S
And 	ELEMENTO_VOCE.ESERCIZIO				= TITOLO.ESERCIZIO
And 	ELEMENTO_VOCE.TI_APPARTENENZA			= TITOLO.TI_APPARTENENZA
And 	ELEMENTO_VOCE.TI_GESTIONE			= TITOLO.TI_GESTIONE
And 	ELEMENTO_VOCE.CD_ELEMENTO_PADRE			= TITOLO.CD_ELEMENTO_VOCE
And 	ELEMENTO_VOCE.ESERCIZIO 			= PDG_PREVENTIVO_SPE_DET.ESERCIZIO
And 	ELEMENTO_VOCE.TI_APPARTENENZA 		  	= PDG_PREVENTIVO_SPE_DET.TI_APPARTENENZA
And 	ELEMENTO_VOCE.TI_GESTIONE			= PDG_PREVENTIVO_SPE_DET.TI_GESTIONE
And 	ELEMENTO_VOCE.CD_ELEMENTO_VOCE		  	= PDG_PREVENTIVO_SPE_DET.CD_ELEMENTO_VOCE
And     PDG_PREVENTIVO_SPE_DET.cd_natura                = natura.cd_natura
And 	PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA	= LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA
And 	PDG_PREVENTIVO_SPE_DET.CD_LINEA_ATTIVITA	= LINEA_ATTIVITA.CD_LINEA_ATTIVITA
And 	LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA		= CDR.CD_CENTRO_RESPONSABILITA
And 	CDR.CD_UNITA_ORGANIZZATIVA			= UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And 	UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
And 	LINEA_ATTIVITA.PG_PROGETTO			IS NOT NULL
And 	LINEA_ATTIVITA.PG_PROGETTO			= MODU.PG_PROGETTO
And 	MODU.ESERCIZIO                                  = PDG_PREVENTIVO.ESERCIZIO
And 	MODU.ESERCIZIO_PROGETTO_PADRE			= COM.ESERCIZIO
And 	MODU.PG_PROGETTO_PADRE				= COM.PG_PROGETTO
And 	COM.ESERCIZIO_PROGETTO_PADRE			= PROGETTO.ESERCIZIO
And     COM.PG_PROGETTO_PADRE                      	= PROGETTO.PG_PROGETTO
And     MODU.CD_TIPO_PROGETTO                           = TIPO_PROGETTO.cd_tipo_progetto
And     PROGETTO.CD_DIPARTIMENTO                        = DIPARTIMENTO.CD_DIPARTIMENTO
And     PDG_PREVENTIVO_SPE_DET.ESERCIZIO                = 2005
And     PDG_PREVENTIVO_SPE_DET.STATO                    = 'Y'
Union
Select
PDG_PREVENTIVO_SPE_DET.ESERCIZIO,
DECODE(UNITA_ORGANIZZATIVA.CD_TIPO_UNITA,'SAC',13,1000),
DECODE(UNITA_ORGANIZZATIVA.CD_TIPO_UNITA,'SAC','SAC',UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA),
DECODE(UNITA_ORGANIZZATIVA.CD_TIPO_UNITA,'SAC',CDS.DS_UNITA_ORGANIZZATIVA,NULL),
Null,
Null,
Null,
Null,
Null,
Null,
Null,
Null,
CDS.CD_UNITA_ORGANIZZATIVA,
CDS.DS_UNITA_ORGANIZZATIVA ,
UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
UNITA_ORGANIZZATIVA.CD_TIPO_UNITA,
UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA ,
PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA,
PDG_PREVENTIVO_SPE_DET.CD_LINEA_ATTIVITA,
TITOLO.CD_ELEMENTO_VOCE,
TITOLO.DS_ELEMENTO_VOCE,
CLASSIFICAZIONE_SPESE.CODICE_CLA_S,
CLASSIFICAZIONE_SPESE.DESCRIZIONE,
ELEMENTO_VOCE.CD_ELEMENTO_VOCE,
elemento_voce.ds_elemento_voce,
PDG_PREVENTIVO_SPE_DET.ORIGINE,
PDG_PREVENTIVO_SPE_DET.CATEGORIA_DETTAGLIO,
PDG_PREVENTIVO_SPE_DET.CD_FUNZIONE,
PDG_PREVENTIVO_SPE_DET.CD_NATURA,
natura.ds_natura,
PDG_PREVENTIVO_SPE_DET.PG_SPESA,
PDG_PREVENTIVO.FL_RIBALTATO_SU_AREA,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RI_CCS_SPESE_ODC, 0) IM_RI_CCS_SPESE_ODC,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RK_CCS_SPESE_OGC, 0) IM_RK_CCS_SPESE_OGC,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RQ_SSC_COSTI_ODC, 0) IM_RQ_SSC_COSTI_ODC,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RS_SSC_COSTI_OGC, 0) IM_RS_SSC_COSTI_OGC,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RJ_CCS_SPESE_ODC_ALTRA_UO, 0) IM_RJ_CCS_SPESE_ODC_ALTRA_UO,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RL_CCS_SPESE_OGC_ALTRA_UO, 0) IM_RL_CCS_SPESE_OGC_ALTRA_UO,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RR_SSC_COSTI_ODC_ALTRA_UO, 0) IM_RR_SSC_COSTI_ODC_ALTRA_UO,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RT_SSC_COSTI_OGC_ALTRA_UO, 0) IM_RT_SSC_COSTI_OGC_ALTRA_UO,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RM_CSS_AMMORTAMENTI, 0) IM_RM_CSS_AMMORTAMENTI,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RN_CSS_RIMANENZE, 0) IM_RN_CSS_RIMANENZE,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RO_CSS_ALTRI_COSTI, 0) IM_RO_CSS_ALTRI_COSTI,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RP_CSS_VERSO_ALTRO_CDR, 0) IM_RP_CSS_VERSO_ALTRO_CDR,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, PDG_PREVENTIVO_SPE_DET.IM_RU_SPESE_COSTI_ALTRUI, 0) IM_RU_SPESE_COSTI_ALTRUI,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RI_CCS_SPESE_ODC) IM_RI_CCS_SPESE_ODC_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RK_CCS_SPESE_OGC) IM_RK_CCS_SPESE_OGC_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RQ_SSC_COSTI_ODC) IM_RQ_SSC_COSTI_ODC_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RS_SSC_COSTI_OGC) IM_RS_SSC_COSTI_OGC_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RJ_CCS_SPESE_ODC_ALTRA_UO) IM_RJ_CCS_SPESE_ODC_ALTRA_UO_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RL_CCS_SPESE_OGC_ALTRA_UO) IM_RL_CCS_SPESE_OGC_ALTRA_UO_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RR_SSC_COSTI_ODC_ALTRA_UO) IM_RR_SSC_COSTI_ODC_ALTRA_UO_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RT_SSC_COSTI_OGC_ALTRA_UO) IM_RT_SSC_COSTI_OGC_ALTRA_UO_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RM_CSS_AMMORTAMENTI) IM_RM_CSS_AMMORTAMENTI_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RN_CSS_RIMANENZE)	 IM_RN_CSS_RIMANENZE_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RO_CSS_ALTRI_COSTI) IM_RO_CSS_ALTRI_COSTI_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RP_CSS_VERSO_ALTRO_CDR) IM_RP_CSS_VERSO_ALTRO_CDR_V,
decode(PDG_PREVENTIVO_SPE_DET.PG_VARIAZIONE_PDG, null, 0, PDG_PREVENTIVO_SPE_DET.IM_RU_SPESE_COSTI_ALTRUI) IM_RU_SPESE_COSTI_ALTRUI_V
From
PDG_PREVENTIVO,
PDG_PREVENTIVO_SPE_DET ,
CLASSIFICAZIONE_SPESE ,
ELEMENTO_VOCE TITOLO,
ELEMENTO_VOCE ,
LINEA_ATTIVITA ,
natura,
CDR,
UNITA_ORGANIZZATIVA,
UNITA_ORGANIZZATIVA CDS
Where   PDG_PREVENTIVO.ESERCIZIO                        = PDG_PREVENTIVO_SPE_DET.ESERCIZIO
And     PDG_PREVENTIVO.CD_CENTRO_RESPONSABILITA         = PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA
And     CLASSIFICAZIONE_SPESE.ESERCIZIO		        = ELEMENTO_VOCE.ESERCIZIO_CLA_S
And 	CLASSIFICAZIONE_SPESE.CODICE_CLA_S		= ELEMENTO_VOCE.COD_CLA_S
And 	ELEMENTO_VOCE.ESERCIZIO				= TITOLO.ESERCIZIO
And 	ELEMENTO_VOCE.TI_APPARTENENZA			= TITOLO.TI_APPARTENENZA
And 	ELEMENTO_VOCE.TI_GESTIONE			= TITOLO.TI_GESTIONE
And 	ELEMENTO_VOCE.CD_ELEMENTO_PADRE			= TITOLO.CD_ELEMENTO_VOCE
And 	ELEMENTO_VOCE.ESERCIZIO 			= PDG_PREVENTIVO_SPE_DET.ESERCIZIO
And 	ELEMENTO_VOCE.TI_APPARTENENZA 		  	= PDG_PREVENTIVO_SPE_DET.TI_APPARTENENZA
And 	ELEMENTO_VOCE.TI_GESTIONE			= PDG_PREVENTIVO_SPE_DET.TI_GESTIONE
And 	ELEMENTO_VOCE.CD_ELEMENTO_VOCE		  	= PDG_PREVENTIVO_SPE_DET.CD_ELEMENTO_VOCE
And     PDG_PREVENTIVO_SPE_DET.cd_natura                = natura.cd_natura
And 	PDG_PREVENTIVO_SPE_DET.CD_CENTRO_RESPONSABILITA	= LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA
And 	PDG_PREVENTIVO_SPE_DET.CD_LINEA_ATTIVITA	= LINEA_ATTIVITA.CD_LINEA_ATTIVITA
And 	LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA		= CDR.CD_CENTRO_RESPONSABILITA
And 	CDR.CD_UNITA_ORGANIZZATIVA			= UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA
And 	UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
And 	LINEA_ATTIVITA.PG_PROGETTO			IS NULL
And     PDG_PREVENTIVO_SPE_DET.ESERCIZIO                = 2005
And     PDG_PREVENTIVO_SPE_DET.STATO                    = 'Y';
