--------------------------------------------------------
--  DDL for View V_PDG_PIANO_RIPARTO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PDG_PIANO_RIPARTO" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "ID_CLASSIFICAZIONE", "CD_CLASSIFICAZIONE", "DS_CLASSIFICAZIONE", "IMPORTO_ASSEGNATO", "IMPORTO_RIPARTITO", "IMPORTO_DA_RIPARTIRE") AS 
  Select A.ESERCIZIO, A.CD_CENTRO_RESPONSABILITA, B.DS_CDR, A.ID_CLASSIFICAZIONE,
       C.CD_CLASSIFICAZIONE, C.DS_CLASSIFICAZIONE,
       SUM(A.IMPORTO_ASSEGNATO) IMPORTO_ASSEGNATO, SUM(A.IMPORTO_RIPARTITO) IMPORTO_RIPARTITO,
       SUM(A.IMPORTO_ASSEGNATO) - SUM(A.IMPORTO_RIPARTITO) IMPORTO_DA_RIPARTIRE
From (Select ESERCIZIO,
             CD_CENTRO_RESPONSABILITA,
             ID_CLASSIFICAZIONE,
             IM_TOT_SPESE_ACC IMPORTO_ASSEGNATO,
             0 IMPORTO_RIPARTITO
      From PDG_PIANO_RIPARTO
      Union All
      Select PDG_MODULO_SPESE.ESERCIZIO,
             CD_CENTRO_RESPONSABILITA,
             PDG_MODULO_SPESE.ID_CLASSIFICAZIONE,
             0 IMPORTO_ASSEGNATO,
             Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0) +
             Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_SPESE, CLASSIFICAZIONE_VOCI
      Where PDG_MODULO_SPESE.id_classificazione=CLASSIFICAZIONE_VOCI.id_classificazione
      And   CLASSIFICAZIONE_VOCI.FL_PIANO_RIPARTO='Y'
      And   PDG_MODULO_SPESE.ID_CLASSIFICAZIONE Not In (Select ID_CLASSIFICAZIONE From PDG_PIANO_RIPARTO
                                   Where PDG_PIANO_RIPARTO.esercizio = PDG_MODULO_SPESE.esercizio
                                   And   PDG_PIANO_RIPARTO.cd_centro_responsabilita = PDG_MODULO_SPESE.cd_centro_responsabilita)
      union all
      Select ESERCIZIO,
             CD_CENTRO_RESPONSABILITA,
             ID_CLASSIFICAZIONE,
             Null IMPORTO_ASSEGNATO,
             Nvl(IM_SPESE_GEST_ACCENTRATA_INT, 0) +
             Nvl(IM_SPESE_GEST_ACCENTRATA_EST, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_SPESE
      Where ID_CLASSIFICAZIONE In (Select ID_CLASSIFICAZIONE From PDG_PIANO_RIPARTO
                                   Where PDG_PIANO_RIPARTO.esercizio = PDG_MODULO_SPESE.esercizio
                                   And   PDG_PIANO_RIPARTO.cd_centro_responsabilita = PDG_MODULO_SPESE.cd_centro_responsabilita)
      union all
      Select a.ESERCIZIO,
             a.CD_CENTRO_RESPONSABILITA,
             To_Number(b.VAL01) ID_CLASSIFICAZIONE,
             Null IMPORTO_ASSEGNATO,
             Nvl(a.IM_CF_AMM_IMMOBILI, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_COSTI a, CONFIGURAZIONE_CNR b
      Where a.ESERCIZIO = b.ESERCIZIO
      And   b.CD_CHIAVE_PRIMARIA = 'PIANO_RIPARTO'
      And   b.CD_CHIAVE_SECONDARIA = 'IM_CF_AMM_IMMOBILI'
      union all
      Select a.ESERCIZIO,
             a.CD_CENTRO_RESPONSABILITA,
             To_Number(b.VAL01) ID_CLASSIFICAZIONE,
             Null IMPORTO_ASSEGNATO,
             Nvl(a.IM_CF_AMM_ATTREZZ, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_COSTI a, CONFIGURAZIONE_CNR b
      Where a.ESERCIZIO = b.ESERCIZIO
      And   b.CD_CHIAVE_PRIMARIA = 'PIANO_RIPARTO'
      And   b.CD_CHIAVE_SECONDARIA = 'IM_CF_AMM_ATTREZZ'
      union all
      Select a.ESERCIZIO,
             a.CD_CENTRO_RESPONSABILITA,
             To_Number(b.VAL01) ID_CLASSIFICAZIONE,
             Null IMPORTO_ASSEGNATO,
             Nvl(a.IM_CF_AMM_ALTRO, 0) IMPORTO_RIPARTITO
      From PDG_MODULO_COSTI a, CONFIGURAZIONE_CNR b
      Where a.ESERCIZIO = b.ESERCIZIO
      And   b.CD_CHIAVE_PRIMARIA = 'PIANO_RIPARTO'
      And   b.CD_CHIAVE_SECONDARIA = 'IM_CF_AMM_ALTRO') A, CDR B, V_CLASSIFICAZIONE_VOCI C
Where A.CD_CENTRO_RESPONSABILITA = B.CD_CENTRO_RESPONSABILITA
and   A.ID_CLASSIFICAZIONE = C.ID_CLASSIFICAZIONE
Group by A.ESERCIZIO, A.CD_CENTRO_RESPONSABILITA, B.DS_CDR,
         A.ID_CLASSIFICAZIONE, C.CD_CLASSIFICAZIONE, C.DS_CLASSIFICAZIONE
;
