--------------------------------------------------------
--  DDL for View V_PDG_VARIAZIONE_RIEPILOGO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PDG_VARIAZIONE_RIEPILOGO" ("ESERCIZIO", "PG_VARIAZIONE_PDG", "TI_GESTIONE", "CD_CDR_ASSEGNATARIO", "DS_CDR", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO", "IM_TOTALE") AS 
  SELECT
--
-- Date: 12/02/2008
-- Version: 1.0
--
-- Vista riepilogo variazioni di competenza per CdR/Dipartimento
-- utile nel corrispondente tab in Variazioni Stanziamento di Competenza
--
-- History:
--
-- Date: 12/02/2008
-- Version: 1.0
-- Creazione
--
-- Body:
--
PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO, PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG,
PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE, CD_CDR_ASSEGNATARIO, DS_CDR,
PRO.CD_DIPARTIMENTO, DS_DIPARTIMENTO,
Sum(IM_SPESE_GEST_DECENTRATA_INT+IM_SPESE_GEST_DECENTRATA_EST+IM_SPESE_GEST_ACCENTRATA_INT+IM_SPESE_GEST_ACCENTRATA_EST+IM_ENTRATA) IM_TOTALE
From
PDG_VARIAZIONE_RIGA_GEST,
LINEA_ATTIVITA,
PROGETTO MOD,
PROGETTO COM,
PROGETTO PRO,
DIPARTIMENTO,
CDR
Where PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO = LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA and 
      PDG_VARIAZIONE_RIGA_GEST.CD_LINEA_ATTIVITA = LINEA_ATTIVITA.CD_LINEA_ATTIVITA And
      MOD.ESERCIZIO = PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO And
      MOD.PG_PROGETTO = LINEA_ATTIVITA.PG_PROGETTO And
      MOD.TIPO_FASE = 'G' And
      MOD.ESERCIZIO_PROGETTO_PADRE = COM.ESERCIZIO And
      MOD.PG_PROGETTO_PADRE = COM.PG_PROGETTO  And
      MOD.TIPO_FASE_PROGETTO_PADRE = COM.TIPO_FASE And
      COM.ESERCIZIO_PROGETTO_PADRE = PRO.ESERCIZIO And
      COM.PG_PROGETTO_PADRE = PRO.PG_PROGETTO And
      COM.TIPO_FASE_PROGETTO_PADRE = PRO.TIPO_FASE And
      PDG_VARIAZIONE_RIGA_GEST.CD_CDR_ASSEGNATARIO = CDR.CD_CENTRO_RESPONSABILITA And
      PRO.CD_DIPARTIMENTO = DIPARTIMENTO.CD_DIPARTIMENTO
Group By PDG_VARIAZIONE_RIGA_GEST.ESERCIZIO, PDG_VARIAZIONE_RIGA_GEST.PG_VARIAZIONE_PDG,
PDG_VARIAZIONE_RIGA_GEST.TI_GESTIONE, CD_CDR_ASSEGNATARIO, DS_CDR, PRO.CD_DIPARTIMENTO, DS_DIPARTIMENTO
Order By 1,2,3,4,5,6 ;
