--------------------------------------------------------
--  DDL for View V_PROGETTO_ANAG
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_PROGETTO_ANAG" ("PESO_DIPARTIMENTO", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "UO_COORDIN_PROG", "PG_COMMESSA", "CD_COMMESSA", "DS_COMMESSA", "UO_COORDIN_COMM", "CD_RESP_COMM", "RESP_COMM", "PG_MODULO", "CD_MODULO", "DS_MODULO", "UO_COORDIN_MOD", "CD_RESP_MODU", "RESP_MODU", "TIPO_PROGETTO", "DS_TIPO_PROGETTO") AS 
  Select
--
-- Date: 01/06/2005
-- Version: 1.0
--
-- Anagrafica progetto - commessa - modulo
--
-- History:
--
-- Date: 01/06/2005
-- Version: 1.0
-- Creazione
--
-- Body:
--
DECODE(PROGETTO.CD_DIPARTIMENTO,'TA',1,'ET',2,'AG',3,'ME',4,'SV',5,'PM',6,'MD',7,'SP',8,'ICT',9,'IC',10,'PC',11,'DG',12,'SAC',13,1000),
NVL(PROGETTO.CD_DIPARTIMENTO,NULL),
NVL(DIPARTIMENTO.DS_DIPARTIMENTO,NULL),
progetto.pg_progetto,
PROGETTO.CD_PROGETTO,
PROGETTO.DS_PROGETTO,
progetto.CD_UNITA_ORGANIZZATIVA,
--UO_PROGETTO.CD_UNITA_ORGANIZZATIVA,
com.pg_progetto,
COM.CD_PROGETTO,
COM.DS_PROGETTO,
com.CD_UNITA_ORGANIZZATIVA,
com.CD_RESPONSABILE_TERZO,
TERZO.DENOMINAZIONE_SEDE,
modu.pg_progetto,
MODU.CD_PROGETTO,
MODU.DS_PROGETTO,
modu.CD_UNITA_ORGANIZZATIVA,
modu.CD_RESPONSABILE_TERZO,
TERZO.DENOMINAZIONE_SEDE,
MODU.CD_TIPO_PROGETTO,
TIPO_PROGETTO.DS_TIPO_PROGETTO
--CDS.CD_UNITA_ORGANIZZATIVA,
--CDS.DS_UNITA_ORGANIZZATIVA ,
--UNITA_ORGANIZZATIVA.CD_UNITA_ORGANIZZATIVA,
--UNITA_ORGANIZZATIVA.CD_TIPO_UNITA,
--UNITA_ORGANIZZATIVA.DS_UNITA_ORGANIZZATIVA 
From
  --UNITA_ORGANIZZATIVA,
  --UNITA_ORGANIZZATIVA CDS,
PROGETTO,
PROGETTO COM,
PROGETTO MODU,
TIPO_PROGETTO,
DIPARTIMENTO, 
TERZO
--UO_PROGETTO
Where   
--        UNITA_ORGANIZZATIVA.CD_UNITA_PADRE		= CDS.CD_UNITA_ORGANIZZATIVA
 	MODU.PG_PROGETTO_PADRE			                    = COM.PG_PROGETTO
And     COM.PG_PROGETTO_PADRE                       	= PROGETTO.PG_PROGETTO
And     MODU.CD_TIPO_PROGETTO                           = TIPO_PROGETTO.cd_tipo_progetto
And     PROGETTO.CD_DIPARTIMENTO                        = DIPARTIMENTO.CD_DIPARTIMENTO
and     com.CD_RESPONSABILE_TERZO			= TERZO.CD_TERZO
and 	modu.cd_responsabile_terzo			= TERZO.CD_TERZO
order by 1,progetto.PG_PROGETTO,com.PG_progetto,modu.PG_progetto
;
