--------------------------------------------------------
--  DDL for View V_RICO_RESIDUI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_RICO_RESIDUI" ("CDR_TESTATA", "PG_STORICO", "ESERCIZIO", "CDR_DETTAGLI", "PG_DETTAGLIO", "CDR_LINEA", "CD_LINEA_ATTIVITA", "ID_CLASSIFICAZIONE", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_ELEMENTO_VOCE", "PG_PROGETTO", "IM_RESIDUO") AS 
  SELECT PDG_RESIDUO.CD_CENTRO_RESPONSABILITA, 
0,
PDG_RESIDUO_DET.ESERCIZIO,
PDG_RESIDUO_DET.CD_CENTRO_RESPONSABILITA,
PDG_RESIDUO_DET.PG_DETTAGLIO,
PDG_RESIDUO_DET.CD_CDR_LINEA,
PDG_RESIDUO_DET.CD_LINEA_ATTIVITA,
CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE,
CLASSIFICAZIONE_VOCI.cd_livello1,   
CLASSIFICAZIONE_VOCI.cd_livello2,
CLASSIFICAZIONE_VOCI.cd_livello3,
CLASSIFICAZIONE_VOCI.cd_livello4,
PDG_RESIDUO_DET.CD_ELEMENTO_VOCE,
NVL(LINEA_ATTIVITA.pg_progetto, NULL),
PDG_RESIDUO_DET.IM_RESIDUO
FROM	 PDG_RESIDUO, 
	 PDG_RESIDUO_DET, 
	 LINEA_ATTIVITA,
	 ELEMENTO_VOCE,
	 CLASSIFICAZIONE_VOCI
WHERE 	 PDG_RESIDUO.ESERCIZIO                  = 2005
AND	 PDG_RESIDUO.STATO                      = 'C'
AND	 PDG_RESIDUO_DET.STATO                  = 'I'
AND	 PDG_RESIDUO.ESERCIZIO                  = PDG_RESIDUO_DET.ESERCIZIO
AND	 PDG_RESIDUO.CD_CENTRO_RESPONSABILITA   = PDG_RESIDUO_DET.CD_CENTRO_RESPONSABILITA
AND	 PDG_RESIDUO_DET.CD_CDR_LINEA           = LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA
AND	 PDG_RESIDUO_DET.CD_LINEA_ATTIVITA      = LINEA_ATTIVITA.CD_LINEA_ATTIVITA
AND	 PDG_RESIDUO_DET.ESERCIZIO              = ELEMENTO_VOCE.ESERCIZIO
AND	 PDG_RESIDUO_DET.TI_GESTIONE            = ELEMENTO_VOCE.TI_GESTIONE
AND	 PDG_RESIDUO_DET.TI_APPARTENENZA        = ELEMENTO_VOCE.TI_APPARTENENZA
AND	 PDG_RESIDUO_DET.CD_ELEMENTO_VOCE       = ELEMENTO_VOCE.CD_ELEMENTO_VOCE
AND	 ELEMENTO_VOCE.ID_CLASSIFICAZIONE       = CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE
UNION
SELECT PDG_RESIDUO_S.CD_CENTRO_RESPONSABILITA, 
PDG_RESIDUO_S.PG_STORICO_,
PDG_RESIDUO_DET_S.ESERCIZIO,
PDG_RESIDUO_DET_S.CD_CENTRO_RESPONSABILITA,
PDG_RESIDUO_DET_S.PG_DETTAGLIO,
PDG_RESIDUO_DET_S.CD_CDR_LINEA,
PDG_RESIDUO_DET_S.CD_LINEA_ATTIVITA, 
CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE,
CLASSIFICAZIONE_VOCI.cd_livello1,     
CLASSIFICAZIONE_VOCI.cd_livello2,     
CLASSIFICAZIONE_VOCI.cd_livello3,     
CLASSIFICAZIONE_VOCI.cd_livello4,     
PDG_RESIDUO_DET_S.CD_ELEMENTO_VOCE,
NVL(LINEA_ATTIVITA.pg_progetto, NULL),
PDG_RESIDUO_DET_S.IM_RESIDUO
FROM	 PDG_RESIDUO_S, 
         PDG_RESIDUO,
	 PDG_RESIDUO_DET_S, 
	 LINEA_ATTIVITA,
	 ELEMENTO_VOCE,
	 CLASSIFICAZIONE_VOCI
WHERE 	 PDG_RESIDUO_S.ESERCIZIO                  = 2005
AND      PDG_RESIDUO.STATO                        != 'C'
AND	 PDG_RESIDUO_DET_S.STATO                  = 'I'
AND	 ((PDG_RESIDUO_S.ESERCIZIO, PDG_RESIDUO_S.CD_CENTRO_RESPONSABILITA, PDG_RESIDUO_S.PG_STORICO_) IN 
	 		(SELECT ESERCIZIO, cd_centro_responsabilita, MAX(pg_storico_)
			FROM PDG_RESIDUO_S
			WHERE ESERCIZIO = 2005
			GROUP BY ESERCIZIO, cd_centro_responsabilita)) 
AND      PDG_RESIDUO.ESERCIZIO                    = PDG_RESIDUO_S.ESERCIZIO
AND      PDG_RESIDUO.CD_CENTRO_RESPONSABILITA     = PDG_RESIDUO_S.CD_CENTRO_RESPONSABILITA      
AND	 PDG_RESIDUO_S.ESERCIZIO                  = PDG_RESIDUO_DET_S.ESERCIZIO
AND	 PDG_RESIDUO_S.CD_CENTRO_RESPONSABILITA   = PDG_RESIDUO_DET_S.CD_CENTRO_RESPONSABILITA
AND	 PDG_RESIDUO_S.PG_STORICO_				  	= PDG_RESIDUO_DET_S.PG_STORICO_
AND	 PDG_RESIDUO_DET_S.CD_CDR_LINEA           = LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA
AND	 PDG_RESIDUO_DET_S.CD_LINEA_ATTIVITA      = LINEA_ATTIVITA.CD_LINEA_ATTIVITA
AND	 PDG_RESIDUO_DET_S.ESERCIZIO              = ELEMENTO_VOCE.ESERCIZIO
AND	 PDG_RESIDUO_DET_S.TI_GESTIONE            = ELEMENTO_VOCE.TI_GESTIONE
AND	 PDG_RESIDUO_DET_S.TI_APPARTENENZA        = ELEMENTO_VOCE.TI_APPARTENENZA
AND	 PDG_RESIDUO_DET_S.CD_ELEMENTO_VOCE       = ELEMENTO_VOCE.CD_ELEMENTO_VOCE
AND	 ELEMENTO_VOCE.ID_CLASSIFICAZIONE       = CLASSIFICAZIONE_VOCI.ID_CLASSIFICAZIONE;
