--------------------------------------------------------
--  DDL for View V_SITUAZIONE_LINEE_COMP_RES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_SITUAZIONE_LINEE_COMP_RES" ("ESERCIZIO", "ESERCIZIO_RES", "CD_CENTRO_RESPONSABILITA", "CD_CDS", "CD_LINEA_ATTIVITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_VOCE", "CD_ELEMENTO_VOCE", "FL_PARTITA_GIRO", "TOT_IM_RESIDUI_RICOSTRUITI", "TOT_IM_STANZ_INIZIALE_A1", "TOT_VARIAZIONI_PIU", "TOT_VARIAZIONI_MENO", "TOT_IM_OBBL_ACC_COMP", "DISP_COMP", "TOT_IM_STANZ_RES_IMPROPRIO", "TOT_VAR_PIU_STANZ_RES_IMP", "TOT_VAR_MENO_STANZ_RES_IMP", "TOT_IM_OBBL_RES_IMP", "TOT_VAR_PIU_OBBL_RES_IMP", "TOT_VAR_MENO_OBBL_RES_IMP", "TOT_VAR_PIU_OBBL_RES_PRO", "TOT_VAR_MENO_OBBL_RES_PRO", "DISP_RES_IMP") AS 
  SELECT V_DISP_RES_IMPROPRIE.ESERCIZIO,
       V_DISP_RES_IMPROPRIE.ESERCIZIO_RES,
       V_DISP_RES_IMPROPRIE.CD_CENTRO_RESPONSABILITA,
       CNRUTL001.GETCDSFROMCDR(V_DISP_RES_IMPROPRIE.cd_centro_responsabilita) CD_cds,
       V_DISP_RES_IMPROPRIE.CD_LINEA_ATTIVITA,
       V_DISP_RES_IMPROPRIE.TI_APPARTENENZA,
       V_DISP_RES_IMPROPRIE.TI_GESTIONE,
       V_DISP_RES_IMPROPRIE.CD_VOCE,
       nvl(VOCE_F.cd_elemento_voce,V_DISP_RES_IMPROPRIE.CD_VOCE) cd_elemento_voce,
       FL_PARTITA_GIRO,
       SUM(TOT_IM_RESIDUI_RICOSTRUITI) TOT_IM_RESIDUI_RICOSTRUITI,
       SUM(TOT_IM_STANZ_INIZIALE_A1  ) TOT_IM_STANZ_INIZIALE_A1,
       SUM(TOT_VARIAZIONI_PIU        ) TOT_VARIAZIONI_PIU,
       SUM(TOT_VARIAZIONI_MENO       ) TOT_VARIAZIONI_MENO,
       SUM(TOT_IM_OBBL_ACC_COMP      ) TOT_IM_OBBL_ACC_COMP,
       SUM(TOT_IM_RESIDUI_RICOSTRUITI) + SUM(TOT_IM_STANZ_INIZIALE_A1) + SUM(TOT_VARIAZIONI_PIU) -
       SUM(TOT_VARIAZIONI_MENO) - SUM(TOT_IM_OBBL_ACC_COMP) DISP_COMP,
       SUM(TOT_IM_STANZ_RES_IMPROPRIO) TOT_IM_STANZ_RES_IMPROPRIO,
       SUM(TOT_VAR_PIU_STANZ_RES_IMP ) TOT_VAR_PIU_STANZ_RES_IMP,
       SUM(TOT_VAR_MENO_STANZ_RES_IMP) TOT_VAR_MENO_STANZ_RES_IMP,
       SUM(TOT_IM_OBBL_RES_IMP       ) TOT_IM_OBBL_RES_IMP,
       SUM(TOT_VAR_PIU_OBBL_RES_IMP  ) TOT_VAR_PIU_OBBL_RES_IMP,
       SUM(TOT_VAR_MENO_OBBL_RES_IMP ) TOT_VAR_MENO_OBBL_RES_IMP,
       Sum(tot_VAR_PIU_OBBL_RES_PRO)   tot_VAR_PIU_OBBL_RES_PRO,
       Sum(tot_VAR_MENO_OBBL_RES_PRO)  tot_VAR_MENO_OBBL_RES_PRO,
       Sum(TOT_IM_STANZ_RES_IMPROPRIO) + Sum(TOT_VAR_PIU_STANZ_RES_IMP) - Sum(TOT_VAR_MENO_STANZ_RES_IMP) -
        (Sum(TOT_IM_OBBL_RES_IMP) + Sum(TOT_VAR_PIU_OBBL_RES_IMP) - Sum(TOT_VAR_MENO_OBBL_RES_IMP)) +
        Sum (tot_VAR_MENO_OBBL_RES_PRO) - Sum (tot_VAR_PIU_OBBL_RES_PRO) DISP_RES_IMP
FROM  V_DISP_RES_IMPROPRIE, ELEMENTO_VOCE ev, VOCE_F
WHERE V_DISP_RES_IMPROPRIE.ESERCIZIO = ev.ESERCIZIO AND
      V_DISP_RES_IMPROPRIE.TI_APPARTENENZA = ev.TI_APPARTENENZA AND
      V_DISP_RES_IMPROPRIE.TI_GESTIONE = ev.TI_GESTIONE AND
      nvl(VOCE_F.cd_elemento_voce,V_DISP_RES_IMPROPRIE.CD_VOCE)= ev.CD_ELEMENTO_VOCE AND
      V_DISP_RES_IMPROPRIE.ESERCIZIO = VOCE_F.ESERCIZIO(+) AND
      V_DISP_RES_IMPROPRIE.TI_APPARTENENZA = VOCE_F.TI_APPARTENENZA(+) AND
      V_DISP_RES_IMPROPRIE.TI_GESTIONE = VOCE_F.TI_GESTIONE(+) AND
      V_DISP_RES_IMPROPRIE.CD_VOCE = VOCE_F.CD_VOCE(+)
GROUP BY V_DISP_RES_IMPROPRIE.ESERCIZIO, V_DISP_RES_IMPROPRIE.ESERCIZIO_RES,
V_DISP_RES_IMPROPRIE.CD_CENTRO_RESPONSABILITA,
CNRUTL001.GETCDSFROMCDR(V_DISP_RES_IMPROPRIE.cd_centro_responsabilita),
       V_DISP_RES_IMPROPRIE.CD_LINEA_ATTIVITA, V_DISP_RES_IMPROPRIE.TI_APPARTENENZA,
    V_DISP_RES_IMPROPRIE.TI_GESTIONE, V_DISP_RES_IMPROPRIE.CD_VOCE,
      nvl(VOCE_F.cd_elemento_voce,V_DISP_RES_IMPROPRIE.CD_VOCE), FL_PARTITA_GIRO;
