--------------------------------------------------------
--  DDL for View V_SOSPESO_REV_ACCERT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_SOSPESO_REV_ACCERT" ("CD_CDS", "ESERCIZIO", "TI_ENTRATA_SPESA", "TI_SOSPESO_RISCONTRO", "CD_SOSPESO", "CD_SOSPESO_PADRE", "IM_SOSPESO", "PG_REVERSALE", "CD_UO_ORIGINE", "IM_ASSOCIATO", "ESERCIZIO_ORI_ACCERTAMENTO", "PG_ACCERTAMENTO", "CD_VOCE", "IM_ACCERTAMENTO", "IM_REVERSALE") AS 
  SELECT
--
-- Date: 19/07/2006
-- Version: 1.3
--
-- Vista di estrazione delle reversali e degli accertamenti associati ai sospesi di
-- entrata CNR
--
-- History:
--
-- Date: 28/11/2002
-- Version: 1.0
-- Creazione
--
-- Date: 25/02/2003
-- Version: 1.1
-- Aggiunto CD_SOSPESO_PADRE
--
-- Date: 28/02/2003
-- Version: 1.2
-- Aggiunto filtro per escludere i dettagli annullati
--
-- Date: 19/07/2006
-- Version: 1.3
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body:
--
A.CD_CDS,
A.ESERCIZIO,
A.TI_ENTRATA_SPESA,
A.TI_SOSPESO_RISCONTRO,
A.CD_SOSPESO,
A.CD_SOSPESO_PADRE,
A.IM_SOSPESO,
C.PG_REVERSALE,
C.CD_UO_ORIGINE,
B.IM_ASSOCIATO,
E.ESERCIZIO_ORIGINALE,
E.PG_ACCERTAMENTO,
E.CD_VOCE,
E.IM_ACCERTAMENTO,
im_reversale
FROM	SOSPESO A,
SOSPESO_DET_ETR B,
REVERSALE C,
REVERSALE_RIGA D,
ACCERTAMENTO E
WHERE
A.CD_CDS = B.CD_CDS AND
A.ESERCIZIO = B.ESERCIZIO AND
A.TI_ENTRATA_SPESA = B.TI_ENTRATA_SPESA AND
A.TI_SOSPESO_RISCONTRO = B.TI_SOSPESO_RISCONTRO AND
A.CD_SOSPESO = B.CD_SOSPESO AND
B.CD_CDS_REVERSALE = C.CD_CDS AND
B.ESERCIZIO = C.ESERCIZIO AND
B.PG_REVERSALE = C.PG_REVERSALE AND
B.STATO <> 'A' AND
C.ESERCIZIO = D.ESERCIZIO AND
C.CD_CDS = D.CD_CDS AND
C.PG_REVERSALE = D.PG_REVERSALE AND
D.CD_CDS = E.CD_CDS AND
D.ESERCIZIO_ACCERTAMENTO = E.ESERCIZIO AND
D.ESERCIZIO_ORI_ACCERTAMENTO = E.ESERCIZIO_ORIGINALE AND
D.PG_ACCERTAMENTO = E.PG_ACCERTAMENTO;
