--------------------------------------------------------
--  DDL for View V_SOSPESO_MAN_IMP
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_SOSPESO_MAN_IMP" ("CD_CDS", "ESERCIZIO", "TI_ENTRATA_SPESA", "TI_SOSPESO_RISCONTRO", "CD_SOSPESO", "CD_SOSPESO_PADRE", "IM_SOSPESO", "PG_MANDATO", "CD_UO_ORIGINE", "IM_ASSOCIATO", "ESERCIZIO_ORI_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "CD_VOCE", "IM_OBBLIGAZIONE", "IM_MANDATO") AS 
  SELECT
A.CD_CDS,
A.ESERCIZIO,
A.TI_ENTRATA_SPESA,
A.TI_SOSPESO_RISCONTRO,
A.CD_SOSPESO,
A.CD_SOSPESO_PADRE,
A.IM_SOSPESO,
C.PG_MANDATO,
C.CD_UO_ORIGINE,
B.IM_ASSOCIATO,
E.ESERCIZIO_ORIGINALE,
E.PG_OBBLIGAZIONE,
E.CD_ELEMENTO_VOCE,
E.IM_OBBLIGAZIONE,
im_mandato
FROM	SOSPESO A,
SOSPESO_DET_USC B,
MANDATO C,
MANDATO_RIGA D,
OBBLIGAZIONE E
WHERE
A.CD_CDS = B.CD_CDS AND
A.ESERCIZIO = B.ESERCIZIO AND
A.TI_ENTRATA_SPESA = B.TI_ENTRATA_SPESA AND
A.TI_SOSPESO_RISCONTRO = B.TI_SOSPESO_RISCONTRO AND
A.CD_SOSPESO = B.CD_SOSPESO AND
B.CD_CDS_MANDATO = C.CD_CDS AND
B.ESERCIZIO = C.ESERCIZIO AND
B.PG_MANDATO = C.PG_MANDATO AND
B.STATO <> 'A' AND
C.ESERCIZIO = D.ESERCIZIO AND
C.CD_CDS = D.CD_CDS AND
C.PG_MANDATO = D.PG_MANDATO AND
D.CD_CDS = E.CD_CDS AND
D.ESERCIZIO_OBBLIGAZIONE = E.ESERCIZIO AND
D.ESERCIZIO_ORI_OBBLIGAZIONE = E.ESERCIZIO_ORIGINALE AND
D.PG_OBBLIGAZIONE = E.PG_OBBLIGAZIONE;
