--------------------------------------------------------
--  DDL for View V_VAR_STANZ_RES_VOCE_CNR
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_VAR_STANZ_RES_VOCE_CNR" ("ESERCIZIO", "PG_VARIAZIONE", "PG_RIGA", "ESERCIZIO_VOCE", "ESERCIZIO_RES", "CD_CDR", "CD_CDS", "CD_LINEA_ATTIVITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_VOCE_CDS", "CD_VOCE_CNR", "TITOLO_CNR", "IM_VARIAZIONE") AS 
  Select
VAR_STANZ_RES_RIGA.ESERCIZIO,
VAR_STANZ_RES_RIGA.PG_VARIAZIONE,
VAR_STANZ_RES_RIGA.PG_RIGA,
VAR_STANZ_RES_RIGA.ESERCIZIO_VOCE,
VAR_STANZ_RES_RIGA.ESERCIZIO_RES,
VAR_STANZ_RES_RIGA.CD_CDR,
CNRUTL001.GETCDSFROMCDR(CD_CDR) CD_CDS,
VAR_STANZ_RES_RIGA.CD_LINEA_ATTIVITA,
VAR_STANZ_RES_RIGA.TI_APPARTENENZA,
VAR_STANZ_RES_RIGA.TI_GESTIONE,
VAR_STANZ_RES_RIGA.CD_VOCE CD_VOCE_CDS,
CNRCTB075.getvocecnrfromvocecds (VAR_STANZ_RES_RIGA.ESERCIZIO_RES,
                                 VAR_STANZ_RES_RIGA.CD_CDR,
                                 VAR_STANZ_RES_RIGA.CD_LINEA_ATTIVITA,
                                 VAR_STANZ_RES_RIGA.ESERCIZIO_VOCE,
                                 VAR_STANZ_RES_RIGA.TI_GESTIONE,
                                 VAR_STANZ_RES_RIGA.TI_APPARTENENZA,
                                 VAR_STANZ_RES_RIGA.CD_ELEMENTO_VOCE) CD_VOCE_CNR,
SUBSTR(CNRCTB075.getvocecnrfromvocecds (VAR_STANZ_RES_RIGA.ESERCIZIO_RES,
                                 VAR_STANZ_RES_RIGA.CD_CDR,
                                 VAR_STANZ_RES_RIGA.CD_LINEA_ATTIVITA,
                                 VAR_STANZ_RES_RIGA.ESERCIZIO_VOCE,
                                 VAR_STANZ_RES_RIGA.TI_GESTIONE,
                                 VAR_STANZ_RES_RIGA.TI_APPARTENENZA,
                                 VAR_STANZ_RES_RIGA.CD_ELEMENTO_VOCE), 3, 2) TITOLO_CNR,
IM_VARIAZIONE
FROM  VAR_STANZ_RES_RIGA
;
