--------------------------------------------------------
--  DDL for View V_VOCE_F_PARTITA_GIRO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_VOCE_F_PARTITA_GIRO" ("ESERCIZIO", "TI_APPARTENENZA", "TI_GESTIONE", "CD_VOCE", "CD_UNITA_ORGANIZZATIVA", "TI_VOCE", "CD_PROPRIO_VOCE", "DS_VOCE", "CD_PARTE", "CD_CATEGORIA", "CD_NATURA", "CD_FUNZIONE", "FL_MASTRINO", "LIVELLO", "CD_TITOLO_CAPITOLO", "CD_SEZIONE_CAPITOLO", "CD_CDS", "CD_CENTRO_RESPONSABILITA", "CD_ELEMENTO_VOCE", "DUVA", "UTUV", "DACR", "UTCR", "PG_VER_REC", "CD_VOCE_PADRE", "FL_PARTITA_GIRO", "FL_VOCE_SAC", "DS_TITOLO_CAPITOLO", "FL_SOLO_COMPETENZA", "FL_SOLO_RESIDUO", "FL_AZZERA_RESIDUI", "ESERCIZIO_ELEMENTO_PADRE", "TI_APPARTENENZA_ELEMENTO_PADRE", "TI_GESTIONE_ELEMENTO_PADRE") AS 
  SELECT
--
-- Date: 09/09/2002
-- Version: 1.2
--
--
-- History:
-- Date: 21/12/2001
-- Version: 1.0
-- Creazione
--
-- Date: 11/06/2002
-- Version: 1.1
-- Aggiunto flag FL_VOCE_SAC
--
-- Date: 09/09/2002
-- Version: 1.2
-- Aggiunto DS_TITOLO_CAPITOLO
--
-- Date: 09/09/2015
-- Version: 1.3
-- Aggiunta nuova gestione che prevede il non popolamento di VOCE_F
--
-- Date: 06/10/2015
-- Version: 1.8
-- Aggiunta nuova gestione pdg e campi ELEMENTO_VOCE_PADRE
--
-- Body:
-- Aggiunge alla VOCE_F il flag su partita di giro (FL_PARTITA_GIRO, FL_VOCE_SAC, DS_TITOLO_CAPITOLO)
--
  A.ESERCIZIO,
  A.TI_APPARTENENZA,
  A.TI_GESTIONE,
  A.CD_VOCE,
  A.CD_UNITA_ORGANIZZATIVA,
  A.TI_VOCE,
  A.CD_PROPRIO_VOCE,
  A.DS_VOCE,
  A.CD_PARTE,
  A.CD_CATEGORIA,
  A.CD_NATURA,
  A.CD_FUNZIONE,
  A.FL_MASTRINO,
  A.LIVELLO,
  A.CD_TITOLO_CAPITOLO,
  A.CD_SEZIONE_CAPITOLO,
  A.CD_CDS,
  A.CD_CENTRO_RESPONSABILITA,
  A.CD_ELEMENTO_VOCE,
  A.DUVA,
  A.UTUV,
  A.DACR,
  A.UTCR,
  A.PG_VER_REC,
  A.CD_VOCE_PADRE,
  B.FL_PARTITA_GIRO,
  B.FL_VOCE_SAC,
  B.DS_ELEMENTO_VOCE,
  B.FL_SOLO_COMPETENZA,
  B.FL_SOLO_RESIDUO,
  B.FL_AZZERA_RESIDUI,
  B.ESERCIZIO_ELEMENTO_PADRE,
  B.TI_APPARTENENZA_ELEMENTO_PADRE,
  B.TI_GESTIONE_ELEMENTO_PADRE
FROM
  VOCE_F A,
  ELEMENTO_VOCE B,
  PARAMETRI_CNR C
 WHERE
  C.ESERCIZIO = A.ESERCIZIO AND
  C.FL_NUOVO_PDG = 'N' AND
  A.ESERCIZIO = B.ESERCIZIO AND
  A.TI_APPARTENENZA = B.TI_APPARTENENZA AND
  A.TI_GESTIONE = B.TI_GESTIONE AND
  A.CD_TITOLO_CAPITOLO = B.CD_ELEMENTO_VOCE
UNION ALL
SELECT
  B.ESERCIZIO,
  B.TI_APPARTENENZA,
  B.TI_GESTIONE,
  B.CD_ELEMENTO_VOCE,
  NULL,
  B.TI_ELEMENTO_VOCE,
  B.CD_PROPRIO_ELEMENTO,
  B.DS_ELEMENTO_VOCE,
  NULL,
  NULL,
  NULL,
  NULL,
  'Y',
  NULL,
  B.CD_ELEMENTO_VOCE,
  NULL,
  NULL,
  NULL,
  B.CD_ELEMENTO_VOCE,
  B.DUVA,
  B.UTUV,
  B.DACR,
  B.UTCR,
  B.PG_VER_REC,
  NULL,
  B.FL_PARTITA_GIRO,
  B.FL_VOCE_SAC,
  B.DS_ELEMENTO_VOCE,
  B.FL_SOLO_COMPETENZA,
  B.FL_SOLO_RESIDUO,
  B.FL_AZZERA_RESIDUI,
  B.ESERCIZIO_ELEMENTO_PADRE,
  B.TI_APPARTENENZA_ELEMENTO_PADRE,
  B.TI_GESTIONE_ELEMENTO_PADRE
FROM
  ELEMENTO_VOCE B,
  PARAMETRI_CNR C
 WHERE
  C.ESERCIZIO = B.ESERCIZIO AND
  C.FL_NUOVO_PDG = 'Y';

   COMMENT ON TABLE "V_VOCE_F_PARTITA_GIRO"  IS 'Estrae tutte le righe di VOCE_F ed aggiunge il fl_partita_giro dalla tabella ELEMENTO_VOCE.';
