--------------------------------------------------------
--  DDL for View V_VOCE_F_SALDI_CDR_LINEA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_VOCE_F_SALDI_CDR_LINEA" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "CD_LINEA_ATTIVITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_VOCE", "IM_OBBL_ACC_COMP", "IM_MANDATI_REVERSALI_PRO", "IM_PAGAMENTI_INCASSI", "STANZIAMENTI", "VARIAZIONI_PIU", "VARIAZIONI_MENO") AS 
  SELECT
--
-- Date: 19/07/2006
-- Version: 1.1
--
-- Vista per controllo incrociato di coerenza dei saldi dei documenti contabili
--
-- History:
--
-- Date: 30/03/2005
-- Version: 1.0
-- Creazione
--
-- Date: 19/07/2006
-- Version: 1.1
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body:
--
     ESERCIZIO
    ,CD_CENTRO_RESPONSABILITA
    ,CD_LINEA_ATTIVITA
    ,TI_APPARTENENZA
    ,TI_GESTIONE
    ,CD_VOCE
    ,SUM(IM_OBBLIG_IMP_ACR)
    ,SUM(IM_MANDATI_REVERSALI)
    ,SUM(IM_PAGAMENTI_INCASSI)
    ,SUM(STANZIAMENTI)
    ,SUM(VARIAZIONI_PIU)
    ,SUM(VARIAZIONI_MENO)
FROM (
     SELECT
       b.ESERCIZIO
      ,b.CD_CENTRO_RESPONSABILITA
      ,b.CD_LINEA_ATTIVITA
      ,b.TI_APPARTENENZA
      ,b.TI_GESTIONE
      ,b.CD_VOCE
      ,b.IM_VOCE IM_OBBLIG_IMP_ACR
      ,0 IM_MANDATI_REVERSALI
      ,0 IM_PAGAMENTI_INCASSI
      ,0 STANZIAMENTI
      ,0 VARIAZIONI_PIU
      ,0 VARIAZIONI_MENO
     FROM OBBLIGAZIONE a, OBBLIGAZIONE_SCAD_VOCE b
     WHERE b.pg_obbligazione > 0
       AND a.cd_cds = b.cd_cds
       AND a.ESERCIZIO = b.ESERCIZIO
       AND a.ESERCIZIO_ORIGINALE = b.ESERCIZIO_ORIGINALE
       AND a.pg_obbligazione = b.pg_obbligazione
       AND a.ESERCIZIO = a.esercizio_competenza
       AND a.stato_obbligazione <>'S' -- Stornato
 UNION ALL
     SELECT
       a.ESERCIZIO
      ,b.CD_CENTRO_RESPONSABILITA
      ,b.CD_LINEA_ATTIVITA
      ,a.TI_APPARTENENZA
      ,a.TI_GESTIONE
      ,a.CD_VOCE
      ,b.IM_VOCE IM_OBBLIG_IMP_ACR
      ,0 IM_MANDATI_REVERSALI
      ,0 IM_PAGAMENTI_INCASSI
      ,0 STANZIAMENTI
      ,0 VARIAZIONI_PIU
      ,0 VARIAZIONI_MENO
     FROM ACCERTAMENTO a , ACCERTAMENTO_SCAD_VOCE b
     WHERE a.pg_accertamento > 0
       AND a.cd_cds = b.cd_cds
       AND a.ESERCIZIO = b.ESERCIZIO
       AND a.ESERCIZIO_ORIGINALE = b.ESERCIZIO_ORIGINALE
       AND a.pg_accertamento = b.pg_accertamento
       AND a.dt_cancellazione IS NULL
 UNION ALL
     SELECT
       a.ESERCIZIO
      ,a.CD_CENTRO_RESPONSABILITA
      ,a.CD_LINEA_ATTIVITA
      ,a.TI_APPARTENENZA
      ,a.TI_GESTIONE
      ,a.CD_VOCE
      ,0 OBBLIG_IMP_ACR
      ,a.IM_CAPITOLO_PESATO IM_MANDATI_REVERSALI
      ,DECODE(b.stato,'P',a.IM_CAPITOLO_PESATO,0) IM_PAGAMENTI_INCASSI
      ,0 STANZIAMENTI
      ,0 VARIAZIONI_PIU
      ,0 VARIAZIONI_MENO
     FROM MANDATO b, v_man_rev_voce_cdr_linea a
     WHERE b.pg_mandato > 0
       AND b.cd_cds=a.cd_cds
       AND b.ESERCIZIO=a.ESERCIZIO
       AND b.pg_mandato=a.pg_documento
       AND a.ti_documento='M'
       AND b.stato <> 'A'
 UNION ALL
     SELECT
       a.ESERCIZIO
      ,a.CD_CENTRO_RESPONSABILITA
      ,a.CD_LINEA_ATTIVITA
      ,a.TI_APPARTENENZA
      ,a.TI_GESTIONE
      ,a.CD_VOCE
      ,0 OBBLIG_IMP_ACR
      ,a.IM_CAPITOLO_PESATO IM_MANDATI_REVERSALI
      ,DECODE(b.stato,'P',a.IM_CAPITOLO_PESATO,0) IM_PAGAMENTI_INCASSI
      ,0 STANZIAMENTI
      ,0 VARIAZIONI_PIU
      ,0 VARIAZIONI_MENO
     FROM REVERSALE b, v_man_rev_voce_cdr_linea a
     WHERE b.pg_reversale > 0
       AND b.cd_cds=a.cd_cds
       AND b.ESERCIZIO=a.ESERCIZIO
       AND b.pg_reversale=a.pg_documento
       AND a.ti_documento='R'
       AND b.stato <> 'A'
 UNION ALL
   SELECT ESERCIZIO, CD_CENTRO_RESPONSABILITA, CD_LINEA_ATTIVITA, TI_APPARTENENZA, TI_GESTIONE,
           CD_VOCE, 0 OBBLIG_IMP_ACR, 0 IM_MANDATI_REVERSALI, 0 IM_PAGAMENTI_INCASSI,
           SUM(TOTALE) STANZIAMENTI,SUM(VARIAZIONI_PIU), SUM(VARIAZIONI_MENO)
   FROM(
   SELECT a.ESERCIZIO, a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA, a.TI_APPARTENENZA, a.TI_GESTIONE,
           CNRCTB053.getVoce_FdaEV (a.ESERCIZIO, a.TI_APPARTENENZA,a.TI_GESTIONE, a.CD_ELEMENTO_VOCE,a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA) CD_VOCE,
           Nvl(a.IM_RI_CCS_SPESE_ODC,0) + NVL(a.IM_RK_CCS_SPESE_OGC,0) +
                          NVL(a.IM_RQ_SSC_COSTI_ODC,0) + NVL(a.IM_RS_SSC_COSTI_OGC,0) +
                          Nvl(a.IM_RU_SPESE_COSTI_ALTRUI,0) TOTALE,
                      0 VARIAZIONI_PIU, 0 VARIAZIONI_MENO
    FROM PDG_PREVENTIVO_SPE_DET a
    WHERE a.ESERCIZIO_PDG_VARIAZIONE IS Null
      And a.STATO = 'Y'
  Union ALL
    SELECT a.ESERCIZIO, a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA, a.TI_APPARTENENZA, a.TI_GESTIONE,
           CNRCTB053.getVoce_FdaEV (a.ESERCIZIO, a.TI_APPARTENENZA,a.TI_GESTIONE, a.CD_ELEMENTO_VOCE,a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA)  CD_VOCE,
           0 TOTALE,Nvl(a.IM_RI_CCS_SPESE_ODC,0) + NVL(a.IM_RK_CCS_SPESE_OGC,0) +
                          NVL(a.IM_RQ_SSC_COSTI_ODC,0) + NVL(a.IM_RS_SSC_COSTI_OGC,0) +
                          Nvl(a.IM_RU_SPESE_COSTI_ALTRUI,0) VARIAZIONI_PIU,
                      0 VARIAZIONI_MENO
    FROM PDG_PREVENTIVO_SPE_DET a, PDG_VARIAZIONE e
    WHERE a.ESERCIZIO_PDG_VARIAZIONE  = e.ESERCIZIO
      AND a.PG_VARIAZIONE_PDG  = e.PG_VARIAZIONE_PDG
      AND e.STATO ='APP'
      And a.STATO = 'Y'
      And Nvl(a.IM_RI_CCS_SPESE_ODC,0) + NVL(a.IM_RK_CCS_SPESE_OGC,0) +
               Nvl(a.IM_RQ_SSC_COSTI_ODC,0) + NVL(a.IM_RS_SSC_COSTI_OGC,0) +
               Nvl(a.IM_RU_SPESE_COSTI_ALTRUI,0) > 0
  UNION ALL
    SELECT a.ESERCIZIO, a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA, a.TI_APPARTENENZA, a.TI_GESTIONE,
           CNRCTB053.getVoce_FdaEV (a.ESERCIZIO, a.TI_APPARTENENZA,a.TI_GESTIONE, a.CD_ELEMENTO_VOCE,a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA)  CD_VOCE,
           0 TOTALE, 0 VARIAZIONI_PIU, (Nvl(a.IM_RI_CCS_SPESE_ODC,0) + NVL(a.IM_RK_CCS_SPESE_OGC,0) +
                          NVL(a.IM_RQ_SSC_COSTI_ODC,0) + NVL(a.IM_RS_SSC_COSTI_OGC,0) +
                          Nvl(a.IM_RU_SPESE_COSTI_ALTRUI,0))* (-1) VARIAZIONI_MENO
    FROM PDG_PREVENTIVO_SPE_DET a, PDG_VARIAZIONE e
    WHERE a.ESERCIZIO_PDG_VARIAZIONE  = e.ESERCIZIO
      AND a.PG_VARIAZIONE_PDG  = e.PG_VARIAZIONE_PDG
      AND e.STATO ='APP'
      And a.STATO = 'Y'
      And Nvl(a.IM_RI_CCS_SPESE_ODC,0) + NVL(a.IM_RK_CCS_SPESE_OGC,0) +
               Nvl(a.IM_RQ_SSC_COSTI_ODC,0) + NVL(a.IM_RS_SSC_COSTI_OGC,0) +
               Nvl(a.IM_RU_SPESE_COSTI_ALTRUI,0) < 0
  UNION ALL
    SELECT a.ESERCIZIO, a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA, a.TI_APPARTENENZA, a.TI_GESTIONE,
           CNRCTB053.getVoce_FdaEV (a.ESERCIZIO, a.TI_APPARTENENZA,a.TI_GESTIONE, a.CD_ELEMENTO_VOCE,a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA)  CD_VOCE,
           Nvl(a.IM_RA_RCE,0) + NVL(a.IM_RC_ESR ,0) TOTALE, 0 VARIAZIONI_PIU, 0 VARIAZIONI_MENO
    FROM PDG_PREVENTIVO_ETR_DET a
    WHERE a.ESERCIZIO_PDG_VARIAZIONE IS Null
      And a.STATO = 'Y'
  UNION ALL
    SELECT a.ESERCIZIO, a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA, a.TI_APPARTENENZA, a.TI_GESTIONE,
           CNRCTB053.getVoce_FdaEV (a.ESERCIZIO, a.TI_APPARTENENZA,a.TI_GESTIONE, a.CD_ELEMENTO_VOCE,a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA)  CD_VOCE,
           0 TOTALE, Nvl(a.IM_RA_RCE,0) + NVL(a.IM_RC_ESR ,0) VARIAZIONI_PIU, 0 VARIAZIONI_MENO
    FROM PDG_PREVENTIVO_ETR_DET a, PDG_VARIAZIONE e
    WHERE a.ESERCIZIO_PDG_VARIAZIONE  = e.ESERCIZIO
      AND a.PG_VARIAZIONE_PDG  = e.PG_VARIAZIONE_PDG
      AND e.STATO ='APP'
      And a.STATO = 'Y'
      And Nvl(a.IM_RA_RCE,0) + NVL(a.IM_RC_ESR ,0) > 0
  UNION ALL
    SELECT a.ESERCIZIO, a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA, a.TI_APPARTENENZA, a.TI_GESTIONE,
           CNRCTB053.getVoce_FdaEV (a.ESERCIZIO, a.TI_APPARTENENZA,a.TI_GESTIONE, a.CD_ELEMENTO_VOCE,a.CD_CENTRO_RESPONSABILITA, a.CD_LINEA_ATTIVITA)  CD_VOCE,
           0 TOTALE, 0 VARIAZIONI_PIU, (Nvl(a.IM_RA_RCE,0) + NVL(a.IM_RC_ESR ,0))*(-1) VARIAZIONI_MENO
    FROM PDG_PREVENTIVO_ETR_DET a, PDG_VARIAZIONE e
    WHERE a.ESERCIZIO_PDG_VARIAZIONE  = e.ESERCIZIO
      AND a.PG_VARIAZIONE_PDG  = e.PG_VARIAZIONE_PDG
      AND e.STATO ='APP'
      And a.STATO = 'Y'
      And Nvl(a.IM_RA_RCE,0) + NVL(a.IM_RC_ESR ,0) < 0)
Group BY
     ESERCIZIO
    ,CD_CENTRO_RESPONSABILITA
    ,CD_LINEA_ATTIVITA
    ,TI_APPARTENENZA
    ,TI_GESTIONE
    ,CD_VOCE
) GROUP BY
     ESERCIZIO
    ,CD_CENTRO_RESPONSABILITA
    ,CD_LINEA_ATTIVITA
    ,TI_APPARTENENZA
    ,TI_GESTIONE
    ,CD_VOCE;
