--------------------------------------------------------
--  DDL for View V_VOCE_F_SALDI_CDS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_VOCE_F_SALDI_CDS" ("ESERCIZIO", "CD_CDS", "TI_APPARTENENZA", "TI_GESTIONE", "CD_VOCE", "IM_STANZ_INIZIALE_A1", "IM_STANZ_INIZIALE_A2", "IM_STANZ_INIZIALE_A3", "VARIAZIONI_PIU", "VARIAZIONI_MENO", "IM_OBBLIG_IMP_ACR", "IM_MANDATI_REVERSALI", "IM_PAGAMENTI_INCASSI", "TI_COMPETENZA_RESIDUO") AS 
  SELECT
--
-- Date: 06/10/2005
-- Version: 1.0
--
-- View che raggruppa i saldi per CDS
--
ESERCIZIO,
CNRUTL001.getCdsFromCdr(cd_centro_responsabilita),
TI_APPARTENENZA,
TI_GESTIONE,
CD_VOCE,
SUM(IM_STANZ_INIZIALE_A1),
SUM(IM_STANZ_INIZIALE_A2),
SUM(IM_STANZ_INIZIALE_A3),
SUM(VARIAZIONI_PIU),
SUM(VARIAZIONI_MENO),
SUM(IM_OBBL_ACC_COMP),
SUM(IM_MANDATI_REVERSALI_PRO),
SUM(IM_PAGAMENTI_INCASSI),
Decode(ESERCIZIO,ESERCIZIO_RES,'C','R')
From VOCE_F_SALDI_CDR_LINEA
Group By ESERCIZIO,
       CNRUTL001.getCdsFromCdr(cd_centro_responsabilita),
       TI_APPARTENENZA,
       TI_GESTIONE,
       CD_VOCE,
       Decode(ESERCIZIO,ESERCIZIO_RES,'C','R')
;

   COMMENT ON TABLE "V_VOCE_F_SALDI_CDS"  IS 'View che raggruppa i saldi per CDS';
