--------------------------------------------------------
--  DDL for View VOCE_F_SALDI_CDR_LINEA
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VOCE_F_SALDI_CDR_LINEA" ("ESERCIZIO", "ESERCIZIO_RES", "CD_CENTRO_RESPONSABILITA", "CD_LINEA_ATTIVITA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "CD_VOCE", "IM_STANZ_INIZIALE_A1", "IM_STANZ_INIZIALE_A2", "IM_STANZ_INIZIALE_A3", "VARIAZIONI_PIU", "VARIAZIONI_MENO", "IM_STANZ_INIZIALE_CASSA", "VARIAZIONI_PIU_CASSA", "VARIAZIONI_MENO_CASSA", "IM_OBBL_ACC_COMP", "IM_STANZ_RES_IMPROPRIO", "VAR_PIU_STANZ_RES_IMP", "VAR_MENO_STANZ_RES_IMP", "IM_OBBL_RES_IMP", "VAR_PIU_OBBL_RES_IMP", "VAR_MENO_OBBL_RES_IMP", "IM_OBBL_RES_PRO", "VAR_PIU_OBBL_RES_PRO", "VAR_MENO_OBBL_RES_PRO", "IM_MANDATI_REVERSALI_PRO", "IM_MANDATI_REVERSALI_IMP", "IM_PAGAMENTI_INCASSI", "DACR", "UTCR", "DUVA", "UTUV", "PG_VER_REC") AS 
  Select A.ESERCIZIO, A.ESERCIZIO_RES, A.CD_CENTRO_RESPONSABILITA, A.CD_LINEA_ATTIVITA, A.TI_APPARTENENZA, A.TI_GESTIONE, A.CD_ELEMENTO_VOCE, A.CD_VOCE,
       IM_STANZ_INIZIALE_A1, IM_STANZ_INIZIALE_A2, IM_STANZ_INIZIALE_A3, VARIAZIONI_PIU, VARIAZIONI_MENO, IM_STANZ_INIZIALE_CASSA,
       VARIAZIONI_PIU_CASSA, VARIAZIONI_MENO_CASSA, IM_OBBL_ACC_COMP, IM_STANZ_RES_IMPROPRIO, VAR_PIU_STANZ_RES_IMP,
       VAR_MENO_STANZ_RES_IMP, IM_OBBL_RES_IMP, VAR_PIU_OBBL_RES_IMP, VAR_MENO_OBBL_RES_IMP,
       IM_OBBL_RES_PRO, VAR_PIU_OBBL_RES_PRO, VAR_MENO_OBBL_RES_PRO, IM_MANDATI_REVERSALI_PRO,
       IM_MANDATI_REVERSALI_IMP, IM_PAGAMENTI_INCASSI,
       A.DACR, A.UTCR, A.DUVA, A.UTUV, A.PG_VER_REC
From SALDI_STANZIAMENTI A,SALDI_IMP_ACC B,SALDI_PAG_INC C
Where A.ESERCIZIO = B.ESERCIZIO
  And A.ESERCIZIO_RES = B.ESERCIZIO_RES
  And A.CD_CENTRO_RESPONSABILITA = B.CD_CENTRO_RESPONSABILITA
  And A.CD_LINEA_ATTIVITA = B.CD_LINEA_ATTIVITA
  And A.TI_APPARTENENZA = B.TI_APPARTENENZA
  And A.TI_GESTIONE = B.TI_GESTIONE
  And A.CD_VOCE = B.CD_VOCE
  And B.ESERCIZIO = C.ESERCIZIO
  And B.ESERCIZIO_RES = C.ESERCIZIO_RES
  And B.CD_CENTRO_RESPONSABILITA = C.CD_CENTRO_RESPONSABILITA
  And B.CD_LINEA_ATTIVITA = C.CD_LINEA_ATTIVITA
  And B.TI_APPARTENENZA = C.TI_APPARTENENZA
  And B.TI_GESTIONE = C.TI_GESTIONE
  And B.CD_VOCE = C.CD_VOCE;
