--------------------------------------------------------
--  DDL for View VOCE_F_SALDI_CDR_LINEA_RICLASS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VOCE_F_SALDI_CDR_LINEA_RICLASS" ("ESERCIZIO", "ESERCIZIO_RES", "CD_DIPARTIMENTO", "PG_PROGETTO", "CD_PROGETTO", "DS_PROGETTO", "PG_COMMESSA", "CD_COMMESSA", "DS_COMMESSA", "PG_MODULO", "CD_MODULO", "DS_MODULO", "CD_CDS", "CD_CENTRO_RESPONSABILITA", "CD_LINEA_ATTIVITA", "CD_NATURA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "CD_VOCE", "CD_LIVELLO1", "CD_LIVELLO2", "CD_LIVELLO3", "CD_LIVELLO4", "CD_LIVELLO5", "CD_LIVELLO6", "CD_LIVELLO7", "IM_STANZ_INIZIALE_A1", "VARIAZIONI_PIU", "VARIAZIONI_MENO", "IM_STANZ_INIZIALE_CASSA", "VARIAZIONI_PIU_CASSA", "VARIAZIONI_MENO_CASSA", "IM_OBBL_ACC_COMP", "IM_STANZ_RES_IMPROPRIO", "VAR_PIU_STANZ_RES_IMP", "VAR_MENO_STANZ_RES_IMP", "IM_OBBL_RES_IMP", "IM_OBBL_RES_PRO", "VAR_PIU_OBBL_RES_PRO", "VAR_MENO_OBBL_RES_PRO", "IM_MANDATI_REVERSALI_PRO", "IM_MANDATI_REVERSALI_IMP", "IM_PAGAMENTI_INCASSI") AS 
  SELECT SALDI.ESERCIZIO,
       SALDI.ESERCIZIO_RES,
       PROGETTO.CD_DIPARTIMENTO,
       PROGETTO.PG_PROGETTO,
       PROGETTO.CD_PROGETTO,
       PROGETTO.DS_PROGETTO,
       COM.PG_PROGETTO,
       COM.CD_PROGETTO,
       COM.DS_PROGETTO,
       MODU.PG_PROGETTO,
       MODU.CD_PROGETTO,
       MODU.DS_PROGETTO,
       Cnrutl001.GETCDSFROMCDR(SALDI.cd_centro_responsabilita),
       SALDI.CD_CENTRO_RESPONSABILITA,
       SALDI.CD_LINEA_ATTIVITA,
       LINEA_ATTIVITA.CD_NATURA,
       SALDI.TI_APPARTENENZA,
       SALDI.TI_GESTIONE,
       SALDI.CD_ELEMENTO_VOCE,
       ELEMENTO_VOCE.DS_ELEMENTO_VOCE,
       SALDI.CD_VOCE,
       CLASS.CD_LIVELLO1,
       CLASS.CD_LIVELLO2,
       CLASS.CD_LIVELLO3,
       CLASS.CD_LIVELLO4,
       CLASS.CD_LIVELLO5,
       CLASS.CD_LIVELLO6,
       CLASS.CD_LIVELLO7,
       SALDI.IM_STANZ_INIZIALE_A1,
       SALDI.VARIAZIONI_PIU,
       SALDI.VARIAZIONI_MENO,
       SALDI.IM_STANZ_INIZIALE_CASSA,
       SALDI.VARIAZIONI_PIU_CASSA,
       SALDI.VARIAZIONI_MENO_CASSA,
       SALDI.IM_OBBL_ACC_COMP,
       SALDI.IM_STANZ_RES_IMPROPRIO,
       SALDI.VAR_PIU_STANZ_RES_IMP,
       SALDI.VAR_MENO_STANZ_RES_IMP,
       SALDI.IM_OBBL_RES_IMP,
       SALDI.IM_OBBL_RES_PRO,
       SALDI.VAR_PIU_OBBL_RES_PRO,
       SALDI.VAR_MENO_OBBL_RES_PRO,
       SALDI.IM_MANDATI_REVERSALI_PRO,
       SALDI.IM_MANDATI_REVERSALI_IMP,
       SALDI.IM_PAGAMENTI_INCASSI
FROM   VOCE_F_SALDI_CDR_LINEA SALDI,
       ELEMENTO_VOCE,
       V_CLASSIFICAZIONE_VOCI CLASS,
       LINEA_ATTIVITA,
       PROGETTO_GEST PROGETTO,
       PROGETTO_GEST COM,
       PROGETTO_GEST MODU
WHERE  CLASS.ID_CLASSIFICAZIONE       = ELEMENTO_VOCE.ID_CLASSIFICAZIONE         AND
       ELEMENTO_VOCE.ESERCIZIO        = SALDI.ESERCIZIO                          AND
       ELEMENTO_VOCE.TI_APPARTENENZA  = SALDI.TI_APPARTENENZA                    AND
       ELEMENTO_VOCE.TI_GESTIONE      = SALDI.TI_GESTIONE                        AND
       ELEMENTO_VOCE.CD_ELEMENTO_VOCE = SALDI.CD_ELEMENTO_VOCE                   AND
       SALDI.CD_CENTRO_RESPONSABILITA = LINEA_ATTIVITA.CD_CENTRO_RESPONSABILITA  AND
       SALDI.CD_LINEA_ATTIVITA        = LINEA_ATTIVITA.CD_LINEA_ATTIVITA         AND
       LINEA_ATTIVITA.PG_PROGETTO     IS NOT NULL                                AND
       LINEA_ATTIVITA.PG_PROGETTO     = MODU.PG_PROGETTO                         AND
       MODU.PG_PROGETTO_PADRE         = COM.PG_PROGETTO                          AND
       MODU.ESERCIZIO_PROGETTO_PADRE  = COM.ESERCIZIO                            AND
       COM.PG_PROGETTO_PADRE          = PROGETTO.PG_PROGETTO                     AND
       COM.ESERCIZIO_PROGETTO_PADRE   = PROGETTO.ESERCIZIO                       AND
       MODU.ESERCIZIO                  = SALDI.ESERCIZIO_RES;
