--------------------------------------------------------
--  DDL for View VP_DBIL_FIN_CNR_DZ
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VP_DBIL_FIN_CNR_DZ" ("ESERCIZIO", "TI_APPARTENENZA", "TI_GESTIONE", "CD_PARTE", "CDC_TITOLO", "CDC_CATEGORIA", "CDC_SEZIONE", "CDC_CAPITOLO", "CDC_ARTICOLO", "CD_VOCE", "DS_CAPITOLO", "CD_UNITA_ORGANIZZATIVA", "TI_VOCE", "DS_VOCE", "DS_PARTE", "CD_TITOLO", "DS_TITOLO", "CD_CATEGORIA", "DS_CATEGORIA", "CD_FUNZIONE", "DS_FUNZIONE", "CD_CDS", "DS_CDS", "CD_NATURA", "DS_NATURA", "CD_PROPRIO_VOCE", "FL_MASTRINO", "LIVELLO", "CD_TITOLO_CAPITOLO", "DS_TITOLO_CAPITOLO", "CD_SEZIONE_CAPITOLO", "CD_CENTRO_RESPONSABILITA", "IM_STANZ_ES_PREC_ASS", "IM_RES_INIZIALE", "IM_RES_VAR_PIU", "IM_RES_VAR_MENO", "IM_STANZ_INIZIALE_A1", "IM_STANZ_VAR_PIU", "IM_STANZ_VAR_MENO", "IM_STANZ_INIZIALE_A2", "IM_STANZ_INIZIALE_A3") AS 
  (select
--
-- Date: 19/12/2002
-- Version: 1.0
--
-- Vista di stampa del bilancio finanziario CNR solo importi significativi per la stampa <> 0
--
-- History:
--
-- Date: 19/12/2002
-- Version: 1.0
-- Creazione
--
-- Body:
--
 ESERCIZIO,
TI_APPARTENENZA, TI_GESTIONE, CD_PARTE, CDC_TITOLO,
CDC_CATEGORIA, CDC_SEZIONE, CDC_CAPITOLO, CDC_ARTICOLO,
CD_VOCE, DS_CAPITOLO, CD_UNITA_ORGANIZZATIVA, TI_VOCE,
DS_VOCE, DS_PARTE, CD_TITOLO, DS_TITOLO,
CD_CATEGORIA, DS_CATEGORIA, CD_FUNZIONE, DS_FUNZIONE,
CD_CDS, DS_CDS, CD_NATURA, DS_NATURA,
CD_PROPRIO_VOCE, FL_MASTRINO, LIVELLO, CD_TITOLO_CAPITOLO,
DS_TITOLO_CAPITOLO, CD_SEZIONE_CAPITOLO, CD_CENTRO_RESPONSABILITA, IM_STANZ_ES_PREC_ASS,
IM_RES_INIZIALE, IM_RES_VAR_PIU, IM_RES_VAR_MENO, IM_STANZ_INIZIALE_A1,
IM_STANZ_VAR_PIU, IM_STANZ_VAR_MENO, IM_STANZ_INIZIALE_A2, IM_STANZ_INIZIALE_A3
from
 VP_DBIL_FIN_CNR
where
   IM_STANZ_ES_PREC_ASS <> 0
or IM_RES_INIZIALE <> 0
or IM_STANZ_INIZIALE_A1 <> 0
or IM_STANZ_INIZIALE_A2 <> 0
or IM_STANZ_INIZIALE_A3 <> 0
)
;

   COMMENT ON TABLE "VP_DBIL_FIN_CNR_DZ"  IS 'Vista di stampa del bilancio finanziario CNR solo importi significativi per la stampa <> 0';
