--------------------------------------------------------
--  DDL for View VP_DPDG_AGGREGATO_SPE_VAR
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VP_DPDG_AGGREGATO_SPE_VAR" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "CD_CDS_ROOT", "DS_CDS_ROOT", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "CD_FUNZIONE", "DS_FUNZIONE", "CD_NATURA", "DS_NATURA", "CD_CDS", "DS_CDS", "IM_RH_CCS_COSTI", "IM_RI_CCS_SPESE_ODC", "IM_RJ_CCS_SPESE_ODC_ALTRA_UO", "IM_RK_CCS_SPESE_OGC", "IM_RL_CCS_SPESE_OGC_ALTRA_UO", "IM_RM_CSS_AMMORTAMENTI", "IM_RN_CSS_RIMANENZE", "IM_RO_CSS_ALTRI_COSTI", "IM_RP_CSS_VERSO_ALTRO_CDR", "IM_RQ_SSC_COSTI_ODC", "IM_RR_SSC_COSTI_ODC_ALTRA_UO", "IM_RS_SSC_COSTI_OGC", "IM_RT_SSC_COSTI_OGC_ALTRA_UO", "IM_RU_SPESE_COSTI_ALTRUI", "IM_RV_PAGAMENTI", "IM_RAA_A2_COSTI_FINALI", "IM_RAB_A2_COSTI_ALTRO_CDR", "IM_RAC_A2_SPESE_ODC", "IM_RAD_A2_SPESE_ODC_ALTRA_UO", "IM_RAE_A2_SPESE_OGC", "IM_RAF_A2_SPESE_OGC_ALTRA_UO", "IM_RAG_A2_SPESE_COSTI_ALTRUI", "IM_RAH_A3_COSTI_FINALI", "IM_RAI_A3_COSTI_ALTRO_CDR", "IM_RAL_A3_SPESE_ODC", "IM_RAM_A3_SPESE_ODC_ALTRA_UO", "IM_RAN_A3_SPESE_OGC", "IM_RAO_A3_SPESE_OGC_ALTRA_UO", "IM_RAP_A3_SPESE_COSTI_ALTRUI", "MIM_RH_CCS_COSTI", "MIM_RI_CCS_SPESE_ODC", "MIM_RJ_CCS_SPESE_ODC_ALTRA_UO", "MIM_RK_CCS_SPESE_OGC", "MIM_RL_CCS_SPESE_OGC_ALTRA_UO", "MIM_RM_CSS_AMMORTAMENTI", "MIM_RN_CSS_RIMANENZE", "MIM_RO_CSS_ALTRI_COSTI", "MIM_RP_CSS_VERSO_ALTRO_CDR", "MIM_RQ_SSC_COSTI_ODC", "MIM_RR_SSC_COSTI_ODC_ALTRA_UO", "MIM_RS_SSC_COSTI_OGC", "MIM_RT_SSC_COSTI_OGC_ALTRA_UO", "MIM_RU_SPESE_COSTI_ALTRUI", "MIM_RV_PAGAMENTI", "MIM_RAA_A2_COSTI_FINALI", "MIM_RAB_A2_COSTI_ALTRO_CDR", "MIM_RAC_A2_SPESE_ODC", "MIM_RAD_A2_SPESE_ODC_ALTRA_UO", "MIM_RAE_A2_SPESE_OGC", "MIM_RAF_A2_SPESE_OGC_ALTRA_UO", "MIM_RAG_A2_SPESE_COSTI_ALTRUI", "MIM_RAH_A3_COSTI_FINALI", "MIM_RAI_A3_COSTI_ALTRO_CDR", "MIM_RAL_A3_SPESE_ODC", "MIM_RAM_A3_SPESE_ODC_ALTRA_UO", "MIM_RAN_A3_SPESE_OGC", "MIM_RAO_A3_SPESE_OGC_ALTRA_UO", "MIM_RAP_A3_SPESE_COSTI_ALTRUI", "DIM_RH_CCS_COSTI", "DIM_RI_CCS_SPESE_ODC", "DIM_RJ_CCS_SPESE_ODC_ALTRA_UO", "DIM_RK_CCS_SPESE_OGC", "DIM_RL_CCS_SPESE_OGC_ALTRA_UO", "DIM_RM_CSS_AMMORTAMENTI", "DIM_RN_CSS_RIMANENZE", "DIM_RO_CSS_ALTRI_COSTI", "DIM_RP_CSS_VERSO_ALTRO_CDR", "DIM_RQ_SSC_COSTI_ODC", "DIM_RR_SSC_COSTI_ODC_ALTRA_UO", "DIM_RS_SSC_COSTI_OGC", "DIM_RT_SSC_COSTI_OGC_ALTRA_UO", "DIM_RU_SPESE_COSTI_ALTRUI", "DIM_RV_PAGAMENTI", "DIM_RAA_A2_COSTI_FINALI", "DIM_RAB_A2_COSTI_ALTRO_CDR", "DIM_RAC_A2_SPESE_ODC", "DIM_RAD_A2_SPESE_ODC_ALTRA_UO", "DIM_RAE_A2_SPESE_OGC", "DIM_RAF_A2_SPESE_OGC_ALTRA_UO", "DIM_RAG_A2_SPESE_COSTI_ALTRUI", "DIM_RAH_A3_COSTI_FINALI", "DIM_RAI_A3_COSTI_ALTRO_CDR", "DIM_RAL_A3_SPESE_ODC", "DIM_RAM_A3_SPESE_ODC_ALTRA_UO", "DIM_RAN_A3_SPESE_OGC", "DIM_RAO_A3_SPESE_OGC_ALTRA_UO", "DIM_RAP_A3_SPESE_COSTI_ALTRUI") AS 
  select
--
-- Date: 23/01/2003
-- Version: 1.0
--
-- Vista di stampa variazioni su aggregato parte ente indotte da variazioni dettagli su piano di gestione
--
-- History:
--
-- Date: 23/01/2003
-- Version: 1.0
-- Creazione
--
-- Body:
--
 ESERCIZIO,
CD_CENTRO_RESPONSABILITA, DS_CDR, CD_CDS_ROOT, DS_CDS_ROOT,
CD_ELEMENTO_VOCE, DS_ELEMENTO_VOCE, CD_FUNZIONE, DS_FUNZIONE,
CD_NATURA, DS_NATURA, CD_CDS, DS_CDS,
IM_RH_CCS_COSTI, IM_RI_CCS_SPESE_ODC, IM_RJ_CCS_SPESE_ODC_ALTRA_UO, IM_RK_CCS_SPESE_OGC,
IM_RL_CCS_SPESE_OGC_ALTRA_UO, IM_RM_CSS_AMMORTAMENTI, IM_RN_CSS_RIMANENZE, IM_RO_CSS_ALTRI_COSTI,
IM_RP_CSS_VERSO_ALTRO_CDR, IM_RQ_SSC_COSTI_ODC, IM_RR_SSC_COSTI_ODC_ALTRA_UO, IM_RS_SSC_COSTI_OGC,
IM_RT_SSC_COSTI_OGC_ALTRA_UO, IM_RU_SPESE_COSTI_ALTRUI, IM_RV_PAGAMENTI, IM_RAA_A2_COSTI_FINALI,
IM_RAB_A2_COSTI_ALTRO_CDR, IM_RAC_A2_SPESE_ODC, IM_RAD_A2_SPESE_ODC_ALTRA_UO, IM_RAE_A2_SPESE_OGC,
IM_RAF_A2_SPESE_OGC_ALTRA_UO, IM_RAG_A2_SPESE_COSTI_ALTRUI, IM_RAH_A3_COSTI_FINALI, IM_RAI_A3_COSTI_ALTRO_CDR,
IM_RAL_A3_SPESE_ODC, IM_RAM_A3_SPESE_ODC_ALTRA_UO, IM_RAN_A3_SPESE_OGC, IM_RAO_A3_SPESE_OGC_ALTRA_UO,
IM_RAP_A3_SPESE_COSTI_ALTRUI, MIM_RH_CCS_COSTI, MIM_RI_CCS_SPESE_ODC, MIM_RJ_CCS_SPESE_ODC_ALTRA_UO,
MIM_RK_CCS_SPESE_OGC, MIM_RL_CCS_SPESE_OGC_ALTRA_UO, MIM_RM_CSS_AMMORTAMENTI, MIM_RN_CSS_RIMANENZE,
MIM_RO_CSS_ALTRI_COSTI, MIM_RP_CSS_VERSO_ALTRO_CDR, MIM_RQ_SSC_COSTI_ODC, MIM_RR_SSC_COSTI_ODC_ALTRA_UO,
MIM_RS_SSC_COSTI_OGC, MIM_RT_SSC_COSTI_OGC_ALTRA_UO, MIM_RU_SPESE_COSTI_ALTRUI, MIM_RV_PAGAMENTI,
MIM_RAA_A2_COSTI_FINALI, MIM_RAB_A2_COSTI_ALTRO_CDR, MIM_RAC_A2_SPESE_ODC, MIM_RAD_A2_SPESE_ODC_ALTRA_UO,
MIM_RAE_A2_SPESE_OGC, MIM_RAF_A2_SPESE_OGC_ALTRA_UO, MIM_RAG_A2_SPESE_COSTI_ALTRUI, MIM_RAH_A3_COSTI_FINALI,
MIM_RAI_A3_COSTI_ALTRO_CDR, MIM_RAL_A3_SPESE_ODC, MIM_RAM_A3_SPESE_ODC_ALTRA_UO, MIM_RAN_A3_SPESE_OGC,
MIM_RAO_A3_SPESE_OGC_ALTRA_UO, MIM_RAP_A3_SPESE_COSTI_ALTRUI, DIM_RH_CCS_COSTI, DIM_RI_CCS_SPESE_ODC,
DIM_RJ_CCS_SPESE_ODC_ALTRA_UO, DIM_RK_CCS_SPESE_OGC, DIM_RL_CCS_SPESE_OGC_ALTRA_UO, DIM_RM_CSS_AMMORTAMENTI,
DIM_RN_CSS_RIMANENZE, DIM_RO_CSS_ALTRI_COSTI, DIM_RP_CSS_VERSO_ALTRO_CDR, DIM_RQ_SSC_COSTI_ODC,
DIM_RR_SSC_COSTI_ODC_ALTRA_UO, DIM_RS_SSC_COSTI_OGC, DIM_RT_SSC_COSTI_OGC_ALTRA_UO, DIM_RU_SPESE_COSTI_ALTRUI,
DIM_RV_PAGAMENTI, DIM_RAA_A2_COSTI_FINALI, DIM_RAB_A2_COSTI_ALTRO_CDR, DIM_RAC_A2_SPESE_ODC,
DIM_RAD_A2_SPESE_ODC_ALTRA_UO, DIM_RAE_A2_SPESE_OGC, DIM_RAF_A2_SPESE_OGC_ALTRA_UO, DIM_RAG_A2_SPESE_COSTI_ALTRUI,
DIM_RAH_A3_COSTI_FINALI, DIM_RAI_A3_COSTI_ALTRO_CDR, DIM_RAL_A3_SPESE_ODC, DIM_RAM_A3_SPESE_ODC_ALTRA_UO,
DIM_RAN_A3_SPESE_OGC, DIM_RAO_A3_SPESE_OGC_ALTRA_UO, DIM_RAP_A3_SPESE_COSTI_ALTRUI from
V_DPDG_AGGREGATO_SPE_VAR
where
DIM_RH_CCS_COSTI <> 0 or
DIM_RI_CCS_SPESE_ODC <> 0  or
DIM_RJ_CCS_SPESE_ODC_ALTRA_UO <> 0  or
DIM_RK_CCS_SPESE_OGC <> 0  or
DIM_RL_CCS_SPESE_OGC_ALTRA_UO <> 0  or
DIM_RM_CSS_AMMORTAMENTI <> 0  or
DIM_RN_CSS_RIMANENZE <> 0  or
DIM_RO_CSS_ALTRI_COSTI <> 0  or
DIM_RP_CSS_VERSO_ALTRO_CDR <> 0  or
DIM_RQ_SSC_COSTI_ODC <> 0  or
DIM_RR_SSC_COSTI_ODC_ALTRA_UO <> 0  or
DIM_RS_SSC_COSTI_OGC <> 0  or
DIM_RT_SSC_COSTI_OGC_ALTRA_UO <> 0  or
DIM_RU_SPESE_COSTI_ALTRUI <> 0  or
DIM_RV_PAGAMENTI <> 0  or
DIM_RAA_A2_COSTI_FINALI <> 0  or
DIM_RAB_A2_COSTI_ALTRO_CDR <> 0  or
DIM_RAC_A2_SPESE_ODC <> 0  or
DIM_RAD_A2_SPESE_ODC_ALTRA_UO <> 0  or
DIM_RAE_A2_SPESE_OGC <> 0  or
DIM_RAF_A2_SPESE_OGC_ALTRA_UO <> 0  or
DIM_RAG_A2_SPESE_COSTI_ALTRUI <> 0  or
DIM_RAH_A3_COSTI_FINALI <> 0  or
DIM_RAI_A3_COSTI_ALTRO_CDR <> 0  or
DIM_RAL_A3_SPESE_ODC <> 0  or
DIM_RAM_A3_SPESE_ODC_ALTRA_UO <> 0  or
DIM_RAN_A3_SPESE_OGC <> 0  or
DIM_RAO_A3_SPESE_OGC_ALTRA_UO <> 0  or
DIM_RAP_A3_SPESE_COSTI_ALTRUI <> 0
;

   COMMENT ON TABLE "VP_DPDG_AGGREGATO_SPE_VAR"  IS 'Vista di stampa variazioni su aggregato parte ente indotte da variazioni dettagli su piano di gestione';
