--------------------------------------------------------
--  DDL for View VP_DPDG_CDR_PRIMO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VP_DPDG_CDR_PRIMO" ("ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "CD_UNITA_ORGANIZZATIVA", "DS_UNITA_ORGANIZZATIVA", "CD_CDS", "DS_CDS", "STATO", "ANNOTAZIONI", "FL_RIBALTATO_SU_AREA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "CD_TITOLO", "DS_TITOLO", "CD_CAPOCONTO", "DS_CAPOCONTO", "CD_FUNZIONE", "DS_FUNZIONE", "CD_NATURA", "DS_NATURA", "IM_RH_CCS_COSTI", "IM_RI_CCS_SPESE_ODC", "IM_RJ_CCS_SPESE_ODC_ALTRA_UO", "IM_RK_CCS_SPESE_OGC", "IM_RL_CCS_SPESE_OGC_ALTRA_UO", "IM_RM_CSS_AMMORTAMENTI", "IM_RN_CSS_RIMANENZE", "IM_RO_CSS_ALTRI_COSTI", "IM_RP_CSS_VERSO_ALTRO_CDR", "IM_RQ_SSC_COSTI_ODC", "IM_RR_SSC_COSTI_ODC_ALTRA_UO", "IM_RS_SSC_COSTI_OGC", "IM_RT_SSC_COSTI_OGC_ALTRA_UO", "IM_RU_SPESE_COSTI_ALTRUI", "IM_RV_PAGAMENTI", "IM_RAA_A2_COSTI_FINALI", "IM_RAB_A2_COSTI_ALTRO_CDR", "IM_RAC_A2_SPESE_ODC", "IM_RAD_A2_SPESE_ODC_ALTRA_UO", "IM_RAE_A2_SPESE_OGC", "IM_RAF_A2_SPESE_OGC_ALTRA_UO", "IM_RAG_A2_SPESE_COSTI_ALTRUI", "IM_RAH_A3_COSTI_FINALI", "IM_RAI_A3_COSTI_ALTRO_CDR", "IM_RAL_A3_SPESE_ODC", "IM_RAM_A3_SPESE_ODC_ALTRA_UO", "IM_RAN_A3_SPESE_OGC", "IM_RAO_A3_SPESE_OGC_ALTRA_UO", "IM_RAP_A3_SPESE_COSTI_ALTRUI", "IM_RA_RCE", "IM_RB_RSE", "IM_RC_ESR", "IM_RD_A2_RICAVI", "IM_RE_A2_ENTRATE", "IM_RF_A3_RICAVI", "IM_RG_A3_ENTRATE") AS 
  select
--
-- Date: 07/10/2002
-- Version: 1.0
--
-- Vista di stampa dei dettagli pdg CDR di primo livello: legge parte spesa ed entrata dalle viste da cui dipende
--
-- History:
--
-- Date: 07/10/2002
-- Version: 1.0
-- Creazione
--
-- Body:
--
 ESERCIZIO
,CD_CENTRO_RESPONSABILITA
,DS_CDR
,CD_UNITA_ORGANIZZATIVA
,DS_UNITA_ORGANIZZATIVA
,CD_CDS
,DS_CDS
,STATO
,ANNOTAZIONI
,FL_RIBALTATO_SU_AREA
,TI_APPARTENENZA
,TI_GESTIONE
,CD_ELEMENTO_VOCE
,DS_ELEMENTO_VOCE
,CD_TITOLO
,DS_TITOLO
,CD_CAPOCONTO
,DS_CAPOCONTO
,cd_funzione
,ds_funzione
,cd_natura
,ds_natura
,IM_RH_CCS_COSTI, IM_RI_CCS_SPESE_ODC,
IM_RJ_CCS_SPESE_ODC_ALTRA_UO,
IM_RK_CCS_SPESE_OGC, IM_RL_CCS_SPESE_OGC_ALTRA_UO, IM_RM_CSS_AMMORTAMENTI, IM_RN_CSS_RIMANENZE,
IM_RO_CSS_ALTRI_COSTI, IM_RP_CSS_VERSO_ALTRO_CDR, IM_RQ_SSC_COSTI_ODC, IM_RR_SSC_COSTI_ODC_ALTRA_UO,
IM_RS_SSC_COSTI_OGC, IM_RT_SSC_COSTI_OGC_ALTRA_UO, IM_RU_SPESE_COSTI_ALTRUI, IM_RV_PAGAMENTI,
IM_RAA_A2_COSTI_FINALI, IM_RAB_A2_COSTI_ALTRO_CDR, IM_RAC_A2_SPESE_ODC, IM_RAD_A2_SPESE_ODC_ALTRA_UO,
IM_RAE_A2_SPESE_OGC, IM_RAF_A2_SPESE_OGC_ALTRA_UO, IM_RAG_A2_SPESE_COSTI_ALTRUI, IM_RAH_A3_COSTI_FINALI,
IM_RAI_A3_COSTI_ALTRO_CDR, IM_RAL_A3_SPESE_ODC, IM_RAM_A3_SPESE_ODC_ALTRA_UO, IM_RAN_A3_SPESE_OGC,
IM_RAO_A3_SPESE_OGC_ALTRA_UO, IM_RAP_A3_SPESE_COSTI_ALTRUI,
0,
0,
0,
0,
0,
0,
0
from vp_dpdg_spe_cdr_primo
union all
select
 ESERCIZIO
,CD_CENTRO_RESPONSABILITA
,DS_CDR
,CD_UNITA_ORGANIZZATIVA
,DS_UNITA_ORGANIZZATIVA
,CD_CDS
,DS_CDS
,STATO
,ANNOTAZIONI
,FL_RIBALTATO_SU_AREA
,TI_APPARTENENZA
,TI_GESTIONE
,CD_ELEMENTO_VOCE
,DS_ELEMENTO_VOCE
,CD_TITOLO
,DS_TITOLO
,CD_CAPOCONTO
,DS_CAPOCONTO
,cd_funzione
,ds_funzione
,cd_natura
,ds_natura
,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,
IM_RA_RCE, IM_RB_RSE, IM_RC_ESR,
IM_RD_A2_RICAVI, IM_RE_A2_ENTRATE, IM_RF_A3_RICAVI, IM_RG_A3_ENTRATE
from vp_dpdg_etr_cdr_primo
;

   COMMENT ON TABLE "VP_DPDG_CDR_PRIMO"  IS 'Vista di stampa dei dettagli pdg CDR di primo livello: legge parte spesa ed entrata dalle viste da cui dipende';
