--------------------------------------------------------
--  DDL for View VP_REGISTRO_IVA_ACQUISTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VP_REGISTRO_IVA_ACQUISTI" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "PG_FATTURA", "ESERCIZIO", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "CD_TIPO_SEZIONALE", "TI_ISTITUZ_COMMERC", "DATA_REGISTRAZIONE", "DATA_EMISSIONE", "PROTOCOLLO_IVA", "PROTOCOLLO_IVA_GENERALE", "NUMERO_FATTURA_FORNITORE", "TI_FATTURA", "COMM_IST_TESTATA", "CODICE_ANAGRAFICO", "RAGIONE_SOCIALE", "IMPONIBILE_DETTAGLIO", "IVA_DETTAGLIO", "IVA_INDETRAIBILE_DETTAGLIO", "TOTALE_DETTAGLIO", "COMM_IST_DETTAGLIO", "CODICE_IVA", "PERCENTUALE_IVA", "DESCRIZIONE_IVA", "FL_IVA_DETRAIBILE", "PERCENTUALE_IVA_DETRAIBILE", "GRUPPO_IVA", "DESCRIZIONE_GRUPPO_IVA", "INTRA_UE", "BOLLA_DOGANALE", "CODICE_VALUTA", "IMPORTO_VALUTA", "ESIGIBILITA_DIFF", "DATA_ESIGIBILITA_DIFF") AS 
  SELECT
--  
-- Date: 03/04/2002  
-- Version: 1.0  
--  
-- Vista di estrazione dei documenti di acquisto 
--  
-- History:  
--  
-- Date: 03/04/2002  
-- Version: 1.0  
-- Creazione  
--  
-- Body:  
--  

       A.CD_CDS, 
       A.CD_UNITA_ORGANIZZATIVA, 
       A.PG_FATTURA, 
       A.ESERCIZIO, 
       A.CD_CDS_ORIGINE, 
       A.CD_UO_ORIGINE, 
       A.CD_TIPO_SEZIONALE, 
	   A.TI_ISTITUZ_COMMERC, 
       A.DATA_REGISTRAZIONE, 
       A.DATA_EMISSIONE, 
       A.PROTOCOLLO_IVA, 
       A.PROTOCOLLO_IVA_GENERALE, 
       A.NUMERO_FATTURA_FORNITORE, 
       A.TI_FATTURA, 
       A.COMM_IST_TESTATA, 
       A.CODICE_ANAGRAFICO, 
       A.RAGIONE_SOCIALE, 
       A.IMPONIBILE_DETTAGLIO, 
       A.IVA_DETTAGLIO, 
       (A.IVA_DETTAGLIO * ((100 - A.PERCENTUALE_IVA_DETRAIBILE) / 100)), 
       A.TOTALE_DETTAGLIO, 
       A.COMM_IST_DETTAGLIO, 
       A.CODICE_IVA, 
       A.PERCENTUALE_IVA, 
       A.DESCRIZIONE_IVA, 
       A.FL_IVA_DETRAIBILE, 
       A.PERCENTUALE_IVA_DETRAIBILE, 
       A.GRUPPO_IVA, 
       A.DESCRIZIONE_GRUPPO_IVA, 
       A.INTRA_UE, 
       A.BOLLA_DOGANALE, 
       A.CODICE_VALUTA, 
       A.IMPORTO_VALUTA, 
       A.ESIGIBILITA_DIFF, 
       A.DATA_ESIGIBILITA_DIFF 
FROM   VP_REGISTRO_IVA_ACQUISTI_PRE A;
