--------------------------------------------------------
--  DDL for View VP_REGISTRO_IVA_ACQUISTI_PRE
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VP_REGISTRO_IVA_ACQUISTI_PRE" ("CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_FATTURA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "CD_TIPO_SEZIONALE", "TI_FATTURA", "TI_ISTITUZ_COMMERC", "DATA_REGISTRAZIONE", "PROTOCOLLO_IVA", "PROTOCOLLO_IVA_GENERALE", "DATA_EMISSIONE", "NUMERO_FATTURA_FORNITORE", "COMM_IST_TESTATA", "CODICE_ANAGRAFICO", "RAGIONE_SOCIALE", "IMPONIBILE_DETTAGLIO", "IVA_DETTAGLIO", "IVA_INDETRAIBILE_DETTAGLIO", "TOTALE_DETTAGLIO", "COMM_IST_DETTAGLIO", "CODICE_IVA", "PERCENTUALE_IVA", "DESCRIZIONE_IVA", "FL_IVA_DETRAIBILE", "PERCENTUALE_IVA_DETRAIBILE", "GRUPPO_IVA", "DESCRIZIONE_GRUPPO_IVA", "INTRA_UE", "BOLLA_DOGANALE", "CODICE_VALUTA", "IMPORTO_VALUTA", "ESIGIBILITA_DIFF", "DATA_ESIGIBILITA_DIFF") AS 
  SELECT
--
-- Date: 03/04/2002
-- Version: 1.0
--
-- Vista di preparazione per estrazione dei documenti di acquisto
--
-- History:
--
-- Date: 03/04/2002
-- Version: 1.0
-- Creazione
--
-- Body:
--
  A.CD_CDS						,
  A.CD_UNITA_ORGANIZZATIVA		,
  A.ESERCIZIO					,
  A.PG_FATTURA_PASSIVA			,
  A.CD_CDS_ORIGINE				,
  A.CD_UO_ORIGINE				,
  A.CD_TIPO_SEZIONALE			,
  A.TI_FATTURA					,
  A.TI_ISTITUZ_COMMERC,
  TRUNC(A.DT_REGISTRAZIONE)	 	 DATA_REGISTRAZIONE,
  A.PROTOCOLLO_IVA				 PROTOCOLLO_IVA,
  A.PROTOCOLLO_IVA_GENERALE      PROTOCOLLO_IVA_GENERALE,
  TRUNC(A.DT_FATTURA_FORNITORE)  DATA_EMISSIONE_FORNITORE,
  A.NR_FATTURA_FORNITORE		 NUMERO_FATTURA,
  UPPER(A.TI_FATTURA)			 COMM_IST_TESTATA,
  A.CD_TERZO					 CODICE_ANAGRAFICO,
  A.RAGIONE_SOCIALE			 	 RAGIONE_SOCIALE,
  DECODE(A.TI_FATTURA,'C',(SUM(NVL(B.IM_IMPONIBILE,0)) * -1),SUM(NVL(B.IM_IMPONIBILE,0))) IMPONIBILE_DETTAGLIO,
  DECODE(A.TI_FATTURA,'C',(SUM(NVL(B.IM_IVA,0)) * -1),SUM(NVL(B.IM_IVA,0)))				  IVA_DETTAGLIO,
  0								 IVA_INDETRAIBILE_DETTAGLIO,
  DECODE(A.TI_FATTURA,'C',(SUM(NVL(B.IM_IMPONIBILE,0) + NVL(B.IM_IVA,0)) * -1),SUM(NVL(B.IM_IMPONIBILE,0) + NVL(B.IM_IVA,0)))	TOTALE_DETTAGLIO,
  NVL(UPPER(B.TI_ISTITUZ_COMMERC),'C')	COMM_IST_DETTAGLIO,
  B.CD_VOCE_IVA							CODICE_IVA,
  C.PERCENTUALE							PERCENTUALE_IVA,
  C.DS_VOCE_IVA							DESCRIZIONE_IVA,
  NVL(C.FL_DETRAIBILE,'Y')				FL_IVA_DETRAIBILE,
  DECODE(NVL(C.FL_DETRAIBILE,'Y'),'N',0,NVL(C.PERCENTUALE_DETRAIBILITA,100)) PERCENTUALE_IVA_DETRAIBILE,
  NVL(C.CD_GRUPPO_IVA, '***** GRUPPO IVA INESISTENTE *****')	GRUPPO_IVA,
  D.DS_GRUPPO_IVA	   		  		 	DESCRIZIONE_GRUPPO_IVA,
  NVL(A.FL_INTRA_UE,'N') 				INTRA_UE,
  NVL(A.FL_BOLLA_DOGANALE,'N')			BOLLA_DOGANALE,
  A.CD_DIVISA					  		CODICE_VALUTA,
  SUM(NVL(B.IM_TOTALE_DIVISA, 0))		IMPORTO_VALUTA,
  fl_liquidazione_differita			ESIGIBILITA_DIFF,
  data_esigibilita_iva				DATA_ESIGIBILITA_DIFF
FROM
  FATTURA_PASSIVA 		A,
  FATTURA_PASSIVA_RIGA 	B,
  VOCE_IVA 		C,
  GRUPPO_IVA 		D
WHERE
  B.CD_CDS    			  	  = A.CD_CDS                 AND
  B.CD_UNITA_ORGANIZZATIVA   = A.CD_UNITA_ORGANIZZATIVA  AND
  B.PG_FATTURA_PASSIVA		  = A.PG_FATTURA_PASSIVA     AND
  B.ESERCIZIO 				  = A.ESERCIZIO              AND
  C.CD_VOCE_IVA (+) 	      = B.CD_VOCE_IVA            AND
  D.CD_GRUPPO_IVA (+) 		  = C.CD_GRUPPO_IVA
GROUP BY          A.CD_CDS,
	  			  A.CD_UNITA_ORGANIZZATIVA,
				  A.ESERCIZIO,
				  A.PG_FATTURA_PASSIVA,
				  A.CD_CDS_ORIGINE,
				  A.CD_UO_ORIGINE,
				  A.CD_TIPO_SEZIONALE,
				  A.TI_FATTURA,
				  A.TI_ISTITUZ_COMMERC,
				  TRUNC(A.DT_REGISTRAZIONE),
				  A.PROTOCOLLO_IVA,
				  A.PROTOCOLLO_IVA_GENERALE,
				  TRUNC(A.DT_FATTURA_FORNITORE),
				  A.NR_FATTURA_FORNITORE,
				  UPPER(A.TI_FATTURA),
				  A.CD_TERZO,
				  A.RAGIONE_SOCIALE,
				  0,
				  NVL(UPPER(B.TI_ISTITUZ_COMMERC),'C'),
				  B.CD_VOCE_IVA,
				  C.PERCENTUALE,
				  C.DS_VOCE_IVA,
				  NVL(C.FL_DETRAIBILE,'Y'),
				  DECODE(NVL(C.FL_DETRAIBILE,'Y'),
				  'N',
				  0,
				  NVL(C.PERCENTUALE_DETRAIBILITA,100)),
				  NVL(C.CD_GRUPPO_IVA,'***** GRUPPO IVA INESISTENTE *****'),
				  D.DS_GRUPPO_IVA,
				  NVL(A.FL_INTRA_UE,'N'),
				  NVL(A.FL_BOLLA_DOGANALE,'N'),
				  A.CD_DIVISA,
				  fl_liquidazione_differita,
				  data_esigibilita_iva;
