--------------------------------------------------------
--  DDL for View VPG_DOC_GENERICO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VPG_DOC_GENERICO" ("ID", "CHIAVE", "DESCRIZIONE", "SEQUENZA", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "CD_TIPO_DOCUMENTO_AMM", "PG_DOCUMENTO_GENERICO", "TI_RECORD_L1", "TI_RECORD_L2", "DS_TIPO_DOCUMENTO_AMM", "TI_ENTRATA_SPESA", "CD_CDS_ORIGINE", "CD_UO_ORIGINE", "DS_CDS", "DS_UO_ORIGINE", "DATA_REGISTRAZIONE", "DS_DOCUMENTO_GENERICO", "TI_ISTITUZ_COMMERC", "IM_TOTALE", "STATO_COFI", "CD_DIVISA", "CAMBIO", "UTCR", "DACR", "CODICE_FISCALE_ENTE", "PARTITA_IVA_ENTE", "VIA_FISCALE_ENTE", "CAP_COMUNE_FISCALE_ENTE", "DS_COMUNE_ENTE", "CD_PROVINCIA_ENTE", "CAB_IC", "ABI_IC", "NUMERO_CONTO_IC", "CIN_IC", "INTESTAZIONE_IC", "DS_ABICAB_IC", "VIA_IC", "CAP_IC", "DS_COMUNE_IC", "CD_PROVINCIA_IC", "PROGRESSIVO_RIGA", "DS_RIGA", "IM_RIGA_DIVISA", "IM_RIGA", "CD_TERZO", "RAGIONE_SOCIALE", "NOME", "COGNOME", "CODICE_FISCALE", "PARTITA_IVA", "DENOMINAZIONE_SEDE", "VIA_SEDE", "DS_COMUNE_SEDE", "CD_PROVINCIA_SEDE", "CAP_COMUNE_SEDE", "CD_MODALITA_PAG", "DS_MODALITA_PAG", "TI_PAGAMENTO", "CAB_TERZO", "ABI_TERZO", "NUMERO_CONTO_TERZO", "CIN_TERZO", "INTESTAZIONE_TERZO", "DS_ABICAB_TERZO", "VIA_BANCA_TERZO", "CAP_BANCA_TERZO", "DS_COMUNE_BANCA_TERZO", "CD_PV_BANCA_TERZO", "CD_CDS_OBB_ACC", "ESERCIZIO_OBB_ACC", "ESERCIZIO_ORI_OBB_ACC", "PG_OBB_ACC", "PG_OBB_ACC_SCAD", "CD_VOCE", "DS_VOCE", "PG_MAN_REV", "IBAN_IC", "IBAN", "CD_TIPO_DOCUMENTO_GENERICO", "DS_TIPO_DOCUMENTO_GENERICO") AS 
  SELECT
--
-- Date: 19/07/2006
-- Version: 1.3
--
-- Vista per la stampa massiva dei documenti generici attivi e passivi
-- Protocollo VPG
--
-- History:
--
-- Date: 19/03/2003
-- Version: 1.0
-- Creazione
--
-- Date: 24/03/2003
-- Version: 1.1
-- Corretta mappatura campi (attributo_15 duplicato)
--
-- Date: 21/01/2004
-- Version: 1.2
-- Estrazione CIN dalla BANCA (richiesta n. 697)
--
-- Date: 19/07/2006
-- Version: 1.3
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Body:
--
ID,
CHIAVE,
DESCRIZIONE,
SEQUENZA,
ATTRIBUTO_1, 		-- CD_CDS
ATTRIBUTO_2, 		-- CD_UNITA_ORGANIZZATIVA,
IMPORTO_1,			-- ESERCIZIO,
ATTRIBUTO_3, 		-- CD_TIPO_DOCUMENTO_AMM,
IMPORTO_2,			-- PG_DOCUMENTO_GENERICO,
TIPO,				-- TI_RECORD_L1,
ATTRIBUTO_4, 		-- TI_RECORD_L2,
ATTRIBUTO_LONG_5,	-- DS_TIPO_DOCUMENTO_AMM
ATTRIBUTO_46, 		-- TI_ENTRATA_SPESA
ATTRIBUTO_49,		-- CD_CDS_ORIGINE,
ATTRIBUTO_50,		-- CD_UO_ORIGINE,
ATTRIBUTO_LONG_2,	-- DS_CDS_ORIGINE,
ATTRIBUTO_LONG_3,	-- DS_UO_ORIGINE,
DATA_1,				-- DATA_REGISTRAZIONE,
ATTRIBUTO_LONG_1,	-- DS_DOCUMENTO_GENERICO,
ATTRIBUTO_5, 		-- TI_ISTITUZ_COMMERC,
IMPORTO_3,			-- IM_TOTALE,
ATTRIBUTO_6, 		-- STATO_COFI,
ATTRIBUTO_7, 		-- CD_DIVISA,
IMPORTO_4,			-- CAMBIO,
ATTRIBUTO_8, 		-- UTCR,
DATA_2,				-- DACR,
ATTRIBUTO_9, 		-- CODICE_FISCALE_ENTE,
ATTRIBUTO_10, 		-- PARTITA_IVA_ENTE,
ATTRIBUTO_11, 		-- VIA_FISCALE_ENTE,
ATTRIBUTO_12, 		-- CAP_COMUNE_FISCALE_ENTE,
ATTRIBUTO_13, 		-- DS_COMUNE_ENTE,
ATTRIBUTO_14, 		-- CD_PROVINCIA_ENTE,
ATTRIBUTO_15, 		-- CAB_IC,   -- dati istituto cassiere
ATTRIBUTO_16, 		-- ABI_IC,
ATTRIBUTO_17, 		-- NUMERO_CONTO_IC,
ATTRIBUTO_51,		-- CIN_IC,
ATTRIBUTO_18, 		-- INTESTAZIONE_IC,
ATTRIBUTO_19, 		-- DS_ABICAB_IC,
ATTRIBUTO_20, 		-- VIA_IC,
ATTRIBUTO_21, 		-- CAP_IC,
ATTRIBUTO_22, 		-- DS_COMUNE_IC,
ATTRIBUTO_23, 		-- CD_PROVINCIA_IC
IMPORTO_12,			-- PROGRESSIVO_RIGA,
ATTRIBUTO_LONG_6, 	-- DS_RIGA,
IMPORTO_5,			-- IM_RIGA_DIVISA,
IMPORTO_6,			-- IM_RIGA,
IMPORTO_7,			-- CD_TERZO,
ATTRIBUTO_25, 		-- RAGIONE_SOCIALE,
ATTRIBUTO_26, 		-- NOME,
ATTRIBUTO_27, 		-- COGNOME,
ATTRIBUTO_28, 		-- CODICE_FISCALE,
ATTRIBUTO_29, 		-- PARTITA_IVA
ATTRIBUTO_30, 		-- DENOMINAZIONE_SEDE,
ATTRIBUTO_31, 		-- VIA_SEDE,
ATTRIBUTO_32, 		-- DS_COMUNE_SEDE,
ATTRIBUTO_33, 		-- CD_PROVINCIA_SEDE,
ATTRIBUTO_34, 		-- CAP_COMUNE_SEDE
ATTRIBUTO_37, 		-- CD_MODALITA_PAG,
ATTRIBUTO_38, 		-- DS_MODALITA_PAG
ATTRIBUTO_46, 		-- TI_PAGAMENTO
ATTRIBUTO_39, 		-- CAB_TERZO,
ATTRIBUTO_40, 		-- ABI_TERZO,
ATTRIBUTO_47,		-- NUMERO_CONTO_TERZO,
ATTRIBUTO_52,		-- CIN_TERZO,
ATTRIBUTO_48,		-- INTESTAZIONE_TERZO,
ATTRIBUTO_41, 		-- DS_ABICAB_TERZO,
ATTRIBUTO_42, 		-- VIA_BANCA_TERZO,
ATTRIBUTO_43, 		-- CAP_BANCA_TERZO,
ATTRIBUTO_44, 		-- DS_COMUNE_BANCA_TERZO,
ATTRIBUTO_45, 		-- CD_PV_BANCA_TERZO
ATTRIBUTO_35, 		-- CD_CDS_OBB_ACC,
IMPORTO_8,			-- ESERCIZIO_OBB_ACC,
IMPORTO_13,			-- ESERCIZIO_ORI_OBB_ACC,
IMPORTO_9,			-- PG_OBB_ACC,
IMPORTO_10,			-- PG_OBB_ACC_SCAD
ATTRIBUTO_36, 		-- CD_VOCE,
ATTRIBUTO_LONG_4,	-- DS_VOCE
IMPORTO_11,			-- PG_MAN_REV
ATTRIBUTO_53,            --IBAN_IC
ATTRIBUTO_54,            --IBAN
ATTRIBUTO_55,            --CD_TIPO_DOCUMENTO_GENERICO
ATTRIBUTO_56            --DS_TIPO_DOCUMENTO_GENERICO
FROM TMP_REPORT_GENERICO ;

   COMMENT ON TABLE "VPG_DOC_GENERICO"  IS 'Vista per la stampa massiva dei documenti generici attivi e passivi
Protocollo VPG';
