--------------------------------------------------------
--  DDL for View VPG_CONGUAGLIO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VPG_CONGUAGLIO" ("ID", "CHIAVE", "TIPO", "SEQUENZA", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "PG_CONGUAGLIO", "DT_REGISTRAZIONE", "DS_CONGUAGLIO", "CD_TERZO", "CD_ANAG", "NOME", "COGNOME", "RAGIONE_SOCIALE", "DT_NASCITA", "DS_COMUNE_NASCITA", "DS_PROVINCIA_NASCITA", "CD_PROVINCIA_NASCITA", "VIA_SEDE", "DS_COMUNE_SEDE", "CD_PROVINCIA_SEDE", "DS_PROVINCIA_SEDE", "FRAZIONE_SEDE", "VIA_FISCALE", "DS_COMUNE_FISCALE", "CD_PROVINCIA_FISCALE", "DS_PROVINCIA_FISCALE", "FRAZIONE_FISCALE", "CAP_COMUNE_FISCALE", "CODICE_FISCALE", "PARTITA_IVA", "ALIQUOTA_FISCALE", "IM_DETRAZIONE_PERSONALE_ANAG", "FL_NOTAXAREA", "FL_NOFAMILYAREA", "FL_ESCLUDI_QVARIA_DEDUZIONE", "FL_INTERA_QFISSA_DEDUZIONE", "DETRAZIONI_PE_DOVUTO", "DETRAZIONI_PE_GODUTO", "DETRAZIONI_LA_DOVUTO", "DETRAZIONI_LA_GODUTO", "DETRAZIONI_CO_DOVUTO", "DETRAZIONI_CO_GODUTO", "DETRAZIONI_FI_DOVUTO", "DETRAZIONI_FI_GODUTO", "DETRAZIONI_AL_DOVUTO", "DETRAZIONI_AL_GODUTO", "IM_DEDUZIONE_DOVUTO", "IM_DEDUZIONE_GODUTO", "IM_IRPEF_DOVUTO", "IM_IRPEF_GODUTO", "FL_ACCANTONA_ADD_TERR", "IM_ADDREG_DOVUTO", "IM_ADDREG_GODUTO", "IM_ADDPROV_DOVUTO", "IM_ADDPROV_GODUTO", "IM_ADDCOM_DOVUTO", "IM_ADDCOM_GODUTO", "NUMERO_GIORNI", "IMPONIBILE_IRPEF_LORDO", "IMPONIBILE_IRPEF_NETTO", "CD_CDS_COMPENSO", "CD_UO_COMPENSO", "ESERCIZIO_COMPENSO", "PG_COMPENSO", "CD_TERZO_COMPENSO", "DS_TRATTAMENTO", "FL_SENZA_CALCOLI", "FL_PAGAM_FONDO_ECO", "PG_MANDATO", "IM_DEDUZIONE_FAMILY_DOVUTO", "IM_FAMILY_DOVUTO", "IM_DEDUZIONE_FAMILY_GODUTO", "IM_FAMILY_GODUTO", "FL_CARICHI_FAMILIARI", "FL_NO_DETRAZIONI_ALTRE", "FL_NO_DETRAZIONI_FAMILY", "FL_DETRAZIONI_ALTRI_TIPI", "IM_REDDITO_COMPLESSIVO", "IM_REDDITO_ABITAZ_PRINC", "FL_APPLICA_DETR_PERS_MAX", "FL_DETRAZIONI_FAM_INTERO_ANNO", "CODICE_FISCALE_ESTERNO", "DT_DA_COMPETENZA_ESTERNO", "DT_A_COMPETENZA_ESTERNO", "IMPONIBILE_FISCALE_ESTERNO", "IM_IRPEF_ESTERNO", "IM_ADDREG_ESTERNO", "IM_ADDPROV_ESTERNO", "IM_ADDCOM_ESTERNO", "DETRAZIONI_LA_ESTERNO", "DETRAZIONI_PE_ESTERNO", "DETRAZIONI_CO_ESTERNO", "DETRAZIONI_FI_ESTERNO", "DETRAZIONI_AL_ESTERNO", "NUMERO_GIORNI_ESTERNO", "PG_COMUNE_ADDCOM_ESTERNO", "IM_CORI_SOSPESO", "IM_CORI_SOSP_CONG", "AMMONTARE", "FL_NO_CREDITO_IRPEF", "FL_NO_CREDITO_CUNEO_IRPEF", "FL_NO_DETR_CUNEO_IRPEF", "IM_CREDITO_IRPEF_GODUTO", "IM_CREDITO_IRPEF_DOVUTO", "IM_BONUS_IRPEF_GODUTO", "IM_BONUS_IRPEF_DOVUTO", "DETRAZIONE_RID_CUNEO_ESTERNO", "DETRAZIONE_RID_CUNEO_GODUTO", "DETRAZIONE_RID_CUNEO_DOVUTO") AS
  SELECT
--
-- Date: 12/10/2007
-- Version: 1.3
--
-- Vista per la stampa del prospetto di conguaglio
-- Protocollo VPG
--
--
-- History:
--
-- Date: 10/11/2003
-- Version: 1.0
-- Creazione
--
-- Date: 23/05/2006
-- Version: 1.1
-- Aggiunti i campi FL_NOFAMILYAREA, IM_DEDUZIONE_DOVUTO, IM_DEDUZIONE_FAMILY_DOVUTO,
-- IM_FAMILY_DOVUTO, IM_DEDUZIONE_FAMILY_GODUTO, IM_FAMILY_GODUTO per adeguamento alla no tax area e alla family area.
--
-- Date: 16/05/2007
-- Version: 1.2
-- Aggiunti FL_NO_DETRAZIONI_ALTRE,FL_NO_DETRAZIONI_FAMILY,FL_DETRAZIONI_ALTRI_TIPI,IM_REDDITO_COMPLESSIVO,
-- IM_REDDITO_ABITAZ_PRINC,FL_APPLICA_DETR_PERS_MAX,FL_DETRAZIONI_FAM_INTERO_ANNO,DETRAZIONI_LA_DOVUTO, DETRAZIONI_LA_GODUTO
-- per adeguamento detrazioni finanziaria 2007
--
-- Date: 12/10/2007
-- Version: 1.3
-- Aggiunti CODICE_FISCALE_ESTERNO,DT_DA_COMPETENZA_ESTERNO,DT_A_COMPETENZA_ESTERNO,IMPONIBILE_FISCALE_ESTERNO,IM_IRPEF_ESTERNO
-- ,IM_ADDREG_ESTERNO,IM_ADDPROV_ESTERNO,IM_ADDCOM_ESTERNO,DETRAZIONI_LA_ESTERNO,DETRAZIONI_PE_ESTERNO,DETRAZIONI_CO_ESTERNO
-- ,DETRAZIONI_FI_ESTERNO,DETRAZIONI_AL_ESTERNO,NUMERO_GIORNI_ESTERNO,PG_COMUNE_ADDCOM_ESTERNO
-- per la gestione dei dati esterni.
--
-- Date: 25/05/2014
-- Version: 2.22
-- Adeguamenti relativi al Bonus DL 66/2014
-- Aggiunti i campi FL_NO_CREDITO_IRPEF,IM_CREDITO_IRPEF_GODUTO,IM_CREDITO_IRPEF_DOVUTO
--
-- Body:
ID,
CHIAVE,
TIPO,
SEQUENZA,
attributo_1,   	   -- CD_CDS,
attributo_2,	   -- CD_UNITA_ORGANIZZATIVA,
importo_1,		   -- ESERCIZIO,
importo_2,		   -- PG_CONGUAGLIO,
data_1,			   -- DT_REGISTRAZIONE,
attributo_long_1,  -- DS_CONGUAGLIO,
importo_3,		   -- CD_TERZO,
importo_4,		   -- CD_ANAG,
attributo_3,	   -- NOME,
attributo_4,	   -- COGNOME,
attributo_5,	   -- RAGIONE_SOCIALE,
data_2,			   -- DT_NASCITA,
attributo_6,	   -- DS_COMUNE_NASCITA,
attributo_7,	   -- DS_PROVINCIA_NASCITA,
attributo_8,	   -- CD_PROVINCIA_NASCITA,
attributo_9,	   -- VIA_SEDE, || numero_civico_sede
attributo_10,	   -- DS_COMUNE_SEDE,
attributo_11,	   -- CD_PROVINCIA_SEDE,
attributo_12,	   -- DS_PROVINCIA_SEDE,
attributo_13,	   -- FRAZIONE_SEDE,
attributo_14,	   -- VIA_FISCALE,
attributo_15,	   -- DS_COMUNE_FISCALE,
attributo_16,	   -- CD_PROVINCIA_FISCALE,
attributo_17,	   -- DS_PROVINCIA_FISCALE,
attributo_18,	   -- FRAZIONE_FISCALE,
attributo_32,	   -- CAP_COMUNE_FISCALE,
attributo_19,	   -- CODICE_FISCALE,
attributo_20,	   -- PARTITA_IVA
importo_dec8_1,	   -- ALIQUOTA_FISCALE
importo_5,		   -- IM_DETRAZIONE_PERSONALE_ANAG,
attributo_21,	   -- FL_NOTAXAREA,
attributo_30,	   -- FL_NOFAMILYAREA,
attributo_22,	   -- FL_ESCLUDI_QVARIA_DEDUZIONE,
attributo_23,	   -- FL_INTERA_QFISSA_DEDUZIONE,
importo_6,		   -- DETRAZIONI_PE_DOVUTO,
importo_7,		   -- DETRAZIONI_PE_GODUTO,
importo_37,		   -- DETRAZIONI_LA_DOVUTO,
importo_38,		   -- DETRAZIONI_LA_GODUTO,
importo_8,		   -- DETRAZIONI_CO_DOVUTO,
importo_9,		   -- DETRAZIONI_CO_GODUTO,
importo_10,		   -- DETRAZIONI_FI_DOVUTO,
importo_11,		   -- DETRAZIONI_FI_GODUTO,
importo_12,		   -- DETRAZIONI_AL_DOVUTO,
importo_13,		   -- DETRAZIONI_AL_GODUTO,
importo_14,		   -- IM_DEDUZIONE_DOVUTO,
importo_15,		   -- IM_DEDUZIONE_GODUTO,
importo_16,		   -- IM_IRPEF_DOVUTO,
importo_17,		   -- IM_IRPEF_GODUTO,
attributo_28,	   -- FL_ACCANTONA_ADD_TERR
importo_18,		   -- IM_ADDREG_DOVUTO,
importo_19,		   -- IM_ADDREG_GODUTO,
importo_20,		   -- IM_ADDPROV_DOVUTO,
importo_21,		   -- IM_ADDPROV_GODUTO,
importo_22,		   -- IM_ADDCOM_DOVUTO,
importo_23,		   -- IM_ADDCOM_GODUTO,
importo_24,		   -- NUMERO_GIORNI,
importo_25,		   -- IMPONIBILE_IRPEF_LORDO,
importo_26,		   -- IMPONIBILE_IRPEF_NETTO,
attributo_24,	   -- CD_CDS_COMPENSO,
attributo_25,	   -- CD_UO_COMPENSO,
importo_27,		   -- ESERCIZIO_COMPENSO,
importo_28,		   -- PG_COMPENSO
importo_29,		   -- CD_TERZO_COMPENSO,
attributo_26,	   -- DS_TRATTAMENTO,
attributo_27,	   -- FL_SENZA_CALCOLI,
attributo_29,	   -- FL_PAGAM_FONDO_ECO,
importo_30,		 -- PG_MANDATO
importo_31,		 --IM_DEDUZIONE_FAMILY_DOVUTO,
importo_32,		 --IM_FAMILY_DOVUTO,
importo_33,		 --IM_DEDUZIONE_FAMILY_GODUTO,
importo_34,		 --IM_FAMILY_GODUTO,
attributo_31,		 --FL_CARICHI_FAMILIARI
attributo_33,            --FL_NO_DETRAZIONI_ALTRE,
attributo_34,		 --FL_NO_DETRAZIONI_FAMILY,
attributo_35,		 --FL_DETRAZIONI_ALTRI_TIPI,
importo_35,		 --IM_REDDITO_COMPLESSIVO,
importo_36,		 --IM_REDDITO_ABITAZ_PRINC,
attributo_36,	   	 --FL_APPLICA_DETR_PERS_MAX
attributo_37, 		--FL_DETRAZIONI_FAM_INTERO_ANNO
attributo_38,           --CODICE_FISCALE_ESTERNO
data_3,                 --DT_DA_COMPETENZA_ESTERNO
data_4,                 --DT_A_COMPETENZA_ESTERNO
importo_39,             --IMPONIBILE_FISCALE_ESTERNO
importo_40,             --IM_IRPEF_ESTERNO
importo_41,             --IM_ADDREG_ESTERNO
importo_42,             --IM_ADDPROV_ESTERNO
importo_43,             --IM_ADDCOM_ESTERNO
importo_44,             --DETRAZIONI_LA_ESTERNO
importo_45,             --DETRAZIONI_PE_ESTERNO
importo_46,             --DETRAZIONI_CO_ESTERNO
importo_47,             --DETRAZIONI_FI_ESTERNO
importo_48,             --DETRAZIONI_AL_ESTERNO
importo_49,             --NUMERO_GIORNI_ESTERNO
importo_50,             --PG_COMUNE_ADDCOM_ESTERNO
IMPORTO_51,              --IM_CORI_SOSPESO
IMPORTO_52,              --IM_CORI_SOSP_CONG
IMPORTO_53,              --AMMONTARE
attributo_39,            --FL_NO_CREDITO_IRPEF
attributo_40,            --FL_NO_CREDITO_CUNEO_IRPEF
attributo_41,            --FL_NO_DETR_CUNEO_IRPEF
IMPORT0_54,              --IM_CREDITO_IRPEF_GODUTO
IMPORTO_55,               --IM_CREDITO_IRPEF_DOVUTO
IMPORTO_59,              --IM_BONUS_IRPEF_GODUTO
IMPORTO_60,               --IM_BONUS_IRPEF_DOVUTO
IMPORTO_56,               --DETRAZIONE_RID_CUNEO_ESTERNO
IMPORTO_57,               --DETRAZIONE_RID_CUNEO_GODUTO
IMPORTO_58               --IM_BONUS_IRPEF_DOVUTO
from tmp_report_generico;
