--------------------------------------------------------
--  DDL for View VPG_ANA_PROGETTI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VPG_ANA_PROGETTI" ("ID", "CHIAVE", "TIPO", "SEQUENZA", "PG_PROGETTO", "PG_PROGETTO_PADRE", "CD_PROGETTO", "DS_PROGETTO", "CD_TIPO_PROGETTO", "CD_UNITA_ORGANIZZATIVA", "CD_RESPONSABILE_TERZO", "DT_INIZIO", "DT_FINE", "DT_PROROGA", "IMPORTO_PROGETTO", "IMPORTO_DIVISA", "CD_DIVISA", "NOTE", "STATO", "CONDIVISO", "DURATA_PROGETTO", "LIVELLO", "DS_RESPONSABILE_TERZO", "DS_TIPO_PROGETTO", "DS_UNITA_ORGANIZZATIVA", "TIPO_FASE") AS 
  SELECT  ID, CHIAVE, TIPO, SEQUENZA,
IMPORTO_1,      -- PG_PROGETTO
IMPORTO_2,      -- PG_PROGETTO_PADRE
ATTRIBUTO_1,    -- CD_PROGETTO
ATTRIBUTO_LONG_1,    -- DS_PROGETTO
ATTRIBUTO_3,    -- CD_TIPO_PROGETTO,
ATTRIBUTO_4,    -- CD_UNITA_ORGANIZZATIVA,
ATTRIBUTO_5,    -- CD_RESPONSABILE_TERZO
DATA_1,         -- DT_INIZIO
DATA_2,         -- DT_FINE
DATA_3,         -- DT_PROROGA
IMPORTO_3,      -- IMPORTO_PROGETTO
IMPORTO_4,      -- IMPORTO_DIVISA
ATTRIBUTO_6,    -- CD_DIVISA
ATTRIBUTO_7,    -- NOTE
ATTRIBUTO_8,    -- STATO
ATTRIBUTO_9,    -- CONDIVISO
ATTRIBUTO_10,   -- DURATA_PROGETTO
IMPORTO_5,      -- LIVELLO
ATTRIBUTO_11,   -- DS_RESPONSABILE_TERZO
ATTRIBUTO_12,   -- DS_TIPO_PROGETTO
ATTRIBUTO_13,   -- DS_UNITA_ORGANIZZATIVA
ATTRIBUTO_14    -- tipo_fase
FROM TMP_REPORT_GENERICO
;
