--------------------------------------------------------
--  DDL for View VPG_PDG_VARIAZIONE_DET
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VPG_PDG_VARIAZIONE_DET" ("ID", "CHIAVE", "TIPO", "SEQUENZA", "ESERCIZIO", "PG_VARIAZIONE_PDG", "DS_VARIAZIONE_PDG", "CD_CDR_PROPONENTE", "DS_CDR_PROPONENTE", "CD_CDR", "DS_CDR", "TI_GESTIONE", "TITOLO", "DS_TITOLO", "CATEGORIA", "DS_CATEGORIA", "STATO", "VARIAZIONE", "ASSESTATO_ENTRATA", "ASSESTATO_SPESA", "ID_DIPARTIMENTO", "CD_DIPARTIMENTO", "DS_DIPARTIMENTO") AS 
  select
	ID, CHIAVE, TIPO, SEQUENZA,
	IMPORTO_1, 		-- ESERCIZIO,
	IMPORTO_2,		-- PG_VARIAZIONE_PDG,
	ATTRIBUTO_LONG_1,	-- DS_VARIAZIONE_PDG,
	ATTRIBUTO_1,		-- CD_CDR_PROPONENTE,
	ATTRIBUTO_LONG_2,	-- DS_CDR_PROPONENTE,
 	ATTRIBUTO_2,		-- CD_CDR,
 	ATTRIBUTO_LONG_3,	-- DS_CDR,
 	ATTRIBUTO_3,		-- TI_GESTIONE,
 	ATTRIBUTO_4,		-- TITOLO,
 	ATTRIBUTO_LONG_4,	-- DS_TITOLO,
 	ATTRIBUTO_5,		-- CATEGORIA,
 	ATTRIBUTO_LONG_5,	-- DS_CATEGORIA,
 	ATTRIBUTO_6,		-- STATO,
 	IMPORTO_3,		-- VARIAZIONE,
 	IMPORTO_4,		-- ASSESTATO_ENTRATA,
 	IMPORTO_5,              -- ASSESTATO_SPESA,
 	IMPORTO_6,              -- ID_DIPARTIMENTO,
 	ATTRIBUTO_7,            -- CD_DIPARTIMENTO,
 	ATTRIBUTO_LONG_6        -- DS_DIPARTIMENTO
from tmp_report_generico
;
