--------------------------------------------------------
--  DDL for View VPG_SIT_PROGETTI_DIP_IST_UO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VPG_SIT_PROGETTI_DIP_IST_UO" ("ID", "CHIAVE", "TIPO", "SEQUENZA", "DIPARTIMENTO", "DES_DIP", "PROGETTO", "DES_PROG", "CD_RESPONSABILE", "DES_RESPONSABILE", "ISTITUTO", "DES_IST", "UO", "DES_UO", "PREV_PERS", "PREV_FUNZ", "PREV_INV", "PREV_PREST", "PREV_BORSE", "OBB_PERS", "OBB_FUNZ", "OBB_INV", "OBB_PREST", "OBB_BORSE", "PAG_PERS", "PAG_FUNZ", "PAG_INV", "PAG_PREST", "PAG_BORSE") AS 
  SELECT  ID, CHIAVE, TIPO, SEQUENZA,
ATTRIBUTO_1,    -- DIPARTIMENTO
ATTRIBUTO_2,    -- DES_DIP
ATTRIBUTO_3,    -- PROGETTO
ATTRIBUTO_LONG_1,    -- DES_PROG
IMPORTO_1,       -- CD_RESPONSABILE,
ATTRIBUTO_5,     -- DES_RESPONSABILE,
ATTRIBUTO_6,    -- ISTITUTO
ATTRIBUTO_7,    -- DES_IST
ATTRIBUTO_8,    -- UO
ATTRIBUTO_9,    -- DES_UO
IMPORTO_2,      -- PREVISIONE PERSONALE
IMPORTO_3,      -- PREVISIONE FUNZIONAMENTO
IMPORTO_4,      -- PREVISIONE INVESTIMENTO
IMPORTO_5,      -- PREVISIONE PRESTAZIONI
IMPORTO_6,      -- PREVISIONE DOTTORATI E BORSE
IMPORTO_7,      -- OBBLIGAZIONI PERSONALE
IMPORTO_8,      -- OBBLIGAZIONI FUNZIONAMENTO
IMPORTO_9,      -- OBBLIGAZIONI INVESTIMENTO
IMPORTO_10,     -- OBBLIGAZIONI PRESTAZIONI
IMPORTO_11,     -- OBBLIGAZIONI DOTTORATI E BORSE
IMPORTO_12,     -- PAGAMENTI PERSONALE
IMPORTO_13,     -- PAGAMENTI FUNZIONAMENTO
IMPORTO_14,     -- PAGAMENTI INVESTIMENTO
IMPORTO_15,     -- PAGAMENTI PRESTAZIONI
IMPORTO_16      -- PAGAMENTI DOTTORATI E BORSE
FROM TMP_REPORT_GENERICO
;
