--------------------------------------------------------
--  DDL for View VPG_PARTITARIO_COMPENSI
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VPG_PARTITARIO_COMPENSI" ("ID", "CHIAVE", "TIPO", "SEQUENZA", "TI_RECORD_L1", "TI_RECORD_L2", "CD_TERZO", "DENOMINAZIONE_SEDE", "VIA_RESIDENZA", "COMUNE_RESIDENZA", "CD_PROVINCIA_RESIDENZA", "DS_PROVINCIA_RESIDENZA", "FRAZIONE_RESIDENZA", "VIA_FISCALE", "COMUNE_FISCALE", "CD_PROVINCIA_FISCALE", "DS_PROVINCIA_FISCALE", "FRAZIONE_FISCALE", "CODICE_FISCALE", "PARTITA_IVA", "DATA_NASCITA", "COMUNE_NASCITA", "CD_PROVINCIA_NASCITA", "DS_PROVINCIA_NASCITA", "ALIQUOTA_FISCALE", "CD_ATTIVITA_INPS", "ALTRA_ASS_PREVID_INPS", "SEDE_INAIL", "MATRICOLA_INAIL", "CD_ANAG_CORR", "FL_NOTAXAREA", "FL_NOFAMILYAREA", "IM_DETRAZIONE_PERSONALE_ANAG", "DT_FINE_RAPPORTO", "CAUSALE_FINE_RAPPORTO", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "ESERCIZIO", "DS_CDS", "DS_UNITA_ORGANIZZATIVA", "PG_COMPENSO", "DS_COMPENSO", "FL_SENZA_CALCOLI", "ESERCIZIO_ORI_OBBLIGAZIONE", "PG_OBBLIGAZIONE", "PG_OBBLIGAZIONE_SCADENZARIO", "STATO_PAGAMENTO_FONDO_ECO", "PG_MANDATO", "DT_TRASMISSIONE", "STATO_COFI", "FL_CONGUAGLIATO", "CD_TI_RAPPORTO", "DS_TIPO_RAPPORTO", "CD_TRATTAMENTO", "DS_TRATTAMENTO", "DT_DA_COMPETENZA_COGE", "DT_A_COMPETENZA_COGE", "IMPONIBILE_FISCALE", "IM_LORDO_PERCIPIENTE", "IM_NETTO_PERCIPIENTE", "IM_CR_ENTE", "IM_CR_PERCIPIENTE", "CD_CONTRIBUTO_RITENUTA", "DS_CONTRIBUTO_RITENUTA", "TI_ENTE_PERCIPIENTE", "IMPONIBILE_LORDO", "IM_DEDUZIONE_IRPEF", "ALIQUOTA", "AMMONTARE_LORDO", "AMMONTARE", "IM_DEDUZIONE_FAMILY", "DETRAZIONI_PERSONALI", "DETRAZIONI_CONIUGE", "DETRAZIONI_FIGLI", "DETRAZIONI_ALTRI", "TOT_AMMONTARE_LORDO", "TOT_AMMONTARE", "TOT_IMPONIBILE_LORDO", "TOT_DETRAZIONI_PERSONALI", "TOT_DETRAZIONI_CONIUGE", "TOT_DETRAZIONI_FIGLI", "TOT_DETRAZIONI_ALTRI", "TOT_DEDUZIONE_IRPEF", "TOT_DEDUZIONE_FAMILY", "DETRAZIONI_RID_CUNEO", "TOT_DETRAZIONI_RID_CUNEO") AS
  select
--
-- Date: 04/12/2006
-- Version: 1.5
--
-- Vista per la stampa partitario compensi
-- Protocollo VPG
--
-- History:
--
-- Date: 6/11/2003
-- Version: 1.0
-- Creazione
--
-- Date: 14/11/2003
-- Version: 1.1
-- Aggiunta delle totalizzazione dei CORI per UO e complessivo per ENTE
--
-- Date: 26/11/2003
-- Version: 1.2
-- Fix mappatura campi
--
-- Date: 17/05/2005
-- Version: 1.3
-- Eliminati i campi delle detrazioni e aggunto il campo IM_DEDUZIONE_FAMILY
--
-- Date: 18/07/2006
-- Version: 1.4
-- Gestione Impegni/Accertamenti Residui:
-- gestito il nuovo campo ESERCIZIO_ORIGINALE
--
-- Date: 04/12/2006
-- Version: 1.5
-- Aggiunti campi TOT_DEDUZIONE_IRPEF,TOT_DEDUZIONE_FAMILY per la stampa partitario compensi
--
-- Body:
--
ID,
CHIAVE,
TIPO,
SEQUENZA,
ATTRIBUTO_1,      -- TI_RECORD_L1
ATTRIBUTO_2,   -- TI_RECORD_L2
IMPORTO_1,        -- CD_TERZO,
ATTRIBUTO_3,      -- DENOMINAZIONE_SEDE,
ATTRIBUTO_4,   -- VIA_RESIDENZA (VIA_SEDE||NUMERO_CIVICO_SEDE)
ATTRIBUTO_5,   -- COMUNE_RESIDENZA,
ATTRIBUTO_6,   -- CD_PROVICIA_RESIDENZA,
ATTRIBUTO_25,   -- DS_PROVINCIA_RESIDENZA,
ATTRIBUTO_26,   -- FRAZIONE_RESIDENZA,
ATTRIBUTO_7,   -- VIA_FISCALE,
ATTRIBUTO_8,   -- COMUNE_FISCALE,
ATTRIBUTO_9,   -- CD_PROVINCIA_FISCALE,
ATTRIBUTO_27,   -- DS_PROVINCIA_FISCALE,
ATTRIBUTO_28,   -- FRAZIONE_FISCALE,
ATTRIBUTO_10,   -- CODICE_FISCALE,
ATTRIBUTO_11,   -- PARTITA_IVA
DATA_1,     -- DATA_NASCITA,
ATTRIBUTO_12,   -- COMUNE_NASCITA
ATTRIBUTO_13,   -- CD_PROVINCIA_NASCITA
ATTRIBUTO_29,   -- DS_PROVINCIA_NASCITA,
IMPORTO_DEC8_2,   -- ALIQUOTA_FISCALE,
ATTRIBUTO_30,   -- CD_ATTIVITA_INPS,
ATTRIBUTO_37,   -- ALTRA_ASS_PREVID_INPS,
ATTRIBUTO_31,   -- SEDE_INAIL,
ATTRIBUTO_32,   -- MATRICOLA_INAIL,
IMPORTO_17,    -- CD_ANAG_CORR,
ATTRIBUTO_33,   -- FL_NOTAXAREA,
ATTRIBUTO_38,   -- FL_NOFAMILYAREA,
IMPORTO_18,    -- IM_DETRAZIONE_PERSONALE_ANAG,
DATA_5,     -- DT_FINE_RAPPORTO,
ATTRIBUTO_34,   -- CAUSALE_FINE_RAPPORTO,
ATTRIBUTO_14,   -- CD_CDS,
ATTRIBUTO_15,   -- CD_UNITA_ORGANIZZATIVA,
IMPORTO_2,    -- ESERCIZIO,
ATTRIBUTO_LONG_1, -- DS_CDS,
ATTRIBUTO_LONG_2, -- DS_UNITA_ORGANIZZATIVA
IMPORTO_3,    -- PG_COMPENSO
ATTRIBUTO_LONG_3, -- DS_COMPENSO,
ATTRIBUTO_16,   -- FL_SENZA_CALCOLI,
IMPORTO_31,    -- ESERCIZIO_ORI_OBBLIGAZIONE,
IMPORTO_4,    -- PG_OBBLIGAZIONE,
IMPORTO_5,    -- PG_OBBLIGAZIONE_SCADENZARIO,
ATTRIBUTO_35,   -- STATO_PAGAMENTO_FONDO_ECO
IMPORTO_6,    -- PG_MANDATO,
DATA_2,     -- DT_TRASMISSIONE,
ATTRIBUTO_36,   -- STATO_COFI
ATTRIBUTO_17,   -- FL_CONGUAGLIATO,
ATTRIBUTO_18,   -- CD_TI_RAPPORTO,
ATTRIBUTO_19,   -- DS_TIPO_RAPPORTO,
ATTRIBUTO_20,   -- CD_TRATTAMENTO,
ATTRIBUTO_21,   -- DS_TRATTAMENTO,
DATA_3,     -- DT_DA_COMPETENZA_COGE,
DATA_4,     -- DT_A_COMPETENZA_COGE,
IMPORTO_7,    -- IMPONIBILE_FISCALE,
IMPORTO_8,    -- IM_LORDO_PERCIPIENTE,
IMPORTO_9,    -- IM_NETTO_PERCIPIENTE,
IMPORTO_10,    -- IM_CR_ENTE,
IMPORTO_11,    -- IM_CR_PERCIPIENTE,
ATTRIBUTO_22,   -- CD_CONTRIBUTO_RITENUTA,
ATTRIBUTO_23,   -- DS_CONTRIBUTO_RITENUTA,
ATTRIBUTO_24,   -- TI_ENTE_PERCIPIENTE,
IMPORTO_13,    -- IMPONIBILE_LORDO,
IMPORTO_14,    -- IM_DEDUZIONE_IRPEF,
IMPORTO_DEC8_1,   -- ALIQUOTA,
IMPORTO_15,    -- AMMONTARE_LORDO,
IMPORTO_16,    -- AMMONTARE
IMPORTO_30,    -- IM_DEDUZIONE_FAMILY,
IMPORTO_19,    -- DETRAZIONI_PERSONALI,
IMPORTO_20,    -- DETRAZIONI_CONIUGE,
IMPORTO_21,    -- DETRAZIONI_FIGLI,
IMPORTO_22,    -- DETRAZIONI_ALTRI,
IMPORTO_23,    -- TOT_AMMONTARE_LORDO,
IMPORTO_24,    -- TOT_AMMONTARE,
IMPORTO_25,    -- TOT_IMPONIBILE_LORDO
IMPORTO_26,    -- TOT_IMPONIBILE_LORDO, , T,
IMPORTO_27,    -- TOT_DETRAZIONI_PERSONALI
IMPORTO_28,    -- TOT_DETRAZIONI_CONIUGE
IMPORTO_29,    -- TOT_DETRAZIONI_FIGLI,
IMPORTO_32,    -- TOT_DEDUZIONE_IRPEF,
IMPORTO_33,    -- TOT_DETRAZIONI_FIGLI,
IMPORTO_34,    -- DETRAZIONI_RID_CUNEO,
IMPORTO_35    -- TOT_DETRAZIONI_RID_CUNEO
from tmp_report_generico;
