--------------------------------------------------------
--  DDL for View VPG_DPDG_CDR_PRIMO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "VPG_DPDG_CDR_PRIMO" ("ID", "CHIAVE", "TIPO", "SEQUENZA", "DESCRIZIONE", "ESERCIZIO", "CD_CENTRO_RESPONSABILITA", "DS_CDR", "CD_UNITA_ORGANIZZATIVA", "DS_UNITA_ORGANIZZATIVA", "CD_CDS", "DS_CDS", "STATO", "ANNOTAZIONI", "FL_RIBALTATO_SU_AREA", "TI_APPARTENENZA", "TI_GESTIONE", "CD_ELEMENTO_VOCE", "DS_ELEMENTO_VOCE", "CD_TITOLO", "DS_TITOLO", "CD_CAPOCONTO", "DS_CAPOCONTO", "CD_FUNZIONE", "DS_FUNZIONE", "CD_NATURA", "DS_NATURA", "IM_RH_CCS_COSTI", "IM_RI_CCS_SPESE_ODC", "IM_RJ_CCS_SPESE_ODC_ALTRA_UO", "IM_RK_CCS_SPESE_OGC", "IM_RL_CCS_SPESE_OGC_ALTRA_UO", "IM_RM_CSS_AMMORTAMENTI", "IM_RN_CSS_RIMANENZE", "IM_RO_CSS_ALTRI_COSTI", "IM_RP_CSS_VERSO_ALTRO_CDR", "IM_RQ_SSC_COSTI_ODC", "IM_RR_SSC_COSTI_ODC_ALTRA_UO", "IM_RS_SSC_COSTI_OGC", "IM_RT_SSC_COSTI_OGC_ALTRA_UO", "IM_RU_SPESE_COSTI_ALTRUI", "IM_RV_PAGAMENTI", "IM_RAA_A2_COSTI_FINALI", "IM_RAB_A2_COSTI_ALTRO_CDR", "IM_RAC_A2_SPESE_ODC", "IM_RAD_A2_SPESE_ODC_ALTRA_UO", "IM_RAE_A2_SPESE_OGC", "IM_RAF_A2_SPESE_OGC_ALTRA_UO", "IM_RAG_A2_SPESE_COSTI_ALTRUI", "IM_RAH_A3_COSTI_FINALI", "IM_RAI_A3_COSTI_ALTRO_CDR", "IM_RAL_A3_SPESE_ODC", "IM_RAM_A3_SPESE_ODC_ALTRA_UO", "IM_RAN_A3_SPESE_OGC", "IM_RAO_A3_SPESE_OGC_ALTRA_UO", "IM_RAP_A3_SPESE_COSTI_ALTRUI", "IM_RA_RCE", "IM_RB_RSE", "IM_RC_ESR", "IM_RD_A2_RICAVI", "IM_RE_A2_ENTRATE", "IM_RF_A3_RICAVI", "IM_RG_A3_ENTRATE") AS 
  select
--
-- Date: 04/03/2003
-- Version: 1.1
--
-- Vista per la stampa del documento dei piani di gestione
-- Protocollo VPG
--
-- History:
--
-- Date: 22/02/2003
-- Version: 1.0
-- Creazione
--
-- Date: 04/03/2003
-- Version: 1.1
-- Gestione varchar2 con size > 200
--
-- Body:
--
ID,
CHIAVE,
TIPO,
SEQUENZA,
DESCRIZIONE,
IMPORTO_37,		-- ESERCIZIO
ATTRIBUTO_1, -- CD_CENTRO_RESPONSABILITA,
ATTRIBUTO_LONG_1, -- DS_CDR,
ATTRIBUTO_3, -- CD_UNITA_ORGANIZZATIVA,
ATTRIBUTO_LONG_2, -- DS_UNITA_ORGANIZZATIVA,
ATTRIBUTO_5, -- CD_CDS,
ATTRIBUTO_LONG_3, -- DS_CDS,
ATTRIBUTO_7, -- STATO,
ATTRIBUTO_LONG_4, -- ANNOTAZIONI,
ATTRIBUTO_9, -- FL_RIBALTATO_SU_AREA,
ATTRIBUTO_10, -- TI_APPARTENENZA,
ATTRIBUTO_11, -- TI_GESTIONE,
ATTRIBUTO_12, -- CD_ELEMENTO_VOCE,
ATTRIBUTO_13, -- DS_ELEMENTO_VOCE,
ATTRIBUTO_14, -- CD_TITOLO,
ATTRIBUTO_15, -- DS_TITOLO,
ATTRIBUTO_16, -- CD_CAPOCONTO,
ATTRIBUTO_LONG_5, -- DS_CAPOCONTO,
ATTRIBUTO_18, -- CD_FUNZIONE,
ATTRIBUTO_19, -- DS_FUNZIONE,
ATTRIBUTO_20, -- CD_NATURA,
ATTRIBUTO_21, -- DS_NATURA,
IMPORTO_1, -- IM_RH_CCS_COSTI,
IMPORTO_2, -- IM_RI_CCS_SPESE_ODC,
IMPORTO_3, -- IM_RJ_CCS_SPESE_ODC_ALTRA_UO,
IMPORTO_4, -- IM_RK_CCS_SPESE_OGC,
IMPORTO_5, -- IM_RL_CCS_SPESE_OGC_ALTRA_UO,
IMPORTO_6, -- IM_RM_CSS_AMMORTAMENTI,
IMPORTO_7, -- IM_RN_CSS_RIMANENZE,
IMPORTO_8, -- IM_RO_CSS_ALTRI_COSTI,
IMPORTO_9, -- IM_RP_CSS_VERSO_ALTRO_CDR,
IMPORTO_10, -- IM_RQ_SSC_COSTI_ODC,
IMPORTO_11, -- IM_RR_SSC_COSTI_ODC_ALTRA_UO,
IMPORTO_12, -- IM_RS_SSC_COSTI_OGC,
IMPORTO_13, -- IM_RT_SSC_COSTI_OGC_ALTRA_UO,
IMPORTO_14, -- IM_RU_SPESE_COSTI_ALTRUI,
IMPORTO_15, -- IM_RV_PAGAMENTI,
IMPORTO_16, -- IM_RAA_A2_COSTI_FINALI,
IMPORTO_17, -- IM_RAB_A2_COSTI_ALTRO_CDR,
IMPORTO_18, -- IM_RAC_A2_SPESE_ODC,
IMPORTO_19, -- IM_RAD_A2_SPESE_ODC_ALTRA_UO,
IMPORTO_20, -- IM_RAE_A2_SPESE_OGC,
IMPORTO_21, -- IM_RAF_A2_SPESE_OGC_ALTRA_UO,
IMPORTO_22, -- IM_RAG_A2_SPESE_COSTI_ALTRUI,
IMPORTO_23, -- IM_RAH_A3_COSTI_FINALI,
IMPORTO_24, -- IM_RAI_A3_COSTI_ALTRO_CDR,
IMPORTO_25, -- IM_RAL_A3_SPESE_ODC,
IMPORTO_26, -- IM_RAM_A3_SPESE_ODC_ALTRA_UO,
IMPORTO_27, -- IM_RAN_A3_SPESE_OGC,
IMPORTO_28, -- IM_RAO_A3_SPESE_OGC_ALTRA_UO,
IMPORTO_29, -- IM_RAP_A3_SPESE_COSTI_ALTRUI,
IMPORTO_30, -- IM_RA_RCE,
IMPORTO_31, -- IM_RB_RSE,
IMPORTO_32, -- IM_RC_ESR,
IMPORTO_33, -- IM_RD_A2_RICAVI,
IMPORTO_34, -- IM_RE_A2_ENTRATE,
IMPORTO_35, -- IM_RF_A3_RICAVI,
IMPORTO_36 -- IM_RG_A3_ENTRATE
from tmp_report_generico trp
;

   COMMENT ON TABLE "VPG_DPDG_CDR_PRIMO"  IS 'Vista per la stampa del documento dei piani di gestione
Protocollo VPG';
