//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.13 at 09:37:57 PM CET 
//


package it.siopeplus.giornaledicassa.custom;

import it.siopeplus.giornaledicassa.FlussoGiornaleDiCassa;

import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the it.siopeplus package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FlussoGiornaleDiCassa_QNAME = new QName("", "flusso_giornale_di_cassa");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.siopeplus
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link it.siopeplus.giornaledicassa.FlussoGiornaleDiCassa }
     */
    public FlussoGiornaleDiCassa createFlussoGiornaleDiCassa() {
        return new FlussoGiornaleDiCassa();
    }

}
