/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 09:58:11 AM CEST 
//


package it.cnr.contab.doccont00.intcass.xmlbnl;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * struttura bilancio
 * 
 * <p>Java class for bilancio complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bilancio">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codifica_bilancio">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="9999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="descrizione_codifica" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="gestione">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="RESIDUO"/>
 *               &lt;enumeration value="COMPETENZA"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="anno_residuo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;minInclusive value="1980"/>
 *               &lt;maxInclusive value="2099"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numero_articolo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;pattern value="[0-9]{1,3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="voce_economica" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;pattern value="[0-9]{1,3}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="importo_bilancio">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minInclusive value="0.01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bilancio", propOrder = {
    "codificaBilancio",
    "descrizioneCodifica",
    "gestione",
    "annoResiduo",
    "numeroArticolo",
    "voceEconomica",
    "importoBilancio"
})
public class Bilancio {

    @XmlElement(name = "codifica_bilancio")
    protected int codificaBilancio;
    @XmlElement(name = "descrizione_codifica")
    protected String descrizioneCodifica;
    @XmlElement(required = true)
    protected String gestione;
    @XmlElement(name = "anno_residuo")
    protected Integer annoResiduo;
    @XmlElement(name = "numero_articolo")
    protected BigInteger numeroArticolo;
    @XmlElement(name = "voce_economica")
    protected BigInteger voceEconomica;
    @XmlElement(name = "importo_bilancio", required = true)
    protected BigDecimal importoBilancio;

    /**
     * Gets the value of the codificaBilancio property.
     * 
     */
    public int getCodificaBilancio() {
        return codificaBilancio;
    }

    /**
     * Sets the value of the codificaBilancio property.
     * 
     */
    public void setCodificaBilancio(int value) {
        this.codificaBilancio = value;
    }

    /**
     * Gets the value of the descrizioneCodifica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescrizioneCodifica() {
        return descrizioneCodifica;
    }

    /**
     * Sets the value of the descrizioneCodifica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescrizioneCodifica(String value) {
        this.descrizioneCodifica = value;
    }

    /**
     * Gets the value of the gestione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGestione() {
        return gestione;
    }

    /**
     * Sets the value of the gestione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGestione(String value) {
        this.gestione = value;
    }

    /**
     * Gets the value of the annoResiduo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAnnoResiduo() {
        return annoResiduo;
    }

    /**
     * Sets the value of the annoResiduo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAnnoResiduo(Integer value) {
        this.annoResiduo = value;
    }

    /**
     * Gets the value of the numeroArticolo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumeroArticolo() {
        return numeroArticolo;
    }

    /**
     * Sets the value of the numeroArticolo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumeroArticolo(BigInteger value) {
        this.numeroArticolo = value;
    }

    /**
     * Gets the value of the voceEconomica property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVoceEconomica() {
        return voceEconomica;
    }

    /**
     * Sets the value of the voceEconomica property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVoceEconomica(BigInteger value) {
        this.voceEconomica = value;
    }

    /**
     * Gets the value of the importoBilancio property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImportoBilancio() {
        return importoBilancio;
    }

    /**
     * Sets the value of the importoBilancio property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImportoBilancio(BigDecimal value) {
        this.importoBilancio = value;
    }

}
