/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 09:58:11 AM CEST 
//


package it.cnr.contab.doccont00.intcass.xmlbnl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for creditore_effettivo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creditore_effettivo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anagrafica_creditore_effettivo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indirizzo_creditore_effettivo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cap_creditore_effettivo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="localita_creditore_effettivo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="provincia_creditore_effettivo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="stato_creditore_effettivo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="2"/>
 *               &lt;maxLength value="2"/>
 *               &lt;pattern value="[A-Z]{2,2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="partita_iva_creditore_effettivo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codice_fiscale_creditore_effettivo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creditore_effettivo", propOrder = {
    "anagraficaCreditoreEffettivo",
    "indirizzoCreditoreEffettivo",
    "capCreditoreEffettivo",
    "localitaCreditoreEffettivo",
    "provinciaCreditoreEffettivo",
    "statoCreditoreEffettivo",
    "partitaIvaCreditoreEffettivo",
    "codiceFiscaleCreditoreEffettivo"
})
public class CreditoreEffettivo {

    @XmlElement(name = "anagrafica_creditore_effettivo", required = true)
    protected String anagraficaCreditoreEffettivo;
    @XmlElement(name = "indirizzo_creditore_effettivo")
    protected String indirizzoCreditoreEffettivo;
    @XmlElement(name = "cap_creditore_effettivo")
    protected String capCreditoreEffettivo;
    @XmlElement(name = "localita_creditore_effettivo")
    protected String localitaCreditoreEffettivo;
    @XmlElement(name = "provincia_creditore_effettivo")
    protected String provinciaCreditoreEffettivo;
    @XmlElement(name = "stato_creditore_effettivo", required = true)
    protected String statoCreditoreEffettivo;
    @XmlElement(name = "partita_iva_creditore_effettivo")
    protected String partitaIvaCreditoreEffettivo;
    @XmlElement(name = "codice_fiscale_creditore_effettivo")
    protected String codiceFiscaleCreditoreEffettivo;

    /**
     * Gets the value of the anagraficaCreditoreEffettivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnagraficaCreditoreEffettivo() {
        return anagraficaCreditoreEffettivo;
    }

    /**
     * Sets the value of the anagraficaCreditoreEffettivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnagraficaCreditoreEffettivo(String value) {
        this.anagraficaCreditoreEffettivo = value;
    }

    /**
     * Gets the value of the indirizzoCreditoreEffettivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndirizzoCreditoreEffettivo() {
        return indirizzoCreditoreEffettivo;
    }

    /**
     * Sets the value of the indirizzoCreditoreEffettivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndirizzoCreditoreEffettivo(String value) {
        this.indirizzoCreditoreEffettivo = value;
    }

    /**
     * Gets the value of the capCreditoreEffettivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapCreditoreEffettivo() {
        return capCreditoreEffettivo;
    }

    /**
     * Sets the value of the capCreditoreEffettivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapCreditoreEffettivo(String value) {
        this.capCreditoreEffettivo = value;
    }

    /**
     * Gets the value of the localitaCreditoreEffettivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalitaCreditoreEffettivo() {
        return localitaCreditoreEffettivo;
    }

    /**
     * Sets the value of the localitaCreditoreEffettivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalitaCreditoreEffettivo(String value) {
        this.localitaCreditoreEffettivo = value;
    }

    /**
     * Gets the value of the provinciaCreditoreEffettivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinciaCreditoreEffettivo() {
        return provinciaCreditoreEffettivo;
    }

    /**
     * Sets the value of the provinciaCreditoreEffettivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinciaCreditoreEffettivo(String value) {
        this.provinciaCreditoreEffettivo = value;
    }

    /**
     * Gets the value of the statoCreditoreEffettivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatoCreditoreEffettivo() {
        return statoCreditoreEffettivo;
    }

    /**
     * Sets the value of the statoCreditoreEffettivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatoCreditoreEffettivo(String value) {
        this.statoCreditoreEffettivo = value;
    }

    /**
     * Gets the value of the partitaIvaCreditoreEffettivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartitaIvaCreditoreEffettivo() {
        return partitaIvaCreditoreEffettivo;
    }

    /**
     * Sets the value of the partitaIvaCreditoreEffettivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartitaIvaCreditoreEffettivo(String value) {
        this.partitaIvaCreditoreEffettivo = value;
    }

    /**
     * Gets the value of the codiceFiscaleCreditoreEffettivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscaleCreditoreEffettivo() {
        return codiceFiscaleCreditoreEffettivo;
    }

    /**
     * Sets the value of the codiceFiscaleCreditoreEffettivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscaleCreditoreEffettivo(String value) {
        this.codiceFiscaleCreditoreEffettivo = value;
    }

}
