/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 09:58:11 AM CEST 
//


package it.cnr.contab.doccont00.intcass.xmlbnl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * anagrafica soggetto autorizzato a rilasciare quietanza
 * 
 * <p>Java class for delegato complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="delegato">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anagrafica_delegato">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="indirizzo_delegato" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cap_delegato" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="16"/>
 *               &lt;pattern value="\d{5}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="localita_delegato" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="provincia_delegato" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="stato_delegato" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="2"/>
 *               &lt;maxLength value="2"/>
 *               &lt;pattern value="[A-Z]{2,2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codice_fiscale_delegato" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "delegato", propOrder = {
    "anagraficaDelegato",
    "indirizzoDelegato",
    "capDelegato",
    "localitaDelegato",
    "provinciaDelegato",
    "statoDelegato",
    "codiceFiscaleDelegato"
})
public class Delegato {

    @XmlElement(name = "anagrafica_delegato", required = true)
    protected String anagraficaDelegato;
    @XmlElement(name = "indirizzo_delegato")
    protected String indirizzoDelegato;
    @XmlElement(name = "cap_delegato")
    protected String capDelegato;
    @XmlElement(name = "localita_delegato")
    protected String localitaDelegato;
    @XmlElement(name = "provincia_delegato")
    protected String provinciaDelegato;
    @XmlElement(name = "stato_delegato")
    protected String statoDelegato;
    @XmlElement(name = "codice_fiscale_delegato")
    protected String codiceFiscaleDelegato;

    /**
     * Gets the value of the anagraficaDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnagraficaDelegato() {
        return anagraficaDelegato;
    }

    /**
     * Sets the value of the anagraficaDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnagraficaDelegato(String value) {
        this.anagraficaDelegato = value;
    }

    /**
     * Gets the value of the indirizzoDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndirizzoDelegato() {
        return indirizzoDelegato;
    }

    /**
     * Sets the value of the indirizzoDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndirizzoDelegato(String value) {
        this.indirizzoDelegato = value;
    }

    /**
     * Gets the value of the capDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapDelegato() {
        return capDelegato;
    }

    /**
     * Sets the value of the capDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapDelegato(String value) {
        this.capDelegato = value;
    }

    /**
     * Gets the value of the localitaDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalitaDelegato() {
        return localitaDelegato;
    }

    /**
     * Sets the value of the localitaDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalitaDelegato(String value) {
        this.localitaDelegato = value;
    }

    /**
     * Gets the value of the provinciaDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinciaDelegato() {
        return provinciaDelegato;
    }

    /**
     * Sets the value of the provinciaDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinciaDelegato(String value) {
        this.provinciaDelegato = value;
    }

    /**
     * Gets the value of the statoDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatoDelegato() {
        return statoDelegato;
    }

    /**
     * Sets the value of the statoDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatoDelegato(String value) {
        this.statoDelegato = value;
    }

    /**
     * Gets the value of the codiceFiscaleDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscaleDelegato() {
        return codiceFiscaleDelegato;
    }

    /**
     * Sets the value of the codiceFiscaleDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscaleDelegato(String value) {
        this.codiceFiscaleDelegato = value;
    }

}
