/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 09:58:11 AM CEST 
//


package it.cnr.contab.doccont00.intcass.xmlbnl;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for funzionario_delegato complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="funzionario_delegato">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codice_funzionario_delegato">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[A-Z|a-z||0-9]{16}"/>
 *               &lt;pattern value="[A-Z|a-z||0-9]{11}"/>
 *               &lt;pattern value="\d{1,7}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="importo_funzionario_delegato">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minInclusive value="0.01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tipologia_pagamento_funzionario_delegato">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numero_pagamento_funzionario_delegato">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "funzionario_delegato", propOrder = {
    "codiceFunzionarioDelegato",
    "importoFunzionarioDelegato",
    "tipologiaPagamentoFunzionarioDelegato",
    "numeroPagamentoFunzionarioDelegato"
})
public class FunzionarioDelegato {

    @XmlElement(name = "codice_funzionario_delegato", required = true)
    protected String codiceFunzionarioDelegato;
    @XmlElement(name = "importo_funzionario_delegato", required = true)
    protected BigDecimal importoFunzionarioDelegato;
    @XmlElement(name = "tipologia_pagamento_funzionario_delegato", required = true)
    protected String tipologiaPagamentoFunzionarioDelegato;
    @XmlElement(name = "numero_pagamento_funzionario_delegato", required = true)
    protected String numeroPagamentoFunzionarioDelegato;

    /**
     * Gets the value of the codiceFunzionarioDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFunzionarioDelegato() {
        return codiceFunzionarioDelegato;
    }

    /**
     * Sets the value of the codiceFunzionarioDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFunzionarioDelegato(String value) {
        this.codiceFunzionarioDelegato = value;
    }

    /**
     * Gets the value of the importoFunzionarioDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImportoFunzionarioDelegato() {
        return importoFunzionarioDelegato;
    }

    /**
     * Sets the value of the importoFunzionarioDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImportoFunzionarioDelegato(BigDecimal value) {
        this.importoFunzionarioDelegato = value;
    }

    /**
     * Gets the value of the tipologiaPagamentoFunzionarioDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipologiaPagamentoFunzionarioDelegato() {
        return tipologiaPagamentoFunzionarioDelegato;
    }

    /**
     * Sets the value of the tipologiaPagamentoFunzionarioDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipologiaPagamentoFunzionarioDelegato(String value) {
        this.tipologiaPagamentoFunzionarioDelegato = value;
    }

    /**
     * Gets the value of the numeroPagamentoFunzionarioDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroPagamentoFunzionarioDelegato() {
        return numeroPagamentoFunzionarioDelegato;
    }

    /**
     * Sets the value of the numeroPagamentoFunzionarioDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroPagamentoFunzionarioDelegato(String value) {
        this.numeroPagamentoFunzionarioDelegato = value;
    }

}
