/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 09:58:11 AM CEST 
//


package it.cnr.contab.doccont00.intcass.xmlbnl;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mandato_associato complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mandato_associato">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numero_mandato" type="{}OnlyNumMax7"/>
 *         &lt;element name="progressivo_beneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mandato_associato", propOrder = {
    "numeroMandato",
    "progressivoBeneficiario"
})
public class MandatoAssociato {

    @XmlElement(name = "numero_mandato")
    protected int numeroMandato;
    @XmlElement(name = "progressivo_beneficiario")
    protected BigInteger progressivoBeneficiario;

    /**
     * Gets the value of the numeroMandato property.
     * 
     */
    public int getNumeroMandato() {
        return numeroMandato;
    }

    /**
     * Sets the value of the numeroMandato property.
     * 
     */
    public void setNumeroMandato(int value) {
        this.numeroMandato = value;
    }

    /**
     * Gets the value of the progressivoBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProgressivoBeneficiario() {
        return progressivoBeneficiario;
    }

    /**
     * Sets the value of the progressivoBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProgressivoBeneficiario(BigInteger value) {
        this.progressivoBeneficiario = value;
    }

}
