/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 09:58:11 AM CEST 
//


package it.cnr.contab.doccont00.intcass.xmlbnl;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * struttura mandato
 * 
 * <p>Java class for mandato complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="mandato">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipo_operazione">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="INSERIMENTO"/>
 *               &lt;enumeration value="VARIAZIONE"/>
 *               &lt;enumeration value="ANNULLO"/>
 *               &lt;enumeration value="SOSTITUZIONE"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numero_mandato" type="{}OnlyNumMax7"/>
 *         &lt;element name="data_mandato">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="importo_mandato">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="15"/>
 *               &lt;fractionDigits value="2"/>
 *               &lt;minInclusive value="0.01"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="conto_evidenza" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="estremi_provvedimento_autorizzativo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="responsabile_provvedimento" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ufficio_responsabile" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bilancio" type="{}bilancio" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="funzionario_delegato" type="{}funzionario_delegato" minOccurs="0"/>
 *         &lt;element name="informazioni_beneficiario" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="progressivo_beneficiario" type="{}OnlyNumMax7"/>
 *                   &lt;element name="importo_beneficiario">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="15"/>
 *                         &lt;fractionDigits value="2"/>
 *                         &lt;minInclusive value="0.01"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="tipo_pagamento">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="CASSA"/>
 *                         &lt;enumeration value="BONIFICO BANCARIO E POSTALE"/>
 *                         &lt;enumeration value="ASSEGNO BANCARIO E POSTALE"/>
 *                         &lt;enumeration value="SEPA CREDIT TRANSFER"/>
 *                         &lt;enumeration value="ASSEGNO CIRCOLARE"/>
 *                         &lt;enumeration value="ACCREDITO CONTO CORRENTE POSTALE"/>
 *                         &lt;enumeration value="ACCREDITO TESORERIA PROVINCIALE STATO PER TAB A"/>
 *                         &lt;enumeration value="ACCREDITO TESORERIA PROVINCIALE STATO PER TAB B"/>
 *                         &lt;enumeration value="F24EP"/>
 *                         &lt;enumeration value="VAGLIA POSTALE"/>
 *                         &lt;enumeration value="VAGLIA TESORO"/>
 *                         &lt;enumeration value="REGOLARIZZAZIONE"/>
 *                         &lt;enumeration value="REGOLARIZZAZIONE ACCREDITO TESORERIA PROVINCIALE STATO PER TAB A"/>
 *                         &lt;enumeration value="REGOLARIZZAZIONE ACCREDITO TESORERIA PROVINCIALE STATO PER TAB B"/>
 *                         &lt;enumeration value="ADDEBITO PREAUTORIZZATO"/>
 *                         &lt;enumeration value="DISPOSIZIONE DOCUMENTO ESTERNO"/>
 *                         &lt;enumeration value="COMPENSAZIONE"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="impignorabili" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="2"/>
 *                         &lt;pattern value="[S,s]{1}[I,i]{1}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="frazionabile" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="2"/>
 *                         &lt;pattern value="[N,n]{1}[O,o]{1}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="gestione_provvisoria" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="2"/>
 *                         &lt;pattern value="[S,s]{1}[I,i]{1}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="data_esecuzione_pagamento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="data_scadenza_pagamento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="destinazione" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="LIBERA"/>
 *                         &lt;enumeration value="VINCOLATA"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="numero_conto_banca_italia_ente_ricevente" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="\d{1,7}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="tipo_contabilita_ente_ricevente" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="FRUTTIFERA"/>
 *                         &lt;enumeration value="INFRUTTIFERA"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="classificazione" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="codice_cgu">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="\d{4}"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="codice_cup" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="15"/>
 *                                   &lt;minLength value="15"/>
 *                                   &lt;pattern value="[A-Z|a-z||0-9|]{1,15}"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="codice_cpv" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;pattern value="\d{14}"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="importo">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;totalDigits value="15"/>
 *                                   &lt;fractionDigits value="2"/>
 *                                   &lt;minInclusive value="0.01"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="bilancio" type="{}bilancio" maxOccurs="10" minOccurs="0"/>
 *                   &lt;element name="bollo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="assoggettamento_bollo">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="ESENTE BOLLO"/>
 *                                   &lt;enumeration value="ASSOGGETTATO BOLLO A CARICO ENTE"/>
 *                                   &lt;enumeration value="ASSOGGETTATO BOLLO A CARICO BENEFICIARIO"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="causale_esenzione_bollo" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="spese" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="soggetto_destinatario_delle_spese">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="A CARICO ENTE"/>
 *                                   &lt;enumeration value="A CARICO BENEFICIARIO"/>
 *                                   &lt;enumeration value="ESENTE"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="natura_pagamento" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="causale_esenzione_spese" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="0"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="beneficiario" type="{}beneficiario"/>
 *                   &lt;element name="delegato" type="{}delegato" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="creditore_effettivo" type="{}creditore_effettivo" minOccurs="0"/>
 *                   &lt;element name="piazzatura" type="{}piazzatura" minOccurs="0"/>
 *                   &lt;element name="sepa_credit_transfer" type="{}sepa_credit_transfer" minOccurs="0"/>
 *                   &lt;element name="codice_versante" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="10"/>
 *                         &lt;maxLength value="10"/>
 *                         &lt;pattern value="[A-Z|a-z]{1}[|0-9]{9}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="causale">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;whiteSpace value="collapse"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="sospeso" maxOccurs="1000" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="numero_provvisorio" type="{}OnlyNumMax18"/>
 *                             &lt;element name="importo_provvisorio">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                   &lt;totalDigits value="15"/>
 *                                   &lt;fractionDigits value="2"/>
 *                                   &lt;minInclusive value="0.01"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ritenute" type="{}ritenute" maxOccurs="30" minOccurs="0"/>
 *                   &lt;element name="informazioni_aggiuntive" type="{}informazioni_aggiuntive" minOccurs="0"/>
 *                   &lt;element name="sostituzione_mandato" type="{}sostituzione_mandato" minOccurs="0"/>
 *                   &lt;element name="dati_a_disposizione_ente_beneficiario" type="{}anyTAG" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dati_a_disposizione_ente_mandato" type="{}anyTAG" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mandato", propOrder = {
    "tipoOperazione",
    "numeroMandato",
    "dataMandato",
    "importoMandato",
    "contoEvidenza",
    "estremiProvvedimentoAutorizzativo",
    "responsabileProvvedimento",
    "ufficioResponsabile",
    "bilancio",
    "funzionarioDelegato",
    "informazioniBeneficiario",
    "datiADisposizioneEnteMandato"
})
public class Mandato {

    @XmlElement(name = "tipo_operazione", required = true)
    protected String tipoOperazione;
    @XmlElement(name = "numero_mandato")
    protected int numeroMandato;
    @XmlElement(name = "data_mandato", required = true)
    protected XMLGregorianCalendar dataMandato;
    @XmlElement(name = "importo_mandato", required = true)
    protected BigDecimal importoMandato;
    @XmlElement(name = "conto_evidenza")
    protected String contoEvidenza;
    @XmlElement(name = "estremi_provvedimento_autorizzativo")
    protected String estremiProvvedimentoAutorizzativo;
    @XmlElement(name = "responsabile_provvedimento")
    protected String responsabileProvvedimento;
    @XmlElement(name = "ufficio_responsabile")
    protected String ufficioResponsabile;
    protected List<Bilancio> bilancio;
    @XmlElement(name = "funzionario_delegato")
    protected FunzionarioDelegato funzionarioDelegato;
    @XmlElement(name = "informazioni_beneficiario", required = true)
    protected List<Mandato.InformazioniBeneficiario> informazioniBeneficiario;
    @XmlElement(name = "dati_a_disposizione_ente_mandato")
    protected AnyTAG datiADisposizioneEnteMandato;

    /**
     * Gets the value of the tipoOperazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoOperazione() {
        return tipoOperazione;
    }

    /**
     * Sets the value of the tipoOperazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoOperazione(String value) {
        this.tipoOperazione = value;
    }

    /**
     * Gets the value of the numeroMandato property.
     * 
     */
    public int getNumeroMandato() {
        return numeroMandato;
    }

    /**
     * Sets the value of the numeroMandato property.
     * 
     */
    public void setNumeroMandato(int value) {
        this.numeroMandato = value;
    }

    /**
     * Gets the value of the dataMandato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataMandato() {
        return dataMandato;
    }

    /**
     * Sets the value of the dataMandato property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataMandato(XMLGregorianCalendar value) {
        this.dataMandato = value;
    }

    /**
     * Gets the value of the importoMandato property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getImportoMandato() {
        return importoMandato;
    }

    /**
     * Sets the value of the importoMandato property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setImportoMandato(BigDecimal value) {
        this.importoMandato = value;
    }

    /**
     * Gets the value of the contoEvidenza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContoEvidenza() {
        return contoEvidenza;
    }

    /**
     * Sets the value of the contoEvidenza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContoEvidenza(String value) {
        this.contoEvidenza = value;
    }

    /**
     * Gets the value of the estremiProvvedimentoAutorizzativo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstremiProvvedimentoAutorizzativo() {
        return estremiProvvedimentoAutorizzativo;
    }

    /**
     * Sets the value of the estremiProvvedimentoAutorizzativo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstremiProvvedimentoAutorizzativo(String value) {
        this.estremiProvvedimentoAutorizzativo = value;
    }

    /**
     * Gets the value of the responsabileProvvedimento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsabileProvvedimento() {
        return responsabileProvvedimento;
    }

    /**
     * Sets the value of the responsabileProvvedimento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsabileProvvedimento(String value) {
        this.responsabileProvvedimento = value;
    }

    /**
     * Gets the value of the ufficioResponsabile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUfficioResponsabile() {
        return ufficioResponsabile;
    }

    /**
     * Sets the value of the ufficioResponsabile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUfficioResponsabile(String value) {
        this.ufficioResponsabile = value;
    }

    /**
     * Gets the value of the bilancio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bilancio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBilancio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bilancio }
     * 
     * 
     */
    public List<Bilancio> getBilancio() {
        if (bilancio == null) {
            bilancio = new ArrayList<Bilancio>();
        }
        return this.bilancio;
    }

    /**
     * Gets the value of the funzionarioDelegato property.
     * 
     * @return
     *     possible object is
     *     {@link FunzionarioDelegato }
     *     
     */
    public FunzionarioDelegato getFunzionarioDelegato() {
        return funzionarioDelegato;
    }

    /**
     * Sets the value of the funzionarioDelegato property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunzionarioDelegato }
     *     
     */
    public void setFunzionarioDelegato(FunzionarioDelegato value) {
        this.funzionarioDelegato = value;
    }

    /**
     * Gets the value of the informazioniBeneficiario property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the informazioniBeneficiario property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInformazioniBeneficiario().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Mandato.InformazioniBeneficiario }
     * 
     * 
     */
    public List<Mandato.InformazioniBeneficiario> getInformazioniBeneficiario() {
        if (informazioniBeneficiario == null) {
            informazioniBeneficiario = new ArrayList<Mandato.InformazioniBeneficiario>();
        }
        return this.informazioniBeneficiario;
    }

    /**
     * Gets the value of the datiADisposizioneEnteMandato property.
     * 
     * @return
     *     possible object is
     *     {@link AnyTAG }
     *     
     */
    public AnyTAG getDatiADisposizioneEnteMandato() {
        return datiADisposizioneEnteMandato;
    }

    /**
     * Sets the value of the datiADisposizioneEnteMandato property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyTAG }
     *     
     */
    public void setDatiADisposizioneEnteMandato(AnyTAG value) {
        this.datiADisposizioneEnteMandato = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="progressivo_beneficiario" type="{}OnlyNumMax7"/>
     *         &lt;element name="importo_beneficiario">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="15"/>
     *               &lt;fractionDigits value="2"/>
     *               &lt;minInclusive value="0.01"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="tipo_pagamento">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="CASSA"/>
     *               &lt;enumeration value="BONIFICO BANCARIO E POSTALE"/>
     *               &lt;enumeration value="ASSEGNO BANCARIO E POSTALE"/>
     *               &lt;enumeration value="SEPA CREDIT TRANSFER"/>
     *               &lt;enumeration value="ASSEGNO CIRCOLARE"/>
     *               &lt;enumeration value="ACCREDITO CONTO CORRENTE POSTALE"/>
     *               &lt;enumeration value="ACCREDITO TESORERIA PROVINCIALE STATO PER TAB A"/>
     *               &lt;enumeration value="ACCREDITO TESORERIA PROVINCIALE STATO PER TAB B"/>
     *               &lt;enumeration value="F24EP"/>
     *               &lt;enumeration value="VAGLIA POSTALE"/>
     *               &lt;enumeration value="VAGLIA TESORO"/>
     *               &lt;enumeration value="REGOLARIZZAZIONE"/>
     *               &lt;enumeration value="REGOLARIZZAZIONE ACCREDITO TESORERIA PROVINCIALE STATO PER TAB A"/>
     *               &lt;enumeration value="REGOLARIZZAZIONE ACCREDITO TESORERIA PROVINCIALE STATO PER TAB B"/>
     *               &lt;enumeration value="ADDEBITO PREAUTORIZZATO"/>
     *               &lt;enumeration value="DISPOSIZIONE DOCUMENTO ESTERNO"/>
     *               &lt;enumeration value="COMPENSAZIONE"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="impignorabili" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="2"/>
     *               &lt;pattern value="[S,s]{1}[I,i]{1}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="frazionabile" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="2"/>
     *               &lt;pattern value="[N,n]{1}[O,o]{1}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="gestione_provvisoria" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="2"/>
     *               &lt;pattern value="[S,s]{1}[I,i]{1}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="data_esecuzione_pagamento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="data_scadenza_pagamento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="destinazione" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="LIBERA"/>
     *               &lt;enumeration value="VINCOLATA"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="numero_conto_banca_italia_ente_ricevente" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="\d{1,7}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="tipo_contabilita_ente_ricevente" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="FRUTTIFERA"/>
     *               &lt;enumeration value="INFRUTTIFERA"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="classificazione" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="codice_cgu">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="\d{4}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="codice_cup" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="15"/>
     *                         &lt;minLength value="15"/>
     *                         &lt;pattern value="[A-Z|a-z||0-9|]{1,15}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="codice_cpv" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;pattern value="\d{14}"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="importo">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;totalDigits value="15"/>
     *                         &lt;fractionDigits value="2"/>
     *                         &lt;minInclusive value="0.01"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="bilancio" type="{}bilancio" maxOccurs="10" minOccurs="0"/>
     *         &lt;element name="bollo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="assoggettamento_bollo">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="ESENTE BOLLO"/>
     *                         &lt;enumeration value="ASSOGGETTATO BOLLO A CARICO ENTE"/>
     *                         &lt;enumeration value="ASSOGGETTATO BOLLO A CARICO BENEFICIARIO"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="causale_esenzione_bollo" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="spese" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="soggetto_destinatario_delle_spese">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="A CARICO ENTE"/>
     *                         &lt;enumeration value="A CARICO BENEFICIARIO"/>
     *                         &lt;enumeration value="ESENTE"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="natura_pagamento" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="causale_esenzione_spese" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="0"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="beneficiario" type="{}beneficiario"/>
     *         &lt;element name="delegato" type="{}delegato" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="creditore_effettivo" type="{}creditore_effettivo" minOccurs="0"/>
     *         &lt;element name="piazzatura" type="{}piazzatura" minOccurs="0"/>
     *         &lt;element name="sepa_credit_transfer" type="{}sepa_credit_transfer" minOccurs="0"/>
     *         &lt;element name="codice_versante" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="10"/>
     *               &lt;maxLength value="10"/>
     *               &lt;pattern value="[A-Z|a-z]{1}[|0-9]{9}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="causale">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;whiteSpace value="collapse"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="sospeso" maxOccurs="1000" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="numero_provvisorio" type="{}OnlyNumMax18"/>
     *                   &lt;element name="importo_provvisorio">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                         &lt;totalDigits value="15"/>
     *                         &lt;fractionDigits value="2"/>
     *                         &lt;minInclusive value="0.01"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ritenute" type="{}ritenute" maxOccurs="30" minOccurs="0"/>
     *         &lt;element name="informazioni_aggiuntive" type="{}informazioni_aggiuntive" minOccurs="0"/>
     *         &lt;element name="sostituzione_mandato" type="{}sostituzione_mandato" minOccurs="0"/>
     *         &lt;element name="dati_a_disposizione_ente_beneficiario" type="{}anyTAG" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "progressivoBeneficiario",
        "importoBeneficiario",
        "tipoPagamento",
        "impignorabili",
        "frazionabile",
        "gestioneProvvisoria",
        "dataEsecuzionePagamento",
        "dataScadenzaPagamento",
        "destinazione",
        "numeroContoBancaItaliaEnteRicevente",
        "tipoContabilitaEnteRicevente",
        "classificazione",
        "bilancio",
        "bollo",
        "spese",
        "beneficiario",
        "delegato",
        "creditoreEffettivo",
        "piazzatura",
        "sepaCreditTransfer",
        "codiceVersante",
        "causale",
        "sospeso",
        "ritenute",
        "informazioniAggiuntive",
        "sostituzioneMandato",
        "datiADisposizioneEnteBeneficiario"
    })
    public static class InformazioniBeneficiario {

        @XmlElement(name = "progressivo_beneficiario")
        protected int progressivoBeneficiario;
        @XmlElement(name = "importo_beneficiario", required = true)
        protected BigDecimal importoBeneficiario;
        @XmlElement(name = "tipo_pagamento", required = true)
        protected String tipoPagamento;
        protected String impignorabili;
        protected String frazionabile;
        @XmlElement(name = "gestione_provvisoria")
        protected String gestioneProvvisoria;
        @XmlElement(name = "data_esecuzione_pagamento")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataEsecuzionePagamento;
        @XmlElement(name = "data_scadenza_pagamento")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar dataScadenzaPagamento;
        protected String destinazione;
        @XmlElement(name = "numero_conto_banca_italia_ente_ricevente")
        protected String numeroContoBancaItaliaEnteRicevente;
        @XmlElement(name = "tipo_contabilita_ente_ricevente")
        protected String tipoContabilitaEnteRicevente;
        protected List<Mandato.InformazioniBeneficiario.Classificazione> classificazione;
        protected List<Bilancio> bilancio;
        @XmlElement(required = true)
        protected Mandato.InformazioniBeneficiario.Bollo bollo;
        protected Mandato.InformazioniBeneficiario.Spese spese;
        @XmlElement(required = true)
        protected Beneficiario beneficiario;
        protected List<Delegato> delegato;
        @XmlElement(name = "creditore_effettivo")
        protected CreditoreEffettivo creditoreEffettivo;
        protected Piazzatura piazzatura;
        @XmlElement(name = "sepa_credit_transfer")
        protected SepaCreditTransfer sepaCreditTransfer;
        @XmlElement(name = "codice_versante")
        protected String codiceVersante;
        @XmlElement(required = true)
        protected String causale;
        protected List<Mandato.InformazioniBeneficiario.Sospeso> sospeso;
        protected List<Ritenute> ritenute;
        @XmlElement(name = "informazioni_aggiuntive")
        protected InformazioniAggiuntive informazioniAggiuntive;
        @XmlElement(name = "sostituzione_mandato")
        protected SostituzioneMandato sostituzioneMandato;
        @XmlElement(name = "dati_a_disposizione_ente_beneficiario")
        protected AnyTAG datiADisposizioneEnteBeneficiario;

        /**
         * Gets the value of the progressivoBeneficiario property.
         * 
         */
        public int getProgressivoBeneficiario() {
            return progressivoBeneficiario;
        }

        /**
         * Sets the value of the progressivoBeneficiario property.
         * 
         */
        public void setProgressivoBeneficiario(int value) {
            this.progressivoBeneficiario = value;
        }

        /**
         * Gets the value of the importoBeneficiario property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getImportoBeneficiario() {
            return importoBeneficiario;
        }

        /**
         * Sets the value of the importoBeneficiario property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setImportoBeneficiario(BigDecimal value) {
            this.importoBeneficiario = value;
        }

        /**
         * Gets the value of the tipoPagamento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoPagamento() {
            return tipoPagamento;
        }

        /**
         * Sets the value of the tipoPagamento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoPagamento(String value) {
            this.tipoPagamento = value;
        }

        /**
         * Gets the value of the impignorabili property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImpignorabili() {
            return impignorabili;
        }

        /**
         * Sets the value of the impignorabili property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImpignorabili(String value) {
            this.impignorabili = value;
        }

        /**
         * Gets the value of the frazionabile property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFrazionabile() {
            return frazionabile;
        }

        /**
         * Sets the value of the frazionabile property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFrazionabile(String value) {
            this.frazionabile = value;
        }

        /**
         * Gets the value of the gestioneProvvisoria property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGestioneProvvisoria() {
            return gestioneProvvisoria;
        }

        /**
         * Sets the value of the gestioneProvvisoria property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGestioneProvvisoria(String value) {
            this.gestioneProvvisoria = value;
        }

        /**
         * Gets the value of the dataEsecuzionePagamento property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataEsecuzionePagamento() {
            return dataEsecuzionePagamento;
        }

        /**
         * Sets the value of the dataEsecuzionePagamento property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataEsecuzionePagamento(XMLGregorianCalendar value) {
            this.dataEsecuzionePagamento = value;
        }

        /**
         * Gets the value of the dataScadenzaPagamento property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataScadenzaPagamento() {
            return dataScadenzaPagamento;
        }

        /**
         * Sets the value of the dataScadenzaPagamento property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataScadenzaPagamento(XMLGregorianCalendar value) {
            this.dataScadenzaPagamento = value;
        }

        /**
         * Gets the value of the destinazione property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinazione() {
            return destinazione;
        }

        /**
         * Sets the value of the destinazione property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinazione(String value) {
            this.destinazione = value;
        }

        /**
         * Gets the value of the numeroContoBancaItaliaEnteRicevente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumeroContoBancaItaliaEnteRicevente() {
            return numeroContoBancaItaliaEnteRicevente;
        }

        /**
         * Sets the value of the numeroContoBancaItaliaEnteRicevente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumeroContoBancaItaliaEnteRicevente(String value) {
            this.numeroContoBancaItaliaEnteRicevente = value;
        }

        /**
         * Gets the value of the tipoContabilitaEnteRicevente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoContabilitaEnteRicevente() {
            return tipoContabilitaEnteRicevente;
        }

        /**
         * Sets the value of the tipoContabilitaEnteRicevente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoContabilitaEnteRicevente(String value) {
            this.tipoContabilitaEnteRicevente = value;
        }

        /**
         * Gets the value of the classificazione property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the classificazione property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClassificazione().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Mandato.InformazioniBeneficiario.Classificazione }
         * 
         * 
         */
        public List<Mandato.InformazioniBeneficiario.Classificazione> getClassificazione() {
            if (classificazione == null) {
                classificazione = new ArrayList<Mandato.InformazioniBeneficiario.Classificazione>();
            }
            return this.classificazione;
        }

        /**
         * Gets the value of the bilancio property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bilancio property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBilancio().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Bilancio }
         * 
         * 
         */
        public List<Bilancio> getBilancio() {
            if (bilancio == null) {
                bilancio = new ArrayList<Bilancio>();
            }
            return this.bilancio;
        }

        /**
         * Gets the value of the bollo property.
         * 
         * @return
         *     possible object is
         *     {@link Mandato.InformazioniBeneficiario.Bollo }
         *     
         */
        public Mandato.InformazioniBeneficiario.Bollo getBollo() {
            return bollo;
        }

        /**
         * Sets the value of the bollo property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mandato.InformazioniBeneficiario.Bollo }
         *     
         */
        public void setBollo(Mandato.InformazioniBeneficiario.Bollo value) {
            this.bollo = value;
        }

        /**
         * Gets the value of the spese property.
         * 
         * @return
         *     possible object is
         *     {@link Mandato.InformazioniBeneficiario.Spese }
         *     
         */
        public Mandato.InformazioniBeneficiario.Spese getSpese() {
            return spese;
        }

        /**
         * Sets the value of the spese property.
         * 
         * @param value
         *     allowed object is
         *     {@link Mandato.InformazioniBeneficiario.Spese }
         *     
         */
        public void setSpese(Mandato.InformazioniBeneficiario.Spese value) {
            this.spese = value;
        }

        /**
         * Gets the value of the beneficiario property.
         * 
         * @return
         *     possible object is
         *     {@link Beneficiario }
         *     
         */
        public Beneficiario getBeneficiario() {
            return beneficiario;
        }

        /**
         * Sets the value of the beneficiario property.
         * 
         * @param value
         *     allowed object is
         *     {@link Beneficiario }
         *     
         */
        public void setBeneficiario(Beneficiario value) {
            this.beneficiario = value;
        }

        /**
         * Gets the value of the delegato property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the delegato property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDelegato().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Delegato }
         * 
         * 
         */
        public List<Delegato> getDelegato() {
            if (delegato == null) {
                delegato = new ArrayList<Delegato>();
            }
            return this.delegato;
        }

        /**
         * Gets the value of the creditoreEffettivo property.
         * 
         * @return
         *     possible object is
         *     {@link CreditoreEffettivo }
         *     
         */
        public CreditoreEffettivo getCreditoreEffettivo() {
            return creditoreEffettivo;
        }

        /**
         * Sets the value of the creditoreEffettivo property.
         * 
         * @param value
         *     allowed object is
         *     {@link CreditoreEffettivo }
         *     
         */
        public void setCreditoreEffettivo(CreditoreEffettivo value) {
            this.creditoreEffettivo = value;
        }

        /**
         * Gets the value of the piazzatura property.
         * 
         * @return
         *     possible object is
         *     {@link Piazzatura }
         *     
         */
        public Piazzatura getPiazzatura() {
            return piazzatura;
        }

        /**
         * Sets the value of the piazzatura property.
         * 
         * @param value
         *     allowed object is
         *     {@link Piazzatura }
         *     
         */
        public void setPiazzatura(Piazzatura value) {
            this.piazzatura = value;
        }

        /**
         * Gets the value of the sepaCreditTransfer property.
         * 
         * @return
         *     possible object is
         *     {@link SepaCreditTransfer }
         *     
         */
        public SepaCreditTransfer getSepaCreditTransfer() {
            return sepaCreditTransfer;
        }

        /**
         * Sets the value of the sepaCreditTransfer property.
         * 
         * @param value
         *     allowed object is
         *     {@link SepaCreditTransfer }
         *     
         */
        public void setSepaCreditTransfer(SepaCreditTransfer value) {
            this.sepaCreditTransfer = value;
        }

        /**
         * Gets the value of the codiceVersante property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodiceVersante() {
            return codiceVersante;
        }

        /**
         * Sets the value of the codiceVersante property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodiceVersante(String value) {
            this.codiceVersante = value;
        }

        /**
         * Gets the value of the causale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCausale() {
            return causale;
        }

        /**
         * Sets the value of the causale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCausale(String value) {
            this.causale = value;
        }

        /**
         * Gets the value of the sospeso property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the sospeso property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSospeso().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Mandato.InformazioniBeneficiario.Sospeso }
         * 
         * 
         */
        public List<Mandato.InformazioniBeneficiario.Sospeso> getSospeso() {
            if (sospeso == null) {
                sospeso = new ArrayList<Mandato.InformazioniBeneficiario.Sospeso>();
            }
            return this.sospeso;
        }

        /**
         * Gets the value of the ritenute property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ritenute property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRitenute().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Ritenute }
         * 
         * 
         */
        public List<Ritenute> getRitenute() {
            if (ritenute == null) {
                ritenute = new ArrayList<Ritenute>();
            }
            return this.ritenute;
        }

        /**
         * Gets the value of the informazioniAggiuntive property.
         * 
         * @return
         *     possible object is
         *     {@link InformazioniAggiuntive }
         *     
         */
        public InformazioniAggiuntive getInformazioniAggiuntive() {
            return informazioniAggiuntive;
        }

        /**
         * Sets the value of the informazioniAggiuntive property.
         * 
         * @param value
         *     allowed object is
         *     {@link InformazioniAggiuntive }
         *     
         */
        public void setInformazioniAggiuntive(InformazioniAggiuntive value) {
            this.informazioniAggiuntive = value;
        }

        /**
         * Gets the value of the sostituzioneMandato property.
         * 
         * @return
         *     possible object is
         *     {@link SostituzioneMandato }
         *     
         */
        public SostituzioneMandato getSostituzioneMandato() {
            return sostituzioneMandato;
        }

        /**
         * Sets the value of the sostituzioneMandato property.
         * 
         * @param value
         *     allowed object is
         *     {@link SostituzioneMandato }
         *     
         */
        public void setSostituzioneMandato(SostituzioneMandato value) {
            this.sostituzioneMandato = value;
        }

        /**
         * Gets the value of the datiADisposizioneEnteBeneficiario property.
         * 
         * @return
         *     possible object is
         *     {@link AnyTAG }
         *     
         */
        public AnyTAG getDatiADisposizioneEnteBeneficiario() {
            return datiADisposizioneEnteBeneficiario;
        }

        /**
         * Sets the value of the datiADisposizioneEnteBeneficiario property.
         * 
         * @param value
         *     allowed object is
         *     {@link AnyTAG }
         *     
         */
        public void setDatiADisposizioneEnteBeneficiario(AnyTAG value) {
            this.datiADisposizioneEnteBeneficiario = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="assoggettamento_bollo">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="ESENTE BOLLO"/>
         *               &lt;enumeration value="ASSOGGETTATO BOLLO A CARICO ENTE"/>
         *               &lt;enumeration value="ASSOGGETTATO BOLLO A CARICO BENEFICIARIO"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="causale_esenzione_bollo" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "assoggettamentoBollo",
            "causaleEsenzioneBollo"
        })
        public static class Bollo {

            @XmlElement(name = "assoggettamento_bollo", required = true)
            protected String assoggettamentoBollo;
            @XmlElement(name = "causale_esenzione_bollo")
            protected String causaleEsenzioneBollo;

            /**
             * Gets the value of the assoggettamentoBollo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAssoggettamentoBollo() {
                return assoggettamentoBollo;
            }

            /**
             * Sets the value of the assoggettamentoBollo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAssoggettamentoBollo(String value) {
                this.assoggettamentoBollo = value;
            }

            /**
             * Gets the value of the causaleEsenzioneBollo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCausaleEsenzioneBollo() {
                return causaleEsenzioneBollo;
            }

            /**
             * Sets the value of the causaleEsenzioneBollo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCausaleEsenzioneBollo(String value) {
                this.causaleEsenzioneBollo = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="codice_cgu">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="\d{4}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="codice_cup" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="15"/>
         *               &lt;minLength value="15"/>
         *               &lt;pattern value="[A-Z|a-z||0-9|]{1,15}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="codice_cpv" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="\d{14}"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="importo">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;totalDigits value="15"/>
         *               &lt;fractionDigits value="2"/>
         *               &lt;minInclusive value="0.01"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "codiceCgu",
            "codiceCup",
            "codiceCpv",
            "importo"
        })
        public static class Classificazione {

            @XmlElement(name = "codice_cgu", required = true)
            protected String codiceCgu;
            @XmlElement(name = "codice_cup")
            protected String codiceCup;
            @XmlElement(name = "codice_cpv")
            protected String codiceCpv;
            @XmlElement(required = true)
            protected BigDecimal importo;

            /**
             * Gets the value of the codiceCgu property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodiceCgu() {
                return codiceCgu;
            }

            /**
             * Sets the value of the codiceCgu property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodiceCgu(String value) {
                this.codiceCgu = value;
            }

            /**
             * Gets the value of the codiceCup property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodiceCup() {
                return codiceCup;
            }

            /**
             * Sets the value of the codiceCup property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodiceCup(String value) {
                this.codiceCup = value;
            }

            /**
             * Gets the value of the codiceCpv property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodiceCpv() {
                return codiceCpv;
            }

            /**
             * Sets the value of the codiceCpv property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodiceCpv(String value) {
                this.codiceCpv = value;
            }

            /**
             * Gets the value of the importo property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImporto() {
                return importo;
            }

            /**
             * Sets the value of the importo property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImporto(BigDecimal value) {
                this.importo = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="numero_provvisorio" type="{}OnlyNumMax18"/>
         *         &lt;element name="importo_provvisorio">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *               &lt;totalDigits value="15"/>
         *               &lt;fractionDigits value="2"/>
         *               &lt;minInclusive value="0.01"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "numeroProvvisorio",
            "importoProvvisorio"
        })
        public static class Sospeso {

            @XmlElement(name = "numero_provvisorio")
            protected long numeroProvvisorio;
            @XmlElement(name = "importo_provvisorio", required = true)
            protected BigDecimal importoProvvisorio;

            /**
             * Gets the value of the numeroProvvisorio property.
             * 
             */
            public long getNumeroProvvisorio() {
                return numeroProvvisorio;
            }

            /**
             * Sets the value of the numeroProvvisorio property.
             * 
             */
            public void setNumeroProvvisorio(long value) {
                this.numeroProvvisorio = value;
            }

            /**
             * Gets the value of the importoProvvisorio property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getImportoProvvisorio() {
                return importoProvvisorio;
            }

            /**
             * Sets the value of the importoProvvisorio property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setImportoProvvisorio(BigDecimal value) {
                this.importoProvvisorio = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="soggetto_destinatario_delle_spese">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="A CARICO ENTE"/>
         *               &lt;enumeration value="A CARICO BENEFICIARIO"/>
         *               &lt;enumeration value="ESENTE"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="natura_pagamento" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="causale_esenzione_spese" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="0"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "soggettoDestinatarioDelleSpese",
            "naturaPagamento",
            "causaleEsenzioneSpese"
        })
        public static class Spese {

            @XmlElement(name = "soggetto_destinatario_delle_spese", required = true)
            protected String soggettoDestinatarioDelleSpese;
            @XmlElement(name = "natura_pagamento")
            protected String naturaPagamento;
            @XmlElement(name = "causale_esenzione_spese")
            protected String causaleEsenzioneSpese;

            /**
             * Gets the value of the soggettoDestinatarioDelleSpese property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSoggettoDestinatarioDelleSpese() {
                return soggettoDestinatarioDelleSpese;
            }

            /**
             * Sets the value of the soggettoDestinatarioDelleSpese property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSoggettoDestinatarioDelleSpese(String value) {
                this.soggettoDestinatarioDelleSpese = value;
            }

            /**
             * Gets the value of the naturaPagamento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaturaPagamento() {
                return naturaPagamento;
            }

            /**
             * Sets the value of the naturaPagamento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaturaPagamento(String value) {
                this.naturaPagamento = value;
            }

            /**
             * Gets the value of the causaleEsenzioneSpese property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCausaleEsenzioneSpese() {
                return causaleEsenzioneSpese;
            }

            /**
             * Sets the value of the causaleEsenzioneSpese property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCausaleEsenzioneSpese(String value) {
                this.causaleEsenzioneSpese = value;
            }

        }

    }

}
