//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 09:58:11 AM CEST 
//


package it.cnr.contab.doccont00.intcass.xmlbnl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * struttura piazzatura, da valorizzare nel caso il tipo_pagamento="BONIFICO BANCARIO E POSTALE"
 * 
 * <p>Java class for piazzatura complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="piazzatura">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="abi_beneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="99999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cab_beneficiario" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="99999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numero_conto_corrente_beneficiario">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="12"/>
 *               &lt;pattern value="[0-9a-zA-Z,/, ,.,\-]{1,12}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="caratteri_controllo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codice_cin" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="codice_paese" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *               &lt;pattern value="\c{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="denominazione_banca_destinataria" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "piazzatura", propOrder = {
    "abiBeneficiario",
    "cabBeneficiario",
    "numeroContoCorrenteBeneficiario",
    "caratteriControllo",
    "codiceCin",
    "codicePaese",
    "denominazioneBancaDestinataria"
})
public class Piazzatura {

    @XmlElement(name = "abi_beneficiario")
    protected Integer abiBeneficiario;
    @XmlElement(name = "cab_beneficiario")
    protected Integer cabBeneficiario;
    @XmlElement(name = "numero_conto_corrente_beneficiario", required = true)
    protected String numeroContoCorrenteBeneficiario;
    @XmlElement(name = "caratteri_controllo")
    protected String caratteriControllo;
    @XmlElement(name = "codice_cin")
    protected String codiceCin;
    @XmlElement(name = "codice_paese", defaultValue = "IT")
    protected String codicePaese;
    @XmlElement(name = "denominazione_banca_destinataria")
    protected String denominazioneBancaDestinataria;

    /**
     * Gets the value of the abiBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAbiBeneficiario() {
        return abiBeneficiario;
    }

    /**
     * Sets the value of the abiBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAbiBeneficiario(Integer value) {
        this.abiBeneficiario = value;
    }

    /**
     * Gets the value of the cabBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCabBeneficiario() {
        return cabBeneficiario;
    }

    /**
     * Sets the value of the cabBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCabBeneficiario(Integer value) {
        this.cabBeneficiario = value;
    }

    /**
     * Gets the value of the numeroContoCorrenteBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroContoCorrenteBeneficiario() {
        return numeroContoCorrenteBeneficiario;
    }

    /**
     * Sets the value of the numeroContoCorrenteBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroContoCorrenteBeneficiario(String value) {
        this.numeroContoCorrenteBeneficiario = value;
    }

    /**
     * Gets the value of the caratteriControllo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaratteriControllo() {
        return caratteriControllo;
    }

    /**
     * Sets the value of the caratteriControllo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaratteriControllo(String value) {
        this.caratteriControllo = value;
    }

    /**
     * Gets the value of the codiceCin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceCin() {
        return codiceCin;
    }

    /**
     * Sets the value of the codiceCin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceCin(String value) {
        this.codiceCin = value;
    }

    /**
     * Gets the value of the codicePaese property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodicePaese() {
        return codicePaese;
    }

    /**
     * Sets the value of the codicePaese property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodicePaese(String value) {
        this.codicePaese = value;
    }

    /**
     * Gets the value of the denominazioneBancaDestinataria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominazioneBancaDestinataria() {
        return denominazioneBancaDestinataria;
    }

    /**
     * Sets the value of the denominazioneBancaDestinataria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominazioneBancaDestinataria(String value) {
        this.denominazioneBancaDestinataria = value;
    }

}
