/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.16 at 09:58:11 AM CEST 
//


package it.cnr.contab.doccont00.intcass.xmlbnl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Da utilizzare con il tipo_operazione SOSTITUZIONE
 * 
 * <p>Java class for sostituzione_reversale complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sostituzione_reversale">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numero_reversale_da_sostituire" type="{}OnlyNumMax7"/>
 *         &lt;element name="progressivo_versante_da_sostituire" type="{}OnlyNumMax7"/>
 *         &lt;element name="esercizio_reversale_da_sostituire">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;minInclusive value="1999"/>
 *               &lt;maxInclusive value="2099"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sostituzione_reversale", propOrder = {
    "numeroReversaleDaSostituire",
    "progressivoVersanteDaSostituire",
    "esercizioReversaleDaSostituire"
})
public class SostituzioneReversale {

    @XmlElement(name = "numero_reversale_da_sostituire")
    protected int numeroReversaleDaSostituire;
    @XmlElement(name = "progressivo_versante_da_sostituire")
    protected int progressivoVersanteDaSostituire;
    @XmlElement(name = "esercizio_reversale_da_sostituire")
    protected int esercizioReversaleDaSostituire;

    /**
     * Gets the value of the numeroReversaleDaSostituire property.
     * 
     */
    public int getNumeroReversaleDaSostituire() {
        return numeroReversaleDaSostituire;
    }

    /**
     * Sets the value of the numeroReversaleDaSostituire property.
     * 
     */
    public void setNumeroReversaleDaSostituire(int value) {
        this.numeroReversaleDaSostituire = value;
    }

    /**
     * Gets the value of the progressivoVersanteDaSostituire property.
     * 
     */
    public int getProgressivoVersanteDaSostituire() {
        return progressivoVersanteDaSostituire;
    }

    /**
     * Sets the value of the progressivoVersanteDaSostituire property.
     * 
     */
    public void setProgressivoVersanteDaSostituire(int value) {
        this.progressivoVersanteDaSostituire = value;
    }

    /**
     * Gets the value of the esercizioReversaleDaSostituire property.
     * 
     */
    public int getEsercizioReversaleDaSostituire() {
        return esercizioReversaleDaSostituire;
    }

    /**
     * Sets the value of the esercizioReversaleDaSostituire property.
     * 
     */
    public void setEsercizioReversaleDaSostituire(int value) {
        this.esercizioReversaleDaSostituire = value;
    }

}
