-- CREATE TABLESPACE
CREATE TABLESPACE tbs_01 DATAFILE 'tbs_f2.dbf' SIZE 500M ONLINE;

-- USER SQL
CREATE USER "PCIR009" identified by dbform
DEFAULT TABLESPACE "TBS_01"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK;

-- QUOTAS
ALTER USER "PCIR009" QUOTA UNLIMITED ON TBS_01;

-- ROLES
GRANT CONNECT, RESOURCE TO "PCIR009";

-- SYSTEM PRIVILEGES
GRANT CREATE ANY VIEW TO "PCIR009" WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO "PCIR009";
GRANT EXECUTE ON DBMS_PIPE TO "PCIR009";
