-- CREATE TABLESPACE
CREATE TABLESPACE tbs_01 DATAFILE 'tbs_f2.dbf' SIZE 500M ONLINE;

-- USER SQL
CREATE USER "SIGLA" identified by siglapw
DEFAULT TABLESPACE "TBS_01"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK;

-- QUOTAS
ALTER USER "SIGLA" QUOTA UNLIMITED ON TBS_01;

-- ROLES
GRANT CONNECT, RESOURCE TO "SIGLA";

-- SYSTEM PRIVILEGES
GRANT CREATE ANY VIEW TO "SIGLA" WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO "SIGLA";
GRANT EXECUTE ON DBMS_PIPE TO "SIGLA";

