// ***************************************************************
// *
// *                    ITipoCaricoScaricoMgr.java Generated by
// *                 Computer Associates International, Inc.
// *
// *    Class: ITipoCaricoScaricoMgr
// *    Package: it.cnr.contab.inventario00.comp
// *    Date:  06-Feb-02 18:55:34
// *    User:  cnr011
// *
// *    Copyright 2000, Computer Associates International, Inc.
// *    All rights reserved.
// *
// ***************************************************************
// *
// * Change History
// *
// * Initials    Date       Comments
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------
// *|        |            |
// *+--------+------------+--------------------------------------------------

package it.cnr.contab.inventario00.comp;
import it.cnr.jada.UserContext;
import it.cnr.jada.bulk.OggettoBulk;
import it.cnr.jada.comp.ComponentException;
import it.cnr.jada.comp.ICRUDMgr;
public interface ITipoCaricoScaricoMgr extends ICRUDMgr
{





/** 
  * Eliminazione di un tipo di Movimento
  *    PreCondition:
  *      E' stata generata la richiesta di eliminazione di un tipo di Movimento Carico/Scarico dell'Inventario.
  *    PostCondition:
  *      La cancellazione è solo logica, quindi viene aggiornato il record sul DB relativo 
  *		al movimento di riferimento, impostando la data di cancellazione uguale al TimeStamp.
  *
  * @param userContext lo <code>UserContext</code> che ha generato la richiesta
  * @param bulk <code>OggettoBulk</code> il Bulk da eliminare
  *
  * @return bulk l'oggetto <code>OggettoBulk</code> creato
**/

public abstract void eliminaConBulk(it.cnr.jada.UserContext param0,it.cnr.jada.bulk.OggettoBulk param1) throws it.cnr.jada.comp.ComponentException;
}