/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.12 at 02:57:51 PM CET 
//


package it.cnr.contab.incarichi00.xmlfp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.cnr.contab.incarichi00.xmlfp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.cnr.contab.incarichi00.xmlfp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.CancellaIncarico }
     * 
     */
    public Comunicazione.Dipendenti.CancellaIncarico createComunicazioneDipendentiCancellaIncarico() {
        return new Comunicazione.Dipendenti.CancellaIncarico();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.SaldoIncarico.ModificaPagamento }
     * 
     */
    public Comunicazione.Dipendenti.SaldoIncarico.ModificaPagamento createComunicazioneDipendentiSaldoIncaricoModificaPagamento() {
        return new Comunicazione.Dipendenti.SaldoIncarico.ModificaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.SaldoIncarico }
     * 
     */
    public EsitoComunicazione.Consulenti.SaldoIncarico createEsitoComunicazioneConsulentiSaldoIncarico() {
        return new EsitoComunicazione.Consulenti.SaldoIncarico();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.SaldoIncarico }
     * 
     */
    public Comunicazione.Dipendenti.SaldoIncarico createComunicazioneDipendentiSaldoIncarico() {
        return new Comunicazione.Dipendenti.SaldoIncarico();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.NuovoIncarico.NuovoPagamento }
     * 
     */
    public Comunicazione.Consulenti.NuovoIncarico.NuovoPagamento createComunicazioneConsulentiNuovoIncaricoNuovoPagamento() {
        return new Comunicazione.Consulenti.NuovoIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.NuovoIncarico }
     * 
     */
    public Comunicazione.Dipendenti.NuovoIncarico createComunicazioneDipendentiNuovoIncarico() {
        return new Comunicazione.Dipendenti.NuovoIncarico();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.SaldoIncarico.ModificaPagamento }
     * 
     */
    public EsitoComunicazione.Dipendenti.SaldoIncarico.ModificaPagamento createEsitoComunicazioneDipendentiSaldoIncaricoModificaPagamento() {
        return new EsitoComunicazione.Dipendenti.SaldoIncarico.ModificaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.NuovoIncarico.NuovoPagamento }
     * 
     */
    public EsitoComunicazione.Dipendenti.NuovoIncarico.NuovoPagamento createEsitoComunicazioneDipendentiNuovoIncaricoNuovoPagamento() {
        return new EsitoComunicazione.Dipendenti.NuovoIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.NuovoIncarico }
     * 
     */
    public Comunicazione.Consulenti.NuovoIncarico createComunicazioneConsulentiNuovoIncarico() {
        return new Comunicazione.Consulenti.NuovoIncarico();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.ModificaIncarico }
     * 
     */
    public Comunicazione.Consulenti.ModificaIncarico createComunicazioneConsulentiModificaIncarico() {
        return new Comunicazione.Consulenti.ModificaIncarico();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.ModificaIncarico.NuovoPagamento }
     * 
     */
    public EsitoComunicazione.Consulenti.ModificaIncarico.NuovoPagamento createEsitoComunicazioneConsulentiModificaIncaricoNuovoPagamento() {
        return new EsitoComunicazione.Consulenti.ModificaIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.ModificaIncarico.NuovoPagamento }
     * 
     */
    public EsitoComunicazione.Dipendenti.ModificaIncarico.NuovoPagamento createEsitoComunicazioneDipendentiModificaIncaricoNuovoPagamento() {
        return new EsitoComunicazione.Dipendenti.ModificaIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.ModificaIncarico.ModificaPagamento }
     * 
     */
    public Comunicazione.Dipendenti.ModificaIncarico.ModificaPagamento createComunicazioneDipendentiModificaIncaricoModificaPagamento() {
        return new Comunicazione.Dipendenti.ModificaIncarico.ModificaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti }
     * 
     */
    public EsitoComunicazione.Dipendenti createEsitoComunicazioneDipendenti() {
        return new EsitoComunicazione.Dipendenti();
    }

    /**
     * Create an instance of {@link EsitoComunicazione }
     * 
     */
    public EsitoComunicazione createEsitoComunicazione() {
        return new EsitoComunicazione();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.SaldoIncarico }
     * 
     */
    public EsitoComunicazione.Dipendenti.SaldoIncarico createEsitoComunicazioneDipendentiSaldoIncarico() {
        return new EsitoComunicazione.Dipendenti.SaldoIncarico();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.ModificaIncarico }
     * 
     */
    public EsitoComunicazione.Consulenti.ModificaIncarico createEsitoComunicazioneConsulentiModificaIncarico() {
        return new EsitoComunicazione.Consulenti.ModificaIncarico();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.ModificaIncarico.NuovoPagamento }
     * 
     */
    public Comunicazione.Dipendenti.ModificaIncarico.NuovoPagamento createComunicazioneDipendentiModificaIncaricoNuovoPagamento() {
        return new Comunicazione.Dipendenti.ModificaIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.ModificaIncarico.ModificaPagamento }
     * 
     */
    public Comunicazione.Consulenti.ModificaIncarico.ModificaPagamento createComunicazioneConsulentiModificaIncaricoModificaPagamento() {
        return new Comunicazione.Consulenti.ModificaIncarico.ModificaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.SaldoIncarico.NuovoPagamento }
     * 
     */
    public EsitoComunicazione.Consulenti.SaldoIncarico.NuovoPagamento createEsitoComunicazioneConsulentiSaldoIncaricoNuovoPagamento() {
        return new EsitoComunicazione.Consulenti.SaldoIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.NuovoIncarico.NuovoPagamento }
     * 
     */
    public EsitoComunicazione.Consulenti.NuovoIncarico.NuovoPagamento createEsitoComunicazioneConsulentiNuovoIncaricoNuovoPagamento() {
        return new EsitoComunicazione.Consulenti.NuovoIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.NuovoIncarico.IncaricatoAzienda }
     * 
     */
    public Comunicazione.Consulenti.NuovoIncarico.IncaricatoAzienda createComunicazioneConsulentiNuovoIncaricoIncaricatoAzienda() {
        return new Comunicazione.Consulenti.NuovoIncarico.IncaricatoAzienda();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.NuovoIncarico }
     * 
     */
    public EsitoComunicazione.Consulenti.NuovoIncarico createEsitoComunicazioneConsulentiNuovoIncarico() {
        return new EsitoComunicazione.Consulenti.NuovoIncarico();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.CancellaIncarico }
     * 
     */
    public EsitoComunicazione.Consulenti.CancellaIncarico createEsitoComunicazioneConsulentiCancellaIncarico() {
        return new EsitoComunicazione.Consulenti.CancellaIncarico();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.CancellaIncarico }
     * 
     */
    public EsitoComunicazione.Dipendenti.CancellaIncarico createEsitoComunicazioneDipendentiCancellaIncarico() {
        return new EsitoComunicazione.Dipendenti.CancellaIncarico();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.NuovoIncarico.IncaricatoAzienda }
     * 
     */
    public EsitoComunicazione.Consulenti.NuovoIncarico.IncaricatoAzienda createEsitoComunicazioneConsulentiNuovoIncaricoIncaricatoAzienda() {
        return new EsitoComunicazione.Consulenti.NuovoIncarico.IncaricatoAzienda();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.ModificaIncarico.ModificaPagamento }
     * 
     */
    public EsitoComunicazione.Consulenti.ModificaIncarico.ModificaPagamento createEsitoComunicazioneConsulentiModificaIncaricoModificaPagamento() {
        return new EsitoComunicazione.Consulenti.ModificaIncarico.ModificaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Errore }
     * 
     */
    public EsitoComunicazione.Errore createEsitoComunicazioneErrore() {
        return new EsitoComunicazione.Errore();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.SaldoIncarico.CancellaPagamento }
     * 
     */
    public Comunicazione.Dipendenti.SaldoIncarico.CancellaPagamento createComunicazioneDipendentiSaldoIncaricoCancellaPagamento() {
        return new Comunicazione.Dipendenti.SaldoIncarico.CancellaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.ModificaIncarico.CancellaPagamento }
     * 
     */
    public EsitoComunicazione.Consulenti.ModificaIncarico.CancellaPagamento createEsitoComunicazioneConsulentiModificaIncaricoCancellaPagamento() {
        return new EsitoComunicazione.Consulenti.ModificaIncarico.CancellaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.SaldoIncarico.CancellaPagamento }
     * 
     */
    public EsitoComunicazione.Dipendenti.SaldoIncarico.CancellaPagamento createEsitoComunicazioneDipendentiSaldoIncaricoCancellaPagamento() {
        return new EsitoComunicazione.Dipendenti.SaldoIncarico.CancellaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.NuovoIncarico }
     * 
     */
    public EsitoComunicazione.Dipendenti.NuovoIncarico createEsitoComunicazioneDipendentiNuovoIncarico() {
        return new EsitoComunicazione.Dipendenti.NuovoIncarico();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.NuovoIncarico.IncaricatoPersona }
     * 
     */
    public EsitoComunicazione.Consulenti.NuovoIncarico.IncaricatoPersona createEsitoComunicazioneConsulentiNuovoIncaricoIncaricatoPersona() {
        return new EsitoComunicazione.Consulenti.NuovoIncarico.IncaricatoPersona();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.ModificaIncarico.ModificaPagamento }
     * 
     */
    public EsitoComunicazione.Dipendenti.ModificaIncarico.ModificaPagamento createEsitoComunicazioneDipendentiModificaIncaricoModificaPagamento() {
        return new EsitoComunicazione.Dipendenti.ModificaIncarico.ModificaPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.CancellaIncarico }
     * 
     */
    public Comunicazione.Consulenti.CancellaIncarico createComunicazioneConsulentiCancellaIncarico() {
        return new Comunicazione.Consulenti.CancellaIncarico();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.ModificaIncarico }
     * 
     */
    public EsitoComunicazione.Dipendenti.ModificaIncarico createEsitoComunicazioneDipendentiModificaIncarico() {
        return new EsitoComunicazione.Dipendenti.ModificaIncarico();
    }

    /**
     * Create an instance of {@link Comunicazione }
     * 
     */
    public Comunicazione createComunicazione() {
        return new Comunicazione();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.SaldoIncarico.ModificaPagamento }
     * 
     */
    public Comunicazione.Consulenti.SaldoIncarico.ModificaPagamento createComunicazioneConsulentiSaldoIncaricoModificaPagamento() {
        return new Comunicazione.Consulenti.SaldoIncarico.ModificaPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.ModificaIncarico }
     * 
     */
    public Comunicazione.Dipendenti.ModificaIncarico createComunicazioneDipendentiModificaIncarico() {
        return new Comunicazione.Dipendenti.ModificaIncarico();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.NuovoIncarico.Dipendente }
     * 
     */
    public Comunicazione.Dipendenti.NuovoIncarico.Dipendente createComunicazioneDipendentiNuovoIncaricoDipendente() {
        return new Comunicazione.Dipendenti.NuovoIncarico.Dipendente();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti }
     * 
     */
    public Comunicazione.Consulenti createComunicazioneConsulenti() {
        return new Comunicazione.Consulenti();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.NuovoIncarico.NuovoPagamento }
     * 
     */
    public Comunicazione.Dipendenti.NuovoIncarico.NuovoPagamento createComunicazioneDipendentiNuovoIncaricoNuovoPagamento() {
        return new Comunicazione.Dipendenti.NuovoIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.SaldoIncarico }
     * 
     */
    public Comunicazione.Consulenti.SaldoIncarico createComunicazioneConsulentiSaldoIncarico() {
        return new Comunicazione.Consulenti.SaldoIncarico();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.SaldoIncarico.CancellaPagamento }
     * 
     */
    public Comunicazione.Consulenti.SaldoIncarico.CancellaPagamento createComunicazioneConsulentiSaldoIncaricoCancellaPagamento() {
        return new Comunicazione.Consulenti.SaldoIncarico.CancellaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.ModificaIncarico.CancellaPagamento }
     * 
     */
    public EsitoComunicazione.Dipendenti.ModificaIncarico.CancellaPagamento createEsitoComunicazioneDipendentiModificaIncaricoCancellaPagamento() {
        return new EsitoComunicazione.Dipendenti.ModificaIncarico.CancellaPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti }
     * 
     */
    public Comunicazione.Dipendenti createComunicazioneDipendenti() {
        return new Comunicazione.Dipendenti();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti }
     * 
     */
    public EsitoComunicazione.Consulenti createEsitoComunicazioneConsulenti() {
        return new EsitoComunicazione.Consulenti();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.NuovoIncarico.Dipendente }
     * 
     */
    public EsitoComunicazione.Dipendenti.NuovoIncarico.Dipendente createEsitoComunicazioneDipendentiNuovoIncaricoDipendente() {
        return new EsitoComunicazione.Dipendenti.NuovoIncarico.Dipendente();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.ModificaIncarico.NuovoPagamento }
     * 
     */
    public Comunicazione.Consulenti.ModificaIncarico.NuovoPagamento createComunicazioneConsulentiModificaIncaricoNuovoPagamento() {
        return new Comunicazione.Consulenti.ModificaIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.NuovoIncarico.IncaricatoPersona }
     * 
     */
    public Comunicazione.Consulenti.NuovoIncarico.IncaricatoPersona createComunicazioneConsulentiNuovoIncaricoIncaricatoPersona() {
        return new Comunicazione.Consulenti.NuovoIncarico.IncaricatoPersona();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.SaldoIncarico.NuovoPagamento }
     * 
     */
    public Comunicazione.Dipendenti.SaldoIncarico.NuovoPagamento createComunicazioneDipendentiSaldoIncaricoNuovoPagamento() {
        return new Comunicazione.Dipendenti.SaldoIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.ModificaIncarico.CancellaPagamento }
     * 
     */
    public Comunicazione.Consulenti.ModificaIncarico.CancellaPagamento createComunicazioneConsulentiModificaIncaricoCancellaPagamento() {
        return new Comunicazione.Consulenti.ModificaIncarico.CancellaPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Dipendenti.ModificaIncarico.CancellaPagamento }
     * 
     */
    public Comunicazione.Dipendenti.ModificaIncarico.CancellaPagamento createComunicazioneDipendentiModificaIncaricoCancellaPagamento() {
        return new Comunicazione.Dipendenti.ModificaIncarico.CancellaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.SaldoIncarico.CancellaPagamento }
     * 
     */
    public EsitoComunicazione.Consulenti.SaldoIncarico.CancellaPagamento createEsitoComunicazioneConsulentiSaldoIncaricoCancellaPagamento() {
        return new EsitoComunicazione.Consulenti.SaldoIncarico.CancellaPagamento();
    }

    /**
     * Create an instance of {@link Comunicazione.Consulenti.SaldoIncarico.NuovoPagamento }
     * 
     */
    public Comunicazione.Consulenti.SaldoIncarico.NuovoPagamento createComunicazioneConsulentiSaldoIncaricoNuovoPagamento() {
        return new Comunicazione.Consulenti.SaldoIncarico.NuovoPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Consulenti.SaldoIncarico.ModificaPagamento }
     * 
     */
    public EsitoComunicazione.Consulenti.SaldoIncarico.ModificaPagamento createEsitoComunicazioneConsulentiSaldoIncaricoModificaPagamento() {
        return new EsitoComunicazione.Consulenti.SaldoIncarico.ModificaPagamento();
    }

    /**
     * Create an instance of {@link EsitoComunicazione.Dipendenti.SaldoIncarico.NuovoPagamento }
     * 
     */
    public EsitoComunicazione.Dipendenti.SaldoIncarico.NuovoPagamento createEsitoComunicazioneDipendentiSaldoIncaricoNuovoPagamento() {
        return new EsitoComunicazione.Dipendenti.SaldoIncarico.NuovoPagamento();
    }

}
