//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.12 at 02:57:51 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.anagrafeprestazioni.it/comunicazionexml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.cnr.contab.incarichi00.xmlfp;
