/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package it.cnr.contab.docamm00.bp;

import it.cnr.contab.docamm00.docs.bulk.Filtro_ricerca_obbligazioniVBulk;
import it.cnr.contab.docamm00.docs.bulk.IDocumentoAmministrativoBulk;
import it.cnr.contab.doccont00.core.bulk.Accertamento_scadenzarioBulk;
import it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk;
import it.cnr.jada.UserContext;
import it.cnr.jada.action.ActionContext;
import it.cnr.jada.action.BusinessProcessException;
import it.cnr.jada.bulk.OggettoBulk;
import it.cnr.jada.ejb.CRUDComponentSession;
import it.cnr.jada.persistency.sql.CompoundFindClause;
import it.cnr.jada.util.RemoteIterator;

/**
 * Insert the type's description here.
 * Creation date: (12/3/2001 10:05:28 AM)
 *
 * @author: CNRADM
 */
public interface IDocumentoAmministrativoBP {
    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    CRUDComponentSession createComponentSession() throws BusinessProcessException;

    RemoteIterator findObbligazioni(UserContext context, Filtro_ricerca_obbligazioniVBulk filtro) throws BusinessProcessException;

    RemoteIterator findObbligazioniAttributes(ActionContext actionContext, CompoundFindClause clauses, OggettoBulk bulk, OggettoBulk context, String property) throws it.cnr.jada.action.BusinessProcessException;

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    Accertamento_scadenzarioBulk getAccertamento_scadenziario_corrente();

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    IDocumentoAmministrativoBulk getBringBackDocAmm();

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    it.cnr.contab.docamm00.docs.bulk.Risultato_eliminazioneVBulk getDeleteManager();

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    IDocumentoAmministrativoBulk getDocumentoAmministrativoCorrente();

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    Obbligazione_scadenzarioBulk getObbligazione_scadenziario_corrente();

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    boolean isAutoGenerated();

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    boolean isDeleting();

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    boolean isManualModify();

    /**
     * Insert the method's description here.
     * Creation date: (12/3/2001 10:21:14 AM)
     *
     * @return it.cnr.contab.doccont00.core.bulk.Obbligazione_scadenzarioBulk
     */
    void setIsDeleting(boolean newIsDeleting);

    void validaObbligazionePerDocAmm(ActionContext actionContext, OggettoBulk bulk) throws BusinessProcessException;
}
